### ISSUE TITLE
Amplify Console GitHub check stuck at 'Expected — Waiting for status to be reported'

### ISSUE THREAD

**Issue by no-creative-name** [aws-amplify/amplify-hosting#1183]
**Setup**
We setup up Amplify Console with branch autodetection for our feature branches. Additionally we added branch restrictions to only be able to merge PRs when the Amplify build check runs through.

**Expected behaviour**
Previews are deployed for the feature branches and when they are successful, the check in the accompanying PR is allowing us to merge.

**Current behaviour**
Previews are deployed successfully for the feature branches, but the Amplify Console check is stuck at 'Expected — Waiting for status to be reported', preventing us to merge the PRs.

App id: d3s356iomuxmyu

**Comment by gwryssekk** [comment]
Thanks, @no-creative-name -- we'll investigate.

**Comment by Mhm0ud** [comment]
I am seeing this same behavior if a commit is pushed to the repository, triggering another build while the last build hasn't finished yet. The check never finishes despite the build actually completing in amplify.

**Comment by victorccccc** [comment]
Sorry for the inconvenience, we've fixed this issue. Feel free to reopen if issue persists
