### ISSUE TITLE
Can't see changes in the PWA app after deploy until clearing the cache.

### ISSUE THREAD

**Issue by shayelbaz1** [aws-amplify/amplify-hosting#1238]
After I do deploy I can't see the changes until I clear the cache in the phone.

I can't see any changes for a long time on the domain and on the downloaded PWA app to the Home Screen the version stays the same.

How to fix it?
How to see the changes?

additional details:
PWA Build with VUEjs

**Comment by kahdojay** [comment]
@shayelbaz1 do you have performance mode enabled?
https://docs.aws.amazon.com/amplify/latest/userguide/ttl.html

If so try turning it off for instant cache validation. If not please provide appId / region / branchname and we can take a closer look.

**Comment by shayelbaz1** [comment]
Hi, performance mode is not enabled.
app: *bitin_wallet*
region:
Europe (Frankfurt)eu-central-1
<https://eu-central-1.console.aws.amazon.com/amplify/home?region=eu-central-1#/d3o18v3n6w795f>

 branchname : master

How do I find the appId?

**Comment by Jay2113** [comment]
Hi @shayelbaz1 👋 , thanks for your continued patience and we apologize for the delayed response on this thread.

Can you confirm if you are still running into this behavior where the code changes are not being deployed instantly?
