### ISSUE TITLE
Failed to load resource: the server responded with a status of 403

### ISSUE THREAD

**Issue by yoyokalin** [aws-amplify/amplify-hosting#1287]
Hi,
I use amplify publish to publish my site to dev server (https://dev.d23nf6vy****.amplifyapp.com). In cli it shows 
√ Zipping artifacts completed.
√ Deployment complete!
https://dev.d23nf6vy****.amplifyapp.com

But I can not go to this page. It shows error

Failed to load resource: the server responded with a status of 403 ()
/themes/saga-blue/theme.css/:1 Failed to load resource: the server responded with a status of 403 ()
/static/js/2.0bc2cba8.chunk.js/:1 Failed to load resource: the server responded with a status of 403 ()
/static/css/2.bc5dc115.chunk.css/:1 Failed to load resource: the server responded with a status of 403 ()
/static/js/2.0bc2cba8.chunk.js/:1 Failed to load resource: the server responded with a status of 403 ()
dev.d23nf6vy****.amplifyapp.com/:1 Failed to load resource: the server responded with a status of 403 ()
dev.d23nf6vy****.amplifyapp.com/:1 Failed to load resource: the server responded with a status of 403 ()
devd23nf6vy****.amplifyapp.com/:1 Failed to load resource: the server responded with a status of 403 ()

Please help me how to fix!

**Comment by ganipcanot** [comment]
Could you please share your appId and region?

**Comment by yoyokalin** [comment]
Hi,
My  appId d23nf6vykic0li,
Region: us-east-1
BR

**Comment by yoyokalin** [comment]
Hi,
After updating amplify cli, when add dev hosting, I encounter
× Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
An error occurred during the publish operation

Please help me!

**Comment by jjanczur** [comment]
Hi, 
how did you solve your issue? I guess it's some kind of misconfiguration. I'm having a similar issue

**Comment by swaminator** [comment]
Closing this task and tracking publish errors in https://github.com/aws-amplify/amplify-hosting/issues/1463
