### ISSUE TITLE
Chinese characters can not be correctly displayed in the Verify tab

### ISSUE THREAD

**Issue by qxzzxq** [aws-amplify/amplify-hosting#1289]
**Describe the bug**
Chinese characters (or maybe other UTF-8 characters) can not be correctly displayed in the **Verify** tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/17144939/100367772-03b28b80-3003-11eb-9b34-4a8431e35baa.png)

![image](https://user-images.githubusercontent.com/17144939/100367840-1a58e280-3003-11eb-9fee-99853cce6ba4.png)

**Comment by kahdojay** [comment]
Thanks for reporting this, we'll need to update our screenshot service to handle this.

**Comment by hloriana** [comment]
We have removed the Verify feature from the Amplify console for the time being.
