### ISSUE TITLE
Gatsby Default Starter Auth signup bug

### ISSUE THREAD

**Issue by litwicki** [aws-amplify/amplify-hosting#1336]
**Describe the bug**
Sample app: https://github.com/aws-samples/aws-amplify-gatsby-auth
Signup error message on gatsby auth sample is misleading. 

**To Reproduce**
1. https://master.d2q2cbdzve9k5c.amplifyapp.com/app/signup
2. Enter a basic insecure password
3. Error message presented is

`errorMessage: {
 "code": "InvalidParameterException",
 "name": "InvalidParameterException",
 "message": "Username could not be created. Please make sure that the username you have entered is between 1 and 128 characters."
}`

**Expected behavior**
Actual error message:
`{__type: "InvalidParameterException",…}
message: "1 validation error detected: Value at 'password' failed to satisfy constraint: Member must have length greater than or equal to 6"
__type: "InvalidParameterException"`

**Screenshots**

**Comment by Jay2113** [comment]
Hi @litwicki, we have deprecated the Amplify Console starter apps and are no longer maintaining it. We have also archived the related GitHub repositories.
