### ISSUE TITLE
Feature request: Merged build previews

### ISSUE THREAD

**Issue by theelk801** [aws-amplify/amplify-hosting#1360]
As far as I can tell, a PR's preview is only based on the source branch's code and not on what the result of merging the PR into the target branch would give. Given that other PRs could be merged into the target branch in the meantime, I'd like to have build previews that show, assuming no merge conflicts, how changes in the target branch could affect the preview without necessarily having to merge the target branch back into the source branch first. I know services like Travis-CI offer this for their tests.

Thanks

**Comment by ganipcanot** [comment]
Maybe I don't fully understand the request could you help me understand?

As it stands currently if you have your mainline branch say `main` which is just a static HTML page with "Hello" on it.

And you're working on `coolnewfeature` branch configured for previews against `main`.

When you make a text change on `coolnewfeature` to change "Hello" to "Hello World" and submit it for preview it will build on top of `main` and display "Hello World".

That is already the default behavior for PR previews.  Am I misunderstanding your request?

**Comment by theelk801** [comment]
What if I have a branch called `anothernewfeature` that changes something else and I merge it before merging `coolnewfeature`, and then I push something new to `coolnewfeature`?

**Comment by ganipcanot** [comment]
This sounds like something that can be solved with the following git workflow:

You can to rebase `coolnewfeature` against `main` to get the latest changes from `anothernewfeature` which was checked into `main`.

Then once you do that you can push changes to `coolnewfeature` which would have both changes.

**So the workflow would be:**
1. Check-in `anothernewfeature` changes
2. `git pull` to get latest changes in `main` branch
3. Rebase `coolnewfeature` against `main`
4. Add whatever new changes to `coolnewfeature` locally
5. Push `coolnewfeature` changes to your git repo on github so PR previews would pickup the changes.
