### ISSUE TITLE
when removing custom domain the redirects do not go away

### ISSUE THREAD

**Issue by alisade** [aws-amplify/amplify-hosting#1410]
**Describe the bug**
When a custom domain is removed the redirect are not deleted, as a result when the domain is added back those redirect automatically show up even though you uncheck the redirects (for example for www)

**To Reproduce**
1. create a custom domain with redirects
2. remove it
3. redirect will still be there

**Expected behavior**
redirects should be removed

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chdome
 - Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by hsspain** [comment]
@alisade Thank you for the feedback. We will add this to our backlog and prioritize it for resolution.

**Comment by junyaogz** [comment]
bug still exists

**Comment by GlenWise** [comment]
Agreed, we're still having this issue

**Comment by prestonwrthompson** [comment]
I was having this problem as well and it is still an issue. However, it can be fixed with a workaround, just not on the `App Settings` > `Domain management` page. Instead, on the `App Settings` > `Rewrites and redirects` page you can remove the redirect.

**Comment by nadetastic** [comment]
Following up on this issue here, the redirect settings will be found under `App Settings` > `Rewrites and redirects` sections as mentioned by @prestonwrthompson above.

Marking this issue as closed.
