### ISSUE TITLE
Merge doesn't trigger new Deployment - single commit is working

### ISSUE THREAD

**Issue by chkrause** [aws-amplify/amplify-hosting#1500]
When we merge from develop branch to master the deployment isn't triggered.
When we do a commit direct in master branche the commit is recognized and deployment is triggered.

Here you can already find the different events fired from codecomit to SNS:
**Event for merge:**
```
	"Records": [
		{
			"awsRegion": "eu-central-1",
			"codecommit": {
				"references": [
					{
						"commit": "8be857ce6952d0592ed2fe700fd1cd6f90515db7",
						"ref": "refs/heads/develop"
					},
					{
						"commit": "39c28e6accc49c317843ee88c78d20512a82fd76",
						"ref": "refs/heads/master"
					}
				]
			},

```
**Event for single commit**
```
	"Records": [
		{
			"awsRegion": "eu-central-1",
			"codecommit": {
				"references": [
					{
						"commit": "c76f39a77e221bba9af9a063c498fa3f376c7b61",
						"ref": "refs/heads/master"
					}
				]
			},

```

I assume that the references are not correct interpreted by the called endpoint https://tbm3nwvot5.execute-api.eu-central-1.amazonaws.com/Prod/codecommit

**Comment by abhi7cr** [comment]
Hello @chkrause,
We have a fix in the pipeline for this, will let you know once its deployed.

**Comment by treywhite21** [comment]
@abhi7cr Any word on the fix for this? Or any recommended workarounds?

**Comment by palfvin** [comment]
@abhi7cr Not sure if it's the same problem, but my latest [commit](https://github.com/palfvin/vtt-app/commit/460d2a5a506246b8bc53457cbc54d416d6dd2509) hasn't triggered a commit in my [project](https://us-west-2.console.aws.amazon.com/amplify/home?code=42a252506edcc792925e&region=us-west-2#/dc2lkff6c0kar) either. Can you provide a status and or workaround?

**Comment by nadetastic** [comment]
Hi @chkrause @treywhite21 @palfvin - following up here, are you still facing this issue? Let me know, otherwise I will go ahead and mark it as closed.

**Comment by palfvin** [comment]
Sorry, I've pretty much abandoned this app, so couldn't tell you if it's
still a problem. I personally have no objections to closing it.

**Comment by treywhite21** [comment]
Feel free to close. I've switched courses as well.

**Comment by chkrause** [comment]
I’m fine if you close it.
