### ISSUE TITLE
Query params are being cut off with the default redirect rule

### ISSUE THREAD

**Issue by YelyseiLukin** [aws-amplify/amplify-hosting#1510]
Recently, we migrated our front-end from S3 + CloudFront to Amplify, and one of our functions stopped working.

We integrated with a third-party service (TradeStation) and after the successful authentication, it should have redirected us back to our website and provide us the code in query params.
But then we noticed that for some reason all the query params are being cut off and instead of `https://our-website.com/profile?code=XXX` we received simply `https://our-website.com/profile` and therefore it broke our logic.

After a deep investigation, we figured out that it most likely was related to the "Rewrites and redirects" rule that we have by default in our Amplify app. To be precise, this one: `/<*>` -> `/index.html`

I was able to overcome this issue by simply adding an extra slash after the redirect URL that we provide. So the `https://our-website.com/profile/?code=XXX` works fine and doesn't cut of query params.

Please let me know if this solution is how it suppose to work or probably you have some better solution like adjusting the redirect rule or anything else.

Thanks in advance!

**Comment by abhi7cr** [comment]
Hi @YelyseiLukin, thanks for reaching out. I will look at this and get back to you with the recommended solution.

**Comment by tomasswood** [comment]
Is there any movement on this? Unfortunately adding an extra slash is not an option for us.

**Comment by swaminator** [comment]
@tomasswood @YelyseiLukin we just launched support for this: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#query-strings-and-path-parameters. Let us know if this works for you.
