### ISSUE TITLE
Amplify Hosting Release History

### ISSUE THREAD

**Issue by swaminator** [aws-amplify/amplify-hosting#152]
Read about the latest features released by AWS Amplify Hosting: https://github.com/aws-amplify/amplify-hosting/blob/main/CHANGELOG.md

**Comment by pdeva** [comment]
there seem to have been no updates since June 2020. is this project essentially dead?

**Comment by siegerts** [comment]
Hi @pdeva, thanks for reaching out! The project is actively being developed. The most recent development, Admin UI (below), provides a visual interface for frontend web and mobile developers to develop app backends and manage app content outside the AWS Management Console.

- https://docs.amplify.aws/console/adminui/start
- https://docs.amplify.aws/console/adminui/intro
