### ISSUE TITLE
UX — Darkmode not applied splash screen

### ISSUE THREAD

**Issue by omenking** [aws-amplify/amplify-hosting#1565]
<img width="1373" alt="Screen Shot 2021-02-13 at 7 44 59 AM" src="https://user-images.githubusercontent.com/7776/107850311-7431a300-6dcf-11eb-8651-2f69dec6fe91.png">

**Comment by abhi7cr** [comment]
Hi @omenking, thanks for reporting. This would be fixed in the upcoming weeks. Will keep you posted!

**Comment by ganipcanot** [comment]
@omenking Could you confirm your environment?

1. Platform: Windows, Mac?
2. Browser: Chrome, Firefox?

Just to confirm you have dark mode enabled correct?

[Windows instructions](https://www.pcmag.com/how-to/how-to-enable-dark-mode-in-windows-10#:~:text=To%20enable%20dark%20mode%2C%20navigate,and%20the%20built%2Din%20apps.)

[Mac instructions](https://support.apple.com/en-us/HT208976#:~:text=Turn%20on%20Dark%20Mode,the%20dark%20appearance%20at%20night.)

On my end I used windows with Chrome/Firefox and I wasn't seeing the issue (Dark mode seems fine).  Could you re-confirm on your end?

![image](https://user-images.githubusercontent.com/21091073/113445890-7cf42d80-93ab-11eb-84f5-66fa28c7d307.png)

**Comment by calavera** [comment]
This has been fixed already.
