### ISSUE TITLE
Brotli Compression

### ISSUE THREAD

**Issue by berikat** [aws-amplify/amplify-hosting#1574]
**Is your feature request related to a problem? Please describe.**
AWS Cloudfront already support Brotli Compression but AWS Amplify cannot enable the Brotli compression. At least I cannot get it to work.

**Describe the solution you'd like**
I would like to enable the Brotli Compression through AWS Amplify

**Comment by andrewgadziksonos** [comment]
Also looking for this feature

**Comment by salv0** [comment]
Please please please!

**Comment by RobertHH-IS** [comment]
Brotli has been part of cloudfront for a while and just requires a simple flag - beginning to look like a dead project.

**Comment by spormeon** [comment]
+1 for this,  its a bit unbelievable that cloudfront supports it but amplify doesn't, been messing about for days trying to get it to work before saw this thread/ issue

**Comment by suarezluis** [comment]
+1 This would reduce our data transfer by almost 30%

**Comment by rishikanttwr** [comment]
+1

**Comment by KholdStare** [comment]
Any plans to expose configuring this in cloudfront for amplify? @swaminator @Jay2113

**Comment by spormeon** [comment]
where was this "completed" then?

**Comment by swaminator** [comment]
Apologies looks like there was some incorrect automation.

**Comment by mauerbac** [comment]
This feature is now supported with our latest launch! 

Check out the details here: https://aws.amazon.com/blogs/mobile/cdn-caching-improvements-for-better-app-performance-with-aws-amplify-hosting/
