### ISSUE TITLE
Build fails (but thinks it succeeds) at 30% in "cloning repository"

### ISSUE THREAD

**Issue by 24601** [aws-amplify/amplify-hosting#1575]
**Describe the bug**
Amplify builds fail when run in the hosted CI/CD environment at 30% during the cloning repository phase of Build, however it thinks the build succeeded, goes on to test and deploy phases, and of course, then totally fails because the build steps were never even attempted as it just quit during cloning at 30% and moved on

 
**To Reproduce**
1. Submit a build in our env

**Expected behavior**
Finishes cloning repository, at least attempts a build, provides some kind of error indication as to what happened

**Screenshots**
https://www.dropbox.com/s/i8ekh8rnazxuv01/Screen%20Shot%202021-02-16%20at%2014.23.20.png?dl=0

**Desktop (please complete the following information):**
N/A - not a desktop issue

**Smartphone (please complete the following information):**
N/A - not a smartphone issue

**Additional context**
Dockerfile is basically the amplify dockerfile with a few extra layers added on, but it has been working just fine. amplify.yml and Dockerfile available by request for AWS engineers directly, don't want to post publicly, can also share in AWS Support Case ID #8000435661 if that helps. My suspicion it is some library issue or issue with the custom docker image used for build. We did not make any significant changes, however a minor bump in revs for the CLI and Hugo, etc as well as base OS updates has seemed to cause this. However, changes in amplify.yml can also seem to trigger it but we're not sure exactly what changes do and don't trigger it yet. 

At the very least, Amplify CI/CD needs to provide much more detailed information as WHY this is croaking so we can figure that out, and most certainly not treat it as a pass if the container is failing. 

Regardless, we cannot stay on this back/downlevel version of the build container forever, it has over 14 security vulnerabilities in the base OS, etc that we'd like to see upgraded and the base amazon linux docker image fixes, and Amplify build providing more data as to what and why it is failing is critical, just croaking at 30% clone and moving on is not acceptable or useful. 

Is there a OOM condition? A ulimit issue? A kernel panic? There's no way of knowing, and even worse, amplify thinks the build phase passed!

**Comment by kahdojay** [comment]
@24601 Can you share those details in the support case as well as your app Id region and build number and ask the support engineers to share with us? You can also email the details to aws-amplify-customer@amazon.com if you prefer.

**Comment by behrooziAWS** [comment]
The build actually proceeds further and it fails to run 'tr' and 'npm' to patch the amplify-cli.  We should properly catch this, report it as an error and fail the build, but while we update our code to do that, please make sure the [necessary software packages](https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html) has been correctly installed on your custom image.

```
2021-02-16T21:08:46.728Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
/root/.nvm/nvm.sh: line 2544: tr: No such file or directory
Error: Cannot find module '/root/.nvm/versions/node/none/lib/node_modules/@aws-amplify/cli/package.json'
2021-02-16T21:08:47.208Z [INFO]: # Unable to determine local version for @aws-amplify/cli, assuming 0.0
2021-02-16T21:08:47.208Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 0.0 to 4.43.0...
/bin/bash: npm: No such file or directory
```
