### ISSUE TITLE
amplify web console consistently crashes or becomes unresponsive in chrome 

### ISSUE THREAD

**Issue by mishabruml** [aws-amplify/amplify-hosting#1635]
**Describe the bug**
amplify web console consistently crashes or becomes unresponsive in chrome browser. CPU usage for chrome spikes to >99% and frequently the chrome kill page/wait dialogue appears

**To Reproduce**
1. https://eu-west-1.console.aws.amazon.com/amplify/home?region=eu-west-1#/

**Desktop (please complete the following information):**
Chrome 88.0.4324.192 (Official Build) (x86_64)
Mac OS Big Sur 11.2.2 (20D80)

**Comment by ganipcanot** [comment]
Are you still having issues on your end?  From my end it seems to be loading just fine.

**Comment by mishabruml** [comment]
yes, the page is still slow to respond
