### ISSUE TITLE
Production URL invalid

### ISSUE THREAD

**Issue by ctjlewis** [aws-amplify/amplify-hosting#1757]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v14.16.0

### Amplify CLI Version

4.48.0

### What operating system are you using?

Ubuntu

### Amplify Categories

Not applicable

### Amplify Commands

publish

### Describe the bug

In the Amplify Console, I have an App with the following:

```
Production environment URL
https://.d1ytxr948XXXX.amplifyapp.com
```

The URL begins with a period (`.`). It is not a valid URL. I do not know why this is happening. Deleting the app and re-creating did not solve this.

### Expected behavior

A valid URL should be generated.

### Reproduction steps

1. Create a new project with `amplify init`.
2. Check Amplify Console and see an invalid production URL.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Jay2113** [comment]
Hi @ctjlewis 👋 , thanks for your continued patience! 

We have deployed a fix for the invalid `Production environment URL` and it should now appear as blank for apps that do not have a frontend branch associated to it in the Amplify Console:

![Image](https://github.com/aws-amplify/amplify-hosting/assets/38470430/2b5068d0-6e45-4097-8abf-123097867109)

**Comment by ctjlewis** [comment]
Nice work @Jay2113!
