### ISSUE TITLE
Several images returning 403 error when navigating to page

### ISSUE THREAD

**Issue by bloody-peanuts** [aws-amplify/amplify-hosting#1762]
I have a new page that was built with react, using npm run build and uploading my build folder. The site runs fine when hosting it on a local server with:

npm install -g serve
serve -s build

But when I upload it with amplify about half the images on the page do not load. There doesn't seem to be any common factor among non-loading images that sets them apart from loading. Similar naming schemes, similar resolutions, and same file extensions as many images that do load. When I try to reach one such image in the browser I get this error:

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>ENPP6DS6APJFVGRN</RequestId>
<HostId>JeIg2Ey4tQJSd7bBQMwkzgCr8+e7RH5R2Ep0VzgvNZ2LdVoRQe3PoSBVQGfxnJMKXmZv92+DcD0=</HostId>
</Error>

Thank you!

**Comment by garyleefight** [comment]
Hi, can you share the app arn with us?

**Comment by jackcodej** [comment]
> I have a new page that was built with react, using npm run build and uploading my build folder. The site runs fine when hosting it on a local server with:
> 
> npm install -g serve
> serve -s build
> 
> But when I upload it with amplify about half the images on the page do not load. There doesn't seem to be any common factor among non-loading images that sets them apart from loading. Similar naming schemes, similar resolutions, and same file extensions as many images that do load. When I try to reach one such image in the browser I get this error:
> 
> `AccessDenied` Access Denied ENPP6DS6APJFVGRN JeIg2Ey4tQJSd7bBQMwkzgCr8+e7RH5R2Ep0VzgvNZ2LdVoRQe3PoSBVQGfxnJMKXmZv92+DcD0=
> Thank you!

Any chance you figured it out on your own? I seem to be having the same issues

**Comment by hloriana** [comment]
@jackcodej are you still experiencing this issue? If so, please share your AppID and region.
