### ISSUE TITLE
published site at amplify domain gives Error  AccessDenied

### ISSUE THREAD

**Issue by nilyin** [aws-amplify/amplify-hosting#1774]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

Hi i have my application published at amplify and have two questions:

1) when using cli (amplify publish) I receive link in terminal which works
http://ecoosmarketplace-20210422211312-hostingbucket-staging.s3-website.eu-central-1.amazonaws.com/

why this link is different from the link stated in Amplify Web Console (which is:
https://main.d24x74bs3wfjmt.amplifyapp.com ) ?

2) when accessing the second link (https://main.d24x74bs3wfjmt.amplifyapp.com) I have received:

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>9NCM6FBHH7DYYWYG</RequestId>
<HostId>UwLWmBvnL6UdrqBk+dueAoe7qGznNFOKETIsxGBJ3uZiR63ujpBVjRv7zwc6ipcAdPjmKohRK7g=</HostId>
</Error>`

I've googled a lot and the only advice is to set redirect, which I did (see the screenshot):
</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>      /index.html     200 (rewrite)

but that didn't help to fix the issue and access the site. Please help to solve it.

### Expected behavior

1) indicate the same published and active links both in CLI and Web Console
2) access the site on shown in wen console link

### Reproduction steps

1) create new amplify site with backend
2) publish using cli - amplify publish and get the links
3) compare on link shown on the amplify main page (see the screenshot)

**Comment by brnmye** [comment]
Hello, thank you for sharing your issue, could you provide your appId and region please.

**Comment by nilyin** [comment]
Hi, thanks for paying attention to my issue. The requested information is geven below:
1) AppId: d24x74bs3wfjmt
2) region: eu-central-1

**Comment by Aser-Elshawi** [comment]
Same problem here:
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>4SRSGDF1AVSWA65D</RequestId>
<HostId>GkwXjQIJ7H0thm3zSw8NNOOQcqDmmiDMJmF86MZ3qZAiB23olmMij92xbcEUhscwNxhCOtOu1nA=</HostId>
</Error>

I just followed exactly the tutorial instructions on AWS

**Comment by hloriana** [comment]
For those running into the `This XML file does not appear to have any style information associated with it. The document tree is shown below.` error, please make sure the `baseDirectory` is set to the correct folder.
