### ISSUE TITLE
Failed to delete backend

### ISSUE THREAD

**Issue by nyholku** [aws-amplify/amplify-hosting#1803]
In Amplify Console I  try delete my application and it says "Failed to delete backend"

Here is the app details:

App name
romexis-vue
App ARN
arn:aws:amplify:eu-central-1:910630674321:apps/d1ib7traq3jffj
Source repository
https://bitbucket.org/nyholkupm/romexis-vue/src/master 
Created at
30/04/2021, 14:21:37
Production branch URL
https://master.d1ib7traq3jffj.amplifyapp.com 
Updated at
30/04/2021, 14:21:37
Framework
Vue - Amplify

**Comment by brnmye** [comment]
Hello thank you for bringing up your issue I will look into it and get back to you as soon as possible

**Comment by Black-Hack** [comment]
Hi, I had the same issue and solved it by creating another backend with the same name and then deleted the old backend and it worked.

**Comment by Narrator** [comment]
@nyholku If you are still facing this issue, could you please try the suggestion here: [#1330 (comment)](https://github.com/aws-amplify/amplify-console/issues/1330#issuecomment-739493860)

Basically, try running this command:
```
aws amplify delete-backend-environment --app-id <YOUR_APP_ID> --environment-name <THE_BACKEND_ENVIRONMENT_NAME>
```

**Comment by hloriana** [comment]
Closing as duplicate of https://github.com/aws-amplify/amplify-hosting/issues/882. Please track the status of the bug fix using that issue. Thank you!
