### ISSUE TITLE
No easy way to re-trace steps from "Create service role", once the button has been clicked once.

### ISSUE THREAD

**Issue by undefobj** [aws-amplify/amplify-hosting#183]
If you click “create a new role” and then close that tab, without actually creating the role, then the “create a new role” button is gone and the user is stuck

**Comment by kahdojay** [comment]
Hi, we'll look at improving this, in the meantime you can follow the [docs on creating a service role](https://docs.aws.amazon.com/amplify/latest/userguide/how-to-service-role-amplify-console.html) then click the refresh button and the role will appear.
