### ISSUE TITLE
Nuxt.js Server Side Rendering (SSR) support

### ISSUE THREAD

**Issue by siegerts** [aws-amplify/amplify-hosting#1860]
**Is your feature request related to a problem? Please describe.**
Given the current support for Next.js SSR, I'd like to have a similar option for Vue developers.

**Describe the solution you'd like**
I'd like to deploy [Nuxt.js](https://nuxtjs.org/) SSR-enabled applications to Amplify Hosting.

**Additional context**

- [Nuxt Server Side Rendering](https://nuxtjs.org/docs/2.x/concepts/server-side-rendering)
- [Nuxt 3 Server Engine](https://v3.nuxtjs.org/concepts/server-engine)

**Comment by siegerts** [comment]
If you're interested in this, please use reactions to 👍🏻!

![image](https://user-images.githubusercontent.com/634958/118824628-01c9d680-b888-11eb-8add-9e4a4e05192d.png)

**Comment by sharaola** [comment]
AWS is misleading in the documentation and giving wrong info 

https://aws.amazon.com/about-aws/whats-new/2020/09/amplify-javascript-adds-server-side-rendering-support-frameworks-next-js-nuxt-js/

It is clearly mentiond that AWS Amplify supports NuxtJS with SSR

While AWS Professional support mentioned it is not supported and they even don't have ETA for this feature to be in place ???!!!!

**Comment by JDHalm** [comment]
yes please

**Comment by bart** [comment]
Is there any estimate when this feature is available? Like @sharaola said it's very misleading information in the corresponding blog post / announcement. As far as I can see AWS has to solve this issue by adding some special workflow when detecting a NuxtJS app during deployment, right? I think it's unfortunately not an open source issue the community can solve, right?

**Comment by devravi** [comment]
+1

**Comment by aavrug** [comment]
+1 This will be really helpful when we don't have to handle anything manually except the push of the code so the deployment will be easy and scaling will be also handled automatically.

**Comment by salv0** [comment]
Is there any news about this? :)

**Comment by annymosse** [comment]
So excited to try this feature 👍

**Comment by StefanV85** [comment]
+1

**Comment by bart** [comment]
I might found a way to at least host a Nuxt 3 app via Lambda. Will further investigate and hopefully find a way to host it with Amplify, even it currently doesn't seem to be possible via Amplify Hosting. The creation of a custom Lambda function (in Amplify) might work based on my following solution. Last but not least I can't understand why it seems to be so difficult for the Amplify team to implement Nuxt 3 hosting feature. The community is waiting for ages now and other providers like Vercel are handling it with an awesome user experience instead. To be honest I'm very disappointed about what AWS is (or better is not) doing!

Here comes a possible workaround:

With Nuxt 3 running on Nitro you have the option to build it with deployment presets. It also has one for AWS Lambda called (yes, you guessed it): `aws-lambda`

1. Run `NITRO_PRESET=aws-lambda yarn build` to generate a Lambda compatible version
2. Zip content of your `.output/server` folder
3. Create a new Lambda function (manually via AWS console) and activate function URL feature
4. Upload your created ZIP file
5. Click on the function URL displayed under your Lambda function ARN
6. Et voila, your entire frontend app is server-side rendered on AWS including dynamic routes

Please let me know if you think this might be a temporary workaround to at least host Nuxt 3 apps serverless on AWS or if you have another solution. Cheers!
create a new Lambda function via AWS console

**Comment by Batto1300** [comment]
I was able to make SSR work by following this https://kodius.com/blog/nuxt-ssr-on-amplify/.

**Comment by bart** [comment]
@Batto1300 This is not SSR. It's using the `generate` command which generates a static site. SSR means it is running a nodeJS instance in the background that handles requests and generates HTML on the server-side.

**Comment by scalemaildev** [comment]
@bart +1 for loving to see this. I ran into the same problem with no CSS. Would be really cool to run a site entirely in Lambda.

**Comment by bart** [comment]
Thanks for pointing this out @scalemaildev but unfortunately it doesn't solve the main issue: AWS still doesn't support AWS out of the box whereas other cloud service providers like Vercel do. That's an issue just AWS can solve and they promised it for months now. I accepted that they give a sh*t on Nuxt 3 community and switched to Vercel and Firebase with most of my projects.

**Comment by scalemaildev** [comment]
> Thanks for pointing this out @scalemaildev but unfortunately it doesn't solve the main issue: AWS still doesn't support AWS out of the box whereas other cloud service providers like Vercel do. That's an issue just AWS can solve and they promised it for months now. I accepted that they give a sh*t on Nuxt 3 community and switched to Vercel and Firebase / Supabase with most of my projects.

Of Vercel/Firebase/Supabase which would you recommend for someone that wants to run a Nuxt3 app "on the edge"? Specifically, a multiplayer game app with a lot of back and forth between client and server?

**Comment by bart** [comment]
@scalemaildev Depends a little on what your server exactly does. If it ist just handling requests and for example generates timestamps Vercel is fine. If you have data that needs to get stored into a database and if you have a more complex app ecosystem I would recommend Firebase which is closer to AWS.

**Comment by salv0** [comment]
Will we ever see this implemented? 👀

**Comment by bart** [comment]
Unfortunately I don't think so. That's why I switched from Nuxt to Vitesse

**Comment by dbhagen** [comment]
@bart what's the benefit of switching to Vitesse? And vanilla Vitesse or Vitesse+Nuxt3? https://github.com/antfu/vitesse-nuxt3

**Comment by bart** [comment]
@dbhagen Main benefit for me is the release date delta between new major versions. It took more than 2 years to update NuxtJS to Vue 3. I don't wanna blame anyone for it because I know that a lot of braking changes took place (for example the new Composition API just to name one here). But in terms of issues we codes have to solve every day there are way more community solution out there for Vue 3 than for Nuxt for sure. Your choice should depend on the project you plan. If it is a single page app only, for sure Nuxt 3 might be the better choice. But if you need a little more freedom and a bigger community (Nuxt is just a piece of the Vue cake) then Vue 3 packed in Vitesse might be the better way to go.

**Comment by pxslip** [comment]
I'm curious if this feature is even being considered? The lack of Nuxt SSR support has brought a major project to a screeching halt as we had operated on the assumption (based on the original announcement) that Amplify would support SSR for Nuxt. Thanks!

**Comment by robokozo** [comment]
Just wanted to update the links in the OP with the latest references:

- [Nuxt Server Side Rendering](https://nuxt.com/docs/guide/concepts/rendering#universal-rendering)
- [Nuxt 3 Server Engine](https://nuxt.com/docs/guide/concepts/server-engine)

I'd love to hear if there was any movement on this request! Is it even being considered?

**Comment by salv0** [comment]
It doesn't seem the Amplify team is really interested in supporting this... too bad

**Comment by notherio** [comment]
By the time this issue was open I was a young tough developer now I’m retired

**Comment by kasvith** [comment]
Do this please

**Comment by trandaison** [comment]
Any update, please

**Comment by Joscha95** [comment]
+1

**Comment by tompscanlan** [comment]
Wait... so does SSR in Nuxt.js work on amplify at all?  Do we require changes from AWS to get it working?  Or can we make it work with special config?  

2 years and a major rev in at least one of the projects tells me this ain't a priority for AWS.

**Comment by devravi** [comment]
Two years without any response. Disheartening. A simple acknowledgement would be appreciated.

**Comment by bart** [comment]
I recommend using Vercel to host your NuxtJS app. It's quite handy and you are not blocked by any AWS work that is required.

**Comment by esorribas** [comment]
@bart the problem is when you have 90% of services under AWS and you are comfortable on it and Vercel is expensive compared to AWS.
I don't understand why is not supported, because I understand they can't support nitro, but come on, you can preset to nodejs and this is not a new technology.

**Comment by siegerts** [comment]
Hi All 👋, 

I'm on the Amplify Hosting PM team. This is something that we are actively tracking. I'm personally invested in this too... I opened this feature request :)  

I appreciate all of the engagement here, in the Nuxt community, and all of the feedback provided over the course of the feature request. I'll maintain communication here with any updates. Thank you again!

**Comment by bart** [comment]
For more than two years now...

**Comment by robokozo** [comment]
@siegerts just a heads up that there are several different SSR frameworks using the https://nitro.unjs.io/ engine. You will get a lot of bang for your buck by supporting this story more directly.

Angular: https://analogjs.org/
SolidJS: https://github.com/solidjs/solid-start/discussions/1052 (announced at most recent vite conf)

There are more frameworks too: https://github.com/unjs/nitro/discussions/1015

You guys should hurry up :) because the firebase team is working on a similar SSR story https://firebase.google.com/docs/hosting/frameworks/frameworks-overview

**Comment by sawravchy** [comment]
Hi @siegerts , Do you have any approx. timeline for this? We have been waiting for this for a long time.

**Comment by sawravchy** [comment]
Hi @siegerts , 
Do you have any approx. timeline for this? We have been waiting for this for a long time.

**Comment by ppoturalskiEC** [comment]
> I'm curious if this feature is even being considered? The lack of Nuxt SSR support has brought a major project to a screeching halt as we had operated on the assumption (based on the original announcement) that Amplify would support SSR for Nuxt. Thanks!

Same here, any updates would be appreciated.

**Comment by esorribas** [comment]
https://twitter.com/AWSAmplify/status/1726635846483210561

rock

**Comment by siegerts** [comment]
Hi All - I am excited to share that we now support Nuxt SSR (and other SSR deployments) on Amplify Hosting 🎉 . The Nuxt zero-config deployment was a combined effort between the Amplify and Nuxt team to integrate the new Amplify Hosting SSR deployment spec in the Nitro server. 

For more information and a walkthrough of deploying a Nuxt app, check out:

[Introducing Support for Hosting Any SSR app on AWS Amplify Hosting](https://aws.amazon.com/blogs/mobile/introducing-support-for-hosting-any-ssr-app-on-aws-amplify-hosting/)
