### ISSUE TITLE
 Deployment failed! 

### ISSUE THREAD

**Issue by unvssprasad** [aws-amplify/amplify-hosting#1934]
When i am trying to publish the changes to amplify it is not giving any error but only showing  Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues. How to fix this issue

**Comment by brnmye** [comment]
Hello looking at that app, I found that a deployment succeeded on June 6 2021, but I do not see a build step being executed, can you confirm if that deployment succeeded and if you see the build step being executed in Amplify console for this app? Thank you

**Comment by unvssprasad** [comment]
Build succeeded i mean ng build and when it comes to deployment it is giving this error, screenshot attached for your refeerence
![image](https://user-images.githubusercontent.com/1838250/121291044-3ec43e80-c905-11eb-8742-633182f1d2e3.png)

**Comment by unvssprasad** [comment]
Build succeeded with ng build and zipping articafts also completed but after deployment failing, attached screenshot
![image](https://user-images.githubusercontent.com/1838250/121291205-7e8b2600-c905-11eb-92a4-e2033df3ccc8.png)
