### ISSUE TITLE
Understanding Storage Usage (5GB free tier)

### ISSUE THREAD

**Issue by noahzs** [aws-amplify/amplify-hosting#1937]
**Which Specific Feature is your question related to?**
I have received an email saying I've used up the 5GB of free tier storage. This is also being reported on my AWS billing console. I am trying to understand what this 5GB of data is, as the only information currently being stored is 2 auth users (No data has been written to tables or models) - definitely not 5GB worth of data. A breakdown of usage would be appreciated.

Cheers

Noah

**Provide additional details e.g. code snippets**
I've attached screenshots showing billing, all content and all users under user management. 
<img width="1448" alt="usermanagement" src="https://user-images.githubusercontent.com/55651683/120398837-4d977800-c37e-11eb-9875-ea12f9d4847a.png">
<img width="1437" alt="contactcontent" src="https://user-images.githubusercontent.com/55651683/120398846-4ff9d200-c37e-11eb-9f4a-b00f435fe16a.png">
<img width="667" alt="billing" src="https://user-images.githubusercontent.com/55651683/120398852-512aff00-c37e-11eb-882b-b5b7fc56cfff.png">
<img width="1437" alt="addresscontent" src="https://user-images.githubusercontent.com/55651683/120398856-51c39580-c37e-11eb-95c1-c62339562ac4.png">

**Comment by brennoflavio** [comment]
Hey, I'm also facing this issue. For me, it shows 5GB of free tier storage used in Amplify, and in S3 console it shows 4.1 GB consumed. Do you know if there is a way to clear the Amplify Storage? Probably it is storing logs or artifacts that is not needed anymore (like old builds).

**Comment by kovan** [comment]
Hi, same issue here. Probably the space is coming from keeping older builds artifacts. 
The question is, how to manage them? the keep piling up forever, or how does this work?. 
I haven't seen any option in the menus for this, and I have looked at the CLI utility and haven't found anything either. Nor there is an S3 bucket in my case.

Help appreciated.

**Comment by MaTesch** [comment]
Same here. There seems to be no option to get rid of old artifacts, or whatever is causing amplify to keep stacking up on Data Storage consumption.

**Comment by MaTesch** [comment]
@siegerts I saw you added a label to this issue. Can you elaborate on the status or road map for this?

**Comment by hloriana** [comment]
Artifacts are stored in Amazon S3 after successful deployments. Currently, those objects will remain in S3 unless you delete them by running commands such as `delete-job` to delete artifacts for a specific job or `delete-branch` to delete objects for all of the jobs for a specific branch (and delete the branch itself). 

https://docs.aws.amazon.com/cli/latest/reference/amplify/delete-job.html
https://docs.aws.amazon.com/cli/latest/reference/amplify/delete-branch.html

Here is an example of how pricing and storage can be estimated when using Amplify Hosting: https://aws.amazon.com/amplify/pricing/
