### ISSUE TITLE
Next.js hosting root [...page].[jt]sx results in 503s for non-`/static-pages/*` assets in S3

### ISSUE THREAD

**Issue by quinnturner** [aws-amplify/amplify-hosting#1947]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-east-1

### Describe the bug

Adding a root `[...page].[jt]sx` page results in the client not being able to fetch most assets from S3. For example, `/_next/data/*` is not accessible. Some debugging suggests that CloudFront (or Lambda, kinda confused) tries to fetch the resource `/_next/data/UynN6AYTWZubV5j5qUyd9/index.json` at `/static-pages/_next/data/UynN6AYTWZubV5j5qUyd9/index.json` resulting in a `503` (or `404` if you increase the permissions on the bucket).

### Expected behavior

A root `[...page].[jt]sx` does not break routing to non-`/static-pages/*`

### Reproduction steps

1. Create a Next.js app following the latest guidelines
2. Create a page `[...page].[jt]sx` at the root of `/pages`. In our instance, we use that page with `getStaticProps` and `getStaticPaths` to produce various pages at build-time. Consider adding some SSR pages with links to them on the home page for full visibility.
3. Deploy the Next.js app to Amplify
4. Visit the website, note that requests to `/_next/data/<path>/index.json` fail with `503`s

### Build Settings

```yaml
Default Next.js build settings
```

**Comment by brnmye** [comment]
Hello can you provide the appId for the app giving you issues? Thank you

**Comment by hloriana** [comment]
A fix has been pushed for this bug. Closing as resolved.
