### ISSUE TITLE
AWS  amplify redirect issue with apple-app-site

### ISSUE THREAD

**Issue by josea2pp** [aws-amplify/amplify-hosting#1983]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region
us-east-1

### Describe the bug

I'm  using aws amplify to host my front end but im getting a issue putting the universal link for ios, i put the apple-app-site-association in my root folder and create a rule in redirect part to point to that file but without extension it just get 404 but if i put and ext .json it works, the problem is that apple required that the file does't have extensions.

this is muy current config and my file is located in /root/apple-app-site-association
   {
        "source": "/apple-app-site-association",
        "target": "/apple-app-site-association",
        "status": "200",
        "condition": null
    }
]

### Expected behavior

That aws allow me put files without extension

### Reproduction steps

upload a file without extension
redirect with a rule to that file
see if it work

**Comment by victorccccc** [comment]
Hi, Can you add this custom rule:
```
[
    {
        "source": "/.well-known/apple-app-site-association",
        "target": "/apple-app-site-association",
        "status": "200",
        "condition": null
    }
]

```

**Comment by josea2pp** [comment]
Victor, thanks for the reply,

But in that case do i have to create a sub directory on mi root? like root/.well-known/apple-app.site-association?

**Comment by victorccccc** [comment]
> Victor, thanks for the reply,
> 
> But in that case do i have to create a sub directory on mi root? like root/.well-known/apple-app.site-association?

No, you can keep apple-app-site-association in root folder.

**Comment by josea2pp** [comment]
not, it seems that doesn't work it bring me the 404

these are my rules 

[
    {
        "source": "/.well-known/apple-app-site-association",
        "target": "/apple-app-site-association",
        "status": "200",
        "condition": null
    },
    {
        "source": "/<*>",
        "target": "/index.html",
        "status": "404-200",
        "condition": null
    },
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    }
]

**Comment by victorccccc** [comment]
> not, it seems that doesn't work it bring me the 404
> 
> these are my rules
> 
> [
> {
> "source": "/.well-known/apple-app-site-association",
> "target": "/apple-app-site-association",
> "status": "200",
> "condition": null
> },
> {
> "source": "/<*>",
> "target": "/index.html",
> "status": "404-200",
> "condition": null
> },
> {
> "source": "</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>",
> "target": "/index.html",
> "status": "200",
> "condition": null
> }
> ]

Sorry for the confusion, is the root folder a folder in your Repo? 
Could you put ```apple-app-site-association``` in root of your repo as target is ```/apple-app-site-association``` ?

Ref: https://github.com/aws-amplify/amplify-console/issues/1209

**Comment by r0nanoc** [comment]
Hi,
I have tried this approach but get error. My rule is configured similar to previous comment...
**_[
    {
        "source": "/.well-known/apple-app-site-association",
        "target": "/apple-app-site-association",
        "status": "200",
        "condition": null
    }
]_**

However when I go to 'Add a new domain' on stripe settings --> payment methods, I get error:

**_We were unable to verify that you control the domain <my-domain>.com. When we tried to request https://<my-domain>.com/.well-known/apple-developer-merchantid-domain-association, it redirected to /.well-known/apple-developer-merchantid-domain-association/. The verification file must be served as a 200 at https://<my-domain>.com/.well-known/apple-developer-merchantid-domain-association to register <my-domain>.com. Did you mean to register /.well-known/apple-developer-merchantid-domain-association/?_**

Appreciate any help here.

**Comment by jameyel** [comment]
@r0nanoc getting the same error. hoping someone can help with this.

**Comment by tamagokun** [comment]
Solution is that the file itself NEEDS a file extension, and the redirect does not:

```
[
    {
        "source": "/.well-known/apple-app-site-association",
        "target": "/.well-known/apple-app-site-association.json",
        "status": "200",
        "condition": null
    }
]
```

Then amplify will be able to find it correctly.

**Comment by chris** [comment]
Note, @tamagokun 's answer worked for me, but just an FYI that if I put this URL in my browser, it results in the typical Amplify/CloudFront `AccessDenied` XML error. But, if I `curl` the URL, it delivers me the file just fine.

**Comment by calavera** [comment]
Thanks for providing the solution to this issue @tamagokun ! I'm going to close this issue, and I will open a new one in the docs repository so we can add this to our docs.
