### ISSUE TITLE
User-agent modified by cloudfront 

### ISSUE THREAD

**Issue by surajsararf** [aws-amplify/amplify-hosting#1993]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

djh7fyxc2u06x

### Region

region=ap-south-1

### Amplify Console feature

Build settings, Custom headers, Redirects

### Describe the bug

I create a project and upload a zip file that consists of an index.html and add redirect rules 
```
Source address: <*>
target address: https://abc.com/<*>
Type: 200 (Rewrite)
```
And it is totally working except user-agent that I am getting this at https://abc.com server
```
user-agent = Amazon CloudFront
```

### Expected behavior

Expecting User-Agent
```
user-agent = Mozilla/5.0 (Linux; Android 6.0.1; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Mobile Safari/537.36
```

### Reproduction steps

Please follow the above stepsfollow

### Additional information

How can I solve this issue? Please help.

**Comment by anatolzak** [comment]
Is there any progress on this issue?

As of now, it is impossible to use AWS Amplify Rewrites for rewrites to an external API because the user agent is modified to be `Amazon CloudFront` instead of the user's user agent.

When will this be fixed?

**Comment by dchanmaisonette** [comment]
Yes, I would like to know when this can be addressed as well.

**Comment by gilliardmacedo** [comment]
Yes, and since it's not possible to use Lambda@Edge or see the CloudFront distribution, there's no workaround.

It's important to SSR features

**Comment by mauerbac** [comment]
This feature has just been supported with our latest launch! Closing.

Check out the details here: https://aws.amazon.com/blogs/mobile/cdn-caching-improvements-for-better-app-performance-with-aws-amplify-hosting/
