### ISSUE TITLE
Not able to deploy from aws amplify from codecommit, getting error at build stage

### ISSUE THREAD

**Issue by shubham2924** [aws-amplify/amplify-hosting#2004]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d94c07lzmk2x4

### Region

us-east-1

### Amplify Console feature

Build settings

### Describe the bug

I'm having basic react app. So very firstly I created a codecommit repo and cloned it in my local machine and pushed it to aws codecommit so entire project(all folders, files) are pushed there. And then I moved to deploy that react app on aws amplify chose my repo and hit 'save and deploy' button but getting an error at build stage only, so below down there was something like 
There was an issue connecting to your repo provider, click "Reconnect repository" in General Settings, and then try your build again.
so I went and clicked "Reconnect repository", still the same error and even tried redeploying the app.
After that I went to that codecommit repo and under commits/HEAD there was this error
"Error
The operation completed, but an error occurred. A specified commit ID is not a valid Git object ID. The specified ID was: HEAD. Make sure that your request includes only valid commit IDs, and then try again."

### Expected behavior

Expected behaviour is to simply get my app deployed with github for aws amplify deployment it was working fine and getting deployed but we're supposed to use aws codecommit only

### Reproduction steps

![image](https://user-images.githubusercontent.com/59010807/123511734-c39eae80-d6a0-11eb-9aa7-cdac0a372a11.png)

**Comment by spencermarley** [comment]
Hi Shubham,

The role that your Amplify app uses needs to have read access to Code Commit, so attach a policy such as AWSCodeCommitReadOnly to it.

Best regards,
Spencer.
