### ISSUE TITLE
cant publish client build

### ISSUE THREAD

**Issue by Gshiray** [aws-amplify/amplify-hosting#2015]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d16z65fc78fkk2

### Region

us-east-1

### Amplify Console feature

Access control

### Describe the bug

getting a permissions error when trying to publish - 
running amplify publish and getting the following error 
An error occurred during the publish operation: User: arn:aws:sts::491044314911:assumed-role/us-east-1_WF4v0uL7s_Full-access/amplifyadmin is not authorized to perform: amplify:ListJobs on resource: arn:aws:amplify:us-east-1:491044314911:apps/d16z65fc78fkk2/branches/test/jobs/*

### Expected behavior

client side app should be published

### Reproduction steps

1. create a new env - amplify env add {env}
2. run amplify publish

**Comment by siegerts** [comment]
Hi @Gshiray, thanks for raising. Can you see if either solution in these other scenarios helps?

https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+is%3Aopen+amplify%3AListJobs

**Comment by calavera** [comment]
I'm going to close this issue for lack of activity. Let us know if the problem still exists and we'll be happy to reopen the ticket.
