### ISSUE TITLE
Custom domain is configured properly, occasionally SPA is down and unavailable  

### ISSUE THREAD

**Issue by RiadHossain43** [aws-amplify/amplify-hosting#2017]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2teza7a96odgs

### Region

eu-west-2

### Step

App deployment

### Status

Available 

### Issue or question

The problem is our domain is configured well through the amplify console, we followed the steps written in the docs and the domain is in route 53 hosted zone. Our website which is built on top of react is also performing well. But occasionally the website gets down in some region and users can't access for 10-20 minutes and then automatically comes back and everything is working well  

### Error message

No error is displayed

**Comment by nimacks** [comment]
@RiadHossain43 can you provide dates when this has happened so we can troubleshoot further? Also you mention that the site goes down in some region? Is this eu-west-2 region or are some users reporting that they cannot access from some parts fo the world?

**Comment by RiadHossain43** [comment]
@nimacks actually some of my users that live in Bolton, UK reported this issue. I'm also operating from Bangladesh I only faced the problem once in my end. Coming back to the event time, the problem occurs occasionally. Last time someone reported me was yesterday `29/6/2021`. I also checked `https://www.whatsmydns.net/` with this URL according to the docs and found in some regions my domain does not respond. I have say three sub domains configured in my single react application. addvantage-technologies.imssystems.tech , my.imssystems.tech, sandbox.imssystems.tech. Also for your information, my TTL time out for all these sub domains are set to 300 seconds in all CNANE records.

**Comment by RiadHossain43** [comment]
@nimacks please did you have a look on the issue?

**Comment by RiadHossain43** [comment]
@nimacks Is there any update regarding this issue ? Our customers are facing  occasional downtime

**Comment by nimacks** [comment]
@RiadHossain43 

> @nimacks Is there any update regarding this issue ? Our customers are facing occasional downtime

We are still investigating the issue and will provide an update once we've been able to reproduce and identify the root cause.

**Comment by Jay2113** [comment]
Hi @RiadHossain43 👋 , thanks for your continued patience and we apologize for the delayed response on this thread. 

It seems that the Amplify app `d2teza7a96odgs` and its associated custom domains have been deleted. 

Can you please confirm the following:
- Are you observing a similar behavior with any other Amplify app? If yes, can you share the impacted Amplify App ID?
- Have you recently been able to reproduce this behavior? If yes, can you share an approximate timeframe (in UTC) and if all users or users from a specific location are reporting this behavior?

**Comment by RiadHossain43** [comment]
@Jay2113 I've stopped using amplify and configuring cloud front directly myself and hosting it on S3 instead of a managed service

**Comment by Jay2113** [comment]
I am sorry to hear that you have moved away from using Amplify Hosting @RiadHossain43 .

That being said, I would like to highlight that we have made significant improvements to the Amplify Hosting service over the past couple of years and in the meantime have also launched new features for our customers: https://github.com/aws-amplify/amplify-hosting/blob/main/CHANGELOG.md. 

If it's suitable for your business use case, we would highly recommend reviewing and reconsidering the Amplify Hosting managed solution and we'll be happy to answer any questions you have either here on GitHub via a new thread or on our community [discord server](https://discord.com/invite/amplify). Thanks!
