### ISSUE TITLE
Team with IAM access can't view deployments in Amplify Console

### ISSUE THREAD

**Issue by marcusharjani** [aws-amplify/amplify-hosting#2082]
I have granted increasingly broader access to the team, beginning with the Amplify Administrator AWS managed IAM policy attached to the team, now granting them the Power User policy. It seems that only I (root user) can view active Amplify deployments in the console. They also had a similar problem where they couldn't create a deployment either. There is no clear answer to what is causing this problem or how to resolve it. 

[Others are having this problem as well](https://github.com/aws-amplify/amplify-console/issues/1224) but there has been no resolution. Any help would be greatly appreciated.

**Comment by ferdingler** [comment]
Does this happen in the UI (Console) only? How about using the AWS CLI? 

```bash
aws amplify list-apps
```

Just trying to narrow down if this may be a UI issue.

**Comment by hloriana** [comment]
Closing due to no response.
