### ISSUE TITLE
SSL certificate issued, webpage error:  DNS_PROBE_FINISHED_NXDOMAIN

### ISSUE THREAD

**Issue by Corey-Wademan** [aws-amplify/amplify-hosting#2102]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1pysc4lw8c3dr

### Region

us-east-1

### Step

Deploy

### Status

Passes tests, fails to load

### Issue or question

I've went through the build steps and had the SSL issued but when I attempt to reach the site, it fails with the DNS error below. I did previously have the domain in use on a S3 bucket but deleted the bucket two days ago to migrate the domain and content to AWS Amplify. 

### Error message

This site can’t be reached
Check if there is a typo in checkpointalarms.com.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by Jay2113** [comment]
Hi @Corey-Wademan @into-expert 👋 , thanks for reaching out to us and we apologize for the delayed response on the thread.

The Amplify app `d1pysc4lw8c3dr` seems to have been deleted and thus we cannot review the domain configuration associated to it.

If you are observing a `DNS_PROBE_FINISHED_NXDOMAIN` error while trying to resolve your custom domain, I would highly recommend reviewing this [article](https://repost.aws/knowledge-center/route-53-troubleshoot-nxdomain-responses) which outlines some potential root causes of this error.

Related thread: https://github.com/aws-amplify/amplify-hosting/issues/2125
