### ISSUE TITLE
Next.js with Next-Auth crashes on Amplify but not locally

### ISSUE THREAD

**Issue by jackHedaya** [aws-amplify/amplify-hosting#2103]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2mic7n2avxrur

### Region

us-east-1

### Amplify Console feature

Backend builds

### Describe the bug

My application handles authentication with NextAuth. NextAuth apparently has some implicit imports to `typeorm` for use in its database features. To be completely honest, I'm not exactly sure how that works in detail but it builds successfully using `next build` on my local machine (no Amplify). 

However, when pushing code to Amplify (using GitHub CD), the deployment fails at the 'Starting SSR Build'  step with the error found below. I attempted to fix it by manually including `typeorm` and `mongodb` in my project and then another library came up with the same problem.

Related NextAuth issue is [here](https://github.com/nextauthjs/next-auth/issues/2439).

### Expected behavior

The build to be successful.

### Reproduction steps

```json
{
  ...
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "generate-password": "^1.6.1",
    "googleapis": "^82.0.0",
    "jsonwebtoken": "^8.5.1",
    "mongodb": "^4.0.1", // Attempt to fix
    "next": "11.0.1",
    "next-auth": "^3.27.3",
    "node-random-name": "^1.0.1",
    "nookies": "^2.5.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-responsive-modal": "^6.1.0",
    "sass": "^1.36.0",
    "typeorm": "^0.2.34", // Attempt to fix
    "url-join": "^4.0.1"
  },
  "devDependencies": {
    "@types/react": "^17.0.15",
    "@types/url-join": "^4.0.1",
    "eslint": "7.31.0",
    "eslint-config-next": "11.0.1",
    "typescript": "^4.3.5"
  }
}
```

The build error logs are here:

```
<next build appears to succeed here>

2021-07-28T13:44:36.151Z [INFO]: Starting SSR Build...
2021-07-28T13:45:48.886Z [ERROR]: Error: Command failed with exit code 1: node_modules/.bin/next build
                                  Failed to compile.
                                  ModuleNotFoundError: Module not found: Error: Can't resolve 'hdb-pool' in '/codebuild/output/.../node_modules/typeorm/platform'
                                  > Build error occurred
                                  Error: > Build failed because of webpack errors
                                  at /codebuild/output/...node_modules/next/dist/build/index.js:15:924
                                  at async Span.traceAsyncFn (/codebuild/output/.../node_modules/next/dist/telemetry/trace/trace.js:6:584)
                                  info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
                                  info  - Checking validity of types...
                                  info  - Creating an optimized production build...
                                  at makeError (/root/.//node_modules/execa/lib/error.js:60:11)
                                  at handlePromise (/root/.//node_modules/execa/index.js:118:26)
                                  at processTicksAndRejections (internal/process/task_queues.js:97:5)
                                  at async Builder.build (/root/.//node_modules/@sls-next/lambda-at-edge/dist/build.js:348:13) {
                                  shortMessage: 'Command failed with exit code 1: node_modules/.bin/next build',
                                  command: 'node_modules/.bin/next build',
                                  escapedCommand: '"node_modules/.bin/next" build',
                                  exitCode: 1,
                                  signal: undefined,
                                  signalDescription: undefined,
                                  stdout: 'info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5\n' +
                                  'info  - Checking validity of types...\n' +
                                  'info  - Creating an optimized production build...',
                                  stderr: 'Failed to compile.\n' +
                                  '\n' +
                                  "ModuleNotFoundError: Module not found: Error: Can't resolve 'hdb-pool' in '/codebuild/output/.../node_modules/typeorm/platform'\n" +
                                  '\n' +
                                  '\n' +
                                  '> Build error occurred\n' +
                                  'Error: > Build failed because of webpack errors\n' +
                                  '    at /codebuild/output/.../node_modules/next/dist/build/index.js:15:924\n' +
                                  '    at async Span.traceAsyncFn (/codebuild/output/.../node_modules/next/dist/telemetry/trace/trace.js:6:584)',
                                  failed: true,
                                  timedOut: false,
                                  isCanceled: false,
                                  killed: false
                                  }
2021-07-28T13:45:48.890Z [ERROR]: [G[?25h[G[J
                                  46s › d2mic7n2avxrur › Error: Command failed with exit code 1: node_modules/.bin/next build
                                  Failed to compile.
                                  ModuleNotFoundError: Module not found: Error: Can't resolve 'hdb-pool' in '/codebuild/output/.../node_modules/typeorm/platform'
                                  > Build error occurred
                                  Error: > Build failed because of webpack errors
                                  at /codebuild/output/.../node_modules/next/dist/build/index.js:15:924
                                  at async Span.traceAsyncFn (/codebuild/output/.../node_modules/next/dist/telemetry/trace/trace.js:6:584)
                                  info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
                                  info  - Checking validity of types...
                                  info  - Creating an optimized production build...
                                  [G[?25h
```

### Build Settings

```yaml
`amplify.yml`


version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by jackHedaya** [comment]
@NathaEEUD I deleted my project so I could deploy on Vercel until this issue is resolved. Would you mind adding your project id so that when someone takes a look they have an active project to look at?

**Comment by NathaEEUD** [comment]
> @NathaEEUD I deployed my project on Vercel until this issue is resolved and deleted it on Amplify without thinking. Would you mind adding your project id so that when someone takes a look they have an active project to look at?

@jackHedaya Hey, I did the same with the project, yesterday I implemented it in Vercel until this issue is solved. Unfortunately, I cannot do that because it's a company project so it's private

**Comment by balazsorban44** [comment]
NextAuth maintainer here. The typeorm import is here:

https://github.com/nextauthjs/next-auth/blob/0f460c22da873025920bc9c88b657d29713090d1/src/server/index.js#L110

https://github.com/nextauthjs/next-auth/blob/main/src/adapters/index.js

This is a bit unfortunate for  folks not using typeorm for their project, because it will be installed for even those who won't use it.

The strange thing is that currently we import typeorm through the underlying dependency:

https://github.com/nextauthjs/adapters/tree/main/packages/typeorm-legacy

So in theory the user shouldn't have to do anything. To reduce bundle size i the future, we will not import this package and this problem should probably go away (since the OP doesn't use typeorm and so they shouldn't have to install it, but it would be interesting to know why this problem happens on AWS Amplify and not on other platforms. (eg Vercel). Someone suggested using Next.js with webpack 4 (webpack 5 is the default now), but seems like a short term solution.

**Comment by RealDrewKlayman** [comment]
> > @NathaEEUD I deployed my project on Vercel until this issue is resolved and deleted it on Amplify without thinking. Would you mind adding your project id so that when someone takes a look they have an active project to look at?
> 
> @jackHedaya Hey, I did the same with the project, yesterday I implemented it in Vercel until this issue is solved. Unfortunately, I cannot do that because it's a company project so it's private

Vercel is sadly not HIPAA compliant so our only option is to use Amplify.. 
We have been unable to do builds because of this right now.

**Comment by jackHedaya** [comment]
Not sure the state of this as it's a couple years old. Closing.
