### ISSUE TITLE
Cloudfront URL 404

### ISSUE THREAD

**Issue by chrisworman-pela** [aws-amplify/amplify-hosting#2104]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d281wdcswuupg5

### Region

us-east-1

### Step

Domain activation / DNS setup

### Status

Failed

### Issue or question

The Cloudfront URL assigned to my Amplify App (i.e. https://d1wcvobqcpvk1c.cloudfront.net) is not resolving to my web app (the amplifyapp.com domain, https://main.d281wdcswuupg5.amplifyapp.com, is working).

On the "Domain Management" page in the AWS Amplify console, the "View DNS Records" popup states **"please wait until your new application loads successfully at the <id>.cloudfront.net url"**.

I setup the domain yesterday, so I assumed that by this morning the Cloudfront domain would resolve.  The "View DNS Records" popup does not mention anything about how long it will take for the cloudfront domain to resolve, so I have no idea how long to wait.

If I just need to wait longer, please update the "View DNS Records" popup copy (that mentions "... loads successfully at the <id>.cloudfront.net url") to indicate approximately how long it will take for the Cloudfront URL to become available.

Otherwise, please advise on how to proceed.

### Error message

If I try to visit the assigned Cloudfront URL (https://d1wcvobqcpvk1c.cloudfront.net), I get the following:

This d1wcvobqcpvk1c.cloudfront.net page can’t be foundNo webpage was found for the web address: https://d1wcvobqcpvk1c.cloudfront.net/
HTTP ERROR 404

**Comment by chrisworman-pela** [comment]
I just did some tests using my local host file, and I am beginning to think the issue is will the following sentence in the "View DNS Records" popup on the AWS Amplify console (Domain management page):

> To serve traffic to your domain, point DNS records to the AWS Amplify service. If you are migrating a custom domain that is already serving production traffic, please wait until your new application loads successfully at the <id>.cloudfront.net url shown below before updating your DNS records:

Looking at https://github.com/aws-amplify/amplify-console/issues/1677, I think the copy above is incorrect and probably should be something like:

> To serve traffic to your domain, point DNS records to the AWS Amplify service. Note that the <id>.cloudfront.net url domain shown below will not resolve to your application, but once you setup the CNAME record shown below, your domain(s) will resolve to your application.

**Comment by ganipcanot** [comment]
This sounds like it has the potential for a documentation update - thanks for reporting we will look at changing the wording here!

**Comment by chrisworman-pela** [comment]
@ganipcanot Can you please confirm that I do NOT need to wait for .cloudfront.net url to load my Amplify app before updating DNS.

**Comment by kovan** [comment]
Yeah, I am facing the same question. Should the app load at .cloudfront.net URL or not?

**Comment by ferdingler** [comment]
Hi all, @chrisworman-pela understanding is correct,

To serve traffic to your custom domain, it needs to point to the CloudFront URL via a CNAME record. But your application will only resolve via the Amplify App URL or via your Custom Domain and not directly on the CloudFront URL. This is because we need to route requests to the proper deployed branch and we use the hostname for that. For example, you may have configured that `www.example.com` points to the `mainline` branch but `dev.example.com` points to the `dev` branch, and so you need to visit your application based on these configured subdomains so that we can route requests accordingly.

**Comment by chrisworman-pela** [comment]
@ganipcanot Is there an ETA on the documentation update?

**Comment by calavera** [comment]
I've opened a ticket to track the documentation work in https://github.com/aws-amplify/docs/issues/4112. That should give more visibility to the pendind addition to the docs. I'm going to close this issue, thanks for reporting it @chrisworman-pela.

**Comment by teamteak** [comment]
So just to be clear.  

If Amplify Hosting is asking me to update our ANAME to: `<id>.cloudfront.net` AND we are NOT using S3 AND it throws a 404, we should rather create a CNAME on our third-party DNS for the corresponding branch application URL we want our domain to resolve to which does work and resolves correctly.

Example:

We want our `example.com` production domain to resolve to our `root` branch, AND `<id>..cloudfront.net` is throwing a 404, therefore use `root.<id>.amplifyapp.com` app URL for your CNAME.

Is this correct?
