### ISSUE TITLE
Auto-build no longer working after 'Reconnect Repository'

### ISSUE THREAD

**Issue by jdeeburke** [aws-amplify/amplify-hosting#2136]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2kp6mp7r2e3ac

### Region

us-east-1

### Amplify Console feature

Build settings

### Describe the bug

While trying to troubleshoot why Previews were not working correctly, I clicked 'Reconnect Repository'. This interface prompts me to delete the webhook on my git repository before continuing, which I did.

After completing the reconnection, I get the green notification saying it was successful, but the webhook is never re-created on my repo, and therefore auto-builds are no longer working.

### Expected behavior

I expect the 'Reconnect Repository' action to create a new webhook in my github repo so that Amplify will be correctly notified when there are changes pushed to my master branch.

### Reproduction steps

1. Click 'Reconnect Repository' and follow it to completion
2. Observe that no webhook is created in GitHub and changes made to `master` are no longer triggering  builds in Amplify.

### Additional information

I also attempted disabling and re-enabling Auto-build for my branch, but that didn't work.
I stopped short of deleting the branch in Amplify, because I didn't want my app to be deleted.

**Comment by amandarose42** [comment]
+1

**Comment by jdeeburke** [comment]
Little update here, I disconnected my `master` branch and attempted to re-connect, which only made things worse. It wouldn't re-create the deploy token needed to get _any_ further code updates from git, even when triggered manually.

Since this breaks our build process I resorted to creating a new Amplify app and moving things over, abandoning the old one.

Still can't get previews to work on the new one, but at least it's auto-building again. 🤷‍♂️

**Comment by amandarose42** [comment]
A workaround for this bug would be to re-setup web hooks. I know this is a little too late for @jdeeburke but for anyone else who gets stuck on this issue: 

https://aws.amazon.com/blogs/mobile/use-the-amplify-console-with-incoming-webhooks-to-trigger-deployments/
- _**I only needed to do Step 5 & 6 from the article linked above!**_
**Start at Step 5 (creating the webhook in Amplify) & mimic Step 6 but using the specific Github Repo (adding the webhook to Github Repo)**

I can confirm this workaround works.

**Comment by Athena96** [comment]
Hi, closing this issue out as it should be fixed now. Please feel free to re-open if you continue to face the issue. thanks!
