### ISSUE TITLE
Logged in as root, usual region, no apps rendering

### ISSUE THREAD

**Issue by weisisheng** [aws-amplify/amplify-hosting#2137]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-west-2

### Amplify Console feature

Not applicable

### Describe the bug

Been using Amplify about 18 months, depending on development plan, cycle between regions.  Currently logged in as root (I know, not best practice) and no amplify apps render in us-west-2.  There should be about ~10 frontend/back apps showing based on my dev/prod work.  I do have other apps in other regions.  I see this problem a few times a year and it usually rectifies itself in a few minutes.  In this instance, it has been 24 hours.  Please advise.

### Expected behavior

Ordinary access to my apps hosted in us-west-2.

### Reproduction steps

1.amplify push from local
2. got to cli in us-west-2
3. get the greeting to "add apps" and none of the others created over last 18 months shows.

**Comment by weisisheng** [comment]
Addendum: I can see apps created over time in us-east-1 and ap-southeast-2 as expected.

**Comment by victorccccc** [comment]
Hi, sorry for the inconvenience. Can you please send your Account Id to aws-amplify-customer@amazon.com? (Please include this Github issue link as the reference) Thanks!

**Comment by victorccccc** [comment]
Hi, sorry for the convenience, we've fixed this issue. Feel free to re-open if issue persists. Thanks
