### ISSUE TITLE
"Amplify Console requires you to have admin access to the repository." - Why?

### ISSUE THREAD

**Issue by a-h** [aws-amplify/amplify-hosting#2160]
I've set up a Personal Access Token for a Github user that's used for CI purposes. The token gives access to the repos, but the console complains that admin access is required.

<img width="700" alt="Screen Shot 2021-08-13 at 13 26 17" src="https://user-images.githubusercontent.com/1029947/129357194-248620da-c116-46a1-8df4-900d83c5aac3.png">

App ID can't be provided, because I can't create an app without giving my CI user admin access to the repo.
Region is eu-west-1

**Comment by a-h** [comment]
For clarity, I really wanted to use CDK:

```js
const amplifyApp = new amplify.App(this, 'xxx', {
    sourceCodeProvider: new amplify.GitHubSourceCodeProvider({
        owner: 'xxx',
        repository: 'xxx',
        oauthToken: SecretValue.plainText(process.env.CI_USER_PERSONAL_ACCESS_TOKEN as string)
    }),
});
amplifyApp.addBranch("main");
```

This was giving me the followign error message.

```
Resource handler returned message: "Invalid request provided: There was an issue setting up your repository. Please try again later.({"message":"Not Found","documentation_url":"https://docs.
github.com/rest/reference/repos#create-a-repository-webhook"}) (Service: Amplify, Status Code: 400, Request ID: 85d2b3bd-9801-4bbb-b787-3ca71e756eb0, Extended Request ID: null)" (RequestToke 
n: ac23db47-0ef6-4d29-ed0f-83eae4d37e3c, HandlerErrorCode: InvalidRequest) 
```

To debug the problem, I was trying to use the console.

In the console, I saw this message about a requirement to be an admin user (this isn't mentioned elsewhere I don't think).

I realised that deploying my CDK project from the CLI worked fine for me when I used my Github personal access token, but not my CI user. The difference is that I'm an `organization owner`, and the CI user is a `member`. I switched the CI user to be an `Owner`, and suddenly it worked.

I realised that by making the user an `Organization Owner`, I was also making them an "Admin" role in each repository, which set the flag in the API response to true, and made Amplify happy.

The right way to deal with this would have been to add my CI user to the repo as admin.

<img width="472" alt="Screen Shot 2021-08-13 at 15 40 17" src="https://user-images.githubusercontent.com/1029947/129374267-f92a3961-f9d8-485b-801a-5ca217856e2b.png">

Using Chrome debug tools, I noticed that the API call to Github was executing from the browser. In the GraphQL response, I could see some references to "admin", and I realised that it is just checking whether the user is an "admin" role of the repository. This doesn't seem right, because the CDK CI process just uses the personal access token, which has defined scopes.

I think the underlying problem is that Amplify is complaining that it needs to be an admin of the repo, when really, all it needs is a Github token with repo access, but there's no way to add that in the UI, so it asks for way more permission than required.

**Comment by ferdingler** [comment]
Hi @a-h, thank you for reaching out. 

When you create an Amplify app using GitHub as source, we use the provided oauth token to create a [Webhook](https://docs.github.com/en/developers/webhooks-and-events/webhooks/about-webhooks) and a [Deploy Key](https://docs.github.com/en/developers/overview/managing-deploy-keys) on your repository. The Webhook is used to listen for GitHub events to trigger Amplify CI/CD based on new commits to your connected branches, and the Deploy Key is used to pull code from your repo during a build.  

The [GitHub permission model](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization) requires Admin access to a repository in order to create webhooks and deploy keys. Which is why the UI shows grayed out those repos for which you are not an admin. And its likely the same reason why your CDK deployment fails. 

We will take the action item to improve our documentation around this subject to make it clearer.

**Comment by a-h** [comment]
The documentation says to use a Personal Access Token with the repo scope which is what I gave it.

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-amplify.GitHubSourceCodeProviderProps.html

```
oauthToken🔹
Type: SecretValue

A personal access token with the repo scope.
```

So the documentation is certainly part of the problem.

I don't want Amplify to create a Github Webhook and deploy key because that means giving a CI user admin rights.

I want to pass Amplify a Github deploy key, and for Amplify to then tell me where I should configure Github to send the Webhook.

**Comment by saviogl** [comment]
@ferdingler Anything on the pipeline to avoid requiring repo Admin permission - CI like credentials should especially follow the least privilege principle and this hard requirement (which by the way is not stated anywhere in the documentation) is really a non-starter for many people

**Comment by saviogl** [comment]
@ferdingler Anything on the pipeline to avoid requiring repo Admin permission - CI like credentials should especially follow the least privilege principle and this hard requirement (which by the way is not stated anywhere in the documentation) is really a non-starter for many people

**Comment by swaminator** [comment]
Please read this: https://github.com/aws-amplify/amplify-console/issues/1542#issuecomment-1049639904. Closing this thread so we can track it there.

**Comment by swaminator** [comment]
We now support GitHub apps to help with this: https://aws.amazon.com/about-aws/whats-new/2022/04/aws-amplify-hosting-github-access-workflows/.

Please let us know if you have any issues.
