### ISSUE TITLE
Nextjs Contentful not showing all images

### ISSUE THREAD

**Issue by Onibenjo** [aws-amplify/amplify-hosting#2171]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2fqmcz003hgr1

### Region

eu-west-2

### Amplify Console feature

Redirects

### Describe the bug

Some images do not load after the build and they are being fetched from contentful. Everything works fine locally

https://blog.daba.school/

I have tried adding the images rewrite/redirect rules, still no effect.

### Expected behavior

All images should show

### Reproduction steps

npm run build
npm run start

### Additional information

I have added this in the rewrite rules ```</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|woff2|ttf|map|json)$)([^.]+$)/>``` to point to ```https://d2jw0ckg3954v4.cloudfront.net/<*>```

**Comment by Onibenjo** [comment]
But it works with the cloudfront url

**Comment by Athena96** [comment]
hi @Onibenjo what version of Next.js are you using? and can you share any configurations you have in your next.config.js file. thanks

**Comment by Onibenjo** [comment]
@Athena96 
Next.js version 11.0.1

``` javascript
//next.config.js
module.exports = {
  images: {
    domains: ['images.ctfassets.net'],
  },
}
```

**Comment by calavera** [comment]
We're trying to reproduce this problem but it looks like everything is working ok, can you let us know if it's working as expected now?
