### ISSUE TITLE
Support PR Previews with subdomains

### ISSUE THREAD

**Issue by adamaltman** [aws-amplify/amplify-hosting#219]
**Is your feature request related to a problem? Please describe.**

One of our apps requires a secure cookie be set on our domain name.  The previews are built and available at a URL like this one: 
```
pr-xxxx.yyyyyyyyyyy.amplifyapp.com
```

**Describe the solution you'd like**

I would like to be able to replace amplifyapp.com (in that pattern above) with a custom domain, that's managed in route53, automatically.

**Additional context**

N/A

**Comment by mwarkentin** [comment]
We have this same issue - our auth token is stored in a secure cookie scoped to our domain, so we are unable to authenticate from our SPA deployed to the preview URL in amplify.

A wrinkle on our end is that our DNS is configured in Cloudflare, not Route53, so I'm not sure how the DNS update would work. 

One idea would be some sort of trigger from Amplify which could let us run a lambda to configure or delete DNS records when preview apps are generated or destroyed.

**Comment by swaminator** [comment]
@mwarkentin @adamaltman this is supported: https://aws.amazon.com/blogs/mobile/automatically-create-and-delete-custom-sub-domains-for-your-branch-deployments-with-amplify-console/

**Comment by davad** [comment]
FYI, looks like this option isn't available if you deploy your root domain _is_ a subdomain. You can manually create sub-subdomainds, but not automatically.

E.g. If the root domain for app is `demo.myapp.com`, you can manually create `pr-27.demo.myapp.com`, but the option to creatae it automatically isn't there.

![Screenshot from 2020-10-16 18-54-27](https://user-images.githubusercontent.com/190387/96354840-39ca2a80-10a9-11eb-9799-805f224bb93a.png)

**Comment by limxingzhi** [comment]
@davad and for anyone else who is looking at this tread, I found this AWS blogpost after searching the internet for hours:

https://aws.amazon.com/blogs/mobile/automatically-create-and-delete-custom-sub-domains-for-your-branch-deployments-with-amplify-console/

Under Step 4, you just have to let the branch pattern match `pr*` and it should work. It is not ideal and the official documentation might want to include this rather than pasting a one-liner.

**Comment by davad** [comment]
@limxingzhi FYI, that option isn't showing up in my applications. I'm guessing it's because I'm using a subdomain as my app domain (think 'admin.example.com' as the production domain with 'staging.admin.example.com' for a staging branch; I'd be hoping to get 'pr-1.admin.example.com' auto-generated)

**Comment by limxingzhi** [comment]
Only new PRs will show up. Your existing PRs will not be accessible.

**Comment by davad** [comment]
@limxingzhi Right, but I'm unable to enable 'Subdomain auto-detection' in the domain settings because that option doesn't show up for me.

**Comment by stanleegoodspeed** [comment]
@davad were you able to figure this out? seems like this is still an issue on Amplify

**Comment by tinynumbers** [comment]
From https://docs.aws.amazon.com/amplify/latest/userguide/to-set-up-automatic-subdomains-for-a-Route-53-custom-domain.html -

![image](https://user-images.githubusercontent.com/1790173/161571333-501e885a-382d-428f-b98f-6c4fd1fa0184.png)

Unfortunate. It would be ideal of auto creation of sub-sub domains could work for a setup where the primary domain is already a subdomain.

**Comment by croossin** [comment]
@davad Curious what solution you went with? We are using a non-subdomain url and I also don’t see that option. We are running into the same issue as you did.

**Comment by davad** [comment]
> @davad Curious what solution you went with? We are using a non-subdomain url and I also don’t see that option. We are running into the same issue as you did.

We ended up not making use of the PR auto-builds

**Comment by havgry** [comment]
@swaminator I don't understand why this is closed, because it's clearly not supported. The documentation you're linking to does only work for root domains and elsewhere it states that it is not supported for subdomains.

For me, preview builds is such an essential feature, that it effectively renders Amplify useless on subdomains for no apparent reason. This leaves me no option but to use Vercel or Netlify.

**Comment by aquacode** [comment]
Any update or projected timeline?

**Comment by croossin** [comment]
@Jay2113 are there any plans in supporting this? Would love to get an update.

**Comment by edufarre** [comment]
Any news on this? We have been struggling with this issue for a while. Do you guys have any intention to tackle it?

**Comment by jperetzIL** [comment]
+1

**Comment by fran-pb** [comment]
+1

**Comment by clark-pang** [comment]
+1

**Comment by airton** [comment]
+1

**Comment by saurabh-git-dev** [comment]
Recently team has updated the Amplify dashboard and They are now providing the option to enable automatic subdomain creation of non-root domains.
![image](https://github.com/aws-amplify/amplify-hosting/assets/68720731/a240cb01-4461-4425-83ed-a9d29787db33)

**Comment by swaminator** [comment]
As mentioned by @saurabh-git-dev this is now supported @adamaltman
