### ISSUE TITLE
301 Redirect 

### ISSUE THREAD

**Issue by marksteven** [aws-amplify/amplify-hosting#2218]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2hr9eo797b92w

### Region

southeast-2

### Amplify Console feature

Environment variables

### Describe the bug

Goal is to make a sub folder example.com/admin - index.html page redirect to admin.example.com and SHOW in browser as admin.example.com not example.com/admin

Multi folder React App with more than one index.html (NOT single entry standard React App)
EG
Root/ index.html
Folder /admin/index.html

Amplify Custom Domain - https://admin.example.com
Redirects to https://example.com/admin

Amplify -  Rewrites Redirects - Source address https://admin.example.com Target address https://example.com/admin Type rewrite 200 
So Rewrite is not working as expected.

Although this successfully allows admin.example.com to be typed into a browser and receive a successful page load.
But the browser shows example.com/admin not admin.example.com

This has been referred to AWS support
who have now asked me to submit this bug to GitHub to hopefully fix.

Regards
Mark
 

### Expected behavior

type into browser
admin.example.com

receive written in browser
admin.example.com

Not in browser
example.com/admin

### Reproduction steps

Build a Gatsby React App with at least one page other than Root Index
Building this App through Amplify will give a successful App with a Root Index.html
a folder and within that folder another index.html

Using both Domain management and Rewrites / redirects point any name to the sub folder index page

This will then work in browser but will not show correctly in browser as 
page.example.com
not example.com/page

### Build Settings

```yaml
Standard Gatsby App with more than one index page
```

**Comment by perdomofranklindev** [comment]
I have the same issue,  the redirect to external url does not work.

**Comment by perdomofranklindev** [comment]
I have the same issue,  the redirect to external url does not work.

**Comment by hloriana** [comment]
The team is aware of this bug and we are currently tracking this for prioritization. In an effort to deduplicate issues, we will close this issue in favor of https://github.com/aws-amplify/amplify-hosting/issues/2601. Please continue to track the progress of this bug using that issue. Thank you!
