### ISSUE TITLE
Amplify build fails and times out for React App

### ISSUE THREAD

**Issue by ScarletSpidey** [aws-amplify/amplify-hosting#2229]
I have been using Amplify to deploy my react application for a few months now, never faced any issues during the build stage, I have also tried to contact aws support services but this particular problem is a bit puzzleing for them too. 

Here is the log build log file:-
https://drive.google.com/file/d/1Ams-sLIHMscFS1j7o9fyBfI53FtMN3eC/view?usp=sharing

Here are my build settings:-
https://drive.google.com/file/d/1DF9n9nqMY5q5ATBvrRZeWmpCcMdihiqH/view?usp=sharing

Here is the package.json file for my project:-
https://drive.google.com/file/d/1Y7geq7pp09YSQMLUukU-5VuJUzHbDW12/view?usp=sharing

On my local machine I am able to create a build with no issues at all. 
Please let me know if you want any other details.

**Comment by behrooziAWS** [comment]
For the build you linked above, this is the error:

```
2021-09-03T07:51:46.193Z [INFO]: ./src/App.js
Cannot find module: 'react-ga4'. Make sure this package is installed.
You can install this package by running: yarn add react-ga4.
```

**Comment by RealDrewKlayman** [comment]
Looks related to: 
https://github.com/aws-amplify/amplify-console/issues/2098

But, they have not been responding on that issue.

**Comment by victorccccc** [comment]
Closing this issue, but feel free to re-open if issue persists. Thanks
