### ISSUE TITLE
PR not getting deleted from the Preview even after its merged to Main Branch

### ISSUE THREAD

**Issue by akanungo22** [aws-amplify/amplify-hosting#2273]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:eu-west-1:109735232192:apps/d3orjv9vmso7oh

### Region

eu-west-1

### Amplify Console feature

Previews

### Describe the bug

The PR is not deleted from console, even though the its merged to main branch.
https://eu-west-1.console.aws.amazon.com/amplify/home?region=eu-west-1#/d3orjv9vmso7oh/pr-1116/

### Expected behavior

Other PRs are deleted automatically once its merged to main branch. But this got stuck.

### Reproduction steps

Its stuck for one PR

### Build Settings

```yaml
not required
```

**Comment by kahdojay** [comment]
Closing in favor of https://github.com/aws-amplify/amplify-hosting/issues/2424, but please let us know you're still experiencing the issue.
