### ISSUE TITLE
Backend Branch Builds: Use a different auth configuration for Prod Environment

### ISSUE THREAD

**Issue by chrismilleruk** [aws-amplify/amplify-hosting#2277]
**Please describe which feature you have a question about?**

I'm using [Team workflows](https://docs.aws.amazon.com/amplify/latest/userguide/team-workflows-with-amplify-cli-backend-environments.html#standard) with [Federated Auth](https://docs.amplify.aws/lib/auth/advanced/q/platform/js/#federate-with-auth0) and [pattern based branch deploys](https://docs.aws.amazon.com/amplify/latest/userguide/pattern-based-feature-branch-deployments.html).

I'd like to use different auth settings for some environment (e.g. prod). 

My main reason for this is to suppress the use of localhost as a valid callback URL in production. Additionally, I'd like to add new urls to the WebClient callback URL as feature front ends are generated but want isolation from prod.

This seems like a common use case but I haven't seen any docs that solve this.

**Provide additional details**

I have tried:
- overriding the config with a backend specific environment variable (`AMPLIFY_WEBCLIENT_ID`)
  <details>
    <summary>This causes a build error: `OAuth properties for the app clients are not matching`</summary>
  
    ```
    2021-09-24T21:01:43.201Z [INFO]: [31mFailed to pull the backend.[39m
    2021-09-24T21:01:43.203Z [INFO]: [31mOAuth properties for the app clients are not matching.[39m
    2021-09-24T21:01:43.254Z [INFO]: [0mError: OAuth properties for the app clients are not matching.[0m
                                     [0m    at Object.headlessImport (/root/.nvm/versions/node/v12.21.0/lib
    ```
  </details>

- configuring `amplify checkout env prod`  with an alternate auth (`amplify auth remove` && `amplify import auth`)
  <details>
    <summary>This creates source code diffs which will move between branches:</summary>
  
    ```Diff
    diff --git a/amplify/backend/auth/simpleapp1f12c941/parameters.json b/amplify/backend/auth/simpleapp1f12c941/parameters.json
    deleted file mode 100644
    index 9dbbb6e..0000000
    --- a/amplify/backend/auth/simpleapp1f12c941/parameters.json
    +++ /dev/null
    @@ -1,6 +0,0 @@
    -{
    -  "authSelections": "userPoolOnly",
    -  "resourceName": "simpleapp1f12c941",
    -  "serviceType": "imported",
    -  "region": "us-west-1"
    -}
    \ No newline at end of file
    diff --git a/amplify/backend/backend-config.json b/amplify/backend/backend-config.json
    index b481bc2..d772b32 100644
    --- a/amplify/backend/backend-config.json
    +++ b/amplify/backend/backend-config.json
    @@ -22,7 +22,7 @@
         }
       },
       "auth": {
    -    "simpleapp1f12c941": {
    +    "simpleappd8c399ca": {
           "service": "Cognito",
           "serviceType": "imported",
           "providerPlugin": "awscloudformation",
    diff --git a/amplify/team-provider-info.json b/amplify/team-provider-info.json
    index 33ee09e..fda56c2 100644
    --- a/amplify/team-provider-info.json
    +++ b/amplify/team-provider-info.json
    @@ -85,7 +85,7 @@
         },
         "categories": {
           "auth": {
    -        "simpleapp1f12c941": {
    +        "simpleappd8c399ca": {
               "userPoolId": "us-west-1_JxPhYUJ5j",
               "userPoolName": "okta_amplify_backend",
               "webClientId": "6s4ixxxxxxxx9ui07",
    ```
  </details>

- both of the above plus a CLI `amplify push` __without__ committing the git diff above.
  This _sort of_ works but I'm not convinced that is will survive more than a few deploys and seems unstable. If there was a way of positively overriding the backend code config with an environment variable (or similar mechanism) then I would feel way more comfortable about this.

  I think this might also have caused a general corruption of the auth settings in the other environments. At one point, I had multiple `categories.auth.xxx` settings in `team-provider.json` after an `amplify env checkout`. With this configuration, the deployed app claimed there were no auth configurations.

**What AWS Services are you utilizing?**

Amplify, Cognito IdP

**Additional questions**

Is there a better way to achieve sensible isolation for the prod environment here? 
Do I need to use a new Amplify app? AWS Account?

Is there anything like protected environments on the roadmap (similar to [protected branches](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches)

Most of my efforts here were hampered by a general lack of observability. The backend build Auth tab has zero information in it. The admin UI is helpful but not quite enough detail. The logs are all over the place, is there a way to view all the disparate logs (cli, console build, cloudtrails, etc) in one searchable tool (e.g. opensearch)?

**Comment by chrismilleruk** [comment]
`App Id`: `d16xma096tmdk6`
`Region`: `eu-west-1`

**Comment by hloriana** [comment]
Closing this issue due to age. If anyone else runs into this use case please open a new issue.
