### ISSUE TITLE
Custom headers does not respect "pattern"

### ISSUE THREAD

**Issue by satispunk** [aws-amplify/amplify-hosting#2281]
Hello, using aws amplify with nextjs and  trying to setup custom headers
For example:

```yaml
customHeaders:
  - pattern: '**/*.woff2'
     headers:
  - key: 'Cache-Control'
     value: 'public, max-age=31536000, immutable'
```

But it also applies to every other response not just .woff2

Any idea or workaround?

AppID: d291k11419qkka Region: eu-central

**Comment by siegerts** [comment]
Hi @satispunk, thanks for opening. Do you mind providing more context (SSR?, build settings, etc.) and anything else that you may have customized? Thanks!

**Comment by ferdingler** [comment]
We are aware of an issue with pattern matching for custom headers that affects NextJs SSR apps. A fix is on the pipeline being rolled out. Apologies for the inconvenience!

**Comment by satispunk** [comment]
@siegerts 

We are using SSR. Everything else is nothing special, I've tried to set headers in next.config.js, but that doesn't help as seems nextjs overrides it to some default settings. So was hopting to use custom headers to achieve the result

@ferdingler 

Good to hear! Could you share if there is some ETA for this to be deployed or is it already?

**Comment by satispunk** [comment]
@ferdingler hi, any updates on this?

**Comment by laketea** [comment]
now is November，it seems all the project which use nextjs ssr will occured this problem, has any other temporary solution？

**Comment by kookster** [comment]
likewise, we are running into this as well, any update?

**Comment by kookster** [comment]
@ferdingler are you able to give an update?

**Comment by thevarunraja** [comment]
> now is November，it seems all the project which use nextjs ssr will occured this problem, has any other temporary solution？

Did you find any workaround?

**Comment by laketea** [comment]
@thevarunraja 

I found a way to solve this problem temporarily

Find the cloundfront id from the deploy log, then find the corresponding instance from the cloundfront console, and set your custom domain directly on this cloudfront instance, so you can bypass the amplify custom header problem.

The cloudfront caching policy works by default, automatically setting a negotiated cache for html and a long cache for static resources.

However, there is a problem that if you reconnect the branch, the cloudfront id will change, so until this is officially fixed, this is the only way to deal with it.

**Comment by thevarunraja** [comment]
> @thevarunraja
> 
> I found a way to solve this problem temporarily
> 
> Find the cloundfront id from the deploy log, then find the corresponding instance from the cloundfront console, and set your custom domain directly on this cloudfront instance, so you can bypass the amplify custom header problem.
> 
> The cloudfront caching policy works by default, automatically setting a negotiated cache for html and a long cache for static resources.
> 
> However, there is a problem that if you reconnect the branch, the cloudfront id will change, so until this is officially fixed, this is the only way to deal with it.

Thank you for your solution. Will try to implement this.

**Comment by AlexKomm** [comment]
Same problem here. Patterns are not working in Next.js SSR App. I think it's a critical issue that has to be solved. @ferdingler , do you have any updates regarding this? A lot of people are experiencing this issue

**Comment by AlexKomm** [comment]
@laketea, I would really appreciate it if you could explain in a more detailed way how you managed to solve this issue by adding these Cloudfront overrides you mentioned

**Comment by multivoltage** [comment]
Me too

**Comment by saadataz** [comment]
@satispunk we have deployed a fix for this. Can you please confirm if it is working for you now.

**Comment by satispunk** [comment]
> @satispunk we have deployed a fix for this. Can you please confirm if it is working for you now.

Great! Will do it next week

**Comment by StephaneBischoff** [comment]
Does not seem to work for me with my NextJS app with SSR. fonts are in the `public/fonts` folder.
fonts are stored in S3 Bucket.  
I have this `customHttp.yml` file. Yet, the `.otf` file have no` Cache-Control` header in response. 
Cloudfront has `x-cache: Miss from cloudfront`

```
customHeaders:
    - pattern: '*.otf'
      headers:
          - key: Cache-Control
            value: s-maxage=86400
```

**Comment by saadataz** [comment]
@StephaneBischoff `*.otf` would match the otf files only in at root e.g `/foo.otf`. If you want to match all the otf files including the ones in sub directories like `public/fonts`, try using `**/*.otf` instead

**Comment by StephaneBischoff** [comment]
Hi @saadataz, 

I have tried with this also and it does not seem to work. I see no `Cache-Content` header returned from requests.
I also tried a different test to see if I could get a header to be returned for any file:
- Added this test header to all files. 
- in AWS Amplify console, clicked the Redeploy this version.
![image](https://user-images.githubusercontent.com/9750058/159483221-0f8cfff6-27db-4998-a6f9-2724845772cd.png)

Yet, still nothing. FYI: I am looking at response headers in Chrome.
I see the response header  `server` listed as `AmazonS3` for fonts and `Cloudfront` for image files.
I must be doing something wrong. 

Thanks

**Comment by saadataz** [comment]
@StephaneBischoff can you please share your app ID?

**Comment by StephaneBischoff** [comment]
@saadataz  AppID: d249fcmqdu6stt Region: ca-central

**Comment by biller-aivy** [comment]
any news?

**Comment by StephaneBischoff** [comment]
@saadataz any update? thank you

**Comment by leftys** [comment]
customHeaders don't work for me at all. no matter if set via customHttp.yml or via Amplify interface in AWS console.

**Comment by markus-mw** [comment]
Same for me as for @leftys

**Comment by hloriana** [comment]
A fix has been deployed for this issue. Closing as resolved.
