### ISSUE TITLE
403 Forbidden create amplify

### ISSUE THREAD

**Issue by riyanefendy** [aws-amplify/amplify-hosting#2304]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

Southeast Asia

### Amplify Console feature

Access control

### Describe the bug

I want to make amplify, but when in the "save and deploy" section, an error message appears "Houston, there's a problem
There was an issue setting up your repository. Please try again later.({"message":"403 Forbidden"})". I have tried revoke on the gitlab application, and also clear cache and browser history. But still can't. Please help fix this problem :)
![Error aws 2](https://user-images.githubusercontent.com/92073210/136321961-ced41003-b0cf-4f43-b1d1-e8568c3dc3fe.PNG)
![error aws](https://user-images.githubusercontent.com/92073210/136321962-f65e2c1b-539f-459c-a77d-33eebb4a5be4.PNG)

### Expected behavior

Please help with this problem, because I can't join my team project

### Reproduction steps

![Error aws 2](https://user-images.githubusercontent.com/92073210/136321943-2cde3d4f-c813-4595-bcc6-ccdda17383b9.PNG)
![error aws](https://user-images.githubusercontent.com/92073210/136321946-fa5bd2ed-d5c2-4cd0-a51a-2949cf82a167.PNG)

**Comment by hloriana** [comment]
Hi @riyanefendy are you still running into this issue?
