### ISSUE TITLE
ACCEPT header stripped off by Amplify before forwarding request to target server

### ISSUE THREAD

**Issue by ssontakke** [aws-amplify/amplify-hosting#2316]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-west-2:840725391265:apps/d2i6qlt8w44ey

### Region

us-west-2

### Amplify Console feature

Not applicable

### Describe the bug

**Context**
We have a web application which has a functionality to download pdf, csv, xls, etc. Frontend hosted on Amplify and is a SPA. Frontend requests are routed to different external endpoints through Amplify Redirection/Rewrite Rules.

**Here is what is happening:**
Browser sends requests to Amplify hosted site - `domain.com/some-unique-path` to download a PDF. Request headers has ACCEPT = `application/pdf`.

Amplify has a redirection rule - 
``` 
{
 "source": "/some-unique-path/<*>",
 "target": "https://subdomain.domain.com/<*>",
 "status": "200",
 "condition": null
}
```

On target server `subdomain.domain.com`, we are not receiving the ACCEPT header. We also noticed that CONTENT_TYPE, HTTP_ACCEPT headers are also empty on the target server.

### Expected behavior

Amplify redirection shouldn't modify any headers. On the target server, we should get ACCEPT headers as it was passed by browser.

### Reproduction steps

1. Create a 200 redirection rule in Amplify like this:
``` 
{
 "source": "/some-unique-path/<*>",
 "target": "https://subdomain.domain.com/<*>",
 "status": "200",
 "condition": null
}
```
2. Do a curl call to Amplify hosted site and set ACCEPT = 'application/pdf'
3. Observe the headers received on target server. You will see ACCEPT header is stripped off.

**Comment by fnavarrodev** [comment]
What's the status of this request?

**Comment by jmcpeak** [comment]
I need the referrer header in my next 13 app - how can I get it?

**Comment by yahya-evoly** [comment]
> I need the referrer header in my next 13 app - how can I get it?

I reached out to AWS technical support regarding this issue recently. Unfortunately, they confirmed there's no direct solution at the moment. If anyone has discovered a workaround, I'd be keen to hear about it!

**Comment by jmcpeak** [comment]
Thanks for the response @yahya-evoly.

The AWS [link](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#request-custom-headers-behavior) @victorccccc gave for headers that _are_ passed was very helpful.

**Comment by calavera** [comment]
This feature has just been supported with our latest launch! I'm closing this issue as it's been resolved.

Check out the details here: https://aws.amazon.com/blogs/mobile/cdn-caching-improvements-for-better-app-performance-with-aws-amplify-hosting/
