### ISSUE TITLE
Build just started failing

### ISSUE THREAD

**Issue by CodySwannGT** [aws-amplify/amplify-hosting#2319]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3rbqv3ka0837l

### Region

us-east-1

### Amplify Console feature

Build settings

### Describe the bug

This just started happening. Whenever we kick off a build we get:

````
                                 # Starting phase: preBuild
                                 # Executing command: cd react-client
2021-10-13T15:54:00.256Z [WARNING]: /codebuild/output/src345981314/src/propswap-staging/amplify.sh: line 4: amplify: command not found
2021-10-13T15:54:00.274Z [INFO]: # Executing command: npm install
2021-10-13T15:54:00.274Z [WARNING]: /codebuild/output/src345981314/src/propswap-staging/amplify.sh: line 13: npm: command not found
2021-10-13T15:54:00.275Z [ERROR]: !!! Build failed
2021-10-13T15:54:00.275Z [ERROR]: !!! Non-Zero Exit Code detected
2021-10-13T15:54:00.275Z [INFO]: # Starting environment caching...
2021-10-13T15:54:00.276Z [INFO]: # Uploading environment cache artifact...
2021-10-13T15:54:00.346Z [INFO]: # Environment caching completed
Terminating logging...
````

To be clear. We didn't change any build settings for months

### Expected behavior

the app builds

### Reproduction steps

Attempt to build app from console or git push

### Build Settings

```yaml
`
version: 1
backend:
  phases:
    build:
      commands:
        # - '# Execute Amplify CLI with the helper script'
        # - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - cd react-client
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: /react-client/build
    discardPaths: true
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - react-client/node_modules/**/*
````
```


### Additional information

_No response_

**Comment by hloriana** [comment]
Hi Cody👋🏽, glad you were able to resolve the issue. Currently, environment variables can only be set via the console but we do appreciate your feedback and will take your use case under advisement. Thank you!
