### ISSUE TITLE
Github checks not completing with Monorepo and Preview

### ISSUE THREAD

**Issue by arledesma** [aws-amplify/amplify-hosting#2366]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d20zy0pum5arn5, d3127if6i267u2, d1d91c9119qjjz, d3jyfteqrhguhk, d1p3gr3fra14kj

### Region

ap-southeast-1

### Amplify Console feature

Monorepo, Previews

### Describe the bug

When a PR is opened in GitHub we are correctly seeing the Preview build initiated in each of our apps.

![image](https://user-images.githubusercontent.com/4999353/140418473-d80865df-8b28-406d-a624-6907e9f09cfb.png)

The Preview build starts for each of the apps and we see a single GitHub check named _AWS Amplify Console Web Preview_.

![image](https://user-images.githubusercontent.com/4999353/140418560-6d6983d2-6dbf-4187-87a9-d59d7915b6fd.png)

The message of the GitHub status states: _Queued — Waiting to run this check..._

Upon completion of the Preview builds in amplify we do not see the check status updated to indicate the successful build.

![image](https://user-images.githubusercontent.com/4999353/140418636-df5f9fe2-2df7-4d97-bae7-3333803c4fd5.png)

We have had to remove branch protection for this check due to it being unreliable.  

This leads us to login to manually checking the status of each Preview build, causing our Review process to include the additional following steps.

1. Login to AWS
2. Go to Amplify
3. Go to the first app
4. Go to the Preview tab
5. Check the status of the Preview build associated with the Pull Request
6. GOTO 3 until all apps in this monorepo are validated

### Expected behavior

Each GitHub check will be completed with the build status and be represented within the GitHub Pull Request.

### Reproduction steps

1. Create a monorepo in GitHub
2. Create multiple Amplify Apps configured for the GitHub monorepo
3. Enable Preview builds in all Amplify Apps
4. Create a new branch in the monorepo
5. Create a commit in the new branch (can be any change or an empty changeset - the message should not include `[skip-cd]`)
6. Open a Pull Request from the new branch

### Build Settings

```yaml
Not Applicable
```

**Comment by hloriana** [comment]
Hi @arledesma 👋🏽, thank you for raising this and for providing repro steps. We've identified this as a bug and are working on this.

**Comment by victorccccc** [comment]
Sorry for the inconvenience, we've fixed this issue. Feel free to reopen if issue persists
