### ISSUE TITLE
Cannot delete an environment

### ISSUE THREAD

**Issue by OlgaMaslova** [aws-amplify/amplify-hosting#2369]
**Which Category is your question related to?**

Delete an environment. I want to completely remove an existing environment. Through console, I chose Delete  that resulted int th following error:
`Deletion failed ValidationException - An error occurred while processing your request: null`

**Amplify CLI Version** 

6.3.1

**AppID and Region**
do5lfh5kuwuas, eu-west-1

**What AWS Services are you utilizing?**
Amplify console

**Provide additional details e.g. code snippets**
![image](https://user-images.githubusercontent.com/29795366/140495725-d7d4c5e2-9d1a-41f3-bfd8-72f804228039.png)

**Comment by hloriana** [comment]
Hi @OlgaMaslova 👋🏽, sorry you're experiencing this. 

Can you try running `delete-backend --app-id <value>  --backend-environment-name <value>` and see what output you get? 

ref: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/amplifybackend/delete-backend.html

**Comment by jamescrowley** [comment]
I have the same issue. I received 

"{
    "AppId": "XXXXX",
    "BackendEnvironmentName": "dev",
    "JobId": "00bcda37-3391-46a1-8b0a-559a70475811",
    "Status": "PENDING"
}
"

when running that command from the CLI. and then

An error occurred (ValidationException) when calling the GetBackend operation: ValidationException - An error occurred while processing your request: null

when running `get-backend`

**Comment by OlgaMaslova** [comment]
Hi @hloriana ,

here is what I see after running delete-backend:
`{
    "AppId": "do5lfh5kuwuas",
    "BackendEnvironmentName": "prod",
    "JobId": "b26061a6-3c3d-4e31-be40-bcbf3cb1663c",
    "Status": "PENDING"
}`

**Comment by hloriana** [comment]
Thank you @OlgaMaslova and @jamescrowley for providing us this information. Does this behavior happen when attempting to delete other backend environments or is this a random occurrence? 

I just deleted some backend environments using both methods and didn't run into this issue. It would be super helpful if either of you could provide reproduction steps so I can understand what's causing this. 

Finally, try this command `amplify env remove <env-name>` and see if that gives you any more information.

**Comment by OlgaMaslova** [comment]
@hloriana  `amplify env remove <env-name>` gives `No environment found with the corresponding name provided`.

For other envs everything was ok. The only difference is that when creating this enviroment with `amplify add env` I cancelled the procedure with ctrl-c in the middle since I realized that I was missing some files... I guess since the creation was aborted the environment is in somewhat unfinished state now...

**Comment by hloriana** [comment]
@OlgaMaslova  Okay last thing, can you look in the CloudFormation console and see if the stack associated with that environment still exists?

Marking this as a bug.

**Comment by hloriana** [comment]
**Reproduction Steps**:

1. Start to create a backend environment via the CLI
2. Cancel the action when the `initializing...` message shows up.
3. Notice the action will be aborted but the environment is listed in the console.
4. Delete the environment via the console. Notice the process fails with `Deletion failed ValidationException`.

**Comment by OlgaMaslova** [comment]
@hloriana yes, I habe only this:
![image](https://user-images.githubusercontent.com/29795366/141437937-42eb9aa6-05bb-4958-bc0d-e1ac74ca91c9.png)

**Comment by jamescrowley** [comment]
I was able to resolve the issue by deleting the parent cloud formation stack directly, then deleting the back-end environment in amplify, and then deleting the connected branch to remove the front-end environment.

**Comment by Lorenzohidalgo** [comment]
hey @hloriana @josefaidt ,

I encountered the same issue, but in my case, the production environment of another app was deleted. how can I recover/restore this??

**Comment by johnpc** [comment]
As of 9/26/2022 several updates have been released that fix issues deleting apps/backends, including the issue reported here: 

```
Deletion failed ValidationException - An error occurred while processing your request: null
```

**Comment by nadetastic** [comment]
Related https://github.com/aws-amplify/amplify-hosting/issues/882
