### ISSUE TITLE
Adding domain adds trailing slash to CSS

### ISSUE THREAD

**Issue by liquidpeachy** [aws-amplify/amplify-hosting#2414]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

https://eu-west-2.console.aws.amazon.com/amplify/home?region=eu-west-2&code=46353428bac8180cc3e1

### Step

Domain

### Status

Success

### Issue or question

When I use the default amplify subdomain, my CSS file works fine. But when I add my domain to the site, Amplify adds a trailing slash to the .CSS file. Therefore my CSS never loads. I've tried using rewrite rules to mitigate it, but it doesn't work.

**Comment by wwb00** [comment]
Hi, I am having the same issue. My site deploys properly on the amplify subdomain, but fails to load CSS on the custom domain.

**Comment by saadataz** [comment]
The issue no longer reproducible
