### ISSUE TITLE
Deployment gets stuck with "Waiting to deploy  Your deployment is being queued..."

### ISSUE THREAD

**Issue by dspinellis** [aws-amplify/amplify-hosting#2428]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dobcx0o9ofg17

### Region

eu-west-1

### Amplify Console feature

Manual deploys

### Describe the bug

When we try to deploy the app from an s3 bucket, the deployment process gets stuck with a "Waiting to deploy" "Your deployment is being queued..." message.  No build details are listed, and the "Deployment history" window gets stuck with a "Loading" message. This happens on the web console both with a user with admin rights and with the root user.

### Expected behavior

The app should eventually deploy.

### Reproduction steps

The steps are as described [here](https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html):

1. Sign in to the AWS Management Console and open the Amplify Console
2. At the top of the page, choose Get started.
3. In the Deliver section, choose Get started.
4. On the Host your web app page, choose Deploy without Git provider. Then, choose Continue.
5. In the Start a manual deployment section, for App name, enter the name of your app.
5. For Environment name, enter `test`
6. For Method, choose Amazon S3.
7. For Bucket, select the name of the bucket from the list. (The bucket should not have enabled ACLs.)
8. For Zip file, select the name of the zip file to deploy.
9. Choose Save and deploy.

### Additional information

Similar (closed but unresolved) issues: #1724, #1455, #1003.

**Comment by asumvp** [comment]
I was also facing this issue few days back and was able to solve it after enabling the ACL on the S3 bucket.

**Comment by dspinellis** [comment]
Thank you @asumvp! I confirm that enabling ACL on the S3 bucket, allowed the app to be deployed in seconds.

**Comment by hloriana** [comment]
Hi @dspinellis and @asumvp, the team is tracking this bug and working on fixing this. I will update this issue once it's been resolved. Thanks!

**Comment by hloriii** [comment]
Closing since enabling ACL on the S3 bucket resolved the issue. This is also outlined in step 8 in our guide for setting up manual deploys with S3: https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html#amazon-s3-or-any-url
