### ISSUE TITLE
Cannot connect to amplify domain when using 1.1.1.1 as my DNS

### ISSUE THREAD

**Issue by stevensacks** [aws-amplify/amplify-hosting#247]
**App Id**: not sure
**Region**: us-east-2 (Ohio)
**Step**: Verify
**Status**: Site is built, cannot access when DNS is 1.1.1.1.

**Issue/question**
I've set my DNS to Cloudflare's 1.1.1.1 on my computer. When it's on CloudFlare, I am unable to access my production branch URL after the build is complete. Technically, it's a dev subdomain branch, but that's besides the point.

If I switch from CloudFlare to google's 8.8.8.8, or even the default provided by my ISP, the url loads just fine. It also loads fine from my iPhone.

I do not know why, but when my DNS is set to 1.1.1.1, the url becomes unreachable. I can wait days and nothing changes so it has nothing to do with propagation. It's not just me. A coworker on the other side of the world changed his DNS to CloudFlare's 1.1.1.1 and immediately he was unable to reach the site. Changed it back, and instantly it loads again.

How do I resolve this?

**Error message**
```
This site can’t be reached
{url}’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN
```

**Comment by kahdojay** [comment]
Hi @stevensacks, thanks for reporting this. We will need to take a closer look and have added this to our backlog.

**Comment by munkhbayar17** [comment]
Hi guys, how is it going? @kahdojay . My domain is also not resolving with DNS_PROBE_FINISHED_NXDOMAIN though I have configured CNAME as requested on Cloudflare.

**Comment by mediamaxdk** [comment]
any solution to this issue?

**Comment by calavera** [comment]
This is a duplicated of https://github.com/aws-amplify/amplify-hosting/issues/2125 I'm going to close this issue, so all communications are centralized in one place.
