### ISSUE TITLE
Self-created backend environments in Amplify Console

### ISSUE THREAD

**Issue by sorokinvj** [aws-amplify/amplify-hosting#2491]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3cnnb5omq5kf5

### Region

eu-west-1

### Amplify Console feature

Access control, Backend builds

### Describe the bug

How do all of these environments happen to be created? I didn't do that, I don't need them. Am I paying for resource allocations related to these? How to get rid of the all? Mine are highlighted with red on the screenshot below, all others were created not by me and I really want to get rid of them as soon as possible

![2022-01-06_16-46-05](https://user-images.githubusercontent.com/4914235/148421361-66768e9d-e74d-4a23-a900-9217ac749c9b.png)

![2022-01-06_16-48-52](https://user-images.githubusercontent.com/4914235/148421381-0011c755-47a5-4b17-aeee-14f4329eddd6.png)

### Expected behavior

No resources allocated without my permission

### Reproduction steps

I have no idea to be honest

**Comment by swaminator** [comment]
Are all those environments created from people you know?

**Comment by hloriana** [comment]
Hi @sorokinvj 👋🏽 can you confirm the version of the Amplify CLI used when you first created this app and the version of the CLI that's being currently?

**Comment by sorokinvj** [comment]
@hloriana sorry for being silent! how do I know the version of the CLI when I first created this app? current is latest, 7.6.15. Autodetection was "on" when this issue appeared. I deleted now all Studios and turned it off, after that nothing popped up again

**Comment by sorokinvj** [comment]
> Are all those environments created from people you know?

@swaminator nope, they were created I don't know how and for who. These are fake names

**Comment by hloriana** [comment]
Hi @sorokinvj those names are generated by Amplify when a customer specifies that they want a new backend to be created upon deployment. This is usually indicated when branch autodetection is enabled with "create new backend" feature selected. You said you disabled that feature but more backends were created so we will investigate what other setting could be enabled that is causing this. Will respond once I have more information.

**Comment by hloriana** [comment]
It looks like you still have branch autodetection enabled. Please let us know if you're still experiencing this behavior when the feature is disabled.

**Comment by hloriana** [comment]
Closing due to age. Please re-open if this issue occurs again.
