### ISSUE TITLE
Issue while accessing the Application URL

### ISSUE THREAD

**Issue by sh319941** [aws-amplify/amplify-hosting#2501]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-west-1:239915762737:apps/d23p0n9rs0u6kw

### Region

us-west-1

### Amplify Console feature

Manual deploys

### Describe the bug

I am getting 404 page not found error while opening my Application 

URL :https://main.d23p0n9rs0u6kw.amplifyapp.com/

### Expected behavior

I am expecting to view my website data while browsing the URL

### Reproduction steps

NA

### Build Settings

```yaml
NA
```

### Additional information

NA

**Comment by hloriana** [comment]
Hi @sh319941 👋🏽, thanks for raising this issue! I'm investigating this behavior and will report back once I've found the cause of this error.

**Comment by hloriana** [comment]
There was likely a delay after the deployment finished but your app should've been available to view. Are you still experiencing this behavior?

**Comment by sh319941** [comment]
It's resolved now
