### ISSUE TITLE
Framework not automatically detected and deployment is failing

### ISSUE THREAD

**Issue by jrcryer** [aws-amplify/amplify-hosting#2520]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dr3giorghk4q1

### Region

eu-west-2

### Amplify Console feature

Build settings

### Describe the bug

The framework is not detected automatically and deployments are failing with the following error:

```
2022-01-17T13:03:11 [INFO]: Beginning deployment for application dr3giorghk4q1, branch:main, buildId 0000000004
2022-01-17T13:03:11 [INFO]: Cannot find any generated SSR resources to deploy. If you intend for your app to be SSR, please check your app Service Role permissions. Otherwise, please check out our docs on how to setup your app to be detected as SSG (https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app)
2022-01-17T13:03:11 [ERROR]: {"code":"7","message":"No ssrResources.json file"}
```

The application is a React app but it looks like it believes it should be a Next application.

### Expected behavior

Application deployed

### Reproduction steps

1. Push code to git repository
2. Monitor build

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by hloriana** [comment]
Hi, apologies for the delay it looks like your baseDirectory needs to be set to .next. If you're still running into this issue please feel free to reopen.

**Comment by mauerbac** [comment]
Hey @hloriana - I think the issue is referring to the service misidentifying Next instead of React. sounds like this developer isn't using Next but rather a React app. Can we reproduce?

**Comment by NotSoShaby** [comment]
We are getting the same error when trying to remove next from our project. Currently the project does not contain next.js and works fine locally, but on the server fails on the deploy stage with the same error. How can we remove this coupling to next? I also see that the `Framework` section in the general settings is grayed out and uneditable

**Comment by hloriana** [comment]
I'm unable to reproduce this behavior however this can be worked around by changing the framework and platform via the AWS CLI:

Change platform to `WEB`
`aws amplify update-app --app-id <APP_ID> --platform WEB --region <REGION>`

Change framework to `React`
`aws amplify update-branch --app-id <APP_ID> --branch-name <BRANCH_NAME> --framework React --region <REGION>`
