### ISSUE TITLE
Domain appears connected to old/lost Amplify configuration

### ISSUE THREAD

**Issue by kevinpowe** [aws-amplify/amplify-hosting#2535]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dlvydzp66tl8o

### Region

us-east-1

### Step

Previously existing website

### Status

App not available

### Issue or question

I've recently reenabled my account after some billing configuration issues. Now that it's reenabled, I'm having issues with AWS Amplify.

My previously configured websites (3 in total) have disappeared, and when I attempt to create a new AWS Amplify configuration in the us-east-1 region, the app disappears (even after clicking save-and-deploy) once I change regions or click out of the app configuration.

The account ID listed in the error message below is not my AWS app ID, but I'm the only person who has used this domain or has access to it. I've since deleted all relevant CNAME records from my DNS configuration for the domain in the hope that will help. (with the exception of the domain ownership record)

Now, each time I attempt to register the domain with the following configuration:
Add Domain - tavernofvoices.com
Exclude root
Add subdomain 'web'
Click Save

AWS Amplify successfully goes through SSL creation and configuration, then fails at Domain Activation with the error message added to the Error message field.

### Error message

Error message: [CNAMEAlreadyExistsException] The following CloudFront distributions are already using one or more of your domains: [Distribution: *******SS50KAW in AWS Account: ******171576]. 

### Additional information

I've checked the Cloudfront configuration for my account, and there are no registered Distributions. I've gone through the regions available for AWS Amplify to verify that there are no existing apps (just in case) and there are none. Previously I was using the us-east-1 region.

**Comment by hloriana** [comment]
Hi @kevinpowe it looks like you have apps in us-east-1 as well as ap-southeast-2. You can try to run the `get-app` command to get more information about your app https://docs.aws.amazon.com/cli/latest/reference/amplify/get-app.html. You can then try to delete the domain association from the app in us-east-1 by using this `delete-domain-association` CLI command https://awscli.amazonaws.com/v2/documentation/api/latest/reference/amplify/delete-domain-association.html. 

We are also investigating the issue with not being able to list your apps.

**Comment by hloriana** [comment]
This issue has since been mitigated. Please open a new issue with the bug report template if you require further assistance. Thank you!
