### ISSUE TITLE
One-click deploy does not work

### ISSUE THREAD

**Issue by paulocoutinhox** [aws-amplify/amplify-hosting#2544]
**Which Category is your question related to?**
Python as Frontend Generator

**Amplify CLI Version** 
7.6.12

**What AWS Services are you utilizing?**
amplify only

**Provide additional details e.g. code snippets**
Hi,

I made a project called Kaktos that is a static site generator using Python (don't have/need backend).

To generate i only need execute two things:

```
python3 -m pip install -r requirements.txt
python3 kaktos.py build
```

It will generate a folder called `build` and it will be deployed.

Now, i want add a button for deploying to Amplify. I search a lot about it for Amplify, but 99% of articles is related to Python for backend (functions etc).

How i can add support for the same thing for Amplify, generating all static files using it?

Thanks.

**Comment by hloriana** [comment]
We were able to reproduce this behavior and have added this to our backlog for prioritization.

**Comment by hloriii** [comment]
This functionality has been recently fixed. Marking this issue as resolved.
