### ISSUE TITLE
All of my apps have disappeared from Amplify

### ISSUE THREAD

**Issue by lewisdonovan** [aws-amplify/amplify-hosting#2546]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d280uf4ztky835 (and others)

### Region

us-east-1

### Amplify Console feature

Not applicable

### Describe the bug

Literally all of my Amplify apps have disappeared from the console. When I create a new app, I get an error message that says `App with id: <APP-ID> not found`. 

I have tried the following locally:

`amplify status && amplify init && amplify pull && amplify push`

It hasn't worked. I get differing errors each time I try to push, the latest being this:

```
UPDATE_FAILED      rOutputLambdaTriggerFunction AWS::CloudFormation::Stack Thu Jan 27 2022 13:37:45 GMT-0500 (Eastern Standard Time) Stack:arn:aws:cloudformation:us-east-1:767995013239:stack/amplify-sonxsplash-dev-212614-videosonxOnePagerVod-533E8D-rOutputLambdaTriggerFunction-D1S3IEAM8NG4/b3f9f3a0-4242-11ec-bcdb-0a7663231551 is in DELETE_COMPLETE state and can not be updated.
UPDATE_FAILED      rInputLambdaTriggerFunction  AWS::CloudFormation::Stack Thu Jan 27 2022 13:37:46 GMT-0500 (Eastern Standard Time) Resource update cancelled    
```

The wierdest thing is that the apps are actually still there, and they still build when I push and merge changes to CodeCommit (I know this because I changed some copy in the repo, pushed to CodeCommit and merged to live, and it updated on my live site), but I just can't see or manage the apps in Amplify.

### Expected behavior

Being able to see my apps

### Reproduction steps

1. Go to Amplify in the AWS Console.
2. Cry.

### Build Settings

```yaml
Autodetected (React, Gatsby)
```

**Comment by lewisdonovan** [comment]
Just a quick update, I've managed to successfully run `amplify push` on one of my apps, after deleting the stack and associated resources and re-running `amplify init`, but the app is still not showing in my dashboard. I'm now absolutely stumped, it feels like the dashboard and my actual account state are not in sync.

**Comment by hloriana** [comment]
Hi @lewisdonovan 👋🏽 thanks for raising this issue. Can you make sure that you're looking in the correct AWS region? If your console is set to a different region from where the apps are actually deployed then you won't be able to see them.

**Comment by lewisdonovan** [comment]
Hi @hloriana, yes I have double checked the region and have also changed and changed back to the correct region. The apps are still not displaying.

**Comment by hloriana** [comment]
Okay thank you for checking we are investigating this internally and will get back to you with more information.

**Comment by hloriana** [comment]
@lewisdonovan can you confirm that you're able to see your apps now?

**Comment by lewisdonovan** [comment]
@hloriana yes, thanks so much! Do we know what the issue was? Want to avoid this happening again in future, so would be good to know if it's anything our end. Thank you.

**Comment by ElyYonce** [comment]
Hi @hloriana, I'm experiencing the same issue.

appid - d1u56ep7p49azn

`aws amplify list-apps --region us-east-1` returns 
{
    "apps": []
}

The app is up, running, and connected to my CodeCommit repo, although, the app isn't displaying in the console. The app was created in the east-1 region and I've checked there and in all other regions and no dice.

**Comment by hloriana** [comment]
@lewisdonovan this was not an issue on your end. @ElyYonce are you still running into this problem?
