### ISSUE TITLE
amplifyPush --simple fails when removing graphql API model

### ISSUE THREAD

**Issue by gakinson** [aws-amplify/amplify-hosting#2553]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1he6253vtkqx8

### Region

us-east-2

### Amplify Console feature

Backend builds

### Describe the bug

We removed an api graphql model and we are unable to deploy using the amplify CI/CD due to the following error:
```
2022-01-31T03:25:00.558Z [INFO]: [0mDestructiveMigrationError: Removing a model from the GraphQL schema will also remove the underlying DynamoDB table.[0m
                                 [0mThis update will remove table(s) [XXXXXXXX][0m
                                 [0mALL EXISTING DATA IN THESE TABLES WILL BE LOST![0m
                                 [0mIf this is intended, rerun the command with '--allow-destructive-graphql-schema-updates'.[0m
                                 [0m    at cantRemoveTableAfterCreation (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/sanity-check.ts:422:11)[0m
                                 [0m    at sanityCheckDiffs (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/sanity-check.ts:59:9)[0m
                                 [0m    at sanityCheckProject (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/sanity-check.ts:41:21)[0m
                                 [0m    at buildProject (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:68:5)[0m
                                 [0m    at transformGraphQLSchema (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/transform-graphql-schema.ts:534:29)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:166:5) {[0m
                                 [0m  removedModels: [ 'XXXXXXXXX' ],[0m
                                 [0m  replacedModels: [],[0m
                                 [0m  toString: [Function (anonymous)][0m
                                 [0m}[0m
```

I tried adding a parameter to the amplifyPush command in the build.yml file, but still no luck.

I understand why the protection is there, but we would like to move forward with the change.

### Expected behavior

Ability to use the Amplify CI/CD web ui console to deploy a change that involves removing an api graphql model

### Reproduction steps

1. Remove a graphql schema type that is annotated with @model
2. Start deploy process

**Comment by duranmla** [comment]
In my case what I have done is to come to my branch _(the intended one to be deployed)_ and deploy from my local machine using the flag `--allow-destructive-graphql-schema-updates` in the end `amplifyPush` suppose to be a script to deploy detecting the right env to deploy but if we manually deploy from local we know what and where to deploy. In my case:

1. `git checkout develop`
2. `git pull`
3. `amplify env checkout staging`
4. `amplify push --allow-destructive-graphql-schema-updates`
5. Then I re-run the failed build _(to make sure the deploy to the custom url take place)_

🎉 

Nonetheless, I am agree we need to have a solution to make sure the CI does this and avoid developers to manually have to update the infrastructure before being able to deploy.

**Comment by hloriana** [comment]
Hi @gakinson thank you for raising this issue. Can you please try @duranmla's suggestion so you can move forward with this change? We will further investigate this behavior on our end.

**Comment by gakinson** [comment]
Hello,

I was able to do this for our beta environment, but for some reason, when I did another deploy after using the CI/CD, it was still failing saying it was destructive. Not sure if there was some sort of amplicy cli issues with the staged/tiered deploy.

In the end we were able to overcome this by changing our deploy pattern, but we are still unable to delete the tables. This is something we will be doing in the future and would like to do it through the CI/CD, but if it comes to it, we can deploy from our local.

It would be great to get this feature though on the CI/CD deployment process. Even if it was an ENV variable or something.

Thank you,
Geoffrey Kinson

**Comment by myartsev** [comment]
+1.
This issue appears to prevent anyone from removing graphql models while using the Amplify CI/CD pipeline.
@gakinson, how did you modify your deploy pattern to get your subsequent CI/CD builds to work?

**Comment by gakinson** [comment]
@myartsev Instead of deleting the resource, I just ended up leaving it existing until the amplify team can resolve this issue. But if we wanted to, we could pull the environment locally and push the change, but we are refraining from that for now since it is okay that the resource sits there unused until this is addressed.

**Comment by gakinson** [comment]
@myartsev Sorry, I didn't really answer your question. I should have mentioned that my initial goal was to delete and rename a model with different indexes. We ended up keeping the same model name, but deployed each key change. I should have clarified this on my earlier comment as it was kind of irrelevant to the main issue.

**Comment by gakinson** [comment]
@hloriana I was wondering if there was any progress/update on this issue?

**Comment by shubhamsharma04** [comment]
Hi all 👋 Thanks for your patience. We have released support for these type of operations via CI/CD as well. To be able to use Amplify CI/CD for changes which requires replacement of the underlying DynamoDB table, including removing a graphql model, please add an environment variable `AMPLIFY_DESTRUCTIVE_UPDATES` and set it to `true`.

Please feel free to re-open this issue if you encounter any problems

**Comment by myartsev** [comment]
@shubhamsharma04 thank you! does this require an update to the CLI (which version?) or is it purely a backend fixed that's already been deployed on your side?

**Comment by shubhamsharma04** [comment]
@myartsev Of course! This does not require an update to CLI. It is purely a backend fix
