### ISSUE TITLE
Can not access list of Amplify apps

### ISSUE THREAD

**Issue by zamargab** [aws-amplify/amplify-hosting#2569]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

https://us-west-2.console.aws.amazon.com/amplify/home?region=us-west-2#/

### Region

us-west-2

### Amplify Console feature

Access control

### Describe the bug

I am trying to login to Amplify console, but I am getting the error below

List apps call failed
Network Failure

### Expected behavior

I expect to see the list of apps I have created in Amplify

### Reproduction steps

Create an Account

Create an app in Amplify

Logout and try to login

**Comment by gnsslrrcs** [comment]
Hello, we are also experiencing the same issue? What is the fix for this?

**Comment by zamargab** [comment]
> troubleshooting FAQ

Hello.. have you looked into this? also, its not possible to submit an App id as this issue isn't specific to a particular app but rather the entire console. It doesn't even load my apps and I have already submitted details for region

**Comment by hloriana** [comment]
Hi @zamargab and @gnsslrrcs can you confirm that your user has permissions to list apps: https://docs.aws.amazon.com/amplify/latest/userguide/security_iam_permissions-reference.html

**Comment by zamargab** [comment]
![Screenshot 2022-02-09 at 00 02 16](https://user-images.githubusercontent.com/75364779/153185877-9afe94f9-8b66-4524-84fa-06ed846876b2.png)
Yes , the user has permissions to list apps, Everything was working just a couple of days ago and I didn't change any settings at all.

**Comment by McLeroy** [comment]
I have this same issue.
I used to have 5 apps on the Amplify Console. Just yesterday I logged in and all my apps were gone.
I even tried creating a new app but immediately I navigate to "All apps" the app is gone. Yes, I know Amplify is region specific. I created the app in "us-east-1" and tried to query it in "us-east-1". 
I have attached a drive video link to better explain.

[https://drive.google.com/file/d/1IGwUMN8XDFDRkWZzTrXM83NC5PTXdY6Y/view?usp=sharing](url)

**Comment by hloriana** [comment]
@zamargab @McLeroy @gnsslrrcs we are investigating this currently. I will update you all shortly.

**Comment by hloriana** [comment]
@zamargab @McLeroy @gnsslrrcs if you're still experiencing this issue can you please provide an AppID and region so we can further investigate what could be preventing you from listing your apps?

**Comment by McLeroy** [comment]
@hloriana I don't know how to get an AppID when I can't even create apps. I just noticed this happens in only "us-east-1" region

**Comment by hloriana** [comment]
> @hloriana I don't know how to get an AppID when I can't even create apps. I just noticed this happens in only "us-east-1" region

see if you can run this command via the CLI: https://docs.aws.amazon.com/cli/latest/reference/amplify/list-apps.html

**Comment by McLeroy** [comment]
@hloriana This is the result of `aws amplify list-apps`
{
    "apps": []
}

But I get all the apps I created in `us-east-2` when I run `aws amplify list-apps --region us-east-2`

**Comment by hloriana** [comment]
@McLeroy and @zamargab Please email aws-amplify-customer@amazon.com with your information and the link to this GitHub issue. We would need an AppID and region or an account number to further investigate since this doesn't appear to be a policy issue. Alternatively, you can also open up a ticket with AWS Support: https://console.aws.amazon.com/support/home#/
