### ISSUE TITLE
XML file does not appear to have any style information associated with it

### ISSUE THREAD

**Issue by tsundzu-skylight** [aws-amplify/amplify-hosting#2571]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2izvo1zwyytn6

### Region

us-east-2

### Amplify Console feature

Build settings

### Describe the bug

I have an app on amplify that connects to github repo to deploy. 
The deploy is successful but when I click the link to access the app I receive this error - _This XML file does not appear to have any style information associated with it. The document tree is shown below._

I have tried implementing the previous solution related to this error mentioned in this forum but it caused the Build stage to fail and not deploy the app successfully.

Scenario 2 -

I have another app where I tested deploying the HTML app using the drag and drop function. The app deploys successfully and I can open the app. The App uses AWS services such as API, Lambda and DynamoDB tables. I made a change to HTML code (adding another label), re-deployed the app successfully. But upon opening the app, I receive the error mentioned above. The original code works, but after making a small change, the error pops up again.

Please assist, I am not sure what to do at this point.

![image](https://user-images.githubusercontent.com/97241619/153141166-dc9fb21d-3449-456a-9102-5fcf0d1da66c.png)

### Expected behavior

I was expecting to open the App with no errors.

### Reproduction steps

Github connection is configured
App is deployed in Amplify
Build process begins and completes successfully
I open the app and receive the error mentioned

### Build Settings

```yaml
version: 1
applications:
  - frontend:
      phases:
        build:
          commands: []
      artifacts:
        baseDirectory: /
        files:
          - '**/*'
      cache:
        paths: []
    appRoot: Uploadtos3
```

**Comment by Flashxjordan** [comment]
Hi,

I am having to cross a similar hurdle. Just wanted to check in and see if you were able to get this resolved, and if so, what changes did you make to find a solution? Thanks
