### ISSUE TITLE
Not able to access Existing Apps in Amplify console

### ISSUE THREAD

**Issue by aroradev-dms** [aws-amplify/amplify-hosting#2577]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify Console feature

Not applicable

### Describe the bug

As of now, Amplify console face challenges while listing/accessing the apps when there are more than 100 apps even if these apps are listed as expected using "**list-apps**" API call from CLI.
<img width="1076" alt="maxResults Network Calls" src="https://user-images.githubusercontent.com/89894573/153485026-46f80de4-19bb-49ed-a4c5-bc89bd91559f.png">

### Expected behavior

Amplify console should not poses any challenges while accessing the apps in the account and also try to paginate the results if the account has more number of apps.

### Reproduction steps

For accounts, with more than 100 apps being created in a Region , this issue might be reproducible. try accessing different apps.

**Comment by hloriana** [comment]
Hi @aroradev-dms, are you only able to see a few of the apps and not all of them? Or are you not able to see any apps in the console at all?

**Comment by hloriana** [comment]
The team is working on a fix for listing apps when the count exceeds 200.

**Comment by Jay2113** [comment]
The Amplify Console supports pagination and you should be able to list more than 100 apps. Closing since this issue has been fixed.
