### ISSUE TITLE
Get custom domain host in SSR application

### ISSUE THREAD

**Issue by yassinecc** [aws-amplify/amplify-hosting#2580]
**Please describe which feature you have a question about?**
Custom domains

**Provide additional details**
We are using Amplify to deploy an SSR application and have set up subdomains with wildcard e.g. "*.myapp.com" through Cloudfront as an alternate domain name. Everything is working fine, except that the SSR application picks up the lambda function name as host and not *.myapp.com
The application's appID is `d2kumq5x0abp49` and is hosted on `eu-west-3`

We have tried to forward additional headers in the default Cloudfront distribution behaviour, but these changes are overriden on deployment. I have also tested with associating a custom domain to Amplify directly, to no avail

_**Is there a way to persist the propagation of a custom domain host all the way to the SSR application?**_

**What AWS Services are you utilizing?**
Amplify, Cloudfront, Lambda, Route53, Certificate Manager...

**Provide additional details e.g. code snippets**

**Comment by hloriana** [comment]
Hi @yassinecc 👋🏽, can you provide your App ID and region so we can further investigate?

**Comment by yassinecc** [comment]
Hello @hloriana :wave: one such app ID is `d2kumq5x0abp49`, and the app is hosted on the `eu-west-3` region

**Comment by yassinecc** [comment]
Hello @hloriana , is there anything I can help with regarding this issue?

**Comment by yassinecc** [comment]
Any news  @hloriana ?

**Comment by yassinecc** [comment]
ping @hloriana , no feedback on this for 2 months now :-(

**Comment by yassinecc** [comment]
Closing this issue as I have found a workaround in https://github.com/aws-amplify/amplify-hosting/issues/2622#issuecomment-1186611188, would be nice to avoid reverting Cloudfront settings on deploy @hloriana
