### ISSUE TITLE
CNAME already exists

### ISSUE THREAD

**Issue by joninaosk** [aws-amplify/amplify-hosting#2583]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1cgsw7szvo5f6

### Region

us-east-1

### Step

Domain activation

### Status

Failed

### Issue or question

I. keep getting this error message:
Error message: [CNAMEAlreadyExistsException] The following CloudFront distributions are already using one or more of your domains

And I have tried everything front and back but nothing seems to work but I think as the error message says that the domain is connected to another distribution on account that is not mine.

Any ideas how to fix this?

### Error message

Error message: [CNAMEAlreadyExistsException] The following CloudFront distributions are already using one or more of your domains: [Distribution: ************* in AWS Account: ***********, Distribution: ************ in AWS Account: ***********]. If you own these distributions, please remove the domains from them first and then retry adding your domain. If you don't own them, then you may already have associated this domain to another Amplify App in another account or region. You can also check our troubleshooting guide for more help: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html

**Comment by joninaosk** [comment]
I am so really stuck here, any idea what could be wrong?

**Comment by phoenixbeats01** [comment]
Also getting this issue

**Comment by joninaosk** [comment]
@phoenixbeats01  In my case I just put the MEDIA_URL  and  DEFAULT_FILE_STORAGE lines in a wrong file.... and it took me such a long time to figure out 😅

**Comment by phoenixbeats01** [comment]
@joninaosk sorry I'm a bit confused on what you mean, what files should those values be present in?

**Comment by joninaosk** [comment]
@phoenixbeats01  Not sure what kind of a project you are working on but in my case I was working in a python project where all of the production settings should be in one file (base.py in my case) but I had the MEDIA_URL and DEFAULT_FILE_STORAGE values in another file. When I added those values to my production file everything worked out. 
Hopefully that makes sense!
