### ISSUE TITLE
Status stuck at Domain Activation stage

### ISSUE THREAD

**Issue by jamessrose** [aws-amplify/amplify-hosting#2588]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2dp62hws6ftgb

### Region

eu-west-1

### Step

Domain activation

### Status

Domain activation

### Issue or question

I have a custom domain at GoDaddy and have completed the CNAME as per instructions, however, the status appears stuck at the 'domain activation' status (and unable to click on it).

I have another domain at GoDaddy & another Amplify site which i have followed the same instructions and that is working fine i.e. i don't believe it is an issue with how i have inputted the CNAME.

### Error message

(No error message) - simply blocked at the Domain Activation stage.

**Comment by hloriana** [comment]
@jamessrose thank you for opening this issue, we are investigating to determine the cause of this. Will update once I have more information.

**Comment by hloriana** [comment]
Update: I was able to successfully reproduce this behavior and confirm that the process is stuck in domain activation phase without error.

**Comment by jamessrose** [comment]
Thanks - does 'without error' mean you don't think any problem? i.e. issue is elsewhere?

Any recommendation how to remediate from here? i.e. i have followed guides and troubleshooting and is all correct - so shall i just delete domain and start again?

**Comment by hloriana** [comment]
I meant there's no error being thrown for a customer to be able to see what's wrong. Can you try to set your domain up again? I attempted again and it's gone through successfully so it should work now.

**Comment by bcien** [comment]
Hello,
I am experimenting a similar issue, but with the domain hosted at Route53.
AppID: d2lb4m0otlxg3
Region: us-west-1

Stuck at: "SSL configuration"
![stuck](https://user-images.githubusercontent.com/20447470/157313636-554bcd46-0d22-4fb2-80cd-af4558771cef.png)

If you think this correspond to a separate ticket, I can create one and remove this reply.

Thanks for the help

**Comment by jamessrose** [comment]
Mine was stuck on Domain Activation stage - i deleted and re-added and it now works fine (as per [hloriana] advice)

So you may need a different ticket i'm afraid

**Comment by jamessrose** [comment]
Hi - Have reopend.....

Readded the domain solved the amplify not domain activated issue (now all green).

However, now the root domain https://fplalerts.com is not accessible however https://www.fplalerts.com is working fine ?

Any ideas?
