### ISSUE TITLE
Build fails on front end stage with no error

### ISSUE THREAD

**Issue by tscole** [aws-amplify/amplify-hosting#2591]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3iczrv56cp0p5

### Region

eu-west-2

### Amplify Console feature

Custom builds

### Describe the bug

Front end builds are timing out with no errors in the logs.
The last few lines of the front end log are:

2022-02-15T15:12:12.704Z [WARNING]: Compiling assets...
2022-02-15T15:12:13.231Z [WARNING]: Browserslist: caniuse-lite is outdated. Please run:
                                    npx browserslist@latest --update-db
2022-02-15T15:12:31.593Z [WARNING]: Compile assets - 18.89s
2022-02-15T15:14:23.845Z [WARNING]: Execute GraphQL (19477 queries) - 109.25s

### Expected behavior

Build should complete :)

### Reproduction steps

Run the build using the button in the console

**Comment by hloriana** [comment]
Hi @tscole 👋🏽 thanks for raising this issue! It looks like your builds are timing out after 1hr.  Through the console, you can adjust the build timeout to up to 8 hours. 

It also looks like you're running `nvm install 12.19.0` and `nvm use 12.19.0` in the preBuild and build phases. You only need to install once and that version will persist for all subsequent phases unless you install and use a different version.

**Comment by tscole** [comment]
@hloriana the builds shouldn't take 60 minutes or even close. When they succeed they complete in about 20 minutes. Something else is going on here. Perhaps a memory issue? Are you able to look into this further please? Simply increasing the timeout is not going to fix the issue.

**Comment by hloriana** [comment]
Hi @tscole yes we are looking into this further. Will update asap.

**Comment by hloriana** [comment]
@tscole can you confirm that your builds are successful locally?

**Comment by tscole** [comment]
Yes, they are building fine locally on my mac.

**Comment by tscole** [comment]
@hloriana any update? This is a production site and if we can't get builds to succeed I need to come up with an alternative plan asap. Is there any indication of what this issue is?

**Comment by swaminator** [comment]
@tscole sorry to hear you're running into this. We do not want you to move away.

**Comment by hloriana** [comment]
Hi @tscole, apologies for the delay. We are still investigating what would cause your builds to start failing and what may have changed prior to your last successful build. Will update you asap.

**Comment by tscole** [comment]
I managed to get a build to complete by reducing the number of pages. This isn't a long term solution for us

On 1 Mar 2022, at 23:39, hloriana ***@***.*** ***@***.***> > wrote:


Hi @tscole, apologies for the delay. We are still investigating what would cause your builds to start failing and what may have changed prior to your last successful build. Will update you asap.

**Comment by ganipcanot** [comment]
How long do your builds take when you run them locally?

**Comment by tscole** [comment]
Just a front end build to test: 232.23s - i.e. less than 4 minutes.

**Comment by hloriana** [comment]
We've investigated the build behavior but in order for us to determine what is possibly causing this, we will need to be able to reproduce the behavior. Is it possible for you to provide a sample project that produces this same issue? Or can you provide more detailed steps for us to reproduce this?

**Comment by hloriana** [comment]
It looks like your most recent builds have been averaging around 7-8 minutes. Please let us know if this issue is resolved for you.

**Comment by tscole** [comment]
It is NOT resolved. I have had to change my site as a work around. Please continue to investigate.

On 5 Apr 2022, at 20:47, hloriana ***@***.*** ***@***.***> > wrote:


It looks like your most recent builds have been averaging around 7-8 minutes. Please let us know if this issue is resolved for you.
