### ISSUE TITLE
Next.js redirect with conditions

### ISSUE THREAD

**Issue by Sekaiichi** [aws-amplify/amplify-hosting#2593]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:eu-central-1:341253789890:apps/d2v7xru8aevic2

### Region

u-central-1

### Amplify Console feature

Redirects

### Describe the bug

Next.js has redirects with conditions and it's work in local. But on aws amplify it doesn't work. https://nextjs.org/docs/api-reference/next.config.js/redirects.   

### Expected behavior

```
    async redirects() {
        return [
            {
                source: '/(.*)',
                has: [
                    {
                        type: 'header',
                        key: 'User-Agent',
                        value:
                            'Mobile|Android|BlackBerry'
                    }
                ],
                destination: 'https://m.alifshop.tj',
                permanent: false
            }
        ]
    }
```

that code work on local well. But on amplify not.

### Reproduction steps

When I tried code on local it's work but on server not.

**Comment by Sekaiichi** [comment]
> Hi 👋, thanks for opening! While we look into this...
> 
> If this issue is related to custom domains, be sure to check the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html) to see if that helps. Also, there is a more general [troubleshooting FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md) that may be helpful for other questions.
> 
> Lastly, please make sure you've specified the `App ID` and `Region` in the issue!
Hi it's exactly related to next.js redirects.
that part not working on aws amplify(
![image](https://user-images.githubusercontent.com/15075961/154924892-a4d4d802-53df-49e3-a598-7401868e14e0.png)

**Comment by Sekaiichi** [comment]
@calavera @ErikCH @mwarkentin @hyandell

**Comment by calavera** [comment]
Thanks for opening this issue. We get notified when issues are open, there is no need to ping people 😄 We've added it to the backlog.

**Comment by Sekaiichi** [comment]
> Thanks for opening this issue. We get notified when issues are open, there is no need to ping people 😄 We've added it to the backlog.

Thank you very much

**Comment by Sekaiichi** [comment]
Good day, @hloriana.
Did you see this problem?

**Comment by roeean** [comment]
Hi,
I have the same problem.
There is a way to solve this?

**Comment by dustinsmith1024** [comment]
I think I am running into the same issue. My original hunch was that Amplify is tweaking the headers because the request is proxied through CloudFront.

Looks like user agent is actual `user-agent: Amazon CloudFront,` when it hits the backend.

My app is trying to use `host` to redirect on. However that is set to `host: prod.us-west-2.gateway.amplify.aws.dev,` with an extra header for the original ` x-forwarded-host: pr-xxx.randomid.amplifyapp.com`.

I swapped our has clause to match the new forwarded for header, but that gives a 502.

```
< HTTP/2 502
< content-type: text/html
< content-length: 1022
< server: CloudFront
< date: Thu, 23 Mar 2023 18:11:47 GMT
< x-cache: LambdaValidationError from cloudfront
< via: 1.1 f82a4020c8fc9b14a403737c65661074.cloudfront.net (CloudFront)
< x-amz-cf-pop: ORD58-P1
< x-amz-cf-id: 0oW9eco22AbmI93_q6REVDn9XzON8ftWqJ5tNrrqoSDTmdj4Zm6Abw==
<
```

Not sure how to proceed right now, I'll update if we find a solution.

**Comment by lahiri-phdworks** [comment]
2yrs now. I am still facing this issue

**Comment by calavera** [comment]
This feature has just been supported with our latest launch! Thanks for your patience. I'm closing this issue as resolved.

Check out the details here: https://aws.amazon.com/blogs/mobile/cdn-caching-improvements-for-better-app-performance-with-aws-amplify-hosting/
