### ISSUE TITLE
Own self generated SSL on Amplify page

### ISSUE THREAD

**Issue by rmaafs** [aws-amplify/amplify-hosting#2616]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Step

Domain activated

### Status

Success

### Issue or question

I just want use my self generated SSL on my domain.
I vinculed my domain successfully, but the Amplify page subdomain use SSL generated for Amazon, but I want use my own SSL.

Can I use my self generated SSL?

Thank you!

**Comment by hloriana** [comment]
Hi @rmaafs 👋🏽 this is currently not supported but we are tracking this feature request for prioritization.

**Comment by calavera** [comment]
I'm going to close this issue as duplicated, since we're tracking the work with this one https://github.com/aws-amplify/amplify-hosting/issues/56

Thanks a lot for opening the ticket @rmaafs
