### ISSUE TITLE
Is there a way to stop generating meta tags about AWS amplify?

### ISSUE THREAD

**Issue by manalab17** [aws-amplify/amplify-hosting#2619]
**Please describe which feature you have a question about?**

**Provide additional details**

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**

Hi, I use amplify for host service apps. 

So, I want to add diffrent meta tags for each apps.

I decided to delete default meta tags in my app. But, amplify generated meta tags about its'info

e.g) 
```
<meta data-n-head="1" data-hid="description" name="description" content="## Built and served by AWS Amplify">
<meta data-n-head="1" data-hid="og:type" name="og:type" property="og:type" content="website">
<meta data-n-head="1" data-hid="og:title" name="og:title" property="og:title" content="blah blah">
.
.
.
```
Is there any option to stop generate? or Just using `document.delete` to delete meta tag?

**Comment by calavera** [comment]
Can you give us more information about your application? having the URL can be useful.
- Are you using Amplify Studio to build your app?
- Are you using the Amplify CLI?
- Are you using any of the Amplify Libraries?

**Comment by manalab17** [comment]
> Can you give us more information about your application? having the URL can be useful.
> 
> * Are you using Amplify Studio to build your app?
> * Are you using the Amplify CLI?
> * Are you using any of the Amplify Libraries?

I'm using aws-amplify console without any libraries.
When I said 'Application' it mean web app. 

e.g page is here! -> https://myy.smartbookingplus.com/

![image](https://user-images.githubusercontent.com/30038115/157143052-44008396-d2ae-48a0-bc8d-19126fb36d10.png)
It can be overwritted meta tag attributes, but I don't want to create any meta tags about amplify for SEO.

**Comment by calavera** [comment]
I've checked with the team, and it doesn't look like we're adding those headers to the code. I'd recommend you to go through the source to verify that they are not in your repository. They might be there because the site started from a template, or something similar, but we don't have access to it.
