### ISSUE TITLE
How to add a wildcard subdomain to my amplify console deployed app.

### ISSUE THREAD

**Issue by yelhow** [aws-amplify/amplify-hosting#262]
** Please describe which feature you have a question about? **
I am using amplify console to deploy my webapp. I am trying to understand if I can add a wildcard subdomain to my domain. 

Does the cli method mentioned in this "https://docs.aws.amazon.com/cli/latest/reference/amplify/create-domain-association.html" can configure wildcard support to my domain.

** Provide additional details**

**Comment by swaminator** [comment]
We currently do not support wildcard subdomains. What are you trying to do ?

**Comment by dahersoftware** [comment]
@swaminator I am developing a multi-tenant app and I want to provide custom subdomain URL to my users.
In amplify console, I have configured a domain and want to find a way to manage subdomains whenever a different tenant register within my app. Currently I see if I have multiple branch I can register a subdomain like <branch.domain> similarly I am looking for <tenant.domain> Urls.

**Comment by dahersoftware** [comment]
@swaminator Any suggestion for this.

**Comment by pipesorter** [comment]
I have similar need, any suggestion @swaminator ?

**Comment by ea-tal** [comment]
same here. 
we're switching from amplify because of this.

**Comment by SourceCode** [comment]
Has anyone come up with any approaches for this yet?

**Comment by JisrHR** [comment]
same here.
we're switching from amplify because of this.I hope amplify start working on this feature it is  very important

**Comment by colecanning** [comment]
@swaminator is there a feature request for this that we can follow?

**Comment by zgr024** [comment]
I have the same issue with trying to launch a multi-tenant application through Amplify. I don't necessarily need a wildcard but if you aren't going to disable the limit of the number of subdomains you allow then a wildcard or regex (not attached to git branches) is the only viable option for multi-tenant applications. 50 subdomains isn't going to get us too far when we're launching an application requiring hundreds (possibly thousands) of subdomains

**Comment by mits87** [comment]
I have also the same problem :-( looking forward for a proper solution.

**Comment by lisbuenas** [comment]
@swaminator is this featured mapped to be implemented soon?

**Comment by summyfeb12** [comment]
Amplify, depending on the app being hosted, creates a CloudFront distribution. Instead of trying to assign the wildcard subdomain to amplify app, you can assign the wildcard subdomain to CloudFront distribution. You can see which Cloudfront distribution Amplify App created in Amplify App Settings--> Rewrites and redirects

**Comment by ea-tal** [comment]
@summyfeb12 , the CloudFront distribution is hidden in my case. 
I have no access to it.
Maybe I'm looking in the wrong place?

**Comment by summyfeb12** [comment]
@ea-tal  I have admin permissions and I can see the cf distribution in both Amplify Console and CloudFront distributions. What do you see in rewrites and redirects?

**Comment by ea-tal** [comment]
@summyfeb12, I see only the table of the source address (regex), the target address, and the type.

**Comment by rsaid99** [comment]
One more vote for a solution for this.

**Comment by SourceCode** [comment]
I wrote an ISV multitenant system for amplify with sub-domain /IAM management. 

The wildcard portion just setup your route53 correctly.

**Comment by neilferreira** [comment]
Related https://github.com/aws-amplify/amplify-hosting/issues/44

**Comment by swaminator** [comment]
Closing to track in #44.
