### ISSUE TITLE
Hooks are not getting uploaded

### ISSUE THREAD

**Issue by gakinson** [aws-amplify/amplify-hosting#2624]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1he6253vtkqx8

### Region

us-east-2

### Amplify Console feature

Backend builds

### Describe the bug

We have hooks in the amplify/hooks folder and unless we execute an amplify push locally, they do not get uploaded/used on the CI/CD pipeline.

We have a beta and production stage which we do not execute direct amplify push commands to locally. We have a hook that needs to be executed on the pipeline and it is not being executed due to the reason above. My assumption is that it has something to do with the amplifyPush script that you use.

### Expected behavior

Amplify CI/CD pipeline executes hooks in the amplify/hooks folder without a local prerequisite amplify push needing to be done.

### Reproduction steps

1. Add a hook to amplify/hooks
2. Git push changes
3. Start build in amplify CI/CD pipeline
4. Notice that hook is not executed

**Comment by hloriana** [comment]
Hi @gakinson 👋🏽 I'm not able to reproduce this issue. I'm able to trigger CI/CD builds that execute hooks during the build phase. What kind of command hooks are you trying to run during the build process (how are they named)?

**Comment by gakinson** [comment]
I am running a pre-build hook which is in  amplify/hooks. The file name is pre-push.js

Can you try the following process.
1. Delete the contents of pre-push or delete the file entirely.
2. Trigger a CI/CD build, wait until complete. (Look to see if it still executes the old hook)
3. Add hook
4. Trigger CI/CD, see if it executes.


Maybe this issue has already been fixed.

**Comment by hloriana** [comment]
If anyone else is running into this behavior, please make sure you enable fullstack CI/CD in the console on the branch you're trying to update. Once this is enabled, Amplify will attempt to update the backend when a new build is triggered and the command hooks will run. 

Please open a new issue if this behavior persists.

**Comment by swaminator** [comment]
https://github.com/aws-amplify/amplify-hosting/issues/2492#issuecomment-1244468917
