### ISSUE TITLE
Console has stopped loading due to undefined (reading 'githubToken')

### ISSUE THREAD

**Issue by silent-vim** [aws-amplify/amplify-hosting#2626]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

Cannot view any apps

### Region

us-west-2

### Amplify Console feature

Build settings, Logging, Notifications, Previews

### Describe the bug

When we navigate to AWS Amplify in our account the console is failing to load. We our currently completely blocked due to this issue and cannot make any changes.
<img width="1289" alt="Screen Shot 2022-03-07 at 2 17 49 PM" src="https://user-images.githubusercontent.com/5408709/157271734-f4315f44-c4e2-4bdf-8326-1a4c013180d9.png">

### Expected behavior

Console should load and allow access to deployed apps.

### Reproduction steps

Navigate to https://us-west-2.console.aws.amazon.com/amplify/home?region=us-west-2#/

**Comment by silent-vim** [comment]
Looks like others are also experiencing issue - https://twitter.com/Scampiuk/status/1500082411891269640

**Comment by hloriana** [comment]
Hi @silent-vim thanks for providing this information; I responded to your email as well. We are investigating this and will update you shortly.

**Comment by calavera** [comment]
hi folks, between March 7 9:13 PM and March 8 9:55 AM PST, we experienced increased error rates connecting with GitHub in the US-EAST-1 Region. The issue has been resolved and the service is operating normally.

If you bump into this again, like @Sherdycoder mentions, try reloading the page without caching so the UI tries to refresh the token again.
