### ISSUE TITLE
Build hanging on frontend stage with no error

### ISSUE THREAD

**Issue by Khristophor** [aws-amplify/amplify-hosting#2627]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d107ndoiwes5ug

### Region

ca-central-1

### Amplify Console feature

Build settings

### Describe the bug

As of a few days ago, some of our Bitbucket connected branch builds are hanging at the frontend stage after successfully building. The log output looks like:
```
2022-03-08T14:50:08.619Z [INFO]: # Completed phase: build
2022-03-08T14:50:08.638Z [INFO]: ## Build completed successfully
2022-03-08T14:50:08.641Z [INFO]: # Starting caching...
2022-03-08T14:50:08.791Z [INFO]: # Creating cache artifact...
2022-03-08T14:50:28.399Z [INFO]: # Cache artifact is: 662MB
2022-03-08T14:50:28.492Z [INFO]: # Uploading cache artifact...
2022-03-08T14:50:32.414Z [INFO]: # Caching completed
2022-03-08T14:50:32.498Z [INFO]: No custom headers found.
2022-03-08T14:50:32.504Z [INFO]: # Starting build artifact upload process...
2022-03-08T14:50:35.633Z [INFO]: # Build artifact is: 58MB
2022-03-08T14:50:35.662Z [INFO]: # Build artifact is: 58MB
2022-03-08T14:50:35.663Z [INFO]: # Uploading build artifact '__artifactsHash.zip'...
2022-03-08T14:50:35.723Z [INFO]: # Uploading build artifact '__artifacts.zip'...
2022-03-08T14:50:36.270Z [INFO]: # Build artifact upload completed
2022-03-08T14:50:36.272Z [INFO]: # Starting environment caching...
2022-03-08T14:50:36.273Z [INFO]: # Uploading environment cache artifact...
2022-03-08T14:50:36.336Z [INFO]: # Environment caching completed
Terminating logging...
```
but the build step does not complete and no further errors are logged.

Other older connected branches (`dev` for example) still deploy successfully, and some newer connected branches (connected and deployed after a failing branch) also deploy successfully.

Is there anywhere to review more information about what is potentially causing an issue?

### Expected behavior

After the build finishes the branch is successfully deployed

### Reproduction steps

1. Connect a branch from Bitbucket with our dev Amplify backend
2. Wait until the build hangs

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm install --legacy-peer-deps --no-audit
        - if [ "${REACT_APP_ENABLE_MOCKING}" = "true" ]; then npx msw init public/ --save; fi
    build:
      commands:
        - npm run test-ci
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

Cancelling and redeploying does not seem to help, neither does disconnecting and reconnecting the branch, or creating a new branch and deploying.

**Comment by hloriana** [comment]
Hi @Khristophor Which branches are you having this issue with? After the build stage completes, are the deploy and verify stages initiated?

**Comment by Khristophor** [comment]
Hi @hloriana, this was occurring between I'd say March 3rd and March 10th. Both the provisioning stage or the build stage would simply stop at the last step and nothing else would happen for hours or days. The other stages would not initiate and I would eventually receive a `Build failed to complete successfully.` error.

As for branches, it was happening on various feature branches off of our main `dev` branch that was still building successfully (for the most part) although I do have a record of a `dev` build failure where the provisioning step ran for 31 minutes and then failed with a `Build timed out` error.

It seems to be working okay now, but it really would have been helpful at the time to have some more insight over what was failing with the builds, if there were service interruptions that were affecting Amplify, etc.

If there's a chance we could get some more information on this past problem, we would very much like to know if there was a cause on the AWS side. We're working on making our application production-ready and the thought of being unable to use our deployment pipeline through no fault of our own is making me rethink Amplify.

**Comment by hloriana** [comment]
@Khristophor I will double check with the team for more information. I will update you as soon as possible.

**Comment by hloriana** [comment]
The team is still deep diving into this issue but it looks like this happened because of the naming conventions of your feature branches. They seem to be exceeding a 128 character limit for our internal processes which is causing the build to hang and timeout. We have identified this as bug and are tracking this for prioritization.

**Comment by Khristophor** [comment]
Thanks for the info @hloriana, that makes sense for most of the timeouts. If the team is poking around, any information on the timeout of the `dev` branch failure (build 134) would also be appreciated.

**Comment by hloriana** [comment]
Hi @Khristophor, we've deployed a fix for this issue so you should no longer be running into this problem. Please re-open if this issue is still occurring for you. Thanks!
