### ISSUE TITLE
Status stuck at Domain Activation stage

### ISSUE THREAD

**Issue by bcien** [aws-amplify/amplify-hosting#2630]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2lb4m0otlxg3

### Region

us-west-1

### Step

SSL Configuration

### Status

Stuck

### Issue or question

I have a custom domain hosted ad Route 53, and after adding a subdomain to the Amplify app (which should be a one click setup), the process get stuck at the SSL Configuration Stage.
![stuck](https://user-images.githubusercontent.com/20447470/157349659-412b949e-274f-489d-876d-feea3d349931.png)

I did try deleting the custom domain within the Amplify console and re-adding it, without success. 

### Error message

I get no error, it just get stuck after checking that all requirements for this step are fulfilled.

**Comment by hloriana** [comment]
Hi @bcien 👋🏽 which DNS provider are you using?

**Comment by bcien** [comment]
After restarting it today, it finally worked.

If someone else face this issue, I recommend to check the following:

1. If you bought/transfer the domain to AWS, go to Route53 and make sure the DNS config is as Amplify requires.
2. If you bought the domain outside AWS and have not transfered it, and if you want to use Route 53: visit the webpage where you bought the domain and make sure the nameservers are set to point to AWS, following Route 53 instructions.
3. If you bought the domain outside AWS and have not transfered it, and if you don't want to use Route 53: visit the webpage where you bought the domain and make sure to add all the DNS entries Amplify requires.

Good luck
