### ISSUE TITLE
NextJS Build Fails without any code-change (same build was previously working)

### ISSUE THREAD

**Issue by karoly-gergely** [aws-amplify/amplify-hosting#2632]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d13opy58e5uyxo and dk39i9iag8i21

### Region

eu-central-1

### Amplify Console feature

Not applicable

### Describe the bug

Build fails in SSR step for NextJS application. No change was done to the code-base, just a redeploy was triggered on a build that previously worked. Ever since the first failure all our next.js application envs via amplify fail to build although no code change was done. This happened right as we were doing our marketing release so it is directly generating losses on our side so we need it fixed ASAP. Considering that no change was done between the point when it was working and now (started failing around 20h ago) it is definitely an issue on your side that is also causing us to keep rebuilding in search of solutions and generating extra costs.

### Expected behavior

The build should work

### Reproduction steps

Start a build
It fails

**Comment by hloriana** [comment]
@karoly-gergely the team has been working on this. Can you try to build again and confirm if you're still experiencing this issue?

**Comment by karoly-gergely** [comment]
@hloriana First of all, I wanted to mention that we really appreciate the rapid response and solving of the issue, it really means a lot as this is a very stressful period for us. Yes, we've tested and it now seems to be working again. Thank you very much!, you can close this issue now :D Wish all support interactions could be this efficient.
