### ISSUE TITLE
Team Environment issue

### ISSUE THREAD

**Issue by sdavis-amido** [aws-amplify/amplify-hosting#2633]
**Please describe which feature you have a question about?**

We're using a few Git code branches to manage the lifecycle (`dev`,`qa`, `pre-prod`, `main`) and have a working Application on the `dev` branch. I can `amplify push` and it all works OK for `dev`. 

There are 5 Java lambda functions in the codebase as well as their associated API Gateway endpoints.

I have git merged the codebase from `dev` to `qa` which seemed to go OK, but when I try and `amplify` push it only knows about one of the lambda functions; it doesn't even seem to want to push the other lambda functions.

I have looked through and compared as may config json files as I can see on the `qa` branch and can see references to the missing lambda functions, as well as see them referred to in the api gateway config folder.

Region = eu-west-2
App Id = d9kqm5aquedtk

**Provide additional details**

Was trying to follow this : https://docs.amplify.aws/cli/teams/overview/

The process I followed was:

```
git checkout qa
amplify env checkout qa
git merge dev
amplify push
```

and it shows just one lambda function, not all 5.

If I do a `amplify function update` it only shows the one function - where does it look for the list of functions it knows about?

**What AWS Services are you utilizing?**

Lambda Java service
API Gateway

**Provide additional details e.g. code snippets**

**Comment by sdavis-amido** [comment]
OK, so I tried a few things and this seemed to work; it was the amplify init that seemed to re-add all of the missing functions

```
git checkout qa
amplify env checkout qa
amplify pull
git merge dev
amplify init
amplify build
amplify push
```

**Comment by calavera** [comment]
Thanks for letting us know that you were able to solve this issue. I'm going to close this ticket. Let me know if you still have difficulties with the environment and I'll happily reopen it.
