### ISSUE TITLE
Unable to host apple-app-site-association to a reactjs deployment on Amplify

### ISSUE THREAD

**Issue by dalekatwork** [aws-amplify/amplify-hosting#2634]
**Unable to host static file apple-app-site-association from the react project root**

**Using**
1. AWS Amplify
2. Reactjs project react@17.0.1

**How to reproduce**
I tried the solution mentioned here: https://github.com/aws-amplify/amplify-hosting/issues/1983

I have the `apple-app-site-association` at the root of my react project and the redirect code on amplify(Rewrites and redirects) from the above solution link.

```
  {
      "source": "/.well-known/apple-app-site-association",
      "target": "/apple-app-site-association",
      "status": "200",
      "condition": null
  },
```

**Comment by calavera** [comment]
@dalekatwork the right solution is at the bottom of that thread, see https://github.com/aws-amplify/amplify-hosting/issues/1983#issuecomment-881549611

**Comment by calavera** [comment]
I'm going to close this issue. Let me know if that information doesn't work and I'll happily reopen it.

**Comment by dalekatwork** [comment]
Hi @calavera the solution doesnt resolve it for me.

I have moved my `apple-app-site-association` file under my root at `public/.well-known/apple-app-site-association`. 

I added the following to the top of my redirects on amplify

```txt
    {
        "source": "/.well-known/apple-app-site-association",
        "target": "/.well-known/apple-app-site-association.json",
        "status": "200",
        "condition": null
    },
```

When I try to curl the url, I get the following

```bash
HTTP/1.1 301 Moved Permanently
Server: CloudFront
Date: Thu, 10 Mar 2022 08:55:44 GMT
Content-Type: text/html
Content-Length: 183
Connection: keep-alive
```

**Comment by calavera** [comment]
Can you give us more information about your app?
What's the url, and appId for your it?

**Comment by dalekatwork** [comment]
hi @calavera, here is the `apple-app-site-association` file

```json
{
  "applinks": {
    "apps": [],
    "details": [{
      "appID": "X7NWDSJWM2.com.dillali.mobile",
      "paths": ["*"]
    }]
  }
}
```

I am trying to host it on `app.dillali.com` under specific url `app.dillali.com/.well-known/apple-app-site-association`
`app.dillali.com` is a react app hosted on Aws Amplify

I am following this documentation: https://docs.expo.dev/guides/linking/#universal-links-on-ios

**Comment by dalekatwork** [comment]
hi, I have figured out where I went wrong.

My `apple-app-site-association` is now under my root at `public/.well-known/apple-app-site-association.json`. 

I am using a redirect rule as the following:

```txt
    {
        "source": "/.well-known/apple-app-site-association",
        "target": "/.well-known/apple-app-site-association.json",
        "status": "200",
        "condition": null
    },
```

curl call on the url works, and my app is working as expected.
