### ISSUE TITLE
Access denied while accessing the application. 

### ISSUE THREAD

**Issue by salman-shezad** [aws-amplify/amplify-hosting#2639]
I was deploying the code to the aws amplify and for that I have created my zip and pasted the same in the S3 bucket
But when I try to run the deployed application it gives me error while accessing the deployed url

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>C44BZG8YGR97MQ76</RequestId>
<HostId>tEpnhj0XRO77r1fneF2qe9G+BVSzQ9b+M4Qqey2etZT3yMIVuQ8XxDDF9Uh9hmhjCY4eWQNcEAM=</HostId>
</Error>

**Comment by calavera** [comment]
Can you give us a little bit more information about your application? 
do you have an appId that you can share with us?
how are you uploading that file?

**Comment by Braj4github** [comment]
I am also getting the same access denied error while uploading the artifact into amplify app manually.

**This XML file does not appear to have any style information associated with it. The document tree is shown below.**
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>AW0AD9DMSJXVKNBP</RequestId>
<HostId>4GE8uzVsiOAyIFiJiV6PL3YuFVBBh7Ndxx8pv7ACoxuir7uXJ6iiSqc0VmbA6OZg7WoHaUTrpWw=</HostId>
</Error>

**Comment by CarsonGH** [comment]
This seems to be happening to me when I add a custom domain to the amplify app. When I remove the domain it works again.

**Comment by Jay2113** [comment]
Kindly ensure that you zip the contents of your build output and not the top level folder: https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html#:~:text=When%20you%20create,be%20initialized%20properly.

If the issue persists, kindly provide the following information:
- Amplify App ID
- AWS region
- Artifacts.zip file

**Comment by davidmanitarellis** [comment]
I have just faced this issue today
