### ISSUE TITLE
Not able to deploy Next.js SSR app

### ISSUE THREAD

**Issue by ikoichi** [aws-amplify/amplify-hosting#2641]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1sig4j0w4mc7r

### Region

eu-west-1

### Amplify Hosting feature

Build settings, Manual deploys

### Describe the bug

I created an Amplify App using the CDK.

The Next.js app is inside a folder of the repository, called `web-app`.

As the Framework was not detected, I manually forced the Framework to Next.js - SSR with these commands.

```
aws amplify update-app \
--app-id d1sig4j0w4mc7r \
--platform WEB_DYNAMIC \
--region eu-west-1

aws amplify update-branch \
--app-id d1sig4j0w4mc7r \
--branch-name dev \
--framework 'Next.js - SSR' \
--region eu-west-1
```

The Service Role is set, it was created by the CDK, and I added to it the additional Permissions as specified in the guide https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#ssr-IAM-permissions

I am still getting this error in the deploy phase:

```
2022-03-11T10:09:23 [INFO]: Beginning deployment for application d1sig4j0w4mc7r, branch:dev, buildId 0000000007
2022-03-11T10:09:23 [INFO]: Cannot find any generated SSR resources to deploy. If you intend for your app to be SSR, please check your app Service Role permissions. Otherwise, please check out our docs on how to setup your app to be detected as SSG (https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app)
2022-03-11T10:09:23 [ERROR]: {"code":"7","message":"No ssrResources.json file"}
```

### Expected behavior

Deployment to succeded, and CloudFront, Lambdas, S3 resources are created.

### Reproduction steps

Manually run a build.

### Build Settings

```yaml
{
  "version": "1.0",
  "appRoot": "web-app",
  "frontend": {
    "phases": {
      "preBuild": {
        "commands": [
          "yarn"
        ]
      },
      "build": {
        "commands": [
          "npm run build"
        ]
      }
    },
    "artifacts": {
      "baseDirectory": ".next",
      "files": "**/*"
    },
    "cache": {
      "paths": [
        "node_modules/**/*"
      ]
    }
  }
}
```

### Additional information

Thanks for your help!

**Comment by calavera** [comment]
hi @ikoichi, can you give us more information about your app? Which version of Next.js are you using?

**Comment by ikoichi** [comment]
Hi @calavera I'm using Next.js 12

**Comment by calavera** [comment]
thanks for letting us know @ikoichi, that's what I suspected. We currently don't support that version, we're working on it.

You can keep track of our progress by clicking the "**Subscribe**" button in this issue 👉  #2343

I'm going to close this ticket so we don't keep duplicated ticket around.

**Comment by wottpal** [comment]
@calavera do you have an official ETA for nextjs-12 support. would love to use aws for my app but vercel just has the better arguments atm.

**Comment by moatezheni** [comment]
some libs and files breake amlify framework detection 
for exemple next-pwa packege and all related config or files 
files that contain env variables 
and .githooks folder
