### ISSUE TITLE
Custom domain 404 but Cloudfront URL Works

### ISSUE THREAD

**Issue by leonardof131** [aws-amplify/amplify-hosting#2642]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1ogeyfaohjzo3

### Region

us-east-1

### Step

Configure DNS

### Status

Failed

### Issue or question

I've setup an dev subdomain for my Amplify app: dev.mydomain.com. Registering the domain on amplify worked, looking at the DNS records I can see the Cloudfront URL where I should point my subdomain with CNAME, I go to Route53 and make the record on the correct zone.

The problem: When I try to visit dev.mydomain.com I get an 404 error. I can access the cloudfront URL and the app loads correctly. 
The same thing happens with the Amplify provided domain for my app, I get an 404.

**Comment by hloriana** [comment]
Hi @leonardof131 I'm able to visit your application via your custom domain. Can you confirm that this is resolved for you?

**Comment by hloriana** [comment]
Please re-open if you're still experiencing this issue. Thank you!
