### ISSUE TITLE
Getting tHis site cant be reached after deploying with custom domain 

### ISSUE THREAD

**Issue by rajinikanth2305** [aws-amplify/amplify-hosting#2643]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-1:514924133480:apps/d3q8naythywm55

### Step

Domain activation

### Status

THis site cant be reached error after deploying it and successfully configured SSL,domnain activation

### Issue or question

I registered my domain name on hostinger.com and at the time of adding custom domain in Amplify ,I have added CNAME,CAA records under DNS Name servers and it successfully configured and domain has as showing activated in amplify. But when I launched its showing This site cant be reached . I have checked multiple times but I am not able to figure it out the major cause of the issue.
![aws](https://user-images.githubusercontent.com/44217560/158000628-c1d2f070-4aac-421b-a208-780b9e683009.PNG)
![trekphotos](https://user-images.githubusercontent.com/44217560/158000644-533e52d1-c1cc-4fed-92d5-eb90202eb31f.PNG)
 Please help me with this issue and do needful.

**Comment by rajinikanth2305** [comment]
Yes I have added. Pleas help me with this issue and I have been facing this issue for the last one day.

**Comment by rajinikanth2305** [comment]
Please help me . I got stuck here and I have to deploy website on custom domain

**Comment by hloriana** [comment]
Hi @rajinikanth2305 👋🏽 it looks like you didn't add `www` as a subdomain for your app. Can you make sure you've added that subdomain? Just select **Manage subdomains** and add `www`. Please let me know if this does not work.
