### ISSUE TITLE
Build successful but link not opening

### ISSUE THREAD

**Issue by dleyyy** [aws-amplify/amplify-hosting#2644]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-1:931986214015:apps/d1ic0ej73uu16h

### Region

us-east-1

### Amplify Hosting feature

Build settings

### Describe the bug

My React app successfully built, but the link does not work. I followed the tutorial, and this is what I am seeing. I am not sure why the app is not appearing.

<img width="1117" alt="Screen Shot 2022-03-12 at 4 25 34 PM" src="https://user-images.githubusercontent.com/64238120/158035516-31613ed1-6bae-4384-a809-8ce2347a3793.png">
<img width="1080" alt="Screen Shot 2022-03-12 at 4 25 51 PM" src="https://user-images.githubusercontent.com/64238120/158035522-86bb7cea-d411-4dc7-996c-d77f644f278d.png">
 

### Expected behavior

I expected to see my working website. 

### Reproduction steps

Building the app

### Build Settings

<img width="1094" alt="Screen Shot 2022-03-12 at 4 28 28 PM" src="https://user-images.githubusercontent.com/64238120/158035650-c941dcfa-5ca4-4d66-81e6-e54d577ba2f9.png">

**Comment by calavera** [comment]
Hi, what's the URL for your website? The screenshot you posted shows the Amplify dashboard, which looks correct to us.

Make sure you set the SPA redirect in your dashboard, if you didn't already:
https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa

**Comment by hloriana** [comment]
Can you also show us what you see when you click the link displayed?

**Comment by decatoncheir** [comment]
My jekyll deployment have the same issue. The build and deployment ticks are all green, but my jekyll website cannot be displayed.  Instead, a page "Your app will appear here once you complete your first deployment." is displayed. 

<img width="1157" alt="Screenshot 2022-03-27 at 2 42 48 PM" src="https://user-images.githubusercontent.com/45692724/160270071-cbedef1a-992c-41c1-bd48-f9dbc3c576d0.png">

**Comment by decatoncheir** [comment]
> My jekyll deployment have the same issue. The build and deployment ticks are all green, but my jekyll website cannot be displayed. Instead, a page "Your app will appear here once you complete your first deployment." is displayed.
> 
> <img alt="Screenshot 2022-03-27 at 2 42 48 PM" width="1157" src="https://user-images.githubusercontent.com/45692724/160270071-cbedef1a-992c-41c1-bd48-f9dbc3c576d0.png">

The link of my deployment is [beta.decatoncheir.net](https://beta.decatoncheir.net)

**Comment by hloriana** [comment]
It looks like the links are loading your website correctly now. If you run into this issue again please feel free to re-open.
