### ISSUE TITLE
Webhook payload with missing commit payload silently fails

### ISSUE THREAD

**Issue by ishansharma** [aws-amplify/amplify-hosting#2646]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

drkit10b1nk6s

### Region

us-west-1

### Amplify Hosting feature

Backend builds, Webhooks

### Describe the bug

My code repo is on GitHub and my main branch deploys to the production website on Amplify. On Feb 24, I pushed 5 commits to the repo and each of them immediately triggered new build. I pushed a small change on Feb 25 and that did not trigger a new build. It was not visible in Amplify dashboard at all.

I tried reconnecting the webhook but that didn't help. After pushing a new commit and connecting webhook again, I was able to get builds to work again. 

I went to my repo and compared the webhook payload. The one that didn't work had `commits` and `head_commit` keys missing in the payload. 

### Expected behavior

I should see an error or some sort of message in Amplify Dashboard. 

### Reproduction steps

1. Pushed a new commit that only contained a submodule update (this commit went through for me but newer commits didn't!)
2. Push new commits where webhooks payload is missing the `commits` and `head_commit` keys (this could be a GitHub bug?)
3. Webhook gets a 202 but Amplify Dashboard does not update.

**Comment by hloriana** [comment]
Hi @ishansharma 👋🏽 Thank you for opening this issue. I'm working to reproduce this issue and will respond once I have more information.

**Comment by hloriana** [comment]
Not able to reproduce this behavior. Please open a new issue if you continue to run into this behavior.
