### ISSUE TITLE
High Time to First Byte (TTFB)

### ISSUE THREAD

**Issue by marco910** [aws-amplify/amplify-hosting#2647]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d33j1egj9kkcu2

### Region

eu-central-1

### Amplify Hosting feature

Performance

### Describe the bug

I deployed a Next.js application with SSR to Amplify Hosting. When I request the page in the browser, I'm getting a high Time to First Byte (TTFB) on the initial request. All other resources like CSS and JS are loading normally and quick.

When I check this on multiple devices, I'm getting always the same result with a high TTFB.

With "high TTFB" I mean a TTFB of +1s and a complete page load time of +3s.

### Expected behavior

The TTF shouldn't take that long. When I host the application on a custom Node.js Server is way faster.

### Reproduction steps

1. Deploy a Next.js app with SSR to Amplify in the "eu-central-1" region.
2. Open it up in the browser and have a look in the "Network" tab of the dev tools in your browser.

**Comment by hloriana** [comment]
Hi @marco910 👋🏽 thanks for opening this issue. I'm not able to reproduce this but i can see this behavior happening with your app. I will update once I have more information.

**Comment by marco910** [comment]
Hi @hloriana Thank you for your quick reply!
I think the problem is maybe located between CloudFront and S3/Lambda. Because when I request the site on one device and few seconds later on another device it works very well and without the high TTFB.

**Comment by marco910** [comment]
Hi @hloriana 
Quick update for you: Today, I deployed a new app with the ID `dwlqy3pibcqzt` to the Amplify Console. The app runs also on Next.js with SSR and I'm facing the same issue as with the other site. 
When I have a look in the response header of the site, I'm getting two headers of `x-amz-cf-pop` with two different values. Is that normal or a bug?

**Comment by hloriana** [comment]
Was this new app a basic SSR app? Are you using any specific SSR features by any chance?

**Comment by jedwardblack** [comment]
I am experiencing the same issue with my NextJS with SSR on AWS Amplify. 12 seconds TTFB for this site: https://getyourpiece.io

**Comment by marco910** [comment]
@hloriana Yes, it's a basic Next.js app with `getStaticProps()` and Incremental Static Regeneration. All the pages are built at build time or in the background. So, there is nothing that could cause the high TTFB There are no "special" features. When I deploy the site to custom server, it's really fast.
I'm also deploying a Gatsby site with Amplify Hosting. With that, I don't have problems.

@jedwardblack In the response headers of your site saw that you are also getting the double `x-amz-cf-pop` header. I agree  with your guess that this could be caused by caching or CloudFront.

**Comment by jedwardblack** [comment]
I looked up the x-amz-cf-pop location codes that are in the response headers for my site using this: https://www.feitsui.com/en/article/3

The IAD50-C2 location is Washington Dulles; that makes sense.
The DWF56-P1 location doesn't exist, at least from what I could find.
The other Dallas-Fort Worth locations do exist, but not P1.

It is probably a problem that there are 2 of those headers, but I would imagine that the bigger problem is that the DFW56-P1 location doesn't exist.

**Comment by marco910** [comment]
Hi @hloriana Are there any updates on this?

**Comment by tyfuji** [comment]
Hi @hloriana we are experiencing the same problem with a SSR Next.js app. TTFB is regularly 300ms+ on all resources. We are testing using the provided amplify domain, not a custom domain, so the domain shouldn’t be a factor. Can anyone help with this?

**Comment by tyfuji** [comment]
To add some more information:
* The high response times are always accompanied by a "x-cache: Miss from Cloudfront" response header.
* Reloading the page immediately is fast (within 2 seconds) and all the resources Hit from Cloudfront.
* Loading a static resource in a new tab, we get Hit from Cloudfront and the resources are fast

The default Amplify Cloudfront TTL policy seems to be 2 seconds, could that have something to do with it?

**Comment by thibauld** [comment]
Hi @hloriana :wave: Same issue here.

We have a Next.js SSR app hosted on Amplify with the same High TTFB issue **for the `text/html` content** (no issue for other type of content as far as I can see).

Our app id is `d3pufjj6b49muy` on `us-east-1`

Here's more context:

* App is deployed from `production` branch where performance mode is enabled
![image](https://user-images.githubusercontent.com/197119/166857987-9c8e7b62-2077-4053-9834-92b2aa6a7598.png)

* From [your doc](https://docs.aws.amazon.com/amplify/latest/userguide/ttl.html#Performance-mode), it seems that performance mode should activate some edge CDN caching:
> Amplify Hosting performance mode optimizes for faster hosting performance by keeping content cached at the edge of the CDN for a longer interval.

* But it doesn't as we can see `cache-control: max-age=0` being passed in the request headers:
![image](https://user-images.githubusercontent.com/197119/166858495-9c85ca4d-f221-46f3-af2b-6e1a503668f7.png)

* Which logically causes Cloudfront to NOT cache the response:
![image](https://user-images.githubusercontent.com/197119/166858717-953196f6-0746-45ce-bf61-19a396045126.png)

* I thought that a quick fix would be to set custom headers... 
![image](https://user-images.githubusercontent.com/197119/166859464-dc309c3c-655a-4b12-b1dc-11d6ae0d206e.png)

* ... but it didn't work for a reason that is unknown to me :man_shrugging: It seems like a bug if I judge by #1170 and #2281 

Happy to share more information if that can be helpful.

**Comment by marco910** [comment]
Hi @thibauld I'm facing the same issue as you on two different Amplify apps. 

One app has a config for custom headers that looks like this:
```
customHeaders:
  - pattern: /_next/static/**/*
    headers:
      - key: Cache-Control
        value: 'public, max-age=31536000, immutable'
      - key: x-frame-options
        value: sameorigin
      - key: x-xss-protection
        value: 1; mode=block
  - pattern: /_next/data/**/*
    headers:
      - key: Cache-Control
        value: 'public, max-age=0, s-maxage=0, must-revalidate'
      - key: x-frame-options
        value: sameorigin
      - key: x-xss-protection
        value: 1; mode=block
  - pattern: '**/*[.html]'
    headers:
      - key: Cache-Control
        value: 'public, max-age=0, s-maxage=0, must-revalidate'
      - key: x-frame-options
        value: sameorigin
      - key: x-xss-protection
        value: 1; mode=block
```
All headers are getting applied and hitting from CloudFront if the files are cached. But I'm also facing the problem with the TTFB on the document request, which is around 3 seconds.

On the second app I'm only using performance mode without any custom headers and having a total page load time of around 6 seconds which is way too long.

**Comment by hloriana** [comment]
@marco910 apologies for the delay. Can you provide the other app ID for the app that's experiencing this issue? @thibauld thanks for providing these details. They will definitely help us determine the root cause. @tyfuji can you provide your app ID as well?

**Comment by ken-nah** [comment]
Hi @hloriana I am experiencing a similar issue as well.

**Comment by tyfuji** [comment]
We actually found some important information on this: It seems to be linked in our case to a cookie that gets modified on each pageload. It appears that changes to a browser cookie invalidate the Cloudfront cache, which by default this should not be the case. When we load our resources in fresh tabs, they become hits in Cloudfront, and future refreshes continue to stay hit, and have low TTFB. It is the browser environment which causes the cookie to continue changing, and therefore invalidates the Cloudfront cache. HTH

**Comment by tyfuji** [comment]
Hi there, any update on this @hloriana ? Unfortunately our client is unable to switch to Amplify because of this issue.

**Comment by richmengsix** [comment]
Any update on this issue? Our website takes 7 seconds to load after switching to SSR..

**Comment by TheTapHouse** [comment]
@hloriana We are also having this issue, anything we can do to mitigate in the meantime?

**Comment by hloriana** [comment]
Hi everyone, we apologize for the delay, we are prioritizing this issue and are working on reproduction and a possible workaround. Thank you all for your patience!

**Comment by tyfuji** [comment]
Thank you @hloriana . Please keep us updated. We decided to try a dummy test app with _SSG_ instead of SSR and got the same problem. This app shows "Next.js - SSG" as the framework in Amplify.

https://www.loom.com/share/cd753b01a5e542d29985f1e14abb0016

**Comment by tyfuji** [comment]
Thanks @jedwardblack ! Not an option for us but appreciate the tip.

@hloriana We were able to do some testing in our apps with performance mode on and off, and testing both static resources and the base index file. It seems like performance mode does more than just affect the headers. The basic finding is that the s-maxage and maxage directives do not influence the cache behavior the way one would expect.

## Next.js SSG (d1q37v148cianr)

**Performance Mode Off**

*Static resource*

- Cache-Control: public, max-age=0, immutable, s-maxage=2
- Result: ❌ Regularly getting slow “Refreshhit”, but refreshing in under 1s results in a fast “Hit”

*Document*

- Cache-control: public, max-age=0, s-maxage=2, must-revalidate
- Result: ❌ Regularly getting slow “Miss”, but refreshing in under 1s results in a fast “Hit”

**Performance Mode On**

*Static Resource*

- Cache-control: public, max-age=0, immutable, s-maxage=600
- Result: ❌ Regularly getting slow “RefreshHit”, but refreshing in under 1s results in a fast “Hit”
- Experiment:
    - Changed cache-control to: public, max-age=31536000, immutable
    - Result: ❌ Regularly getting slow “RefreshHit”, but refreshing in under 1s results in a fast “Hit”

*Document*

- Cache-control: public, max-age=0, s-maxage=600, must-revalidate
- Result: ✅ All good!

## Next.js SSR (dpbvd6d215akw)

**Performance Mode Off**

*Static Resource*

- Cache-Control: public,max-age=31536000,immutable
- Result: ✅ All good. Asset sticks in Cloudfront for a substantial period.

*Document*

- Cache-Control: public, max-age=0, s-maxage=2, must-revalidate
- Result: ❌ Regularly getting slow “Miss”, but refreshing in under 1s results in a fast “Hit”

**Performance Mode On**

*Static resource*

- Cache-Control: public, max-age=0, immutable, s-maxage=600
- Result: ❌ Regularly getting slow “Miss”, but refreshing in under 1s results in a fast “Hit”

*Document*

- **cache-control:** public, max-age=0, s-maxage=600, must-revalidate
- Result: ❌ Regularly getting slow “Miss”, but refreshing in under 1s results in a fast “Hit”

**Comment by tyfuji** [comment]
Just checking on this! For now we have had to set up production hosting off of amplify until this is resolved. We’d love to fully consolidate into Amplify as soon sa we can.

**Comment by Nimdy** [comment]
I seem to have adjusted a lot but its hit or miss. I have a cheat but its working, I need to get it working better. 



![image](https://user-images.githubusercontent.com/16698453/177544185-9b643313-da63-47a1-8112-cacd842e8922.png)

![image](https://user-images.githubusercontent.com/16698453/177544320-8f8cd3c0-c8e9-433e-b6b8-b5fe4ea37476.png)

**Comment by tyfuji** [comment]
Any word? Our client is still waiting on help with this to fully utilize Amplify.

**Comment by bogdan-bakhmetiev** [comment]
Facing same issue

**Comment by walkingtospace** [comment]
any update? the first visit to our website hosted on Amplify is very slow

**Comment by nvduc2910** [comment]
@walkingtospace creating a lambda function + EventBridge scheduler for requesting to the website every 5 mins would help.

**Comment by Nimdy** [comment]
I corrected this by doing what @nvduc2910 stated about a month ago.

Here is the code we use:

```
const axios = require('axios');

exports.handler = async (event) => {
            return axios.get(`https://www.diontraining.com`)
            .then(res => {console.log("success"); return res.data}).catch(err => console.error(err));
};
```

<img width="527" alt="image" src="https://user-images.githubusercontent.com/16698453/184501527-9737e023-2c25-4082-bdd7-19e2a62a8122.png">

Hope this helps until something else is done in the future.

**Comment by Nimdy** [comment]
Here is the code we use and did what @nvduc2910 said. We started this about a month ago.

Lambda function
```
const axios = require('axios');

exports.handler = async (event) => {
            return axios.get(`https://www.YOURWEBSITE.com`)
            .then(res => {console.log("success"); return res.data}).catch(err => console.error(err));
};
```

EventBridge
<img width="527" alt="image" src="https://user-images.githubusercontent.com/16698453/184501595-37fbc4e4-7aea-4bc7-b9cc-41b8d5f060b7.png">

**Comment by bunge12** [comment]
Just deployed a project to Amplify and noticed this issue :( Amplify seemed so promising but between 10-minute build times and now this we may consider another provider until these issues are fixed.

**Comment by tyfuji** [comment]
Yeah, unfortunately Amplify is not something we can recommend to clients until this is fixed.

**Comment by colin-riddell** [comment]
I too might need to consider alternative solutions that will allow hassle free deployment of Next.js / SSR applications that load quickly. Very sad, since bits of the Amplify platform work quite well, but other bits are just flaky as hell.
Keen to keep a track of progress on this issue.

**Comment by lyhlg** [comment]
I'm also facing the same problem.
Could you please share your progress in resolving this issue?? @hloriana

**Comment by michrome** [comment]
Thank you all for your patience on this. We are improving Amplify Hosting's support for apps that use SSR (server-side rendering), including TTFB (time to first byte).

I'm looking for volunteers who use Next.js to test and give feedback on the improvements as part of a gated beta in the coming weeks.

If you're interested in taking part, email me at [jrm@amazon.com](mailto:jrm@amazon.com). In the email, let me know:

* Your AWS Account ID;
* The email associated with the account.

Looking forward to hearing from you,
Mike

**Comment by Edouardsharies** [comment]
I'm also facing the same problem.
Could you please share your progress in resolving this issue?? @hloriana @michrome

**Comment by michrome** [comment]
Last week we announced [improved support for Next.js 12 and 13](https://aws.amazon.com/blogs/mobile/amplify-next-js-13/). You should see improved TTFB after [migrating to that release] (note that as part of that change, the CloudFront for your app is fully managed by Amplify Hosting and is not listed in your AWS account) or creating a new Next.js 13 app.
