### ISSUE TITLE
problem calling /api routes in nextjs build

### ISSUE THREAD

**Issue by bbarbour** [aws-amplify/amplify-hosting#2650]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1kdidycueu4b6

### Region

us-east-1

### Amplify Hosting feature

Backend builds

### Describe the bug

Since yesterday getting 503 unavailable errors on any api routes on my nextjs deployment. 

i have tried to recreate with a very vanilla next-js app - the front end pages work just fine, but the api/hello route returns 503. 

tried to execute the lambda@edge test and getting the following request

-----

Response
{
  "errorType": "Runtime.UnhandledPromiseRejection",
  "errorMessage": "TypeError: Cannot read property 'headers' of undefined",
  "trace": [
    "Runtime.UnhandledPromiseRejection: TypeError: Cannot read property 'headers' of undefined",
    "    at process.<anonymous> (/var/runtime/index.js:35:15)",
    "    at process.emit (events.js:400:28)",
    "    at processPromiseRejections (internal/process/promises.js:245:33)",
    "    at processTicksAndRejections (internal/process/task_queues.js:96:32)"
  ]
}

Function Logs
START RequestId: 9f1b426c-dd06-42b2-a809-14294d410adf Version: $LATEST
2022-03-15T05:41:05.884Z	9f1b426c-dd06-42b2-a809-14294d410adf	ERROR	TypeError: Cannot read property 'headers' of undefined
    at Object.apiResolver (/var/task/chunks/458.js:2660:55)
    at Module.<anonymous> (/var/task/chunks/458.js:49:30)
2022-03-15T05:41:05.885Z	9f1b426c-dd06-42b2-a809-14294d410adf	ERROR	TypeError: Cannot read property 'headers' of undefined
    at Object.apiResolver (/var/task/chunks/458.js:2660:55)
    at Module.<anonymous> (/var/task/chunks/458.js:49:30)
2022-03-15T05:41:05.886Z	9f1b426c-dd06-42b2-a809-14294d410adf	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: Cannot read property 'headers' of undefined","reason":{"errorType":"TypeError","errorMessage":"Cannot read property 'headers' of undefined","stack":["TypeError: Cannot read property 'headers' of undefined","    at Object.apiResolver (/var/task/chunks/458.js:2660:55)","    at Module.<anonymous> (/var/task/chunks/458.js:49:30)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: Cannot read property 'headers' of undefined","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:400:28)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:96:32)"]}
END RequestId: 9f1b426c-dd06-42b2-a809-14294d410adf
REPORT RequestId: 9f1b426c-dd06-42b2-a809-14294d410adf	Duration: 380.02 ms	Billed Duration: 381 ms	Memory Size: 512 MB	Max Memory Used: 65 MB	Init Duration: 165.25 ms	
Unknown application error occurred

Request ID
9f1b426c-dd06-42b2-a809-14294d410adf

### Expected behavior

expecting default response for api routes {"name": "john doe"}

### Reproduction steps

1. npx next-create-app
2. add to gitlab
3. from aws amplify console connect to repo
4. build/deploy
5. browse to .../api/hello 
6.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by bbarbour** [comment]
Still getting problems here 

503 ERROR
The request could not be satisfied.
The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

Generated by cloudfront (CloudFront)
Request ID: vcDd8m7igko619vTbdoFLFbwa9JPIpgGLfyFLUhMwtONiDaHNlTM8A==

**Comment by calavera** [comment]
Sorry about the trouble. We're currently looking at this problem. We already have a different issue open that we're tracking in https://github.com/aws-amplify/amplify-hosting/issues/2518.

I recommend you to go to that issue and click the **Subscribe** button so you can get notified when we have a fix in place. I'm going to close this issue so we don't have duplicated tickets.

**Comment by bbarbour** [comment]
@calavera this is still broken and the associated issue at #2518 appears to be something else, is someone able to take a look or is there another option here?

**Comment by bbarbour** [comment]
OK sorry this is resolved - i noticed for some reason next was upgraded to v12 - which is not supported in amplify

**Comment by foobarnes** [comment]
If anyone can't figure it out after a downgrade: https://github.com/aws-amplify/amplify-hosting/issues/2518#issuecomment-1228954355
