### ISSUE TITLE
How to use amplify hosting preview with mono repo? 

### ISSUE THREAD

**Issue by mithun35h** [aws-amplify/amplify-hosting#2651]
**Please describe which feature you have a question about?**

PR Previews in monorepo

**Provide additional details**
I have a monorepo, which is connect to amplify hosted app

Below is the app structure

apps
-platform
-widget
libs
-ui

I have enabled PR previews, it works, but the problem is, it randomly picks across application and their no way to specify which app to pick the preview from?

I have also enabled DIFF_ONLY - which makes other app fail if there is no change - how to make them success as this cause the PR check as failure

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**

**Comment by mithun35h** [comment]
ok, amplify posts all the successful build previews as comments, which is perfect as you can preview all apps which are changed

The only problem now seems to be is, the amplify check for github PR checks is failing or in loading state

Next steps, i think it's better to disable AMPLIFY_DIFF_DEPLOY as some libs might be used in apps (which have no changes in the PR), which can be previewed

**Comment by hloriana** [comment]
Hi @mithun35h  Apologies for the delay. 

> The only problem now seems to be is, the amplify check for github PR checks is failing or in loading state

I did not run into this issue when creating previews for monorepo apps. Please re-open if you are continuing to run into this behavior.
