### ISSUE TITLE
Redirection from non www to www url

### ISSUE THREAD

**Issue by ParulSharma2622** [aws-amplify/amplify-hosting#2652]
We have an amplify react app setup. below are the details:

app id : d280tc8bca7hos
app region : ap-southeast-2

Earlier the domain was mapped without www. But now we have configured www and setup a redirect from non www to www.

Unfortunately, it's working for new users only and not for existing ones. 

Existing users dont get redirected to www url until they hard refresh the page and if they again try to load the app without www url they face same problem again.

Please let me know what could be the reason for this and how it will be resolved.

Thanks,

**Comment by hloriana** [comment]
HI @ParulSharma2622 👋🏽 thanks for raising this question. I was not able to reproduce this issue but we are still investigating. Will update once I have new information.

**Comment by hloriana** [comment]
I imagine the page is being cached in your existing customers' browsers. They should try clearing their cache to see if this removes this recurring behavior. Please let us know if this does not resolve the issue.

**Comment by ParulSharma2622** [comment]
yes, If they hard referesh the page i.e.. ctrl+f5 then it work but if they again try to access the same page without www then it doesn't work.

This is strange behaviour and I am not able to understand what's wrong. We've even re-created a new app so that the issue is resolved but it's not for some reasons.

**Comment by ParulSharma2622** [comment]
Hi, @hloriana did you checked it further.

**Comment by ParulSharma2622** [comment]
I think the issue is not related to caching. Issue is at domain level. 

I have noticed that my updated code isn't getting served from non www url (without hard refresh) which is why it doesn't automatically get redirected to www url.

I don't understand why the updated code isn't reflecting back on non www url.

Please somebody help me resolve this issue.

**Comment by hloriana** [comment]
@ParulSharma2622 which DNS provider is your domain hosted with?

**Comment by ParulSharma2622** [comment]
@hloriana 

our DNS provider is **AWS Route 53**

**Comment by ParulSharma2622** [comment]
@hloriana are you still looking into this issue.

**Comment by ParulSharma2622** [comment]
anyone looking into this issue.

**Comment by ParulSharma2622** [comment]
anyone there, who can help me with this issue.

**Comment by hloriana** [comment]
Hello, apologies for the delay, we have not yet root caused this behavior and we have not been able to reproduce this. I'm syncing with the team for an update. Thank you for your patience!

**Comment by benhurley** [comment]
https://stackoverflow.com/questions/71701660/amplify-and-goddady-forwarding-to-www-subdomain

**Comment by benhurley** [comment]
> @benhurley I'm having the same issue from GoDaddy to Amplify...

Glad it's not just me. We are running our site rn off an app. subdomain.

**Comment by ianhirsch** [comment]
Yeah unfortunately the naked domain for the site that we migrated is the top ranking address in google search so it is really turning into a big deal 😓

**Comment by swaminator** [comment]
Unfortunately this is not something we can handle at the Amplify end. Browsers by design cache served pages and won't change behavior until a hard refresh or until your next deployment.

**Comment by benhurley** [comment]
> Unfortunately this is not something we can handle at the Amplify end. Browsers by design cache served pages and won't change behavior until a hard refresh or until your next deployment.

Is this because AWS can't provide a public load balancer IP for Amplify? That appears to be how your competitors handle this situation.

For anyone else that can't migrate to Route 53 (a tall ask for a domain currently in use for company email, endpoints, etc), I was able to stand up a landing page with a competing service that uses www as the primary domain and an alias record to their load balancer to redirect naked to www.
