### ISSUE TITLE
Root domain not accessible 

### ISSUE THREAD

**Issue by jamessrose** [aws-amplify/amplify-hosting#2658]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2dp62hws6ftgb

### Region

eu-west-1

### Step

Domain availiable

### Status

Root domain not accessible 

### Issue or question

Hi

I previously had an issue where my domain would not activate - however,  i readded the domain and that solved issue (now all green).

However, now the root domain https://fplalerts.com/ is not accessible but https://www.fplalerts.com/ is working fine ?

Any ideas?

### Error message

This site can’t be reached

**Comment by hloriana** [comment]
Hi @jamessrose sometimes it takes a while for the root domain to become active. I just navigated to it and was able to load your site. Please try again and let me know if you're running into this issue still.

**Comment by jamessrose** [comment]
Yes thanks, working now - i realised i need to add a ANAME record (which i had to switch DNS to route 53 first) - but all good now thanks

**Comment by hloriana** [comment]
Awesome, what DNS provider were you using before?

**Comment by jamessrose** [comment]
GoDaddy - but they don't offer ANAME / Alias - so that was the root issue
