### ISSUE TITLE
How to set a sub sub-domain in the Domain management console

### ISSUE THREAD

**Issue by julienlaurent-migso** [aws-amplify/amplify-hosting#2659]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3ta305xte59t6

### Region

eu-central-1

### Step

Domain management

### Status

Failed

### Issue or question

Hi, 
we are working through multi environments, with several Amplify Apps 
(Dev / Test / Stagging + one environment per client : prod01 / prod02 / ...)

Each environement app shared the same ressources like Cognito User Pool.
For cross authentication needs we are using cookies to share auth tokens.

For the moment our domain configuration is like that:
`https://<env>-<app>.ourdomain.com` (our domain is registered through AWS Route 53)

But to improve our cookies security we want to update our configuration domain to : 
`https://<app>.<env>.ourdomain.com`  (and manage our cookies at this level `.<env>.ourdomain.com`

When we try in the amplify console to set up our subdomain like :  `<app>.<env>`  we got this issue:
![image](https://user-images.githubusercontent.com/79509459/159164992-54419d4c-88e6-44f5-989e-346b7686f427.png)

How can we manage this configuration ? 
thank you for your help,

**Comment by hloriana** [comment]
Hi @julienlaurent-migso 👋🏽 did you try following the steps to set up a multilevel subdomain? You'd want to add `<env>.yourdomain.com` as a domain and exclude the root. You would then add `<app>.` as a subdomain. Here are the instructions to do so: https://docs.aws.amazon.com/amplify/latest/userguide/to-manage-subdomains.html#to-add-a-multi-level-subdomain. Please let us know if these steps work for you.

**Comment by hloriana** [comment]
Thank you for providing further clarification. You can share cookies across subdomains within an app but not across multiple apps because a CNAME can only resolve to one distribution. Each custom domain is connected to its own CloudFront distribution and there is no way to associate a domain with multiple distributions.

**Comment by julienlaurent-migso** [comment]
Hi @hloriana,
I am not agree with you, we can share cookies between all apps carried by the same domain.
I am actually doing this thing to be able to share token authentication accross my Amplify Apps. 

See below my amplify app:
![image](https://user-images.githubusercontent.com/79509459/160078409-a483c389-7e8f-4c41-9448-64905733fadf.png)

For each app i have defined a related sub domain for each environment:

My domains for TLG:
![image](https://user-images.githubusercontent.com/79509459/160078625-3cc635a1-f28d-47a7-832a-14870f807fe1.png)

My domains for CORE:
![image](https://user-images.githubusercontent.com/79509459/160079470-f7c1f5d4-a5f0-4a4f-9f30-6b457810f689.png)

Same logic for all my apps...

And my need is to be able to set my domains like that:
1) domain : `.mydomain.com`
2) subdomain : `environmentName.mydomain.com`
3) sub-subdomain : `appName.environmentName.mydomain.com`

Like that:
![image](https://user-images.githubusercontent.com/79509459/160082108-01d0e0f7-7a41-4f61-be49-99d4a8e1a146.png)

How can i manage my domains like that ? thank you

**Comment by julienlaurent-migso** [comment]
@hloriana any update on this subject ?

**Comment by Jay2113** [comment]
Hi @julienlaurent-migso, thank you for your continued patience and apologies for the delayed response on this issue.

Here is a solution that you can consider using for your use-case. You will need to attach 4 domains (each with 1 subdomain) to your app as follows:
```
Amplify App 1

Domain: env1.mydomain.com
Subdomain: app1.env1.mydomain.com
```
![Screen Shot 2022-07-08 at 2 25 21 PM](https://user-images.githubusercontent.com/38470430/178072533-766e0b16-f121-4892-a52b-bf9ed808bbfc.png)

```
Amplify App 1

Domain: env2.mydomain.com
Subdomain: app1.env2.mydomain.com
```
![Screen Shot 2022-07-08 at 2 25 44 PM](https://user-images.githubusercontent.com/38470430/178072953-ff8e304c-6724-4c63-9fef-9a00eada1b7e.png)

```
Amplify App 2

Domain: env1.mydomain.com
Subdomain: app2.env1.mydomain.com

Domain: env2.mydomain.com
Subdomain: app2.env2.mydomain.com

and so on...
```
