### ISSUE TITLE
Uptime Robot unable to check on amplify site

### ISSUE THREAD

**Issue by acomito** [aws-amplify/amplify-hosting#2662]
I have a vanilla react app on amplify. I have uptime robot setup but it's just getting "connection timeout" and thinks the site is down.

Some other details

- The site is definitely not down, I checked
- I can hit the website url from things like postman too and I get back the html I want
- When I host the same react app on netlify, I can hit the url with uptime roboto and it gets a correct response that it's up
- I can't get any more details from uptime robot about what error it's getting (is it a CORs error message, etc-- they wont say and their UI won't give any details)
- I have uptime robot setup to ping our backend API, and all is working well. So it's not a matter of us not understanding how to setup uptime robot

Given that I can hit the same app when it's hosted on netlify, it feels like some kind of issue with the default headers that amplify sets up maybe?

I sort of remember us having a similar issue with reflect.run too

Can anyone point me in the right direction?

**Comment by hloriana** [comment]
Hi @acomito I'm not familiar with uptime robot but I will take a look and see if I can reproduce.

**Comment by acomito** [comment]
Thanks @hloriana . I remember we had some issues with reflect.run running against our site as well... maybe a header setting that needs to be changed from the amplify defaults to allow services like this to programmatically hit the website?

**Comment by acomito** [comment]
@hloriana I wanted to restart this issue.

We're trying to monitor uptime with synthetic API tests on datadog and having the same issue.

Is there a certain header that these uptime/pinging services are sending that amplify is saying no to?

**Comment by acomito** [comment]
Seems like maybe the default cloudfront is blocking the user agent from "robots"

**Comment by hloriana** [comment]
Apologies for the lack of updates on this issue. If these 3rd party tools depend on the `user-agent` header, then that is likely why the functionality is failing.  

The `user-agent` header is replaced with a value of "Amazon CloudFront", this is because we don't make the user-agent part of the cache key in the interest of increasing your cache hit ratio. Otherwise, given the cardinality of this header, you would experience a very low cache hit ratio, which is undesirable.
