### ISSUE TITLE
Download amplify binary

### ISSUE THREAD

**Issue by Revhealthkannan** [aws-amplify/amplify-hosting#2670]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

https://besremi.revhealthstaging.com/

### Amplify Hosting feature

Manual deploys

### Describe the bug

Hi, i would like to download the binary which is already running in my staging.  because production is hosted with our partners.
We are using amplify to create the website and we don't want to build it local for sending the binary to production.

### Expected behavior

need a option to download the existing app binary

### Reproduction steps

NA

### Build Settings

```yaml
NA
```

### Additional information

NA

**Comment by hloriana** [comment]
Hi @mwarkentin there aren't any binaries. With manual deploys, we just unzip and deploy the given files as is. In any case, if there are files that you need to access, it's best to open a case with [AWS Support](https://us-east-1.console.aws.amazon.com/support/home?region=us-east-1&skipRegion=true#/) so you can verify your identity and they can help you access the information you're seeking.
