### ISSUE TITLE
Unable to create a NextJS application in a monorepo as SSG, Amplify defaults to SSR and build fails

### ISSUE THREAD

**Issue by clawrence121** [aws-amplify/amplify-hosting#2671]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2wz88kivlk99n

### Region

ap-southeast-2

### Amplify Hosting feature

Build settings, Custom builds, Monorepo

### Describe the bug

I am unable to specify I would like to use Amplify's SSG build settings when connecting my repo.

On creation, Amplify detects a NextJS repo and attempts to create an SSR backend for me, with no way for me to specify that I am in need of SSG deployment.
As such, when building Amplify cannot find the required files and fails:
<img width="1318" alt="Screen Shot 2022-03-29 at 7 13 06 pm" src="https://user-images.githubusercontent.com/23254373/160565305-caa1300e-5982-4de9-8c3d-dc7d71035a83.png">

I would like to be able to specify if the NextJS app is SSR or SSG, when I use a base NextJS repo with export specified in the package.json it works fine (detects and deploys with SSG).
<img width="971" alt="Screen Shot 2022-03-29 at 7 18 56 pm" src="https://user-images.githubusercontent.com/23254373/160566423-e0c59941-5f74-442f-b81e-f6ebbe6c8e82.png">
<img width="234" alt="Screen Shot 2022-03-29 at 7 19 14 pm" src="https://user-images.githubusercontent.com/23254373/160566468-d25f8a15-da0c-4987-9197-5872d0b4bab4.png">

I would like to use S3 with Cloudfront, but my use case relies on deploy hooks quite heavily (it's a statically generated CMS frontend), so if anyone can suggest that can help that would be awesome.

### Expected behavior

I would like to be able to select SSR or SSG when creating the application. I know the SSG setting in Amplify works for this use case, I just need to be able to set it myself.

### Reproduction steps

1. Create a NextJS application using the NX monorepo build too https://nx.dev/next/overview
2. Set up the application for static deployment by adding an export script to the package.json, eg "my-app-export": "nx rn my-app:export"
3. Push to git provider of choice (I used gitlab)
4. Create a new Amplify application, following the basic setup steps, and defining the new export command and output location in the build steps
5. Allow the app to build, and it will fail when trying to deploy SSR resources

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install --frozen-lockfile
    build:
      commands:
        - yarn my-app-export
  artifacts:
    baseDirectory: dist/apps/my-app/exported
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by indiejoseph** [comment]
Actually once the project detected your app is SSR, you cannot change it later on, please make sure the branch you connected with next export in your build script for Amplify to detect it correctly.

**Comment by hloriana** [comment]
If you're still running into this issue, please feel free to re-open. Thank you!
