### ISSUE TITLE
Build failing with 429 errors from github

### ISSUE THREAD

**Issue by l-hendriks** [aws-amplify/amplify-hosting#2672]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

Since about a week or so we intermittently encounter lots of build fails because of 429 errors (multiple daily). In our package.json we have a few dependencies to github packages (so dep: 'https://github.com...') and it fails on these. This used to never happen and causes builds to completely fail.

### Expected behavior

I would expect to not have so many 429 errors.

### Reproduction steps

It happens intermittently on any build

**Comment by hloriana** [comment]
Hi @l-hendriks can you provide you app ID and region so we can further investigate?

**Comment by l-hendriks** [comment]
sure! eu-west-1 and d21nzwkm439ia

**Comment by hloriana** [comment]
Thanks for your communication. Can you also provide the logs that show these 429 errors?

**Comment by l-hendriks** [comment]
Sure, it goes from "clong repository" to "backend" in the pipeline, that log is the following:

```
                                 # Starting phase: build
                                 # Executing command: export BUILD_ID="***"
...

2022-03-29T09:42:09.000Z [INFO]: yarn install v1.22.0
2022-03-29T09:42:09.130Z [INFO]: [1/4] Resolving packages...
2022-03-29T09:42:09.805Z [INFO]: [2/4] Fetching packages...
2022-03-29T09:42:18.345Z [WARNING]: error Command failed.
                                    Exit code: 128
                                    Command: git
                                    Arguments: ls-remote --tags --heads https://github.com/***.js.git
                                    Directory: /codebuild/output/src618599175/src/platform
                                    Output:
                                    fatal: unable to access 'https://github.com/***.js.git/': The requested URL returned error: 429
2022-03-29T09:42:18.350Z [INFO]: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
2022-03-29T09:42:48.249Z [ERROR]: !!! Build failed
2022-03-29T09:42:48.328Z [ERROR]: !!! Non-Zero Exit Code detected
2022-03-29T09:42:48.328Z [INFO]: # Starting environment caching...
2022-03-29T09:42:48.328Z [INFO]: # Uploading environment cache artifact...
2022-03-29T09:42:48.402Z [INFO]: # Environment caching completed
Terminating logging...
```

the last few days the error seems to have disappeared though!

**Comment by l-hendriks** [comment]
Thanks a lot for the reply! I have added the github token, the issue hasn't been going on for a while now so might be that that fixed the issue.
