### ISSUE TITLE
Unable to connect branch for hosting after OAuth to GitHub App code access for triggering build

### ISSUE THREAD

**Issue by Hamza141999** [aws-amplify/amplify-hosting#2677]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dwfmevspagm4e

### Region

eu-central-1

### Amplify Hosting feature

Manual deploys

### Describe the bug

Amplify is shifting from OAuth, to GitHub Application to access the code. When I proceeded to deploy the a branch from my GitHub repo, it redirected me to choose my GitHub account, and then to select a particular repo/all repos. After I was done selecting my GitHub branch for AWS Amplify to access, I expected Amplify would allow deployment, but instead, I'm being redirected again and again to the screen where we're asked to select a repo/all repos. (I am the owner of that repo so there aren't any permission issues)

### Expected behavior

After selecting the particular branch I wanted to deploy, Amplify would proceed on branch deployment 

### Reproduction steps

1. Click on "Connect branch" button under "Hosting Environments" inside your amplify app
2.  It will redirect you to a page asking where would you like to install AWS Amplify region
3. Select any, and choose either a specific branch, or all repos. Click save
4.  It will loop you on the same page and won't let you proceed to deploy

**Comment by Athena96** [comment]
Hi @Hamza141999 were you by chance trying to connect a repo through an organization you have access to, or was the repo in your own account?

**Comment by Hamza141999** [comment]
> Hi @Hamza141999 were you by chance trying to connect a repo through an organization you have access to, or was the repo in your own account?

I was trying to connect the repo through an organization I have access to, of which I was given the ownership of as well.

**Comment by hloriana** [comment]
@Hamza141999 Can you try connecting again? Some changes were pushed. Please let us know if you are still blocked.

**Comment by Hamza141999** [comment]
> Hi @Hamza141999 were you by chance trying to connect a repo through an organization you have access to, or was the repo in your own account?



> @Hamza141999 Can you try connecting again? Some changes were pushed. Please let us know if you are still blocked.

Yeah its working now, thanks!
