### ISSUE TITLE
Cannot use GitHub organization repository

### ISSUE THREAD

**Issue by yukinakanaka** [aws-amplify/amplify-hosting#2678]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

ap-northeast-1

### Describe the bug

Hello, I'm creating new app using GitHub repository but I cannot use GitHub organization repository.

After giving persmissions and going back to aws, aws would redirect me to GitHub again.

1. Choose GitHub and click continue
![image](https://user-images.githubusercontent.com/8342501/161025145-8e0a8901-a779-42a1-99ab-7b4929001067.png)
2. Choose GitHub organization account
![image](https://user-images.githubusercontent.com/8342501/161025498-0fdcebb0-54b8-40c2-8b75-5b04bcb62791.png)
3. Install & Authorize
![image](https://user-images.githubusercontent.com/8342501/161025567-314c69d6-cd52-400f-8496-1eddf5ba485e.png)
4. Redirect GitHub again
![image](https://user-images.githubusercontent.com/8342501/161025781-fdfbd371-5d9d-4630-9569-a4b980f8546b.png)
5. I can confirm that install is done, but nothing is going on.
![image](https://user-images.githubusercontent.com/8342501/161025998-a12112b3-2ac3-41b9-aa99-a830ebc5a9b7.png)

---
I even re-authorized Amplify, as you've once suggested here: https://github.com/aws-amplify/amplify-hosting/issues/1347#issuecomment-1009299429
(but that did not help either)

### Expected behavior

I can proceed to the Select Repository screen, where I can choose a repository.

### Reproduction steps

I wrote in 'Describe the bug'.

**Comment by arundna** [comment]
Hi @yukinakanaka - Thanks for reaching out! We've made some changes in the backend. Can you please test the flow again and let us know if you still face the same issue?

If yes, can you collect the Console Logs from the browser and send an email to aws-amplify-customer@amazon.com?

Thanks!

**Comment by yukinakanaka** [comment]
Hi @arundna 
It was fixed! Thanks a lot for your help!
