### ISSUE TITLE
Create domain association failed One or more domains requested are already associated with another Amplify app:

### ISSUE THREAD

**Issue by karanpiplani** [aws-amplify/amplify-hosting#2681]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1xr43oj5tcyn0

### Region

ap-south-1

### Step

Add Domain

### Status

Failed

### Issue or question

While adding the custom domain in amplify app it says that the domain is already linked to another amplify app.
Though I verified and couldn't find the domain linking to another amplify app.
I am attaching the screenshot below for the reference.
<img width="1280" alt="Screenshot 2022-04-05 at 1 42 11 PM" src="https://user-images.githubusercontent.com/67543546/161709173-b16f1d91-1b80-4df3-9904-84841061fdfe.png">

### Error message

Create domain association failed One or more domains requested are already associated with another Amplify app:

**Comment by hloriana** [comment]
Hi @karanpiplani we can see those domains are associated with an Amplify app in another account. Please make sure you check all of your AWS accounts for apps created in the `ap-south-1` region. 

Please note we cannot provide support for cross-account issues via GitHub. If you still cannot find the app that is associated with those domains, create a ticket with [AWS Support](https://us-east-1.console.aws.amazon.com/support/home?region=us-east-1&skipRegion=true#/) for further assistance. Thank you!

**Comment by hloriana** [comment]
If you're still running into this issue, please feel free to re-open.
