### ISSUE TITLE
I cannot query users created through the lambda function

### ISSUE THREAD

**Issue by sulak2** [aws-amplify/amplify-hosting#2682]
I integrated a post confirmation lambda function in my authentication flow (which is build using cognito) to save users in the backend.
When this lambda function runs I can see that user has been created in the 'UserTable' of dynamo DB but I cannot query that user from inside my application and also I cannot see that user from inside of my amplify studio.

**Comment by hloriana** [comment]
Hi @sulak2  👋🏽 we're happy to assist you but first, please create a GitHub issue using the **Bug report** template. Thank you!
