### ISSUE TITLE
Amplify Console UI Bug: clicking the "Build" link doesn't do anything

### ISSUE THREAD

**Issue by reesscot** [aws-amplify/amplify-hosting#2686]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3inl0muob87le

### Region

us-east-2

### Describe the bug

When I go Amplify Console to look for status of an Amplify hosting deployment and it's at the build stage (hasn't reached deploy), when I click the "Build" link while my site is building during a deployment to Amplify Hosting, it doesn't do anything. However, when I click the icon above it will show the build information.

Image below illustrates that the "Build" text is broken and does nothing when you click it, but the icon works correctly when clicked.
![2022-04-06 14 52 03](https://user-images.githubusercontent.com/6165315/162078236-1bee7cb0-daf5-4302-80a7-84c25b1073fc.gif)

### Expected behavior

Both icon and "Build" text should show the build information when clicked.

### Reproduction steps

1. Go to Amplify Console and find a Amplify hosting site that's at the build stage
2. NOTE: this bug doesn't manifest itself for deployed sites. For some reason the "Build" link works fine for those, but if it's successfully deployed, I don't care as much about the build status.
3. Try to click the Build link
4. Notice that nothing happens
5. Click the icon above the Build link
6. Notice that the build information shows

**Comment by hloriana** [comment]
Hi @reesscot 👋🏽 thank you for raising this issue. This is a bug with the UI. We will add this to our backlog for prioritization. Thank you!

**Comment by Jay2113** [comment]
Hi @reesscot 👋 , thanks for your continued patience!

Over the past year, we have made several improvements to the Amplify Console and this bug seems to have been resolved as a part of it. Additionally, I performed some tests and I was unable to reproduce this particular behavior with multiple apps across different AWS regions. 

Can you please confirm if you are still running into this behavior?
