### ISSUE TITLE
Backend environments screen whites out

### ISSUE THREAD

**Issue by rubenchoi2** [aws-amplify/amplify-hosting#2687]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3r1hu2ggi78mc

### Region

ap-northeast-2

### Amplify Hosting feature

Access control

### Describe the bug

When I choose app - Backend environments - env, then the screen whites out after few seconds. 
Developer tool console(F12) has the following error:

vendors~main.js:59 TypeError: Cannot read properties of undefined (reading 'includes')
    at main.js:1:4057498
    at Array.some (<anonymous>)
    at F.V.generateTabs (main.js:1:4057471)
    at F.render (main.js:1:4059569)
    at zo (vendors~main.js:59:71428)
    at Uo (vendors~main.js:59:71227)
    at zs (vendors~main.js:59:112369)
    at ku (vendors~main.js:59:98325)
    at Cu (vendors~main.js:59:98253)
    at Su (vendors~main.js:59:98116)

Furthermore, Backend environments - env - Authentication - User pool - Sign-in experience,
I think there should be login(via amplify-app) history in <Cognito user pool sign-in>, but it is empty.

Suppose that we have a button to list S3 bucket once login in to amplify-app, <unAuth_role> always appeared in CloudTrail log, not <auth_role> even though I successfully logged in to amplify-app using { withAuthenticator } from '@aws-amplify/ui-react'

### Expected behavior

1. no white out.
2. cognito login history shown

### Reproduction steps

1. Amplify console - app - backend environments - env - wait few seconds (or choose Authentication tab)

**Comment by hloriana** [comment]
I wasn't able to reproduce this white screen. Please open a new issue if you continue to see this behavior.
