### ISSUE TITLE
Pr previews not created

### ISSUE THREAD

**Issue by axelkry** [aws-amplify/amplify-hosting#2688]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:eu-west-1:776484548923:apps/dlj4cpwmp3163

### Region

eu-west-1

### Amplify Hosting feature

Previews

### Describe the bug

Pr previews are almost never created in our repo anymore.. The issue sounds very similar to what was described in this [issue](https://github.com/aws-amplify/amplify-hosting/issues/1173#issuecomment-1088680149) .. but what the solution/root cause was not totally clear. 

We have a Monorepo with 30+ permanent branches which are used for dev environments, all these have pr-previews enabled but the previews are almost never created anymore. We also have quite a lot of old branches in the repo (1000+) mainly from old PRs which we will look into removing. but it would be great if we could get some help/guidance on how to find the root cause for why the pr-previews are not being created.

### Expected behavior

Pr-previews created for all branches where it has been enabled

### Reproduction steps

1. create a pull-request where the base-branch has pr-previews enable in the amplify console
2. notice that no pr-preview job or comment on the PR is created

**Comment by hloriana** [comment]
Hi @axelkry 👋🏽 thanks for opening this issue. We're taking a look to see if there is a limit you've exceeded. I will update you once I have more information.

**Comment by axelkry** [comment]
@ganipcanot Thanks! And just to clarify for future reference, the issue is that our "Branch autodetection pattern" matches more than 50 branches. And not that we have more than 50 branches in the github repo. Right?

**Comment by axelkry** [comment]
Understood 👍 .. Will PR-preview envs count towards this quota? I'm asking since each PR preview env is listed with the formad "pr-[number]" as "branches" in App Settings -> General
