### ISSUE TITLE
How can I delete my Hosting Environment only. 

### ISSUE THREAD

**Issue by jakcst** [aws-amplify/amplify-hosting#2691]
I've created a frontend hosting environment but can't get it to build. I'd like to simply remove it and move to beanstalk. However, I have a backend (auth) setup that I would like to keep in place. How can I accomplish this?

**Comment by hloriana** [comment]
Hi @jakcst 👋🏽 thanks for opening this issue. Two things here: 
1. What issues are you running into with building your application on Amplify? Please provide an AppID so we can investigate and help to unblock you.
2. You can continue to manage your backend via the [Amplify CLI](https://docs.amplify.aws/cli/) or using the [Amplify Studio](https://docs.amplify.aws/console/)

**Comment by alonsnir** [comment]
How about the original question - how to remove a hosting environment? In my case I have added via the console, it fails to build whatever errors it gets, how to remove it?

**Comment by rdpacheco** [comment]
@alonsnir I was able to remove mine by:

- AWS Amplify Console & Select App
- Actions (top right) > View app settings
- Scroll down to branches
- Select branch to remove Hosting from
- Actions (top right) > Disconnect branch

Then the hosting went away in my console. Not sure if thats what you need, but its what i needed
