### ISSUE TITLE
Can an existing cloudfront distribution be linked to amplify?

### ISSUE THREAD

**Issue by zadrafi** [aws-amplify/amplify-hosting#2693]
I have an amplify app that's a web hosting app. When I created it, it created a custom S3 Bucket and a CloudFront distribution that I can't seem to find but I'm having difficulty finding out whether its possible to link the app to an existing distribution. Any help is appreciated. 

Thank you

**Comment by calavera** [comment]
If you're using Amplify Hosting, you don't have direct access to the S3 Bucket, or CloudFront distribution. It's not possible to link an app to a distribution that you control.

**Comment by zadrafi** [comment]
Yes, but what about the documentation that shows that one can import existing resources via the amplify CLI such as using amplify import storage, or amplify configure hosting?
