### ISSUE TITLE
Hosting react app on AWS Ampilfy 

### ISSUE THREAD

**Issue by raboomar** [aws-amplify/amplify-hosting#2697]
I'm trying to host a react app on was amplify but during the building stage, I keep getting an error. I have attached pics of my setup. 

CustomerError: Artifact directory doesn't exist: build

`version: 1
frontend:
  phases:
    # IMPORTANT - Please verify your build commands
    build:
      commands: []
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths: []`

**Comment by raboomar** [comment]
`version: 1
frontend:
  phases:
    # IMPORTANT - Please verify your build commands
    build:
      commands: []
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths: []`

**Comment by hloriana** [comment]
Hi @raboomar can you provide you App ID?

**Comment by SeanRenet** [comment]
I am also having this problem.  is there an answer to it?  I am building a nextjs amplify app.

2022-07-16T16:56:08.974Z [INFO]: !!Invalid custom header config file. The `customHeaders` key should be an array
2022-07-16T16:56:09.004Z [ERROR]: !!! CustomerError: Artifact directory doesn't exist: build

**Comment by raboomar** [comment]
I wasn't in the right folder make sure your path is set right
