### ISSUE TITLE
domain activation not completed

### ISSUE THREAD

**Issue by xenyinnaya** [aws-amplify/amplify-hosting#2698]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Step

domain activation

### Status

not completed

### Issue or question

i have a domain registered at godaddy and have added a cname record in the dns server but i only see one cname record. kindly assist me to get back to the cname configuration file to be added at the dns server to add the second cname record. i can not find it my aws dns management setting. if it is not the issue with completing the activation of the domain, help me verify. 
![domain management error msg](https://user-images.githubusercontent.com/98754579/162868810-b636d99d-ebf2-48e4-8cf3-571ee98a7900.JPG)
![domain activation error](https://user-images.githubusercontent.com/98754579/162868854-b4d80224-dc30-4895-9fca-51b97c4cd026.JPG)

**Comment by hloriana** [comment]
Hi @xenyinnaya you should be to find the DNS records that need to be added in the dropdown menu under **Actions**. Please let us know if you're still running into this problem.

**Comment by hloriana** [comment]
Please re-open if you're still running into domain activation issues. Thank you!
