### ISSUE TITLE
Stuck at build and deploy steps

### ISSUE THREAD

**Issue by nicolasmplus** [aws-amplify/amplify-hosting#2699]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

ap-east-1

### Describe the bug

I have connected to a GitHub repo for build and deploy on code updates and setup a Incoming Webhook to build and deploy a static site periodically. Recently, I observed that some of the deployments cannot be completed.

Normally, the site can be deployed within 10 minutes.

<img width="806" alt="image" src="https://user-images.githubusercontent.com/53163737/162890210-14bec1ad-c237-4123-b6cb-99403c8551b6.png">

Recently, there were failures on the deployment.

<img width="799" alt="image" src="https://user-images.githubusercontent.com/53163737/162890258-a12fdd10-ad67-47b9-a74c-3106a6b84e2d.png">

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/53163737/162890319-ac8c3701-c5d8-4995-8498-0baf9b2cf24a.png">

And this message is shown.

<img width="516" alt="image" src="https://user-images.githubusercontent.com/53163737/162890348-2e88ae75-3a42-41d2-a96e-5d0a0d91d122.png">

Sometimes, it would not be deployed successfully and got stuck on the deploy stage so long that I needed to stop it. Sometimes, It would just work.

<img width="808" alt="image" src="https://user-images.githubusercontent.com/53163737/162890847-363d9675-c0e4-44f0-b47b-513ee97ccad9.png">

I guess the build was successful.

<img width="741" alt="image" src="https://user-images.githubusercontent.com/53163737/162891137-ca85a291-03f9-467a-97f2-2fd446306db6.png">

### Expected behavior

With the build being successful, the deployment is expected to be successful too.

### Reproduction steps

Not applicable

### Build Settings

```yaml
Not applicable
```

**Comment by nicolasmplus** [comment]
Sometimes, the log is saying the deployment is completed but it is not reflected on the UI.

<img width="686" alt="image" src="https://user-images.githubusercontent.com/53163737/162898762-9d82d765-e26d-4563-a715-6eb7d9b5a7a8.png">

```
2022-04-12T06:32:55 [INFO]: Beginning deployment for application xxxxxxx, branch:prod, buildId 0000004149
2022-04-12T06:32:55 [INFO]: Got archive: 153557 bytes
2022-04-12T06:32:56 [INFO]: Deployment complete

```

**Comment by hloriana** [comment]
Hi @nicolasmplus 👋🏽 thanks for raising this issue. For us to figure out why your deployments are failing, we need to investigate a bit further. Can you provide you App ID?

**Comment by nicolasmplus** [comment]
Hello @hloriana! I now have 2 apps suffering from the issue recently. They are `d1mxwac2gxvx2l` and `d2ucgbk8kwui22`. Thanks!

**Comment by hloriana** [comment]
@nicolasmplus apologies for the delay. Thanks for providing the app IDs , we're investigating.

**Comment by nicolasmplus** [comment]
@hloriana I see the deploying are returning to normal starting from 20-May. Will keep an eye on it in the coming week. Thanks!

**Comment by BwL1289** [comment]
Happening to me as well. Happy to provide info.
