### ISSUE TITLE
js error in AWS Amplify console which causes screen to go blank, preventing usage of amplify console

### ISSUE THREAD

**Issue by jonschoning** [aws-amplify/amplify-hosting#2700]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

js error in AWS Amplify console which causes screen to go blank, preventing usage of amplify console

![image](https://user-images.githubusercontent.com/137183/163093385-ccce1382-ae70-4694-8f90-3b1242521843.png)

### Expected behavior

no js errors

### Reproduction steps

clicking around in tabs

**Comment by hloriana** [comment]
Hi @jonschoning 👋🏽 thanks for raising this issue. Which tabs/settings were you clicking around in that produced this behavior?

**Comment by jonschoning** [comment]
Amplify > BackendEnvironments > "MyDevEnv" > API

**Comment by hloriana** [comment]
Apologies for the delay, I was able to reproduce this bug. We are tracking this bug for prioritization.

**Comment by swaminator** [comment]
@jonschoning can you still reproduce this? We are no longer able to repro. What browser are you using?

**Comment by jonschoning** [comment]
![image](https://user-images.githubusercontent.com/137183/168408019-f05d60f7-1706-4cb3-a4e7-fb9915652738.png)
chrome Version 101.0.4951.64 (Official Build) (64-bit)

**Comment by nadetastic** [comment]
Hi @jonschoning following up here - let me know if you are still facing this issue. If not we can close this out. Thanks!
