### ISSUE TITLE
What happens with my backend if I enabled amplify studio?

### ISSUE THREAD

**Issue by zzBrunoBrito** [aws-amplify/amplify-hosting#2705]
**Please describe which feature you have a question about?**
I have an existing amplify app with a lot of custom backend lambdas. Also have social sign up enabled. I would like to know what happens if I enable amplify studio, it will override my current backend with amplify studio?

**Provide additional details**

**What AWS Services are you utilizing?**
Amplify, amplify studio

**Provide additional details e.g. code snippets**

**Comment by swaminator** [comment]
@zzBrunoBrito no it won't. It will just give you a visual interface to view the backend.

**Comment by hloriana** [comment]
Amplify Studio will allow you to use a visual interface to view and interact with your backend resources. You can enable Amplify Studio for any of your existing Amplify apps in the console by navigating to **App settings** -> **Amplify Studio settings** -> Enable Amplify Studio.
