### ISSUE TITLE
Domain name is used by CloudFront distribution

### ISSUE THREAD

**Issue by MathieuLarocque** [aws-amplify/amplify-hosting#2713]
I don't have a CloudFront distribution but when I try to use Amplify to link with my domain, it says it is already used by a CloudFront distribution and I don't know how to delete something I don't see anywhere. 
It says this:

"Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below.
Error message: [CNAMEAlreadyExistsException] The following CloudFront distributions are already using one or more of your domains: [Distribution: *******MEZWLBW in AWS Account: ******200621, Distribution: *******MEZWLBW in AWS Account: ******200621]. If you own these distributions, please remove the domains from them first and then retry adding your domain. If you don't own them, then you may already have associated this domain to another Amplify App in another account or region."

If this is from another account, how do I disconnect my domain names from them?

**Comment by dod-jwulf** [comment]
If you are taking a domain over from someone it's possible that they could have a coudfront setup for the same domain name, in which case they would need to take theirs down first, and after those changes have propagated you should be able to connect yours.
