### ISSUE TITLE
NextJS - SSR Pages and Link Component returning 503 error when opened in new tabs (using rewrites)

### ISSUE THREAD

**Issue by maykelesser** [aws-amplify/amplify-hosting#2714]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1ldpv0104xmkw

### Region

us-east-1

### Amplify Hosting feature

Redirects

### Describe the bug

I have a website developed using NextJS ([Here](https://main.d1ldpv0104xmkw.amplifyapp.com/)).
I also have my site internationalized, so some routes are naturally rewritten inside next.config.js.

After completing the build and testing the routes, it works normally. However, if I open a route that uses SSG in a new tab (which uses the native Next/Link component), and it goes through the rewrite, it returns the message below.

(example: [Confiança e segurança](https://main.d1ldpv0104xmkw.amplifyapp.com/sobre/confianca-e-seguranca). But, if you access through the domain, and click on link, it works). The rewrite doesnt work if i've access the url without clicking.

> 503 ERROR
> The request could not be satisfied.
> The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
> If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
> Generated by cloudfront (CloudFront)
> Request ID: _4bRVM5ksb5qlfZaN379mcy_HvjZ27wSk_2dWMSbg_sMjk9HK0_M9w==

Something I've also noticed (and may have something to do with this problem) is that the 404 is not working (if I try to access a route that doesn't exist, the same error is generated).

Here i have my next.config.js, that handle those rewrites. Maybe, using the BeforeFiles parameters is causing the problem. But, this does not happen in a local environment or on another server (Netlify).

```
module.exports = {
    i18n: {
        locales: ['pt-BR'],
        defaultLocale: 'pt-BR'
    },
    images: {
        dangerouslyAllowSVG: true,
        contentSecurityPolicy: 'default-src \'self\'; script-src \'none\'; sandbox;',
    },

    // * We use rewrites to handle translated pages
    async rewrites() {
        return {
            beforeFiles: [
                {
                    source: '/sobre/confianca-e-seguranca',
                    destination: '/about/trust-and-security',
                },
                ...
            ]
        }
     }
}
```

### Expected behavior

Possibility to open site links without errors in new tabs, using rewrites normally.

### Reproduction steps

1. Open https://main.d1ldpv0104xmkw.amplifyapp.com/
2. Go to Footer and click in every link that uses rewrite settings (example: [Confiança e segurança](https://main.d1ldpv0104xmkw.amplifyapp.com/sobre/confianca-e-seguranca))
3. The error will be shown on the screen, if it is opened without going through the next/link.

**Comment by maykelesser** [comment]
I've removed the beforeFiles condition and fallback params, and it worked.

**Comment by calavera** [comment]
Thanks for investigating this issue. It looks like it's a duplicated of https://github.com/aws-amplify/amplify-hosting/issues/2701.

We're currently working on improvements for Next.js support, and this problem is in our radar. I'm going to close this issue so we don't have duplicated tickets. Feel free to subscribe to #2701 so you get notified when we resolve this problem.
