### ISSUE TITLE
AWS amplify "Configuration SSL" pending

### ISSUE THREAD

**Issue by PierreBalazuc** [aws-amplify/amplify-hosting#2715]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

https://eu-central-1.console.aws.amazon.com/amplify/home?region=eu-central-1#/d2y4s18nsmd981

### Region

eu-central-1

### Step

custom domain

### Status

Configuration SSL

### Issue or question

Hello,
I got an app running perfectly on amplify hosted on one of my domain. No error here. For migration reason, i need to deploy an other branch of my app on an other domain before clothing the existing one.
Current : www.securiz.co
New one : www.securiz.org

I choose to add a new custom domaine on an other connected branch, and now i'm stuck with the "Configuration SSL". It stay pending for 24h then failed.

I've check the custom domains troubleshooting guide, but i think my domain is broken. (securiz.org)
I don't know how to make it work. I read every thread dealing with this kind of error but no result for me...

I hope u guys can help me.

Kind regards (sorry for my english)

PB

**Comment by hloriana** [comment]
Hi @PierreBalazuc 👋🏽 thanks for reaching out. What DNS provider are you using?

**Comment by hloriana** [comment]
Can you also provide a screenshot of what you see during this step in setting up your custom domain? There may be instructions to add CNAME records or some other type of instructions.
