### ISSUE TITLE
Build failed to complete successfully.

### ISSUE THREAD

**Issue by rupam-kundu** [aws-amplify/amplify-hosting#2724]
Hello,

When trying to host my React app on Amplify hosting build is failing. Please find attached below the build log file.

[log.txt](https://github.com/aws-amplify/amplify-hosting/files/8580457/log.txt)

Please find below the contents of my amplify.yml file.

```version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
The application is running successfully locally.

Please help me resolve this issue.

**Comment by hloriana** [comment]
Hi @rupam-kundu can you provide your App ID so we can further investigate and also make sure you can build locally as well

**Comment by rupam-kundu** [comment]
Hi @hloriana . Thanks for your reply. My App Id is `d10nw5r62oxier`. I am able to build my application locally.

**Comment by Jay2113** [comment]
Hi @rupam-kundu 👋 , thanks for your continued patience and apologies for the delayed response on this thread.

From the provided build logs, it looks like the build failed with the following error:
```
2022-04-28T06:35:38.986Z [INFO]: Failed to compile.
2022-04-28T06:35:38.987Z [INFO]: Module not found: Error: Can't resolve 'mapbox-gl' in '/codebuild/output/src312621445/src/GlobalNextGenTech-website/node_modules/react-map-gl/dist/esm/components'
2022-04-28T06:35:39.026Z [WARNING]: npm
2022-04-28T06:35:39.026Z [WARNING]: ERR! code ELIFECYCLE
                                    npm ERR! errno 1
2022-04-28T06:35:39.029Z [WARNING]: npm
2022-04-28T06:35:39.029Z [WARNING]: ERR! globalnextgentech-website@0.1.0 build: `react-scripts build`
                                    npm ERR! Exit status 1
                                    npm ERR!
                                    npm ERR! Failed at the globalnextgentech-website@0.1.0 build script.
                                    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Kindly verify that the `mapbox-gl` dependency is installed correctly with the appropriate version in your `package.json` file for your Amplify app `dmjok2glzhae9`. You can also perform a clean install of the dependency as follows:
```
rm -rf node_modules
rm package-lock.json
Add the dependency
npm install
Commit the changes to the git repository and it will trigger a new build
```
