### ISSUE TITLE
Problem Hosting a Static Website in AWS Amplify Console

### ISSUE THREAD

**Issue by ddmora** [aws-amplify/amplify-hosting#2729]
**Please describe which feature you have a question about?**

AWS Amplify hosting a static website.

**Provide additional details**

I am using AWS Amplify to create a static website. This website contains an html form that will send the form information to a lambda function, and provides and answer.  I am using this [tutorial](https://aws.amazon.com/getting-started/hands-on/build-web-app-s3-lambda-api-gateway-dynamodb/) as guide, Well, my problem is that I need to create a datalist with thousands of options . So What I am doing is putting all those options in a json file and I am uploading this file using the code showed below. **This code works in my local IDE but not works when I upload a zip file in AWS Amplify console**. Why?

**What AWS Services are you utilizing?**
AWS Amplify, AWS Lambda

**Provide additional details e.g. code snippets**

```
 <p id="p-branch">
                        <label for="branch">Branch:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                        <input list="list" class="large" id="branch" role="combobox" autocomplete="on" name="branch"
                        placeholder="Select a branch..."/>
                        <datalist  id="list">
                        </datalist> 

                        <script type="text/javascript">
                    
                            $(document).on('ready',function (){
                                 
                                $.getJSON('branch.json', function(data) {
                                    $.each(data, function(key, valor) {
                                        $("#list").append('<option value="' + valor['BranchName'] +
                                         '" id="' +  valor['ID'] +
                                          '" name="' + valor['BranchName']  + 
                                          '">' + 'Id: ' + valor['ID']  + ' - Number: ' + valor['BranchNumber'] + ' - Name: ' + valor['BranchName'] +
                                           ' </option>');
                                    }); // close each()
                                }); // close getJSON()
                            });
                        </script>

 </p>

```

**Comment by hloriana** [comment]
Hi @ddmora 👋🏽  do you receive any errors after uploading your zip folder to Amplify? Please share any screenshots or error logs you may have.

**Comment by hloriana** [comment]
Please re-open if you're still running into this issue.
