### ISSUE TITLE
Install and authorize GitHub App returns not enough permissions

### ISSUE THREAD

**Issue by blanchma** [aws-amplify/amplify-hosting#2730]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-2:885048644588:apps/d3nswdh9hjl9sk

### Region

us-east-2

### Describe the bug

I tried the new Github App. I gave permissions to an organization where I'm admin as well as admin in the repositories but I keep getting: "We do not have permission to access this repository. Please update your permissions and try again."

<img width="604" alt="image" src="https://user-images.githubusercontent.com/423378/166304323-6a07c44e-3746-4b7b-abf7-f50f88257b0c.png">

### Expected behavior

Permissions are the one required by Amplify Github App so it should be enough to continue or get a clear error.

### Reproduction steps

1. Migrate from old amplify applications github integration to new Github App.
2. Provide permissions through OAuth
3. Blocked in step 1

**Comment by hloriana** [comment]
Hi @blanchma 👋🏽  I was able to reproduce this issue. This appears to only be happening for repositories owned by Github organizations. I've added this to our backlog for prioritization and syncing with the team for a possible workaround.

**Comment by aaaleee** [comment]
Hi @hloriana, I think I'm affected by this as well, is there a workaround?

**Comment by saksham1709** [comment]
I am suffering from this issue too! how to solve this? It was working perfectly a month back

**Comment by Erikmmkarlsson** [comment]
I also suffer from this.

**Comment by Jay2113** [comment]
Please try to revert your app back to the OAuth workflow by running the `update-app` CLI command: `aws amplify update-app --app-id <VALUE> --repository <VALUE> --access-token <VALUE>`

You can then try to trigger a new build or redeploy the previous one.

**Comment by blanchma** [comment]
What should this `access-token` comes from?

**Comment by Jay2113** [comment]
The `access-token` will be the PAT for your repo: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token.

**Comment by yiweixia** [comment]
I'm also running into this issue when trying to add a repository branch for the first time.

I can successfully list the repositories when going through the OAuth process to give amplify permissions, but back in the amplify console, none of the organization repos are showing up in the dropdown menu in the  "Add repository branch" screen. Personal repos show up fine.

@hloriana Any ETA on when this'll be fixed? Or is there a workaround for setting this up for the first time since I'm not migrating?

**Comment by Neel0108** [comment]
> Please try to revert your app back to the OAuth workflow by running the `update-app` CLI command: `aws amplify update-app --app-id <VALUE> --repository <VALUE> --access-token <VALUE>`
> 
> You can then try to trigger a new build or redeploy the previous one.

what is a repository value ?

**Comment by Ryan6795** [comment]
I was also running into this issue oddly enough whenever I had '-' in my repo name it would spring this error. Once I removed that symbol from my repo name it worked.

**Comment by jobypthomas** [comment]
Same issue. I had my repo has '-' in it as well.
