### ISSUE TITLE
I can't "Connect branch"

### ISSUE THREAD

**Issue by blanchma** [aws-amplify/amplify-hosting#2731]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-2:885048644588:apps/d3nswdh9hjl9sk

### Region

us-east-2

### Amplify Hosting feature

Backend builds, Build settings

### Describe the bug

I tried to connect my application to the source code in Github. I go to "Connect branch" and it says "GitHub authorization was successful." but when I click Next I got "Please select a repository before proceeding.". The problem is I don't have anything to choose.

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/423378/166304995-bb02bf0a-933a-4511-b9be-ea8d566c7153.png">

### Expected behavior

1. Go to application
2. Connect branch
3. Click next after choose a repository

### Reproduction steps

1. Go to application
2. Connect branch
3. Click next after and blocked with: "Unable to Proceed. Repository not selected."

**Comment by ii-igku** [comment]
same here

**Comment by hloriana** [comment]
Hi @blanchma 👋🏽  can you try going to General Settings and select "reconnect repository" to migrate to the GitHub app? Please let us know if this unblocks you.

**Comment by hloriana** [comment]
If you're still experiencing this issue, feel free to re-open.

**Comment by blanchma** [comment]
Still the same issue after "reconnect repository" 

<img width="691" alt="image" src="https://user-images.githubusercontent.com/423378/170601831-3bb3467f-3a62-47ef-b7d7-0851d212d720.png">

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/423378/170602112-13b89e77-8897-4cea-8a3e-421e9d459544.png">

**Comment by blanchma** [comment]
I solve this issue, updating the source repository through AWS CLI.

**Comment by alialfa** [comment]
@blanchma thank you, nice to know...

just managed to fix in by going to General > Branches > Action > Disconnect branch
seems mine was confused with a previous branch that I had deleted.

For anyone that lands on this issue, the page below is expected behaviour on migration:
![image](https://user-images.githubusercontent.com/46943057/173128040-21bc2675-4050-49ef-8eae-d0fe5afcb07f.png)
