### ISSUE TITLE
403 ERROR The request could not be satisfied.

### ISSUE THREAD

**Issue by yiurenma** [aws-amplify/amplify-hosting#2734]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-1:553056037772:apps/d3ivilocc7odni

### Region

us-east-1

### Step

Domain activation

### Status

Failed

### Issue or question

I have a domain where host in Aliyun Cloud:  scvip.com.cn  and I have added a CNAME (test.scvip.com.cn) which is pointed to https://main.d3ivilocc7odni.amplifyapp.com/ 

but test.scvip.com.cn request will throw below error 

`403 ERROR
The request could not be satisfied.
Bad request. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: aHAMGg8vaTYhyfAzD4uyxq2pDyVduYO-aM2rnI0yrP_D2FPev9Ytlg==`

**Comment by sumitsahoo** [comment]
DId it get resolved? I am also getting same error for a custom domain :(

**Comment by Jay2113** [comment]
Hi @yiurenma, apologies for the delayed response on this issue. It looks like you have already removed the domain association from your Amplify app `d3ivilocc7odni`. If issue persists, please feel free to reopen this issue.

@sumitsahoo Kindly create a new issue with all the requested information and we can then investigate into it further.
