### ISSUE TITLE
Logging into Amplify Studio issues

### ISSUE THREAD

**Issue by MichaelDAbrams** [aws-amplify/amplify-hosting#2736]
**Please describe which feature you have a question about?**
No longer able to log into Amplify Studio, no users listed anymore, just spinner and never loads

**Provide additional details**
Hi, so my team and I have run into an issue when we tried to add a new team member. It wont let anyone launch studio even when logged in through AWS. and it won't show any users at all in the studio settings. Not sure how we can get this fixed.

**What AWS Services are you utilizing?**
Amplify

**Provide additional details e.g. code snippets**
<img width="1792" alt="Screen Shot 2022-05-05 at 12 00 25 PM" src="https://user-images.githubusercontent.com/91335322/166964585-bcc9d5f8-7a91-4dc3-92ca-990e0d2fc126.png">
<img width="1792" alt="Screen Shot 2022-05-05 at 11 59 25 AM" src="https://user-images.githubusercontent.com/91335322/166964586-2205cfe3-6b84-4d1a-8dbc-ff6fa8511e5b.png">

**Comment by hloriana** [comment]
Hi @MichaelDAbrams 👋🏽 thanks for raising this issue. I'm not seeing this behavior when I navigate to Amplify studio settings. Can you try again and see if the issue persists while we investigate?

**Comment by MichaelDAbrams** [comment]
hi @hloriana the issue is still occuring, still unable to add users and unable to log in

**Comment by hloriana** [comment]
Hi @MichaelDAbrams we still aren't able to reproduce this on our end unfortunately so we will need some more information. 

1. Are there any error logs that appear in the browser console? If so, please provide screenshots.
2. Please provide an HAR capture; it may be able to tell us why the information isn't loading.
3. We can hop on a call to further investigate this issue. Please reach out to aws-amplify-customer@amazon.com with your availability and we will schedule a call.

For a workaround, you can try disabling and re-enabling Amplify studio. This won't affect your backend resources but it will remove any users you invited to access Amplify Studio.
