### ISSUE TITLE
Unable to activate domain - CNAMEAlreadyExistsException

### ISSUE THREAD

**Issue by IndusCreations** [aws-amplify/amplify-hosting#2737]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-1:013646252454:apps/d2zb6maoikeybh

### Region

us-east1

### Step

DomainActivation

### Status

FAiled

### Issue or question

I am unable to connect this instance to my domain.

### Error message

Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below.
Error message: [CNAMEAlreadyExistsException] The following CloudFront distributions are already using one or more of your domains: [Distribution: *******X99BO3M in AWS Account: ******200621, Distribution: *******X99BO3M in AWS Account: ******200621]. If you own these distributions, please remove the domains from them first and then retry adding your domain. If you don't own them, then you may already have associated this domain to another Amplify App in another account or region. You can also check our troubleshooting guide for more help: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html

### Additional information

..

**Comment by hloriana** [comment]
Hi @IndusCreations 👋🏽  please follow the guides we have in our FAQ to resolve this: https://github.com/aws-amplify/amplify-hosting/blob/main/FAQ.md#cnamealreadyexistsexception

**Comment by IndusCreations** [comment]
I do not see any duplicate app using this. I had my account suspended and reactivated few months ago - is it the case that thse are state entries from the previous app instance. I cannot seem to find where they are.

**Comment by IndusCreations** [comment]
Please help resolve this - all my domains are blocked 22yards.com, 22yards.com and ipltable.com!

**Comment by hloriana** [comment]
Can you please create a support case following this guide: https://docs.aws.amazon.com/awssupport/latest/user/case-management.html#creating-a-support-case. They will be able to help you associate your custom domain to your app.

**Comment by IndusCreations** [comment]
I checked there is no duplicate entry in any of my other distributions..:(



Thanks
Indus Creations Team
________________________________
