### ISSUE TITLE
Failed to pull the backend. "no such file or directory" in layer node_modules/.bin

### ISSUE THREAD

**Issue by CSHaze** [aws-amplify/amplify-hosting#2738]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d20sfr6tv47x3i

### Region

us-east-1

### Amplify Hosting feature

Backend builds

### Describe the bug

When trying to run a backend build, using amplify hosting, there is an error pulling the existing backend.

`/codebuild/output/src541213411/src/application/amplify/.temp/#current-cloud-backend/function/appsyncUpdateLayer/lib/nodejs/node_modules/.bin/loose-envify`

When trying to pull the backend the build tries to access a file inside the node_modules/.bin folder of a function layer in the current-cloud-backend. Local pushes work fine and when I look at the current-cloud-backend zip the file exists.

Builds on a fresh build environment work. I have tried not caching the node modules and it doesn't make a difference. I have also had trouble trying to push any updates to the layer, it does not recognize my changes.

### Expected behavior

I'd expect the build to be able to find files in the node_modules/.bin directory of my function layers.

### Reproduction steps

1. Create a lamda layer inside of an amplify project. Make sure the node_modules contain references such as "loose-envify" so that entries are created in node_modules/.bin
2. Push these changes so that a hosted build is started.
3. Observe the error.

### Build Settings

```yaml
Custom build image dockerfile

FROM ubuntu:latest

SHELL ["/bin/bash", "--login", "-c"]

 # Install apt packages
RUN apt update         && \
    apt install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt update         && \
    apt upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"  && \
    apt install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"     \
        unzip                   \
        curl                    \
        git-all                 \
        openssh-server          \
        ufw                     \
        python3.8            && \
    apt install -y python3-pip && \   
    apt-get clean

# Install Venv
# COPY Pipfile Pipfile.lock
RUN pip3 install pipenv

# Install nodejs and npm
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && \
 apt install -y nodejs

# Install aws cli
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
unzip awscliv2.zip && \
./aws/install

# Install global NPM packages
RUN npm install -g @ionic/cli
```
```


### Additional information

_No response_

**Comment by CSHaze** [comment]
I think I solved this using `amplify push --force` it seemed to get things back in sync. Am I misunderstanding the design?  Is this intended?

**Comment by CSHaze** [comment]
Nevermind, I am still seeing this issue pop up. I am trying to figure out a reliable workaround. It is failing all my backend builds.

**Comment by hloriana** [comment]
Hi @CSHaze apologies for the delay. We are taking a look at this issue.

**Comment by CSHaze** [comment]
I'm starting to think this may come from running an `amplify push` from my local machine without forcing a layer update.

**Comment by hloriana** [comment]
Closing since there is a workaround.
