### ISSUE TITLE
How to make 200 redirect ONLY when there is no file

### ISSUE THREAD

**Issue by AlexandreFauchard** [aws-amplify/amplify-hosting#2739]
**Please describe which feature you have a question about?**
Redirects and rewrites

**Provide additional details**
Hello,

I have a problem with the 200 rewrites.
Imagine I have a pre-generated news website with Gatsby.
I have some generated html files with the path `/news/xxx` and some news non-generated with the same path. 

To handle non-generated news I have a static file `/loader/news` which make all api request to display the news as a pre-generated one. Obviously, to handle it, I've add a 200 rewrite like that : 
```
{
  "source": "/news/<*>",
  "target": "/loader/news",
  "status": "200",
  "condition": null
}
```

But my pre-generated news are also rewrited to `/loader/news`.

If I change the status to `404-200` it work well but the status code one non-regenerated are 404 which is wrong... 
How can I make the 200 status code work only if the requested file is not found ? 

**What AWS Services are you utilizing?**
Amplify

**Comment by hloriana** [comment]
Hi @AlexandreFauchard apologies for the delay. We are investigating if this is currently possible. We will update you shortly.

**Comment by hloriana** [comment]
It's currently not possible to make a redirect rule conditional in this way. If you had a specific path for the non-generated pages like `/news/xxx/xxx` then you would be able to leverage the [Order of Redirects](https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#order-of-redirects) and have that rule honored first. The pre-generated pages at `news/xxx` would then be redirected using the rule you already have.
