### ISSUE TITLE
Unable to create user to log in to Amplify Studio ?

### ISSUE THREAD

**Issue by ahlag** [aws-amplify/amplify-hosting#2742]
**Please describe which feature you have a question about?**

Amplify Studio

When I try to pull my backend via cli like this:
I'm presented with the Amplify Studio login in a browser.
I've tried using giving myself `AdministratorAccess-Amplify` but I still couldn't login. I have also tried inviting myself with my gmail account but I wasn't able to create the user.

**Provide additional details**

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**

So, how do I log in to Amplify Studio ?

**Comment by hloriana** [comment]
HI @ahlag can you try creating a user via the Amplify Console? Please follow this guide: https://docs.amplify.aws/console/adminui/access-management/

**Comment by ahlag** [comment]
@hloriana 
Thank you for the follow up!

**Comment by hloriana** [comment]
@ahlag please let us know if you're still blocked. Thank you!

**Comment by tkhmy** [comment]
@hloriana 
Hi, I also have this problem, I follow the instruction https://docs.amplify.aws/console/adminui/access-management/#to-invite-team-members-to-access-a-project to send the invitation to another email, but the another member do not receive any invitation email.
![image](https://user-images.githubusercontent.com/41041286/168426080-1ce16b6f-e655-450e-8b61-3b11e0f41990.png)

Do we need to create an IAM user and then only add it into the amplify studio?

**Comment by ahlag** [comment]
@hloriana 
I have fixed it on the UI. Thank you!

**Comment by R-Art-project** [comment]
Thank @hloriana this solve my problem
