### ISSUE TITLE
Amplify cannot oauth gitlab

### ISSUE THREAD

**Issue by OlgaMaslova** [aws-amplify/amplify-hosting#2750]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2pn15o81elpww

### Region

eu-west-1

### Amplify Hosting feature

Access control

### Describe the bug

Cannot reconnect to the gitlab repository (neither connect a new branch). Error on redirecting to gitlab repository:
"The authorization server does not support this response type."

### Expected behavior

Oauth to Gitlab works.

### Reproduction steps

In Amplify console click "Connect branch".

### Additional information

![image](https://user-images.githubusercontent.com/29795366/168094986-ba26e654-8b92-45d1-8798-90bc3173118f.png)

**Comment by TimTimT** [comment]
Same problem since about 12 hours ago. Unable to make any new deployments using Gitlab.

**Comment by hloriana** [comment]
Hi @OlgaMaslova @TimTimT 👋🏽  We're investigating connectivity issues for customers trying to create new applications with GitLab. We will update once we have more information.

**Comment by hloriana** [comment]
The fix for this bug has been pushed so you should be able to connect to your GitLab repositories now. Thank you!
