### ISSUE TITLE
Rewrite all URLs ending in .php to .html

### ISSUE THREAD

**Issue by cmeyer** [aws-amplify/amplify-hosting#2753]
**Please describe which feature you have a question about?**
Rewriting rules

**Provide additional details**
My files exist in a subfolder. And I would like URLs of the form:

`/x/abc.php`

to be redirected (200) to the file:

`/x/abc.html`

**What AWS Services are you utilizing?**
AWS Amplify

**Provide additional details e.g. code snippets**

I would expect this to work:
```
[
    {
        "source": "/<*>.php",
        "target": "/<*>.html",
        "status": "200",
        "condition": null
    }
]
```

Is this possible?

**Comment by cmeyer** [comment]
@hloriana I see you self assigned this. Is this something that is expected to work?

Even documentation explaining how redirects are supposed to work would be useful. For instance, when are regexp's used vs substitutions like <*> or <date> used? Also, what is the syntax of regexp's in this implementation?

**Comment by hloriana** [comment]
Hi @cmeyer 👋🏽 apologies for the delay. I was able to get this scenario working for my app. In this case, I'm redirecting all html files under pages to png image files with the same name. Here is my example rule: 
![Screen Shot 2022-07-07 at 6 52 46 PM](https://user-images.githubusercontent.com/76065904/177890058-d4e8a515-4b25-43d4-b7b3-b944a9c284ba.png)

So if I visit `/pages/about.html` it will redirect to `/images/about.png`. Please let us know if this works for you.

Also, thank you for your feedback on our redirects documentation. I have added this to our product backlog for us to update our documentation regarding regular expressions.

**Comment by hloriana** [comment]
Please re-open if this solution did not work for you. Thank you!

**Comment by cmeyer** [comment]
@hloriana Your solution doesn't address the issue I filed. Your solution redirects FROM HTML to PNG. I was asking to redirect PHP to TO HTML (note: PHP, NOT PNG).

**Comment by hloriana** [comment]
@cmeyer My example shows that you can redirect from one file extension to another file extension. Were you able to test this out with your application to ensure that it works for you?
