### ISSUE TITLE
An error occurred during the publish operation: Branch dev not found.

### ISSUE THREAD

**Issue by M-Harty21** [aws-amplify/amplify-hosting#2755]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-1:530803797840:apps/d2vexy11uhscqy

### Region

us-east-1

### Amplify Hosting feature

Backend builds, Manual deploys

### Describe the bug

? Do you still want to publish the frontend? Yes
Publish started for amplifyhosting

> rabbithole@0.0.0 build
> ng build

✔ Browser application bundle generation complete.
✔ Copying assets complete.
⠋ Generating index html...1 rules skipped due to selector errors:
  .amplify-stepperfield__input:not(,[aria-invalid=true]) -> Empty sub-selector
✔ Index html generation complete.

Initial Chunk Files           | Names         |  Raw Size | Estimated Transfer Size
main.53d530c6d5e1dbab.js      | main          |   1.17 MB |               259.52 kB
styles.45afbab00ac0e52c.css   | styles        | 217.01 kB |                19.99 kB
polyfills.631c0c2fdc56a7bd.js | polyfills     |  33.08 kB |                10.64 kB
runtime.a5b2e8f427cb6080.js   | runtime       |   1.30 kB |               695 bytes

                              | Initial Total |   1.42 MB |               290.83 kB

Build at: 2022-05-17T16:25:49.919Z - Hash: ea86490da29a9252 - Time: 50154ms

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-amplify\analytics\lib-esm\Providers\AWSPinpointProvider.js depends on 'uuid'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-amplify\analytics\lib-esm\Providers\AmazonPersonalizeProvider.js depends on 'lodash/get'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-amplify\analytics\lib-esm\Providers\AmazonPersonalizeProvider.js depends on 'lodash/isEmpty'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-amplify\analytics\lib-esm\Providers\AmazonPersonalizeProvider.js depends on 'lodash/isEqual'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-amplify\auth\lib-esm\Auth.js depends on 'url'. CommonJS or AMD dependencies can cause optimization bailouts.       
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-amplify\core\lib-esm\Signer.js depends on '@aws-crypto/sha256-js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-amplify\datastore\lib-esm\datastore\datastore.js depends on 'uuid'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-amplify\datastore\lib-esm\util.js depends on 'buffer'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-amplify\datastore\lib-esm\util.js depends on 'ulid'. CommonJS or AMD dependencies can cause optimization bailouts. 
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-amplify\geo\lib-esm\Providers\AmazonLocationServiceProvider.js depends on 'camelcase-keys'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-amplify\pubsub\lib-esm\Providers\AWSAppSyncRealTimeProvider\index.js depends on 'uuid'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-amplify\ui-angular\__ivy_ngcc__\fesm2015\aws-amplify-ui-angular.js depends on 'qrcode'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-amplify\ui\dist\esm\helpers\authenticator\context.js depends on 'lodash/includes'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-amplify\ui\dist\esm\helpers\authenticator\formFields\defaults.js depends on 'lodash/cloneDeep'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-amplify\ui\dist\esm\machines\authenticator\index.js depends on 'xstate/lib/actions'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-amplify\ui\dist\esm\theme\createTheme.js depends on 'style-dictionary/lib/utils/deepExtend'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-amplify\ui\dist\esm\theme\createTheme.js depends on 'style-dictionary/lib/utils/flattenProperties'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-sdk\client-cognito-identity\dist\es\runtimeConfig.browser.js depends on '@aws-crypto/sha256-browser'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-sdk\client-comprehend\dist\es\protocols\Aws_json1_1.js depends on 'uuid'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-sdk\client-location\dist-es\runtimeConfig.browser.js depends on '@aws-crypto/sha256-browser'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-sdk\client-s3\dist\es\protocols\Aws_restXml.js depends on 'fast-xml-parser'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-sdk\client-translate\dist\es\protocols\Aws_json1_1.js depends on 'uuid'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-sdk\eventstream-marshaller\dist\es\EventStreamMarshaller.js depends on '@aws-crypto/crc32'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\@aws-sdk\middleware-retry\dist\es\defaultStrategy.js depends on 'uuid'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\amazon-cognito-identity-js\es\AuthenticationHelper.js depends on 'buffer'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\amazon-cognito-identity-js\es\AuthenticationHelper.js depends on 'crypto-js/core'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\amazon-cognito-identity-js\es\AuthenticationHelper.js depends on 'crypto-js/hmac-sha256'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\amazon-cognito-identity-js\es\AuthenticationHelper.js depends on 'crypto-js/lib-typedarrays'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\matth\Desktop\Varsity\IMY 772\rabbithole-aws-serverless\rabbithole\node_modules\amazon-cognito-identity-js\es\Client.js depends on 'isomorphic-unfetch'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

√ Zipping artifacts completed.
× Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
An error occurred during the publish operation: Branch dev not found.

Been trying now for ages to fix this bug but don't know what could be the issue here

### Expected behavior

Successfully deploy my app to Amplify, manually through the CLI

### Reproduction steps

amplify publish

### Build Settings

```yaml
version: 1
applications:
  - appRoot: rabbithole
    # backend:
    #   phases:
    #     build:
    #       commands:
    #         - '# Backend Deploying : for now we do not need auto deployment for backend (Except when we add testing)'
    #         - amplifyPush --simple
    frontend:
      phases:
        preBuild:
          commands:
            - npm ci
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: dist/rabbithole
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
```

**Comment by hloriana** [comment]
Hi @M-Harty21 👋🏽  thanks for raising this issue. It'd be helpful if we can look at the logs for this failed deployment to further investigate but it appears this app has been deleted. Is there a different app where you're running into this issue? If so, try running `aws amplify list-branches --app-id <value>` to make sure the `dev` branch exists. I was not able to reproduce this behavior.

**Comment by M-Harty21** [comment]
Hi there, had to reinitialize the app, but did it through the Amplify Studio/Console instead of the CLI. There is something really buggy about using the Amplify CLI... had no idea what could've been the actual issue.

**Comment by M-Harty21** [comment]
My educated guess after hours and hours of trying to figure this stuff out is that: when done through the CLI it creates a "dev" backend environment that is linked to the frontend. When using the Amplify Console/Studios it seems to instead create a environment called "staging", when deploying to the CI/CD it seems to work with the staging environment then the dev environment... As I said my experience so far with the Amplify CLI is and has been very inconsistent. Hope this helps bug fixes
