### ISSUE TITLE
Custom domain status is available but 404 error occurs

### ISSUE THREAD

**Issue by yukinakanaka** [aws-amplify/amplify-hosting#2757]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3kvv0tz27aniv

### Region

ap-northeast-1

### Step

Complited

### Status

Available

### Issue or question

404 ERROR occurs with custom domain. How can I fix this?
![image](https://user-images.githubusercontent.com/8342501/168937331-43675247-e950-4dc3-90e4-5d5966400fee.png)

### Error message

HTTP ERROR 404

### Additional information

•  custom domain is available
![image](https://user-images.githubusercontent.com/8342501/168937184-dba9d96a-8772-4366-b92f-2a040cb0a164.png)

• At Route53 CNAME Record has been created automatically
![image](https://user-images.githubusercontent.com/8342501/168937683-befdb2a9-9991-4292-a464-3b510eb990b5.png)

• CNAME resolves correctly 
![image](https://user-images.githubusercontent.com/8342501/168937826-37a88be2-67aa-4ba4-a73a-bcd07dd3123e.png)

**Comment by yukinakanaka** [comment]
Please anyone help me! 😭

**Comment by hloriana** [comment]
Hi @yukinakanaka 👋🏽  I'm able to load your website when I navigate to the subdomain you associated with your staging branch so I'm not seeing the 404 issues. What url are you having difficulties accessing?

**Comment by hloriana** [comment]
Awesome, glad to see you're unblocked! I'll bring the extended delay to the team's attention.
