### ISSUE TITLE
Create domain association failed

### ISSUE THREAD

**Issue by rubanzasilva** [aws-amplify/amplify-hosting#2766]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

North Virginia

### Region

us-east-1

### Step

Adding domain

### Status

Failed

### Issue or question

I tried to connect my amplify app to a custom domain but when I try to add the subdomains I get the error below deposit the fact that I have no other app deployed to that domain

### Error message

Create domain association failed
One or more domains requested are already associated with another Amplify app: zicofe.com, www.zicofe.com

### Additional information

![Uploading D954BCD4-B037-46A6-B171-8FC6FCF72E82.png…]()

**Comment by hloriana** [comment]
Hi @rubanzasilva 👋🏽 Can you share your app ID? We can double check to make sure the domain is not associated to another app within your account. If it is in fact associated with another account, please open a case with [AWS Support](https://us-east-1.console.aws.amazon.com/support/home?region=us-east-1#/). They will be able to further assist you.

**Comment by rubanzasilva** [comment]
The issue was well resolved with the help of AWS customer support, the issue was because I had my account suspended the resources already assigned to the domain were taking a while to appear in amplify console but were actually there, just not showing up.

After a while the application showed up in AWS amplify console, issue was resolved.
