### ISSUE TITLE
Amplify Hosting {"code":"7","message":"No ssrResources.json file"}

### ISSUE THREAD

**Issue by rei-shaholli** [aws-amplify/amplify-hosting#2768]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-east-1

### Describe the bug

Hello, I have a Next.js app that we are hosting via amplify.  

We are trying to deploy the next.js app as an SSG (Next.js - SSG) and we followed the guidelines outlined in the following docs:  

[https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app ](https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app).

From the article above ^ we did the following to our package.json for the amplify build to recognize our app as a Next.js SSG:
...
  "scripts": {
    "dev": "next dev",
    "build": "next build && next export",
    "start": "next start"
},
...

we, furthermore, set the base directory to "out" in the amplify.yml as such:
...
  artifacts:
    baseDirectory: out
...

And although the build phase seemingly  creates the SSG components the  deploy phase FAILS with the following

2022-05-26T16:38:09 [INFO]: Cannot find any generated SSR resources to deploy. If you intend for your app to be SSR, please check your app Service Role permissions. Otherwise, please check out our docs on how to set up your app to be detected as SSG ([https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app ](https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app))
2022-05-26T16:38:09 [ERROR]: {"code":"7","message":"No ssrResources.json file"}

### Expected behavior

The next.js app is deployed successfully.

### Reproduction steps

1. Run the build
2. Notice that the deploy fails

### Build Settings

```yaml
frontend:
  phases:
    preBuild:
      commands:
        - yarn install --frozen-lockfile
    build:
      commands:
        - echo 'running build'
        - yarn build
  artifacts:
    baseDirectory: out
    files:
      - '**/*'
```

### Additional information

package.json scripts;

  "scripts": {
    "dev": "next dev",
    **"build": "next build && next export",**
    "start": "next start",
}

**Comment by hloriana** [comment]
Hi @rei-shaholli 👋🏽 It looks like you made the proper adjustments for an SSG app. can you provide your app ID so we can further investigate?

**Comment by rei-shaholli** [comment]
Hi @hloriana I actually got the deployment to build by running:

aws amplify update-app --app-id <APP_ID> --platform WEB --region <REGION>

I had previously run this command and deployments were working fine, but I noticed that the app had gone back to being WEB_DYNAMIC (by itself?), so I re-run that command and now everything is working fine.  Just fyi!

Thanks for the response!
Rei
