### ISSUE TITLE
An error occurred while fetching the app backend: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1

### ISSUE THREAD

**Issue by AIV-GH** [aws-amplify/amplify-hosting#2770]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

https://main.d30u9bk4i5ytt1.amplifyapp.com 

### Region

US West (Oregon) us-west-2

### Step

Domain activation

### Status

Failed

### Issue or question

Domain Name - aitensors.org,  Company Name  - AITensors corp.
After the deployment of code in githube ,after a long time it was showing Domain activation is failed 

### Error message

[AmplifyWaitTimeout] The domain association has failed because we did not find the CNAME verification record on the DNS entries of your domain. Please check our troubleshooting guide for help: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html

### Additional information

An error occurred while fetching the app backend: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1

**Comment by skylus** [comment]
I had this issue too, resolved it when I realized I used subdomain.mydomain.com (different hosted zone) rather than choosing mydomain.com and excluding root & adding a subdomain. (it seemed as though I have to add hosted zone for amplify custom domain with subdomain but it's not true)
