### ISSUE TITLE
Can't resolve 'pg-native'

### ISSUE THREAD

**Issue by newilu** [aws-amplify/amplify-hosting#2771]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d61j5m72chkto

### Region

eu-west-1

### Describe the bug

About 4 days ago just faced this issue when trying to build my project:

ModuleNotFoundError: Module not found: Error: Can't resolve 'pg-native' in '/codebuild/output/src089491803/src/effectorecommerce/node_modules/pg/lib/native'
                                  > Build error occurred
                                  Error: > Build failed because of webpack errors
                                  at /codebuild/output/src089491803/src/effectorecommerce/node_modules/next/dist/build/index.js:397:19
                                  at async Span.traceAsyncFn (/codebuild/output/src089491803/src/effectorecommerce/node_modules/next/dist/telemetry/trace/trace.js:60:20)
                                  at async Object.build [as default] (/codebuild/output/src089491803/src/effectorecommerce/node_modules/next/dist/build/index.js:77:25)
                                  
                                  
Absolutely NOTHING was changed in package json or in lock file. I dont even know what is pg-native because i never used it before in my life.

### Expected behavior

Expected that BUILDS WILL WORK WITHOUT SURPRISES LIKE THIS

### Reproduction steps

idk what to say here. got to my account and try to build? here is the logs
[log (33).txt](https://github.com/aws-amplify/amplify-hosting/files/8786580/log.33.txt)

### Additional information

locally all works fine and builds perfectly without any issues

**Comment by hloriana** [comment]
Hi @newilu 👋🏽 try setting this environment variable in the console and see if this unblocks you:
 set `AMPLIFY_NEXTJS_EXPERIMENTAL_TRACE` to equal `true`

Doc for reference: https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html

**Comment by newilu** [comment]
thanks a lot! that worked for me
