### ISSUE TITLE
There's a javascript error in the AWS Amplify console

### ISSUE THREAD

**Issue by mxswd** [aws-amplify/amplify-hosting#2777]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

none

### Region

ap-southeast-2

### Amplify Hosting feature

Not applicable

### Describe the bug

I can't access the console at all because you have a javascript error in your web page.

<img width="1316" alt="Screen Shot 2022-05-31 at 6 45 40 PM" src="https://user-images.githubusercontent.com/136101/171109468-c01ba6c5-c819-499c-ae08-a04f5e4d0f9d.png">

### Expected behavior

Open the AWS Amplify console by navigating to https://ap-southeast-1.console.aws.amazon.com/amplify/home?region=ap-southeast-2

### Reproduction steps

Open https://ap-southeast-1.console.aws.amazon.com/amplify/home?region=ap-southeast-2

**Comment by hloriana** [comment]
Hi @mxswd 👋🏽  thanks for raising this issue. Can you try clearing your cache and refreshing the page?

**Comment by mxswd** [comment]
@hloriana Hello, thanks for the quick response. I tried Empty Caches, private browsing and Edge on Windows and the problem still occurs. I can't access the Amplify console in the ap-southeast-2 region anymore. ap-southeast-1 works fine.

**Comment by DavidRalph** [comment]
Same issuehere , seeing the error: `this.props.preferences is undefined` when trying to view Amplify console in `us-east-2` and the page does not load. 

Other regions work fine, `us-east-2` is the only one not working and is also the only region I have an existing app in.

**Comment by hloriana** [comment]
I'm syncing with the team to further investigate. @DavidRalph can you provide a screenshot of the error as well?

**Comment by saadataz** [comment]
can you please also share the content of the preferences key in your browser's local storage to help with debugging.
You can run the following in chrome dev tools while Amplify console is open.
```js
localStorage.getItem("preferences")
```

**Comment by mxswd** [comment]
> @mxswd @DavidRalph I previously suggested clearing the cache but can you try clearing the local storage as well? You can do that by navigating to developer tools -> applications -> storage -> local storage.

Thanks I think that fixed it! 

This was my local storage preferences before I deleted them:

```
"{\"releaseFlashBarDismissed\":{\"2_0_5\":true},\"clusterList\":{\"pageSize\":10,\"custom\":\"cards\"},\"capacityProvidersTable\":{\"pageSize\":5,\"visibleContent\":[\"name\",\"type\",\"asgData\",\"managedScaling\",\"managedInstanceProtection\",\"currentSize\",\"desiredSize\",\"minSize\",\"maxSize\",\"updateStatus\"]}}"
```

**Comment by DavidRalph** [comment]
Thanks, clearing local storage fixed it for me also.

Here are the preferences and a screenshot of the issue prior to clearing local storage:
```
"{\"releaseFlashBarDismissed\":{\"2_0_5\":true},\"taskLogs\":{\"custom\":\"ABSOLUTE_LOCAL\"},\"serviceEvents\":{\"pageSize\":10,\"custom\":\"ABSOLUTE_LOCAL\"},\"serviceLogs\":{\"custom\":\"ABSOLUTE_LOCAL\"}}" 
```
![amplify](https://user-images.githubusercontent.com/1348290/172172364-6860deb2-a454-4e70-b23e-64811a2a7e71.png)
