### ISSUE TITLE
Not able to delete Amplify App 

### ISSUE THREAD

**Issue by yogesh432kumar** [aws-amplify/amplify-hosting#2780]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-west-1

### Amplify Hosting feature

Access control, Backend builds, Manual deploys

### Describe the bug

Can not delete the app. No backend or frontend attached. Created with CLI but do not have project locally anymore. App is just hanging in AWS/Console creating problems for attaching domain to new app.

Can you please help delete the old app that's just hanging. Not able to use CLI for it anymore.

### Expected behavior

deleted

### Reproduction steps

select app in Amplify console. try to delete

### Build Settings

```yaml
n/a
```

### Additional information

n.a

**Comment by hloriana** [comment]
Hi @yogesh432kumar please run this AWS CLI command to delete the application:
`aws amplify delete-backend-environment --app-id <value> --environment-name <value>`. 

This will delete all backend resources. You can then remove the hosting environment from the console.
