### ISSUE TITLE
How do I configure this routing situation? [Angular routing]

### ISSUE THREAD

**Issue by Jun711** [aws-amplify/amplify-hosting#2781]
I have deployed my mono repo using Amplify. Most parts work but there is some issue with routing.
I have a mono repo that has multiple folders and one of the folder contains an angular app.

The angular app is inside `sso` folder and it has paths like `login`, `signup` etc managed by Angular app router
When I go to `www.test.com/sso`, the angular app redirects correctly to `www.test.com/sso/login` but when I refresh on that page, it will look for `sso/login` in my mono repo which doesn't exist. 

How do I set up so that it doesn't do that use Angular routing where appropriate?

**Comment by hloriana** [comment]
Hi @Jun711 can you provide reproduction steps or a sample repo for us to reproduce this issue?
