### ISSUE TITLE
WebGl - react app working on local but doesn't load data when hosted

### ISSUE THREAD

**Issue by njainupwork** [aws-amplify/amplify-hosting#2791]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

hong-kong

### Amplify Hosting feature

Performance

### Describe the bug

I have deployed a react app with unity game support (WebGl) on aws and the game data is not loading as it is supposed to be . I tried to deploy on other platform such as vercel and it working absolutely fine there. 

the file with extension ".data" and ".wasm" doesn't seem to load .

Checked in network tap (developer tools) it shows status code 304 but the file is not
even loaded once.

.data and .wasm file is not even build properly 

### Expected behavior

It is suppose to load the whole unity game 

### Reproduction steps

I tried deploying app to amplify but it doesn't work even though it was working fine on my local . Then checked which file is loaded and which are not .

Checked network tab to find out that .data file is not even loaded

**Comment by tfabes** [comment]
Any luck with this? Been having a similar issue!

**Comment by njainupwork** [comment]
Please follow this steps , to get it resolved

01:57:50 PM Daniel S: In the Amplify Console, if you go to redirects
01:58:13 PM Daniel S: there is a redirect rule that is a regular expression with file extensions.
01:58:40 PM Daniel S: you need to add your .data and .wasm file extensions to that list.
01:59:07 PM Daniel S: so change
01:59:17 PM Daniel S:  </^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json|gltf|mp3|tsx|obj|fbx|jpeg)$)([^.]+$)/>
01:59:20 PM Daniel S: to
01:59:43 PM Daniel S:  </^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json|gltf|mp3|tsx|obj|fbx|jpeg|data|wasm)$)([^.]+$)/>
