### ISSUE TITLE
Amplify Console Reports wrong metrics

### ISSUE THREAD

**Issue by ARKKYN** [aws-amplify/amplify-hosting#2793]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d31h6o5dbwaoj9

### Region

ap-south-1

### Amplify Hosting feature

Not applicable

### Describe the bug

The No of requests Shown in Amplify metrics is Incorrect for this app. Since I also log it in to google analytics as well. The Difference in the no of requests is huge. PFA screenshot of no of requests.

![Screenshot 2022-06-06 at 6 40 39 PM](https://user-images.githubusercontent.com/10711160/172167646-4bebf66f-373c-421d-aeec-a26b749e788d.png)

### Expected behavior

The no of requests should be less than 1000 per month maximum.

### Reproduction steps

You can check the metrics in the app.

### Build Settings

```yaml
None
```

**Comment by Jay2113** [comment]
Hi @ARKKYN 👋 , thanks for reaching out to us and we apologize for the delayed response on this thread.

It looks like you have deleted the Amplify app `d31h6o5dbwaoj9` and thus we won't be able to review the metrics for it from our end. 

I am going to close this thread but please feel free to reopen a new GitHub issue using our [bug template](https://github.com/aws-amplify/amplify-hosting/issues/new?assignees=&labels=bug%2Cpending-triage&projects=&template=1.bug_report.yaml) if you are still experiencing a mismatch in metrics between the number of requests in Amplify and Google Analytics.

Thank you!
