### ISSUE TITLE
List apps call failed: network timeout - Cannot see my apps on new machine

### ISSUE THREAD

**Issue by smilburn1990** [aws-amplify/amplify-hosting#2796]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2ntbxsw7r6p14

### Region

eu-west-2

### Amplify Hosting feature

Access control

### Describe the bug

When is go onto Amplify on my new machine it doesn't display any apps and says there is a network failure. I have installed the CLI on my new computer and configured it to a new IAM role but when I try to pull the project there is an error that says "cli.json" does not exist.

### Expected behavior

Display my apps on my account no matter the machine

### Reproduction steps

Log into AWS account
Go to Amplify
See there are no available apps and the error above is shown

### Build Settings

version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install --ignore-engines
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: /dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

### Additional information

There is no backend on this application
There seems to be other parts of AWS giving me a similar error even though I have updated my IAM

**Comment by hloriana** [comment]
Hi @smilburn1990 👋🏽 are you still running into this behavior? Can you try different browsers to see if this same error displays?

**Comment by Jay2113** [comment]
Hi @smilburn1990, if the issue persists can you provide us a HAR file of the issue as it contains the API requests that lead to these console errors. You can refer to this article to learn more about how to generate a HAR file: https://aws.amazon.com/premiumsupport/knowledge-center/support-case-browser-har-file/
