### ISSUE TITLE
CloudFront-Is-Desktop-Viewer always set true, even if I use mobile

### ISSUE THREAD

**Issue by xiaoxiaosaohuo** [aws-amplify/amplify-hosting#2800]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify Hosting feature

Custom headers

### Describe the bug

I use Nextjs SSR, I want to get the user agent in getServerSideProps, however, can not get it, I found there some headers like : CloudFront-Is-Desktop-Viewer, it's always set true, even if I use a mobile device.

### Expected behavior

can detect real device type

### Reproduction steps

1. using getServerSideProps
2. print the header
3. deploy it

**Comment by hloriana** [comment]
Hi @xiaoxiaosaohuo 👋🏽 thank you for raising this. We have added it to our product backlog for prioritization.

**Comment by mauerbac** [comment]
This feature has just been supported with our latest launch! Closing.

Check out the details here: https://aws.amazon.com/blogs/mobile/cdn-caching-improvements-for-better-app-performance-with-aws-amplify-hosting/
