### ISSUE TITLE
The Amplify UI does crash  

### ISSUE THREAD

**Issue by falcon027** [aws-amplify/amplify-hosting#2809]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

eu-central-1

### Amplify Hosting feature

Not applicable

### Describe the bug

The complete Amplify UI does crash if I try to open it. It seems to be caused by this error: 
Uncaught TypeError: Cannot read properties of undefined (reading 'githubToken') 
at F.render (main.js:formatted:53018:44) 
at zo (vendors~main.js:59:71428) 
at Uo (vendors~main.js:59:71227) 
at zs (vendors~main.js:59:112369) 
at ku (vendors~main.js:59:98325) 
at Cu (vendors~main.js:59:98253) 
at Su (vendors~main.js:59:98116) 
at du (vendors~main.js:59:95103) 
at vendors~main.js:59:44772 
at t.unstable_runWithPriority (vendors~main.js:67:3768)

### Expected behavior

I expended the UI to let me view all my project’s

### Reproduction steps

1. Open the AWS Amplify console 
2. The page remains empty

**Comment by hloriana** [comment]
Hi @falcon027 👋🏽 thanks for opening this issue. Can you try clearing out the local storage in your browser and refresh the page?

**Comment by falcon027** [comment]
Hi @hloriana  thanks for your quick response after cleaning the browser cache, it works.
