### ISSUE TITLE
There was an issue connecting to your repo provider, click "Reconnect repository" in General Settings, and then try your build again.

### ISSUE THREAD

**Issue by rkbnair7** [aws-amplify/amplify-hosting#2816]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-1:775963498893:apps/d10lo44ao9d0ii

### Amplify Hosting feature

Build settings

### Describe the bug

Tried building the application a larger number of times today. Every time getting the following error:
There was an issue connecting to your repo provider, click "Reconnect repository" in General Settings, and then try your build again.

### Expected behavior

application to be built successfully

### Reproduction steps

Build again

### Build Settings

```yaml
Source repository
https://us-east-1.console.aws.amazon.com/codesuite/codecommit/repositories/theme-park-frontend/browse/refs/heads/master?region=us-east-1 

Production branch URL
https://main.d10lo44ao9d0ii.amplifyapp.com 

App ARN
arn:aws:amplify:us-east-1:775963498893:apps/d10lo44ao9d0ii

Service role
arn:aws:iam::775963498893:role/service-role/AWSAmplifyCodeCommitExecutionRole-d1i9x4ergd03vs
```

### Additional information

Trying to build theme-park app

**Comment by rkbnair7** [comment]
Hello, any suggestions please?

**Comment by hloriana** [comment]
Can you confirm that the service-role in use has access to CodeCommit? Which permissions did you attach to the role?

**Comment by rkbnair7** [comment]
Hello Sir, how do I find service-role in use? Please suggest.

**Comment by Jay2113** [comment]
This is the IAM service role `AWSAmplifyCodeCommitExecutionRole-d1i9x4ergd03vs` attached to your Amplify app `d10lo44ao9d0ii`. Kindly review the permission policy attached to it and ensure that it has read-only access to your codecommit repository `theme-park-frontend`.

You can also consider creating a new app and use this workflow where the service creates an IAM role with read-only access to your codecommit repository:
![Screen Shot 2022-07-04 at 11 45 50 PM](https://user-images.githubusercontent.com/38470430/177267352-c9a0a334-868f-45ef-a766-7dfca73d5fca.png)
