### ISSUE TITLE
New Hello World SSG Gives `<Code>AccessDenied</Code>` Error

### ISSUE THREAD

**Issue by jd-carroll** [aws-amplify/amplify-hosting#2818]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d29c09egvjdkj0

### Region

us-west-2

### Amplify Hosting feature

Not applicable

### Describe the bug

Created a new simple NextJS app to test the static deployment.  Updated the build command to be:
```
    "build": "next build && next export",
```

When running `amplify init` made sure to edit the config so that the `DistributionDir` was `out` instead of `.next`:
```
{
  "projectName": "my-app",
  "version": "3.1",
  "frontend": "javascript",
  "javascript": {
    "framework": "react",
    "config": {
      "SourceDir": "src",
      "DistributionDir": "out",
      "BuildCommand": "npm run-script build",
      "StartCommand": "npm run-script start"
    }
  },
  "providers": [
    "awscloudformation"
  ]
}
```

When you open the link, instead of getting to the page I receive an error:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>MBH2KDW47MRX7FAF</RequestId>
<HostId>pEqBoQ+Px246OeVf7FP3ptUw+a22Qi+IhZLvPcPVUXiyJaKMXO8ukIFuTlj7ijed7Qy+Y94zSaE=</HostId>
</Error>
```
Which looks like some kind of S3 error.

### Expected behavior

When deployed you would be able to see the app.

### Reproduction steps

1. Create new SSG capable app
2. Run amplify init with the following config:
```
? Initialize the project with the above configuration? No
? Enter a name for the environment dev
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using react
? Source Directory Path:  src
? Distribution Directory Path: out
? Build Command:  npm run-script build
? Start Command: npm run-script start
```
3. Run amplify hosting with the following config:
```
$ amplify add hosting
✔ Select the plugin module to execute · Hosting with Amplify Console (Managed hosting with custom domains, Continuous deployment)
? Choose a type Continuous deployment (Git-based deployments)
? Continuous deployment is configured in the Amplify Console. Please hit enter once you connect your repository 
Amplify hosting urls: 
┌──────────────┬──────────────────────────────────────────────┐
│ FrontEnd Env │ Domain                                       │
├──────────────┼──────────────────────────────────────────────┤
│ master       │ https://...                                  │
└──────────────┴──────────────────────────────────────────────┘
```
4. Deploy the app

**Comment by hloriana** [comment]
Hi @jd-carroll 👋🏽 can you make sure the `baseDirectory` is set to `out` in your build settings?

**Comment by Jay2113** [comment]
It looks like you have deleted your Amplify app `d29c09egvjdkj0`. Please feel free to reopen if the issue persists.

FYI we identify a Next.js SSG app on Amplify if it conforms to these conditions:
- App's build script in the package.json file reflects the following:
```
"scripts": {
  "dev": "next dev",
  "build": "next build && next export",
  "start": "next start"
},
```
- BuildSpec (amplify.yml) of your Amplify app reflects the `baseDirectory` as `out`:
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: out
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
