### ISSUE TITLE
Access Control Credentials Not Working

### ISSUE THREAD

**Issue by zcoon** [aws-amplify/amplify-hosting#2819]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dxs7s2827n8m7

### Region

us-east-1

### Amplify Hosting feature

Access control

### Describe the bug

The write up for this is simple.

We had credentials for access control on our sites that previously worked as expected.

Starting some time within the last 12 hours, our teams started to notice that the credentials no longer worked (despite no changes from our side).

I've checked this issue against multiple apps we host with amplify, and it affects every single one, including when I change the credentials and copy/paste them to try logging in. The only valid solution at the moment is to remove the access control altogether which defeats the entire purpose of this feature.

### Expected behavior

The expected behavior is that I can successfully log into a password protected site with the credentials that are set within the Amplify console.

### Reproduction steps

Try to access any password protected amplify site with valid credentials.

### Additional information

From checking the Amplify discord, this issue is not specific to just my account. Other users are mentioning the same issue.
<img width="1025" alt="Screen Shot 2022-06-21 at 4 23 03 PM" src="https://user-images.githubusercontent.com/6790561/174899627-74b4da9f-744d-4aff-abc0-266365d5c7fd.png">

**Comment by hloriana** [comment]
Hi @zcoon 👋🏽 Thanks for raising this issue. The team is root causing this behavior and we are actively working on a solution for this issue. We will post an update ASAP.

**Comment by hloriana** [comment]
Please re-deploy your app. After re-deployment, you should be able to use your Access Control credentials successfully. Please let us know if you're unblocked.
