### ISSUE TITLE
Base domain doesn't redirect to www

### ISSUE THREAD

**Issue by alexey-shary** [aws-amplify/amplify-hosting#2823]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dlh8899o5fac2

### Region

us-east-1

### Step

Access to Production Environment URL

### Status

Failed

### Issue or question

Base domain doesn't redirect to www subdomain for Amplify application. Domain is migrated to Route 53 and A record points to the CloudFront URL that is taken from Amplify Domain Management. There are also redirect rules that should redirect from https://mydomain.io to https://www.mydomain.io but it doesn't work neither.

**Comment by hloriana** [comment]
Hi @alexey-shary 👋🏽 apologies for the delay in response. It looks like your base domain is redirecting to your `www` sub domain now. Please re-open if you are still running into this issue. Thank you!
