### ISSUE TITLE
Latest code commit to GitHub isn't triggering Build for AWS Amplify APP

### ISSUE THREAD

**Issue by ayodyln** [aws-amplify/amplify-hosting#2829]
**Please describe which feature you have a question about?**
I'm currently working a web app for my student job. Each time I pushed a commit, usually AWS Amplify would auto build my latest code. Until it randomly stopped. Now, each time I commit some code. Amplify won't perform an auto-build of my latest code. 

**Provide additional details**
Upon commit of latest code, I check if the build is performing. Nothing happens to trigger a build. I looked online for past info about this issue and found to reconnect the main branch of my repository. That worked, but it still won't auto-build after that. 

**What AWS Services are you utilizing?**
AWS Amplify (Graphql, Hosting, Auth)

Where should I go from here? I'm still new to the game and trying to find a way to repair my workflow. Thank you!

**Comment by ayodyln** [comment]
Update:

After going about trouble shooting a different way. It seems my latest commits are being registered. I deleted the webhooks for my repository and reconnected the main branch to my app. Has this happened before to anyone else, what causes this to happen?

**Comment by hloriana** [comment]
Hi @ayodyln 👋🏽 we are looking into this behavior. Did removing the webhooks and reconnecting the application resolve the issue?

**Comment by Jay2113** [comment]
Hi @ayodyln, I was unable to reproduce this behavior. If the issue continues to persist, kindly reopen the issue and provide us the following information:
- Amplify app id
- Is your GitHub repository present within a GitHub organization?
- Have you migrated your Amplify app to use the GitHub app workflow? https://docs.aws.amazon.com/amplify/latest/userguide/setting-up-GitHub-access.html#migrating-to-github-app-auth

**Comment by ayodyln** [comment]
Sorry for the late replies. @hloriana, doing that did fix the issue to put it simply. For some odd reason, I had two registered webhooks when I looked at them on my GitHub repo.
