### ISSUE TITLE
Amplify rewrite not working with custom domains

### ISSUE THREAD

**Issue by pankaj-mule** [aws-amplify/amplify-hosting#2833]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2vlbywok6rbvz

### Region

ap-northeast-1

### Step

Custom Domain rewrite failing for some ISP

### Status

Failed

### Issue or question

I have hosted react application using amplify, which is working fine **amplify** domain, but with custom domain it wasn't working on few places. when we drilled down the issue it seems failing only when api's are called through rewrites added in App Setting.

API added in rewrite is pointing to backend system which is deployed in aws with route 53 configured to elb where it has hosted. Everything works fine with amplify url but failing only through custom domain

### Error message

With custom domain, 

same app same machine same api we getting 
ERR_HTTP2_PROTOCOL_ERROR for custom domain and not for amplify domain

### Additional information

We didn't find any configurations to use same ssl as used for elb, downgrade http2 to http1.1, disable cors and other cloudfront configs

So tried to create seperate cloudfront which should be mapped to amplify app but it didn't worked as well

**Comment by pankaj-mule** [comment]
UI and API are hosted with same server with different subdomains

**Comment by hloriana** [comment]
Hi @pankaj-mule 👋🏽 can you please provide an HAR capture for when you access the API through the redirects with the custom domain?

**Comment by pankaj-mule** [comment]
hloriana, we are still facing issue, as you asked to share HAR, it may have sensitive information due to which we may not able to share any info
