### ISSUE TITLE
28/06/2022 AWS AMLIFY UPLOAD CONTINUES TO FAIL ON APPROX. 50MB FILE

### ISSUE THREAD

**Issue by basfordrobert** [aws-amplify/amplify-hosting#2835]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

https://ap-southeast-2.console.aws.amazon.com/amplify/home?code=a18cd4fd2c0447386242&region=ap-southeast-2

### Region

southeast-2

### Amplify Hosting feature

Manual deploys

### Describe the bug

As an authenticated AWS Console User, upload file to AWS AMPLIFY by manual fileselection fails

### Expected behavior

Upload file transfer success

### Reproduction steps

1.Login AWS Console
2. Select AWS Amplify
3. Select App
4. Select file for upload Archive.zip
5. Select Deploy

### Build Settings

```yaml
Last successful upload 13/06/2022 
./amplify/home?code=a18cd4fd2c0447386242&region=ap-southeast-2#/d2ina7ghoi2un8
```

### Additional information

Internet Speed for deployment - Uplink >40Mbps Downlink >400Mbps 
Upload file Archive.zip is approx. 50MB

**Comment by hloriana** [comment]
Hi @basfordrobert 👋🏽 can you provide the zip folder so we can reproduce this behavior?

**Comment by Jay2113** [comment]
It looks like your recent deployments have completed successfully. If you continue to observe deployment failures, kindly provide us the following information:
- zip folder of the build artifacts
- Does the issue occur when using "Drag and drop" or "Amazon S3 or any URL" method?

Docs: https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html
