### ISSUE TITLE
Amplify Rewrites and Redirect

### ISSUE THREAD

**Issue by coetzeetx** [aws-amplify/amplify-hosting#2839]
I am trying to setup a proxy for my Amplify web app so that '/demo' is redirecting to another domain which would be my server in this case. 

to do this I use the following rule:

![image](https://user-images.githubusercontent.com/98972396/176647816-0fa27111-8ae3-4f81-b63f-40f65646a5be.png)

The Result is a 403 on my frontend.

I have also tried a redirect:

![image](https://user-images.githubusercontent.com/98972396/176648030-9b26cd40-6ca7-491b-a6bf-1cb1efe600a2.png)

which results in a CORS missing in header issue.

but upon inspecting the server's headings cors is allowed on all domains:

![image](https://user-images.githubusercontent.com/98972396/176648200-c92188cb-d5d2-47f5-8b22-9f7588e3df94.png)

what am i doing wrong?

**Comment by hloriana** [comment]
Hi @coetzeetx 👋🏽 thanks for raising this issue. You have to use 200 rewrite to proxy the request to another domain which appears you have done correctly initially. Can you please provide your app ID so we can further investigate? An HAR capture after making the request can also help us identify why the request is not working.

**Comment by Jay2113** [comment]
Closing the thread due to age. Refer to our [docs](https://docs.aws.amazon.com/amplify/latest/userguide/redirect-rewrite-examples.html#reverse-proxy-rewrite) on how to setup reverse proxy rewrites.
