### ISSUE TITLE
Custom domain not serving latest version of app

### ISSUE THREAD

**Issue by stitch-rich** [aws-amplify/amplify-hosting#2846]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dq8ai2n6pg8pv

### Region

eu-west-2

### Step

deployment

### Status

Available

### Issue or question

We are using Amplify to host 3 front end only React applications. These are deployed through our Github action pipelines using the API.

This runs successfully and the app is updated on the Amplify url each time we run it with the latest code. However it appears the version of our app being served on the custom domain configured is a version from about a week ago. Each time we run the build we get the same result so appears this stopped being updated mid-end of last week.

We have been across our code, setup and anything we can see our side but cannot find anything that would have changed to cause this. It is affection all 3 of our apps in Amplify which are run across 2 custom domains. No changes were made to DNS or pipelines in this time so we are a at a bit of a loss as to next steps to rectify this.

**Comment by hloriana** [comment]
Hi @stitch-rich 👋🏽 thanks for raising this issue. I've not setup CI/CD with Github Actions before so I need some more information from you to fully understand. Are there any workflow logs you can share that are output by GitHub when you run a deployment? Also, could you share the yml script you are running for the workflow? Please be sure to redact any sensitive information.

**Comment by dereke55** [comment]
I seem to be having a similar issue using Manual Deployment.  I have documented the issue in #2860 .  Please let me know if I can provide additional information to help troubleshoot this issue.

**Comment by oliver-leung** [comment]
We've root-caused the issue and are currently working on the fix. In the meantime, please use one of the following workarounds:
1. Disable, then re-enable the custom domain in App Settings > Domain Management > Manage subdomains
1. Only upload compressed .zip build artifact folders

**Comment by katherinepamina** [comment]
@oliver-leung is there an ETA on resolving this?

**Comment by oliver-leung** [comment]
@katherinepamina Unfortunately we can't provide an ETA on the fix, but it has been implemented and we're hoping to deploy it soon. In the meantime, please use one of the above provided workarounds.

**Comment by maurhub** [comment]
Hey guys, I'm experiencing the same issue with CI enabled. Had to disable and re enable custom domains to get it working

**Comment by markAking** [comment]
I am as well. And this response from tech support is awful

**Comment by mbj36** [comment]
I have faced this issue too, Had to disable and re-enable it. Can we get this fixed sooner please ?

**Comment by runtman** [comment]
Can this be addressed, it's a pretty ridiculous bug to have around for so long.

**Comment by oliver-leung** [comment]
The fix has already been deployed and verified in all regions. Please retry your deployments, and let me know if the issue persists.
