### ISSUE TITLE
AWS amplify not rendering image while local build render image correctly

### ISSUE THREAD

**Issue by andreling01** [aws-amplify/amplify-hosting#2849]
**Please describe which feature you have a question about?**
I'm currently using AWS amplify to run one of my react app. I added one image in my react public folder so I can use that as a background. When I test it in my local, the image shows correctly. However, after I push my code to git and use AWS amplify to build it, I found the image is missing. Based on the build log, seems the image is never copy to the build directory. Is there anything I need to do to make sure the image is correct uploaded?

**Provide additional details**
My git branch: https://github.com/andreling01/mltd-ranking
My app id: d3azsbdqn01xd0

**What AWS Services are you utilizing?**
AWS amplify

**Provide additional details e.g. code snippets**
I also make sure the manifest file is changed and added with my new image information.

**Comment by hloriana** [comment]
Hi @andreling01 👋🏽 thanks for raising this question. I was able to reproduce and find a solution for you. 🙂 We have a [rewrite rule for SPA applications](https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa) that routes all files to `index.html`. We use regular expressions to identify the different file extensions that we rewrite: 
![Screen Shot 2022-07-06 at 11 33 42 AM](https://user-images.githubusercontent.com/76065904/177599834-0eb51b64-d3a2-4867-9c50-7803dd2acea3.png)

Your background image is a `jpeg` which we did not add to the regex. If you add `|jpeg|` like so ,  then you should be able to see your background image.

Workaround:
1. In the console, navigate to your app and select **Rewrites and redirects** 
2. Select **Edit** and replace the source address with `</^[^.]+$|\.(?!(css|gif|ico|jpg|jpeg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>`
3. Save and refresh your hosted page.

Please let us know that this works for you.

**Comment by andreling01** [comment]
Thanks! That solved my problem!
