### ISSUE TITLE
Only way to enable automatic deploys is to delete production?

### ISSUE THREAD

**Issue by PederAaby** [aws-amplify/amplify-hosting#2854]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2ihfergif0nj1

### Region

us-north-1

### Amplify Hosting feature

Backend builds

### Describe the bug

We have previously set up a manual deploy to production, mainly using Amplify publish. 

Now we want to deploy from Github. But pressing "Reconnecting repository" only causes the below button to spin. 
![Screenshot 2022-07-07 at 13 21 19](https://user-images.githubusercontent.com/16704172/177761947-dd5caa85-7284-44f9-a491-7a490431e97f.png) 
 
And attempting to use the command `aws amplify update-app --app-id APP_ID_HERE --repository REPOSITORY_URL --access-token ACCESS_TOKEN` yields the error "An error occurred (BadRequestException) when calling the UpdateApp operation: Cannot connect your app to repository while manually deployed branch still exists. Please delete all branches and try again.". 

And pressing "disconnect branch" here
![Screenshot 2022-07-07 at 13 22 59](https://user-images.githubusercontent.com/16704172/177762239-0b9494ea-01b3-42b5-ac09-49900b927b2f.png)

Tells us that this will delete the associated hosted app, which is our production environment. 

Is the only solution to set up CI/CD in Amplify to tear down our production environment? 

### Expected behavior

Able to connect repository and enable auto deploys. 

### Reproduction steps

See description

**Comment by hloriana** [comment]
Hi @PederAaby 👋🏽 thanks for raising this issue. There currently isn't a way to convert a manually deployed app to CI/CD. What you can do instead is create a new app that uses your repository and connect that app to the backend environment associated with your manually deployed app. 

Here is a guide for connecting an app to a backend environment in another app:[ Edit an existing frontend to point to a different backend](https://docs.aws.amazon.com/amplify/latest/userguide/reuse-backends.html#reuse-backends-edit-existing)
