### ISSUE TITLE
Add domain successful but app not available at the domain

### ISSUE THREAD

**Issue by thewebwell** [aws-amplify/amplify-hosting#2856]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dqhlfzv5g21vy

### Region

eu-west-1

### Step

Add domain

### Status

Success

### Issue or question

Our domain is managed by Route53, so all records can be created automatically. The add domain step appears to complete successfully. The Route53 records are created automatically, one for the SSL cert and another CNAME to map the domain to the automatically generated Cloudfront distribution. 

The problem is the app is not available at the custom domain. The url cannot be reached.

I have tried removing the domain and adding it again. I have tried this several times. That doesn't make any difference.

I have also tried deleting the Amplify app completely and creating it again. I get the same problem.

This problem makes it impossible to connect the domain to the app.

### Additional information

The app is available on the default amplify url provided.

**Comment by thewebwell** [comment]
This issue appears to be specific to the domain. I tried adding a different domain and that worked - the app was available at this newly added domain.

By way of background, the domain that has the problem was previously mapped to Amplify in a different AWS account. I removed that domain from the app in the previous AWS account, and then have added the domain in this new AWS account.
I assume the problem must be something to do with this. Please advise how to resolve

**Comment by hloriana** [comment]
Hi @thewebwell 👋🏽 the master branch is returning blank due to a CORS issue with trying to access an API. But it appears that the other 3 branches are able to access the corresponding API. The response is missing the `Access-Control-Allow-Origin` header that is present in the respond headers on the other branches.
