### ISSUE TITLE
Amplify App Missing, Tried redeploying but domain setup says domain already associated with different app

### ISSUE THREAD

**Issue by incepthink** [aws-amplify/amplify-hosting#2865]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-east-2

### Describe the bug

We had a an amplify app up and running for many months, but the app is now missing from our list of amplify apps on console ('m sure I'm looking at the right regions,tried switching regions too). The site was live and working but no new changes were being pushed. Tried fetching using the aws cli too, but this app is missing.

I tired making a new amplify app from the same github repo and delete the old s3 records and set up new ones. I made the new app without any issues, but while I configure the domain I get this error
`Create domain association failed
One or more domains requested are already associated with another Amplify app: (domain names...)
`
Is there any way to hard reset this or free up this some other way? Can I get a list of all my amplify apps globaly(I checked different regions and can't find it anywhere but still I'd like to check)? I am fine with redeploying the app again, how can I get my domain freed up from amplify again?

### Expected behavior

Amply app correctly displayed in app list in amplify consose

### Reproduction steps

Nil

**Comment by hloriana** [comment]
Hi @incepthink can you please share your account ID or current app ID so we can further investigate this behavior?

**Comment by hloriana** [comment]
Closing due to no response. Please re-open if you are running into this issue still.
