### ISSUE TITLE
On Refreshing page leads to Access Denied error

### ISSUE THREAD

**Issue by dgosar** [aws-amplify/amplify-hosting#2867]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dbn8rbdgw1k4f

### Region

us-east-1

### Amplify Hosting feature

Access control, Build settings, Redirects

### Describe the bug

I have hosted my react app using amplify and it's working fine, but when I refresh the some specific page, it throw Access Denied error
**please check attach a screen shot of the error**
<img width="563" alt="image" src="https://user-images.githubusercontent.com/107399099/178969603-bacadec4-3c8d-4baf-9895-3a237f76e60c.png">
**My Build settings are below:**
<img width="238" alt="image" src="https://user-images.githubusercontent.com/107399099/178969764-966126db-9fc7-4121-a576-07851017f90b.png">
**Also I have tried setting rewrites and redirects with following settings:**
Try 1:
Source address: </^[^.]+$|.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>
Target address: /index.html
Type: 200

Try 2:
Source address: </^((?!\.(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$).)*$/>
Target address: /index.html
Type: 200
Still getting the error

### Expected behavior

Its should work with any url/path

### Reproduction steps

1. Deploy your app on AWS Amplify
2. Run the build
3. Link to the domain
4. Hit the website 
5. Refresh page on user profile

**Comment by Jay2113** [comment]
Hi @dgosar , I was not able to reproduce this behavior while navigating through your Amplify URL and custom domain. Are you still running into this issue?

**Comment by dgosar** [comment]
No I fixed this by adding permission for uploading assets to S3 as custom-policy in Amplify API.
In custom-policies.json
[
  {
    "Action": [
      "s3:*Object",
    ],
    "Resource": [
      "arn:aws:s3:::*"
    ]
  }
]
