### ISSUE TITLE
Domain SSL configuration — SSL creation error (we require additional verification for one or more domain names)

### ISSUE THREAD

**Issue by vkart** [aws-amplify/amplify-hosting#2871]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

drlm8guohfh15

### Region

eu-west-1

### Step

SSL creation

### Status

Failed

### Issue or question

Amplify app was successfully connected to a second-level domain,  managed by Cloudflare. SSL certificate was issued without any problems. At some point AWS was unable to reissue the certificate. I tried to remove and re-add domain to the app in Apmlify console. As a result I'm stuck at the first step — SSL creation with the error below.

### Error message

There was a failure in generating the certificate. Please try again.
Error message: We require additional verification to request a certificate for one or more domain names in this request. The following page describes this in more detail: https://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-failed.html#failed-additional-verification-required

**Comment by hloriana** [comment]
Hi @vkart apologies for the delay. The best way to resolve this issue is for you to create a [Support Case](https://console.aws.amazon.com/support/home)  as suggested in the troubleshooting guide. AWS Support will be able to help you renew your certificate for your domain.
