### ISSUE TITLE
Custom Domain Error [ERR_NAME_NOT_RESOLVED] for subdomain

### ISSUE THREAD

**Issue by mhollenbeckMykori** [aws-amplify/amplify-hosting#2873]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

db5obs13i7dsc

### Region

eu-central-1

### Step

Subdomain hosting

### Status

Availiable

### Issue or question

Subdomain is not reachable, even though Status: Availiable and no Errors in the Dashboard.

Setup:
- disabled root domain
- dns records setup with wint global

The domain activation is successful, but the app cannot be reached via the given subdomain.

### Error message

DNS_PROBE_FINISHED_NXDOMAIN

### Additional information

The App is reachable if the setup is done for the root domain instead. 

The check on https://www.whatsmydns.net/ is also successful.

**Comment by hloriana** [comment]
Hi @mhollenbeckMykori it appears that your app is reachable via the subdomain now. Please re-open if you run into this issue again. Thank you.
