### ISSUE TITLE
Error listing Github Repositories when updating repository

### ISSUE THREAD

**Issue by alacret** [aws-amplify/amplify-hosting#2875]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dpfiqr8ihahwm

### Region

us-east-1

### Amplify Hosting feature

Not applicable

### Describe the bug

When listing the repos, the app throws an error of no access to the repos, even when it already has access. 

This happens when I'm trying to reconnect a Repo, or with the message of Start Migration to a Github App.
<img width="1728" alt="Screen Shot 2022-07-20 at 9 25 56 AM" src="https://user-images.githubusercontent.com/918895/179994318-dd6103e9-e6f9-4e9b-8537-627fa4021ffa.png">

### Expected behavior

To list all the Github repositories that the app has access to

### Reproduction steps

1. Got to the app
2. Click General
3. click Reconnect Repository
4. The access to my org has access to over 220 repos, maybe this is the error

**Comment by hloriana** [comment]
Hi @alacret I wasn't able to reproduce this. Was this Amplify app already Migrated to GitHub App? Is this also happening with other apps deployed from repos in that GitHub organization?

**Comment by alacret** [comment]
> Hi @alacret I wasn't able to reproduce this. Was this Amplify app already Migrated to GitHub App? Is this also happening with other apps deployed from repos in that GitHub organization?

@hloriana yes and yes
