### ISSUE TITLE
DNS config for domain managed in separate AWS Route 53 account

### ISSUE THREAD

**Issue by lucasishuman** [aws-amplify/amplify-hosting#2877]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2frxnc8yrk6a

### Region

us-west-2

### Step

Root domain configuration

### Status

Subdomains work, root domain does not

### Issue or question

It is very easy to configure a custom domain for an Amplify app when the domain is managed in Route 53 within the same AWS account.
https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-amazon-route-53.html

There is also good documentation about how to configure a custom domain for an app hosted by a third party.
https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-a-third-party-dns-provider.html

However, I am not 100% sure how to configure a custom domain for my Amplify app where the domain is managed by Route 53 in a _separate_ AWS account which is not my own.

I've been treating it as a 3rd party since I cannot browse and select the domain directly from within the console as I can with domains in my own account. I have verified the domain, added two subdomains and the 'root' domain. The subdomains are working great after adding the CNAME records to DNS in separate Route 53 account (including a 'www' subdomain)

However, when it comes to the "root" domain... there is not a way to manually add the ANAME record in the separate Route 53 account (step 12 in 3rd-party DNS docs). There is also not a way to add a CNAME to the root domain (step 11 of 3rd-party DNS docs).
https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-a-third-party-dns-provider.html

What is the proper path for configuring Route 53 DNS in a separate AWS account from the one where my Amplify app lives?

Thank you.

### Error message

Root domains **do not** resolve
eg.
https://besupernatural.com

Subdomains **do** resolve
Eg.
https://www.besupernatural.com

### Additional information

![image](https://user-images.githubusercontent.com/1753761/180090285-094959e5-b912-4e1f-8e1e-dfacd5d4ebca.png)

**Comment by lucasishuman** [comment]
Screens from separate Route 53 DNS management

![Screen Shot 2022-07-20 at 8 47 49 PM](https://user-images.githubusercontent.com/1753761/180107089-3a8cb76e-cd92-4b4b-8de2-ee741e17c08f.png)

![Screen Shot 2022-07-20 at 8 48 21 PM](https://user-images.githubusercontent.com/1753761/180107101-8e5e55a5-48d2-44b2-b221-d2d0d2ba59c5.png)

**Comment by hloriana** [comment]
Apologies for the delay. This is a limitation with Amazon Route53. As you've discovered, there isn't an option to provide an ALIAS record for resources that exist outside of the same account. The only workaround is to migrate the custom domain to Route53 in the same account your Amplify app is in so you can use the root domain.
