### ISSUE TITLE
Rewrites and redirect does not work in manual static deployments

### ISSUE THREAD

**Issue by incr3m** [aws-amplify/amplify-hosting#2881]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

https://ap-southeast-2.console.aws.amazon.com/amplify/home?region=ap-southeast-2#/d2f0p04mnv8zp2

### Region

ap-southeast-2

### Amplify Hosting feature

Manual deploys, Redirects

### Describe the bug

We are currently doing static SPA hosting via Amplify Console. Accessing the root path seems to be working. However refreshing the containing routes will show the following error:
![image](https://user-images.githubusercontent.com/3125784/180364880-9557a133-33cc-49c0-b7bd-9882a2b43cb7.png)

Files are getting deployed using NodeJS script:
```js
await amplify
  .startDeployment({
    appId,
    branchName,
    sourceUrl: `s3://${data.Bucket}/${data.Key}`,
  })
  .promise();
```

I already added the configuration in **Rewrites and redirects** settings but it does not seem to change anything
![image](https://user-images.githubusercontent.com/3125784/180365487-3b471c75-57bf-45e7-b600-2f221436399c.png)

### Expected behavior

Rewrite and redirects should work with manual deploy

### Reproduction steps

1. Setup rewrites and redirect
2. Add new environment
3. Select Amazon S3 as method
4. Wait for build to be completed
5. Access hosting url with adding route/path (e.g. `https://testdeploy.d2f0p04mnv8zp2.amplifyapp.com/anything/`

**Comment by hloriana** [comment]
Hi @incr3m apologies for the delay. I'm not able to reproduce this access denied behavior. When you create your zip file, are you navigating inside the build directory and zipping the contents? If you just zip the folder itself, then you can run into this access denied error.

**Comment by incr3m** [comment]
@hloriana I tried using a different zip library and append file per file and still getting the same issue. 
Here's the full deploy script i'm using for this. Let me know if you need the actual APP IDs:
```js
import AWS from "aws-sdk";
import fs from "fs";
// import * as url from 'url';
import { zip } from "zip-a-folder";

// const __dirname = url.fileURLToPath(new URL('.', import.meta.url));

const [branchName, directory] = process.argv.slice(2);

const zipPath = `${directory}.zip`;

await zip(directory, zipPath);

const PRJ = "emb-hosting";
const STATIC_HOSTING_APP_ID = "d2f0pxxxxxxxxx";
const S3_BUCKET_NAME = "mbdevops-xxxxx-dev";

const amplify = new AWS.Amplify({
  region: "ap-southeast-2",
});

const s3 = new AWS.S3({
  region: "ap-southeast-2",
});

const appId = STATIC_HOSTING_APP_ID;

try {
  await amplify
    .createBranch({
      appId,
      branchName,
    })
    .promise();
} catch (err) {
  console.log(">>deploy-zip/index::", "branch exists: ", branchName); //TRACE
}

const { jobSummaries } = await amplify
  .listJobs({
    appId,
    branchName,
    maxResults: 1,
  })
  .promise();

console.log(">>deploy-zip/index::", "jobSummaries", jobSummaries); //TRACE

const lastJob = jobSummaries[0];
if (lastJob && lastJob.status === "PENDING") {
  console.log(">>deploy-zip/index::", "job is ongoing"); //TRACE
  await amplify.stopJob({ appId, branchName, jobId: lastJob.jobId }).promise();
}

function uploadToS3(fileName, s3Key) {
  const readStream = fs.createReadStream(fileName);

  const params = {
    Bucket: S3_BUCKET_NAME,
    Key: `${PRJ}/${branchName}/${s3Key}`,
    Body: readStream,
    // ACL: 'public-read',
  };

  return new Promise((resolve, reject) => {
    s3.upload(params, function (err, data) {
      readStream.destroy();

      if (err) return reject(err);

      return resolve(data);
    });
  });
}

const data = await uploadToS3(zipPath, `${branchName}/${branchName}.zip`);

if (!data.Location) throw new Error("Can't get data location");

await amplify
  .startDeployment({
    appId,
    branchName,
    sourceUrl: `s3://${data.Bucket}/${data.Key}`,
  })
  .promise();

const reviewUrl = `https://${branchName}.${appId}.amplifyapp.com`;
/**
 * Expose deploy URL
 */
console.log(">>deploy-zip/index::", "url", reviewUrl); //TRACE

```

**Comment by hloriii** [comment]
There *may* be an incompatibility with how `zip-a-folder` package creates the file and what is needed to host a manual deploy app on Amplify. 

According to our [documentation](https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html), this error occurs when:

> When you create the zip folder, make sure you zip the contents of your build output and not the top level folder. For example, if your build output generates a folder named “build” or “public”, first navigate into that folder, select all of the contents, and zip it from there. If you do not do this, you will see an “Access Denied” error because the site's root directory will not be initialized properly.

That being said, I'm unfamiliar with how `zip-a-folder` creates the zip file but it could be causing the error. I recommend manually zipping the contents and deploying that to see if the issue persists. 

It also appears that your app seems to be working at this time. We do apologize for the oversight of this issue. If you continue to experience unexpected behaviors, please open a new issue and we will be happy to help.
