### ISSUE TITLE
asp.net core 6 app - Access Denied 

### ISSUE THREAD

**Issue by paresh-bhatewra** [aws-amplify/amplify-hosting#2883]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d34fcwfeedlxri

### Region

us-east-1

### Amplify Hosting feature

Access control

### Describe the bug

When I open the app url https://prod.d34fcwfeedlxri.amplifyapp.com, it gives access denied error.

### Expected behavior

it should open the app.

### Reproduction steps

1. I uploaded a zip file containing build output of asp.net core 6 site.
2. Deployment succeeded.
3. Got this url  - https://prod.d34fcwfeedlxri.amplifyapp.com/
4. When I go to this irl, it gives me access denied error

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>M0CF5RXCMMNDJFK8</RequestId>
<HostId>MVAVlpF6umLRgKepze1oY313yHucX7IlXkwHWrzOc8b2VhI8OQNq0YE04/el0KHWu3cJ7twyOBc=</HostId>
</Error>

**Comment by hloriana** [comment]
Hi @paresh-bhatewra 👋🏽 it looks like you removed your app so I'm not able to further investigate. Did you navigate into the build output folder and zip the contents? If you just zip the folder itself you can run into this error. Please see our Manual Deploy documentation for more details on this error: https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html

**Comment by paresh-bhatewra** [comment]
Hey,

I had gone through that article before raising the ticket, and I confirm that I created the zip in correct way as mentioned. I have again deployed the same zip with same error.

https://prod.d2ethzgr24y9e0.amplifyapp.com//

Let me know what I am doing wrong.

**Comment by paresh-bhatewra** [comment]
@hloriana - any update?

**Comment by Jay2113** [comment]
@paresh-bhatewra 👋 , thanks for reaching out. The 404 error can occur if the `index.html` file is not present or is nested under a directory in the zip file. To get started with deploying .NET apps on Amplify Hosting, refer to this blog post: https://aws.amazon.com/blogs/devops/deploy-net-blazor-webassembly-application-to-aws-amplify/.
