### ISSUE TITLE
Continuous Deploys happening even if disabled

### ISSUE THREAD

**Issue by chstrong** [aws-amplify/amplify-hosting#2890]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3k63zo08axthy

### Region

us-east-1

### Describe the bug

Even though continuous deployments is disabled, it will still deploy continuously.

On the main hosting screen, it says the following: Continuous deploys setup with staging backend.

![Screenshot 2022-07-28 at 9 05 38 PM](https://user-images.githubusercontent.com/6489758/181513154-ada2cebd-fcc3-4bc1-839a-d3db01589375.png)

But when clicking on the edit link, the checkbox for "Enable full-stack continuous deployment (CI/CD)" is unchecked.

![Screenshot 2022-07-28 at 9 05 54 PM](https://user-images.githubusercontent.com/6489758/181513607-00365529-e933-4eab-8184-2965924a511e.png)

### Expected behavior

When the checkbox for "Enable full-stack continuous deployment (CI/CD)" is unchecked, there shouldn't be a message on the main screen, that Continuous deploys is set up, and there shouldn't be any continuous deployments happening.

### Reproduction steps

1. Create a new application and link repository
2. Do not check the checkbox to Enable full-stack continuous deployments
3. Once the app is created, look at the main screen of the app, and you will see that it says that continuous deploys is set up, even though it's unchecked when clicking on the edit link.

**Comment by hloriana** [comment]
Hi @chstrong 👋🏽 we have added this as a bug to our product backlog for prioritization. I tested this out in my own account and it appears that this is just a UI bug. If you look at build logs where you've disabled continuous deploys, you'll see Amplify generate an `aws-exports.js file` for the frontend but updates won't be pushed to the backend. 

You also have the option of removing the `backend` section from your build settings and adding the `AMPLIFY_SKIP_BACKEND_BUILD` environment variable (set to `true`) to avoid building the backend.

**Comment by chstrong** [comment]
Hi @hloriana,

Thanks for your kind assistance, adding this as a bug. 

In the NextJS app, that I've built, I'm not using the backend environments, only the frontend environments.

So I don't have an aws-exports.js file locally.

It's the frontend that gets built automatically, once I push changes to GitHub, even though I've not enabled the option.

**Comment by swaminator** [comment]
@chstrong this is by design. Continous deploys **is** setup, its just not pointing to any backend.
