### ISSUE TITLE
AdministratorAccess-Amplify policy should contain es:UpdateDomainConfig Action

### ISSUE THREAD

**Issue by clownbaby** [aws-amplify/amplify-hosting#2892]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dcaffs0m7jnrr

### Region

us-east-2

### Amplify Hosting feature

Access control, Backend builds

### Describe the bug

When you create a new environment and use the wizard to create a new deployment role, the default behavior is to create a role with AdministratorAccess-Amplify policy.

This policy doesn't seem to include es:UpdateDomainConfig, which is causing cloudformation errors when I add the following to team-provider-info.json and deploy

```
    "categories": {
      "api": {
        "<>": {
          "OpenSearchInstanceType": "t2.medium.elasticsearch"
        }
      },
```

`[User: arn:aws:sts::<>:assumed-role/<> is not authorized to perform: es:UpdateElasticsearchDomainConfig on resource: arn:aws:es:us-east-2:<>:domain/amplify-opense-<> because no identity-based policy allows the es:UpdateElasticsearchDomainConfig action, User: arn:aws:sts::<>:assumed-role/<> is not authorized to perform: es:UpdateDomainConfig on resource: arn:aws:es:us-east-2:<>:domain/amplify-opense-<> because no identity-based policy allows the es:UpdateDomainConfig action] (Service: AWSElasticsearch; Status Code: 403; Error Code: AccessDeniedException; Request ID: 05004c79-2056-43cd-9ec3-d0c32ed37675; Proxy: null)`

### Expected behavior

Probably shouldn't have cloudformation deployments fail deployments with default policies

### Reproduction steps

1. Create app with new role, using 'create new role' feature
2. "Create a new service role. In the window that opens, accept the pre-selected defaults on each screen to create a new service role."
3. Create schema with @searchable types
4. Update team-provider-info.json with new value for OpenSearchInstanceType
5. $ amplify push -y
6. Check cloudformation for build failure (SearchableStack)

**Comment by hloriana** [comment]
Hi @clownbaby 👋🏽 thank you for pointing out this discrepancy with the managed policy. We have added this to our product backlog for prioritization.

**Comment by MattHapner** [comment]
I've run into this issue as well. Is there any known workaround for this?

It's not immediately clear to me why this is failing now - I haven't changed the OpenSearch instance type since initialization, and now the Domain needs a configuration update.

**Comment by GeorgeBellTMH** [comment]
I just got this as well...

**Comment by GeorgeBellTMH** [comment]
@hloriana this seems like an easy fix...might need to bump up the priority...

**Comment by GeorgeBellTMH** [comment]
Also, might make more sense in CLI?

**Comment by GeorgeBellTMH** [comment]
I believe this is coming up now because somewhere between 9->10 of the cli they rearranged backend-config.json to alpha...which repushes everything...including some config that hadn't been pushed in a long time...

**Comment by spudlig** [comment]
Got this as well - is there currently a workaround?

**Comment by hloriii** [comment]
Hi folks, the policy was updated on February 24th, 2023 to include `es:UpdateElasticsearchDomainConfig`: https://docs.aws.amazon.com/amplify/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-updates 

Closing as resolved.
