### ISSUE TITLE
Deploy reports "Invalid Id" but not service is noted

### ISSUE THREAD

**Issue by Endlessline** [aws-amplify/amplify-hosting#2897]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1d2nf54jf2ui0

### Region

us-east-2

### Amplify Hosting feature

Manual deploys

### Describe the bug

With no changes to my code or infrastructure I've gotten the following output in my builds. I'm not sure what ID the output is referring to or which service is involved. I've checked S3 and the deployment and hosting buckets are showing updated documents (so my thinking is that the files are at least partially updated). 

CLI version 6.3.1

```
frontend build command exited with code 0
--
1778 | Publish started for S3AndCloudFront
1779 | - Uploading files...
1780 | ✖ Error has occurred during file upload.
1781 | An error occurred during the publish operation: Invalid id
1782 |  
1783 | [Container] 2022/07/29 17:05:45 Command did not exit successfully amplify publish -y -a -c exit status 1
1784 | [Container] 2022/07/29 17:05:45 Phase complete: BUILD State: FAILED
1785 | [Container] 2022/07/29 17:05:45 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: amplify publish -y -a -c. Reason: exit status 1
1786 | [Container] 2022/07/29 17:05:45 Entering phase POST_BUILD
1787 | [Container] 2022/07/29 17:05:45 Uploading S3 cache...
1788 | [Container] 2022/07/29 17:17:38 Phase complete: POST_BUILD State: SUCCEEDED
1789 | [Container] 2022/07/29 17:17:38 Phase context status code:  Message:

```

The build script uses the following buildspec

```version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm install -g @aws-amplify/cli@6.3.1 --unsafe-perm=true
      - npm install
  build:
    commands:
      - AMPLIFY="{\"envName\":\"dev\"}"
      - amplify init --amplify $AMPLIFY --providers "{\"awscloudformation\":{\"configLevel\":\"general\"}}" --yes
      - amplify publish -y -a -c

cache:
  paths:
    - node_modules/**/*
    - amplify/backend/api/wbbugs/build/**/*
```

### Expected behavior

Error should be more descriptive. Root of problem is very difficult to ascertain. 

### Reproduction steps

Run deploy with CLI @ 6.3.1 perhaps. Reproduction is difficult as this worked and no changes have been made.

**Comment by hloriana** [comment]
Hello @Endlessline apologies for the delay, are you still running into this issue?

**Comment by Endlessline** [comment]
This stopped without any changes. Possibly some internal issue?

**Comment by hloriana** [comment]
We recommend upgrading to the latest version of the Amplify CLI. If this issue reoccurs please open a new issue. Thank you!
