### ISSUE TITLE
Any way for get current domain?

### ISSUE THREAD

**Issue by vadimka123** [aws-amplify/amplify-hosting#2909]
I’m using Amplify for host frontend app
Here custom domain setup + enabled Web Previews 
My frontend application contains microfrontend which should know domain on which hosted for retrieve all assets 
So I need get current domain for main branch deploy and in Web Preview
If will changed custom domain or moved to other Amplify app or will be new logic for domain of Web Preview this not should affect application
So in result any way for get current domain on build stage ?

**Comment by hloriana** [comment]
Hi @vadimka123 thanks for raising this question. Are you asking if there is a way to retrieve the web preview domain during the build process?
