### ISSUE TITLE
React build fails due to polyfills errors

### ISSUE THREAD

**Issue by lucas122478** [aws-amplify/amplify-hosting#2911]
I have a react project I am trying to get to build and run on AWS and I receive the polyfill stream error. Locally I resolved this by adding a fallback for stream and crypto. However, I can't figure out how to do the same here without access to the node_modules folder. How would I fix this on AWS?

Error below:

2022-08-03T22:42:40.505Z [INFO]: Module not found: Error: Can't resolve 'stream' in '/codebuild/output/src576058783/src/OKCAFE/node_modules/cipher-base'
                                 BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
                                 This is no longer the case. Verify if you need this module and configure a polyfill for it.
                                 If you want to include a polyfill, you need to:
                                 - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
                                 - install 'stream-browserify'
                                 If you don't want to include a polyfill, you can use an empty module like this:
                                 resolve.fallback: { "stream": false }

**Comment by itseasy21** [comment]
Run `npm install node-polyfill-webpack-plugin` in your terminal

go to your `webpack.config.js` and paste this:
```
const NodePolyfillPlugin = require('node-polyfill-webpack-plugin')
module.exports = {
// Other rules like entry, output, devserver....,
plugins: [
    new NodePolyfillPlugin()
]}
```
this should fix it. They have removed automatic polyfills in webpack 5. We have to include them ourselves. More info [here](https://github.com/webpack/changelog-v5#automatic-nodejs-polyfills-removed)

**Comment by hloriana** [comment]
Please let us know if the above solution works for you. Thank you!

**Comment by hloriana** [comment]
Please open a new issue if you need further assistance. Thank you!
