### ISSUE TITLE
New AWS Static HTML Site - Access Denied

### ISSUE THREAD

**Issue by Michael-G-Workman** [aws-amplify/amplify-hosting#2913]
Hello,

I have several static html websites that I am planning for AWS, since AWS is free for limited traffic, which I think is the best option for limited budgets.

My website consisted of an index.html file and then an images folder holding several images, and it is at the domain michaelgworkman.com, with the registrar Verio, I zipped the folder, then uploaded it to AWS Amplify, then imported my SSL cert from sslforfree.com, and then waited for the DNS to propagate, and now it looks like AWS is at the domain. But I get this error:

![image](https://user-images.githubusercontent.com/46582611/183044279-6e49ea54-2296-4bf0-9021-66d305ccd1ad.png)

I am an experienced software engineer, but I am completely new to AWS.

Thank you.

**Comment by hloriana** [comment]
HI @Michael-G-Workman can you please make sure you navigate inside the folder, select all of the files and Zip the files instead. If you just zip the folder itself you'll run into this exact issue. Please refer to this documentation for information regarding this behavior: https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html
