### ISSUE TITLE
"Reconnect repositories" runs forever in the console

### ISSUE THREAD

**Issue by MrBrunoSilva** [aws-amplify/amplify-hosting#2914]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1pu3lf7ktkoyr

### Region

us-west-2

### Amplify Hosting feature

Build settings, Manual deploys

### Describe the bug

I have an app that is manually deployed to dev/prod branches. I need to convert it over to use automated builds and deployment connected to the existing GitHub branches.
If I go the application page, app/app settings:general, and select "Reconnect Repositories" it spins forever. Perhaps this project has been connected to a repo in the past, but we've only used manual deploys for the meaningful life of the app. The Amplify GitHub app is installed and gives access to the specific projects in our organization's GitHub.

According to issue  #1554 it is not possible to convert a manually deployed project to CI/CD project. But that seems like it would be (and should be) a common path. 

### Expected behavior

Expected:
- Either reconnect repositories display a helpful error OR
- An additional option exists to reset repository connection and enable CI/CD OR
- This is properly documented with a guide "Converting from Manual Deployment to CI/CD" similar to the one for [getting started with existing code](https://docs.aws.amazon.com/amplify/latest/userguide/getting-started.html)

### Reproduction steps

1. go to amplify console
2. select app given by ID above
3. select Actions/View App Settings
4. click the button "Reconnect repository"

### Build Settings

```yaml
I don't have an amplify.yml
```

**Comment by hloriana** [comment]
Hi @MrBrunoSilva As you've stated this is currently not possible. Please follow issue #1554 for any updates regarding this feature.
