### ISSUE TITLE
Build failed! Can't find the causing issue

### ISSUE THREAD

**Issue by gary-reis** [aws-amplify/amplify-hosting#2916]
I'm trying to host my create-react-app with aws amplify. How should I resolve the error below?

Cloning repository - ✔

Backend - Failed!

![AWS Amplify console and 1 more page - Personal - Microsoft​ Edge 06-Aug-22 10_54_49 AM](https://user-images.githubusercontent.com/103214812/183235462-7918b8d3-95f7-42e2-9e74-4e6407ac89e2.png)

**Comment by hloriana** [comment]
Hi @gary-reis you could try making fsevents optional using `npm i fsevents@latest -f --save-optional` on future builds. If this does not work for you, please provide your App Id so we can further assist.
