### ISSUE TITLE
Custom Domain serves old version of site / 404

### ISSUE THREAD

**Issue by ltickett** [aws-amplify/amplify-hosting#2920]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dlitcjrqaqz64

### Region

eu-west-1

### Step

Custom Domain

### Status

Confused

### Issue or question

I have setup continuous deployment to Amplify and things seem to be working nicely.

I can see the date/time of the last deployment in a version.html file I include in the deployment:

https://prod.dlitcjrqaqz64.amplifyapp.com/version.html

Unfortunately, when I try and access the file via my custom domain I get a 404:

https://fp.tickett.net/version.html

I have another Amplify app and am seeing "similar" behaviour (for that app, I am actually seeing an old version of the version.html when using my custom domain, but the current deployment when using the .amplifyapp.com domain).

Any bright ideas?

Many Thanks!

**Comment by hloriana** [comment]
Hi @ltickett 👋🏽 thanks for raising this issue. I'm not sure what caused this behavior but while we investigate, try removing the domain, adding it back, and then redeploy. Please let us know if this unblocks you.

**Comment by ltickett** [comment]
Thanks @hloriana I gave that a try, but it didn't help unfortunately.

I hope you are able to identify the issue your end.

**Comment by hloriana** [comment]
@ltickett I'm seeing a 200 response on your site now. Is it returning the updated `version.html` file?

**Comment by ltickett** [comment]
Nope, still seeing an error though I now realise it's not a 404
![Screenshot_20220810-230900](https://user-images.githubusercontent.com/4687431/184029191-d94d5980-5973-48d2-9432-2cc110f63721.png)

Does this help?

Thanks @hloriana

**Comment by ltickett** [comment]
I just rechecked and now the page is loading and matches between the amplifyapp.com address and fp.tickett.net

So I decided to try deploying a new version...

That is immediately reflected on the amplifyapp.com address, but fp.tickett.net is still showing the old one.

Driving me insane!

**Comment by hloriana** [comment]
Okay yes I can now see that the custom domain and the amplify domain are now showing 2 different versions. We are investigating what is causing the delay.

**Comment by ltickett** [comment]
Really glad you've been able to recreate. I hope I'm not doing something silly.

It seems like a super straightforward config/setup.

Thanks for keeping me in the loop.

**Comment by ltickett** [comment]
Any joy @hloriana ?

I feel like I may have to jump ship soon if we can't figure out what's going on :/

**Comment by Narrator** [comment]
@ltickett Hello! I'm an engineer from the Amplify team.

It looks like you are deploying using a custom URL. We have a known issue with this mechanism and we have a fix for this in the pipeline that should get deployed next week.

Meanwhile, here are some manual workarounds (You won't be able to use your continuous deployment process): 
1. Upload your zip file to S3 and start a build on the Amplify console by providing the details of the S3 bucket.
2. Drag and drop the zip file via the Amplify console

You can read more about these methods by following this link: https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html

**Comment by ltickett** [comment]
Super, thanks @Narrator 

Is this known issue documented publicly? It might have saved me a lot of wasted effort.

Similarly, where can I follow along to see the status of the fix?

Many Thanks

L

**Comment by ltickett** [comment]
@Narrator any progress? Are you still optimistic we'll get this resolved by the end of the week?

Thanks

L

**Comment by ltickett** [comment]
Hi @Narrator - just checking in to see if you have an update please?

**Comment by Narrator** [comment]
@ltickett The fix has been rolled out! Can you please try your deployment now and let us know if there are any issues? Thanks for your patience!

**Comment by ltickett** [comment]
Bad news unfortunately @Narrator 

The issue still seems to exist.

Let me know if you need any further detail.

Thanks

L

**Comment by ltickett** [comment]
It's looking OK now from my laptop (my phone is still showing the access denied message, though works in incognito, so I guess some browser caching might be going on).

I just tried with another Amplify site, and that seems to be working too.

Great job- thank you!
