### ISSUE TITLE
Can "Build" phase be skipped if artifacts are provided by user?

### ISSUE THREAD

**Issue by vatonbero** [aws-amplify/amplify-hosting#2922]
**Please describe which feature you have a question about?**

AWS Amplify

**Provide additional details**

Some users might want to provide prepared artifacts therefore AWS Amplify will not have to provide docker and waste resources. Is there a way to disable entire build step and yust deploy pre-compiled artifacts in AWS Amplify?

**What AWS Services are you utilizing?**

AWS Amplify

**Provide additional details e.g. code snippets**

N/A

**Comment by hloriana** [comment]
Hi @vatonbero you can deploy build artifacts using Manual deploys. You can upload those artifacts to an S3 bucket and trigger a manual deployment or you can also drag and drop a zip file for deployment. Please defer to this [Manual Deploys ](https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html)documentation for step-by-step instructions. Thank you!

**Comment by hloriana** [comment]
Hi @vatonbero currently it's not possible to skip the build step for git based deployments and the only alternative we provide is manual deploys. 

While build containers will be provisioned for CI/CD deployments, you can still save time on builds if you leverage the environment variables that allow you to skip frontend or backend builds when they are set to `true`:

- `PROCESS_SKIP_FRONTEND_DEPLOY` allows you to skip the frontend build
- `AMPLIFY_DIFF_DEPLOY` lets you skip the frontend build if there weren't any changes made to frontend code
- `AMPLIFY_SKIP_BACKEND_BUILD` lets you skip backend build
- `AMPLIF_DIFF_BACKEND` lets you skip building the backend if no changes were detected

I hope these options are viable for your use case.

**Comment by hloriana** [comment]
Hi @vatonbero sorry I missed your last question but yes, you can set environment variables directly in the amplify.yml script or you can also set them via the Amplify Console: https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html
