### ISSUE TITLE
Build is succeeding but intended app is not rendering

### ISSUE THREAD

**Issue by SKYELab** [aws-amplify/amplify-hosting#2925]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d22xc4jv649wi2/main/2?step=PROVISION

### Region

us-west-1

### Amplify Hosting feature

Build settings, Previews

### Describe the bug

AWS Amplify Provision, Build, Deploy and Verify are all green checked. However, when I click on verify it says "Screenshots are temporarily disable, We are aware of the issue and are working on a fix". 

When I try to go to my connected website (hosting on Godaddy, completed all the hosting requisites), the website does not load. 

My code should be okay, I can run the react app locally and on a heroku server. 

### Expected behavior

My website should load. 

### Reproduction steps

A few warnings:

2022-08-12T06:53:24.371Z [WARNING]: npm
2022-08-12T06:53:24.373Z [WARNING]: WARN prepare removing existing node_modules/ before installation
2022-08-12T06:53:53.377Z [WARNING]: Browserslist: caniuse-lite is outdated. Please run:
                                    npx browserslist@latest --update-db
                                    Why you should do it regularly:
                                    https://github.com/browserslist/browserslist#browsers-data-updating
2022-08-12T06:54:18.057Z [WARNING]: !! No index.html detected in deploy folder: 

2022-08-12T06:54:18.057Z [INFO]: # Starting build artifact upload process...
2022-08-12T06:54:51.055Z [INFO]: # Build artifact is: 470MB
2022-08-12T06:54:51.117Z [INFO]: # Build artifact is: 470MB
2022-08-12T06:54:51.119Z [INFO]: # Uploading build artifact '__artifactsHash.zip'...
2022-08-12T06:54:51.150Z [INFO]: # Uploading build artifact '__artifacts.zip'...
2022-08-12T06:54:53.625Z [INFO]: # Build artifact upload completed
2022-08-12T06:54:53.627Z [INFO]: # Starting environment caching...
2022-08-12T06:54:53.627Z [INFO]: # Environment caching completed

**Comment by hloriana** [comment]
Hi @SKYELab can you make sure that your `baseDirectory` is set to the appropriate file path. For example, the `baseDirectory` should be set to `build` in a React application. If the wrong path is given, then a blank screen will appear when you try to access your site.

**Comment by SKYELab** [comment]
Got it thanks! 
Also, how can we gauge just how much AWS hosting will cost. I have some credits - I want an easy way to gauge roughly how much time/customer load that would last. Also, is the cost of hosting on AWS a function or how many customers visit, or how much space my repository is taking (I'm using Github -> Amplify so I'm guessing its not taking up space on my AWS servers or is that a mistake?)

**Comment by Jay2113** [comment]
@SKYELab 👋 , to learn about the AWS Amplify pricing model refer to this documentation: https://aws.amazon.com/amplify/pricing/.

Also, you can utilize the AWS Pricing Calculator to create a cost estimate based on your usage pattern: https://calculator.aws/#/createCalculator/Amplify.
