### ISSUE TITLE
Amplify Studio returns a blank page

### ISSUE THREAD

**Issue by anasnaciri** [aws-amplify/amplify-hosting#2928]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2e0jlrp3fc6qt

### Region

eu-west-2

### Amplify Hosting feature

Backend builds

### Describe the bug

Amplify Studio won't launch, either via the launch studio button in the AWS console or via the CLI, it only opens a new window with a blank page.

On the browser console I get the following errors: 

-Refused to execute inline script because it violates the following Content Security Policy directive: "script-src https://d1fqdzidq79abj.cloudfront.net https://prod.pa.cdn.uis.awsstatic.com https://*.cdn.uis.awsstatic.com/ https://*.cdn.console.awsstatic.com/". Either the 'unsafe-inline' keyword, a hash ('sha256-UOqWu81MIt39ytlVIufO2itF9939P+F/kkVvUqMF7H8='), or a nonce ('nonce-...') is required to enable inline execution.

-Refused to execute inline script because it violates the following Content Security Policy directive: "script-src https://d1fqdzidq79abj.cloudfront.net https://prod.pa.cdn.uis.awsstatic.com https://*.cdn.uis.awsstatic.com/ https://*.cdn.console.awsstatic.com/". Either the 'unsafe-inline' keyword, a hash ('sha256-BASPrZsnv30xRHENt0p9CpqrevJ82KJFj8n87yhCFvo='), or a nonce ('nonce-...') is required to enable inline execution.

-Refused to load the script 'https://eu-west-2.admin.amplifyapp.com/static/js/458.f31c69ad.chunk.js' because it violates the following Content Security Policy directive: "script-src https://d1fqdzidq79abj.cloudfront.net https://prod.pa.cdn.uis.awsstatic.com https://*.cdn.uis.awsstatic.com/ https://*.cdn.console.awsstatic.com/". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

-Refused to load the script 'https://eu-west-2.admin.amplifyapp.com/static/js/main.efcd4bcc.chunk.js' because it violates the following Content Security Policy directive: "script-src https://d1fqdzidq79abj.cloudfront.net https://prod.pa.cdn.uis.awsstatic.com https://*.cdn.uis.awsstatic.com/ https://*.cdn.console.awsstatic.com/". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

### Expected behavior

the normal behavior is to open amplify studio 

### Reproduction steps

1. log into my account
2. navigate to amplify
3. navigate to the app
4. click on launch studio
5. or skip step 2,3 and 4 directly open amplify studio via amplify cli

**Comment by anasnaciri** [comment]
<img width="1440" alt="Screen Shot 2022-08-15 at 21 15 09" src="https://user-images.githubusercontent.com/50685636/184710739-de85cb0f-244c-401b-9e18-4ef61e755ea7.png">

**Comment by hloriana** [comment]
Hi @anasnaciri I'm not seeing this behavior in any of my web browsers. Have you tried this in different browsers?

**Comment by anasnaciri** [comment]
I've tried chrome, safari, and firefox and the issue persisted for the whole day
I deleted cache and cookies, restarted my laptop, and even tried creating some new projects but the issue was always there, whoever amplify studio worked on its own a few minutes now, I don't know where the problem was.

**Comment by hloriana** [comment]
Ok I'll close the issue since it's working now. If the issue arises again please feel free to re-open.
