### ISSUE TITLE
Changing hosting environment from GitHub to Deploy without Git provider

### ISSUE THREAD

**Issue by lien-eckang** [aws-amplify/amplify-hosting#2930]
Hi, 
I am using amplify and having trouble with changing hosting environment.
Currently I am using GitHub to hosting, however, something that I want to do is change to Deploy without Git provider.

I already tried the CLI:
aws amplify update-app --app-id AMPLIFY_APP_ID --repository REPOSITORY_URL --access-token GITHUB_ACCESS_TOKEN

It doesn't work at all and I want to know is there any way to solve it.

Thanks in advance.
![image](https://user-images.githubusercontent.com/107384851/184789605-9e60d32c-a018-4112-9f0c-9b2fd7f12e67.png)
(source: https://www.cloudysave.com/aws/deploy-without-git-provider/)

**Comment by hloriana** [comment]
Hi @lien-eckang currently its not possible to convert from a Git provider app to a manual deploy app or vice versa. We recommend creating a new Amplify app if you want a manually deployed app. Thank you!

**Comment by lien-eckang** [comment]
Thanks hloriana for the reply,

However, do yo have any plan to implement the service in the future?
