### ISSUE TITLE
503 error when fetching an internal NextJS api with query params.

### ISSUE THREAD

**Issue by Nithur-M** [aws-amplify/amplify-hosting#2944]
**Please describe which feature you have a question about?**
I have a problem with internal API routes in NextJS. 

**Provide additional details**
I am trying to fetch data using an internal API with query parameters. The Amplify is not recognizing it and treating it as an URL and throws a 503 error.

The same version of the app deployed on Vercel is working perfectly.

**What AWS Services are you utilizing?**
Amplify.

**Provide additional details e.g. code snippets**
I am using NextJS version 12.

Anyone faced the same issue. Do you have any tips for me?

**Comment by hloriana** [comment]
Hi @Nithur-M we've seen this happen when Access Control is enabled on SSR apps. Do you have Access Control enabled? Also can you use this guide to look for the logs and see if there's any additional information that can help us troubleshoot? https://github.com/aws-amplify/amplify-hosting/blob/main/FAQ.md#access-lambda-edge-logs

**Comment by hloriana** [comment]
Closing due to no response. Please re-open if you continue to face this issue. Thank you.
