### ISSUE TITLE
domain configuration with route 53

### ISSUE THREAD

**Issue by movagroup** [aws-amplify/amplify-hosting#2945]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

https://eu-central-1.console.aws.amazon.com/amplify/home?region=eu-central-1#/dolvo1jqsb8it

### Region

eu-central-1

### Step

Custom Domain setup

### Status

failed

### Issue or question

it should work with one click but it dosent tried many things but still dosent recognises the domain.

**Comment by hloriana** [comment]
Hi @movagroup please provide more details on the issue you are running into so we can assist you:

1. What DNS provider are you using?
2. Have you added all of the DNS records to your custom domain in your DNS provider settings? (ex, CNAME records)
3. Which step of the Custom Domain setup are you stuck at?
4. Can you provide a screenshot of the error you're seeing?

**Comment by hloriana** [comment]
Domain is available and properly hosting the site. Closing this issue as resolved.
