### ISSUE TITLE
Amplify troubleshooting

### ISSUE THREAD

**Issue by Mykykyta** [aws-amplify/amplify-hosting#2954]
Hi, I have a question about how could I better troubleshoot Amplify building process. For now I am facing difficulties while building my code inside of amplify container environment. I am not sure what could be the issue because I can successfully build it locally and it can be succesfully deployed on lambdas manually or I can also succesfully build everything inside of my custom provisioned docker image which I also use in Amplify. The question is in difference between my provisioned docker image and the environment my project is being built in. Are there any ways for me to debug it in more details? To connect to the container somehow? I have noticed it clones repository under the hood and I guess there can be something else to conflict with my packages. Can I somehow disable cloning repository? I would prefer doing it myself to my provisioned docker image without any additional layers I can't see.

![image](https://user-images.githubusercontent.com/32738499/187269285-293e76ba-f956-4451-9aa9-2b46904bbf85.png)

That is the process of deployment itself

![image](https://user-images.githubusercontent.com/32738499/187267302-7cd8704d-96ed-48b4-b3e7-bbf32b01f010.png)

I have no such errors while building locally or inside of the provisioned image I used.

**Comment by Jay2113** [comment]
Hi @Mykykyta 👋 , thanks for reaching out to us and we sincerely apologize for the delayed response on this thread.

If you are still running into this issue, can you please provide us the following information?
- Amplify App ID
- Branch name
- Build # which is failing
