### ISSUE TITLE
Access Log not Accessible

### ISSUE THREAD

**Issue by 0618** [aws-amplify/amplify-hosting#2960]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

all

### Region

all

### Amplify Hosting feature

Logging

### Describe the bug

Not able to get the access log from either console or CLI.

From console, it's the same as https://github.com/aws-amplify/amplify-hosting/issues/1891 , keeps seeing "Fetching Access Logs...".

From CLI, some times get partial logs (not full logs), sometimes get blank file.

### Expected behavior

User should be able to download all the access logs either from console or CLI basing on the chosen time frame.

### Reproduction steps

Console:
follow the access log steps https://docs.aws.amazon.com/amplify/latest/userguide/access-logs.html

CLI:

```sh
aws amplify generate-access-logs --domain-name <DOMAIN-NAME> --app-id <APP-ID> --start-time 2021-08-31T10:59:00Z --end-time 2021-08-31T12:00:00Z
```

**Comment by hloriana** [comment]
Hi @0618 thanks for raising this issue. I was not able to reproduce but the team is investigating this behavior and will provide an update on this issue once this has been root caused.

**Comment by 0618** [comment]
Thanks. The time range in the command was incorrect, which is 2021, but supposed to be 2022.
