### ISSUE TITLE
Amplify redirect of none www to a www

### ISSUE THREAD

**Issue by Innovolved** [aws-amplify/amplify-hosting#2962]
We have an amplify react app setup. 

I created a none www redirect to a www. under the rewrites and redirects section. 
Its not working and directing to a - HTTP Error 404. The requested resource is not found.

Can you please assist and resolve soonest.

**Comment by hloriana** [comment]
Hi @Innovolved can you provide your app ID and a screenshot of the network logs in your developer tools when requesting the source URL for the redirect? 

We will need to see how your redirects are setup to determine the cause of this behavior.

**Comment by Innovolved** [comment]
Hi, 
apps/d2p7alcwhtixib

![image](https://user-images.githubusercontent.com/1861121/188214658-5d11b9cc-837a-4755-9d8d-0b233098d9fd.png)

**Comment by Innovolved** [comment]
Hi @hloriana, [hloriana](https://github.com/hloriana)
Any update regarding this redirect item ?

**Comment by Innovolved** [comment]
> Hi @Innovolved can you provide your app ID and a screenshot of the network logs in your developer tools when requesting the source URL for the redirect?
> 
> We will need to see how your redirects are setup to determine the cause of this behavior.

Herewith is the APP ID : apps/d2p7alcwhtixib

**Comment by Innovolved** [comment]
Hi, 
Any update regarding this ????
Its been 11 days with no response !!!
Herewith is the APP ID : apps/d2p7alcwhtixib

@hloriana @hloriana @hloriana @hloriana @hloriana @hloriana @hloriana

**Comment by Innovolved** [comment]
Please @hloriana !!!
Reply and resolve soonest. I'm beginning to think that this support platform is useless to aws (amazon). 
My migration is loosing SEO results because of this simple redirect that aws CANT get correct. I added more redirects and they are all not working. Check asap and reply soonest !!!!

@hloriana @hloriana @hloriana @hloriana @hloriana @calavera @kevinold @ErikCH 

> Hi @Innovolved can you provide your app ID and a screenshot of the network logs in your developer tools when requesting the source URL for the redirect?
> 
> We will need to see how your redirects are setup to determine the cause of this behavior.

**Comment by hloriana** [comment]
Hi @Innovolved my sincerest apologies for the delay in response. The team is working on improving visibility and response times across this platform to provide better customer experience and help resolve these issues in a timely fashion. 

Your root domain redirect to `www` appears to be working now. I've provided a response on this issue https://github.com/aws-amplify/amplify-hosting/issues/2977 as well. Please respond to #2977 if you are continuing to experience this problem. I will be watching that issue closely for an update from you. Thank you!

**Comment by Innovolved** [comment]
Hi @hloriana, this support platform is useless. Please close it down as aws should not be referenced to a platform that claim support and does not support.
