### ISSUE TITLE
Access Log Download button needs a debouncer

### ISSUE THREAD

**Issue by 0618** [aws-amplify/amplify-hosting#2965]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

all

### Amplify Hosting feature

Logging

### Describe the bug

The download button didn't work at first, so I clicked it multiple times, then it downloaded multiple times....

![Pasted_Image_9_4_22__16_36](https://user-images.githubusercontent.com/11983489/188337911-f1c9a30f-8fa5-411a-99b8-d996428a6d78.png)

### Expected behavior

The button should be disabled when unavailable. And it should has a debouncer to prevent sending too many request if the user clicks too frequenctly.

### Reproduction steps

1. go to Amplify Console, monitoring
2. click "Access logs" tab
3. click "Download" button

**Comment by hloriana** [comment]
Hi @0618 👋🏽 I just tested this out but was not able to reproduce the behavior. The download button should be grayed out until the logs become available for download. Here is a screenshot of what you should see: 
![Screen Shot 2022-09-15 at 6 03 44 PM](https://user-images.githubusercontent.com/76065904/190523807-32915408-135a-45b1-b5d9-0d785d891754.png)

**Comment by 0618** [comment]
It was greyed out (disabled), but when it's enabled again, the issue mentioned above happened.

**Comment by Jay2113** [comment]
Hi @0618 👋 , thanks for your continued patience and we apologize for the delayed response on this thread. 

I performed a few tests both in the Firefox and Chrome browsers and was unable to reproduce this behavior. Can you please confirm if you are still running into this issue with the `Download` button in the `Monitoring` section of the Amplify Console?

If yes, can you please provide us a [HAR capture](https://repost.aws/knowledge-center/support-case-browser-har-file) of it as it will help us understand the API requests and its corresponding responses?
