### ISSUE TITLE
Amplify redirect of none www to a www

### ISSUE THREAD

**Issue by Innovolved** [aws-amplify/amplify-hosting#2977]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

APP ID : apps/d2p7alcwhtixib

### Region

Ohio

### Step

Added to app routing

### Status

Configure success

### Issue or question

I created a none www redirect to a www. under the rewrites and redirects section.
Its not working and directing to a - HTTP Error 404. The requested resource is not found.
Herewith is the APP ID : apps/d2p7alcwhtixib

**Comment by hloriana** [comment]
Hi @Innovolved 👋🏽 thanks for providing details regarding this issue. I checked your root domain and it appears that the redirect to the `www` subdomain is working properly. Can you please confirm that you are able to see this on your end?
