### ISSUE TITLE
Deployment/Build/webpack

### ISSUE THREAD

**Issue by harv45678** [aws-amplify/amplify-hosting#2979]
**Which Specific Feature is your question related to?**
I've created an app using create-react-app and locally when I do "npm run build" it creates the correct webpack files for every js/jsx file in my src directory but when I deploy it to amplify via github it only creates a main.hash.js file and all of the other src files are untouched and viewable.
how do I get amplify to do a full build?

**Provide additional details e.g. code snippets**

**Comment by letsbelopez** [comment]
Transferring to hosting because customer is having building the app during hosting deployment.

**Comment by hloriana** [comment]
Hi @harv45678 👋🏽  Apologies for the delay in response here. If you're still running into this problem, please open a new issue with the [bug report](https://github.com/aws-amplify/amplify-hosting/issues/new?assignees=&labels=bug%2Cpending-triage&template=1.bug_report.yaml) template. That will give us the information we need to understand why your builds are failing. Thank you!
