### ISSUE TITLE
Deploying a NextJS SSR app creates new CloudFront distribution instead of using existing one (since September 9th)

### ISSUE THREAD

**Issue by StephaneBischoff** [aws-amplify/amplify-hosting#2982]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1y5airyx8txqb

### Region

ca-central-1

### Amplify Hosting feature

Not applicable

### Describe the bug

Usually, when deploying a new version of Amplify website, the existing CloudFrount distribution is used and updated. This has been the behavior for the past 9 months.

But since September 9th, when I deploy a new version of my Amplify website, it creates a new CloudFront distribution every time.
My production live website is not updated since the old distribution is not updated. 

Why this change in behavior? 
Is this a bug or expected?

Furthermore, email notifications for Amplify also stopped working today... Not sure if its a new Amplify build that brought in bugs.

Thanks

### Expected behavior

- Existing CloudFront distribution should be used and updated when deploying Amplify website. (Past behavior)
- Email notification should continue to work

### Reproduction steps

1- Deploy a Amplify website with an existing Cloudfront distribution 
2- Notice that a new Cloudfront distribution is created.
3- Redeploy a change
4- A 3rd Cloudfront distribution is created

### Build Settings

```yaml
N/A
```

### Additional information

N/A

**Comment by dansokol** [comment]
What was the resolution for this one?  I'm having the same issue

**Comment by zhynroman** [comment]
I am having the same issue. The app is in ca-central-1 region and each new build and deployment creates a new CloudFront distribution since the Sep 9.

@StephaneBischoff  Could you please share what what the fix that helped you to resolve this?

**Comment by StephaneBischoff** [comment]
Hi @dansokol @zhynroman 

Unfortunately, I was no able to resolve this issue. In our staging environment, AWS Amplify deployed correctly and updated the correct CloudFront distribution. But, in Production this was not the case. 

I decided to move everything to Vercel. It took me half a day. Furthermore, I was able to update my NextJS application to the latest version. So it was win-win. 

Best of luck.

**Comment by aungbobotun** [comment]
@palpatim   @mauerbac  @manueliglesias . This issue is urgent. Plz we are also facing the issue. At least reply on this

**Comment by costerman** [comment]
This is an urgent issue for my team as well.  A new Cloudfront distribution is being created on each build as well as a URL Rewrite in Amplify Console.  This started for us early this morning (3:26am ET).

**Comment by Jay2113** [comment]
@costerman @aungbobotun @zhynroman @dansokol can you provide us your Amplify app id?

**Comment by dansokol** [comment]
> @costerman @aungbobotun @zhynroman @dansokol can you provide us your Amplify app id?

@Jay2113 app id: d2lw9gp91e6yf1

I also opened an issue for this: https://github.com/aws-amplify/amplify-hosting/issues/2987

**Comment by costerman** [comment]
@Jay2113 `d7rf8fcnzpljj`

Also noticed lambda's also getting created with each build.  Seems like Amplify is behaving like its the first time run on each build, provisioning new resources each time instead of reusing existing resources it has already provisioned.

**Comment by arundna** [comment]
@costerman, @dansokol  - Thank you for providing the AppId's. We're looking at the issue with priority and will keep you posted with an update shortly.

**Comment by aungbobotun** [comment]
@arundna @Jay2113   I think it's not related to the APP ID because I have created multiple apps with different AWS accs, it's happening all over the AWS. [APP_ID: `d26o7rkrg9pon6`]. Thx for the support

**Comment by fevega1** [comment]
Facing the same issue @Jay2113, appreciate it if you could also check these apps `d1gea2s40al8l0`  and `d25ldgknre5sp`

**Comment by Jay2113** [comment]
Thanks for providing that information. This is currently our highest priority and we are actively working on root causing this issue.

**Comment by hloriana** [comment]
@StephaneBischoff @fevega1 @dansokol @costerman Apologies for this inconvenience. New deployments of your app should no longer create new SSR resources in your account (CloudFront distribution, Lambda@Edge functions, S3 buckets). The resources created with your last deployment will be used for future builds.

If you are using custom domains, we are actively working on a solution for having your custom domains serve the latest content. We are treating this with high priority and we'll keep you posted with an update.

Thank you all for your patience.

**Comment by Jay2113** [comment]
Please perform the following steps on your Amplify app to ensure that your custom domains are serving the latest content:
- In the Amplify Console, navigate to `App settings` -> `Domain management`
- Select the `Manage subdomains` button -> ⚠️ DO NOT MAKE ANY CHANGES to this section
- Click on the `Update` button

Once the domain update process has completed, navigate to your custom domains in the browser and they should now serve the latest content.

**Comment by multivoltage** [comment]
@Jay2113 I confirm that this "trick" does not work for me. "Update" button stays on "loading" state also after 30 minutes. No changes in the site.

**Comment by Jay2113** [comment]
@multivoltage can you provide us your Amplify app id?

**Comment by multivoltage** [comment]
Yes. d2skhgz4a0rx0t
20 minutes ago I tried to remove and attach staging branch without results.

**Comment by Jay2113** [comment]
@multivoltage I reviewed your app configuration and can you try the following steps:
- Remove/Delete the staging-test.conio.com custom domain from your app `d2skhgz4a0rx0t` which is currently associated to your staging branch.
- Wait for the domain removal process to complete in the Amplify console.
- Re-connect the staging-test.conio.com custom domain to your staging branch.

You should then be able to see the latest content being served on both the domains (.amplifyapp.com and your custom domain for staging branch).

**Comment by HarrisonJackson** [comment]
We've been seeing this issue. Manually running the subdomain update did get the latest deployment showing so that is good. Will we need to do that each time now or should that resolve the issue going forward?

@Jay2113 will we need to manually cleanup the extra resources that have been created? Trying to avoid any unexpected charges but also don't want to manually remove any resources and then cause automated updates to fail / lock the builds forever. Thanks

**Comment by multivoltage** [comment]
I tried it. Also removed staging branch. Tomorrow I will retry

**Comment by multivoltage** [comment]
@Jay2113 We tried these 3 steps. I have to add an extra step (commit sometings on staging). Now seems to work (I probably do a check for future commit to check if bug is fixed). My deploy log is:
```
2022-09-23T09:46:22 [INFO]: Starting Deployment
2022-09-23T09:46:22 [INFO]: Updating Edge config
buildId 0000000002
2022-09-23T09:46:23 [INFO]: Got archive: 19412466 bytes
2022-09-23T09:46:26 [INFO]: Deployment complete
```

Others times this log show us all resource created for deploy

**Comment by croossin** [comment]
@hloriana Any ETA/updates on a permanent fix? This is plaguing each of our amplify builds. This seems to be a somewhat major issue.

**Comment by hloriana** [comment]
Hi @croossin 👋🏽 We apologize for the inconvenience. Your builds should not be creating new CloudFront distributions. Please provide your App ID so we can investigate why this issue is occurring for your app.

**Comment by raphaelmelo** [comment]
Facing the same issue @Jay2113, appreciate it if you could also check these apps id=d32znhus06x42m region=sa-east-1

**Comment by mittatvasoft** [comment]
Any update on this issue ?
Recently I tried migrating next JS 11 to 12

from the console these were the final logs (of deploy stage)
2023-03-07T06:53:33 [INFO]: Beginning deployment for application <MY_APP_ID>, branch:release/dev, buildId 0000001388
2023-03-07T06:54:02 [INFO]: Deployment complete.

However, When I checked after clearing cache
changes were not reflecting. hence build was not updated

**Comment by hloriii** [comment]
@mittatvasoft I was not able to reproduce this behavior when migrating to Next.js 12. After migration, your application should be displaying updated content. If you are running into any issues with the migration please open a new issue with bug report template so that we can provide you assistance. Thank you!
