### ISSUE TITLE
Next.js app syncing with database on local but not when deployed.

### ISSUE THREAD

**Issue by yashsavalia1** [aws-amplify/amplify-hosting#2984]
I am using a Next.js app and on my localhost, I can create posts for which I have a model for in Amplify's backend read from aws. These changes are synced with the Amplify console. When I deploy it however, it returns an empty array of posts and creating a post will temporarily add the post to the site and can be viewed by different users but the post does not show up in the Amplify console and disappears after a minute or 2. 

I am using Amplify backend with API, Auth and File Storage added. I used the Amplify CLI to pull my changes from AWS. I called `Amplify.configure(awsExports);` in my _app.tsx file.

I am not sure what my issue is necessarily, so any help is appreciated.

**Comment by hloriana** [comment]
Hi @yashsavalia1 👋🏽 thanks for reaching out for assistance. Can you confirm that the newly created posts are being properly added to the file storage resource? Also if you could share a sample repo that reproduces the error or even snippets of your code where new posts are being created that would be helpful. If you want to send this information privately, you can send it to aws-amplify-customer@amazon.com.
