### ISSUE TITLE
Deleted amplify studio UserPool

### ISSUE THREAD

**Issue by mahadbajwa97** [aws-amplify/amplify-hosting#2998]
My team mate mistakenly deleted the user pool used to login into amplify studio. Is there a way to artificially create a UserPool and associate with amplify studio

**Comment by hloriana** [comment]
Hi @mahadbajwa97 sorry you accidentally deleted the user pool. You can import an existing user pool into your Amplify application either through the CLI or using Amplify Studio. Please refer to the following documentation for further guidance:

- [Import Amazon Cognito Resources](https://docs.amplify.aws/console/auth/import/),
- [Use an existing Cognito User Pool and Identity Pool](https://docs.amplify.aws/cli/auth/import/)
