### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by SpruceVedant** [aws-amplify/amplify-hosting#3000]
I am trying to deploy my node  web-app on AWS amplify hosting services. After configuring amplify.yml , the web-app is serving the frontend but it doesn't start the node server  which is the entry-point(index.js) of the application as specified in the package.json file.
I am using snowpack as a build tool.

Here's my directory structure
![Screenshot 2022-09-21 221324](https://user-images.githubusercontent.com/76097198/191565851-47ad6370-662f-4488-af4d-450da42b521f.png)

Here's amplify.yml
![Screenshot 2022-09-21 222009](https://user-images.githubusercontent.com/76097198/191566165-ef4959ac-4d33-4ffa-a819-853670472ed9.png)

**Comment by hloriana** [comment]
Hi @SpruceVedant 👋🏽 thanks for raising this issue. What framework are you using for your application? Please provide your App ID so we can get a better understanding of the issue and provide you with next steps. Thank you!

**Comment by SpruceVedant** [comment]
Hey, I am using express as a framework.
Here is my App id: d1xdmz2t46v25v

**Comment by SpruceVedant** [comment]
> Hi @SpruceVedant 👋🏽 thanks for raising this issue. What framework are you using for your application? Please provide your App ID so we can get a better understanding of the issue and provide you with next steps. Thank you!

Hey , I am using express.
Here is my AppId - d1xdmz2t46v25v

**Comment by hloriii** [comment]
Apologies for the oversight here. To support your Express app as part of the backend environment for your application, you can follow this documentation to setup to **Deploy an** [Express](https://expressjs.com/) **web server** using the Amplify CLI. If you have any further questions, please feel free to open a new issue and we will be happy to help you.
