### ISSUE TITLE
customeHttp.yml doesn't show up on console

### ISSUE THREAD

**Issue by 0618** [aws-amplify/amplify-hosting#3001]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2xpdt70dla3di

### Region

us-east-1

### Amplify Hosting feature

Custom headers

### Describe the bug

I added the customHttp.yml file to my repo. Looks like it works in the app, but I see an empty box on the console

![image](https://user-images.githubusercontent.com/11983489/191611280-da5f00a9-426f-41fb-8df2-b656b63acb60.png)

### Expected behavior

The file box should show the customHttp.yml file

### Reproduction steps

1. add a customHttp.yml file with some header to the app's root file
2. deploy the app
3. see the header changes in the app
4. Amplify console --> Custom Headers. It's blank

**Comment by hloriana** [comment]
Hi @0618 👋🏽 There are two methods of adding custom headers to your Amplify application. You can do so via the console and also by adding a `customHTTP.yml` file to the root of your repository as you have mentioned. 

Adding the `customHTTP.yml` will not change the code in Custom Headers settings in the console. If you happen to have different settings in the console and in your file, then the `customHTTP.yml` will take precedence. You can read more about setting custom headers[ here](https://docs.aws.amazon.com/amplify/latest/userguide/custom-headers.html#setting-custom-headers).
