### ISSUE TITLE
CORS issues on Amplify hosting in us-east-1 making Amplify unusable

### ISSUE THREAD

**Issue by giovannetti-eric** [aws-amplify/amplify-hosting#3008]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-east-1

### Amplify Hosting feature

Manual deploys

### Describe the bug

When I click on the "Redeploy this version" when I'm into an Amplify branch of a project, nothing happen, in the console, I have these logs:

`POST https://amplify.us-east-1.amazonaws.com/apps/xxx/branches/master/jobs net::ERR_FAILED 403`

`Access to XMLHttpRequest at 'https://amplify.us-east-1.amazonaws.com/apps/xxx/branches/master/jobs' from origin 'https://us-east-1.console.aws.amazon.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

`NetworkingError: Network Failure
    at XMLHttpRequest.<anonymous> (vendors~main.js:99:417967)
main.js:1 key: message
main.js:1 Network Failure
main.js:1 key: code
main.js:1 NetworkingError
main.js:1 key: time
main.js:1 Tue Sep 27 2022 14:39:08 GMT-0400 (Eastern Daylight Time)
main.js:1 key: region
main.js:1 us-east-1
main.js:1 key: hostname
main.js:1 amplify.us-east-1.amazonaws.com
main.js:1 key: retryable`

A lot of others features have CORS issues (settings hook, editing config, etc.)

### Expected behavior

Fix the CORS issues

### Reproduction steps

1. Go to Amplify
2. Select a project
3. Select a branch
4. Click on the "Redeploy this version" button

### Additional information

![Screen Shot 2022-09-27 at 14 47 16](https://user-images.githubusercontent.com/264842/192610739-a115f956-8818-4a1a-b156-4e41c5e2d84a.png)

**Comment by hloriana** [comment]
Hi @giovannetti-eric 👋🏽 we are currently investigating this issue however we are not able to reproduce this behavior on our end. Can you confirm if this is happening in multiple apps? Are you able to run a successful deployment by pushing a commit to the repository?

Please provide your app ID so we can further investigate why this behavior is occurring for you.
