### ISSUE TITLE
Can custom-domain subdomain swapping be used as a form of rollback or blue/green?

### ISSUE THREAD

**Issue by jag-ermeister** [aws-amplify/amplify-hosting#3023]
Hello!

We currently use Amplify for our frontend React/Next.js app and Elastic Beanstalk for our backend.  A feature that we love in Elastic Beanstalk is that it enables blue/green deployment and zero-downtime rollbacks by providing url-swapping functionality: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.CNAMESwap.html

In Amplify, we have configured a custom domain for our frontend app and we utilize several different subdomains that point at our various branches.  After checking out the `Domain Management > Manage Subdomains` screen in Amplify, I am wondering if this same sort of blue/green/rollback functionality could be achieved?

For example, if we have the following configured:
- Subdomain: www, Branch: main
- Subdomain: www2, Branch: dev

...then could we, for example push a new version of our code to the `dev` branch, and then simply reassign our `www` subdomain to the dev branch?  Then, if we discovered an issue, we could rollback by reassigning the `www` subdomain to the `main` branch.  

Hopefully this question makes sense.  I imagine that there may be some CDN cache-busting issues that prevent this solution from being reasonable, but I'm curious to hear thoughts from the experts!

Thank you!

**Comment by hloriana** [comment]
Hi @jag-ermeister 👋🏽  

For each subdomain you add, the dropdown will list all of the branches you have deployed so you can select which branch you want it to point to. If you pushed a change to dev, you could point `www` to the dev branch by selecting `dev` from the dropdown menu. After saving you should be able to confirm the `www` subdomain is pointing to `dev` when navigating to that URL in the browser. Similarly, if the changes pushed to dev are undesirable, you could point the `www` subdomain back to `main` using the same method. 

<img width="688" alt="Screen Shot 2022-10-05 at 5 44 22 PM" src="https://user-images.githubusercontent.com/76065904/194178485-d9bbc199-b27d-42eb-9e2b-2b565f1c2b1b.png">

I tested this in my account and the changes took affect rather quickly. So yes, this should work. Thanks for reaching out!

**Comment by jag-ermeister** [comment]
Great, thanks for confirming!
