### ISSUE TITLE
Amplify serving .wasm with text/html content type

### ISSUE THREAD

**Issue by krflol** [aws-amplify/amplify-hosting#3029]
As it says above.
`Unexpected error in loadWasm. [Message: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.]`

In the request, text/html it shown as the content type.

**Comment by hloriii** [comment]
Apologies for missing this. For anyone who runs into this error in the future, please open a new issue with the [bug report](https://github.com/aws-amplify/amplify-hosting/issues/new?assignees=&labels=bug%2Cpending-triage&template=1.bug_report.yaml) template and we will assist you. Thank you!
