### ISSUE TITLE
Allow update git repository's name

### ISSUE THREAD

**Issue by hoan-pham-duy** [aws-amplify/amplify-hosting#3037]
### Is this related to another service?

Connect Repository

### Describe the feature you'd like to request

When I tried to rename my GitHub repository, I couldn't continue working with the current AWS Amplify app.
I need to delete old environments and create new ones.
That is inconvenient and it would be better if we had the option to update the git repository's link.

### Describe the solution you'd like

Config dynamic git repository's link in AWS Amplify's app for environments.

### Describe alternatives you've considered

- Design tools in Web Browser to synchronize data between old environments and new environments between AWS applications.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by hloriana** [comment]
Hi @hoan-pham-duy 👋🏽 you can update your repository via the AWS CLI by running this command:

`aws amplify update-app --app-id <value> --repository <value> --access-token <value>`

Please refer to the command documentation for additional information: https://docs.aws.amazon.com/cli/latest/reference/amplify/update-app.html
