### ISSUE TITLE
Add permissions boundary support to amplifyPush

### ISSUE THREAD

**Issue by spavuluri** [aws-amplify/amplify-hosting#3041]
amplify cli introduced support for providing permissions boundary for roles generated by Amplify using the `--permissions-boundary` option during `init`, `env add` or `env update`.
As noted here - https://docs.amplify.aws/cli/project/permissions-boundary/

Can [amplifyPush](https://github.com/aws-amplify/amplify-hosting/blob/main/scripts/amplifyPush.sh) extend this support so that hosted applications can make use of it?

Thank you.

**Comment by Narrator** [comment]
Hello! We already support this via the `AMPLIFY_PERMISSIONS_BOUNDARY_ARN` environment variable. Please have a look at: https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#amplify-console-environment-variables

Can you also share your build spec please? Thank you!
