### ISSUE TITLE
AWS Tutorial: Build a Basic Web Application - Fails on Last Step

### ISSUE THREAD

**Issue by merlinmarch** [aws-amplify/amplify-hosting#3045]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d23r6yopbmlw3t

### AWS Region

eu-west-2

### Amplify Hosting feature

Deployments

### Describe the bug

Hi,

I have completed the tutorial AWS - Build a Basic Web Application (https://aws.amazon.com/getting-started/hands-on/build-web-app-s3-lambda-api-gateway-dynamodb/) multiple times, and I am getting the same error on the very last step. When I 'test the updated web app' by entering a First Name, Last Name, then clicking 'Call API', I get the following pop-up:

![image](https://user-images.githubusercontent.com/98752089/197195468-a58cc4d8-3100-4ab3-837a-1dad2c871a44.png)

The First Name and Last Name are appearing in the DynamoDB table as an item, with the correct timestamp, so part of the call to the API appears to be working. However the message 'Hello from Lambda' followed by the text I filled in is not appearing in the browser.

I am new to this discipline so would welcome a solution! Why am I getting this pop-up and not the desired output?

Thanks.

### Expected behavior

On clicking 'Call API' in the browser, I expect the browser to show a message that starts with Hello from Lambda followed by the text I filled in, as described in the very last step of the tutorial.

### Reproduction steps

I carefully followed the tutorial.

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriana** [comment]
Hi @merlinmarch 👋🏽 apologies for the inconvenience. I visited your website and was able to view the "Hello from Lambda" response. We will update the tutorial to address any potential gaps.
