### ISSUE TITLE
Custom domain issue

### ISSUE THREAD

**Issue by yinxiangshi** [aws-amplify/amplify-hosting#3056]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2qb4xwieziuir

### AWS Region

us-west-2

### Amplify Hosting feature

Not Applicable

### Describe the bug

I deployed my site using amplify a few days ago and bound my domain name (allonsygamma.com) in router53, then I reported the problem in GitHub. The next day, in my aws, my previous app disappeared. Today I tried to open a new app with my personal domain name and I got an error: 

Error message: [CNAMEAlreadyExistsException] The following CloudFront distributions or Amplify Apps are already using one or more of your domains: [Distribution: *******J7CH77T in AWS Account: ******171576, Distribution: *******J7CH77T in AWS Account: ******171576].

### Expected behavior

Bind domain to my new app.

### Reproduction steps

none

### Build Settings

```yaml
none
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by asnoba** [comment]
I keep getting this issue too. Can assign my domain to a new app after the old one was deleted. I tried a few times during the last couple of days.

**Comment by nategoethel** [comment]
I had to update my existing CNAME records to point to the `*.amplifyapp.com` domain of my new app. From there, Amplify gave me new CNAME records to swap in in my DNS. After that I just had to wait for DNS records to propagate.

**Comment by yinxiangshi** [comment]
> I had to update my existing CNAME records (from the old app) to point to the `*.amplifyapp.com` domain of my new app. From there, Amplify gave me new CNAME records to swap in in my DNS. After that I just had to wait for DNS records to propagate.

If your old APP is existing, you can solve this issue. But mine does not exist.

**Comment by nategoethel** [comment]
> > I had to update my existing CNAME records (from the old app) to point to the `*.amplifyapp.com` domain of my new app. From there, Amplify gave me new CNAME records to swap in in my DNS. After that I just had to wait for DNS records to propagate.
> 
> If your old APP is existing, you can solve this issue. But mine does not exist.

My app did not exist at the time.

**Comment by yinxiangshi** [comment]
> > > I had to update my existing CNAME records (from the old app) to point to the `*.amplifyapp.com` domain of my new app. From there, Amplify gave me new CNAME records to swap in in my DNS. After that I just had to wait for DNS records to propagate.
> > 
> > 
> > If your old APP is existing, you can solve this issue. But mine does not exist.
> 
> My old app did not exist at the time.

In my router 53, I have 2 CNAME, did you change all your CNAME?

**Comment by nategoethel** [comment]
Yes, I had to change all related CNAME records.

**Comment by yinxiangshi** [comment]
> Yes, I had to change all related CNAME records.

I will take a try, thx!

**Comment by hloriana** [comment]
Hi @yinxiangshi the app that your custom domain is currently connected to still exists. When you say the app "disappeared" did you attempt to delete the app or is it just not visible in the console? We can see on our end that your app still exists and is still connected to the custom domain. Try running `aws amplify list-apps` to see if you are able to still interact with that application.

**Comment by yinxiangshi** [comment]
> Hi @yinxiangshi the app that your custom domain is currently connected to still exists. When you say the app "disappeared" did you attempt to delete the app or is it just not visible in the console? We can see on our end that your app still exists and is still connected to the custom domain. Try running `aws amplify list-apps` to see if you are able to still interact with that application.

Hi, I didn't delete the app. In my dashboard, I can only see an app named "homepage"

**Comment by yinxiangshi** [comment]
> Hi @yinxiangshi the app that your custom domain is currently connected to still exists. When you say the app "disappeared" did you attempt to delete the app or is it just not visible in the console? We can see on our end that your app still exists and is still connected to the custom domain. Try running `aws amplify list-apps` to see if you are able to still interact with that application.

I just find that my old app appears, and my new app disappears...
