### ISSUE TITLE
git log no longer returns full history in post build script

### ISSUE THREAD

**Issue by mgalanos** [aws-amplify/amplify-hosting#3057]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d32esl1el8cxwx

### AWS Region

us-east-2

### Amplify Hosting feature

Frontend builds, Git providers

### Describe the bug

We have a script that runs after the FE build is complete to generate a version number that will be used for the application.
A component of this version number is based on the number of commits and uses the following command:
'git log --oneline | wc -l'

This has been working for years but suddenly stopped working. Based on our recent releases it seems that this stopped working somewhere between 10/17 and 10/19.

Instead of returning the correct number of commits, it is always returning 1. "git log" only show the current commit and nothing prior.

### Expected behavior

It is expected that 'git log --oneline | wc -l' continue to return the number of commits as it had been prior to 10/19.

### Reproduction steps

Create a script that runs the command  'git log --oneline | wc -l' 
Ensure there are more than 1 commits on the deployed branch
print out the result of the above command. 

### Log output

Below is a snippet of the build log from 10/17 that shows the version number <number of commits>.<sha of current commit>
```
# Put your logs below this line
2022-10-18T01:21:01.901Z [INFO]: Update version number:  871.37c23db0


```
And below is a snippet of the build log from 10/19 that shows the incorrect version
2022-10-20T01:38:14.414Z [INFO]: Update version number:  1.7bc9c72

**Comment by ferdingler** [comment]
Hi @mgalanos , thank you for reaching out. All the details are very much appreciated as it helps us understand your use case. We are indeed making improvements to our build service in the interest of making builds faster, and one of the recent changes was to limit the depth of the git clone so that we don't spend time pulling old code unnecessarily. I'm sorry this affected the way you generate a version number for your application. Have you considered using the commit ID as version number instead? Or perhaps doing a `git fetch origin` yourself within your buildspec commands?

**Comment by mgalanos** [comment]
@calavera @ferdingler Thank you for the quick and detailed reply! I have been able to get this working again based on your input.
