### ISSUE TITLE
Failed to load url

### ISSUE THREAD

**Issue by fyenw** [aws-amplify/amplify-hosting#3068]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-2:222795186790:apps/d2yju30z7d966a

### Region

ohio

### Step

Failed to load url

### Status

Failed to load url

### Issue or question

Hello, I have gone through all of the provision, build and deploy steps, connected my github and connected my domain, but I can't see anything online when I search the domain name, it just says "site can't be reached" or opens names.co.uk where I bought the domain name from depending on whether I click the link in the AWS app or search it myself. I really need this site live today. Please help ASAP

### Error message

Failed to load url: https://www.nirannatalie.com/ 401

**Comment by hloriana** [comment]
Hi @fyenw 👋🏽 I just tried visiting your site and was able to see the access control prompt to view the website for both the custom domain URL and the `<branch>.<appID>.amplifyapp.com` URL. Has this issue resolved for you over the weekend? If not, it would be helpful if you could provide an HAR capture or screenshot of the errors you are seeing. Thank you!
