### ISSUE TITLE
AWS amplify log groups

### ISSUE THREAD

**Issue by Titi-layo** [aws-amplify/amplify-hosting#3073]
I can see that Amplify provides some logs in the monitoring tab of the amplify console. Was wondering if it also generates log groups which can be accessed via cdk. Aim is to pass these logs to a third party monitoring/observability tool

**Comment by hloriana** [comment]
Hi @Titi-layo 👋🏽 currently we only supply access logs via the Amplify console and also through the AWS CLI command `aws amplify generate-access-logs`: https://docs.aws.amazon.com/cli/latest/reference/amplify/generate-access-logs.html which will return a url that you can visit to download the log data. We do not have a method for customers to access log groups at this time.
