### ISSUE TITLE
Sucessfully deployed NextJS app don't show in amplifyapp.com url

### ISSUE THREAD

**Issue by gabrielizalo** [aws-amplify/amplify-hosting#3075]
**Please describe which feature you have a question about?**

- Amplify Hosting for NextJS is not working.

**Provide additional details**

- I have a successfully deployed NetxJS app as you can see in this image:
![PEzEauX4le](https://user-images.githubusercontent.com/656353/199621409-005c2715-3004-4f95-a3eb-0b0b15524834.png)

- But the AmplifyApp URL shows a 404 error: https://master.d3j6nnrg9voe17.amplifyapp.com/

**What AWS Services are you utilizing?**

- Amplify Hosting

**Provide additional details e.g. code snippets**

- N/A

**Comment by hloriana** [comment]
Hi @gabrielizalo we apologize for the delay in assistance on this issue. If you run into this problem again please feel free to open a new issue and we will promptly assist.
