### ISSUE TITLE
Auto delete old builds

### ISSUE THREAD

**Issue by imdkbj** [aws-amplify/amplify-hosting#3077]
**Is your feature request related to a problem? Please describe.**
We have to manually delete the old build to clear the amplify storage by using the command line `aws amplify delete-job --app-id xxxxxxx --branch-name dev --job-id 1` or `#!/bin/bash
for i in {411..440}
do
aws amplify delete-job --app-id xxxxx --branch-name dev --job-id $i
done`

**Describe the solution you'd like**
There should to option like as Keep last N build or Auto delete build in N days. Or we should have a option to select and delete builds visually from the amplify console.

**Comment by michrome** [comment]
Hi @imdkbj and thanks for the suggestion. Rolling out now, **storage charges for build outputs** apply to the app's last 3 builds only.

**Comment by imdkbj** [comment]
> Hi @imdkbj and thanks for the suggestion. Rolling out over the coming weeks, **storage charges for build outputs** apply to the app's last 3 builds only.


_That's very sweet of you. Well, still i believe that old build should to get deleted as these consume unnecessary space for AWS as well as owner. Amplify should have default options  as suggested or something like that._

**Comment by swaminator** [comment]
This feature has been rolled out.
