### ISSUE TITLE
Build stopped deploying to AWS amplify

### ISSUE THREAD

**Issue by ParulSharma2622** [aws-amplify/amplify-hosting#3078]
We have deployed our white label React based applications using AWS Amplify. We update build very frequently and it take almost 5-6 minutes to complete a build.

But my builds have stopped deploying to the server today and I don't understand what could be the issue.

Please clarify what could be the reason for this. Our application is in production and we are concerned if something is wrong with our setup.

Here is the app details :
App Id : dodkejkakumhf
App region : ap-southeast-2

I am attaching a screenshot for your reference.

![Screenshot_24](https://user-images.githubusercontent.com/69511562/199689173-9efec069-b3f7-449f-83d1-aa7b418a878d.png)

Thanks,

**Comment by hloriana** [comment]
Hi @ParulSharma2622 👋🏽 it looks like an AppSync API key is missing. Is it possible that the API key has been deleted recently? Also, try running `amplify push` locally to confirm that your backend environment can be properly updated.

**Comment by ParulSharma2622** [comment]
Hi, thanks for your comment. Please check the attached screenshot to see what error I am facing when I run amplify push
![Screenshot_28](https://user-images.githubusercontent.com/69511562/200167972-ce106b3b-295b-48cb-af49-b0dac831020d.png)

**Comment by ParulSharma2622** [comment]
@hloriana are you still looking into this bug. It's critical, we are not able to deploy the code on production envs.

**Comment by ParulSharma2622** [comment]
This is resolved, thanks.
