### ISSUE TITLE
There was an issue connecting to your repo provider, click "Reconnect repository" in General Settings, and then try your build again.

### ISSUE THREAD

**Issue by tmosmant** [aws-amplify/amplify-hosting#3079]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d23mofeed7f7c7

### AWS Region

eu-west-1

### Amplify Hosting feature

Build settings, Deployments, Frontend builds, Git providers

### Describe the bug

Our Gitlab repository was connected until today. Now we can't trigger build as they always fail with this log error message:
```
2022-11-03T09:54:46.319Z [ERROR]: !!! CustomerError: Unable to clone repository due to user error code: 128
```

The following message appears, but reconnecting the repository fails with an `Unauthorized` red banner error message.
```
There was an issue connecting to your repo provider, click "Reconnect repository" in General Settings, and then try your build again.
```

In the console, we can see that Amplify does a POST to `https://console-extensions.amplify.eu-west-1.amazonaws.com/access-token` that ends up in a 500 error:

```
Access to XMLHttpRequest at 'https://console-extensions.amplify.eu-west-1.amazonaws.com/access-token' from origin 'https://eu-west-1.console.aws.amazon.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

### Expected behavior

We would like to be able to build our product again.

### Reproduction steps

1. In AWS Amplify console, go to our app
2. Trigger a build from `master`
3. Build fails as it cannot clone the git repo.

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriana** [comment]
Hi @tmosmant 👋🏽 we apologize for this inconvenience. We have identified this as a bug and are currently working on root causing the issue. We will provide you with an update and next steps as soon as possible.

**Comment by hloriana** [comment]
Thank you for your patience, the fix has been deployed to all AWS regions. Please try redeploying your app to confirm the issue is resolved for you.

**Comment by tmosmant** [comment]
What patience? You fixed it right away 🎉

Thanks @hloriana and @Jay2113 !
