### ISSUE TITLE
Style and Images not showing

### ISSUE THREAD

**Issue by KngAnt12** [aws-amplify/amplify-hosting#3084]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

aws:amplify:us-east-1:071576481120:apps/d2a9jw56aeie5g

### AWS Region

us-east-1

### Amplify Hosting feature

Manual deploys

### Describe the bug

I am not able to see they style and images of the static website I built. I can see everything locally but once I zip up the index.html build then deploy nothing shows correctly. I've tried adding a custom read and rewrite to include my image types to no avail.

### Expected behavior

![image](https://user-images.githubusercontent.com/48504402/200186580-773bc3cd-66ed-4692-b808-030dcc799e68.png)

### Reproduction steps

![image](https://user-images.githubusercontent.com/48504402/200186310-92c76706-ba9e-4841-8492-8aa84048725e.png)

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriana** [comment]
Hi @KngAnt12 👋🏽 did you navigate inside the folder and zip all of the contents within it? If you zip the folder itself then that could cause some issues.

**Comment by KngAnt12** [comment]
Ok, so I zipped up my css files, images, and my JS file but I'm now receiving the error below.

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>

**Comment by KngAnt12** [comment]
> Hi @KngAnt12 👋🏽 did you navigate inside the folder and zip all of the contents within it? If you zip the folder itself then that could cause some issues. Typically it results in an Access denied error but I noticed that the css files are also not being loaded. Can you also ensure that the css and image files are in the zipped folder?
