### ISSUE TITLE
SSL Certificate not auto renewed for my website.

### ISSUE THREAD

**Issue by mdmujeeb** [aws-amplify/amplify-hosting#3085]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3cobm3yw505pg

### Region

ap-south-1

### Step

SSL Certificate

### Status

Expired

### Issue or question

SSL Certificate not auto renewed for my website.
Please renew it immediately.

**Comment by hloriana** [comment]
Hi @mdmujeeb 👋🏽 The SSL certificate will not auto-renew if there were any changes made to the CNAME verification record in your DNS provider settings or if it was removed entirely. To resolve this, please remove and add your custom domain. Please refer to this documentation for more information: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html
