### ISSUE TITLE
Migrate Amplify app to a different region

### ISSUE THREAD

**Issue by andreyroizin** [aws-amplify/amplify-hosting#3089]
**Please describe which feature you have a question about?**
I need to migrate my Amplify react-native app to a different region, from us-east-1 to eu-central-1. I already have various services set up, such as Auth, Storage, Push Notifications, etc. Is there any automated way to move this configuration to a different region( creating a new app for it is also an option)? Thank you in advance for your help!

**Comment by hloriana** [comment]
Hi @andreyroizin 👋🏽 apologies for the delay. We currently do not support migrating Amplify applications across regions. However, there is an advanced workflow where you can export the CloudFormation stack to the Amplify CDK and use that stack across regions: [Use CDK for cross-account or cross-region Amplify backend deployments](https://docs.amplify.aws/cli/usage/export-to-cdk/#use-cdk-for-cross-account-or-cross-region-amplify-backend-deployments).
