### ISSUE TITLE
Create domain association failed

### ISSUE THREAD

**Issue by asnoba** [aws-amplify/amplify-hosting#3090]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

eu-west-1

### Step

Domain management

### Status

Failed

### Issue or question

I keep getting this error message when trying to connect my custom domain:

### Error message

Create domain association failed
One or more domains requested are already associated with another Amplify app: www.xx.dk, xx.dk

### Additional information

I've previously had the domain attached to another amplify app, but that has been deleted, so I can't look it up any longer in the aws console to remove the custom domain.

**Comment by hloriana** [comment]
Hi @asnoba 👋🏽 apologies for the delay in assistance here. If you are still having trouble connecting your domain, please provide your Amplify App ID so that we can further troubleshoot.

**Comment by asnoba** [comment]
Hi @hloriana. It's these two App Ids: d2sbfysdp94ybh and d2p7bkw9h9dp33.

**Comment by Jay2113** [comment]
Hi @asnoba 👋 , thanks for your continued patience and apologies for the delayed response on this thread.

I observed that your Amplify app `d2sbfysdp94ybh` has a custom domain `asnoba.com` connected to it and the Amplify app `d2p7bkw9h9dp33` does not have a custom domain associated to it.

Are you continuing to observe any errors during the domain activation process?
