### ISSUE TITLE
Stuck in SSL Configuration Step of Domain Management. 

### ISSUE THREAD

**Issue by diegoDeMiguelDPA** [aws-amplify/amplify-hosting#3092]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

eu-cenral-1

### Step

SSL  Configuration

### Status

In order to verify domain ownership, configure the following CNAME record associated with your domain and verify that the CNAME record exists in your Domain Name Server (DNS) file.

### Issue or question

Hi, I am stuck on the SSL Configuration Step of the Domain Management process in order to have a custom domain in my amplify project. The Domain's hosted zone is in AWS Route 53. Following this troubleshoot didn't help: [Link](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#my-domain-hosted-with-amazon-route-53-is-stuck-in-the-pending-verification-
![Screenshot 2022-11-09 at 06 26 14](https://user-images.githubusercontent.com/103195404/200746405-aedee371-1af1-4558-9b6d-6b6d19879f04.png)
state)  

The hosted zone of the domain shows the requested CNAME certificate and the name servers are consistent throughout the Route 53 console (see troubleshooting link) but the process doesn't move forward and the domain is not linke to the amplify project, any idea on how to solve this?

Thanks.

![Screenshot 2022-11-09 at 06 21 33](https://user-images.githubusercontent.com/103195404/200746429-87fca4d0-7a37-446a-a7ba-000558de8b14.png)

### Error message

In order to verify domain ownership, configure the following CNAME record associated with your domain and verify that the CNAME record exists in your Domain Name Server (DNS) file.

**Comment by ea-life** [comment]
![image](https://user-images.githubusercontent.com/5454952/200930089-410d9815-4b4a-403f-a96d-550587c7089b.png)

Same issue

**Comment by g445g445** [comment]
I also have the same issue, my CNAME is configured in Route 53 but wont be picked up by amplify

**Comment by mattfixme** [comment]
same issue

**Comment by manibpr** [comment]
Same issue

**Comment by novekm** [comment]
Double check that your Name Servers in "Registered Domains" matches the name servers in the NS record in your hosted zone. After there, it still can take some time in my experience - it took at long as 72 hours for one app
