### ISSUE TITLE
Next.js: How to store/deploy the file 'service-account-file.json' from Google Services

### ISSUE THREAD

**Issue by CauanCabral** [aws-amplify/amplify-hosting#3098]
**Please describe which feature you have a question about?**

How should I write a file at the build stage and have it deployed with my source code at Next.js API runtime (in Lambda@Edge)?

**Provide additional details**

Implementing reCaptcha (and I think any other Google Service) requires a Service Account.

To authenticate, the [Google Client expects a json file](https://cloud.google.com/docs/authentication/application-default-credentials).

I tried to create that file based on ENV/SECRETS at the build stage (using a command in my `amplify.yml`), save it, and put it in my project _root_ path.

But that file not exists in API executed code (I think it's ignored by the bundle stage).

I have tried to create the file at runtime, but storage is read-only on Lambda env

![image](https://user-images.githubusercontent.com/83092/200903008-c8180557-4944-487d-bc9b-41cb3d03cfd3.png)

**What AWS Services are you utilizing?**

 - Amplify Hosting with Next.js SSG+SSR

**Provide additional details e.g. code snippets**

**Comment by CauanCabral** [comment]
Thanks @calavera , but I don't think this solves or answers my question.

The `service-account-file.json` that Google expects is for backend usage only (API context), not for public access (like the `static` folder provides).

There is no way to write a file at build time and read it on API/backend/lambda context?

**Comment by CauanCabral** [comment]
A Next.js server route (the `/api` precisely), which runs in Lambda context.

**Comment by CauanCabral** [comment]
The problem was Google reCaptach only accepts the credentials from that physical file. In best case a I can only change the [expected path for the credential file](https://cloud.google.com/docs/authentication/application-default-credentials#GAC):

![image](https://user-images.githubusercontent.com/83092/209225246-0800b24e-dc5d-4b40-bee5-bc7b457eb729.png)

I tried to put the credential as ENV and at runtime write them to the file, but I got an error (as printed in the original issue) saying the filesystem is read-only.

**Comment by hloriana** [comment]
Closing this issue as resolved.
