### ISSUE TITLE
Custom Domain Activation Failed as it's deploying in an AWS Account doesn't belong to me

### ISSUE THREAD

**Issue by SarasArya** [aws-amplify/amplify-hosting#3106]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d11qok004as25h

### Region

ap-south-1

### Step

Domain Activation

### Status

Failed

### Issue or question

I was trying to deploy with AWS Amplify, and AWS now blocks my domain. It's failing at the Domain Activation stage, saying that some CF distribution is already using my domain, but I don't have access to this CF Distribution. 
All instructions in the troubleshooting guide point to things I can do when I have access to the distribution but I don't. 

Since the AWS Account doesn't belong to me, following the guide is complex. I have even emailed aws-amplify-customer@amazon.com but to no avail. Can someone from AWS help me remove this distribution from that account so I can proceed? 

### Error message

Error message: [CNAMEAlreadyExistsException] The following CloudFront distributions or Amplify Apps are already using one or more of your domains: [Distribution: ******30F6TC1 in AWS Account: ******717855]. For distributions you own, please remove the domains from them first and then retry adding your domain. For Amplify apps you own, you may already have associated this domain to another Amplify App in another accountor region. You can also check our troubleshooting guide for more help: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.htmlalready use

**Comment by hloriana** [comment]
Hi @SarasArya 👋🏽 it appears that the CNAMEs are associated with a CloudFront distribution that is linked to your account but it does not appear to be attached to an Amplify app. For further assistance, please open an AWS Support case.
