### ISSUE TITLE
Commit to a feature branch broke QA

### ISSUE THREAD

**Issue by timalive** [aws-amplify/amplify-hosting#3108]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2l65reg7arq0g

### AWS Region

eu-west-1

### Amplify Hosting feature

One click deploy

### Describe the bug

We are rewriting an app - all within a feature branch [TA-591/keycloak](https://eu-west-1.console.aws.amazon.com/amplify/home?region=eu-west-1#/d2l65reg7arq0g/ta-591-keycloak)

When we committed to this branch, it rendered our QA branch inoperable.  To be clear, we did NOT redeploy our QA branch but it now produces a 503 when navigating to the endpoint

### Expected behavior

We expected the current qa to be unaffected by a commit to a feature branch.

### Reproduction steps

Navigate to the QA endpoint

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by nadetastic** [comment]
Hi @timalive following up on this issue. Are you still facing this problem? It looks like the APP ID you shared may have been deleted, but let me know if you still have questions about this.
