### ISSUE TITLE
Next.js 13 no SSR

### ISSUE THREAD

**Issue by arpecop** [aws-amplify/amplify-hosting#3124]
**Please describe which feature you have a question about?**

I am pretty excited about the Amplify support of Next@latest , unfortunately the "hello world" app I am trying to deploy acts like create-react-app without the useful prerendered content 

**Provide additional details**
https://main.d1top4agb5zal9.amplifyapp.com/ (if you view the source there is no HTML)
same repo/codebase/version deployed to Vercel: 
https://next13-mu.vercel.app/

**What AWS Services are you utilizing?**
Amplify Hosting

**Provide additional details e.g. code snippets**
![Screenshot 2022-11-19 at 2 13 08](https://user-images.githubusercontent.com/168974/202823332-229f8081-3835-49e4-b415-b7f66fd03c1e.png)
from AWS console logs
![Screenshot 2022-11-19 at 2 16 22](https://user-images.githubusercontent.com/168974/202823562-5488cf2c-fea7-4e20-9d43-f38e5706ce75.png)

**Comment by DanProudfoot** [comment]
I am also getting no messaging about running in the build step. 

We're having a lot of issues (right now getting a 502 error on a brand new deployment) and wonder if this might have something to do with it

**Comment by swaminator** [comment]
@DanProudfoot can you share your AppID( found in app settings >General)? We could hop on a call to see what's going on.

**Comment by arpecop** [comment]
does this has some preferences for region ? , I am deploying from eu-west-1 ... and since the post I didn't make new updates, now the app displays 500 error

**Comment by michrome** [comment]
Are you seeing this behaviour with a "Hello word" page like the below?

```js
// pages/ssr.js
export default function SSR({ formattedDate }) {
  return (
    <>
      <h1>Server-side rendered page</h1>
      <p>
        This page is server-side rendered. It was rendered on {formattedDate}.
      </p>
      <p>
        <a href="/">View a static page.</a>
      </p>
    </>
  );
}

export async function getServerSideProps() {
  const renderDate = Date.now();
  const formattedDate = new Intl.DateTimeFormat("en-US", {
    dateStyle: "long",
    timeStyle: "long",
  }).format(renderDate);
  console.log(
    `SSR ran on ${formattedDate}. This will be logged in CloudWatch.`
  );
  return { props: { formattedDate } };
}
```

**Comment by DanProudfoot** [comment]
> @DanProudfoot can you share your AppID( found in app settings >General)? We could hop on a call to see what's going on.

@swaminator Our AppId is `d35zta8s7v7rta`. Happy to jump on a call during UK working hours ( 9 - 5:30 GMT).

@arpecop We're also deploying to eu-west-1...maybe that's the problem?

**Comment by michrome** [comment]
Hey @DanProudfoot - please send me a note jrm@amazon.co.uk and we'll connect during the UK workday.

**Comment by michrome** [comment]
Hey @arpecop for the avoidance of doubt, are you using SSR or **streaming SSR**?

Amplify Hosting doesn't yet support streaming SSR, which you might see if you use the (beta) `/app` directory feature. That said, it should fall back to client side rendering: for example https://main.d123h98fg6yy59.amplifyapp.com/ is created from https://github.com/vercel/next.js/tree/canary/examples/with-turbopack

**Comment by arpecop** [comment]
@michrome I would be happy to use the old way (using src/pages/) but before trying to migrate I have question regarding the support lambda@edge , and edge geolocations ?

**Comment by michrome** [comment]
@arpecop if in doubt, I recommend creating a new app to test it out.

After migrating, apps have a fully-managed CloudFront distribution that will not be visible in your AWS account, so Lamba@Edge will not be available to you. No geographic restrictions are set so the distribution is serving gloablly.

**Comment by Jay2113** [comment]
Closing this issue due to age.
