### ISSUE TITLE
NextJS migration disabled ISR

### ISSUE THREAD

**Issue by evan1715** [aws-amplify/amplify-hosting#3128]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dd58s257c5tmr

### AWS Region

us-east-1

### Amplify Hosting feature

Backend builds, Deployments, Not Applicable

### Describe the bug

The ISR feature does not work after the migration from the previous Amplify to the new Amplify with NextJS.

### Expected behavior

I expect ISR to still work. It's a simple call to pull a list of something once an hour. The function includes a timestamp to keep track of when it was last updated, and it doesn't update except for at build time.

### Reproduction steps

It's a very simple code for ISR.

export async function getStaticProps() {
    try {
        return { props: { list: await listAll() }, revalidate: 3600 }; //3600 is 1 hour.
    } catch (error) {
        console.log('getStaticProps', error);
    }
}

Does not regenerate the data after an hour, or even after a full day.

### Build Settings

```yaml
N/A
```

### Log output

N/A

### Additional information

N/A

**Comment by hloriana** [comment]
Hi @evan1715 👋🏽 thank you for raising this issue. We apologize for the inconvenience this bug is causing. The Amplify Hosting team is aware of this bug and we are treating this with high priority. We will update this issue with next steps once we have a workaround or solution in place.

**Comment by evan1715** [comment]
ok, sounds good. let me know when there's a potential fix and i'll test it out, then respond back with the results.

**Comment by ChrisAtVirtueraDev** [comment]
facing the same issue. observed that occasionally, a newer version of a page is being delivered, but on reload, the old version (build time) is delivered again. so you get the updated version on those rare occasions, but then the old content again.

**Comment by ChrisAtVirtueraDev** [comment]
on demand revalidation via api route also not working. i would assume due to the same bug

**Comment by evan1715** [comment]
@ferdingler please wait for a response before closing these. the issue presented is not for regular ISR, but for the dynamic/revalidation part as said in the expected behavior section.

i'm using it to download a list of all IoT devices we have to search through them. the browser caches the list for a while so the user does not have to download a new list every call. now with ISR doing it every page call, it is being downloaded every time, slowing the page significantly. so, i do not believe this issue topic is officially closed until the dynamic part is fixed. then i would like to test it and give a reply before closing the topic. 

in the meantime, i will now have to stop ISR and just use static generation at build time due to the increase in load time from this newer ISR adjustment.
