### ISSUE TITLE
Build failure for hugo web site in git repo.

### ISSUE THREAD

**Issue by curranjohn46** [aws-amplify/amplify-hosting#3135]
**Please describe which feature you have a question about?**
Amplify web hosting.
**Provide additional details**
My build of a new hugo site in a github repo is failing. This is my first tie trying this. I believe it might be failing because it is not using the github personal access token but not sure. I found this doc but not sure how to implement this via the AWS Amplify console build process.  https://docs.aws.amazon.com/amplify/latest/userguide/setting-up-GitHub-access.html

Any help would be appreciated and hopefully this is the right place to ask.

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**

**Comment by hloriana** [comment]
Hi @curranjohn46 👋🏽 can you please provide your Amplify app ID? We can investigate what is causing the build failure and provide you with next steps once we have more details.
