### ISSUE TITLE
Can't change source provider to GitHub 

### ISSUE THREAD

**Issue by santiagocezar** [aws-amplify/amplify-hosting#3136]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

de8cv9owok4bt

### AWS Region

sa-east-1

### Amplify Hosting feature

Git providers

### Describe the bug

Similar situation as #2677. I've moved my webpage source code from CodeCommit to GitHub. I've removed the hosting environment from my Amplify app and now I'm trying to connect GitHub, when I select GitHub it sends me to the "Add repository branch" section, it instanly refreshes the page, and when it finishes loading it's now asking me to select a CodeCommit repository. I press cancel, select GitHub again and then the same happens again.

### Expected behavior

I should be able to choose a repository and branch from GitHub

### Reproduction steps

1. Remove the hosting environment of an app
2. Go to the app home
3. Choose GitHub as a source provider
4. Webpage refreshes
5. Unable to add GitHub repository
6. Repeat from step 2

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by swaminator** [comment]
@santiagocezar you have to connect a new repository. This capability is currently isn't supported.

**Comment by santiagocezar** [comment]
I think I might have been misunderstood, sorry. This is the issue I'm having and I'm pretty sure this is a bug, not a missing feature:

[Kooha-2022-11-22-21-48-07.webm](https://user-images.githubusercontent.com/48573316/203449605-a0891d3a-1442-49d6-9466-563b7fe50168.webm)

I'm not able to choose a GH repository at all. I've already tried disabling content blocking extensions (even Firefox tracking protection) without luck. Hopefully that video helps

**Comment by hloriana** [comment]
Hi @santiagocezar 👋🏽 we currently don't support changing the repositories via the Amplify Console. However there is a workaround. You can update the repository via the CLI:

`aws amplify update-app --app-id <value> --repository https://github.com/hloriana/animal-crossing.git --access-token <PAT value>` 

Then you can navigate back to the Amplify console and connect the branch of the GitHub repository you want to host.

**Comment by santiagocezar** [comment]
Alright, that command worked! Thank you so much! 

Some feedback:  
> we currently don't support changing the repositories via the Amplify Console

I think that should be more obvious, this just seemed to be some kind of obscure bug, maybe there should be some kind of warning or error even on cases like this
