### ISSUE TITLE
NextJS 13 SSR app set-cookie missing in response header

### ISSUE THREAD

**Issue by ashish7adlakha** [aws-amplify/amplify-hosting#3142]
My NextJS 13 SSR app is setting cookies on my local machine properly but the response headers are not returning with set cookie for `__next_preview_data` when i deploy on amplify. does anyone have any idea why this is happening?

**`Amplify SSR`**

<img width="572" alt="image" src="https://user-images.githubusercontent.com/11086923/203734697-1c6a0d04-9ffd-4aba-8ff7-b2eb73f979b1.png">

**`Local System`**

<img width="573" alt="image" src="https://user-images.githubusercontent.com/11086923/203734997-0c3d50e9-ea60-47e5-adcf-7a1dba97646d.png">

_Originally posted by @ashish7adlakha in https://github.com/aws-amplify/amplify-hosting/issues/2554#issuecomment-1326133152_

**Comment by ferdingler** [comment]
Hi, thanks for reporting this issue. We have rolled out a fix for proper handling of Set-Cookie header with multiple values. Feel free to reopen if you still experience issues.
