### ISSUE TITLE
Amplify triggers deploying CloudFront again when not neccessary 

### ISSUE THREAD

**Issue by entest-hai** [aws-amplify/amplify-hosting#3154]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d38q1ys9oywejq

### AWS Region

us-east-1

### Amplify Hosting feature

SSR

### Describe the bug

I have noticed that Amplify hosting trigger deploying CloudFront though there are no changing in static files. Let me explain 

1. I only change a few line of code and there is no any change about static files in S3 and CloudFront
2. Then Amplify still trigger CloudFront to re-deploy again 

### Expected behavior

1. Amplify should not trigger CloudFront re-deploy again when not necessary 
2. Amplify should use CloudFront Invalidation for specific static file change 

This will help the overall build time faster 

### Reproduction steps

1. Create a new Amplify SSR hosting 
2. Deploy 
3. Modify README and commit a code change, do not change any static files which will be stored in CloudFront
4. Go to CloudFront and see it is re-deploying. This is not necessary and case long build time in overall  

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriana** [comment]
Hi @entest-hai 👋🏽 Thanks for raising this issue. If you would like to skip builds for commits where the changes do not affect the website, you can as `[skip-cd]` at the end of the commit message. See [Skip build for a commit](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#skip-build-for-a-commit). This will prevent the builds from be triggered for that specific commit.

If you would also like to take advantage of faster build times, we've recently launched support for Next.js 12 and 13. With this support, Next.js apps deploy 3x faster. Please see: https://aws.amazon.com/about-aws/whats-new/2022/11/aws-amplify-hosting-support-next-js-12-13/
