### ISSUE TITLE
Unable to set multiple cookies when app is deployed to Amplify Hosting

### ISSUE THREAD

**Issue by jbmgil** [aws-amplify/amplify-hosting#3156]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3jxl298th9s9o

### AWS Region

sa-east-1

### Amplify Hosting feature

Custom headers

### Describe the bug

I have a Next.js app that receives data from another app on the backend and send it to it's own client as cookies. These cookies are working fine on localhost, but they are not being set properly when I deploy the app to AWS Amplify.

In my backend code, I have an array of cookies and send them to the client like so:
`res.setHeader("Set-Cookie", cookies);`
But only the first cookie of the array is being set.

I have multiple apps deployed to Amplify and they all work just fine with the same code. The issue is happening only with this specific app.

By researching possible solutions I found that It could be a Cloudfront distribution's config, but going to Services -> Cloudfront -> Distributions I found that there is no dist for this Amplify app (the others all have one).

I've tried several possible solutions but none of them worked so far.
I'll be happy to provide more infos if needed.

### Expected behavior

![image](https://user-images.githubusercontent.com/55856405/204823032-0fab717f-c91d-4cb5-a35e-ad0dace91534.png)

### Reproduction steps

N/A

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ferdingler** [comment]
Hi, thank you for bringin this to our attention. We have rolled out a fix for proper handling of multi-value headers. Feel free to reopen if you are still experiencing problems.
