### ISSUE TITLE
Faster deployment, currently 10 minutes aprox.

### ISSUE THREAD

**Issue by crow7m** [aws-amplify/amplify-hosting#3157]
Good day, we are using amplify for  our front-end react application, I have noticed that every build takes approximately 10 minutes, 
There is a way to speed up the process?
Thank you

**Comment by hloriana** [comment]
Hi @crow7m 👋🏽 You can [enable or disable diff based frontend build and deploy](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#enable-diff-deploy) by adding `AMPLIFY_DIFF_DEPLOY` as an environment variable and set it to `true`. Amplify will attempt to run a diff on the `src` or `appRoot` and if no differences are detected then the build and deploy phase will skip. But this may not apply to your use case if your builds are front-end only. 

If you provide us your App ID, we can investigate what is contributing to the build times and determine if there are steps you can take to reduce them.

**Comment by crow7m** [comment]
@hloriana thank you for your answer, yes, in our case every push is an update, so diff-deployment won't help.
here is an app id: dc6ypf75kxz10, thank you

**Comment by Rafcin** [comment]
@crow7m https://github.com/ducktors/turborepo-remote-cache If you use Turbo, take a look at this, remote cache is quite cool and you can host it yourself.

**Comment by crow7m** [comment]
@hloriana good day, may I ask you if there is any update about this one? thank you

**Comment by re-thc** [comment]
This is an AWS problem. I have tried with CodeCatalyst (the new service) and used a blueprint to deploy to Amplify. Out of the box the pipeline was 10minutes. 0 config from the user. All recommendations and setup from AWS on a minimal sample repository.

**Comment by crow7m** [comment]
@hloriana Good day any update on this one ? Thank you

**Comment by Jay2113** [comment]
Over the past year, we have made significant improvements to reduce the overall build times for Amplify applications. Also, you can use the `cache` attribute in the build specification file to cache the build time dependencies such as `node_modules` folder to further speed up your builds: https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html.
