### ISSUE TITLE
isBot and userAgent do not work in Next.js 12 middleware.ts

### ISSUE THREAD

**Issue by bc-ptg** [aws-amplify/amplify-hosting#3159]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d20j9opmqvf3vx

### AWS Region

us-east-1

### Amplify Hosting feature

SSR

### Describe the bug

`userAgent(request)` called within middleware.ts does not behave as expected.

In particular `isBot` always returns `false`.

Example middleware.ts as follows:

```
import { NextRequest, NextResponse, userAgent } from 'next/server';

export function middleware(request: NextRequest) {
    const { isBot, browser, device, engine } = userAgent(request);

    if (isBot) {
        return NextResponse.redirect("https://this-is-a-bot");
    } else {
        return NextResponse.redirect("https://this-is-not-a-bot");
    }

}
```

We also noticed the browser, device, and engine responses also never appear to return any data, although our primary concern is `isBot` as we need that to implement rewrites for prerender.io.

### Expected behavior

After changing the browser's user agent to a bot's, such as `Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)` and implementing the example middleware.ts, visiting the app should redirect to the "this-is-a-bot" result. This works when building and testing locally, however on Amplify it always redirects to the "this-is-not-a-bot" result.

### Reproduction steps

1. Implement the example middleware.ts and push to Amplify
2. Change your browser's useragent to a bot's, e.g. `Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)`
3. Visit the app and observe the incorrect return from middleware.ts

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

We are on Next 12.3.1

**Comment by JanStevens** [comment]
This boils down to the same as https://github.com/aws-amplify/amplify-hosting/issues/3142,
The cloudfront distribution is hidden now which means you cannot forward any custom headers to your nextjs app.

What a great oversight of AWS regarding nextjs hosting 🤦‍♂️ . With the old amplify you at least had a cloudfront distribution that could be edited.

**Comment by mikefrancis** [comment]
@hloriana Thanks for taking a look. We've had to temporarily move our website to Vercel as our content editors are completely unable to preview content (facilitated by cookies) at the moment which is a massive dealbreaker for us (and others I imagine).

I just wanted to highlight that if this cannot be fixed pretty much immediately, we will be migrating hosting platforms away from Amplify indefinitely.

**Comment by ferdingler** [comment]
Hi, apologies for the inconvenience and thanks for reporting this bug. We have rolled out a fix to properly handle multiple Set-Cookie headers present in responses. Feel free to reopen if you are still experiencing issues.
