### ISSUE TITLE
Unable to deploy backend environment "storage headless is missing the following inputParams tables, region"

### ISSUE THREAD

**Issue by Syphini** [aws-amplify/amplify-hosting#3160]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.17.0

### Amplify CLI Version

10.0.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes as far as I'm aware

### Amplify Categories

storage, api

### Amplify Commands

Not applicable

### Describe the bug

While attempting to deploy our AWS Amplify connected application, the backend environment fails to deploy with this error

> Command failed with exit code 1: amplify pull --amplify {"envName":"staging","defaultEditor":"code","appId":"XXX"} --providers {"awscloudformation":{"configLevel":"project","useProfile":true,"profileName":"amplify-backend-processor"}} --frontend {"frontend":"javascript","framework":"react","config":{"SourceDir":"src","DistributionDir":"build","BuildCommand":"npm run-script build","StartCommand":"npm run-script start"}} --yes ✖ Failed to sync UI components - Fetching updates to backend environment: staging from the cloud. - Building resource api/XXX - Building resource auth/XXX - Building resource storage/XXX - Building resource storage/XXX - Building resource storage/XXX ✔ Successfully pulled backend environment staging from the cloud. ✖ There was an error initializing your environment. ⚠️ Amplify command hooks are disabled in the current execution environment. ⚠️ See https://docs.amplify.aws/cli/usage/command-hooks/ for more information. Amplify AppID found: XXX. Amplify App name is: XXX Backend environment staging found in Amplify Console app: XXX ✅ GraphQL schema compiled successfully. Edit your schema at XXX or place .graphql files in a directory at XXX Successfully generated models. Generated models can be found in XXX ✅ GraphQL schema compiled successfully. Edit your schema at XXX or place .graphql files in a directory at XXX Failed to pull the backend. 🛑 storage headless is missing the following inputParams tables, region Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report' Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

After previously searching for solutions I attempted to add the following environment variables as others have said this helps

> AMPLIFY_STORAGE_BUCKET_NAME
 AMPLIFY_STORAGE_REGION

I similarly tried to add the CATEGORIES environment variable after the previous ones did not work, however this caused a separate issue and the 'Cloning Repository' build step now throws the following error

> Error: storage headless is missing the following inputParams tables, region
                                 at ensureHeadlessParameters (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-storage/lib/provider-utils/awscloudformation/import/import-dynamodb.js:400:11)
                                 at headlessImport (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-storage/lib/provider-utils/awscloudformation/import/import-dynamodb.js:360:40)
                                 at importedDynamoDBEnvInit (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-storage/lib/provider-utils/awscloudformation/import/import-dynamodb.js:260:12)
                                 at runMicrotasks (<anonymous>)
                                 at processTicksAndRejections (internal/process/task_queues.js:95:5)
                                 at async updateConfigOnEnvInit (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-storage/lib/provider-utils/awscloudformation/index.js:157:9)
                                 at async /snapshot/repo/build/node_modules/@aws-amplify/amplify-category-storage/lib/index.js:352:22
2022-09-30T00:52:15.094Z [ERROR]: !!! Build failed
2022-09-30T00:52:15.094Z [ERROR]: !!! Non-Zero Exit Code detected

I'd appreciate any advice I can get on solving this issue

### Expected behavior

Application should deploy with Frontend and Backend working correctly.

### Reproduction steps

After attempting to recreate on a new project I have come up with nothing, however it only seemed to have occurred in this project after importing an existing DynamoDB Table

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

```

</details>

### Project Identifier

1faff6209c11433887b9b21140585980

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by grantjoy** [comment]
Any update on this? I can provide more info if needed, but it seems well defined.

**Comment by Syphini** [comment]
Since the latest Amplify Hosting release, I haven't had the same issue again. Unsure if the env vars kicked in properly or it just resolved itself naturally, but I've yet to see it reappear in the last couple of months

**Comment by grantjoy** [comment]
@Syphini you could check your config through the hosting console and see if AMPLIFY_STORAGE_TABLES is set - my guess is that it is given that my stuff broke until I set it on the newest version.

**Comment by jakejcheng** [comment]
> I solved this problem by setting env vars through: Amplify -> Environment variables -> then adding env vars for: AMPLIFY_STORAGE_BUCKET_NAME (set it to whatever you want, it's useless) AMPLIFY_STORAGE_REGION (I set my region, might be useless as well, but it was required) AMPLIFY_STORAGE_TABLES (JSON like: { "STORAGE_RESOURCE_NAME_1":"DDB_TABLE_NAME_1", "STORAGE_RESOURCE_NAME_2":"DDB_TABLE_NAME_2"} )
> 
> This is still a bug. At a minimum the bucket name var shouldn't be needed and it would be great if this were just inferred.

Imported storage/table today and got the same error. And your solution worked so thank you! (I set AMPLIFY_STORAGE_BUCKET_NAME to "THIS IS USELESS" and it worked so indeed useless)

**Comment by Syphini** [comment]
The issue resolved itself a while back seemingly with a new update to Amplify Hosting. 
I'm closing this as I haven't seen it reappear again even without making any significant changes myself
