### ISSUE TITLE
Unable to migrate to google domain to AWS

### ISSUE THREAD

**Issue by saverna12345** [aws-amplify/amplify-hosting#3165]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

ohio

### Step

taralaistressrelief.com

### Status

failed

### Issue or question

Migrating a google domain to AWS.
Created host, updated name server in google domain, switched to custom server, added domain to was amplify 
It's been a week and the website is still now published.
<img width="2297" alt="awsamplify" src="https://user-images.githubusercontent.com/26666705/205168964-485be454-669c-4b7a-b79e-27a33ceba0fb.png">

### Error message

<img width="709" alt="servernotfound" src="https://user-images.githubusercontent.com/26666705/205169321-ef552127-e300-49b0-b691-d1d964e29d96.png">
 this is what I see when look for the website

### Additional information

was on the line with google today everything looks good on that end, I am just stuck on was side by not being able to see the domain
 Migrating a google domain to AWS.
Created host, updated name server in google domain, switched to custom server, added domain to was amplify 
It's been a week and the website is still now published.
<img width="2297" alt="awsamplify" src="https://user-images.githubusercontent.com/26666705/205168964-485be454-669c-4b7a-b79e-27a33ceba0fb.png">

**Comment by Rafcin** [comment]
@saverna12345 Have you run tests in Route 53 to verify everything is working? https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-test.html
