### ISSUE TITLE
Delete domain for an existent amplify build

### ISSUE THREAD

**Issue by Rhplx** [aws-amplify/amplify-hosting#3167]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d32hlawnrhnw8v

### Region

us-east-1

### Step

Domain connection to AWS

### Status

failed

### Issue or question

I am trying to connect a domain to a AWS Amplify build but i got this error:

Error message: [CNAMEAlreadyExistsException]...

i don't know if there is another amplify build connected to the domain but can i do something to release it and connect it to this build? or my domain is lost forever? Thanks in advance.

### Error message

Error message: [CNAMEAlreadyExistsException] The following CloudFront distributions or Amplify Apps are already using one or more of your domains: [Distribution: ******QYKSIW8 in AWS Account: ******xxxx, Distribution: ******xxxx in AWS Account: ******xxxxxx]. For distributions you own, please remove the domains from them first and then retry adding your domain. For Amplify apps you own, you may already have associated this domain to another Amplify App in another accountor region

**Comment by hloriana** [comment]
Hi @Rhplx 👋🏽 it looks like your custom domain is still connected to an Amplify app in another account. In order to use this domain with your new Amplify app, you will have to deactivate the CloudFront distribution associated with that domain. 

Please follow this guide to resolve the issue: https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

**Comment by Rhplx** [comment]
I dont have access to the amplify account that have the domain, what can i do?  if i buy premium support they will be able to fix it?
