### ISSUE TITLE
SSR app detected as "Web" instead of "Next.js - SSR"

### ISSUE THREAD

**Issue by pwellner** [aws-amplify/amplify-hosting#3168]
**Please describe which feature you have a question about?**

While deploying a NextJS application that previously deployed without error, the FrontEnd logs of the build process terminate after the following error message:

` !!! CustomerError: Framework Web not supported`

Can someone explain the meaning of this error message?

**Provide additional details**

I have tested many different versions of NextJS, including `13.0.5` and `12.3.4`
I have tested different versions of NodeJS in my Amplilfy "Build Settings", including the default, v16 and v18

I had recently migrated my app to `WEB_COMPUTE`, so I attempted to revert back with
 `aws amplify update-app --platform WEB_DYNAMIC` but got the same error.

Then I tried a fresh deployment on amplify, which did not prompt me to migrate.  This successfully deployed once on one branch, but failed with this `CustomerError` message for other  identical branches.

**What AWS Services are you utilizing?**
Amplify with continuous build setup from GitHub branches

**Provide additional details e.g. code snippets**

Snippet of logs below:
```
2022-12-02T00:19:44.112Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
2022-12-02T00:19:44.260Z [INFO]: # Completed phase: build
2022-12-02T00:19:44.262Z [INFO]: ## Build completed successfully
2022-12-02T00:19:44.263Z [INFO]: # Starting caching...
2022-12-02T00:19:44.267Z [INFO]: # Creating cache artifact...
2022-12-02T00:19:44.269Z [INFO]: # Created cache artifact
2022-12-02T00:19:44.269Z [INFO]: # Uploading cache artifact...
2022-12-02T00:19:44.347Z [INFO]: # Uploaded cache artifact
2022-12-02T00:19:44.347Z [INFO]: # Caching completed
2022-12-02T00:19:44.349Z [INFO]: Setting NEXT_PRIVATE_STANDALONE=true to produce .next/standalone directory
2022-12-02T00:19:44.350Z [INFO]: # No custom headers found.
2022-12-02T00:19:44.350Z [ERROR]: !!! CustomerError: Framework Web not supported
2022-12-02T00:19:44.352Z [INFO]: # Starting environment caching...
2022-12-02T00:19:44.352Z [INFO]: # Environment caching completed
```

**Comment by oste** [comment]
I am also seeing this issue after attempting to deploy a new branch for a previously successfully built app. 
I should note that I only tried the new branch because I couldn't get the basic auth to go away or successfully login after changing Access Control settings.

**Comment by hloriana** [comment]
Hi @oste 👋🏽 if you recently migrated to WEB_COMPUTE from WEB_DYNAMIC and are seeing issues with Access Control settings, please make sure to remove the rewrite rule that points to the old CloudFront distribution. 

Navigate to **App settings** -> **Rewrites and redirects** -> and remove the rule. 

Access Control settings are stored in that distribution which is why the prompt continues to appear. Ideally the rewrite rule would have been deleted upon migrating but this is a bug we are currently prioritizing to fix.

**Comment by pwellner** [comment]
Hi @hloriana, Can you explain the meaning of the error message `!!! CustomerError: Framework Web not supported`  or an example situation that can cause it?  What does "Framework Web" refer to in this case?
Thanks

**Comment by hloriana** [comment]
Hi @pwellner 👋🏽 apologies for this inconvenience. It appears the branch is mistakenly being detected as `web` which is what is used for applications that use frameworks like React or Angular.  Try running this command to update your branch's framework to `Next.js - SSR`:

`aws amplify update-branch --app-id <value> --branch-name <value> --framework 'Next.js - SSR' `

**Comment by pwellner** [comment]
Thank you very much @hloriana!  The command you suggested fixes the issue.

Could it be perhaps that Amplify incorrectly detected the wrong framework because  `appRoot: web` was set as the build directory in my `amplilfy.yml` settings?

**Comment by hloriana** [comment]
Re-opening for tracking purposes since this appears to be a bug that needs a proper fix.

**Comment by hloriana** [comment]
We have not been able to reproduce this issue on our end. If anyone else runs into this behavior, please create a new issue with detailed reproduction steps. Thank you!
