### ISSUE TITLE
Where is my next.js edge function?

### ISSUE THREAD

**Issue by yourhrh** [aws-amplify/amplify-hosting#3171]
**Please describe which feature you have a question about?**
Where can I find ssr lambda@edge when hosting a next.js application?

**Provide additional details**
Currently, the ssr application has been distributed through amplify, and it has been confirmed that the api and ssr are working. But I don't know where my lambda@edge is.

**What AWS Services are you utilizing?**
amplify ssr hosting

**Provide additional details e.g. code snippets**

**Comment by hloriana** [comment]
Hi @yourhrh 👋🏽, if you are hosting a Next.js 12 or 13 application then those resources are fully managed by Amplify and do not exist in your account. If you would like to access your logs, you can do so by navigating to **App settings > Monitoring > Hosting compute log** and you will find a log group named `/aws/amplify/<app_id>`. 

Please note that there needs to be an IAM role associated with your app to access those logs and that role must include these permissions: `logs:PutLogEvents` `logs:CreateLogStream` `logs:CreateLogGroup`.

Feel free to read more about Amplify Hosting support for Next.js 12 and 13 here:

- [AWS Amplify Hosting announces support for Next.js 12 and 13](https://aws.amazon.com/about-aws/whats-new/2022/11/aws-amplify-hosting-support-next-js-12-13/)
- [Deploy a Next.js 13 app to AWS with Amplify Hosting](https://aws.amazon.com/blogs/mobile/amplify-next-js-13/)
