### ISSUE TITLE
Font not accepting in Amplify

### ISSUE THREAD

**Issue by sekarkeerth** [aws-amplify/amplify-hosting#3181]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-1

### Amplify Hosting feature

Web previews

### Question

I am using Kanit font in our website and in the local it works fine but in Amplify after generating the build the font is not taking. How can we fix this ?

**Comment by hloriana** [comment]
Hi @sekarkeerth can you provide your app Id so we can investigate the issue further? Also, make sure that all necessary font files have been pushed to your remote repository, it's possible that a file could be missing.
