### ISSUE TITLE
Next v13 - Failed to write image to cache.

### ISSUE THREAD

**Issue by MiadV** [aws-amplify/amplify-hosting#3184]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2n7tnxsfd508i

### AWS Region

ap-southeast-1

### Amplify Hosting feature

SSR

### Describe the bug

My App is running normally but when I check the logs in CloudWatch sometimes I can see `Failed to write image to cache`  mostly when  I open a SSR page. I was wondering why am I getting this error. Does this mean my images are not getting cached?

### Expected behavior

-

### Reproduction steps

I'm using `next/legacy/image` component from next v13

### Build Settings

```yaml
-
```

### Log output

<details>

```
Failed to write image to cache cRMBEi5cIuFeS7F9BE7d4K4ESVCBkCUHgRE0FcfKSwU= [Error: ENOENT: no such file or directory, mkdir '/var/task/.next/cache/images']
{
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/var/task/.next/cache/images'
}

```

</details>

**Comment by ferdingler** [comment]
Hi, we have rolled out a fix for this, you should no longer see this error neither with ISR pages or Image Optimizations. Thanks for reporting!
