### ISSUE TITLE
CloudFront Cache not being immediately invalidated after rebuild/redeploy if custom cache control header is set [Next.js - SSR]

### ISSUE THREAD

**Issue by ChrisAtVirtueraDev** [aws-amplify/amplify-hosting#3186]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1gzjuqxqbagv4

### AWS Region

us-west-1

### Amplify Hosting feature

Custom headers, Deployments, SSR

### Describe the bug

CloudFront Cache not being immediately invalidated after rebuild/redeploy if custom cache control header is set

### Expected behavior

Instantaneous invalidation of CloudFront on redeployment 

### Reproduction steps

In next.config.js I set the Cache-Control header to "s-maxage=600".
After deployment, everything works as intended = Getting the content from cloudfront for 600sec after it fetches new data.

**Observed Behavior:**
Now I change the value so say "s-maxage=300".
After redeployment, I will still get all the content from the previous build, including the Cache Control header "s-maxage=600", until the specified 600seconds run out. 

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by calavera** [comment]
This feature has just been supported with our latest launch! I'm closing this issue as it's been resolved.

Check out the details here: https://aws.amazon.com/blogs/mobile/cdn-caching-improvements-for-better-app-performance-with-aws-amplify-hosting/
