### ISSUE TITLE
App incorrectly treated as a "Next.js" app

### ISSUE THREAD

**Issue by gxxcastillo** [aws-amplify/amplify-hosting#3190]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-1

### Amplify Hosting feature

Monorepo, SSR

### Describe the bug

I have an NX repo, where one of the applications is a NextJS application.  However, the application that I am trying to publish via Amplify hosting is NOT a NextJS application.  Nonetheless, Amplify hosting sets the framework to Next.js - SSR and now, I don't know if this is related but my builds all error out with: 

```
> Setting NEXT_PRIVATE_STANDALONE=true to produce .next/standalone directory
> # No custom headers found.
> !!! CustomerError: Standalone directory not found in <...>/standalone. Please enable output standalone on your next.config.js file or set NEXT_PRIVATE_STANDALONE=true. https://nextjs.org/docs/advanced-features/output-file-tracing#automatically-copying-traced-files```

### Expected behavior

I would expect to be able to have control over the framework that Amplify Hosting chooses so that it does not incorrectly try to build my app as if it were a Next.js app.  I would expect to build my application without getting "Standalone directory" errors for a non Next.js app.

### Reproduction steps

1. create NX monorepo with multiple applications, one of which is a Next.js applictions
2. try to set up Amplify Hosting for your non-Next.js application

### Build Settings

_No response_

### Log output

<details>

```
# Put your logs below this line

```

</details>


### Additional information

_No response_

**Comment by gxxcastillo** [comment]
Update: I tried deleting any mention of nextjs from my repo, including all my other applications and any nextjs library from package.json and recreating my .lock file and now I'm getting this error when I try to deploy:

```
> !!! CustomerError: Cannot read 'next' version in package.json.
```

**Comment by hloriana** [comment]
Hi @gxxcastillo please share your app ID so we can further investigate why your app is being incorrectly detected as SSR. Also what framework are you using for the app you are trying to deploy?

You can try to mitigate this by changing the framework setting for your app's branch by running the `update-branch` command. Here is an example you would use if it were a React app :

`aws amplify update-branch --app-id <value> --branch-name <value> --framework  'React'`

**Comment by gxxcastillo** [comment]
Hi @hloriana , the app ID is `d3njefl2j1zdtl`.  I'll try the `update-branch` command now...

**Comment by gxxcastillo** [comment]
Hi @hloriana, is there any way to work around this?  At the moment this is blocking me from being able to have my nextjs app alongside my non-nextjs app in my monorepo.

**Comment by subooom** [comment]
Hey, I'm also getting this error but I am indeed trying to host a NextJs application. Package.json has the dependency for 
` "next": "12.1.6",` but I'm getting `[ERROR]: !!! CustomerError: Cannot read 'next' version in package.json.`

**Comment by gxxcastillo** [comment]
I think the following worked for me.  I'm stuck on some other issues now, however, so I'm not 100% sure yet if it's going to work: 

```
> aws amplify update-app --app-id {appid} --platform WEB --region {region}
```
