### ISSUE TITLE
Next.js 13 

### ISSUE THREAD

**Issue by basselabbara** [aws-amplify/amplify-hosting#3195]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d113cc0qzdxa93

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Describe the bug

Trying to upload a zip build of Next.js with SSR. It says deployment successful but the environment URL says Access Denied.

### Expected behavior

The URL should show the Next app instead of Access Denied.

### Reproduction steps

1. Go to any environment URL of the app.

### Log output

<details>

```
# Put your logs below this line
2022-12-12T18:21:36 [INFO]: Starting Deployment
2022-12-12T18:21:37 [INFO]: Updating Edge config
n, buildId 0000000008
2022-12-12T18:21:37 [INFO]: Got archive: 29260413 bytes
2022-12-12T18:21:46 [INFO]: Deployment complete

```

</details>

**Comment by hloriana** [comment]
Hi @basselabbara 👋🏽 Apologies for this inconvenience but Amplify Hosting currently doesn't support manually deploying SSR apps: https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html. 

Please follow this guide instead to deploy Next.js apps with Amplify: https://docs.aws.amazon.com/amplify/latest/userguide/deploy-nextjs-app.html

**Comment by lbustelo** [comment]
I wanted to add that this should not be exclusive to NextJS 13... would be great if it supported NextJS 12 as well.

Additionally, it would be great to trigger a deployment from an S3 package using CDK.

**Comment by lbustelo** [comment]
@hloriana I've been having discussions with support about this exact feature. In theory, it seems that there should not be any technical reason why we can't deploy Next JS SSR app using upload of files or S3, as long as the files are organized in some expected way.

It seems that Amplify Hosting does the following:

1. Identifies the type of project it is hosting based on the content. There may be some hardcoded rules based on project source (ie. Git vs S3), but regardless, it seems that these can be modified through CLI

```
aws amplify update-app --app-id <app_id> --platform WEB_COMPUTE
aws amplify update-branch --app-id <app_id> --branch-name <branch_name>  --framework 'Next.js - SSR'
```

2. Build of assets. In terms of Next JS, this would be a next build with some additional AWS specifics steps to build whatever is needed to deploy Lambda@Edge.

3. Infrastructure deployment. S3, CloudFront, Lambda@Edge, IAM, etc...

If I can configure the App properly using commands above and also perform a build on my end that mimics #2, could it be then possible for me to upload the output of that build using Manual approach (DnD files or S3) and trigger #3?

**Comment by yanlin96** [comment]
Hi team,

I did a test with git repo with "web_dynamic". And In the building phase, I notice a new "serverless" folder is generated by Amplify in the ```artifacts.zip``` for the following deployment. 

Looks like the only difference in the ```.next``` and ```artifacts.zip``` is the "serverless" folder. 

Therefore, maybe Amplify could have the ability to know the manually uploaded **zip** files is from Nextjs project in the building phase, then somehow generating the "serverless" folder for the following deployment.

**Comment by FaijanSaifi99** [comment]
> Is it possible to use the ZIP approach in 2023?

i have tried it. but did not work.

**Comment by arturkasperek** [comment]
As a workaround, my CI/CD process push thing to AWS codecommit.
I think it should be possible to upload ZIP to support different CI/CD use cases

**Comment by arturkasperek** [comment]
any update ?

**Comment by tmokmss** [comment]
This feature is highly desired for consistent use of Amplify Hosting from AWS CDK. Given that we can deploy an _SPA_ app from CDK s3 asset to Amplify Hosting ([doc](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-amplify-alpha-readme.html#deploying-assets)), why not for SSR apps?

**Comment by inthegreenwild** [comment]
+1 to this feature I have a case where it would be very benificial to manually deploy a Nuxt 3 app with SSR enabled rather than having to go through ci/cd amplify console

**Comment by haarism** [comment]
> +1 to this feature I have a case where it would be very benificial to manually deploy a Nuxt 3 app with SSR enabled rather than having to go through ci/cd amplify console

It is worth noting that, although not via inbuilt amplify API () it is possible to download the build from an artifact repo like AWS CodeArtifact. Avoiding `@aws-sdk/*` NodeJS SDK  in your webapp build will reduce the total artifact size. And move `@aws-sdk/client-codeartifact` into a different package that can download this using  OIDC federation right permission setup on the amplify role.  I use Next.js ISR and this works just fine.  

But I would still like to see this feature to inbuilt in AWS APIs - aws cli and `aws_amplify_app` terraform.

**Comment by lbustelo** [comment]
Is this still on the radar? Last thing I heard from AWS rep was that this was going to be announced in re:Invent 2023. Came and went. I know AWS does not want to share/commit to roadmaps, but a little bit of news here would help.

**Comment by sundeep-paulraj** [comment]
+1, manual deployment for SSR via zip files would be helpful

**Comment by arturkasperek** [comment]
Any news ?

**Comment by FaijanSaifi99** [comment]
Nope. I had to connect my github repo.

**Comment by wolfgang000** [comment]
+ yes, this is an important feature

**Comment by FaijanSaifi99** [comment]
I recently visited on amplify and i saw the option for manual deployment but only for static site generation.

**Comment by mauerbac** [comment]
Hey everyone -- Matt from the Amplify Hosting team here. @FaijanSaifi99 @wolfgang000 @arturkasperek @sundeep-paulraj @lbustelo @j-boivie-rs @haarism @inthegreenwild 

I know everyone wants an update here! The team is currently scoping this feature and I have a question to ask everyone.

What workflow do you plan to use this feature with? Meaning, we would need the build output to conform to our SSR deployment specification, [listed here](https://docs.aws.amazon.com/amplify/latest/userguide/ssr-deployment-specification.html). Would you expect a CLI tool that you can run so the files are built in the correct format? Or would you add this into your own build pipeline? 

Thank you

**Comment by arturkasperek** [comment]
@mauerbac I prefere an option where I can own full process and build everything on my CI/CD. I think we should just send a ZIP. You can create some standalone tool which will transform nextjs build folder into yours format

**Comment by basselabbara** [comment]
@mauerbac a CLI tool would be awesome. Perhaps one that can package and deploy straight to Amplify.
Thanks!

**Comment by lbustelo** [comment]
@mauerbac Being able to control the build independent of deployment would be ideal. 

1. Use some library from Amplify to build a standard NextJS app into a build output that conforms to what Amplify needs.
2. That build output could them be uploaded to an S3 bucket
3. Use Amplify to configure a new application to deploy the NextJS build from said S3 location

**Comment by haarism** [comment]
@mauerbac  Would you consider the following capabilities:

- The CLI tool can upload a zip file. Guide need on how to structure this for frameworks like Nextjs, and if any monorepo related specifics to be taken care of.

- The CLI tool can to pull artifacts from AWS Artifactory. (Currently, I use custom tooling over `@aws-sdk/client-codeartifact` to pull builds, enabling the Amplify deployment in few minutes compared to NextJS builds (SSG + ISR) that can take 22 min in the 4 core Amplify build lambda)

- Full utilization of external CI/CD platforms are important especially in case of monorepos with fixed versioning bias (e.g., nx.dev). This is in contrast to independent versioning of dependencies that are shared across sites and each site  can  afford to run at an independent pace of development. So this presents edge cases when validating multiple web apps at scale, especially when shared dependencies change. The challenge increases with trunk-based development, where changes need to move to pre-production quickly (from a feature branch to main branch). Small PRs need to be ideally iterated rapidly across pre-production websites. Speed in pipeline automation is essential, and leveraging an external artifactory enables asynchronous pipeline tasks. If Amplify can pull such artifacts, it would greatly accelerate deployment without thinking though custom tooling like I have setup.

**Comment by coye2004** [comment]
@mauerbac, Hi any good news?

**Comment by osama-rizk** [comment]
Hey everyone — quick update relevant to this thread. The Amplify Gen2 team just opened a developer-preview RFC for `defineHosting()` + `ampx deploy` that covers the workflow being asked for here: build SSR apps on your own CI/CD — GitHub Actions, GitLab CI, Jenkins, or local — and ship them to your AWS account without going through a managed build pipeline.

Full SSR feature support across the board — Next.js (ISR, image optimization, streaming RSC), Nuxt (SWR, image optimization, streaming), Astro (SSR + islands, image optimization, streaming) — no compromises vs. the managed path.

There's also a standalone CDK construct (`AmplifyHostingConstruct`) for the deploy-from-S3-asset use case mentioned by @tmokmss and @lbustelo.

**You only need these 3 steps:**

**1. Install**

```bash
npm install @aws-amplify/hosting@iac-hosting @aws-amplify/backend-cli@iac-hosting @aws-amplify/backend@iac-hosting
```

**2. Add an `amplify/hosting.ts`**

```ts
import { defineHosting } from '@aws-amplify/hosting';

defineHosting();
```

**3. Ship it**

```bash
npx ampx deploy --identifier my-app
```

That's it — your SSR app is deployed to your AWS account, framework auto-detected from `package.json`, no console click-through required.

Full RFC with examples and a place to leave feedback: https://github.com/aws-amplify/amplify-backend/issues/3211

Developer preview, so APIs may still shift. To be clear: this is a **self-managed** path — separate from the existing Amplify Hosting console product. You own the CloudFormation stack, the resources sit in your AWS account, and you deploy with your own CI/CD. The managed Amplify Hosting in the console continues to work as it does today; this is an additional option, not a replacement. Please try it and let us know in the RFC if something in your workflow (monorepo layout, CodeArtifact pull, etc.) isn't covered.

cc @basselabbara @lbustelo @yanlin96 @arturkasperek @FaijanSaifi99 @tmokmss @inthegreenwild @haarism @j-boivie-rs @sundeep-paulraj @wolfgang000 @coye2004 @artemudovyk @dwil618 @mohamed-ali @MustaRohman @nebbles @richard-jfc @SanteeMarcel @Aerophite @alexabidri @andrey59412678 @bmickan-amazon @christowiz @constantinehuzenko @dnsorlov @douglassanttech @drevisios @EmmanuelRTM @GanatraJay2000 @girdharsoni @goguda @gregorymfoster @heliocosta-dev @higher68 @jasmeen-goyani-scaletech @johnwheeler @juulchin @karlas @karopolopoulos @lkabell @matusfaro @Mettiu88 @mhfortuna @MilanMercantile @mtan11 @nick-infinitegiving @nicolello-dev @nicopadu @nrmohan @RussellBloxwich @samp-reston @shann-dev @shixiaobao17145 @skazantsev @Souhib @syed-yawar @tamiradler @tfluehr @tomoiti @uhDann @mauerbac

**Comment by arturkasperek** [comment]
@osama-rizk it's too late - I already migrated to something else. AWS is too slow in adding new things

**Comment by osama-rizk** [comment]
Hey @arturkasperek ,
Totally understandable. Sorry to hear that you needed to migrate to something else. We'll keep your feedback in mind as we continue building this out. If your needs change down the line, the [RFC](https://github.com/aws-amplify/amplify-backend/issues/3211) is open and we'd love your input.
