### ISSUE TITLE
404 Errors on most static pages in a Next JS 13 app

### ISSUE THREAD

**Issue by april-swellfox** [aws-amplify/amplify-hosting#3198]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

Node 16

### Amplify CLI Version

10.5.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

NO manual changes made.

### Describe the bug

I'm using Next 13 app. I recently updated a minor change in the april branch and the build was successful. The change should not affect the visibility of the pages because it's just about font optimization. But then some static pages get 404 errors. The main branch works fine since I didn't update it. I don't know their difference apart from the minor update.

It works well in my local computer. It's only in the april branch amplify app that's having this issue.

![404errors](https://user-images.githubusercontent.com/80304413/207251318-99bab968-1227-460e-96dc-eb67774f522c.jpg)

### Expected behavior

The static pages should load, not 404

### Reproduction steps

1. Git pushed to trigger Amplify build.
2. Main page works - https://april.dk0lb4vk3xvnt.amplifyapp.com/
3. Sub page works - https://april.dk0lb4vk3xvnt.amplifyapp.com/connector 
4. All  sub of sub pages don't work  (404):
examples:
- https://april.dk0lb4vk3xvnt.amplifyapp.com/connector/suppliers/te-connectivity-amp-brand
- https://april.dk0lb4vk3xvnt.amplifyapp.com/connector/articles/the-importance-of-connectors
- https://april.dk0lb4vk3xvnt.amplifyapp.com/connector/suppliers/bulgin-limited
- https://april.dk0lb4vk3xvnt.amplifyapp.com/relay/articles/questions-to-ask
- https://april.dk0lb4vk3xvnt.amplifyapp.com/relay/articles/about-relay-guide
- https://april.dk0lb4vk3xvnt.amplifyapp.com/relay/suppliers/american-zettler

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ferdingler** [comment]
Hi @april-swellfox, by any chance, are you using the new `appDir` feature of NextJS? If so, they have recently fixed this issue in their canary release, but is not yet on the main stable release. Here is more information on this particular issue: https://github.com/vercel/next.js/issues/42812#issuecomment-1313287665.

**Comment by april-swellfox** [comment]
@ferdingler No, I'm still using the `pages` dir since the `app` is still in beta. They don't recommend using that in production.

**Comment by april-swellfox** [comment]
Hi. Is there any update on this?

**Comment by april-swellfox** [comment]
Hi again. I double checked the build output and it correctly generated the static pages. I debugged my code and found out that the issue is in my getStaticProps() code. Sorry.
