### ISSUE TITLE
Preview builds failing with error code 128

### ISSUE THREAD

**Issue by amplitude-dev-docs** [aws-amplify/amplify-hosting#3199]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d19s7xzcva2mw3

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments, Frontend builds

### Describe the bug

Preview builds are failing for a public repo. Everything was working up until this morning, and as far as I know, nothing changed with our configuration.

First I tried opening a new PR, then I tried removing and re-installing the GitHub Amplify App, and I've tried to reconnect the repo several times.

### Expected behavior

I expect the PR previews to build successfully. 

### Reproduction steps

1. Open a PR. 
2. Wait for the build to fail and return at 128 error. 

### Build Settings

```yaml
version: 1.0
frontend:
  phases:
    # IMPORTANT - Please verify your build commands
    preBuild:
      commands:
        - python3 -m pip install --upgrade pip
        - python3 -m pip install -r requirements.txt
        - pip3 install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git@8.5.6-insiders-4.25.0
    build:
      commands:
        - mkdocs build -f insiders.mkdocs.yml
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: site
    files:
      - '**/*'
  cache:
    paths: []
```

### Log output

<details>

```
# Put your logs below this line


2022-12-13T17:55:26.550Z [INFO]: # Cloning repository: git@github.com:Amplitude-Developer-Docs/amplitude-dev-center.git
2022-12-13T17:55:28.936Z [INFO]: 
2022-12-13T17:55:28.938Z [INFO]: Cloning into 'amplitude-dev-center'...
2022-12-13T17:55:29.066Z [INFO]: fatal: couldn't find remote ref pull/451/head
2022-12-13T17:55:29.101Z [INFO]: Successfully cleaned up Git credentials
2022-12-13T17:55:29.102Z [ERROR]: !!! CustomerError: Unable to clone repository due to user error code: 128
2022-12-13T17:55:29.102Z [INFO]: # Starting environment caching...
2022-12-13T17:55:29.680Z [INFO]: # Environment caching completed
Terminating logging...

```

</details>

**Comment by ferdingler** [comment]
Hi, this issue was caused due to a GitHub incident with Pull Requests: https://www.githubstatus.com/incidents/4p7zympgsr86. They have mitigated the problem.
