### ISSUE TITLE
How to resolve net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep 200 on my react app hosted on AWS amplify

### ISSUE THREAD

**Issue by rahulkohli23** [aws-amplify/amplify-hosting#3201]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Step

Domain is working fine

### Status

Success

### Issue or question

This seems to be an issue with Cross domain script loading. As I am trying to integrate my react app with a payment gateway Paytm which opens up a checkout page, but this issue is blocking the same.

Need help on this

### Error message

net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep 200

**Comment by ferdingler** [comment]
Hi @rahulkohli23, how is this issue related to Amplify? Without details about your App, Region or Steps to reproduce there is not much we can do to help.

**Comment by hloriana** [comment]
Hi @rahulkohli23 👋🏽 if you are experiencing an issue with an Amplify Hosting related feature, please open a new issue with the bug report template. Be sure to include your app ID, reproduction steps, a description of the bug and what the expected behavior is. These details will help us to investigate your issue.
