### ISSUE TITLE
Nightwatch tests not working in parallel from CI requiring us to run them in serial causing TokenExpired error

### ISSUE THREAD

**Issue by austinamorusoyardstick** [aws-amplify/amplify-hosting#3204]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2t0beklulssyh

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Describe the bug

When running tests in nightwatch parallel against aws device farm causes tests to fail randomly. Running test in serial allows test to pass however the ExpiredToken exception is throw so tests don't have time to finish. Currently only have half our nightwatch tests completed and they take over 1 hour 15 minutes. The 1 hour limit for calling aws resources within the build pipeline is not long enough. 

### Expected behavior

Tests pass without ExpiredToken error allowing build to pass and not fail. 

### Reproduction steps

1. make a build run longer than 1 hour
2. watch the error and the build fail

### Log output

<details>

```
ExpiredTokenException: The security token included in the request is expired


```

</details>

### Additional information

 https://github.com/aws-amplify/amplify-hosting/issues/2751

**Comment by austinamorusoyardstick** [comment]
We are running tests that create users and intercept emails so there is a non trivial amount of time that tests tests take even without the parallel vs serial issue.

**Comment by hloriana** [comment]
Hi @austinamorusoyardstick I just responded to your comment in #2751:

> ...the 60 minute timeout is a hard limit at this time. Unfortunately there is no workaround for this but the team is aware of this limitation and are tracking this in our product backlog. We apologize for this inconvenience.

Closing this issue as a duplicate oof #2751.
