### ISSUE TITLE
Amplify redirects and rewrites behaviors

### ISSUE THREAD

**Issue by McCo0L** [aws-amplify/amplify-hosting#3206]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

do7s4dygb19e8

### AWS Region

us-east-2

### Amplify Hosting feature

SSR

### Question

We are moving our application from Next11  to Next13 and deploying to Amplify. Before this we were using a customized cloudfront to take care of all our redirects as we need some path to go to different application behind an ALB. We want to keep that behavior with amplify the Next13 application seems fine but the redirects just show:
```
502 ERROR
The request could not be satisfied.
CloudFront wasn't able to connect to the origin. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

Generated by cloudfront (CloudFront)
```
We cannot find a way to customize that Cloudfront distribution as it's a managed one that we are not able to access through our console. 

Is there a way to modify the behaviors for the rewrites and redirects or at least to be able to use a custom Cloudfront distribution for our amplify deployment?

**Comment by McCo0L** [comment]
is there a way to do this?

**Comment by hloriana** [comment]
Hi @McCo0L 👋🏽 apologies for the delay here. Our support for Next.js 12 and 13 applications offers fully managed infrastructure to reduce operational overhead. The CloudFront distribution associated with your application is managed by Amplify and are not customizable at this time.

Modifying CloudFront distributions is currently only possible with Next.js 11 apps. If your app was previously deployed using Next.js 11, then you can follow [these instructions ](https://docs.aws.amazon.com/amplify/latest/userguide/update-app-nextjs-version.html#revert-ssr-migration)to revert the migration: We apologize for this inconvenience.
