### ISSUE TITLE
Server Not Found

### ISSUE THREAD

**Issue by Christian-Pickett** [aws-amplify/amplify-hosting#3207]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-west-2:718447578190:apps/d1wxopx0ls5nh9

### Region

us-west-2

### Step

custom domain redirection

### Status

Server Not Found

### Issue or question

Hello, I believe I have the same issue as is described in the closed issue #2846 [](https://github.com/aws-amplify/amplify-hosting/issues/2846) or  #2860

When I run my app locally, or indeed if I use the original amplifyapp.com URL that it started with, before I added the custom domain, everything works fine. But if I try to use the custom domain from Route 53, then I see the Server Not Found error. 

I tried disabling and re-enabling the custom domains in the domain management screen as suggested in issue #2846 but that was unsuccessful in fixing the issue. I have another very similar simple app besides the given App Id and they both exhibit the same problem. 

Thanks for any advice or help you can give.

**Comment by hloriana** [comment]
Hi @Christian-Pickett 👋🏽 thanks for raising this issue. We need some more information to understand why the custom domain is not resolving:
1. Are there any errors that display in your domain management settings in the Amplify console? If so please share a screenshot.
2. Amplify should have automatically added CNAME records to the hosted zone for your Route53 domain. Can you navigate to your Route53 hosted zone and confirm those records exist?

**Comment by Christian-Pickett** [comment]
Hello @hloriana, thanks for looking at my issue. Here is what my domain management settings page in the Amplify console looks like:
![ptmgmt](https://user-images.githubusercontent.com/37274353/208974123-000f4824-501e-44f3-9c12-9c4368d64b4f.png)

and here is what the route53 hosted zone looks like:

![53ptMgmt](https://user-images.githubusercontent.com/37274353/208974210-c59d8d07-bf7e-4c07-a8ab-aa8a2400a833.png)

**Comment by Christian-Pickett** [comment]
Sorry, I did not mean to close the issue with my last comment.
