### ISSUE TITLE
502 error on NextJs using SSR. Lambda function returns invalid response exceeds size limit of 1mb.

### ISSUE THREAD

**Issue by pruthviraj-developer** [aws-amplify/amplify-hosting#3214]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2kggzonkc0z6

### AWS Region

ap-south-1

### Amplify Hosting feature

Frontend builds

### Question

We are using AWS amplify for building and hosting our react- next js application, we are using SSR.
Some of the urls are giving the below error.

The request could not be satisfied.
The Lambda function result failed validation: The body is not a string, is not an object, or exceeds the maximum size. See Limits in the Amazon CloudFront Developer Guide. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: mzyamzcKVRu15qDa3iSsycS8tiVpkR9HbAGV8NFCikZ5sJSS9pA8rw==

In  Logs- we are getting the error as - ERROR Validation error: The Lambda function returned an invalid response, the length of the body and header was 1.5mb bytes which exceeds the cloudfront limit of 1mb  bytes on the maximum length of the request  including the body size and headers .

Please help us to resolve the same.

**Comment by pruthviraj-developer** [comment]
Hi @calavera 

Will the above issue be resolved once we move to Next-Js 13 version, as of now we are using the Next-Js 11 version.

**Comment by pruthviraj-developer** [comment]
Thank you @calavera

**Comment by dchanmaisonette** [comment]
@calavera Does it mean if we don't move it, we'll continue to have this issue?  We're running nextJS 10 and this just started happening in the past couple days.

**Comment by Jay2113** [comment]
@dchanmaisonette 👋 , as stated [here](https://github.com/aws-amplify/amplify-hosting/issues/3214#issuecomment-1366200710) the issue can be resolved by migrating over to Amplify Hosting compute. Also, I'll recommend reviewing the following documentation:
- Amplify Classic or `Web_Dynamic` platform support: https://docs.aws.amazon.com/amplify/latest/userguide/ssr-nextjs11-support.html
- Migration guide to Compute or `Web_Compute` platform: https://docs.aws.amazon.com/amplify/latest/userguide/update-app-nextjs-version.html
