### ISSUE TITLE
Nextjs api routes

### ISSUE THREAD

**Issue by atef-abdellatif** [aws-amplify/amplify-hosting#3215]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3vjdfceexw7fw

### AWS Region

eu-west-2

### Amplify Hosting feature

Deployments

### Question

Hi, I deployed nextjs SSR v12.2.3 to AWS Amplify but I can't access api routes (myDomain/api/example). I'm fetching data from MongoDB database and im using nextjs built-in api (pages/api).

**Comment by antonicasasayas** [comment]
Did you find a solution?

**Comment by atef-abdellatif** [comment]
Not yet!

**Comment by hloriana** [comment]
Hi @atef-abdellatif, apologies for the delay in response here. Have you taken a look at your Hosting compute logs in the console? When you try to access the api routes, what errors are you seeing?
