### ISSUE TITLE
the Backend points to a different env

### ISSUE THREAD

**Issue by CLu1s** [aws-amplify/amplify-hosting#3219]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dcg64l50n907n

### AWS Region

us-east-1

### Amplify Hosting feature

Backend builds

### Question

How do I change or confirm where my backend API and authentication are pointing?

Recently I migrated to next12 amplify config, and amplify realized an automated build of my main branch, but when I tried to log in, it says that my pool client does not exist but is showing an old deleted pool client id, 
I checked that my backend environment was pointing to the correct API and auth AWS apps, and it is, but when I visit my site, it still shows that my credentials are not valid because my pool client does not exist. I need to figure out how to revert or change to which environment my frontend points.
![image](https://user-images.githubusercontent.com/5587538/210107659-2ae3b36c-47f7-4eca-9a0a-0f36d92e1a0f.png)

**Comment by hloriana** [comment]
Hi @CLu1s 👋🏽 thanks for raising this issue. If your old user pool that has your credentials still exists, you can import that user pool via the Amplify CLI. Please follow our documentation for how to import that user pool:

- [Unlink an existing Cognito User Pool or Identity Pool](https://docs.amplify.aws/cli/auth/import/#unlink-an-existing-cognito-user-pool-or-identity-pool)
- [Import an existing Cognito User Pool](https://docs.amplify.aws/cli/auth/import/#import-an-existing-cognito-user-pool)
