### ISSUE TITLE
404 for dynamic routes with Next.js - SSR

### ISSUE THREAD

**Issue by cehret** [aws-amplify/amplify-hosting#3221]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2acxb4ntzp7r3

### AWS Region

eu-central-1

### Amplify Hosting feature

Deployments, Frontend builds, SSR

### Question

Hello,

I started a app using next.js, react.js for building a frontend for a headless CMS. As the page structure is maintained in the CMS I wrote a [[...slug]].js with getStaticPaths and getStaticProps to generate the slugs from the CMS.

The App runs locally with WebStrom without problems. I created a new AWS Amplify App connecting the GIT repository. Everything works fine - build and deployment is done. I even connected a Subdomain for testing.  BUT in the frontend the dynamic routes do not work - I always get a 404 Error: https://react.toco3.dev/ - if I use a static route e.g. https://react.toco3.dev/api/hello it is working. 

I also connected the same repository to vercel and the frontend is working like in my local environment: https://t3-react.vercel.app/

So my question is: what am I missing? 
I think amplify got the right settings: Next.js - SSR! Could it be the node version? I'm using 18 in my local environment and I think vercel uses 18, too. I tried to use another build-image to have 18 in Amplify - but the same behavior in the frontend - so I switched back to the Standard-Image.

I really would like to use Amplify and hope that someone has an idea whats going wrong here!
If you need any further information I'm happy to share!

Thank you!

**Comment by cehret** [comment]
I investigated some more: 
the dynamic routing works in generell with the Internationalized Routing Feature of next.js 13. I put a simple [pid].js in /pages/test and I can call it:  

https://react.toco3.dev/test/1234
https://react.toco3.dev/it/test/1234

This one does not work, which is ok, because I did not add "jp" to next.config:
https://react.toco3.dev/jp/test/1234

So the problem seems that my [[...slug]].js is not interpreted correctly?!

**Comment by jeremiah-quill** [comment]
I am experiencing the same behavior, but with pages which look like: 

```
/[slug].jsx
```

**Comment by nadetastic** [comment]
Hi @cehret following up on this issue. This may have been an issue with how your Rewrites and Redirects are configured - however it looks like the APP ID you shared may have been deleted. Can you let me know if you are still having this issue, and if so share the APP ID or rewrites configuration?

@jeremiah-quill for your scenario, could you also share your APP ID or rewrites/redirects?

**Comment by nadetastic** [comment]
@jeremiah-quill following up with you here - could you share your APP ID so I can investigate further?
