### ISSUE TITLE
Urgent! Can't find cloud-front for new amplify with nextjs-13

### ISSUE THREAD

**Issue by aungbobotun** [aws-amplify/amplify-hosting#3232]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2og1m4tmjf057

### Region

Global

### Step

Fetching cloudfront

### Status

Failed

### Issue or question

I don't know but it's so urgent. please some one from amplify reply

**Comment by hloriana** [comment]
Hi @aungbobotun 👋🏽 can you describe the issue that you are running into so that we can provide you with assistance?
