### ISSUE TITLE
Create domain association failed

### ISSUE THREAD

**Issue by jiteshsrivastava** [aws-amplify/amplify-hosting#3234]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

ap-south-1

### Step

domain activation

### Status

Failed

### Issue or question

I deleted the previous Ampily application still Error occurred.
Kindly resolved my issue.

### Error message

Create domain association failed
One or more domains requested are already associated with another Amplify app: www.gurukulacademylko.in, gurukulacademylko.in

**Comment by hloriana** [comment]
Hi @jiteshsrivastava apologies for the delay here. Can you provide the app ID of the Amplify app you are trying to associate the domain with?
