### ISSUE TITLE
Next Image optimisation

### ISSUE THREAD

**Issue by stanleyagius** [aws-amplify/amplify-hosting#3238]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2rkde9qah37u7

### AWS Region

eu-central-1

### Amplify Hosting feature

SSR

### Question

I am trying to use next/image optimisation for an app that displays images from an S3 bucket.  Everything works fine locally but the images do not show up when served from amplify.  If I check the payload from network traffic, the link is fine and I can open it but it fails to render on the page, getting error 400 - "url" parameter is valid but upstream response is invalid.  The error on cloudwatch is upstream image response failed for...  I am using Next 13 and Amplify should support it - https://youtube.com/watch?v=jwjF4YY5OLE&feature=shares. My suspicion is that in this video he grabs the images using getServerSideProps, did anyone manage to get next/image optimisation to work by querying for remote images client side?

**Comment by hloriana** [comment]
Hi @stanleyagius 👋🏽 thanks for raising this issue. We apologize for this inconvenience. We were able to reproduce this issue and are currently working towards mitigating this behavior. We will update this issue once we have resolved this.

**Comment by oliver-leung** [comment]
Hi @stanleyagius, we've patched the issue - please let me know if you're still seeing that error

**Comment by stanleyagius** [comment]
> Hi @stanleyagius, we've patched the issue - please let me know if you're still seeing that error

It is working like a charm.  Thanks a million
