### ISSUE TITLE
next image can't access ,return 500

### ISSUE THREAD

**Issue by caoli4608** [aws-amplify/amplify-hosting#3239]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3p618zu81pm7z

### AWS Region

us-east-1

### Amplify Hosting feature

SSR

### Describe the bug

if i use next image tag ,the images can't access.and server return 500 error !
for exmaple :https://main.d3p618zu81pm7z.amplifyapp.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fms.6817b6df.png&w=640&q=75.

i have try on local. everything is ok.

### Expected behavior

the server return image

### Reproduction steps

![image](https://user-images.githubusercontent.com/13860181/212521445-00822365-fe0e-45ae-8832-808e8fec7619.png)

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriana** [comment]
Hi @caoli4608 👋🏽 can you check your access logs and see if Lambda is returning any error logging? You can find these logs by navigating to **Monitoring** -> **Hosting compute logs** -> select the log group under **CloudWatch log streams**.

**Comment by caoli4608** [comment]
Thans, There is an error ,I have fix it . The nextjs has conflict with amplify.  can refer :https://github.com/vercel/next.js/issues/34134
