### ISSUE TITLE
Deploy of new Amplify app removed data of unrelated app

### ISSUE THREAD

**Issue by daannijkamp** [aws-amplify/amplify-hosting#3240]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1jny8zesq8m5c

### AWS Region

eu-west-1

### Amplify Hosting feature

Backend builds

### Describe the bug

We deployed a new app in AWS Amplify.
In this deploy the backend of an unrelated app (d1nyxy0mujwrun) is overwritten and all resources in this app are deleted (DynamoDB backend tables for GraphQL API)

### Expected behavior

Deploys of new apps should not modify unrelated apps 

### Reproduction steps

1. Create new app
2. Deploy

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriana** [comment]
Hi @daannijkamp 👋🏽 we are sorry to hear that backend resources were accidentally deleted. Can you provide more details around the application you deployed? Was that application using the backend environment in that separate application?  We are working to reproduce this behavior and further investigate.

**Comment by hloriana** [comment]
We were unable to reproduce this behavior. Please open a new issue if you continue to run into this issue or if you can provide more details on how you ran into this behavior. Closing due to no response.
