### ISSUE TITLE
unable to upload website 

### ISSUE THREAD

**Issue by ptha3** [aws-amplify/amplify-hosting#3241]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

 arn:aws:amplify:ap-southeast-2:503845996473:apps/d29eg33fjwtte8

### Step

showing error message on website

### Status

failed

### Issue or question

When uploading the website - getting the below error message. The previous version of website is working correctly.

### Error message

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>2TTQHEYYZ8XHSGQR</RequestId>
<HostId>DVvy4XJ9/WNJ7y0d5qy8xa7dyAF52jqEaKag39Y+0ZcadP0zA1K/Azwf8ozHXqY95rXpptowQVE=</HostId>
</Error>

**Comment by hloriana** [comment]
Hi @ptha3 👋🏽 did you zip the contents of the build output folder? If you zip the folder itself then you will run into the error you described which is noted in our documentation: [Manual Deploys with Amplify Hosting](https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html). Please follow these instructions:

> When you create the zip folder, make sure you zip the contents of your build output and not the top level folder. For example, if your build output generates a folder named “build” or “public”, first navigate into that folder, select all of the contents, and zip it from there. If you do not do this, you will see an “Access Denied” error because the site's root directory will not be initialized properly.
