### ISSUE TITLE
custom domain not working 

### ISSUE THREAD

**Issue by bigtechsolution** [aws-amplify/amplify-hosting#3243]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

ap-northeast-2

### Step

custom domain create

### Status

Available

### Issue or question

I created a shop branch with amplify and 

I am able to access it through https://shop.dl396hvgnkwcx.amplifyapp.com/

but when I set up a custom domain shop.collexx.io, I am unable to access it and nslookup shows 

DNS_PROBE_FINISHED_NXDOMAIN status. 

However, the other branch beta  

https://beta.collexx.io 

is working normally. 

Can you tell me the reason why shop.collexx.io is not working?

And How to fix it?

### Error message

yes 

### Additional information

appid : dl396hvgnkwcx
hosting: NEXTJS 13

**Comment by hloriana** [comment]
Hi @bigtechsolution 👋🏽 thanks for raising this issue. Can you try removing the subdomain and adding it back to see if that gets the subdomain to resolve properly? In the mean time, we are continuing to investigate this behavior.

**Comment by bigtechsolution** [comment]
I follow thease steps

1. i remove branch shop first
2. i re generate branch shop again
3. i generate sub domain  shop.collexx.io  

I follow thease steps

1. i remove branch shop first
2. i re generate branch shop again
3. i generate sub domain  https://shop.collexx.io  

Do you find any clue ?

> Hi @bigtechsolution 👋🏽 thanks for raising this issue. Can you try removing the subdomain and adding it back to see if that gets the subdomain to resolve properly? In the mean time, we are continuing to investigate this behavior.

**Comment by bigtechsolution** [comment]
any update on this issue?

**Comment by GabrielBuenoAzevedo** [comment]
I also need some help with this issue. I'm on this exact situation with a new branch using a new subdomain on a previously registered domain

**Comment by Jay2113** [comment]
Apologies for the delayed response on the issue. @bigtechsolution Can you confirm for us if you have the appropriate CNAME record configured in your DNS provider for the shop.collexx.io subdomain? It should be a CNAME record pointing to a CloudFront distribution. 

@GabrielBuenoAzevedo Can you confirm the same for your subdomain? Also, kindly provide us your Amplify App ID.
