### ISSUE TITLE
Create domain association failed One or more domains requested are already associated with another Amplify app: etaop.in

### ISSUE THREAD

**Issue by xabhi7549** [aws-amplify/amplify-hosting#3253]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

duwsx28ik9714

### Region

ap-south-1

### Step

Domain Add

### Status

Create domain association failed One or more domains requested are already associated with another Amplify app: etaop.in

### Issue or question

Create domain association failed One or more domains requested are already associated with another Amplify app: etaop.in

What I am doing wrong?

### Error message

Create domain association failed One or more domains requested are already associated with another Amplify app: etaop.in

### Additional information

Create domain association failed One or more domains requested are already associated with another Amplify app: etaop.in

**Comment by hloriana** [comment]
Hi @xabhi7549 👋🏽 it looks like the domain has been successfully associated with your Amplify application and is properly hosting your application. Do you need further assistance?

**Comment by xabhi7549** [comment]
Hi @hloriana , I able to add www.etaop.in not etaop.in
