### ISSUE TITLE
The "path" argument must be of type string. Received undefined - Backend Build  After adding Auth

### ISSUE THREAD

**Issue by kaomartin** [aws-amplify/amplify-hosting#3255]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1mrumpxmhxq7m

### AWS Region

us-west-2

### Amplify Hosting feature

Backend builds

### Describe the bug

> 2023-01-21T19:51:40.700Z [INFO]: # Cloning repository: git@github.com: <blah blah>
> 2023-01-21T19:51:42.304Z [INFO]: 
> 2023-01-21T19:51:42.307Z [INFO]: Cloning into 'BlahBlah'...
> 2023-01-21T19:51:42.307Z [INFO]: # Switching to commit: 87c32d05056503b8cdfecd4998738b4474303ea1
> 2023-01-21T19:51:42.322Z [INFO]: Note: switching to '87c32d05056503b8cdfecd4998738b4474303ea1'.
>                                  You are in 'detached HEAD' state. You can look around, make experimental
>                                  changes and commit them, and you can discard any commits you make in this
>                                  state without impacting any branches by switching back to a branch.
>                                  If you want to create a new branch to retain commits you create, you may
>                                  do so (now or later) by using -c with the switch command. Example:
>                                  git switch -c <new-branch-name>
>                                  Or undo this operation with:
>                                  git switch -
>                                  Turn off this advice by setting config variable advice.detachedHead to false
>                                  HEAD is now at 87c32d0 Debug amplify build
> 2023-01-21T19:51:42.352Z [INFO]: Successfully cleaned up Git credentials
> 2023-01-21T19:51:42.353Z [INFO]: # Checking for Git submodules at: /codebuild/output/src149049828/src/<myapp>/.gitmodules
> 2023-01-21T19:51:42.361Z [INFO]: # Retrieving environment cache...
> 2023-01-21T19:51:42.808Z [INFO]: # Retrieved environment cache
> 2023-01-21T19:51:42.808Z [INFO]: ---- Setting Up SSM Secrets ----
> 2023-01-21T19:51:42.808Z [INFO]: SSM params {"Path":"/amplify/d1mrumpxmhxq7m/staging/","WithDecryption":true}
> 2023-01-21T19:51:42.862Z [INFO]: # Determining if there are buildable backend changes in the amplify directory of the repository...
> 2023-01-21T19:51:42.905Z [INFO]: # Last built commit: dfbe411b136136edc0f86812da69a1022539dff3
> 2023-01-21T19:51:42.915Z [INFO]: # Differences detected.
> 2023-01-21T19:51:42.915Z [INFO]: # Continuing with backend build...
> 2023-01-21T19:51:42.915Z [INFO]: # Defaulting to Node version 16
> 2023-01-21T19:51:51.548Z [INFO]: # Node version 16 is available for installation
> 2023-01-21T19:51:51.646Z [INFO]: # Installing Node version 16
> 2023-01-21T19:51:58.307Z [INFO]: # Now using Node version 16
> 2023-01-21T19:51:59.446Z [WARNING]: Cannot find module '/root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/package.json'
>                                     Require stack:
>                                     - /snapshot/AWSMobilePioneerExecute/out/index.js
> 2023-01-21T19:51:59.446Z [INFO]: # Patching NPM package '@aws-amplify/cli' to 10.6.2...
> 2023-01-21T19:52:06.032Z [INFO]: # Done patching NPM package '@aws-amplify/cli' to version 10.6.2
> 2023-01-21T19:52:06.123Z [INFO]: # Retrieving cache...
> 2023-01-21T19:52:11.506Z [INFO]: # Extracting cache...
> 2023-01-21T19:52:20.649Z [INFO]: # Extraction completed
> 2023-01-21T19:52:20.782Z [INFO]: # Retrieved cache
>        # Starting phase: build
> 2023-01-21T19:52:34.726Z [INFO]: [0mAmplify AppID found: d1mrumpxmhxq7m. Amplify App name is: BlahBlah[0m
> 2023-01-21T19:52:34.788Z [INFO]: [0mBackend environment staging found in Amplify Console app: BlahBlah[0m
> 2023-01-21T19:52:35.315Z [WARNING]: - Fetching updates to backend environment: staging from the cloud.
> 2023-01-21T19:52:35.800Z [WARNING]: - Building resource api/amplifyDatasource
> 2023-01-21T19:52:35.801Z [WARNING]: - Building resource auth/BlahBlahc8a96b08
> 2023-01-21T19:52:35.925Z [WARNING]: ✔ Successfully pulled backend environment staging from the cloud.
> 2023-01-21T19:52:36.007Z [INFO]: ✅
> 2023-01-21T19:52:37.637Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
> 2023-01-21T19:52:38.923Z [WARNING]: - Initializing your environment: staging
> 2023-01-21T19:52:39.492Z [WARNING]: - Building resource api/amplifyDatasource
> 2023-01-21T19:52:39.492Z [WARNING]: - Building resource auth/BlahBlahc8a96b08
> 2023-01-21T19:52:39.609Z [WARNING]: ✔ Initialized provider successfully.
> 2023-01-21T19:52:39.683Z [WARNING]: ✖ There was an error initializing your environment.
> 2023-01-21T19:52:39.683Z [INFO]: 🛑 The "path" argument must be of type string. Received undefined
>                                  Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
> 2023-01-21T19:52:39.685Z [INFO]: Session Identifier: fbdbe50a-3196-454e-9a8c-2ab56dce7287
> 2023-01-21T19:52:39.980Z [ERROR]: !!! Build failed
> 2023-01-21T19:52:39.980Z [ERROR]: !!! Non-Zero Exit Code detected
> 2023-01-21T19:52:39.980Z [INFO]: # Starting environment caching...
> 2023-01-21T19:52:39.981Z [INFO]: # Uploading environment cache artifact...
> 2023-01-21T19:52:40.107Z [INFO]: # Uploaded environment cache artifact
> 2023-01-21T19:52:40.107Z [INFO]: # Environment caching completed
> Terminating logging...

I am able to `amplify push` and build and run locally and it works just fine, however the amplify hosting pipeline is failing.   I saw another post with a similar error using auth [Here](https://github.com/aws-amplify/amplify-hosting/issues/2306) - and it was suggested I move the location of the auth's parameters json file out of the /build folder.   I've tried that as well and it still produces the same result.    I am not able to get detailed error messages in my logs like the post I just linked either, but I'm assuming something similar is happening.

I have two backends defined, and two hosting locations defined.   a staging and prod - I am only building the staging host, and my resources deploy on the staging backend. 

### Expected behavior

I expected the build to success and my application hosted.    

### Reproduction steps

- Create an amplify react project using amplify 10.6.2
- Connect to GitHub
- Create two hosting environments (prod, stage)
- Create two backends (prod, stage)
- Create a dummy API, deploy to both prod and stage.   This should all work fine.  Did for me.
- Checkout the stage envionment with amplify
- Add auth with amplify
- Just using the basic template with username/email.
- Amplify push
- Commit code to your staging branch or attempt to build your newly committed code in GitHub

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriana** [comment]
Hi @kaomartin 👋🏽 thanks for raising this issue. Can you confirm if `amplify/backend/api/<api-name>/cli-inputs.json` exists in your repository? If not, try following the mitigation steps outlined in this issue: https://github.com/aws-amplify/amplify-cli/issues/11724#issuecomment-1397718764

Please let me know if this is not the case and I will continue to investigate this error.

**Comment by kaomartin** [comment]
> Hi @kaomartin 👋🏽 thanks for raising this issue. Can you confirm if `amplify/backend/api/<api-name>/cli-inputs.json` exists in your repository? If not, try following the mitigation steps outlined in this issue: [aws-amplify/amplify-cli#11724 (comment)](https://github.com/aws-amplify/amplify-cli/issues/11724#issuecomment-1397718764)
> 
> Please let me know if this is not the case and I will continue to investigate this error.

this fixed the build issue, thank you!
