### ISSUE TITLE
My Website update is not showing as domain is located in "Master"

### ISSUE THREAD

**Issue by arefin69** [aws-amplify/amplify-hosting#3256]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

616760714404

### AWS Region

us-east-1

### Amplify Hosting feature

Not Applicable

### Question

My Gitlab is connected to "Main" and "Master". When I deploy, Main is showing update but Master is not working. https://main.d1niglopqvvk62.amplifyapp.com/home this link is located in Main. But https://snah.org/ is not showing updates which is located in Master. How can i change to from Master to Main? or How can i see update in Master?

**Comment by hloriana** [comment]
Hi @arefin69 👋🏽 thanks for reaching out with this issue. It looks like your master branch was building the same commit for each deployment. Can you try to push a new commit to the master branch and make sure that Amplify is building using the latest commit? You can verify this by checking the **last commit message** in the console or by checking the build logs to see the commit ID under the **Clone repository** logs.
