### ISSUE TITLE
Automatic sub domain creation for multi level custom domain

### ISSUE THREAD

**Issue by samanmohamadi** [aws-amplify/amplify-hosting#3257]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3fwj1dkns35sh

### Region

us-west-2

### Step

-

### Status

Available

### Issue or question

The option _"Automatically create subdomains for branch names that match a pattern"_ is disappeared for multi-level domains.

steps to reproduce:

1. add a multi-level domain e.g app1.mydomain.com
2. wait until domain verification passed
3. go to manage subdomains
4. there is no option for **Automatically creating subdomains**

### Error message

-

### Additional information

I don't know if it's a bug or it has been removed intentionally.

**Comment by hloriana** [comment]
Hi @samanmohamadi thanks for raising this question. You can only setup automatic subdomains with the root domain (ex: mydomain.com). The checkbox will be hidden if you're trying to do this with a subdomain. This is explained in our documentation here: https://docs.aws.amazon.com/amplify/latest/userguide/to-set-up-automatic-subdomains-for-a-Route-53-custom-domain.html.

You can still add multilevel subdomains manually by following this guide: https://docs.aws.amazon.com/amplify/latest/userguide/to-manage-subdomains.html
