### ISSUE TITLE
Is it possible to setup Amplify to use MTLS protected API Gateways?

### ISSUE THREAD

**Issue by ogg130** [aws-amplify/amplify-hosting#3259]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

new_app

### AWS Region

us-west-1

### Amplify Hosting feature

Access control

### Question

I've got an API Gatweway configured to connect using MTLS using this documentation: https://aws.amazon.com/blogs/compute/introducing-mutual-tls-authentication-for-amazon-api-gateway/

As a human, I can make an API call using my client cert and private key.

As an Amplify site, my client cert needs to be in the API's configured truststore and I need to use my private key to make the API call.

How do I get access to the Amplify/Route53 auto configured certs PEM file and its key? It does not show up in ACM for me and it doesnt appear to be availble through the amplify console. Alternatively, can the cert and key be leveraged through the SDK somehow?

Thanks!

**Comment by ogg130** [comment]
Bueller? :D

**Comment by hloriana** [comment]
Hi @ogg130 👋🏽 thanks for raising this question. Amplify Hosting is a managed service and we manage all of the certificates internally. We do not provide access to any keys or PEM files associated with certificates at this time. We apologize for this inconvenience.
