### ISSUE TITLE
A file is not served in gzip

### ISSUE THREAD

**Issue by kinitkit** [aws-amplify/amplify-hosting#3262]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dy65p52ntwmxh

### AWS Region

us-west-2

### Amplify Hosting feature

Custom headers, Deployments, Frontend builds

### Question

Ahoy!
Is there a limit as to how much size a file should be before it is served over gzip? We have this react build with a massive chunk of 12mb and it is not being served as gzip even though in Request Headers there is a `accept-encoding: gzip, deflate, br`. But the other files (chunks) are served in gzip.

**Comment by hloriana** [comment]
Hi @kinitkit 👋🏽 thanks for raising this question. Can you provide any details or screenshots related to the error that you see when making the requests that fail? That will be helpful for us to determine why the file isn't being served.

**Comment by kinitkit** [comment]
Hi, @hloriana.

This is the request that's not returned as a gzip
![image](https://user-images.githubusercontent.com/23753030/215295841-688c4d22-4224-4a5b-9168-662c6eb1443a.png)

While this other chunk is in gzip
![image](https://user-images.githubusercontent.com/23753030/215296066-ef267409-2f2f-4ca7-9b11-0416ddb1dd0e.png)

Request sizes
![image](https://user-images.githubusercontent.com/23753030/215296108-4427ac5e-320d-4aea-8750-0a734db569bc.png)

**Comment by hloriana** [comment]
Hi @kinitkit thanks for providing these extra details. Amplify Hosting uses CloudFront to serve content and it's also responsible for handling file compression. CloudFront has a file compression limit of 10 MB (see [here](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html)). The larger file exceeds this limit which is why it's not being served as gzip.

Have you tried leveraging tree shaking and code splitting to reduce the size of your files?

**Comment by kinitkit** [comment]
Thank you! Haven't found that limitation. I'll be trying to do tree shaking since we are already did code splitting.
