### ISSUE TITLE
Stuck at SSL configuration

### ISSUE THREAD

**Issue by waltermvp** [aws-amplify/amplify-hosting#3263]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

https://us-east-1.console.aws.amazon.com/amplify/home?region=us-east-1&code=418f86fb0a19c8d3a34d#/d9lzc3aeq3798/settings/domains

### Region

us-east-1

### Step

domain activation

### Status

SSL configuration

### Issue or question

I have set the proper DNS settings but am stuck at "SSL configuration". I waited several hours. I am using NameCheap for domain hosting. 

<img width="910" alt="Screenshot 2023-01-24 at 10 49 35 PM" src="https://user-images.githubusercontent.com/1158238/214475897-11c3f60d-a249-42ee-8539-639083afb2de.png">
<img width="718" alt="Screenshot 2023-01-24 at 10 49 05 PM" src="https://user-images.githubusercontent.com/1158238/214475898-c3e7c2c0-1053-415e-9cca-dab775755cd4.png">

**Comment by hloriana** [comment]
Hi @waltermvp 👋🏽 thanks for raising this question. According to our [troubleshooting](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#my-domain-hosted-with-a-third-party-is-stuck-in-the-pending-verification-state) guide:

> It is important to update your CNAME records as soon as you create your custom domain. After your app is created in the Amplify console, your CNAME record is checked every few minutes to determine if it resolves. If it doesn’t resolve after an hour, the check is made every few hours, which can lead to a delay in your domain being ready to use. If you added or updated your CNAME records a few hours after you created your app, this is the most likely cause for your app to get stuck in the Pending Verification state.

The CNAME record you added is not resolving properly. You can see this by searching for the record on whatsmydns.net: https://www.whatsmydns.net/#CNAME/_fb9a0535c6a6352edfa0fe06a864ee6c.waltermvp.com

Please double check to confirm that you have properly configured the DNS records. If the issue persists you can follow these next steps:

1. Contact your DNS provider to diagnose why the DNS record is not resolving.
2. [Migrate your DNS to Route53](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/MigratingDNS.html)

**Comment by waltermvp** [comment]
@hloriana  thank you very much for your response. I've been staring at the configuration for hours. Do you see anything that is wrong by glancing at the above settings?

**Comment by waltermvp** [comment]
I have compared the settings with other working amplify sites on my Namecheap that do work. I'm pretty sure it's correct @hloriana
