### ISSUE TITLE
Change notification e-mail message body

### ISSUE THREAD

**Issue by rof20004** [aws-amplify/amplify-hosting#3266]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d35aq2ovh1lkks

### AWS Region

us-east-2

### Amplify Hosting feature

Notifications

### Question

HI folks,

is it possible to change the default message body of the notification feature?

Today I'm getting this message:

Build notification from the AWS Amplify Console for app: 
https://********.amplifyapp.com/. Your build status is SUCCEED. 
Go to ********** to view details on your build.

I want to add the committer name in this message(I'm using github repository).

I'm using it with SNS + Slack

Thanks :)

**Comment by hloriana** [comment]
Hi @rof20004 👋🏽 thanks for raising this question! Currently we do not support creating custom notification messages. We apologize for this inconvenience.
