### ISSUE TITLE
First load after deployments takes up to ~15 seconds

### ISSUE THREAD

**Issue by jdpst** [aws-amplify/amplify-hosting#3269]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1zloo668ozrvr

### AWS Region

eu-west-1

### Amplify Hosting feature

Deployments, Frontend builds, Monorepo

### Describe the bug

When visiting an amplify frontend deployment for the first time, it can take up to 15 seconds to display content. Subsequently pages are served immediately as expected. Interestingly, it doesn't seem to make any difference _which_ page is visited first. Also interestingly, it is not on a per-page basis–after the initial page is served, _all other pages_ are served immediately too.

### Expected behavior

I would expect the first page to be served much more quickly than it is currently. I could understand some (~1-2 seconds) of latency if the page does not exist in an edge location yet but not ~15 seconds of latency.

We are running Amplify builds side-by-side with ECS+Fargate and have never experienced anything like this with using those services.

### Reproduction steps

1. Run a build
2. Visit the app

### Build Settings

```yaml
cdk.aws_codebuild.BuildSpec.fromObjectToYaml({
    version: 1,
    applications: [
      {
        appRoot,
        frontend: {
          phases: {
            preBuild: {
              commands: [
                "npm ci",
                'echo "NEXT_PUBLIC_HOST=$AWS_BRANCH.$AWS_APP_ID.amplifyapp.com" >> .env.production',
                'echo "NEXT_PUBLIC_GIT_SHA=$(git rev-parse HEAD)" >> .env.production',
              ],
            },
            build: {
              commands: ["npm run build"],
            },
            postBuild: {
              commands: [
                "shopt -s dotglob", // include filenames beginning with a ‘.’ in the results of filename expansion, except '.' and '..'
                `mv -f .next/standalone/${appRoot}/* .next/standalone`,
              ],
            },
          },
          artifacts: {
            baseDirectory: ".next",
            files: ["**/*"],
          },
          cache: {
            paths: ["../../node_modules/**/*", ".next/cache/**/*"],
          },
        },
      },
    ],
  });
```

### Additional information

We are using a monorepo setup with several NextJS applications which we are considering migrating to Amplify Hosting from ECS/Fargate.

The closest thing I have to logs showing these are these, which are from a PR branch. They show the request took just under 15 seconds to run but that a second request took just 6ms.

<img width="1465" alt="image" src="https://user-images.githubusercontent.com/63979647/214902060-2b5918e5-3bf5-4024-b540-c6160f6f141c.png">

**Comment by hloriana** [comment]
Hi @jdpst thanks for raising this issue. This is a known issue that the team is actively investigating. We have an open issue to track this behavior: https://github.com/aws-amplify/amplify-hosting/issues/3211. We apologize for this inconvenience, please follow #3211 for future updates. 

Closing this issue as a duplicate.
