### ISSUE TITLE
Cannot create CloudFront distributions

### ISSUE THREAD

**Issue by sitezen** [aws-amplify/amplify-hosting#3272]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1sjseq5g6uq4l

### AWS Region

eu-west-3

### Amplify Hosting feature

Deployments

### Question

After website (next.js 13) stop updating on new deploys, I tried to complete remove app from AWS and have removed all (as I thought) related, including all CloudFront distributions.
New app was successfully recreated, everything works and updating, but CloudFront seems totally missing. CloudFront distributions totally empty.
Tried to remove hosting and add again, tried to create one more app from scratch - nothing related CloudFront appears.
Deployment tab looks like:
2023-01-29T09:41:19 [INFO]: Beginning deployment for application d1sjseq5g6uq4l, branch:production, buildId 0000000004
2023-01-29T09:41:35 [INFO]: Deployment complete

Last log record for "Default Lambda@Edge for Next CloudFront distribution" - many days ago, it no more calling.
How can I get CloudFront working again?
Or now all it totally hidden from end user?

**Comment by hloriana** [comment]
Hi @sitezen 👋🏽 Amplify Hosting released support for Next.js 12 and Next.js 13 applications in November, 2022. 

[AWS Amplify Hosting announces support for Next.js 12 and 13](https://aws.amazon.com/ar/about-aws/whats-new/2022/11/aws-amplify-hosting-support-next-js-12-13/)

Next.js 13 Amplify applications are fully managed by Amplify Hosting; this means that the underlying resources such as the CloudFront distribution and Lambda@Edge functions are no longer deployed in your account. The infrastructure is fully managed to reduce operational overhead for developers.

Are you running into any issues with your Next.js 13 application?
