### ISSUE TITLE
nazerapp.com Activation Issue

### ISSUE THREAD

**Issue by edsoltani** [aws-amplify/amplify-hosting#3274]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1pp6yv3lx30wv

### Region

eu-west-2

### Step

Domain Activation

### Status

Failed

### Issue or question

Domain nazerapp.com activation keeps failing. We have checked CloudFront and the domain dose not exist but we still get the error.

### Error message

Error message: [CNAMEAlreadyExistsException] The following CloudFront distributions or Amplify Apps are already using one or more of your domains: [Distribution: *******G1G048H in AWS Account: ******816663].

**Comment by hloriana** [comment]
Hi @edsoltani 👋🏽 please open a case with [AWS Support](https://support.console.aws.amazon.com/support/home?region=us-west-2#/case/create) so that you can receive further assistance.
