### ISSUE TITLE
access files from index.html give 403 errors

### ISSUE THREAD

**Issue by jayadhoni** [aws-amplify/amplify-hosting#3276]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

app1943

### AWS Region

us-east-1

### Amplify Hosting feature

Access control

### Question

getting issues in access files inside index html in amazon web host

![runtimeerror](https://user-images.githubusercontent.com/8916734/215793814-b9828c9b-4195-4567-bbec-d2682fa2bf0b.PNG)

**Comment by hloriana** [comment]
Hi @jayadhoni 👋🏽 please ensure that you are navigating inside your build output and zipping the contents. If you zip the folder itself, you can run into an access denied error. Please review our documentation for how to manually deploy your application: **https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html**
