### ISSUE TITLE
Subdomain limit of 50

### ISSUE THREAD

**Issue by scottmanny** [aws-amplify/amplify-hosting#3279]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3f0vp9f8i81gz

### Region

us-east-1

### Step

Domain management

### Status

Failed

### Issue or question

I use AWS Amplify for managing my app (https://pickleplanner.com), and I love it.  Every time a customer signs up they get their very own web address (e.g. https://my-club-name.pickleplanner.com).  My latest customer just tried to sign up but received an error because it exceed the 50 subdomain limit (that I was unaware of).  Please help me to get this subdomain limit increased, I'll do anything.  Thanks.

### Error message

Too many sub domains requested, the maximum allowed in your account is 50

### Additional information

Feel free to call me at 618.980.3277

**Comment by scottmanny** [comment]
I seemed to have found the place to request an increase to the quota.  https://us-east-1.console.aws.amazon.com/servicequotas/home/services/amplify/quotas/L-A6716586

**Comment by hloriana** [comment]
Hi @scottmanny 👋🏽 thanks for raising this question. There is a default limit of 50 subdomains for each domain used in a region. You can proceed to request a limit increase [here](https://console.aws.amazon.com/servicequotas/home/services/amplify/quotas/L-85685B2E) if you have not already. 

For additional documentation on our service limits, feel free to reference our [Amplify service quotas](https://docs.aws.amazon.com/general/latest/gr/amplify.html#service-quotas-amplify). Thank you!
