### ISSUE TITLE
Deleting all environment variables disabled save button

### ISSUE THREAD

**Issue by taylorsmithgg** [aws-amplify/amplify-hosting#3284]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-west-2

### Amplify Hosting feature

Environment variables

### Describe the bug

When attempting to delete all environment variables, the save button is disabled when there are none.

### Expected behavior

The save button should allow deleting all environment variables.

### Reproduction steps

1. Create environment variable in new project
2. Delete environment variable
3. Save button is disabled

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriana** [comment]
Hi @taylorsmithgg thanks for raising this issue, we have added this bug to the backlog for prioritization.

**Comment by hloriana** [comment]
The fix has been pushed for this, closing as resolved.
