### ISSUE TITLE
Amplify Preview Status not update in Github Action

### ISSUE THREAD

**Issue by jackykwandesign** [aws-amplify/amplify-hosting#3287]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d9yldpv6pkjrw

### AWS Region

ap-southeast-1

### Amplify Hosting feature

Web previews

### Describe the bug

same as https://github.com/aws-amplify/amplify-hosting/issues/1458#issuecomment-1107924466

When multiple PR trigger build in Amplify, it will never update Github CICD status check,
stuck at building forever
![image](https://user-images.githubusercontent.com/46065771/216233177-7b7e0669-d509-4fd7-8071-269639181d36.png)

But in AWS amplify console, it show finish status
![image](https://user-images.githubusercontent.com/46065771/216233260-f79b99f2-bdd8-4ecc-b08f-fa23ebb64731.png)

### Expected behavior

Github CICD status always show correct status, or we can trigger job rerun in github action

### Reproduction steps

Trigger amplify preview with two branch running at the same time, so if job B start running when job A not finish yet, they will stuck forever

### Build Settings

```yaml
NA
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriana** [comment]
Hi @jackykwandesign 👋🏽, thanks for raising this issue. We are working on reproducing this behavior and adding it to our product backlog for prioritization.
