### ISSUE TITLE
How to change Node Version in Lambda Function that hosts Nextjs SSR

### ISSUE THREAD

**Issue by saulonunesdev** [aws-amplify/amplify-hosting#3295]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3vc58cpnaxzh9

### AWS Region

us-east-2

### Amplify Hosting feature

Deployments

### Question

Hi, Thanks for the support and sorry if this is a duplicate, but I've researched a lot and couldn't find any docs or issues related.

I have a nextjs app that needs to run on node18, you can see the issue below.
![image](https://user-images.githubusercontent.com/26988193/217118118-96113668-887f-40b9-9092-a2e9f59a2519.png)

I've already tried the following:
 - set engines to 18.x in package.json
 - update environment variable of NODE_VERSION to 18.x
 - update the build settings to use a custom docker image: node:18.2.0
 - created a lambda function with node18.x in the backend, but i failed to use that function as a runtimer 
   - Update Runtime in amplify/backend/function/YOURLAMBDA/yourlambda-cloudformation-template.json
 - Set node version in .nvmrc file in the project root
 
 Here is the repo example: https://github.com/Sirge-io/test-amplify
 
 PS: Just to be clear, i'm not talking about the functions that we can add into `amplify/function` but the lambda that hosts the frontend

Any Help is much appreciated. Thanks.

**Comment by hloriana** [comment]
Hi @saulonunesdev, thanks for raising this question. Updating the runtime for Lambda functions hosting SSR apps is not supported at this time. We will keep this open as a feature request instead. We apologize for this inconvenience.

**Comment by saulonunesdev** [comment]
Thanks @hloriana ^^

**Comment by valenciaHQ** [comment]
Up to this, we need this.

**Comment by clementAC** [comment]
We definitively need to run our public faced application on maintained environment and lot of lib are dropping node 16 so basically with amplify we are stuck to not update our application
