### ISSUE TITLE
Deployment is not reflecting in the UI

### ISSUE THREAD

**Issue by manishfin** [aws-amplify/amplify-hosting#3297]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

[redacted]

### AWS Region

us-west-2

### Amplify Hosting feature

Frontend builds, SSR

### Describe the bug

When i deploy my latest changes to my master branch, the deployment is successfully completed in Amplify console but i don't see any changes in the UI. There are no failures in the log during the deployment.

Please assist as what can be the root cause of this issue.

### Expected behavior

After successful deployment the latest changes should be rendered in the UI, this is not a cache issue i have confirmed.

### Reproduction steps

1. Commit code changes to the master branch
2. Deployment starts in Amplify and successfully completed
3. Refresh the UI, no changes are rendered

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Jay2113** [comment]
@manishfin 👋, thanks for raising this issue with us. It seems that you have provided your AWS Account ID within the App ID field and thus we have redacted it for security concerns.

Can you provide us your Amplify App ID instead?

**Comment by hloriana** [comment]
Hi @manishfin You can find your app ID by following these steps:
1.  Navigate to your app > App settings > General 
2. Find the **App ARN** 
3. The format of the ARN is arn:aws:amplify:<region>:<accountID>:apps/<app-id>
4. The app ID will be the last string of digits
