### ISSUE TITLE
Clicking "View in CloudFormation" for a backend environment intermittently redirects to list stack screen instead of showing the particular stack information

### ISSUE THREAD

**Issue by anurag128** [aws-amplify/amplify-hosting#3301]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

All

### AWS Region

us-east-1

### Amplify Hosting feature

Not Applicable

### Describe the bug

When we clicking "View in CloudFormation" for a backend environment intermittently redirects to list stack screen that is similar to "https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/".

### Expected behavior

However, the expected redirect should similar to "https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/stackinfo?filteringText=&filteringStatus=active&viewNested=true&hideStacks=false&stackId=<stackARN>"

### Reproduction steps

1. Navigate to the Amplify Application
2. Navigate to backend environments
3. Click on any backend environment and click "View in CloudFormation" under the overview section

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriana** [comment]
Hi @anurag128 👋🏽 I'm not able to replicate this behavior on my end. You described this as intermittent - are you seeing this behavior when making an update to the backend? How often does this occur?
