### ISSUE TITLE
AWS access credentials can not be found

### ISSUE THREAD

**Issue by atef-abdellatif** [aws-amplify/amplify-hosting#3303]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

db4nz94zrbxbj

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Question

Hi,

Thank you so much in advance for taking the time to help me!

question 1: 
I'm hosting my NodeJS app on Amplify with auto deployment via GitHub, but after I added a backend to my app (AppSync GraphQL, DynamoDB, and  Storage) and pushed the code changes to GitHub, Amplify build failed because of an access error states: "AWS access credentials can not be found" (screenshot-1 attached).

question 2:
I added a Lambda function to my app via command "amplify add function" to do some price calculation. I chose the "hello world" function. I then added an API Gateway (REST API) trigger to invoke the function, but I don't know how fetch data from the API endpoint from my app. I tried to use "await API.get(apiName, path)" but I got an error states that the url doesn't exist (screenshot-2, screenshot-3 attached). I also tried "await fetch(url, options)" but got an error says that "Origin http:localhost:3000 is not allowed by Access-Control-Allow-Orign. Status code: 200". However CORS is enabled on this API gateway endpoint. (screenshot-4, screenshot-5 attached). 

question 3:
is it possible to fetch data directly from a Lambda function URL without having to trigger an API Gateway? if yes, would you please let me know how. 

I would really appreciate any help.

<img width="518" alt="screenshot-1" src="https://user-images.githubusercontent.com/110037539/218390705-fb75a6e0-6bbc-4aaf-b731-dc40ed9bfd65.png">
<img width="598" alt="screenshot-2" src="https://user-images.githubusercontent.com/110037539/218390712-b38b92f8-1d42-452c-addb-73d869e574b1.png">
<img width="748" alt="screenshot-3" src="https://user-images.githubusercontent.com/110037539/218390714-951575d7-cf18-4eb7-8fb8-0bf9dd2a3470.png">
<img width="574" alt="screenshot-4" src="https://user-images.githubusercontent.com/110037539/218391862-0d124b0d-f0ab-4fd8-8c26-db5468338211.png">
<img width="917" alt="screenshot-5" src="https://user-images.githubusercontent.com/110037539/218390719-f075c28d-948c-4a7c-9e62-269bc0c7a17f.png">

**Comment by hloriana** [comment]
Hi @atef-abdellatif, in order for your backend environment to be successfully built during the CI/CD process, you must ensure that your application has a service role attached. The service role gives Amplify permission to access your backend resources. Please review our documentation for how to add a role: https://docs.aws.amazon.com/amplify/latest/userguide/how-to-service-role-amplify-console.html

**Comment by atef-abdellatif** [comment]
Thank you so much! I had totally forgotten to attach the role to my app. Appreciate it!
