### ISSUE TITLE
Aws amplify hosting 200 redirects between subdomains

### ISSUE THREAD

**Issue by arnriu** [aws-amplify/amplify-hosting#3305]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2vkkrtyuegtfl

### AWS Region

eu-west-3

### Amplify Hosting feature

Redirects

### Question

I have multiple subdomains on my amplify react app, each subdomain linked to a branch.

I already have a 301 permanent on a subdomain: https://sub.domain.com is on a branch but redirects fine to https://anothersub.domain.com as intended.
It works fine, and I can remove this redirect anytime I want to use `sub` and its branch. Rest of the time, I add the redirect and my users are redirected to `anothersub` if they try to reach `sub`.

Now, I want to add a 200 rule for 2 new subs. Let's give them names: `foo`and `bar`.
What I want to achieve: https://foo.domain.com should display its branch for everyone, except people from a specific country. For them, we want to display https://bar.domain.com , but with a 200 rewrite to keep url https://foo.domain.com
For the moment, I skipped the country part, I just tried to achieve the 200 redirect and will try the country condition once done.

Is it possible ?

What I tried with no success:

```
[
    {
        "source": "https://sub.domain.com",
        "target": "https://anothersub.domain.com",
        "status": "301",
        "condition": null
    },
    {
        "source": "https://foo.domain.com",
        "target": "https://bar.domain.com",
        "status": "200",
        "condition": null
    },    
    {
        "source": "/<*>",
        "target": "/index.html",
        "status": "404-200",
        "condition": null
    },
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|woff2|ttf|map|json|lin|webp)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    }
]
```

**Comment by hloriana** [comment]
Hi @arnriu, thanks for raising this question. I was able to reproduce this and it appears to be a bug with the 200 rewrite rule not working. For a workaround, you should be able to use a 301 redirect and add the country code to the rule for [region based routing](https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html). 

Please let me know if you are able to leverage the workaround outlined above. I added this bug to our backlog for prioritization and we will update this issue once it has be fixed.

**Comment by hloriana** [comment]
Closing as a duplication of https://github.com/aws-amplify/amplify-hosting/issues/2601. Please continue any further engagement on that issue. Thank you!
