### ISSUE TITLE
How do I delete resources that are no longer in use after migrating to Amplify Hosting compute?

### ISSUE THREAD

**Issue by hiroki-yoneda** [aws-amplify/amplify-hosting#3311]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3a8l9fwex6aym

### AWS Region

ap-northeast-1

### Amplify Hosting feature

Deployments, SSR

### Question

After https://github.com/aws-amplify/amplify-hosting/issues/3298 question, I maigreted to Amplify Hosting compute. And CloudFront distributions, Lambda@Edge, etc. did not appear to have been deployed.

However, CloudFront distributions, Lambda@Edge, etc. deployed before migration remained.

Looking at the information on https://github.com/aws-amplify/amplify-hosting/issues/3158#issuecomment-1332755075, I understand that the reason CloudFront distributions, Lambda@edge, etc. are still there is to be enabled to rollback to WEB_DYNAMIC.

If a rollback to WEB_DYNAMIC is not necessary, how can I delete them? I would like to do this automatically via CLI, etc., rather than manually deleting. And other than CloudFront distributions, Lambda@Edge and S3 buckets, what resources remain undeleted?

Does anyone have any good ideas?

## How to migrate

```sh
aws amplify update-app --app-id <APP_ID> --platform WEB_COMPUTE --region <REGION>
```

**Comment by hloriana** [comment]
Hi @hiroki-yoneda, thanks for raising this question. Please keep in mind that if you want to revert the migration after deleting the resources, it will not work.  But if you are absolutely sure you will not have a need to revert the migration, you can delete the resources manually. To identify which resources to remove, you can follow these steps:

1. navigate to the last successful build **prior** to the migration
2. select the **Deploy** tab
3. In the deploy logs, you will see the ID's for the CloudFront distribution, Lambda functions, and any other resources that were deployed in your account for that application.

Once you have the IDs for all of the resources, you can navigate to the respective AWS service in the console and manually delete the resources.

**Comment by hloriana** [comment]
Hi @hiroki-yoneda, thanks for raising this question. Please keep in mind that if you want to revert the migration after deleting the resources, it will not work.  But if you are absolutely sure you will not have a need to revert the migration, you can delete the resources manually. To identify which resources to remove, you can follow these steps:

1. navigate to the last successful build **prior** to the migration
2. select the **Deploy** tab
3. In the deploy logs, you will see the ID's for the CloudFront distribution, Lambda functions, and any other resources that were deployed in your account for that application.

Once you have the IDs for all of the resources, you can navigate to the respective AWS service in the console and manually delete the resources.

**Comment by hiroki-yoneda** [comment]
Hi @hloriana, thanks for your response. I understood that the resources shown in the last deployment log before migration are the resources that have not been used since the migration. You answered that we can delete them manually, but is it possible to delete them automatically? For example, I am thinking of deleting them with CLI commands such as [delete-distribution](https://docs.aws.amazon.com/cli/latest/reference/cloudfront/delete-distribution.html#delete-distribution), [delete-function](https://docs.aws.amazon.com/cli/latest/reference/lambda/delete-function.html#delete-function) and [rm](https://docs.aws.amazon.com/cli/latest/reference/s3/rm.html#rm).

Are there any problems with deleting with these commands?

**Comment by hloriii** [comment]
Hi @hiroki-yoneda yes, those resources can also be deleted using those CLI commands.
