### ISSUE TITLE
Domain Issues - Go Daddy Requires IP address but can't find on Amplify App

### ISSUE THREAD

**Issue by JhordanFigueroa** [aws-amplify/amplify-hosting#3315]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2zqdgjji2arww

### Region

us-west-1

### Step

SSL Certificate and Routing From Go Daddy DNS

### Status

Available - But not Working 

### Issue or question

Root Domain doesn't seem to be connected properly. 
Went through the steps here (https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-godaddy.html). 
This https://pardoglobal.com/ doesn't work. 
But this does work. https://www.pardoglobal.com/

I talked to Go Daddy representative and they said I needed the IP address from amplify app for Type A record. 

### Error message

<img width="1436" alt="Screenshot 2023-02-18 at 10 23 50 AM" src="https://user-images.githubusercontent.com/43771604/219873918-e22a6f32-66c5-4513-b685-d06e34cd9cc9.png">

**Comment by hloriana** [comment]
Hi @JhordanFigueroa 👋🏽, thanks for raising this question. For domains managed by third party DNS providers such as GoDaddy, you can configure the domain to forward the requests sent to the root domain. Those requests can be forwarded to a sub domain such as `www.example.com`.

> 1. If you want to keep GoDaddy as your provider and update the root domain, add Forwarding and set up a domain forward:
> 2. Scroll down to the bottom of the DNS Management page to find the Forwarding box.
> 3. For Forward to, choose http://, and then enter the name of your subdomain to foward to (for example, www.example.com).
> 4. For Forward Type, choose Temporary (302).
> 5. For Settings, choose Forward only.
> 6. Choose, Save.

Since GoDaddy does not have ANAME/ALIAS support, you also have the option of migrating your domain to Route53 if you did want to use the root domain for your application as well. 

> This step is not required for subdomains. GoDaddy doesn’t support ANAME/ALIAS records. For DNS providers that do not have ANAME/ALIAS support, we strongly recommend migrating your DNS to Amazon Route 53. For more information, see [Configuring Amazon Route 53 as your DNS service](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-configuring.html).
