### ISSUE TITLE
CNAME target changed unexpectedly (CNAMEDNSMisconfiguration)

### ISSUE THREAD

**Issue by pietrorea** [aws-amplify/amplify-hosting#3316]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dyq6nlhufv0y0

### Region

us-east-2

### Step

Domain activation

### Status

CNAMEDNSMisconfiguration

### Issue or question

Here's what I did:

- I added a custom subdomain to my Amplify Hosting app.
- I copied the **three** DNS records that I needed to change from the Amplify dashboard (1 for SSL verification and 2 for domain verification). See screenshot attached. 
- Sent these to a client for them to set up their DNS. Took them about a week to do this.
- When I came back to the Amplify dashboard, I see that the SSL verification worked but now Amplify is saying that the other two are misconfigured. Amplify is saying that the Cloudfront DNS records should have been something different from what I saw and copied initially.

Why did the original DNS record I saw on Amplify change? Is there an undocumented time limit to change the DNS once the process has started, else it changes? The documentation says to add the SSL verification DNS record shortly after you add the domain in the dashboard, but it says nothing about the Cloudfront ones. 

### Error message

Error message: [CNAMEDNSMisconfiguration] The following domain names include an incorrectly configured DNS record that points to the wrong target URL: [Domain $CUSTOMER_URL has a CNAME record pointing to df50tvptn3dfv.cloudfront.net, Domain www.$CUSTOMER_URL_1 has a CNAME record pointing to df50tvptn3dfv.cloudfront.net]. The correct target URL was d1uyquvksywcxs.cloudfront.net. Please cleanup any old CNAME records from your DNS entries before adding your domain.

### Additional information

<img width="711" alt="Screen Shot 2023-02-20 at 9 38 51 AM" src="https://user-images.githubusercontent.com/1264371/220136444-82096f30-9982-4edf-8d83-fbafff3e998e.png">

**Comment by hloriana** [comment]
Hi @pietrorea, thanks for raising this question! Were there any prior DNS records added to the domain? If the domain was connected to an Amplify app previously and the records were not removed before adding the domain to this current App, then this will trigger a loop where the records will be mismatched.

Please ensure any stale records are removed before attempting to add this domain again.

I'm currently investigating if there is a time limit for adding the CNAME records and will update this issue once I have more information.

**Comment by hloriana** [comment]
Hi @pietrorea after further investigation, we have not yet identified a time constraint with the CloudFront CNAME records. 

However, while you were waiting for your client to update their domain settings with the DNS records, did you happen to see and click a **retry** button in the Amplify console? If you did, then that would restart the domain association process and generate new DNS records to add. 

Our recommendation moving forward is to perform the following steps:

1. Remove the domain from the Amplify app.
2. Have the client delete the DNS records from their provider settings. (This must be done before trying to add the domain to the Amplify app again).
3. Add the domain back to the Amplify app
4. Have the client add the DNS records as soon as possible to avoid getting stuck in the pending verification state. 
5. If a **retry** button appears before the client adds the DNS records, do not click it.

Alternatively, if you cannot guarantee that your client will be able to add the DNS records in a timely manner, you can also try migrating the domain to Route53. Once the domain is migrated, Amplify will be able to automatically setup the domain association.  See https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-configuring.html.

**Comment by pietrorea** [comment]
@hloriana yes, I think that I did click the Retry button. I didn't know that this would create new DNS records. I think the docs need updating or there needs to be a confirmation screen that says this will happen.

We managed to hook up the domain name after trying the whole process again. Thank you for your help.

**Comment by runtman** [comment]
If it helps I had this issue yesterday.

I've tried again today and the issue isn't apparent?
