### ISSUE TITLE
How to add header CloudFront-Is-Mobile-Viewer in AWS Amplify?

### ISSUE THREAD

**Issue by caiodounis** [aws-amplify/amplify-hosting#3322]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [x] I have removed any sensitive information from my code snippets and submission.

### App Id

dnzn4ifojcrc4

### AWS Region

us-east-1

### Amplify Hosting feature

Custom headers

### Question

I'm using nextjs 13 with aws amplify, and I'm trying to identify the user's device using the request header `user-agent` but I can see the header is coming with a fixed value `Amazon Cloudfront`. After a brief research I saw a couple of tutorials on how to add the headers like `CloudFront-Is-Mobile-Viewer` in a cloudfront distribution, but I wasn't able to do that in AWS Amplify. How can I add that header in the request headers in AWS Amplify?

**Comment by hloriana** [comment]
Hi @caiodounis 👋🏽 thanks for raising this question. We do not have a way of allowing customers to use this CloudFront header at this time but we are tracking this as a feature request.

**Comment by caiodounis** [comment]
Hi @hloriana thanks for the reply!
Is there any other way to make Amplify **not** mask the `user-agent` header?
This way I would be able to identify the device.

**Comment by mauerbac** [comment]
This feature has just been supported with our latest launch! Closing.

Check out the details here: https://aws.amazon.com/blogs/mobile/cdn-caching-improvements-for-better-app-performance-with-aws-amplify-hosting/
