### ISSUE TITLE
Deploy suceeded, but I get access denied when trying to access the website.

### ISSUE THREAD

**Issue by JasonLLu** [aws-amplify/amplify-hosting#3325]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1of9cjllf02ep

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Question

I am getting the below when trying to load the website. I have tried changing home.html to index.html, nothing is working.

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<link type="text/css" rel="stylesheet" id="dark-mode-custom-link"/>
<link type="text/css" rel="stylesheet" id="dark-mode-general-link"/>
<style lang="en" type="text/css" id="dark-mode-custom-style"/>
<style lang="en" type="text/css" id="dark-mode-native-style"/>
<style lang="en" type="text/css" id="dark-mode-native-sheet"/>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>ZQNXZY360WQFG5AF</RequestId>
<HostId>HAAwgXFFpd6pmhrF4TwWPE5uqXFlXeb1qkVOCKOuQhkOHk9dVCZ1lYwERfz8TAZYGLFNx2GjXNQ=</HostId>
</Error>
```

**Comment by hloriana** [comment]
Hi @JasonLLu 👋🏽 thanks for raising this. This can occur when the `baseDirectory` has an incorrect file path in your build script. I can see you currently have it set to `/app`. 

When you build you your app locally, does the `app` directory get created with the necessary build artifacts? What framework are you using for your frontend?

**Comment by JasonLLu** [comment]
I am using Flask as my framework.

And amplify is pulling my github repository (clones the app/ directory).

The file structure is app/templates/index.html and app/__init__.py

It all run fine locally.

**Comment by JasonLLu** [comment]
@hloriana  Here is my tree of the app directory if it helps:

├── app
│   ├── __init__.py
│   ├── __pycache__
│   │   └── __init__.cpython-38.pyc
│   └── templates
│       └── index.html

**Comment by JasonLLu** [comment]
Also I do see an artifact.zip that gets created and app is a folder in it

**Comment by hloriana** [comment]
Hi @JasonLLu, thanks for sharing additional details. You are running into this issue because Amplify does not support hosting Flask applications at this time. We apologize for this inconvenience.
