### ISSUE TITLE
Lambda size too large with Layer enabled

### ISSUE THREAD

**Issue by ZacMelendez** [aws-amplify/amplify-hosting#3330]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### AWS Region

us-east-1

### Amplify Hosting feature

Backend builds

### Question

I am trying to create an amplify lambda which can access pandas, and when trying to install pandas using the Pipfile, I get the `Original error was: No module named 'numpy.core._multiarray_umath'` error, and so I ended up deleting the function, and creating a new one from scratch using the `arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:3` layer. However, I get the following error on build:

```
Resource handler returned message: "Unzipped size must be smaller than 93503870 bytes"
```

And this is just using the default Python 3.9 template.

My Amplify CLI version is 10.0.0.

Any ideas on how to get my Py3.9 function access to pandas while still being smaller than the max bundle size?

**Comment by hloriana** [comment]
Hi @ZacMelendez, thanks for raising this question. Could you also provide your app ID so we can further investigate your backend build failure? I'm currently investigating any possible workarounds for this issue and will update once I have more information.
