### ISSUE TITLE
Amplify Hosting Preview not able to find Github PR in private repo (within public org)

### ISSUE THREAD

**Issue by jasondamour** [aws-amplify/amplify-hosting#3333]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dt8rcpplq2gyw

### AWS Region

us-east-2

### Amplify Hosting feature

Web previews

### Describe the bug

A preview branch can successfully build and deploy, but does not attach details back to corresponding Github PR.

### Expected behavior

Creating/committing a PR should create an Amplify Preview, and attach Amplify Preview details to Github PR

### Reproduction steps

1. Enabled Auto-Builds and Web Previews for our Github repositories. Connected AWS Amplify to Github via an admins's Github account. 
2. Created a new branch and pushed change, observed that the autobuild worked properly and a custom domain for the branch was created properly. Observed that "preview" is enabled for this branch.
3. Created a Pull Request for the branch. Observed that no Preview was created in amplify, and no details were added to the Github Pull request.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

Private Github repo within Public Organization

App ID: `dt8rcpplq2gyw`
Test Branch: `test-amp`
PR ID: `!105`

DM me for additional debug details.

**Comment by hloriana** [comment]
Hi @jasondamour 👋🏽 I tried testing this behavior out (using a GH org and private repo) and I was able to successfully trigger a pr preview for new branches. When you enabled previews, were you prompted to install the GitHub app and if so, can you confirm that the app exists in GitHub?

**Comment by Narrator** [comment]
@jasondamour  Can you please share a few more details about this issue?

1. Did you observe this behavior with other branches or did it happen only with the `test-amp` branch?
2. In the issue details, you have mentioned that Amplify did not attach details to the PR, but in the reproduction steps you have mentioned that no preview was created. Can you please clarify which one is true?
3. Do you consistently observe this behavior with all PR previews for your repository?

**Comment by jasondamour** [comment]
@hloriana 
- The app exists in Github, yes

@Narrator 
1. It happens with all branches
2. Both are true. No preview is created, and no details are added to Github (since there are none to attach I suppose)
3. Yes, this has never worked in this repository.

One thing I just realized. We are creating our `main` branch in amplify (via terraform) as in `DEVELOPMENT` stage. Does this stage of the default branch prevent previews being created? In other words, does Amplify only create Previews against `PRODUCTION` stage branches?
```
resource "aws_amplify_branch" "web_main" {
  app_id      = aws_amplify_app.web.id
  branch_name = "main"

  framework = "React"
  stage     = "DEVELOPMENT"
}
```

**Comment by jasondamour** [comment]
Ah, after testing I see thats the case.
