### ISSUE TITLE
XML file error

### ISSUE THREAD

**Issue by StopGuardianDev** [aws-amplify/amplify-hosting#3335]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

ddgwfgarxdvb5

### AWS Region

us-east-1

### Amplify Hosting feature

Manual deploys

### Describe the bug

[https://no.ddgwfgarxdvb5.amplifyapp.com/](url)
It says this :
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>FDCZWTAACBX7C2WN</RequestId>
<HostId>gngMM8HLNVQ8hQDc32fY9FepDyqVhirspawgJ73o+bd7cQBU2og9PriqOpivvPj0z3rxU2q2ASA=</HostId>
</Error>

### Expected behavior

My project won't work,

### Reproduction steps

1. git clone https://github.com/amethystnetwork-dev/Incognito.git
2. npm install
3. npm start

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I am testing aws on a web proxy to see how it works

**Comment by hloriana** [comment]
Hi @StopGuardianDev, thanks for raising this issue.

For manually deployed apps, you would need to run a build locally of your application and then zip the contents of that folder so it can be deployed with Amplify. Please see this guide for further details: https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html.

Also, Amplify provides hosting for static websites but according to [this documentation](https://amethystnetwork-dev.github.io/docs/static-hosts/), the application you are trying to deploy cannot be deployed with static site hosting providers. That can also be why the site is not properly deployed.
