### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by saikiranchalla1** [aws-amplify/amplify-hosting#3336]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3c8hq796dv5c6

### Region

us-east-1

### Step

Domain Activation

### Status

Success

### Issue or question

I had a few code changes and the deployment in Amplify was successful. But when I try to get to the URL for the app, both custom and Amplify hosted, I get an access denied error:

```
AccessDeniedAccess DeniedZTW5F4YT0ZKGSWDETB008TJGY0nP7woOjSJDO0Zeu8cy1Yg4extFGq1AbDkb2wn3WIQpRUKj0QV1SV5qXlM4DZFi7io=
```

### Error message

AccessDeniedAccess DeniedZTW5F4YT0ZKGSWDETB008TJGY0nP7woOjSJDO0Zeu8cy1Yg4extFGq1AbDkb2wn3WIQpRUKj0QV1SV5qXlM4DZFi7io=

**Comment by saikiranchalla1** [comment]
I have tried removing the rewrites and redirects, and all custom domains. I still get the error. I'm using Angular for my app.

**Comment by hloriana** [comment]
Hi @saikiranchalla1, you have the `baseDirectory` set to `dist/SkillClick`. Can you verify if that is the appropriate file path for your build artifacts?

**Comment by saikiranchalla1** [comment]
Hi @hloriana 
I can confirm that the `baseDirectory` is right. The `index.html` file is present in that directory.

**Comment by saikiranchalla1** [comment]
You were right @hloriana. The path was wrong in `angular.json`. Fixing it resolved the error. Thank you and I'm very sorry for the trouble. :)
