### ISSUE TITLE
CNAMEAlreadyExistsException for custom domain

### ISSUE THREAD

**Issue by ycchangabriel** [aws-amplify/amplify-hosting#3339]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2qaj96ayd9tj9

### Region

ap-southeast-1

### Step

Domain activation

### Status

Failed

### Issue or question

Domain activation failed with no idea where to troubleshoot.  I do not have any AWS account match the one mentioned in the error message.

[Speculation] The domain I purchased is not first-handed.  I lease it after the previous owner failed to keep the subscription.  I am therefore suspecting some CNAME records are left in the their AWS account.

### Error message

Error message: [CNAMEAlreadyExistsException] The following CloudFront distributions or Amplify Apps are already using one or more of your domains: [Distribution: *******A3GT6FR in AWS Account: ******532419]. For distributions you own, please remove the domains from them first and then retry adding your domain. For Amplify apps you own, you may already have associated this domain to another Amplify App in another accountor region. You can also check our troubleshooting guide for more help: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html

### Additional information

domain: gabriel.engineer

**Comment by hloriana** [comment]
Hi @ycchangabriel 👋🏽 , thanks for raising this issue. Since this domain is still associated with an active Amplify application in a separate AWS account, next steps would be for you to open a ticket with [AWS Support](https://support.console.aws.amazon.com/support/home?region=us-east-1#/) as we cannot provide cross-account assistance via GitHub.
