### ISSUE TITLE
how to host a php web app on aws amplify

### ISSUE THREAD

**Issue by Jegerh** [aws-amplify/amplify-hosting#3343]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-1

### Amplify Hosting feature

Backend builds, Build settings, Deployments, Frontend builds, Redirects

### Question

I'm trying to build a laravel web app on aws amplify. I've configured an ECR with php, nodejs, npm, composer etc to handle laravel. I then use this image to build an aws amplify app. Although it deploys successfully it does not load. 

I can tell .htaccess is an issue because aws amplify doesn't appear to use it. Is there a way to convert .htaccess to amplify redirects/custom headers?

Is it even possible to run a laravel app on amplify?

Loading mysite.amplify.com/index.php only downloads the index.php file rather than loading.

**Comment by hloriana** [comment]
Hi @Jegerh 👋🏽 thanks for raising this question. According to our [documentation](https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html):

> Amplify Hosting supports the common SPA frameworks, for example, React, Angular, Vue.js, Ionic, and Ember, as well as static site generators like Gatsby, Eleventy, Hugo, VuePress, and Jekyll.

Amplify supports hosting for static web sites (including SPAs) and for server-side rendered (SSR) apps using the Next.js framework. 

I'm not familiar with Laravel or PHP applications but it's possible that there needs to be a server that can interpret the `index.php` and provide the `js`, `html` files needed to display the app which Amplify doesn't support at this time.
