### ISSUE TITLE
Yarn zero-install PnP with Next.js on SSR provider

### ISSUE THREAD

**Issue by robinjoh** [aws-amplify/amplify-hosting#3347]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dmo7zkmrsd18o

### AWS Region

eu-west-1

### Amplify Hosting feature

SSR

### Question

I wonder if the current runtime can handle Yarn PnP or if it requires node_modules to get its dependencies? The build succeeds as expected but i get the following runtime error when using pnp as node linker: `Error: Cannot find module 'next/dist/server/next-server'.` So this makes me wonder if i am doing something incorrect when building the app or if this way of resolving dependencies is not supported in AWS Amplify hosting for next.js? I am using Next.js version 13 with SSR provider.

**Comment by nadetastic** [comment]
Hi @robinjoh thank you for opening this issue. I was attempting to look into the APP ID you shared but it appears that it may have been deleted.

Are you still facing this issue?
