### ISSUE TITLE
CWL_THROTTLING_EXCEPTION on Provision Step

### ISSUE THREAD

**Issue by gnewfield** [aws-amplify/amplify-hosting#3349]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1dqg4zhpoydyx

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Question

The Provision step of my deployment keeps failing, with this error message being displayed in the console: 

`[CWL_THROTTLING_EXCEPTION: The maximum request rate permitted by Amazon CloudWatch Logs has been exceeded for your account. Error message: Rate exceeded]`

I looked at CloudTrail and found that there are a lot of requests to the CreateLogStream API. (It should be noted, however, that this does not seem to be greater than the quota which is 50 TPS by default.) If the error is correct, I think there are two options to fix this:

1. Increase the quota
2. Reduce logging

I tried increasing the quota to 100, and this allowed the subsequent build to succeed. However, the next one failed for the same reason, so this does not seem to be a long-term fix.

I think reducing logging would be best, especially because the CreateLogStream requests seem to be resulting in `ResourceAlreadyCreatedException`. However, I do not see any options in the build or Amplify settings to control this.

Please advise.

**Comment by nadetastic** [comment]
Hi @gnewfield thank you for opening this issue. Has this happened to you consistently, and are you still currently experiencing this?
