### ISSUE TITLE
Any way for get current domain? [Following]

### ISSUE THREAD

**Issue by Guate-Jorge** [aws-amplify/amplify-hosting#3355]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2nlxtzfnzygvs

### AWS Region

us-east-1

### Amplify Hosting feature

Build settings

### Question

> Hi @vadimka123 thanks for raising this question. Are you asking if there is a way to retrieve the web preview domain during the build process?

_Originally posted by @hloriana in https://github.com/aws-amplify/amplify-hosting/issues/2909#issuecomment-1209999216_
       
Hello @hloriana, I am also looking for information on the same topic. Do you have any advice or updates on this that you could share with me? Thank you!

**Comment by Jay2113** [comment]
Hi @Guate-Jorge 👋 , thanks for reaching out to us and apologies for the delayed response on this thread.

You can retrieve/construct the web preview domain URL during the build process using [Amplify environment variables](https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#amplify-console-environment-variables) as follows:

```
echo "https://pr-$AWS_PULL_REQUEST_ID.$AWS_APP_ID.amplifyapp.com"
```

We are working on adding the `AWS_PULL_REQUEST_ID` environment variable to our official AWS documentation.

**Comment by Jay2113** [comment]
We have updated our official documentation to include the `AWS_PULL_REQUEST_ID` environment variable: https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#amplify-console-environment-variables
