### ISSUE TITLE
how to claim domain name for amplify custom domain when used on another AWS account with no access to it

### ISSUE THREAD

**Issue by 99electronic** [aws-amplify/amplify-hosting#3361]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-2:206402932923:apps/d3nl8au7y7rvf8

### Region

us-east-2

### Step

domain activation

### Status

failed with resource in use on another account

### Issue or question

I'm trying to add custom subdomain to amplify app, but getting message that it is already in use with another resource. I'm the domain owner now and need to claim it. I do not have access to that another AWS account and previous owner does not remember which email was used to login. I do not have aws account number as the error only shows 5 last digits. I have full DNS access, how to claim this to my AWS account without accessing the old one?

### Error message

above

### Additional information

I'm able to create subdomain which is not in use on previous account (dev is not available but for instance dev3 id) Somehow I need to remove this domain from old account all together

**Comment by hloriana** [comment]
Hi @99electronic 👋🏽 we cannot provide cross account assistance via GitHub. Please open a case with AWS Support for further assistance [here](https://support.console.aws.amazon.com/support/home?region=us-east-1#/case/create).
