### ISSUE TITLE
Is there any difference between the "production environment" and other environments?

### ISSUE THREAD

**Issue by chrisfosterelli** [aws-amplify/amplify-hosting#3363]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

ca-central-1

### Amplify Hosting feature

Deployments

### Question

When using amplify hosting in the AWS console, apps have a "production environment" attribute that can be set, under repository settings.

![image](https://user-images.githubusercontent.com/2072672/224086844-bb24cb6b-9fbe-4cfa-a080-472f304f1bdb.png)

What is the actual difference between the environment denoted as production environment and any other environments on the application? 

This is a simple manual amplify hosting app and we are considering deploying multiple production versions through different environments, but if all non-production environments get some sort of "dev environment" behaviour that makes them slower then this might not be the best approach for us.

**Comment by swaminator** [comment]
@chrisfosterelli currently there isn't a difference between the two so you should be okay to deploy multiple prod versions.

**Comment by chrisfosterelli** [comment]
@swaminator Thank you!
