### ISSUE TITLE
App does not load at <id>.cloudfront.net 

### ISSUE THREAD

**Issue by hnhegde** [aws-amplify/amplify-hosting#3365]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1px6elllbl4t3

### Region

us-east-2

### Step

Domain activation

### Status

Failed

### Issue or question

App is accessible at: https://master.d1px6elllbl4t3.amplifyapp.com. 
I am trying to setup custom domain in Amplify. I followed the [instructions provided](https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-a-third-party-dns-provider.html). Status is stuck at: "Domain Activation". 

![image](https://user-images.githubusercontent.com/4962589/224241631-14c6f3ac-603d-4c4d-bd6c-df785ab4270e.png)

When I click on Actions->View DNS records, the id is different from the appid provided though:
![image](https://user-images.githubusercontent.com/4962589/224242803-a743a234-a74d-4acd-bba1-d2c2e2f30b6d.png)

Nonetheless, my app never loads at the url provided: 

![image](https://user-images.githubusercontent.com/4962589/224243471-1e0c91f3-188e-4772-b937-3cf9efb88a2b.png)

I also tried plugging in the appid in the URL, but same result.

![image](https://user-images.githubusercontent.com/4962589/224243742-2327fdd5-770e-460a-a4d6-a1b015d67335.png)

### Error message

HTTP 404 Error

### Additional information

Issue is similar to: https://github.com/aws-amplify/amplify-hosting/issues/1883

**Comment by hloriana** [comment]
Hi @hnhegde 👋🏽 Apologies for the confusion. Do you see those instructions in the console? Please let us know where those instructions surface so that we can update them accordingly.

According to our [documentation](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-404-cloudfront-url):

> To serve traffic, Amplify Hosting points to a CloudFront URL via a CNAME record. In the process of connecting an app to a custom domain, the Amplify console displays the CloudFront URL for the app. However, you cannot access your application directly using this CloudFront URL. It returns a 404 error. Your application resolves only using the Amplify app URL (for example, https://main.d5udybEXAMPLE.amplifyapp.com, or your custom domain (for example www.example.com).

It looks like the domain activation has succeeded since opening this issue. Do you require any further assistance?

**Comment by hnhegde** [comment]
Hi @hloriana ,
Under Domain Management -> Actions->View DNS records, I see:
![image](https://user-images.githubusercontent.com/4962589/226075523-51ac6365-d42e-4715-8612-f11f73ed8fb1.png)

Yes, activation is now fine. I am using CloudFlare as my DNS manager and have created a CNAME record there pointing to the *.amplifyapp url. That seems to have worked.
