### ISSUE TITLE
Amplify intergration with CodeCommit - build not started

### ISSUE THREAD

**Issue by YairBunker** [aws-amplify/amplify-hosting#3366]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-1

### Amplify Hosting feature

Build settings, Deployments, Frontend builds

### Describe the bug

I have built a sample next.js app in CodeCommit and created a new app in Amplify which is associated with my code repo. In Amplify, I have set the build settings to automatically run a build when a new commit is added to the main branch. When adding new commits, Amplify does not start the build and deploy process automatically.

Please see - 

Amplify app ARN: 
arn:aws:amplify:us-east-1:334328381145:apps/d169vflm8bz309

### Expected behavior

New commit to code commit should invoke a build process in AWS Amplify.

### Reproduction steps

create a new code repo on CodeCommit and add a sample next.js app there.
create a new app in Amplify, and associate it with the CodeCommit code repo.
Connect the main branch to the Amplify app and enable the auto-build option
Add a new commit to the main branch in the code repo
Observe that AWS amplify does **not** start a build+deploy process.  

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriii** [comment]
Hi @YairBunker 👋🏽 apologies for the oversight on this issue. I've tried reproducing this behavior but new commits pushed to CodeCommit repositories appear to trigger new builds appropriately. I can see that you've had recent changes made to your application; are you still running into this behavior?

**Comment by YairBunker** [comment]
Hello, yes, we have investigated and resolved the integration issue between code commit and amplify. It was related to encryption which was added to the SNS queue between code commit and amplify, for which we have enabled access to the keys used for encryption.
