### ISSUE TITLE
When Redirecting From/To URLs With Trailing Slash, URL Query Doesn't Persist

### ISSUE THREAD

**Issue by anatolzak** [aws-amplify/amplify-hosting#3374]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2d2aijy8ye0g3

### AWS Region

us-east-1

### Amplify Hosting feature

Redirects

### Describe the bug

I have deployed a simple Next.js app to AWS Amplify from the following repo: https://github.com/anatolzak/nextjs-query-example

When I go to any page (except the index page) without a trailing slash and add url query params, it redirects me to the url with a trailing slash but **drops my url query**.

So if I go to: `https://main.d2d2aijy8ye0g3.amplifyapp.com/test?query_1=true`, it redirects me to `https://main.d2d2aijy8ye0g3.amplifyapp.com/test/`

In my `next.config.js`, I set `trailingSlash` to `true` so it redirects urls without a trailing slash to their counterpart with a trailing slash. 
Without setting `trailingSlash` to `true` in Next.js apps, urls with a trailing slash produce 403 status code which is another issue https://github.com/aws-amplify/amplify-hosting/issues/3373, but I am sure that if AWS Amplify redirected you from urls with a trailing slash to without a trailing slash, which is the default expected behavior for Next.js apps, I am sure AWS Amplify would still drop the query param as described above.

I can also confirm it happens with Gatsby apps as well, where they default to redirecting urls without a trailing slash to their counterpart with a trailing slash, but AWS Amplify drops the query params during the redirect as well. 

But when using Vercel for both Gatsby and Next.js apps, it never drops query params when redirecting to/from urls with a trailing slash.

### Expected behavior

When redirecting to/from urls with a trailing slash, url query should persist and not be deleted after the redirect.

### Reproduction steps

1. Deploy a Next.js app from this repo https://github.com/anatolzak/nextjs-query-example
2. Delete any rewrites or redirects
3. Go to `/test?query=1`, and it will redirect to `/test/`

**Comment by anatolzak** [comment]
Is there any progress on this issue?

**Comment by anatolzak** [comment]
Has there been any progress on this issue?

**Comment by anatolzak** [comment]
This issue doesn't occur with next.js ssr apps. 
It does occur with next.js ssg apps or any other ssg apps. All my gatsby apps have the same issue as well.

**Comment by Jay2113** [comment]
@anatolzak 👋 , we have shipped a fix for this behavior and this issue should no longer occur. Thanks for your continued patience!
