### ISSUE TITLE
Can't create a new AWS Amplify application due to "Houston, there's a problem"

### ISSUE THREAD

**Issue by sineto** [aws-amplify/amplify-hosting#3376]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Question

I'm trying to create a new app with AWS Amplify console but in the last step I'm always receiving the error
>  "Houston, there's a problem We are unable to process your request. Please reach out to your support representative."

- Next.js latest version
- Application from GitLab private repository

How can I proceed with that?

**Comment by hloriii** [comment]
Hi @sineto 👋🏽 thanks for raising this question. Can you outline the steps you're following to host an application so that I can try to reproduce the behavior on my end? Also, if you can, please provide a screenshot of the error.

**Comment by ibogdan94** [comment]
have the same error

**Comment by sineto** [comment]
The steps I'm following:
- Press _Get Started_ on dashboard
- Choose GitLab source repository
- Set config: Next.js repository on GitLab; `main` branch; mark monorepo connection;
- Set _Advanced Settings_ with proper environments variables and with _Live package updates_ set to Next.js latest version

And that's pretty much it
![2023-03-27_00-20](https://user-images.githubusercontent.com/7028658/227832918-e0bd0c93-4e4d-4ac8-a09f-10ab6e0bff15.png)
