### ISSUE TITLE
8-13 Min Build Times For Static Sites Because of "Installing Node version 16"

### ISSUE THREAD

**Issue by anatolzak** [aws-amplify/amplify-hosting#3378]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2zy39zyfphuy2

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Describe the bug

I have a Next.js SSG app on AWS Amplify. I found 3 builds on different days whose build times were: 8 minutes, 9.5 minutes, and 13.5 minutes.

Normally, our build times are 3 minutes. Looking into the build logs, I found that this command was causing the long build times: `Installing Node version 16` which is in the `Build` - `Cloning repository` step.

Here are the portion of the logs for each of the builds showing the addition of 5-10 minutes to the build time during that command.

```
2023-03-20T11:06:33.470Z [INFO]: # Installing Node version 16
2023-03-20T11:11:40.219Z [WARNING]: ! Unable to patch packages...
```

```
2023-03-16T17:21:12.653Z [INFO]: # Installing Node version 16
2023-03-16T17:27:37.500Z [WARNING]: ! Unable to patch packages...
```

```
2023-03-15T11:15:27.719Z [INFO]: # Installing Node version 16
2023-03-15T11:25:56.476Z [WARNING]: ! Unable to patch packages...
```

### Expected behavior

Builds for static sites shouldn't take 8-13 minutes. Normally, the build times are about 3 minutes, but I got 8-13 minute builds 3 times in 3 different days (March 15, March 16, March 20)

### Reproduction steps

1.  

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriana** [comment]
Hi @anatolzak 👋🏽  thanks for raising this issue. This appears to be an intermittent issue with Node.js according to one of their GitHub issues reported on 3/16: https://github.com/nodejs/node/issues/47120.

**Comment by hloriii** [comment]
It looks like the extended build times in those 3 occurrences were due to the Node.js issue mentioned above. Your recent builds appear to average around 2-3 minutes. If you run into this behavior in the future, please feel free to open a new issue. Thank you!
