### ISSUE TITLE
On migration of web dynamic to web compute for NextJs app, Environment variables are not getting assigned properly

### ISSUE THREAD

**Issue by rupeshcw** [aws-amplify/amplify-hosting#3381]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3bhy9n779jun9

### AWS Region

ap-south-1

### Amplify Hosting feature

Environment variables

### Describe the bug

-> After Migration from web dynamics to web compute, it redeployed master branch which is obvious but it picked default environment variables in place of overwritten for master branch.
-> also happening for other branches it's not picking env variable correctly defined for specific branch. 

### Expected behavior

-> It should pick environment variable defined for same branch or default if not exist 

### Reproduction steps

1. define default and branch specific environment variable
2. deploy master or any branch
3. migrate to web compute 
4. redeploy same branch

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriana** [comment]
Hi @rupeshcw 👋🏽 , I was unable to reproduce this behavior. Here is what I tried

1. create a Next app with version 11
2. deploy 2 branches to Amplify app2: `master` and `staging`
3. setup environment variable with override for `staging` branch
4. redeploy the branches to ensure the proper values are applied for each branch
5. upgrade Next version to 12
6. migrate application to `WEB_COMPUTE`
7. redeploy branches

I checked the logs for each branch and they were both using the appropriate environment variables and overrides. 

In your case, are the overrides not being applied to the specified branches?
