### ISSUE TITLE
mp4 files AccessDenied. Status 403 

### ISSUE THREAD

**Issue by lien-dkseo** [aws-amplify/amplify-hosting#3385]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1qa7vk27tk7ku

### AWS Region

ap-northeast-2

### Amplify Hosting feature

Manual deploys, Redirects

### Question

Question: how to get .mp4 files

1. cra app local build
2. only amplify hosting env. no backend env.
3. manual deploy
4. 'drag and drop' from local build directory
5. only mp4 file is 403 error (space.mp4 is 5.59MB)

![image](https://user-images.githubusercontent.com/91306431/227087834-e52015da-4832-48dc-96ca-0496c833f46e.png)

```
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>1QVT7KJ6CTJ2JYGG</RequestId>
  <HostId>op/ljMUiwZPiAldYUJYNu8YVWWclslHrW89tKA7GcGdlIVQyEnWeR+6Y3XB+C8Ab78nHKubZm/4=</HostId>
</Error>
```

![image](https://user-images.githubusercontent.com/91306431/227088262-8501de87-9dac-4ef9-b766-5045833b9b85.png)
6. 'mp4' redirect not working
```
</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|woff2|ttf|map|json|webp|mp4)$)([^.]+$)/>
```
7. changing ext from .mp4 to .png or .jpg does not work

**Comment by hloriii** [comment]
Hi @lien-dkseo 👋🏽 thanks for raising this question and apologies for the delay. This can happen if you drag and drop zipped folder if you zipped the folder itself. In this case, try to perform a Manual Deploy by navigating inside the build directory and zipping up the contents. Then deploy the zip via drag and drop. 

However, it looks like the MP4 file is loading successfully now:

<img width="679" alt="Screenshot 2023-03-28 at 6 17 05 PM" src="https://user-images.githubusercontent.com/76065904/228388233-77c3c621-b3f7-4821-9456-99bbcb0b3645.png">

Did you use different steps to mitigate this issue?

**Comment by lien-dkseo** [comment]
Hi @hloriii thanks for response

![image](https://user-images.githubusercontent.com/91306431/228394380-c5695ff6-9bc9-4599-8028-f0f252bdbe25.png)
Currently redirecting to another url.

i'll try 'deploy the zip via drag and drop'

**Comment by lien-dkseo** [comment]
@hloriii thanks !!
it's working with no redirecting.

`deploy the zip`

![image](https://user-images.githubusercontent.com/91306431/228395675-bd5ffbcc-21ba-49f3-a254-36ee7c8c3f18.png)
