### ISSUE TITLE
Domain is not Showing made application

### ISSUE THREAD

**Issue by habibshahid2013** [aws-amplify/amplify-hosting#3391]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

https://us-east-2.console.aws.amazon.com/amplify/home?region=us-east-2#/dexvpd8cs3sf4/main/6

### Region

US-east(ohio)

### Step

n/a

### Status

404

### Issue or question

I'm not sure what my Application isn't showing as hosted. I'm seeing a 404:

[https://main.dexvpd8cs3sf4.amplifyapp.com ](https://main.dexvpd8cs3sf4.amplifyapp.com/)
Started at
3/26/2023, 5:22:26 PM
Build duration
-

Source repository
https://github.com/habibshahid2013/PBS-MovieApp-Project/tree/main

### Error message

404

### Additional information

I'm running the application on next.js. not sure whats the problem is

**Comment by hloriii** [comment]
Hi @habibshahid2013 👋🏽  apologies for the delay here. 

This issue appears to be similar to https://github.com/aws-amplify/amplify-hosting/issues/3398.

A 404 can occur if the Amplify app's platform setting is incorrect and if the branch's framework setting is incorrect. If you are still running into this behavior, you can try running the following AWS CLI commands:

`aws amplify update-app --app-id <APP_ID> --platform WEB_COMPUTE --region <REGION>`
`aws amplify update-branch --app-id <APP_ID> --branch-name <BRANCH_NAME> --framework 'Next.js - SSR' --region <REGION>`

Please let us know if this resolves the issue for you.
