### ISSUE TITLE
Stuck on SSL configuration: Hosted with Route 53

### ISSUE THREAD

**Issue by mattfixme** [aws-amplify/amplify-hosting#3393]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1whutde7aoqvo

### Region

us-east-2

### Step

Domain activation

### Status

Stuck

### Issue or question

Domain activation stuck on "SSL Configuration" for more than 24 hours. My domain is on Route53. All configurations are done, but custom domains always fail to activate.

![Xnip2023-03-28_16-45-45](https://user-images.githubusercontent.com/94779860/228181285-d1767b52-29bf-4c25-805c-bd8840e60253.jpg)

### Error message

the page request "checkDNS" error
![Xnip2023-03-28_16-02-02](https://user-images.githubusercontent.com/94779860/228169716-c457af5d-5f51-443c-904c-5d2f889b0403.jpg)

**Comment by hloriii** [comment]
Hi @mattfixme 👋🏽 thanks for raising this issue. Upon initial investigation, it looks like the certificate is properly resolving at this time. You can also verify this plugging the record into https://dnschecker.org/#CNAME/domain.com. Are you still experiencing this issue?

**Comment by mattfixme** [comment]
yes, it's ok. thx
