### ISSUE TITLE
Amplify website API calls not functioning

### ISSUE THREAD

**Issue by FelixDeMan** [aws-amplify/amplify-hosting#3395]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3k83whk2hxwnm

### AWS Region

us-east-1

### Amplify Hosting feature

Public APIs

### Describe the bug

I made a website that communicates with our ML model on a GCP VM through API calls. The API calls on my website are set-up in the following way:
 **try {     
      const response = await fetch('http://34.90.xxx.xxx:5000/endpoint_replace', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(payload)
      });
  **
  
  These API calls work locally, but are not functioning once uploaded through Amplify. The firewall set-up should be correct and accept all incoming calls. Why does it work from my machine but not from the Amplify website?
  
  Maybe relevant info: the VM is located in EUW, while the amplify is hosted on us-east. The VM uses a Flask app (yes, with CORS) and worked earlier when connecting to streamlit front ends.

### Expected behavior

I expect to get the correct response, or at the very least a response on the VM. The call is not coming in.

### Reproduction steps

Clone the git branch
Run locally
Deploy on Amplify
Try /demo page

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriii** [comment]
Hi @FelixDeMan thanks for raising this issue. Could provide a screenshot of the error or an HAR capture of the request being made?
