### ISSUE TITLE
App could not be loaded with enabled Access control

### ISSUE THREAD

**Issue by labeh** [aws-amplify/amplify-hosting#3397]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2teuflyxbwkga

### AWS Region

eu-central-1

### Amplify Hosting feature

Access control

### Describe the bug

**Problem Description**
I am not able to access the Amplify app via the browser. It is loading forever without any progress and success.

**Problem Analysis**
I have redeployed the application without success. Accessing via the internal amplifyapp URL gives the same result. The Amplify Access Log shows a 301 for redirection to HTTPS and a 401. I assumed that the problem is related to the "Access control" feature, so I deactivated it and everything worked as expected. So my guess is that the "Access control" function does not work properly. I double-checked this with a second app which was working before with the "Access control" feature and it shows the same unintended behaviour.

### Expected behavior

The browser should receive an answer to trigger the basic auth and to continue loading the files from the Amplify server.

### Reproduction steps

1. Have "Access control" enabled
2. Try to open the Amplify (or custom) URL via the browser

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriii** [comment]
Hi @labeh 👋🏽 I just tried to reproduce this behavior but I was able to use Access Control as expected without any bugs. We have a weird known bug where using a `:` in the password causes the access control settings to revert but even in that case, the website is still accessible. 

Are there any special characters that you're using in your credentials? That could potentially be the cause of this behavior.

**Comment by hloriii** [comment]
Also, when you have access control enabled, are you prompted to enter in the credentials or does that not show up as well?

**Comment by TonyKnibb-MakaraHealth** [comment]
I have the same issue and our password is just letters and numbers.

**Comment by labeh** [comment]
For me the access control is now working again as expected. I haven't changed anything though and did not do any deployments or config changes. The Basic Auth Popup is now popping up again as expected and with the right credentials, I am able to "login".
