### ISSUE TITLE
I cannot add Git CI/CD to a new frontend environment in Amplify

### ISSUE THREAD

**Issue by prof2k** [aws-amplify/amplify-hosting#3399]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1nzj85x7cuacz

### AWS Region

us-east-1

### Amplify Hosting feature

Git providers

### Describe the bug

I used to be able to add a git provider to my project frontend environment but after creating a new environment and deploying with an s3 bucket, when I click "add Environment" it doesn't show an option to add a git provider anymore. Also, I can't find any place on the entire console that allows me to add a repository to the app.

The problem is that I need a CI/CI pipeline to add environmental variables to the app so the backend environment can work as per this thread: https://github.com/aws-amplify/amplify-hosting/issues/441 I think it may have something to do with my using S3 bucket for the current frontend environment (new) and then moving the upload but I may be wrong.

### Expected behavior

The console should have an interface that allows me to connect Git to the application. Currently, there's no way for me to do that. 

### Reproduction steps

![image](https://user-images.githubusercontent.com/52117110/228678432-7725c13e-158c-439a-9dce-7aceff3777f9.png)
![image](https://user-images.githubusercontent.com/52117110/228678537-d4f35552-34db-4753-84d1-81348e434e1b.png)

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

https://user-images.githubusercontent.com/52117110/228679705-5b69bfa5-968d-4343-8de5-5e220714e49f.mp4

**Comment by hloriii** [comment]
Hi @prof2k  👋🏽 thanks for raising this issue. Amplify Hosting has 2 methods for hosting your application:
1. [Continuous deployment](https://docs.aws.amazon.com/amplify/latest/userguide/getting-started.html) - connect the application to a git repository and automate builds that trigger with new commits.
2. [Manual deploys](https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html) - drag and drop a zip file or host your application from files stored in S3

You cannot convert a manually deployed app to a CI/CD app or vice versa. That is why you no longer see the option to connect to a git provider in the console after manually deploying your application. You have 2 options to move forward in this scenario:

1. If you want to keep your current manually deployed frontend, you can create a new Amplify application that uses a git provider and then connect that application to the backend environment in `d1nzj85x7cuacz`. 
See [Reuse backends when creating a new app](https://docs.aws.amazon.com/amplify/latest/userguide/reuse-backends.html#reuse-backends-create-connect)

3. Or, if you don't want to keep the manually deployed frontend, you can delete your frontend environment by navigating to `app settings -> general -> environments -> select your branch name -> actions -> disconnect`

<img width="1117" alt="Screenshot 2023-03-29 at 6 19 16 PM" src="https://user-images.githubusercontent.com/76065904/228691159-3b7cdf1d-01c3-40ca-835b-13c3039f754f.png">

**Comment by prof2k** [comment]
Wow. Thanks. I thought is was a bug or something.

Resolved
