### ISSUE TITLE
CloudWatch Log Group does not exist

### ISSUE THREAD

**Issue by reeslabree** [aws-amplify/amplify-hosting#3408]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

djcjv9hw2o9as

### AWS Region

eu-central-1

### Amplify Hosting feature

Access logs

### Describe the bug

After navigating to `Monitoring > Hosting compute logs` and clicking the CloudWatch log stream associated with my main branch, the CloudWatch Management Console returns a banner across the top of the screen that says "Log group does not exist".

### Expected behavior

Directed to the CloudWatch log group associated with my app.

### Reproduction steps

1. New App.
2. Host new app.
3. Connect Github.
4. Deploy.
5. Select CloudWatch log group using steps above.

### Log output

<details>

```
none
```

</details>

### Additional information

I've checked all additional regions outside of `eu-central-1` and this log group doesn't exist.

**Comment by hloriii** [comment]
Hi @reeslabree thanks for raising this issue. I was not able to reproduce this behavior on my end and I only see the error if I navigate to a region where the log group doesn't exist. Are you seeing this behavior for multiple branches or the just the main branch?

**Comment by reeslabree** [comment]
@hloriii I only have the main branch deployed at the moment. After giving it some thought, I'm wondering if it means that my NextJS lambda@edge function is not being deployed, and hence no log group. When I load the application, it shows some bare bones HTML and CSS, but also displays `Error 500`. I'd like to investigate this error more, but alas, no log group.

**Comment by hloriii** [comment]
Hi @reeslabree 👋🏽  apologies for the delay here. Can you check your CloudTrail even history to see if there is a [DeleteLogGroup](https://us-east-1.console.aws.amazon.com/cloudtrail/home?region=us-east-1#/events/bbf460e0-069c-4671-8eba-68d2262e69dc) event that occurred?  It's possible that your log group may have been delete. 

Can you also try hosting a new branch or app and see if the issue persists? 

ref: https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_DeleteLogGroup.html

**Comment by reeslabree** [comment]
@hloriii Resolved. Amplify did not automatically create a service role, and thus there wasn't a role associated with it that had the permission to create log group.
