### ISSUE TITLE
Incredibly slow cold starts

### ISSUE THREAD

**Issue by borisyordanov** [aws-amplify/amplify-hosting#3412]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d26rfy7bgd5d4z

### AWS Region

ca-central-1

### Amplify Hosting feature

Deployments

### Describe the bug

If I haven't visited a deployment in a while (or I visit one that's just been created), it takes ages (~15 seconds) for the page to load. This is surprising considering my landing page only has a sidebar and an h1 tag.

After the first load follow-up re-loads are quick (even after clearing local cache). The only conclusion I can make is that a part of AWS' infra is falling asleep which causes poor performance.

### Expected behavior

The page should load in under 1s.
[Source](https://www.thinkwithgoogle.com/marketing-strategies/app-and-mobile/page-load-time-statistics/)

### Reproduction steps

1. Load a deployment after it's created or fallen asleep, e.g. https://main.d26rfy7bgd5d4z.amplifyapp.com/

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriii** [comment]
Hi @borisyordanov 👋🏽 thanks for raising this issue. The Amplify Hosting team is aware of this behavior and we are working on mitigation. We have identified that some apps have a higher app initialization time which can contribute to high TTFB. You can test this locally for your app by following this guide: [Measure Compute app's initialization/start up time locally](https://github.com/aws-amplify/amplify-hosting/blob/main/FAQ.md#measure-compute-apps-initializationstart-up-time-locally)

**Comment by hloriii** [comment]
We are also using issue https://github.com/aws-amplify/amplify-hosting/issues/3211 to track this particular behavior and will be providing future updates on that issue. 

Closing as duplicate.
