### ISSUE TITLE
Amplify build stuck on Provisioning step

### ISSUE THREAD

**Issue by NoahFarris** [aws-amplify/amplify-hosting#3413]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2r19n766h639

### AWS Region

us-west-2

### Amplify Hosting feature

Frontend builds

### Describe the bug

My Amplify Frontend APP is connected to Github and has had 30(ish) successful builds, today I pushed out some very minor changes to my Github main branch, which was picked up correctly by my amplify app, however, it has been stuck on the provisioning step. It does not move from this step at all, does not give me any indication of what's going on, it simply has the docker command and that's it, with no failures.

### Expected behavior

The build finishes successfully (or at least makes it to the build stage).

### Reproduction steps

1. Make change to React application's code.
2. Push change to github main branch.
3. Go into Amplify console and view build, which is now stuck in provisioning stage.

### Build Settings

```yaml
My amplify.yml:

version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
```

### Log output

<details>

Perhaps this is what I'm confused by, there are no log outputs, it runs the docker command and sits there, doing nothing. With no info about what's going on.

</details>

### Additional information

Things I've done with no success:
1. Manually redeploy the build.
2. Manually redeploy old build that has worked in the past (Last successful build was on March 21st 2023)
3. Update Node version to 14 (like what's been done in previous issues).
4. Disconnected and reconnected github.
5. Attempted to create a new app that points at the same Github repo (this actually resulted in the error 400: "Pagesize must be greater than 0", which I'll be submitting a separate issue for).

**Comment by Jay2113** [comment]
Hey @NoahFarris 👋, 

In order to further troubleshoot your issue, please reach out to the AWS Support team: https://aws.amazon.com/support for additional assistance.

Thank you!
