### ISSUE TITLE
amplify backend studio failes

### ISSUE THREAD

**Issue by beeble-donghyunna** [aws-amplify/amplify-hosting#3417]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2um7ciz10fth0

### AWS Region

us-east-2

### Amplify Hosting feature

Backend builds

### Question

Once i start backend environments, the error occurs as follows

Failed to update sandbox app for backendManagerAppId ce9255a0-163e-44bd-b4d9-62dd8be63dfa and region us-west-2.

**Comment by hloriii** [comment]
Hi @beeble-donghyunna 👋🏽 thanks for raising this issue. Can you provide reproduction steps and any relevant screenshots of the error you're running into?

**Comment by ajessu** [comment]
@beeble-donghyunna We were able to reproduce this issue recently on the Studio side and  have released a fix. Could you try again and report back whether you're still experiencing this issue?

Thanks!
