### ISSUE TITLE
Unable to remove trailing slash from any pages

### ISSUE THREAD

**Issue by ShivamJoker** [aws-amplify/amplify-hosting#3421]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2qol2ytcn686p

### AWS Region

us-east-1

### Amplify Hosting feature

Redirects

### Describe the bug

Unable to remove trailing slash from any pages.

My website is hosted at https://sqlplay.net (no problem with root)
If I try to visit https://sqlplay.net/privacy

I get redirected to `https://sqlplay.net/privacy/` <--- trailing slash

My amplify redirect rules config:

```json
[
    {
        "source": "/<*>/",
        "target": "/<*>",
        "status": "301",
        "condition": null
    }
]
```

### Expected behavior

It should just keep me to `/privacy`, but it redirects to `/` version the page.

### Reproduction steps

Host a static website on amplify with multiple HTML pages.

Configure the redirect rules as mentions above.

Try to visit a non-root page.

My tree looks like this:

```
├── index.html
├── mstile-150x150.png
├── og-image.webp
├── privacy
│   └── index.html
```

**Comment by hloriii** [comment]
Hi @ShivamJoker 👋🏽 thanks for raising this issue. This is a known bug with redirects where we add a trailing slash for 301 and 302 redirects. This bug is being prioritized and we are working on fixing this. We apologize for the inconvenience and will update this issue once this has been resolved.

**Comment by ShivamJoker** [comment]
@hloriii it's been almost a month.
Any update?

**Comment by saadataz** [comment]
@ShivamJoker this is by design. Please review the [redirect behavior documentation](https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#trailing-slashes-and-clean-urls)

If you would like to avoid redirecting https://sqlplay.net/privacy to https://sqlplay.net/privacy/, you can move the file `/privacy/index.html` to `/privacy.html`
