### ISSUE TITLE
LambdaLimitExceeded errors for app hosted on custom domain

### ISSUE THREAD

**Issue by thiagobasilio-nanga** [aws-amplify/amplify-hosting#3422]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-1:318362644734:apps/d3f02ubvvviwfu

### Region

us-east-1

### Step

Domain on production - Lambda limits exceeded

### Status

Error

### Issue or question

Hi,

One of our frontend developers just noticed that we're getting a response header with the following error from CloudFront:

`x-cache: LambdaLimitExceeded from cloudfront`

![amplify_cloudfront_lambda_limit_exceeded](https://user-images.githubusercontent.com/53570042/231586022-71ea178f-7866-4210-b00a-d0492f24e20b.png)

I double-checked the Lambda Concurrent executions limits, but our usage isn't crossing the current limit (1000).

I wonder what could be done to fix this issue since we're not able to access or see anything that AWS Amplify provisions behind the scenes (e.g., CloudFront distributions or Lambda functions).

Kind regards,
Thiago

**Comment by hloriii** [comment]
Hi @thiagobasilio-nanga 👋🏽  thanks for raising this issue. 

Between 12:08 PM and 12:09 PM PDT on 04/12/2023, we experienced an increase in error rate in US-EAST-1. The issue has been resolved and the service is operating normally.
