### ISSUE TITLE
Nextjs latest 13.3.0 deploy breaks IMAGE (next/image)

### ISSUE THREAD

**Issue by marketsystems** [aws-amplify/amplify-hosting#3428]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

eu-west-2

### Amplify Hosting feature

Deployments, Frontend builds

### Describe the bug

Deployed a simple gallery to Amplify as a test of my nextjs app which pulls images from cloudinary and passes them to next/image, site loads in browser fine and navigation to all pages works BUT ALL images appear broken using next/image <Image ... /> (server error 500 on all images).

Tried image urls from images hosted on S3 instead -> same issue all images broken.

Image Domains are allowed and correct in next.config.js

Using Next 13.3.0 npm package (the latest)
Using Nextjs App Dir

I have an app on amplify using next 13.2.0 and had no image problems at all so:
**downgraded next package version to 13.2.0 SUDDENLY ALL IMAGES WORK FINE from any source!!**

Can only assume next 13.3.0 and amplify do not work nicely yet

### Expected behavior

The images should show instead of server error 500 and broken!

### Reproduction steps

As Above description

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by killyvera** [comment]
i also had issues in the next 13 build provision phase, i cant go foward, but hosting my app in netifly works ok, it happened suddenly.

**Comment by shankiflang** [comment]
Same problem here !

**Comment by QuadTriangle** [comment]
@aws-amplify

**Comment by marketsystems** [comment]
> Had the same issue, and based on the error in CloudWatch, it seems like the following issue: [vercel/next.js#48173](https://github.com/vercel/next.js/issues/48173)
> 
> So downgrading to 13.2.4 fixed this for me for now.

Yeah found 13.2.4 works fine! How do u find the error in cloudwatch? Not that clued up with aws yet myself but I did check cloudwatch to see if I could find out what it was - couldnt find an error log easily though..

**Comment by marketsystems** [comment]
> Hi folks, this appears to be an issue related to Next.js 13.3.0 that _may_ not be specific to Amplify Hosting according to this issue [vercel/next.js#48173](https://github.com/vercel/next.js/issues/48173)
> 
> However, we are investigating this further on our end to determine next steps. In the mean time, please downgrade Next to the previous working version.

I dont think its entirely AWS might be something other module related (potentially sharp according to that other linked thread), but can tell you my project works on 13.3.0 locally with images showing and also no problems deployed to Vercel. Would be nice if it worked on Amplify too :D ;)

**Comment by hloriii** [comment]
Hi @marketsystems thanks for those details. You can find those logs in the Amplify console by following these steps:
1. Navigate to **Monitoring**
2. Select the **Hosting compute logs** tab
3. Select the log group and a new tab will open with log events listed in the CloudWatch console

**Comment by hloriii** [comment]
This issue no longer persists after the deployment of this fix from Next.js: https://github.com/waldo-vision/waldo/pull/293

This was not an issue from Amplify Hosting and appears to have been resolved front Next.js side.
