### ISSUE TITLE
Cannot create new Amplify application: Error connecting repository "There was an issue setting up your repository."

### ISSUE THREAD

**Issue by JackLot** [aws-amplify/amplify-hosting#3434]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-1

### Amplify Hosting feature

Not Applicable

### Describe the bug

The Amplify web UI fails to create a new hosting application. After clicking "Save and deploy" I get the following 400 error:

```
There was an issue setting up your repository. Please try again later.
({"message":"Not Found","documentation_url":"https://docs.github.com/rest/webhooks/repos#create-a-repository-webhook"})
```
<img width="798" alt="Screenshot 2023-04-19 at 12 31 58 AM" src="https://user-images.githubusercontent.com/1841253/232968872-1f181644-f789-4b57-8d12-8b853c1547de.png">

I followed the steps in the [user guide](https://docs.aws.amazon.com/amplify/latest/userguide/setting-up-GitHub-access.html#setting-up-github-app). GitHub authorization is successful and I am able to select a repository and branch. Build settings are left as the defaults; however, when I click "Save and deploy" I am immediately shown the error message above.

Logging in and logging out (as suggested by other issues) did not work. Revoking permissions on GitHub then reauthorizing Amplify did not work. Permissions on the Github side seem to be fine.

### Expected behavior

I click "Save and deploy" after authorizing my GitHub repository, and I am able to proceed with the Amplify hosting workflow. I have not used Amplify before so I'm not sure what is supposed to happen next - I assume a new Amplify app will be created.

### Reproduction steps

1. Follow the steps in the Amplify user-guide for connecting a Github repository: https://docs.aws.amazon.com/amplify/latest/userguide/setting-up-GitHub-access.html#setting-up-github-app
2. Receive "There was an issue setting up your repository." after clicking "Save & Deploy" on step 14

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriii** [comment]
Hi @JackLot 👋🏽 thanks for raising this issue. There should be a webhook that gets created for your repository when you try to deploy the application. Can you confirm if that webhook was created when you tried to deploy?

To find the webhook:
1. Navigate to your repository in GitHub
2. Click **Settings*
3. Select **Webhooks**

**Comment by JackLot** [comment]
Thank you so much for the quick reply. When I navigate to the repo's settings, I see no webhooks:

<img width="639" alt="Screenshot 2023-04-19 at 2 45 10 PM" src="https://user-images.githubusercontent.com/1841253/233170884-0946f5ff-4f35-4564-a72e-102f4bb8dce4.png">

**Comment by hloriii** [comment]
@JackLot okay thanks for the verification. I have a few more follow up questions.

1. Can you provide a screenshot of the build settings that are generated?
2. What framework is your application using?

**Comment by JackLot** [comment]
Sure.

1) Screenshot of the build settings (I left everything default)

<img width="774" alt="Screenshot 2023-04-19 at 3 58 46 PM" src="https://user-images.githubusercontent.com/1841253/233186397-d3a2b790-7326-46a3-835b-2c631bfbf288.png">

Advanced settings
<img width="774" alt="Screenshot 2023-04-19 at 3 59 06 PM" src="https://user-images.githubusercontent.com/1841253/233186424-abb304b8-02ae-4d77-8bf9-8afb70e828c7.png">

Final review page before clicking "Save and deploy"
<img width="814" alt="Screenshot 2023-04-19 at 4 00 00 PM" src="https://user-images.githubusercontent.com/1841253/233186657-07122e61-270a-4f07-bea4-597a63a74c05.png">


2. The framework is Gatsby

**Comment by hloriii** [comment]
@ThePatrickDavis In order to further troubleshoot your issue, please reach out to the AWS Support team: https://aws.amazon.com/support for additional assistance. They will be able to assist you in getting your first Amplify app deployed. 

Thank you!

**Comment by JackLot** [comment]
@hloriii I believe this issue was closed by accident. In your previous comment the person you @ mentioned is not me.
