### ISSUE TITLE
Couldn't host a react app on AWS Amplify

### ISSUE THREAD

**Issue by TASLIM-ENIOLLA** [aws-amplify/amplify-hosting#3446]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

52dd2813cc59e2181df2

### AWS Region

us-east-1

### Amplify Hosting feature

Build settings

### Describe the bug

Anytime I try to host a react app recently, I would get this error: "Houston, there's a problem
We are unable to process your request. Please reach out to your support representative."

### Expected behavior

I shouldn't get an error. I've used amplify to host a react application and it worked just fine

### Reproduction steps

Go to AWS amplify
Click "New App" and click "Host Web App"
Check Github and click continue
Select therapist-dashboard from the repository list and choose any branch and click next
Click next and save and deploy

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriii** [comment]
Hi @TASLIM-ENIOLLA 👋🏽 thanks for raising this issue. Do you have any applications currently hosted with Amplify or is this the first application you're trying to host? It would be helpful if you could provide us an app ID from an app that's already hosted (if you have any) or if you could provide us an account ID that would be helpful as well. 

You can send that information to aws-amplify-customer@amazon.com if you'd like to send that privately.
