### ISSUE TITLE
Deployment issue. stuck at build, no error indication.

### ISSUE THREAD

**Issue by EmpChirag** [aws-amplify/amplify-hosting#3448]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dqvrcxarye2ri

### AWS Region

us-east-1

### Amplify Hosting feature

Git providers

### Question

Hello, My app was working fine but since few days when I merge new branch it stuck at in build step while deploying, it is not giving any error. I don't know what to do now, I have checked all possibilities.

**Comment by ignoxx** [comment]
have the same issue and in my case it gets stuck once i start downloading a ~150mb file using curl

**Comment by hloriii** [comment]
Hi @EmpChirag 👋🏽 thanks for raising this issue. It looks like you have since deleted your app so we cannot investigate further on our side what could have been the cause for the build failure. Do you have any screenshots of the build logs from when you experienced this issue?

**Comment by hloriii** [comment]
Hi @ignoxx 👋🏽 can you please provide your app ID so we can investigate this further?

**Comment by EmpChirag** [comment]
thanks for your response, unfortunately my app is deleted by developer. I will get back to you once new app is created.
