### ISSUE TITLE
migration banner disappeared after cancelling

### ISSUE THREAD

**Issue by heejin617** [aws-amplify/amplify-hosting#3452]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

https://ap-northeast-2.console.aws.amazon.com/amplify/home?region=ap-northeast-2#/db4hy11ovq43d

### AWS Region

ap-northeast-2

### Amplify Hosting feature

Frontend builds

### Describe the bug

I was intended to migrate the beta branch of our app from Next11 to Next12. However, I noticed that the migration task has been started over all branches including master branch, so I canceled the task that was going on in the master branch.

The problem is, even though I cancelled the migration, the banner section shows nothing and it seems there's no ways to see a 'migrate' button again. Moreover, when I retry to re-build the beta branch, the build terminal shows an error like this because the migration task has been not completed:
```
 !! CustomerError: Please update your Next.js version to 12 or newer and re-run your build to migrate to Amplify Hosting Compute. Learn More: https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-
```
My question is:
Is there any way to re-run the migration process on amplify console?
Is it possible to selectively migrate the branch on the console?

### Expected behavior

App should be migrated to Next12 from Next11 and deployed.

### Reproduction steps

1. Press the migration button in the banner 
2. Cancel the migration process
3. Go back to app page and there would be loading banner but doesn't shows anything

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by nadetastic** [comment]
Hi @heejin617 thank you for opening this issue. I'm currently investigating this and I'll follow up soon.

**Comment by heejin617** [comment]
Hi, It turned out the beta branch was pointing the older commit that includes next11 version in package.json and that's why the build script showed the version error. And found that the migration process was already completed when canceling the build.
