### ISSUE TITLE
Container-Based deploy with .ENV vars

### ISSUE THREAD

**Issue by gzimbron** [aws-amplify/amplify-hosting#3455]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Question

Hello, I'm trying to deploy a "Container-based" app, but my .npmrc file uses an ENV var to install dependencies.

Can someone explain to me please where to configure this option?

Thank you 

here is my Dockerfile

```Dockerfile

FROM public.ecr.aws/docker/library/node:18-alpine AS build

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

FROM public.ecr.aws/docker/library/node:18-alpine AS deploy

WORKDIR /app

RUN rm -rf ./*

COPY --from=build /app/package.json .

COPY --from=build /app/build .

RUN npm install --production

EXPOSE 3000

CMD ["node", "index.js"]

```

**Comment by SamKomesarook** [comment]
@gzimbron You can [create environment vars](https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html), and reference them in the buildfile.

**Comment by gzimbron** [comment]
Thank you @SamKomesarook .

I'm facing with other trouble.

My sveltekit app have /src folder where Amplify add all aws-exports.ts graphql files and Dockerfile , etc..

But I need to dockerize app in parent directory (../) is there a way to set Dockerfile and .dockerignore in root and all other amplify files in /src path?
