### ISSUE TITLE
Getting a SyntaxError: Unexpected token 'v', "version ht"... is not valid JSON on github connection

### ISSUE THREAD

**Issue by gabrielAHN** [aws-amplify/amplify-hosting#3456]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

New_app

### AWS Region

us-east-1

### Amplify Hosting feature

Git providers

### Describe the bug

When connecting github I am getting this error
<img width="1270" alt="Screenshot 2023-05-03 at 11 36 45 PM" src="https://user-images.githubusercontent.com/35410279/236107421-afc73e2b-2ac2-4e02-9a38-3d0dabaa710a.png">

Checking github all is authorized as seen below:
<img width="702" alt="Screenshot 2023-05-03 at 11 37 33 PM" src="https://user-images.githubusercontent.com/35410279/236107504-afd40dcc-c6f4-4f52-81f8-5c998d3f087b.png">

Have uninstalled and reinstalled the above application not sure what else

### Expected behavior

To be able to connect to github repo

### Reproduction steps

1. start new amplify application
2. Try to connect github to branches, and getting error

### Build Settings

```yaml
there is none
```

### Log output

<details>

```
There was an error detecting your build settings.
SyntaxError: Unexpected token 'v', "version ht"... is not valid JSON

```

</details>

**Comment by SamKomesarook** [comment]
@gabrielAHN how are you going to build & deploy without any build settings? They're probably required by amplify..

**Comment by gabrielAHN** [comment]
> @gabrielAHN how are you going to build & deploy without any build settings? They're probably required by amplify..

Yes but doesn’t amplify create a build setting if it doesn’t detect it? Also, had one in my repo with the same effect sadly

**Comment by hloriii** [comment]
Hi @gabrielAHN 👋🏽 can you confirm if you have any errors in your `package.json file`? I was not able to return the same exact error that you're seeing but I added some non-JSON text to `package.json` and returned a similar error `There was an error detecting your build settings.` when trying to select that repository. 

If you could provide us a repo that reproduces the same error, that would help us determine the issue.

**Comment by gabrielAHN** [comment]
Hey @hloriii 👋 

Just sent an invite to the repo ghn let us know if you were able to get access and are able to replicate the behavior?

**Comment by gabrielAHN** [comment]
Hey found it is related to the package.json being in the directory, which is confusing since package.json is needed. How would I fix this?
<img width="189" alt="Screenshot 2023-05-10 at 8 44 12 PM" src="https://github.com/aws-amplify/amplify-hosting/assets/35410279/bdf5cd72-ed24-4e34-94d8-8563d4327db5">

When I remove package json it stops working

**Comment by hloriii** [comment]
Hi @gabrielAHN thanks for providing the additional information. I'll take a look at the package.json and try to pinpoint the issue. Will update shortly.
