### ISSUE TITLE
Custom Domain Hosting Issue

### ISSUE THREAD

**Issue by shutupfaezan** [aws-amplify/amplify-hosting#3459]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d20pac6vlfjqwd

### Region

ap-south-1:430596722621

### Step

Custom Domain TrobleShoot

### Status

Active but not viewable

### Issue or question

I Wanted to host my react app on amplify so I created an amplify app which worked perfectly and I have Godaddy as my DNS provider so I finished all the SSL configuration which included adding a CNAME to the cloudnet url then adding the CNAME AWS provides with the respective name subdomain and value. After finishing this about an hour later my site show's active but when I click on the link to my site it shows connection not secure so I created an SSL certificate for it from AWS certificate management still in vain.  I tried my URL on whtatsmydns.com and it shows configuration active but on the site it shows connection not secure.

### Error message

Connection not secure.

**Comment by hloriii** [comment]
Hi @shutupfaezan 👋🏽 when adding a custom domain for your Amplify application, we issue an SSL certificate that is generated by AWS Certificate Manager. You have to create a CNAME record that points to the ACM validation server.

We outline how to do this in step 6 of our user guide: [Add a custom domain managed by GoDaddy](https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-godaddy.html). 

Did you follow these steps to setup your custom domain?

**Comment by shutupfaezan** [comment]
I'll check it out. Thanks !!!
