### ISSUE TITLE
Not able to run a amplify website when included .png and js in the zip file

### ISSUE THREAD

**Issue by Nack2544** [aws-amplify/amplify-hosting#3463]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-east-1

### Step

Domain activation

### Status

Failed

### Issue or question

Hello everyone, I have an issue uploading a zip file that contains HTML, png, js files in it. when I single upload the index.html file, the website is worked but because we include the image background and the character image from the png into the zip file, we keep getting the ""This amplifyapp.com page can’t be found, HTTP ERROR 404"" 

### Error message

"This amplifyapp.com page can’t be found, HTTP ERROR 404"

**Comment by hloriii** [comment]
Hi @Nack2544 👋🏽 apologies for the delay in response here. How are you zipping your files? Are you navigating inside the folder and zipping all of the contents?

Also, when you serve your application locally, are the images accessible in the application?

**Comment by hloriii** [comment]
If you can provide an app ID, that will also help us to investigate this issue.
