### ISSUE TITLE
Nextjs ^13.4.0 500 errors

### ISSUE THREAD

**Issue by frattaro** [aws-amplify/amplify-hosting#3466]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3vbomo5vhow60

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Describe the bug

Updating the nextjs dependency from 13.3.4 to 13.4.0 or 13.4.1 results in 500 error responses

### Expected behavior

I'd expect amplify-hosted sites to function like it does with 13.3.4

### Reproduction steps

1. bump dependency
2. wait for deployment
3. see internal server errors

### Log output

<details>

```
# Put your logs below this line
  | 2023-05-06T09:45:35.938-04:00 | TypeError: handler is not a function
  | 2023-05-06T09:45:35.938-04:00 | at Server.<anonymous> (/tmp/app/server.js:29:11)
  | 2023-05-06T09:45:35.938-04:00 | at Server.emit (node:events:513:28)
  | 2023-05-06T09:45:35.938-04:00 | at parserOnIncoming (node:_http_server:998:12)
  | 2023-05-06T09:45:35.938-04:00 | at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
```

</details>

### Additional information

I see it failing for all 6 apps. Runs fine locally and in github actions.

**Comment by iluvmemes** [comment]
I also am experiencing this with app id: `d1ufjo04olhaov`  This is a first deployment of a fresh Nextjs 13.4.1 app.

**Comment by cuadrarcf** [comment]
I'm having the same problem too. With a fresh installation using Nextjs 13.4.1 and got error 500 from server. In the logs I found "TypeError: handler is not a function" Any idea ?

**Comment by CarlosVF22** [comment]
I'm having the same problem too. With a fresh installation using Nextjs 13.4.1 and got error 500 from server.

**Comment by shawnseaton** [comment]
I am having the same error whether I use the pages router (supported by AWS Amplify) or App router (not supposed to be supported at this time by AWS Amplify) - TypeError: handler is not a function

2023-05-07T17:22:15.936-07:00	START RequestId: 81f2ee95-f6a5-404a-a48e-f09629d615bd Version: $LATEST

2023-05-07T17:22:15.937-07:00	[x-amplify-log][WARN] Skipping duplicate span name=RuntimeTotal

2023-05-07T17:22:15.937-07:00	[x-amplify-log][INFO] TRACING RequestId: 81f2ee95-f6a5-404a-a48e-f09629d615bd TraceId: Root=1-645840b7-70ab5d08110208c8005ad833

2023-05-07T17:22:15.937-07:00	[x-amplify-log][INFO] handling request host=127.0.0.1 port=3000 path_and_query=/ headers=x-forwarded-for: 174.72.31.68, 64.252.71.210, x-forwarded-proto: https, x-forwarded-port: 443, host: main.d3ugeayt2y6c7h.amplifyapp.com, x-amzn-trace-id: Root=1-645840b7-70ab5d08110208c8005ad833, user-agent: Amazon CloudFront, x-amz-cf-id: vHOkZ7XXtrKsT-CCBXyZFmsIa7kYfokuQ9hGGbiT6dhdyXKnvBXrdA==, accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7, via: redacted (64), accept-encoding: gzip, sec-ch-ua: redacted (66), sec-ch-ua-mobile: redacted (2), sec-ch-ua-platform: redacted (7), upgrade-insecure-requests: redacted (1), sec-fetch-site: redacted (10), sec-fetch-mode: redacted (8), sec-fetch-user: redacted (2), sec-fetch-dest: redacted (8), cloudfront-viewer-country: US

2023-05-07T17:22:15.996-07:00	TypeError: handler is not a function

2023-05-07T17:22:15.996-07:00	at Server.<anonymous> (/tmp/app/server.js:29:11)

2023-05-07T17:22:15.996-07:00	at Server.emit (node:events:513:28)

2023-05-07T17:22:15.996-07:00	at parserOnIncoming (node:_http_server:998:12)

2023-05-07T17:22:15.996-07:00	at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)

2023-05-07T17:22:16.000-07:00	[x-amplify-log][INFO] app response status_code=500 Internal Server Error headers=date: Mon, 08 May 2023 00:22:15 GMT, connection: keep-alive, keep-alive: redacted (9), content-length: 21, x-amplify-internal-request-id: 81f2ee95-f6a5-404a-a48e-f09629d615bd, x-amplify-internal-metrics: CustomerServerReadinessCheck;dur=177, RuntimeTotal;dur=258, RuntimeInitialization;dur=191, CustomerServerCall;dur=62

2023-05-07T17:22:16.016-07:00	REPORT RequestId: 81f2ee95-f6a5-404a-a48e-f09629d615bd Duration: 80.30 ms Billed Duration: 81 ms Memory Size: 1024 MB Max Memory Used: 74 MB In

**Comment by sozdayka** [comment]
If you download the build, you can notice that the launch should be from the folder app. 

<img width="1381" alt="Screenshot 2023-05-08 at 09 04 16" src="https://user-images.githubusercontent.com/12620773/236746275-fc0f5ff0-6291-4f1c-a02f-a384ab0e6161.png">

And folder app missing in server

<img width="1205" alt="Screenshot 2023-05-08 at 09 03 25" src="https://user-images.githubusercontent.com/12620773/236746127-4ed79b0f-28ca-41c9-adb6-c44b9f0bfa6d.png">

Perhaps the problem is in the new version of the Next or need additional configuration

**Comment by espenbye** [comment]
Got the same issue. Tried downgrading the Next.js packages, but it will still not work.

**Comment by abepuentes** [comment]
I downgrading next because I was thinking this was related to next@13.4.1. So I went back to next@13.3.5 which was working before and I got the same results as @espenbye has already pointed out, internal error is present on next versions that were working just fine a couple of days ago.

**Comment by cuadrarcf** [comment]
Downgrading  the version to "next": "13.2.4" works for me.

**Comment by Lezzio** [comment]
What's your package manager ? Using pnpm with symlinks broke our apps. We're now using another mode to avoid symlinks as a hot fix

**Comment by espenbye** [comment]
Tried downgrading to `13.2.4 `without luck - same issue. It was working on `13.3.4` before. Using NPM.

**Comment by frattaro** [comment]
off topic:

IMO 13.2.4 was the last solid nextjs release, been buggy since then (talking about core nextjs, not including beta stuff like fonts, app dir, metadata, swc). I assume it's because of the edge stuff they're pushing.

**Comment by hloriii** [comment]
Hi folks, thanks for opening/engaging on this issue. We are currently working on root causing this behavior and determining next steps.  

If you haven't already done so, please provide your App IDs so that we can investigate further. We will update this issue shortly. Thank you!

**Comment by espenbye** [comment]
> Hi folks, thanks for opening/engaging on this issue. We are currently working on root causing this behavior and determining next steps.
> 
> If you haven't already done so, please provide your App IDs so that we can investigate further. We will update this issue shortly. Thank you!

🙌🏼

AppId: d3pgmzdoktuvon
Region: eu-north-1
Environment: develop

**Comment by claptimes5** [comment]
> Hi folks, thanks for opening/engaging on this issue. We are currently working on root causing this behavior and determining next steps.
> 
> If you haven't already done so, please provide your App IDs so that we can investigate further. We will update this issue shortly. Thank you!

drk0c55ymjt56

Thanks!

**Comment by hloriii** [comment]
This issue is reproducible with Next.js versions 13.4.0 and 13.4.1. The latest release of Next.js where this issue does not occur is *13.3.4*. If you haven't tried already, please downgrade to 13.3.4 or an early version of Next.js as a workaround.

**Comment by hloriii** [comment]
@abepuentes I see you tried to downgrade to 13.3.5, can you try version 13.3.4 instead?

**Comment by hloriii** [comment]
@espenbye you can try another method of downgrading. Please follow these steps to add a package version override to your Amplify application: https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup-live-updates

Be sure to select `Next.js version` and set it to `13.3.4` or earlier.

**Comment by espenbye** [comment]
> @espenbye you can try another method of downgrading. Please follow these steps to add a package version override to your Amplify application: https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup-live-updates
> 
> Be sure to select `Next.js version` and set it to `13.3.4` or earlier.

Thanks! Will try that.

Also, I just downloaded the artifacts from the last build (where my package.json has next set to 13.2.4) and had a look at node_modules/next - package.json there still says 13.4.1 👀 Seems to be cached somewhere - is there a way to invalidate it?

**Comment by hloriii** [comment]
@espenbye I see. Try removing that path from your build settings:

```
  cache:
    paths:
      - node_modules/**/* <---- remove this line
```

**Comment by espenbye** [comment]
Can confirm downgrading worked. 👍🏻 With `npm i next@v13.2.3` instead of setting the version directly in package.json and then running npm install.

**Comment by shivpratik** [comment]
My last build with 13.3 worked perfectly fine. Now wth 13.4.1 it stopped working.

App ID: d3q4rozm6753hp
Region: us-east-2

By when will this issue be fixed?

**Comment by pldhiman** [comment]
Same Issue, I have tried with 13.2.3, 13.2.4, 13.3.4 and 14.x.x

App id : d3m86055xwbko8  // reproduced Internal Server Error continuously.
 
App ID : d3g1kvlu663ue6 // randomly occuring

This issue mainly occurs when deploying a new build. working perfectly fine on older deployed projects.

**Comment by abepuentes** [comment]
> @abepuentes I see you tried to downgrade to 13.3.5, can you try version 13.3.4 instead?

@hloriii thanks for the info, 13.3.4 its working fine with some minor issues. About 13.4.1, could be this related? https://github.com/vercel/next.js/issues/49536

**Comment by ferdingler** [comment]
Hi, this issue is indeed related https://github.com/vercel/next.js/issues/49536 . Looks like a regression was introduced on Next.js v13.4.0 on this commit: https://github.com/vercel/next.js/commit/83b774eeb69f1fe4f636260f83ed98c6d0717a3d. We have submitted a PR with a recommended fix: https://github.com/vercel/next.js/pull/49548.

**Comment by abepuentes** [comment]
@ferdingler thanks for your comment and PR, let's hope some of the owners at next like @ shuding could have some time to review it soon. Also seems like this #49338

**Comment by frattaro** [comment]
https://github.com/vercel/next.js/pull/49548 is approved so it should likely come out in 13.4.2 (or 13.5.0, whatever it ends up being)

**Comment by abepuentes** [comment]
Hi everyone, next 13.4.2 canary 6 has the fix of this, thanks again to @ferdingler for his PR.

**Comment by frattaro** [comment]
works! big thanks to the Amplify team, very impressive response

**Comment by michrome** [comment]
Next.js 13.4.2 is now released and fixes this isssue. Thank you @ferdingler !
