### ISSUE TITLE
Jekyll build broken

### ISSUE THREAD

**Issue by tuananhle7** [aws-amplify/amplify-hosting#3473]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d4d1r1668d2gf

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments, Frontend builds

### Describe the bug

My recent Jekyll build on AWS Amplify mysteriously fails with

```
sass-embedded-1.62.1-x86_64-linux-musl requires rubygems version >= 3.3.22,
                                    which is incompatible with the current version, 3.1.6
```

This didn't happen before and I don't know how to get this build to work.

This is the full build log: https://gist.github.com/tuananhle7/e00d20b4062e10bc2573280f053356ce

For reference, here is a build log for the last successful build: https://gist.github.com/tuananhle7/bef7bbd28b90c156689fc46a07d28b00

Please help.

### Expected behavior

Described above.

### Reproduction steps

Described above.

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by nadetastic** [comment]
Hi @tuananhle7 I'm currently working to reproduce this issue and will follow up as soon as I have some information. Thanks!

**Comment by nadetastic** [comment]
@tuananhle7 I was able to reproduce this error using the following [sample project](https://github.com/nadetastic/hosting-jekyll) (which is the default from `jekyll new`.

However I resolved by changing my build settings and overriding bundler package and setting it to latest.

![BuildSettings](https://github.com/aws-amplify/amplify-hosting/assets/87148442/26886c7e-0af6-41a3-8a93-5e77151b6192)

Could you give this a try and let me know if it works?

**Comment by tuananhle7** [comment]
It works now, thanks!
