### ISSUE TITLE
Redirect/Rewrite rules are not applying to new Custom domains

### ISSUE THREAD

**Issue by Veskump** [aws-amplify/amplify-hosting#3477]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1e0i5bjsy4bbs

### AWS Region

eu-central-1

### Amplify Hosting feature

Redirects

### Describe the bug

Our Amplify app is configured with the following rewrites:
```
[
    {
        "source": "/s/<*>",
        "target": someTargetUrl,
        "status": "200",
        "condition": null
    },
    {
        "source": "/<*>",
        "target": someOtherTargetUrl,
        "status": "200",
        "condition": null
    }
]
```

These rewrites work correctly for the default domain and any of the older Custom Domains we have made previously. However, the `"/s/<*>"` rewrite does not work on any new Custom Domains we create. So any new Custom Domain we create simply always shows the `someOtherTargetUrl` page even in cases where it should show `someTargetUrl` page .

### Expected behavior

The newly created Custom Domains should rewrite/redirect in the same way as all of the old Custom Domains.

### Reproduction steps

1. Setup rewrite rules as described
2. Create a new Custom Domain

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by nadetastic** [comment]
@Veskump I was able to reproduce this by having the order of my redirects set a certain way.

This will produce the error you are facing
| Route        | order           | 
| ------------- |:-------------:|
| /s/<*>      | first |
| /<*> | second | 

In order to resolve rearrange the order and place `/*` before `/s/<*>` like so:
| Route        | order           | 
| ------------- |:-------------:|
| /<*>      | first |
| /s/<*> | second | 


Can you confirm this and let me know if this works?

**Comment by Veskump** [comment]
@nadetastic 

I just tested your suggestion and it does appear to "fix" the issue for the newly created Custom Domains. However, that change causes all of the old Custom Domains to break so it is not a usable solution.

According to the documentation https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html my original order is the correct one:
> Redirects are executed from the top of the list down.

So it appears that for some reason newly created custom domains apply the redirects in reversed order. This is most definitely a bug.

**Comment by Veskump** [comment]
@nadetastic It looks like this issue has now been fixed. The rewrites are now working as expected for all of our custom domains without needing to make any changes in our end.
