### ISSUE TITLE
CRA build issue

### ISSUE THREAD

**Issue by kinitkit** [aws-amplify/amplify-hosting#3481]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2pjia7yruoojd

### AWS Region

us-west-2

### Amplify Hosting feature

Frontend builds

### Question

We are currently experiencing an issue related to building our Create-React-App (CRA) projects.

We have two applications with the same branch configurations and environmental variables. The applications are ostensibly identical, yet we are encountering a problem where one application builds successfully while the other consistently fails.

We would appreciate your prompt assistance in resolving this matter as it is affecting our development and deployment process. Please let us know if you need any additional information to assist with troubleshooting.

Thank you in advance for your support and assistance.

![image](https://github.com/aws-amplify/amplify-hosting/assets/23753030/28c79ec7-4955-4a64-ba21-01a08273e93d)

**Comment by hloriii** [comment]
Hi @kinitkit 👋🏽 thanks for raising this question. I see you have this set in your build script:

`export NODE_OPTIONS=--max-old-space-size=8192`

This will not work because `8192` exceeds the 7GB memory that the host contains so it will will be ignored. Instead, try setting this:

`export NODE_OPTIONS=--max-old-space-size=5632`

Please let me know if this solves the issue for you.

**Comment by kinitkit** [comment]
Hi @hloriii!

I updated it to `5632` but still seeing the same error. Any other options that we can do?

**Comment by hloriii** [comment]
Hi @kinitkit thanks for trying that out. The current configuration for your app may require more RAM than Amplify currently offers: the build environment is an isolated host with 4 vCPU and 7GB memory. We plan to offer larger build environments in the near future however this is a hard limit for the service today.

We do apologize for this inconvenience. Please feel free to open a new issue if you have other questions regarding Amplify Hosting. Thank you!
