### ISSUE TITLE
Cannot add a second domain to Amplify app

### ISSUE THREAD

**Issue by SaltXCTech** [aws-amplify/amplify-hosting#3494]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:ca-central-1:959825878301:apps/dzstis8vbs287

### Region

ca-central-1

### Step

Domain Activation

### Status

Failed

### Issue or question

Cannot add a second domain to the Amplify app, and this is the error I'm getting:

SSL creationSSL configurationDomain activation
Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below.
Error message: [CNAMEAlreadyExistsException] The following CloudFront distributions or Amplify Apps are already using one or more of your domains: [Distribution: *******53DQC0B in AWS Account: ******878301, Distribution: *******53DQC0B in AWS Account: ******878301]. For distributions you own, please remove the domains from them first and then retry adding your domain. For Amplify apps you own, you may already have associated this domain to another Amplify App in another accountor region. You can also check our troubleshooting guide for more help: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html

**Comment by nadetastic** [comment]
Hi @SaltXCTech thank you for openning this issue. Looking at the error it seems that the domain you are attempting to add to your app is already associated with a different app. Can you verify that the domain doesn't already have an association with another application within the same account?

**Comment by SaltXCTech** [comment]
Hi Dan,

Thanks for replying!

I don't think it's associated with another app. It's a newly registered domain in Rout53 and only set up for this app.

Thanks,
Bill
________________________________

**Comment by nadetastic** [comment]
@SaltXCTech what is the domain that you are trying to add?
