### ISSUE TITLE
App does not show status 

### ISSUE THREAD

**Issue by truonglocbinh** [aws-amplify/amplify-hosting#3497]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dq4gdul9tuikh

### AWS Region

us-east-1

### Amplify Hosting feature

Notifications

### Question

I have three apps, but I confuse that why only two apps has show status `Success`, My QA app does not show ?
![Screen Shot 2023-05-26 at 06 37 14](https://github.com/aws-amplify/amplify-hosting/assets/8655190/95802088-b1b7-4ea5-ab63-e6e3e0b0ef36)

**Comment by nadetastic** [comment]
Hi @truonglocbinh thanks for opening this issue. A few questions - when you select the app to view it, what deployment status do you see? Also another way to double check this is to use the API action [GetApp](https://docs.aws.amazon.com/amplify/latest/APIReference/API_GetApp.html#API_GetApp) to see the status. Here is an example of how to do this with the AWS CLI

```bash
aws amplify get-app --app-id <app-id>
```
the response:
```json
{
    "app": {
        "appId": "<app-Id>",
        "appArn": "<app-arn>",
        ...
        "productionBranch": {
            "lastDeployTime": "<time-stamp>",
            "status": "SUCCEED",
            "branchName": "<branch-name>"
        },
        ...
    }
}
```

This can help determine if its the console that isn't pulling the status correctly.

**Comment by truonglocbinh** [comment]
@nadetastic I check and it return `productionBranch: null`
