### ISSUE TITLE
route 53 domain transferred to another aws account

### ISSUE THREAD

**Issue by lnepis** [aws-amplify/amplify-hosting#3502]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Step

domain activation

### Status

error

### Issue or question

I get this error, while setting up my route 53 domain in amplify.
"In order to verify domain ownership, configure the following CNAME record associated with your domain and verify that the CNAME record exists in your Domain Name Server (DNS) file."

this is the domain I am trying to activate. www.seapointe-rental4beach.com

### Error message

"In order to verify domain ownership, configure the following CNAME record associated with your domain and verify that the CNAME record exists in your Domain Name Server (DNS) file."

SSL creation is green, but the error comes at SSL configuration process...and the final is domain activation

### Additional information

this is the long string I m given under the error

xxxxxxxxxxxxxxx.seapointe-rental4beach.com. CNAME _yyyyyyyyyyyyyyy.dnzkjbsjxj.acm-validations.aws.

I created a record on the hosted domain with cname and copied the entire string displayed, but it gives an error.

I am stuck at

**Comment by hloriii** [comment]
Hi @lnepis 👋🏽 thanks for raising this issue.

If your DNS provider is Route53, then DNS verification should be done automatically without you having to manually create the CNAME record. I just tested this and was able to add my custom domain in just a few minutes.

Can you provide the Amplify app ID and also a screenshot of the record in Route53? Feel free to redact parts of the record as you've done in the issue.

**Comment by lnepis** [comment]
Thank you. Now I am getting this error.

something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below.
Error message: One or more of the CNAMEs you provided are already associated with a different resource.’



I deleted everything, created a new hosted zone for the AWS domain and updated the name servers.
It automatically created 5 records, 2 CNAME, SOA, NS and one A

What else needs to be done? I am still unable to connect. In the Amplify ‘Domain management’, I added the domain and one it tried to configure, it creates SSL, passes configuration, but then stops at domain activation with the above error.

AWS Support does not respond consistently, sometimes 24 sometimes48 hrs. I am kind of sick of this AWS complexities and bad support unless you  pay for the support. I am unable to productionalize my domain that I purchased 1 month ago.

**Comment by hloriii** [comment]
@lnepis Can you provide your app ID so we can look into this further?

**Comment by lnepis** [comment]
Hi - thanks. Here it is

dyuid38m2ttyo

**Comment by Jay2113** [comment]
@lnepis 👋 , I observed that the Amplify app `dyuid38m2ttyo` has been deleted. If the issue persists or resurfaces, I'll recommend reviewing the custom domain troubleshooting guide: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html.
