### ISSUE TITLE
Web previews in an app that uses another app's backend

### ISSUE THREAD

**Issue by ChandlerCodazen** [aws-amplify/amplify-hosting#3506]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dws8hqpcjmvk7 and dgrpkzzv2sl2z

### AWS Region

us-west-1

### Amplify Hosting feature

Web previews

### Question

I set this issue up as a usage question since I am unsure whether this is an actual bug or what I want to do is not supported.

I have two amplify apps. Only one of them has a backend, and the other exists purely to deploy a second front-end environment that uses the same backend. They both connect to the same repository since it is a monorepo. When I created the second app, I was able to specify the first app's backend environment to be used instead of a new one.

On the amplify app that has the backend, web previews work just fine, however, web previews can not be configured on the second one since the backend list is empty. Am I able to setup web previews to take advantage of the first app's backend, just like the frontend in the second app already is?

<img width="659" alt="image" src="https://github.com/aws-amplify/amplify-hosting/assets/119635539/c745bdc7-41f7-4d4f-8791-7d1bb96d5791">

**Comment by nadetastic** [comment]
Hi @ChandlerCodazen thank you for opening this issue. In regards to your question, you should be able to configure the web previews in app A to use a backend in app B, as long as the the main app in app A has be set to use the same backend.

Can you refresh the page/ go through the preview config steps again?

**Comment by ChandlerCodazen** [comment]
Hello @nadetastic! Thank you for the quick response. Refreshing the page and going through the steps yields an empty environment list like in the photo above. I have 2 frontends in both apps. 1 for production and 1 for staging. The prod ones are connected to the same prod backend, and the staging ones are connected to the same staging backend.

**Comment by nadetastic** [comment]
@ChandlerCodazen Thanks for confirming, i've tried to reproduce this with no luck as it works as expected for me. Here are the steps I took:

1. Two apps in the same region - app A has a backend, app B has no backend
2. Configure app B to use app A's backend
3. Enable previews in app B, and while going through the preview config, choose app A's backend
4. Create a PR for app B which generates a preview using app A's backend

**Comment by ChandlerCodazen** [comment]
@nadetastic Thank you for looking into it. Since those exact steps result in a blank dropdown in the preview config (for me anyways), what would my next steps be?
