### ISSUE TITLE
New App not visible in AWS console

### ISSUE THREAD

**Issue by hoseyneil** [aws-amplify/amplify-hosting#3507]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1umlzukw8wz8v

### AWS Region

us-east-1

### Amplify Hosting feature

Access control

### Describe the bug

Hi,

I created an app with hosting and multiple env backend and other people in my organization cannot see it.  

They have tried swapping to the correct region but this doesnt appear to be it.

Ive added them to the Amplify Studio in the settings and that works fine.

### Expected behavior

The other used in my orgaization can see the app I created.

### Reproduction steps

1. Open All Apps: https://us-east-1.console.aws.amazon.com/amplify/home?region=us-east-1#/
2.  The other use in my AWS account/org should see the app.

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriii** [comment]
Hi @hoseyneil 👋🏽 thanks for raising this issue. This sounds like there are permissions needed for other users to be able to see the Amplify app. Here are some next steps to consider:

1. Ensure the users have proper permissions. To get started quickly, Amplify has the [AdministratorAccess-Amplify](https://docs.aws.amazon.com/amplify/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-AdministratorAccess-Amplify) managed policy that will allow access to multiple services related to Amplify. Please keep in mind that you can provide more granular permissions if needed. 
2. When the above policy is used, users will be able to run commands via the Amplify CLI.  If users cannot run commands via the Amplify CLI then there is likely another permissions issue outside of Amplify.
3. Check to see if there are any Service Control Policies (SCPs) at the account level or AWS Organization level that could be blocking access for other users. 

Please let us know if these tips help resolve the issue for you.
