### ISSUE TITLE
Is it possibly to increase Cloudfront timeout parameter when using Amplify?

### ISSUE THREAD

**Issue by martysaid** [aws-amplify/amplify-hosting#3508]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2t6g5ffdrl1wb

### AWS Region

ap-southeast-2

### Amplify Hosting feature

Not Applicable

### Question

I have a NextJS app hosted on AWS Amplify. The application makes a call to a third party API. The responses from the third party API may take longer than 30 seconds. Accordingly, my API is getting 504 errors from Cloudfront. My understanding is that there might be Cloudfront settings to extend the timeout length. Is this correct? If so, how can these be configured?

Thanks for your help.

**Comment by hloriii** [comment]
closing as duplicate
