### ISSUE TITLE
https://aws.amazon.com/blogs/mobile/amplify-next-js-13/

### ISSUE THREAD

**Issue by ConsultantsCombined** [aws-amplify/amplify-hosting#3511]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

Next JS - ISR - Documentation Stating Falsehoods

### AWS Region

us-east-1

### Amplify Hosting feature

SSR

### Describe the bug

Quite simply, the documentation states here https://aws.amazon.com/blogs/mobile/amplify-next-js-13/ that ISR is available for AWS Amplify. I would like to know who decided it was legal to lie in documentation to get sales? 

I have dug through tons of issues closed by some individual that seems to provide no further details on why ISR doesn't work, they just keep deflecting and saying they will update the documentation but it has been 6+ months.

Can you please provide some accurate information about whether or not you can truly support features you state are available in this ecosystem. It's pretty sad Vercel uses AWS infrastructure, and this is where we end up with AWS Amplify.

### Expected behavior

Make ISR work as your documentation states or you may regret lying in your documentation.

### Reproduction steps

1. Setup nextjs app with amplify
2. Enable SSR
3. Setup ISR
4. Deploy
5. Lies

### Build Settings

```yaml
Irrelevant
```

### Log output

Irrelevant 

### Additional information

Irrelevant

**Comment by Jay2113** [comment]
Hi @ConsultantsCombined, thanks for reaching out to us regarding the support of Incremental Static Regeneration (ISR) for Next.js apps on Amplify Hosting.

We can confirm that we support the ISR feature for Next.js apps on Amplify Hosting with both the [Web Compute platform](https://aws.amazon.com/blogs/mobile/amplify-next-js-13/) as well as the legacy [Web_Dynamic platform](https://docs.aws.amazon.com/amplify/latest/userguide/ssr-nextjs11-support.html). 

Today, we do not support On-demand ISR with either of the platforms and our team is working extensively to prioritize this feature for our customers: https://github.com/aws-amplify/amplify-hosting/issues/3116

The lack of support for On-demand ISR has already been outlined in our official AWS documentation - https://docs.aws.amazon.com/amplify/latest/userguide/ssr-Amplify-support.html#supported-unsupported-features

We will be closing this issue in favor of the documentation. As a reminder, please be respectful when raising issues and follow [Amazon Open Source Code of Conduct](https://aws.github.io/code-of-conduct). We endeavor to provide the best customer experience in a respectful and welcoming environment. Thank you!
