### ISSUE TITLE
amplify not pulling gitHub updates, also banner on UI keeps loading

### ISSUE THREAD

**Issue by vijayendra-roy** [aws-amplify/amplify-hosting#3517]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dhjilswhbtpyw

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Describe the bug

amplify not pulling gitHub updates, also banner on UI keeps loading. it worked fine till 1 day ago. 

### Expected behavior

amplify should deploy updated code. the banner on UI should have guidance/instructions as usual.

### Reproduction steps

1. make a change in the code 2. commit/push to github, 3. amplify fails to deploy

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by foobarnes** [comment]
I'm experiencing the same. AppId: d263pg34gxs8oh

**Comment by vijayendra-roy** [comment]
i tried creating new app, connected to same gitHub. on initial deployment, it worked but when i updated code again, same issue.

**Comment by Jay2113** [comment]
Hi @vijayendra-roy @foobarnes , we are actively investigating into this to narrow down the root cause of the issue.

**Comment by richie42690** [comment]
Same here. I tried two commits and neither triggered a build.

**Comment by Jay2113** [comment]
A quick update on the root cause:

Amplify Hosting uses GitHub web-hooks to trigger your builds and the root cause of this issue seems related to this ongoing GitHub event: https://www.githubstatus.com/ .

**Comment by vijayendra-roy** [comment]
appreciate the quick deep dive. i see the GitHub incident is resolved. trying new build, likely working now, will confirm in a bit.

**Comment by Jay2113** [comment]
Thanks @vijayendra-roy!

@foobarnes @richie42690 Please retry triggering a new build as the GitHub incident is resolved.

**Comment by richie42690** [comment]
@Jay2113 The build queue automatically resolved/triggered for me. Thanks for keeping us updated!

**Comment by foobarnes** [comment]
All good! Thanks @Jay2113 and team for digging in and keeping us updateed.
