### ISSUE TITLE
app deployed successfully but not shown in repo

### ISSUE THREAD

**Issue by malawadd** [aws-amplify/amplify-hosting#3519]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3p7gaoq9nj5qh

### AWS Region

us-east-1

### Amplify Hosting feature

Build settings, Deployments

### Question

i'm building this app from this repo :  https://github.com/malawadd/chainlink-truflation/tree/main 

now my question is :  why doesnt it show the building status on my github you know the ✅ or ❌ ?

**Comment by Jay2113** [comment]
Hi @malawadd 👋 , thanks for reaching out to us!

I observed that your Amplify app `d3p7gaoq9nj5qh` has deployed successfully and the [website](https://main.d3p7gaoq9nj5qh.amplifyapp.com/) is also resolving just fine.

Can you please elaborate on the behavior that you are observing with the GitHub repository? It would be helpful if you could also provide screenshots. Thanks!
