### ISSUE TITLE
Update DNS records panel does not show CNAME/ANAME to configure in DNS

### ISSUE THREAD

**Issue by jurmous** [aws-amplify/amplify-hosting#3527]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d36lla5d0e4afd

### Step

Getting Domain DNS record

### Status

Not shown

### Issue or question

I tried to connect a custom subdomain. It did not show the verify DNS record but I could find it in the XHR communication. Than it validated. But now it does not show any records in View DNS records.

I tried it in multiple browsers.

Screenshot:

<img width="1149" alt="Screenshot 2023-06-13 at 16 41 40" src="https://github.com/aws-amplify/amplify-hosting/assets/6823511/83a6607b-cf67-4aba-9677-298a3bb28af8">

### Error message

Error is that no DNS records are showing up. The direct amplify link is working.

Don't know if it is relevant. The browser console shows a failure:

404 https://prod.us-east-1.appstate.amplifyapp.com/AppState?appId=d36lla5d0e4afd

{
    "message": "Requested app was not found"
}

**Comment by Jay2113** [comment]
Hi @jurmous 👋 , thanks for reaching out to us!

I was unable to reproduce this behavior on my end in the Amplify Console Domain Management page. Can you please try the following:
- Delete the custom domain and retry connecting it to your Amplify app `d36lla5d0e4afd`
- If the issue persists, can you try to run the `get-domain-association` CLI command to see if you are able to retrieve the DNS records using the AWS CLI:
```
aws amplify get-domain-association --app-id d36lla5d0e4afd --domain-name <VALUE>
```
- Lastly, if you are able to actively reproduce this issue can you capture and provide us a HAR file? This will help us better understand the API requests and their responses recorded by your browser. Steps to capture a HAR file are outlined [here](https://repost.aws/knowledge-center/support-case-browser-har-file).

**Comment by jurmous** [comment]
Deleting the custom domain and connecting it again worked. It now shows the DNS record. Thanks! (I tried this before but this time it worked)
