### ISSUE TITLE
Build failed for "Invalid next.config.js options detected (target)

### ISSUE THREAD

**Issue by multivoltage** [aws-amplify/amplify-hosting#3529]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2skhgz4a0rx0t

### AWS Region

eu-west-1

### Amplify Hosting feature

Frontend builds

### Describe the bug

Recently we updated our next app from 11 to 12. 
Now we cannot deploy since build fail (only in aws), because of a target option.

Target is not anymore supported by next 12. But build log say:
`
2023-06-14T08:52:53.131Z [ERROR]: Error: Command failed with exit code 1: node_modules/.bin/next build
                                  warn  - Invalid next.config.js options detected:
                                  - The root value has an unexpected property, target, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, future, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).
                                  See more info here: https://nextjs.org/docs/messages/invalid-next-config
`

We did not set any "target" options in next.config.js. 
We removed **AMPLIFY_NEXTJS_EXPERIMENTAL_TRACE = true** from env variables of amplify (we used that for next 11 before migration to web-compute.
I noticed that if we put again this variable build will be ok. 

### Expected behavior

Build is ok without target option and without AMPLIFY_NEXTJS_EXPERIMENTAL_TRACE

### Reproduction steps

- setup a next 11 app
- migrate to web-compute (in this transiction we had other issued related to cache)
- remove AMPLIFY_NEXTJS_EXPERIMENTAL_TRACE
- run a build

### Build Settings

```yaml
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - cat next.config.js
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line
2023-06-14T08:50:58.656Z [INFO]: Done in 73.68s.
2023-06-14T08:50:58.660Z [INFO]: Starting SSR Build...
2023-06-14T08:52:53.131Z [ERROR]: Error: Command failed with exit code 1: node_modules/.bin/next build
                                  warn  - Invalid next.config.js options detected:
                                  - The root value has an unexpected property, target, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, future, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).
                                  See more info here: https://nextjs.org/docs/messages/invalid-next-config
                                  warn  - The `target` config is deprecated and will be removed in a future version.
                                  See more info here https://nextjs.org/docs/messages/deprecated-target-config
                                  warn  - Compiled with warnings
                                  ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js
                                  Critical dependency: the request of a dependency is an expression
                                  Import trace for requested module:
                                  ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js

```

</details>

**Comment by hloriii** [comment]
Hi @multivoltage this error occurs when trying to build a Next 12 or 13 app using the `WEB_DYNAMIC` platform. It looks like your app is still using `WEB_DYNAMIC`. You should see a button in the console on the general settings page to migrate the app. Please let us know if that unblocks you.

**Comment by multivoltage** [comment]
@hloriii ,You are right. I didn't notice because I was sure I migrated (for the second time) my app. In fact I managed to deploy a version with next 12. So does that mean that it is possible to have next 12 with web-dynamic?

**Comment by hloriii** [comment]
Hi @multivoltage you are correct. Next.js versions 12 and later are only supported by the `WEB_COMPUTE` platform. `WEB_DYNAMIC` is the Classic version of support for Next.js apps that use versions 11 and earlier. 

Amplify apps cannot contain branches that use both versions of support so please ensure you migrate all branches to compute. For more information, please refer to our documentation: [Migrating a Next.js 11 SSR app to Amplify Hosting compute](https://docs.aws.amazon.com/amplify/latest/userguide/update-app-nextjs-version.html.).

Do you need any further assistance with this issue?

**Comment by multivoltage** [comment]
Tomorrow I will try :)

**Comment by multivoltage** [comment]
@hloriii 
Tried with vert BAD resulta.
I'm sure to clicked migrate, and wait a new build.
My site after deploy was down (maybe for redirect with cloudfront).
Now I have already "MIGRATE" button.

How can be possible?

**Comment by multivoltage** [comment]
After some other problems now I see a good behavior.
