### ISSUE TITLE
Quick Navigation on Chrome returns Metadata

### ISSUE THREAD

**Issue by SamKomesarook** [aws-amplify/amplify-hosting#3531]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d19oqxloeeub82

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments, Frontend builds, Performance mode, SSR

### Describe the bug

We have built and deployed a Next13 app with the performance mode enabled.

When quickly navigating with the back/forward buttons on chrome to an external site, then back to the Amplify site, strange metadata is shown in an html `pre` tag, a sample of which is below:

<img width="877" alt="Screenshot 2023-06-14 at 10 31 49" src="https://github.com/aws-amplify/amplify-hosting/assets/47465976/f398decc-4dfd-4269-a24a-8ea1329cb815">

### Expected behavior

The site should load like normal with the quick navigation.

### Reproduction steps

The site is unfortunately private, and we were unable to replicate with a test repo, however we can provide access to our site for testing.

The bug only appears on chrome, when navigating in and out of the site with the back/forth buttons quickly.

**Comment by hloriii** [comment]
Hi @SamKomesarook 👋🏽 I tried testing this but couldn't produce the behavior you're describing with using the back/forward buttons in chrome. Would you be able to provide an HAR capture or a screenshot of the request and response headers in the network tab so we can see more details about the request? 

Also, does this happen when navigating back to a specific page in your application or does this happen for any page?

**Comment by Olawande-samuel** [comment]
I am also experiencing a similar issue. In my case, the issue occurs when I navigate back from a Next.js 404 page and also when I leave the site unattended for a period of time (about 1-2 hours). I have attached a screenshot of my request and response headers
![oie_OEMp5makSttX](https://github.com/aws-amplify/amplify-hosting/assets/49659941/6197fdfb-1388-4d38-aadb-30d8af9cb503)

**Comment by SamKomesarook** [comment]
My request and response headers look very similar to the above. It could be a Next issue, however my local deployment works fine. @hloriii If there is some way to confidentially provide our internal testing URL, I am happy to do so.

**Comment by hloriii** [comment]
Hi @SamKomesarook That would be super helpful. Are you on Discord? We have a Discord server that allows folks to engage with the greater Amplify community. If you join the server, you can personally message me with those details. Here is an invite link: https://discord.gg/amplify and my username is Loriana#9619. 

Alternatively, you can also send an email to aws-amplify-customer@amazon.com. 

Either method works fine.

**Comment by SamKomesarook** [comment]
Will do, thank you!

**Comment by hloriii** [comment]
@Olawande-samuel thanks for providing the screenshot. Can you provide your app id as well please?

**Comment by SamKomesarook** [comment]
After upgrading to the most recent version of Next, I am unable to replicate...

**Comment by hloriii** [comment]
Hi @SamKomesarook 👋🏽 thanks for providing that update and also for responding to my email. 

I'm closing this as resolved since you're no longer able to produce the behavior. If this issue occurs for you again, feel free to open a new issue.
