### ISSUE TITLE
Issue with `Storage.put` command when deployed to Hosting

### ISSUE THREAD

**Issue by vgthoppae** [aws-amplify/amplify-hosting#3533]
### Amplify CLI Version

11.1.1

### Question

This may be something simple, the `Storage.put` command works fine from localhost, but breaks when the app is accessed from the custom domain set up on hosting, with the below error. Simply puzzling. Appreciate any pointers.

```
TypeError: (0 , sx.resolveHostHeaderConfig) is not a function
    at new t (_app-355c5eb0eb8aef58.js:13:240132)
    at sL (_app-355c5eb0eb8aef58.js:13:242758)
    at e._createNewS3Client (_app-355c5eb0eb8aef58.js:13:256028)
    at new e (_app-355c5eb0eb8aef58.js:13:251009)
    at e.put (_app-355c5eb0eb8aef58.js:13:272345)
    at e.put (_app-355c5eb0eb8aef58.js:13:280266)
    at O (_app-355c5eb0eb8aef58.js:35:387332)
```

This is an amplify provisioned storage with CORS policies.

**Comment by Jay2113** [comment]
Hi @vgthoppae 👋 , thanks for reaching out to us!

Can you please share the following information with us:
- Amplify app id
- Detailed steps using which we could reproduce the behavior on our end
- Next.js version of your app

**Comment by vgthoppae** [comment]
@Jay2113 Sorry for the delay in getting back.  The amplify app id is `d2u5j3f0zlsz1e` and the next js version is `13.1.1`. 

I have some superficial unverified theory that might be of help. The error seems to be from incompatible `@aws-amplify/client-s3` module. The Storage.put command calls `createS3Client` which refers to a missing `resolveHostHeaderConfig`.

The way to reproduce is to build a simple Next.js app, add amplify storage and provide an option on the UI to upload a file that calls `Storage.put` method.  Thanks for your time and attention.

**Comment by vgthoppae** [comment]
@Jay2113 I was able to fix this issue by adding `@aws-sdk/middleware-host-header` dependency.

**Comment by Jay2113** [comment]
@vgthoppae 👋 , glad to hear that you were able to fix this issue and thanks for sharing the resolution here as it can be helpful to other devs who are running into a similar error.
