### ISSUE TITLE
Amazon Linux 2023 build image

### ISSUE THREAD

**Issue by hoolby** [aws-amplify/amplify-hosting#3537]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

eu-west-1

### Amplify Hosting feature

Build settings

### Is your feature request related to a problem? Please describe:

Partially related to Node.js version limitations when using the default Amazon Linux:2 image, specifically the outdated GLIBC version.
[https://github.com/aws-amplify/amplify-hosting/issues/3109](https://github.com/aws-amplify/amplify-hosting/issues/3109)

### Describe how you'd like this feature to work

A build image option for Amazon Linux 2023.

This would allow users to use new and future releases of Node.js without having to use or create custom images, while benefiting from the AL2023 optimizations and security updates

**Comment by kachkaev** [comment]
Looks like it's available now (just not as a default): https://github.com/aws-amplify/amplify-hosting/issues/3773#issuecomment-1811288919

**Comment by CGarces** [comment]
For me AL2023 is useless, fails using python backends.
I was trying to bump my backend to 3.11 but also fails using 3.9

I haved rollback to Amazon linux 2.
Use `nvm use $VERSION_NODE_18` just works fine for me.

**Comment by Jay2113** [comment]
Amplify Hosting now uses the Amazon Linux 2023 build image by default for newly deployed applications. For more details, refer to this blog post: https://aws.amazon.com/blogs/mobile/amazon-linux-2023-hosting/.
