### ISSUE TITLE
App served as old cached version after updating compute engine

### ISSUE THREAD

**Issue by kolodi** [aws-amplify/amplify-hosting#3543]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3bbqgqvls6ewq

### AWS Region

eu-west-1

### Amplify Hosting feature

Deployments, Frontend builds

### Describe the bug

In order to migrate to newer version of NextJS I have updated compute engine in amplify console as suggested. After that I have had to redeploy my production branch (I did not want to do so but I was kind of forced by my users stared to point me some issues on the site and I had already new version of app tested locally and ready to deploy). So I deployed the new version of the app, first on the "prod" branch. The build and deploy logs are all good and it is successfully deployed. Entered deployed app URL and it was still showing an older version of the app. So I waited for an hour or so. Same thing. So I have deployed also on "qa" and "dev" branches, hoping that it can "unlock" cache. But it get even worse. Now I have an even older version (from like a year ago) shown on all hosting environments. 

### Expected behavior

I expect to see the latest deployed version of my app.

### Reproduction steps

1. Update compute engine
2. Deploy new NextJS v13 app
3. App is not updated when going to the hosting URL (with custom domail)

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line
End of frontend build:
                                 ├ chunks/framework-8a37bd1e87a81516.js   42.1 kB
                                 ├ chunks/main-2870f0c43f33b8ea.js        30.9 kB
                                 ├ chunks/pages/_app-f3d53b9b3b9eb72e.js  152 kB
                                 ├ chunks/webpack-5761f3a204ffdf4a.js     1.08 kB
                                 └ css/b26f2502eaab9cd6.css               30.6 kB
2023-06-19T20:55:35.158Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
2023-06-19T20:55:35.741Z [INFO]: # Completed phase: build
2023-06-19T20:55:35.774Z [INFO]: ## Build completed successfully
2023-06-19T20:55:35.775Z [INFO]: # Starting caching...
2023-06-19T20:55:35.786Z [INFO]: # Creating cache artifact...
2023-06-19T20:55:51.500Z [INFO]: # Created cache artifact
2023-06-19T20:55:51.574Z [INFO]: # Uploading cache artifact...
2023-06-19T20:55:59.055Z [INFO]: # Uploaded cache artifact
2023-06-19T20:55:59.184Z [INFO]: # Caching completed
2023-06-19T20:55:59.188Z [INFO]: Setting NEXT_PRIVATE_STANDALONE=true to produce .next/standalone directory
2023-06-19T20:55:59.191Z [INFO]: # No custom headers found.
2023-06-19T20:56:03.181Z [INFO]: # Starting environment caching...
2023-06-19T20:56:03.275Z [INFO]: # Uploading environment cache artifact...
2023-06-19T20:56:03.376Z [INFO]: # Uploaded environment cache artifact
2023-06-19T20:56:03.377Z [INFO]: # Environment caching completed
Terminating logging...

Deploy logs:
2023-06-19T20:56:07 [INFO]: Beginning deployment for application d3bbqgqvls6ewq, branch:main, buildId 0000000038
2023-06-19T20:56:21 [INFO]: Deployment complete


```

</details>

### Additional information

I've noticed that in the deploy phase there is no more s3 bucket name and cloud front id. It is not clear where the build artifacts are going and why cloud front distributions are pointing to some old s3 builds rather than to the latest (where?) build. Maybe it is different in new compute engine, but nevertheless I have my app completely useless now as the old frontend does not work well with the latest backend and my app in production used by my numerous clients is just unusable now.

**Comment by hloriii** [comment]
Hi @kolodi 👋🏽 thanks for raising this issue. 

With the classic support (for Next.js versions 11 and older) there are resources deployed in your account which you observed under the deploy tab. With compute support, Amplify fully manages those resources so they are no longer deployed in your account. That is why you cannot see any information for those resources in the deploy section after migrating.

It looks like there are still redirect rules that are pointing to older distributions from before you migrated to compute support. When requests are made to your app, the content is being served from an older distribution instead of the new distribution created during migration.

To ensure requests are being served by the newest distribution, please remove those redirect rules. Please let us know if this advice helps unblock you.

**Comment by kolodi** [comment]
You saved my day. Thank you. 

I think it merits to be written here:
https://docs.aws.amazon.com/amplify/latest/userguide/update-app-nextjs-version.html

**Comment by hloriii** [comment]
@kolodi Nice! Thank you for that feedback. Closing this issue as resolved.
