### ISSUE TITLE
Unable to use wildcard in rewrites and redirects routes

### ISSUE THREAD

**Issue by DataLoreB4** [aws-amplify/amplify-hosting#3546]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1svm68u3nyy54

### AWS Region

us-west-2

### Amplify Hosting feature

Redirects

### Frontend framework

React

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

Unable to use any wildcard in rules.

By following the examples on this article [https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html](https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html)

this "**/<*>**" expression sould work as a source address but I'm receiving this error in the console:
**Uncaught SyntaxError: Unexpected token '<' (at main.4d428541.js:1:1)**

In fact, can't make any regular expression work, always fails with the same error.

I tried just "/" and "*" and "/*" and "/*/" etc. and I do not receive any error but the rule doesn't work.

The only way to make it work is by filling in the exact match, for example, "/jobs/" --> this works as expected.

### Expected behavior

Wildcards should work and by using /<*> all the routes must be redirected as the article says:
_"You can use the following example code to redirect all traffic to index.html as a rewrite. In this scenario, the rewrite makes it appear to the user that they have arrived at the original address."_

Original address	Destination Address	Redirect Type	Country Code
/<*>                        /index.html                      rewrite (200)

### Reproduction steps

1. Go to Amplify console
2. Select a React application
3. Make sure the "Hosting environments" tab is selected
4. In the left side menu, click "Rewrites and redirects"
5. Add this rule: JSON [{"source": "/<*>", "status": "200", "target": "/index.html", "condition": null}]

### Log output

<details>

```
main.4d428541.js:1 Uncaught SyntaxError: Unexpected token '<' (at main.4d428541.js:1:1)

```

</details>

### Additional information

The real issue I want to fix is the 404 error when pressing F5, the URL is sent to the server, the server responses 404 and adds the "/" at the end of the browser's URL.  So, I want to do exactly what the article says: 

_"You can use the following example code to redirect all traffic to index.html as a rewrite. In this scenario, the rewrite makes it appear to the user that they have arrived at the original address."_

By filling in "/jobs/" as a source and "/index.html" as target with 200 (rewrite) the issue is gone.  

But of course I have to add 1 rule for each route.

BTW: I have added _redirects file to public folder with the line: 

_/*    /index.html   200_

and It's completly ignored, that's why I'm trying with the rewrites and redirects feature.

**Comment by Jay2113** [comment]
Hi @DataLoreB4 👋 , thanks for reaching out to us and apologies for the delayed response on the thread.

This particular behavior is caused since your app uses a `200 (Rewrite)` rule which basically rewrites all the requests even for static assets such as js, css, image files to `index.html`. This causes the root `index.html` for your app to return an empty/blank page since it was not able to retrieve these static asset files.

Thus, to resolve this behavior you will need to switch the rewrite type to either `404 (Rewrite)` or `404 (Redirect)`:
```
[
    {
        "source": "/<*>",
        "target": "/index.html",
        "status": "404-200",
        "condition": null
    }
]

OR

[
    {
        "source": "/<*>",
        "target": "/index.html",
        "status": "404",
        "condition": null
    }
]
```
This will allow you to point requests to nonexistent pages of your web app to its `index.html` page.

**Comment by DataLoreB4** [comment]
> Hi @DataLoreB4 👋 , thanks for reaching out to us and apologies for the delayed response on the thread.
> 
> This particular behavior is caused since your app uses a `200 (Rewrite)` rule which basically rewrites all the requests even for static assets such as js, css, image files to `index.html`. This causes the root `index.html` for your app to return an empty/blank page since it was not able to retrieve these static asset files.
> 
> Thus, to resolve this behavior you will need to switch the rewrite type to either `404 (Rewrite)` or `404 (Redirect)`:
> 
> ```
> [
>     {
>         "source": "/<*>",
>         "target": "/index.html",
>         "status": "404-200",
>         "condition": null
>     }
> ]
> 
> OR
> 
> [
>     {
>         "source": "/<*>",
>         "target": "/index.html",
>         "status": "404",
>         "condition": null
>     }
> ]
> ```
> 
> This will allow you to point requests to nonexistent pages of your web app to its `index.html` page.
