### ISSUE TITLE
Not getting past SSL configuration

### ISSUE THREAD

**Issue by MemeMaster2023** [aws-amplify/amplify-hosting#3547]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

Singapore

### Step

SSL configuration

### Status

Pending

### Issue or question

The https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-godaddy.html

I added the CNAME records (there is no ANAME in godaddy)

Step. 7 is not clear.

How to redirect in godaddy?
What domain to use?

### Additional information

<img width="1151" alt="Screenshot 2023-06-22 at 12 17 49" src="https://github.com/aws-amplify/amplify-hosting/assets/134248861/af2c1628-25ef-4823-8d33-6f0505e984bb">

**Comment by hloriii** [comment]
Hi @MemeMaster2023 step 7 is asking you to setup domain forwarding in GoDaddy if you want to update your root domain. You can also follow these steps from GoDaddy to complete step 7: https://www.godaddy.com/help/forward-my-godaddy-domain-12123

If you're still stuck on SSL configuration after adding the proper CNAME record, please provide your App ID so we can investigate further.
