### ISSUE TITLE
error in domain activation

### ISSUE THREAD

**Issue by divyesh-frodobots** [aws-amplify/amplify-hosting#3552]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

https://ap-southeast-1.console.aws.amazon.com/amplify/home?region=ap-southeast-1#/d3kxs1m4tn9svw

### Region

southeast-1.

### Step

domain activation

### Status

failed

### Issue or question

i am getting this error on the domain activation

`We had issues connecting your custom domain: xxx.xxx.com. Please visit the Domain Management page for more information.
`

### Error message

We had issues connecting your custom domain: xxx.xxx.com. Please visit the Domain Management page for more information.

### Additional information

i try two time but same issue 

![image](https://github.com/aws-amplify/amplify-hosting/assets/125444846/80a32912-b106-46ae-8e70-ee9b4f4cc4d8)

**Comment by nayan32biswas** [comment]
I was trying to reassign the same domain to another app. I got the same error in two scenarios. If the scenario matches, you could solve this issue.

1. In the DNS manager the targeted domain is already assigned with different values.
        Solution: Remove the value targeted name in the DNS manager.
3. When I request the same domain for two different apps (that are already running).
        Solution: Delete Custom-Domain on another app.
For both solutions, users may experience downtime.

**Comment by Jay2113** [comment]
Hi @divyesh-frodobots 👋 , thanks for reaching out to us!

The `AmplifyWaitTimeout` exception can occur if the DNS records (provided in the Amplify Console or fetched via AWS CLI) for your domain are not updated within the 3rd party DNS provider settings within 48 hours of connecting the custom domain to your Amplify app.

It is important that you perform this step soon after adding your custom domain in the Amplify console. The AWS Certificate Manager (ACM) immediately starts attempting to verify ownership. Over time, the checks become less frequent. If you add or update your CNAME records a few hours after you create your app, this can cause your app to get stuck in the pending verification state.

**Our recommendations:**
- If the domain activation process is stuck in the Amplify Console, you can either click the `Retry` button or delete the domain and then retry the process.
- Update the DNS records in the 3rd party DNS provider as soon as possible ideally within an hour.
