### ISSUE TITLE
Domain Activation Error : At least one of your domains has a CAA record that does not include Amazon as an approved Certificate Authority

### ISSUE THREAD

**Issue by indrajitsinh-rathod** [aws-amplify/amplify-hosting#3553]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dojms6svkj6ag

### Region

us-east-1

### Step

Domain activation

### Status

Failed

### Issue or question

I tried to add the dns configuration, following all the steps of the platform.

But I've got an error on Domain Activation step. I have retried multiple times but in vain.

![Screenshot 2023-06-26 105826](https://github.com/aws-amplify/amplify-hosting/assets/132458175/ee938050-160a-4bd5-8715-1bd25410e76d)

### Error message

![Screenshot 2023-06-26 105826](https://github.com/aws-amplify/amplify-hosting/assets/132458175/ee938050-160a-4bd5-8715-1bd25410e76d)
As shown in the screen it says that CAA record is misssing but I have addedd a CAA record and tried several times to reverify but it keeps on failing with the same error. You can check the CAA record propagation here
https://www.whatsmydns.net/dns-lookup/caa-records?query=coachbar.io&server=google

**Comment by indrajitsinh-rathod** [comment]
@hloriii can you please help me with this ?

**Comment by indrajitsinh-rathod** [comment]
I was able to solve this issue by allowing a  CAA record  to create a certificate for wildcard domain. I think this should be clearly mentioned in the amazon docs. I had to add a CAA record with issuewild as well to make this work. So folks if you are pointing to a subdomain keep in mind to add a CAA record for both issue and issuewild tags.

**Comment by Jay2113** [comment]
Hi @indrajitsinh-rathod 👋 , thanks for your continued patience and apologies for the inconvenience caused due to a lack of documentation on this issue/error.

We are working on updating our documentation for the same.
