### ISSUE TITLE
Is there any way to use IAM Role for auth in next.js api routes

### ISSUE THREAD

**Issue by juaoose** [aws-amplify/amplify-hosting#3557]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d14z3n2zfezi4a

### AWS Region

us-east-1

### Amplify Hosting feature

Not Applicable

### Question

I have a Next.js app deployed on Amplify and I'd like to connect to DynamoDB from one API Route.

Is it possible to use the credentials provided by the service account instead of having to manage a set of AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY (plus having to rename them since the AWS_ environment variables are reserved)?

I tried adding the DynamoDB admin policy to the service role but it does not seem to work.

**Comment by Jay2113** [comment]
@juaoose 👋 , thanks for reaching out. We are tracking this as a feature request here #3205. I'll recommend subscribing to it to track updates.
