### ISSUE TITLE
Houston, there's a problem.

### ISSUE THREAD

**Issue by sharathkannan04** [aws-amplify/amplify-hosting#3577]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Frontend framework

React

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

I not able to deploy my react app using Amplify,This is the error message that I get while trying to deploy the app.

"Houston, there's a problem,We are unable to process your request. Please reach out to your support representative."

### Expected behavior

To deploy and run the application using Amplify.

### Reproduction steps

Try to deploy any react app in my account.

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by davidkslack** [comment]
Similar issue all weekend. 

> Houston, there's a problem
> We are unable to process your request. Please reach out to your support representative.

I get the above error following the AWS tutorial (link below) and have no "support representative" that I know of.
https://aws.amazon.com/getting-started/hands-on/build-web-app-s3-lambda-api-gateway-dynamodb/module-one/?e=gs2020&p=build-a-web-app-intro

Tried with 2 regions (London and Oregon) with no success.
Can't find the logs for Amplify so I have no log either.

I've attached the index zipped in case that was the issue [index.zip](https://github.com/aws-amplify/amplify-hosting/files/11995874/index.zip)

Any help appreciated. 
Thanks

**Comment by davidkslack** [comment]
Created a new AWS account and was able to get this working.
Still have no way of seeing logs or errors and the "Houston, there's a problem" error tells us nothing :(

**Comment by Jay2113** [comment]
Hi @maverick101101 @davidkslack 👋 , thanks for reaching out to us.

Are you observing the `Houston, there's a problem,We are unable to process your request. Please reach out to your support representative.` exception when trying to create your first Amplify app? Or do you already have existing Amplify applications in your AWS account?

Additionally, can you please share your AWS Account ID (where you observing this exception) privately via a DM on our [community discord server](https://discord.gg/amplify). My username is `Jay Raval`.

**Comment by maverick101101** [comment]
@Jay2113 not my first amplify application i had deployed this application a week before and everything was working fine.

**Comment by Jay2113** [comment]
@maverick101101 thanks for sharing that information, can you also share your Amplify App ID?

**Comment by KrishnaSaiChaitanya** [comment]
@Jay2113 I am also getting the same problem can you help me I have sent the screenshot to your dm in Discord

**Comment by davidkslack** [comment]
@Jay2113 This is my first application using Amplify, I'm simply following the tutorial. However, my account has been around for a while, I'll send the details now on discord

**Comment by JunyounsKim** [comment]
It looks like I have same problem. Please share solution if reason is found out.

**Comment by maverick101101** [comment]
@Jay2113 I have deployed the app earlier and terminated the instance. and now i'm trying to deploy the same app again.
since this is during the initial deployment I don't have an APP ID.

**Comment by LakshithaCentronixx** [comment]
@Jay2113 Any update on this issue? I'm also facing the same. Its a react app that I'm trying to deploy for the first time

**Comment by Jay2113** [comment]
@davidkslack @sharathkannan04 Thanks for your continued patience.

In order to further troubleshoot your issue, please reach out to the AWS Support team: https://aws.amazon.com/support for additional assistance.

Thank you!
