### ISSUE TITLE
ERROR: Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html" 

### ISSUE THREAD

**Issue by jimenaCabrejas** [aws-amplify/amplify-hosting#3582]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3s0j7pt07cq91

### AWS Region

us-east-1

### Amplify Hosting feature

Build settings

### Question

Hi!

I have a React APP with Vite that I have deployed using the Amplify Hosting service (linking to my git repository). The app builds and deploys correctly.

But when I try to access the web I get the following error:

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
<img width="692" alt="image" src="https://github.com/aws-amplify/amplify-hosting/assets/25618971/e40afdd0-98a2-430f-a1ff-2181cc212d06">

Do I need to configure some extra settings on the Amplify Hosting console?

**Comment by Jay2113** [comment]
Hi @jimenaCabrejas 👋 , thanks for reaching out to us and apologies for the delayed response on this thread.

It seems that the Amplify app `d3s0j7pt07cq91` has been deleted. Are you still running into this issue? 

This particular error can occur if your app has an incorrect `base` public path set in the `vite.config.js` file: https://vitejs.dev/guide/build.html#public-base-path
