### ISSUE TITLE
504 Timeout error calling NextJS Api connected to Pinecone

### ISSUE THREAD

**Issue by techlab-capco** [aws-amplify/amplify-hosting#3583]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3iwy67ebz5xwx

### AWS Region

eu-north-1

### Amplify Hosting feature

Not Applicable

### Question

Hello there,

I've successfully deployed my NextJS app (deployed in north-EU), that has an internal API path called from the FE to the BE of the NextJS app.

The Api perform a call to an external vector Databse (Pinecone), but every time I call the API I received a 504 error from the app. I guess is something related to the time used from the app to reach the DB (hosted in US), and the Amplify just cut off the connection after a while (around 20sec avarege).

There is a way to set the time-out to 30 or 60 sec before cutting the connection and ends up with a 504 error?

Thanks.

**Comment by Jay2113** [comment]
Hi @techlab-capco 👋 , thanks for reaching out to us and apologies for the delayed response on this thread.

Unfortunately, increasing the timeout of the Lambda functions hosting SSR apps using the Compute platform is not supported at this time. Additionally, the timeout on these functions is set to 30 secs by default. That being said, we have an open feature request pertaining to this use case: https://github.com/aws-amplify/amplify-hosting/issues/3223

I am going to close this thread in favor of it to keep the communication in the same place as that will be the place to receive status updates on this feature. Thanks for your continued cooperation and understanding.
