### ISSUE TITLE
Houston, there's problem error while deploying first React App.

### ISSUE THREAD

**Issue by JunyounsKim** [aws-amplify/amplify-hosting#3585]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

ap-northeast-2

### Amplify Hosting feature

Deployments

### Frontend framework

React

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

During following React App deployment tutorial(https://aws.amazon.com/ko/getting-started/hands-on/build-react-app-amplify-graphql/), I encountered below error message when I clicked "Save and Deploy" button

"Houston, there's a problem.
We are unable to process your request. Please reach out to your support representative"

It was under "Deploy your app with AWS Amplify" step. I linked my Github repository and branch and accepted default build settings.

And in last Review page, when I clicked "Save and deploy" button above error pop up.

Could you help me with this?

Please let me know if you want some other information.

### Expected behavior

deployment successs

### Reproduction steps

following tutorial https://aws.amazon.com/ko/getting-started/hands-on/build-react-app-amplify-graphql

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Jay2113** [comment]
Hi @JunyounsKim 👋 , thanks for raising this with us.

Can you please share your AWS Account ID (where you observing this exception) privately via a DM on our [community discord server](https://discord.gg/amplify)? My username is `Jay Raval`.

**Comment by JunyounsKim** [comment]
@Jay2113 hi, I sent you my account id. Please check it.

**Comment by Jay2113** [comment]
@JunyounsKim 

In order to further troubleshoot your issue, please reach out to the AWS Support team: https://aws.amazon.com/support for additional assistance.

Thank you!
