### ISSUE TITLE
Subdomain configuration issue

### ISSUE THREAD

**Issue by yanislavtankov** [aws-amplify/amplify-hosting#3587]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dlim9jss3y8u2

### Region

eu-west-2

### Step

Subdomain activation

### Status

not working

### Issue or question

i have setup for subdomains by very same way as each of them is connected to different branches in code commit. Three subdomains are working perfect, but last one says "No access to this site"". I think the re is a bug with DNS. Can you help please?

### Error message

No access to this site

**Comment by yanislavtankov** [comment]
Can anyone help with this? Checked configuration several times and no difference in settings compare to other domains that work!!! What is going on?
![image](https://github.com/aws-amplify/amplify-hosting/assets/26672099/f1ff6d07-dace-4d9c-b75c-5fa0fa64acdf)

**Comment by Jay2113** [comment]
Hi @yanislavtankov 👋 , thanks for raising this and apologies for the delayed response on this thread.

I reviewed the domain configuration for your Amplify app `dlim9jss3y8u2` and it seems that all the domains both on the `.amplifyapp.com` and `.sieloapp.com` subdomains are resolving as expected:

```
dev - password protected
dev1 - password protected
dev2 - password protected
dev3 - password protected
dev4 - publicly accessible
prod - publicly accessible
```

Are you still running into any issues when accessing either of the subdomains?
