### ISSUE TITLE
Create a hosting deletes existing environment and setup

### ISSUE THREAD

**Issue by arvind-das** [aws-amplify/amplify-hosting#3589]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

ap-south-1

### Amplify Hosting feature

Frontend builds

### Question

I had setup a graphql backend which was working perfectly.  I created a react client and deployed that to hosting. As soon as I did it, all my configurations for graphql api were lost, database deleted. I lost all the setup. Is it expected that when you create hosting and it tries to deploy backend, any existing setups will be lost ? Please guide,

**Comment by Jay2113** [comment]
Hi @arvind-das 👋 , thanks for reaching out to us.

Can you please share the following information?
- Amplify App ID
- Detailed steps to reproduce the behavior that you are observing with amplify backend

**Comment by arvind-das** [comment]
Sure , just give me a day, the existing environment is deployed for testing now where I have deployed the frontend to s3 and is being used for demos , I will crate another app and share its details .
