### ISSUE TITLE
Amplify encounters issues connecting our custom domain

### ISSUE THREAD

**Issue by bogdan-neagu-lh** [aws-amplify/amplify-hosting#3593]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d36cxmqsra8du6

### Region

eu-west-1

### Step

Domain activation

### Status

Failed

### Issue or question

CNAME records have been created to the domain (hosted in a different environment)

nslookup -type=NS holcim-smartcast.lhinside.com
Server:  NASIACTDCPD01.na.holcim.net
Address:  10.215.74.237

Non-authoritative answer:
holcim-smartcast.lhinside.com   canonical name = d2g7uhrszy8cvy.cloudfront.net

nslookup -type=TXT _ae673dc628c482a00a56d767a3dbb26b.holcim-smartcast.lhinside.com
Server:  NASIACTDCPD01.na.holcim.net
Address:  10.215.74.237

Non-authoritative answer:
_ae673dc628c482a00a56d767a3dbb26b.holcim-smartcast.lhinside.com text =

        "_8a6dd795bd532b3444e80d63d30ae9f5.jzckvmdcqj.acm-validations.aws"

However, Domain activation failed with the message:

Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below.
Error message: [AmplifyWaitTimeout] The domain association has failed because we did not find the CNAME verification record on the DNS entries of your domain. Please check our troubleshooting guide for help: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html

### Error message

Error message: [AmplifyWaitTimeout] The domain association has failed because we did not find the CNAME verification record on the DNS entries of your domain.

**Comment by Jay2113** [comment]
Hi @bogdan-neagu-lh 👋 , thanks for reaching out to us!

The AmplifyWaitTimeout exception can occur if the DNS records (provided in the Amplify Console or fetched via AWS CLI) for your domain are not updated within the 3rd party DNS provider settings within 48 hours of connecting the custom domain to your Amplify app.

It is important that you perform this step soon after adding your custom domain in the Amplify console. The AWS Certificate Manager (ACM) immediately starts attempting to verify ownership. Over time, the checks become less frequent. If you add or update your CNAME records a few hours after you create your app, this can cause your app to get stuck in the pending verification state.

Our recommendations:

- If the domain activation process is stuck in the Amplify Console, you can either click the Retry button or delete the domain and then retry the process.
- Update the DNS records in the 3rd party DNS provider as soon as possible ideally within an hour.

**Comment by bogdan-neagu-lh** [comment]
Thank you for your reply. We finally made it work, but our experience with the process is not the greatest, because there is a very short window of time to perform the DNS entry change, and a Retry will change the DNS record to be added, so it is a vicious circle.

**Comment by Jay2113** [comment]
I am glad to hear that you were able to successfully connect a custom domain to your Amplify app @bogdan-neagu-lh and thanks for relaying the additional feedback on this process/workflow. I am going to share it with the team internally.
