### ISSUE TITLE
AWS Amplify Page not fetching applications

### ISSUE THREAD

**Issue by charlieforward9** [aws-amplify/amplify-hosting#3596]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

na

### Region

us-east-1

### Environment name

na

### What operating system are you using?

Mac

### Browser type?

Google Chrome

### Describe the bug

When I sign into my AWS account and click on Amplify in my recently visited, I am shown an error message saying: 

> List apps call failed
Network Failure"

### Expected behavior

Amplify apps should be shown on the service view.

### Reproduction steps

Sign into AWS account with MFA, click on Amplify service...

I am trying to set up a new dev environment on a new computer while my current computer gets repaired. I recently had a card decline a billing tap, but fixed it within a few days. I am hoping to access my application as soon as possible to minimize time-based impediments on my work.

**Comment by Jay2113** [comment]
Hi @charlieforward9 👋 , thanks for reaching out to us.

Can you please share your AWS Account ID (where you observing this exception) privately via a DM on our [community discord server](https://discord.gg/amplify)? My username is `Jay Raval`.
