### ISSUE TITLE
Can I change the request body size limit to resolve the 413 error?

### ISSUE THREAD

**Issue by ma2yama** [aws-amplify/amplify-hosting#3598]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dgmffouh08avy

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Question

Next.js containing large files (about 20MB) was deployed with Amplify.
An error occurred with status code 413 when accessing.
Can I change the maximum size of the request body?

**Comment by Jay2113** [comment]
Hi @ma2yama 👋 , thanks for reaching out to us and apologies for the delayed response here.

The maximum output size of an asset such as an image file on the Amplify Hosting Compute platform can't exceed 4.3 MB. Thus, the maximum size of the request body is immutable.

In this case, as a workaround you can have a larger image file stored somewhere and use the `next/image` component to resize and optimize it into a Webp or AVIF format and then serve it as a smaller size.
