### ISSUE TITLE
500 error on new NextJS-13.4.6 app after successful build and deploy 

### ISSUE THREAD

**Issue by darkdx** [aws-amplify/amplify-hosting#3604]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3pyyq39ksbou

### AWS Region

ap-southeast-1

### Amplify Hosting feature

SSR, Web previews

### Frontend framework

Next.js

### Next.js version

13.4.6

### Next.js router

App Router

### Describe the bug

The build was successful, but the page displays server 500.

<img width="1311" alt="image" src="https://github.com/aws-amplify/amplify-hosting/assets/88136242/43a60815-6d15-4a17-ba27-d8ca8c1e27f4">

### Expected behavior

Site renders as expected.

### Reproduction steps

- Select "Host Web App" from the "New app" drop down.
- Connect github repo
- Assign branch (master)
- Accept build settings and click "Next"
- Click "Save and Deploy"
- Wait for build and deploy to complete.
- Click on hyperlink to assigned URL
- Received 500 error

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm i
    build:
      commands:
        - npm run build:$BUILD_ENV
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
                                 # Starting phase: preBuild
                                 # Executing command: npm i
2023-07-21T03:37:10.693Z [INFO]: changed 7 packages, and audited 714 packages in 8s
2023-07-21T03:37:10.696Z [INFO]: 164 packages are looking for funding
                                 run `npm fund` for details
                                 2 moderate severity vulnerabilities
                                 To address all issues, run:
                                 npm audit fix
                                 Run `npm audit` for details.
2023-07-21T03:37:10.706Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
                                 # Executing command: npm run build:$BUILD_ENV
2023-07-21T03:37:11.056Z [INFO]: > nextjs13@0.1.0 build:dev
                                 > APP_ENV=dev next build
2023-07-21T03:37:11.564Z [INFO]: - warn No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
2023-07-21T03:37:11.576Z [INFO]: Attention: Next.js now collects completely anonymous telemetry regarding usage.
2023-07-21T03:37:11.576Z [INFO]: This information is used to shape Next.js' roadmap and prioritize features.
                                 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
                                 https://nextjs.org/telemetry
2023-07-21T03:37:11.664Z [INFO]: - info Creating an optimized production build...
2023-07-21T03:37:43.116Z [INFO]: - info Compiled successfully
2023-07-21T03:37:43.118Z [INFO]: - info Linting and checking validity of types...
2023-07-21T03:37:51.036Z [INFO]: - info Collecting page data...
2023-07-21T03:38:03.483Z [INFO]: - info Generating static pages (0/3)
2023-07-21T03:38:03.814Z [INFO]: - info Generating static pages (3/3)
2023-07-21T03:38:03.832Z [INFO]: - info Finalizing page optimization...
2023-07-21T03:38:03.834Z [INFO]: 
2023-07-21T03:38:03.860Z [INFO]: Route (app)                                Size     First Load JS
                                 ┌ λ /[locale]                              2.05 kB         113 kB
                                 ├ λ /[locale]/hatch                        10.5 kB         314 kB
                                 └ ○ /favicon.ico                           0 B                0 B
                                 + First Load JS shared by all              111 kB
                                 ├ chunks/5769-5597d8064b76b266.js        25.3 kB
                                 ├ chunks/7698-b02f66b356ce2152.js        32 kB
                                 ├ chunks/bce60fc1-f64723d0939dbe29.js    50.5 kB
                                 ├ chunks/main-app-f38b6241210f2f7b.js    223 B
                                 └ chunks/webpack-134d055da76f5c92.js     2.63 kB
                                 Route (pages)                              Size     First Load JS
                                 ─ ○ /404                                   185 B          75.9 kB
                                 + First Load JS shared by all              75.8 kB
                                 ├ chunks/framework-4498e84bb0ba1830.js   45.1 kB
                                 ├ chunks/main-68a505b286e29d35.js        27.9 kB
                                 ├ chunks/pages/_app-8fa61e72220a040a.js  200 B
                                 └ chunks/webpack-134d055da76f5c92.js     2.63 kB
                                 ƒ Middleware                               27.1 kB
2023-07-21T03:38:03.861Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
2023-07-21T03:38:04.774Z [INFO]: # Completed phase: build
2023-07-21T03:38:04.776Z [INFO]: ## Build completed successfully
2023-07-21T03:38:04.777Z [INFO]: # Starting caching...
2023-07-21T03:38:04.787Z [INFO]: # Creating cache artifact...
2023-07-21T03:38:15.819Z [INFO]: # Created cache artifact
2023-07-21T03:38:15.907Z [INFO]: # Uploading cache artifact...
2023-07-21T03:38:19.720Z [INFO]: # Uploaded cache artifact
2023-07-21T03:38:19.788Z [INFO]: # Caching completed
2023-07-21T03:38:19.792Z [INFO]: Setting NEXT_PRIVATE_STANDALONE=true to produce .next/standalone directory
2023-07-21T03:38:19.795Z [INFO]: # No custom headers found.
2023-07-21T03:38:24.856Z [INFO]: # Starting environment caching...
2023-07-21T03:38:24.929Z [INFO]: # Environment caching completed
Terminating logging...

```

</details>

**Comment by darkdx** [comment]
@Jay2113 Would you mind taking a look

**Comment by victorccccc** [comment]
Hi,

After checking the log, you might be impacted by the NextJs issue introduced by App Router implementation. Can you try this workaround?  https://github.com/vercel/next.js/issues/49169#issuecomment-1625667285.

In the meantime, I cannot reproduce this issue deploying the App router app, do you have any special settings? (e.g basePath)

Thanks

**Comment by darkdx** [comment]
> Hi, 你好
> 
> After checking the log, you might be impacted by the NextJs issue introduced by App Router implementation. Can you try this workaround? [vercel/next.js#49169 (comment)](https://github.com/vercel/next.js/issues/49169#issuecomment-1625667285).检查日志后，您可能会受到应用路由器实现引入的 NextJs 问题的影响。您可以尝试此解决方法吗？Vercel/next.js#49169（评论）。
> 
> In the meantime, I cannot reproduce this issue deploying the App router app, can you please make sure you have `page.js (jsx, tsx)` under the root of `app` folder as it's required by [app router](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#pages)?同时，我无法重现部署应用程序路由器应用程序的此问题，您能否确保您在应用程序路由器所需的文件夹根 `app` 目录下？ `page.js (jsx, tsx)`
> 
> Thanks 谢谢

I'll try. 

Here is my directory structure

<img width="309" alt="image" src="https://github.com/aws-amplify/amplify-hosting/assets/88136242/cc92105c-df77-4da9-8eb6-850163b763ac">

My local build and then run start is displayed normally.

**Comment by darkdx** [comment]
> Hi, 你好
> 
> After checking the log, you might be impacted by the NextJs issue introduced by App Router implementation. Can you try this workaround? [vercel/next.js#49169 (comment)](https://github.com/vercel/next.js/issues/49169#issuecomment-1625667285).检查日志后，您可能会受到应用路由器实现引入的 NextJs 问题的影响。您可以尝试此解决方法吗？Vercel/next.js#49169（评论）。
> 
> In the meantime, I cannot reproduce this issue deploying the App router app, can you please make sure you have `page.js (jsx, tsx)` under the root of `app` folder as it's required by [app router](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#pages)?同时，我无法重现部署应用程序路由器应用程序的此问题，您能否确保您在应用程序路由器所需的文件夹根 `app` 目录下？ `page.js (jsx, tsx)`
> 
> Thanks 谢谢

![image](https://github.com/aws-amplify/amplify-hosting/assets/88136242/69b238ca-8f73-4d93-859c-e5fba83a213d)
It failed. I was running it successfully.

**Comment by darkdx** [comment]
<img width="333" alt="image" src="https://github.com/aws-amplify/amplify-hosting/assets/88136242/7ac51448-382a-452e-b36f-1796c9bb9d09">

I think my Build is a success.

**Comment by darkdx** [comment]
@nadetastic Can you take a look at that for me? Thank you

**Comment by darkdx** [comment]
It could be used normally a few days ago, but the error of 500 was reported in the last few days. Did you make any changes?

**Comment by darkdx** [comment]
@swaminator 
@siegerts 
@calavera
Could you please help to have a look? Thank you. It has affected the normal launch of the project.

**Comment by ferdingler** [comment]
> It could be used normally a few days ago, but the error of 500 was reported in the last few days. Did you make any changes?

@darkdx the appId you provided `d3pyyq39ksbou` was created on July 20th (yesterday). Is there another app that was working  before but stopped working? if so, could you provide the appId for it? 

Also, have you tried adding the `page.jsx` in the root of the `app` directory? That page is the UI for the `/` URL.

**Comment by doiali** [comment]
> In the meantime, I cannot reproduce this issue deploying the App router app, can you please make sure you have `page.js (jsx, tsx)` under the root of `app` folder as it's required by [app router](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#pages)?

I had the same issue and went through a lot of pain. But finally this worked for me. Thank you so much.

@ferdingler 
Here is a previous build that the error is still present in:   
- d1uhtp6enph3is  
- ca-central

You can see the 500 error happening in [this link](https://applylink.ai/people/user1)

**Comment by darkdx** [comment]
> > It could be used normally a few days ago, but the error of 500 was reported in the last few days. Did you make any changes?
> 
> @darkdx the appId you provided `d3pyyq39ksbou` was created on July 20th (yesterday). Is there another app that was working before but stopped working? if so, could you provide the appId for it?
> 

appId: d2ecldvvwhurjm
branch: dev

> Also, have you tried adding the `page.jsx` in the root of the `app` directory? That page is the UI for the `/` URL.

I used next-intl.
<img width="318" alt="image" src="https://github.com/aws-amplify/amplify-hosting/assets/88136242/13f2f36d-4ea0-4369-87f0-8d8b62f6819b">

The display is normal after deployment last week, please confirm whether your code has changed.

Please resolve as soon as possible. In addition, the display is normal after vercel deployment.

Thank you.

**Comment by darkdx** [comment]
next-intl: https://next-intl-docs.vercel.app/docs/getting-started/app-router-client-components

**Comment by victorccccc** [comment]
Hi, @darkdx 

Sorry for the inconvenience. Could you please follow these steps below to add the environment variable as a workaround?

1. **[Important]** Set environment variable `__NEXT_PRIVATE_PREBUNDLED_REACT=next` in Amplify Console:

<img width="1467" alt="Screen Shot 2023-07-23 at 23 07 30" src="https://github.com/aws-amplify/amplify-hosting/assets/17761274/fc70d279-4751-45a0-aca7-90a55d65339e">

2. Add following command in your build spec:
```
build:
    commands:
      - env | grep -e __NEXT_PRIVATE_PREBUNDLED_REACT >> .env.production
```

We still cannot reproduce the issue by [example app](https://github.com/amannn/next-intl/tree/main/examples/example-next-13) provided by `next-intl`. Could you please send us a minimal reproduction repository if possible? (aws-amplify-customer@amazon.com)

Thanks a lot!

**Comment by darkdx** [comment]
> Hi,  你好@darkdx
> 
> Sorry for the inconvenience. Could you please follow these steps below to add the environment variable as a workaround?很抱歉给您带来不便。您能否按照以下步骤添加环境变量作为解决方法？
> 
> 1. **[Important]** Set environment variable `__NEXT_PRIVATE_PREBUNDLED_REACT=next` in Amplify Console:[重要]在放大控制台中设置环境变量 `__NEXT_PRIVATE_PREBUNDLED_REACT=next` ：
> 
> <img alt="Screen Shot 2023-07-23 at 23 07 30" width="1467" src="https://user-images.githubusercontent.com/17761274/255498624-fc70d279-4751-45a0-aca7-90a55d65339e.png">
> 2. Add following command in your build spec:在构建规范中添加以下命令：
> 
> ```
> build:
>     commands:
>       - env | grep -e __NEXT_PRIVATE_PREBUNDLED_REACT >> .env.production
> ```
> 
> We still cannot reproduce the issue by [example app](https://github.com/amannn/next-intl/tree/main/examples/example-next-13) provided by `next-intl`. Could you please send us a minimal reproduction repository if possible? ([aws-amplify-customer@amazon.com](mailto:aws-amplify-customer@amazon.com))我们仍然无法通过 提供 `next-intl` 的示例应用程序重现该问题。如果可能的话，您能否向我们发送一个最小的复制存储库？（ aws-amplify-customer@amazon.com）
> 
> Thanks a lot! 多谢！

Thank you very, very much for your reply, adding the environment variable `__NEXT_PRIVATE_PREBUNDLED_REACT=next`failed, but by looking at the [example app](https://github.com/amannn/next-intl/tree/main/examples/example-next-13), tsx no-found.tsx solved 500 errors after adding app and `page.tsx,layout.tsx,no-found.tsx`. Thank you very much. Have a good life.
