### ISSUE TITLE
allow access only via CloudFront and disallow direct access to the Amplify App URL

### ISSUE THREAD

**Issue by minozo** [aws-amplify/amplify-hosting#3605]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

ap-southeast-1

### Amplify Hosting feature

Access control

### Question

I am using Amplify via CloudFront and would like to only show access from Cloudfront and disallow direct access to the Amplify App URL, is there a way to do this?

When I put password restrictions in Access Control, the password restrictions are also applied from the address via CloudFront.

**Comment by Jay2113** [comment]
Hi @minozo 👋 , thanks for raising this with us!

The Amplify generated URL `https://<branch-name>.<app-id>.amplifyapp.com` is publicly accessible and it cannot be disabled for any Amplify application. 

If you have connected a custom domain to your app, our recommendation would be as follows:
- Share the custom domain URL with your customers
- You can consider adding a redirect rule which would redirect your customers from the Amplify generated URL to your custom domain:
```
{
        "source": "https://<branch-name>.<app-id>.amplifyapp.com",
        "target": "https://example.com",
        "status": "302",
        "condition": null
}
```
