### ISSUE TITLE
Size of build output error, although nextjs build output is way smaller

### ISSUE THREAD

**Issue by jbreemhaar** [aws-amplify/amplify-hosting#3606]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dqdk4n5ewneid, d2vwdfz9609eox

### AWS Region

us-west-1

### Amplify Hosting feature

Frontend builds

### Question

Hi all!

I've been having issues with a specific nextjs app in a monorepo with two other nextjs apps.  It's the smallest nextjs app of three with only one page and one API route. The build output is fairly large (172M total, 73M of .next/cache) but that's far less than the reported file size from the build process (238471689). I've got a hunch this error started being thrown since a different app (but from the same monorepo) actually had a too large build size (lots of static resources were accidentally pushed and deployed). The weird part is that the error is also being thrown when hosting the problematic app with a newly created amplify app. 

appID dqdk4n5ewneid is an app created today, same problem.
appID d2vwdfz9609eox is the existing app which has been stuck now for days (maybe weeks).

So the other two monorepo apps are way, way bigger (e.g. ~30 pages with 4 locales, lots of static resources) and have no issues with being build. One of those has a build output of 458M, but 316M of it is .next/cache. 

I'm pretty much stuck at the moment, and been trying to fix this issue for the last couple of days. I understand monorepo's, nextjs build output is not the Amplify's team responsibility, but 🤷‍♂️  no idea what to do next. 

Error being thrown is:
`!!! CustomerError: The size of the build output (238471689) exceeds the max allowed size of230686720 bytes. Please reduce the size ofyour build output and try again.`

**What I've tried**
* Creating a new app. 
* Adding `- envCache --set stackInfo ""` to amplify build phase.
* Adding `rm -rf .next/cache/` as a build and postbuild command. 
* Different frontend.artifacts.build locations in amplify.yml.
* Tons of tinkering with nextjs versions, amplify cli versions, nextjs configurations, etc.

**What I haven't tried yet**
* amplify CLI  command invalidate-project-cache command  https://awscli.amazonaws.com/v2/documentation/api/latest/reference/codebuild/invalidate-project-cache.html. I'm not sure which codebuild project I should use as it managed by amplify. Also a newly setup app shouldn't have build cache already available right?
 
This issue might be related https://github.com/aws-amplify/amplify-hosting/issues/3601 because of the build size exceeding  error since a deployment with a build actually being too large. Difference is a different monorepo-amplify-app had the actual exceeding build output, and the app mentioned in this issue is still throwing the error.

**Comment by ferdingler** [comment]
@jbreemhaar could you check what is taking most of the size on your build output? You can do this by running the following commands locally: 

1. Run a build first using standalone mode (this will produce node_module folders inside .next/standalone). 
```bash
export NEXT_PRIVATE_STANDALONE=true
npm run build # or yarn build
```

2. Now check the size of these folders

Static files
```bash
du -h .next/static
```

Public folder
```bash
du -h public
```

and the standalone folder
```bash
du -h .next/standalone
```

**Comment by jbreemhaar** [comment]
@ferdingler sure!

.next/static
2.5M    .next/static

public
4.2M    public

96M    .next/standalone

**Comment by ulisse1996** [comment]
Hi, we have the same problem with a full NextJS 13.4.10

46M .next/static
12M public
126M .next/standalone

**Comment by eschnou** [comment]
Same issue here, even when simply triggering a **build that passed before**: worked fine in July 21st and fails today when retriggering the same build with same commit, same dependencies, same build pipeline etc.

When checking on size, both locally and on the node with du, the size is about 159M:

```
2023-07-26T11:56:37.462Z [INFO]: ℇ  (Streaming)  server-side renders with streaming (uses React 18 SSR streaming or Server Components)
                                 λ  (Server)     server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)     automatically rendered as static HTML (uses no initial props)
2023-07-26T11:56:37.684Z [INFO]: # Executing command: du -h -d1 .next
2023-07-26T11:56:37.687Z [INFO]: 133M	.next/cache
2023-07-26T11:56:37.688Z [INFO]: 30M	.next/server
2023-07-26T11:56:37.688Z [INFO]: 28M	.next/static
2023-07-26T11:56:37.688Z [INFO]: 44K	.next/types
2023-07-26T11:56:37.702Z [INFO]: 99M	.next/standalone
                                 291M	.next
2023-07-26T11:56:37.702Z [INFO]: # Executing command: rm -fr .next/cache
2023-07-26T11:56:37.719Z [INFO]: # Executing command: du -h -d1 .next
2023-07-26T11:56:37.720Z [INFO]: 30M	.next/server
2023-07-26T11:56:37.720Z [INFO]: 28M	.next/static
2023-07-26T11:56:37.721Z [INFO]: 44K	.next/types
2023-07-26T11:56:37.734Z [INFO]: 99M	.next/standalone
                                 159M	.next
2023-07-26T11:56:37.734Z [INFO]: # Completed phase: build
2023-07-26T11:56:37.735Z [INFO]: ## Completed Frontend Build
2023-07-26T11:56:37.736Z [INFO]: ## Build completed successfully
2023-07-26T11:56:37.738Z [INFO]: Setting NEXT_PRIVATE_STANDALONE=true to produce .next/standalone directory
2023-07-26T11:56:37.740Z [INFO]: Found customHttp.yml, applying custom headers...
2023-07-26T11:57:18.260Z [ERROR]: !!! CustomerError: The size of the build output (323613118) exceeds the max allowed size of230686720 bytes. Please reduce the size ofyour build output and try again.

```

**Comment by Jay2113** [comment]
Hey everyone 👋

We just released some changes to improve how we bundle Next.js apps. These changes don't need the standalone directory anymore. That should help eliminate the problem of reaching the 200MB bundle limit. These changes require a new deploy in your application to take effect. The expected outcome is that your app bundles should be smaller, and not bump into the size limit.

If you have comments or questions don't hesitate to reach us via AWS support.
