### ISSUE TITLE
Provisioning step is never ending

### ISSUE THREAD

**Issue by EmilioOjeda** [aws-amplify/amplify-hosting#3609]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dylhf6dk0pdfu

### AWS Region

us-east-1

### Amplify Hosting feature

Git providers

### Frontend framework

Other

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

I've been trying for 2 days to get deployed a new version of the website.

Previously, amplify detected the changes on the **master** branch and triggered the deploys automatically. Well, this stopped working. Then I tried to run the flow manually by clicking on the "**Redeploy this version**" option, but the "**Provisioning**" step was never-ending.

### Expected behavior

Be able to deploy changes; get all the steps working again: Provisioning > Build > Deploy.

### Reproduction steps

I've tried 2 things.

1. By pushing changes to the branch configured in the app.
2. Click on the "Redeploy this version" option to trigger the deployment process manually.

... none of the options is working.

![Screenshot 2023-07-21 at 13 26 19](https://github.com/aws-amplify/amplify-hosting/assets/30152877/b5268c68-fee4-4aae-a1cb-e5e42a80a942)
![Screenshot 2023-07-21 at 13 24 15](https://github.com/aws-amplify/amplify-hosting/assets/30152877/f9625538-0879-45d7-a8fd-b6fc717368f4)

**Comment by Jay2113** [comment]
Hi @EmilioOjeda 👋 ,

In order to further troubleshoot your issue, please reach out to the AWS Support team: https://aws.amazon.com/support for additional assistance.

Thank you!
