### ISSUE TITLE
Environment Variables is confusing...????

### ISSUE THREAD

**Issue by xanderbilla** [aws-amplify/amplify-hosting#3610]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3uw69qnd5b4kr

### AWS Region

ap-south-1

### Amplify Hosting feature

Environment variables, SSR

### Question

I created an app using **NextJs** and now I want to host it on AWS Amplify but I don't know how to handle those Environment Variables. I tried to put the exact key value in Environment Variables of my amplify app, but the app itself returned an error that is failed to fetch data 

Thank you

**Comment by ferdingler** [comment]
> but I don't know how to handle those Environment Variables

What environment variables are you referring to? 

Here is our documentation on how to make your environment variables visible to the SSR Compute runtime: https://docs.aws.amazon.com/amplify/latest/userguide/ssr-environment-variables.html

**Comment by xanderbilla** [comment]
I have been using jwttoken and mongoDB env variables but I'm not able to do the same on Amplify.

**Comment by Jay2113** [comment]
@xanderbilla Are you still running into issues when trying to make your environment variables visible to the SSR Compute runtime? If yes, can you confirm that you followed the steps outlined in this documentation: https://docs.aws.amazon.com/amplify/latest/userguide/ssr-environment-variables.html?
