### ISSUE TITLE
Amplify app Github connectivity lost

### ISSUE THREAD

**Issue by vgthoppae** [aws-amplify/amplify-hosting#3612]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d30wn2r7brpbf5

### AWS Region

us-east-1

### Amplify Hosting feature

Git providers

### Question

This app has been running fine for a couple of months. One fine day, it lost its connectivity to Github, not just that, I don't see any git repo as an option at all in the repository setting. Before creating a new app, I wanted to see what caused it and see if we can possibly salvage this app. 

Note: Service role was found missing from the Settings page, which I added back, but made no change.

<img width="1022" alt="Screen Shot 2023-07-24 at 11 19 18 AM" src="https://github.com/aws-amplify/amplify-hosting/assets/4568997/e717893d-164f-4e84-a07a-5c476f67211b">

**Comment by Jay2113** [comment]
Hi @vgthoppae 👋 , thanks for raising this issue!

Currently, I see that the Amplify app `d30wn2r7brpbf5` does not have a git repository associated to it. If you had previously connected a git repository to this app, you can review the following resources to understand the changes made to your Amplify app resource:
- Review the `DeleteBranch`, `UpdateApp` and `UpdateBranch` API calls made from your AWS account using [AWS CloudTrail](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-getting-started.html). You can also refer to the Amplify API actions [here](https://docs.aws.amazon.com/amplify/latest/APIReference/API_Operations.html).
- Verify if the [GitHub app](https://docs.aws.amazon.com/amplify/latest/userguide/setting-up-GitHub-access.html) is installed appropriately as it required for read-only access to repositories.
