### ISSUE TITLE
The 'node_modules' folder is missing the 'next' dependency

### ISSUE THREAD

**Issue by timdouglas** [aws-amplify/amplify-hosting#3616]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1m9105kyx4cvx

### AWS Region

eu-west-1

### Amplify Hosting feature

Deployments, Frontend builds

### Frontend framework

React

### Next.js version

13.3.4

### Next.js router

Pages Router

### Describe the bug

Frontend build deployment is failing with message below despite no changes to the build settings

```
[ERROR]: !!! CustomerError: The 'node_modules' folder is missing the 'next' dependency. This is required at runtime to run your application. If you are using a monorepo framework, you may need to do additionalsetup to ensure the necessary runtime dependencies are included in the build output directory Read more: https://github.com/aws-amplify/amplify-hosting/blob/main/FAQ.md#using-a-monorepo-framework
```

First failure coincided with the first use of @aws-amplify/cli version 12.2.0, but rolling back to 12.1.1 still produces the failure.

Above message appears on the test job, but not on the build job.

### Expected behavior

Build pipeline to pass and deployments to succeed

### Reproduction steps

1. Trigger a new build on the app
2. Build job passes
3. Test job starts
4. Tests pass
5. Error appears after test artifacts uploaded

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple

frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next/
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .next/**/*

test:
  phases:
    preTest:
      commands:
        - npm ci
        - npm install wait-on pm2
        - npm run build
        - npx pm2 start npm -- run start
        - npx wait-on --timeout 60000 http://localhost:3000
    test:
      commands:
        - CYPRESS_BASE_URL="http://localhost:3000" npm run cypress:run -- --env tags=@smoke --record
    postTest:
      commands:
        - npx pm2 kill
  artifacts:
    baseDirectory: cypress
    files:
      - 'report/**/*.json'
      - '**/*.png'
      - '**/*.mp4'
```

### Log output

<details>

```
2023-07-25T12:03:43.692Z [INFO]: ## Tests completed successfully
2023-07-25T12:03:43.694Z [INFO]: # Starting test artifact upload process...
2023-07-25T12:03:43.703Z [WARNING]: ! Test config file not found for the configFilePath glob provided in your build spec: **/mochawesome.json
2023-07-25T12:03:43.725Z [INFO]: # Uploading build artifact 'testArtifacts.zip'...
2023-07-25T12:03:43.808Z [INFO]: # Test artifact upload completed
2023-07-25T12:03:43.810Z [INFO]: # No custom headers found.
2023-07-25T12:03:47.391Z [ERROR]: !!! CustomerError: The 'node_modules' folder is missing the 'next' dependency. This is required at runtime to run your application. If you are using a monorepo framework, you may need to do additionalsetup to ensure the necessary runtime dependencies are included in the build output directory Read more: https://github.com/aws-amplify/amplify-hosting/blob/main/FAQ.md#using-a-monorepo-framework
2023-07-25T12:03:47.511Z [INFO]: # Starting environment caching...
2023-07-25T12:03:47.511Z [INFO]: # Uploading environment cache artifact...
2023-07-25T12:03:47.582Z [INFO]: # Uploaded environment cache artifact
2023-07-25T12:03:47.582Z [INFO]: # Environment caching completed
Terminating logging...
```

</details>

**Comment by timdouglas** [comment]
Added a command to list out `node_modules` at the end of the frontend and test jobs, both include `next` directory:

```
2023-07-25T12:55:11.005Z [INFO]: # Executing command: ls -lah node_modules
2023-07-25T12:55:11.019Z [INFO]: total 1.9M
                                 drwxr-xr-x 1090 root root  32K Jul 25 12:51 .
                                 drwxr-xr-x   20 root root 4.0K Jul 25 12:51 ..
...
                                 drwxr-xr-x   10 root root 4.0K Jul 25 12:51 next
                                 drwxr-xr-x    6 root root   94 Jul 25 12:51 @next
...
```

**Comment by victorccccc** [comment]
Hi @timdouglas 👋, can you ensure all `.nft.json` files are present as they are necessary for the WEB COMPUTE deployment.

Thanks

**Comment by ferdingler** [comment]
The `node_modules` folder is now generated by reading the `.nft.json` files produced by the Next.js build. The nft.json files dictate the files needed to be copied to the node_modules folder. In your case, you have a command in your buildspec that removes those files `.next -type f -name '*.nft.json' -delete` which is causing the resulting `node_modules` folder to be empty. 

Listing the contents of node_modules with `ls -lah node_modules` is not an accurate check because you are listing the node_modules on the root of your project, which includes devDependencies and prod dependencies. We produce another trimmed down version of node_modules folder based on the nft.json files.

**Comment by timdouglas** [comment]
Hi @victorccccc that did the trick. When did the files become required? We were told to remove them a few months ago when we were having issues with deployment bundle size
