### ISSUE TITLE
Deploy stuck in Provision state 

### ISSUE THREAD

**Issue by Gallyket1** [aws-amplify/amplify-hosting#3620]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d7fgjwnrevxdk

### AWS Region

eu-west-1

### Amplify Hosting feature

Frontend builds

### Frontend framework

React

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

When J launch the build, it's stuck on the "Provision" state

![image](https://github.com/aws-amplify/amplify-hosting/assets/41904793/90e44868-dd86-44f1-a78a-5242fcc76a30)

### Expected behavior

The deploy should reach the "Build" step

### Reproduction steps

1. Connect the app using GitHub (It's React app)
2. Launch the deploy
3. The deploy still on the "Provision" state for a long time 

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Jay2113** [comment]
Hi @Gallyket1 👋 ,

In order to further troubleshoot your issue, please reach out to the AWS Support team: https://aws.amazon.com/support for additional assistance.

Thank you!
