### ISSUE TITLE
Application error: a server-side exception has occurred (see the server logs for more information)

### ISSUE THREAD

**Issue by AnirudhaGohokar** [aws-amplify/amplify-hosting#3621]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2umt3ed2rr7fk

### AWS Region

eu-west-2

### Amplify Hosting feature

SSR

### Frontend framework

NextJS-SSR

### Next.js version

13.4.10+

### Next.js router

App Router

### Describe the bug

Suddenly server side rendered pages are breaking. Getting below error when doing server side rendering only. Client side rendering is wroking fine:

`application error: a server-side exception has occurred (see the server logs for more information). Digest: xyz`

### Expected behavior

Server side rendering should work properly

### Reproduction steps

Open any SSR page

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Jay2113** [comment]
Hi @AnirudhaGohokar 👋 , thanks for raising this!

Have you reviewed the SSR compute logs for your Amplify app `d2umt3ed2rr7fk`? The logs should be present in a CloudWatch Log group named `/aws/amplify/d2umt3ed2rr7fk` and these logs might potentially reflect some errors which could help you identify the root cause of the SSR pages that are failing to load.

**Comment by AnirudhaGohokar** [comment]
Hi @Jay2113 ,

We are also unable to access log in same zone. Tried switching to different AZ's but no luck. See attached screenshot:

![image](https://github.com/aws-amplify/amplify-hosting/assets/5802339/8c4c58d0-1b9a-41e5-aef6-c2c5c4357be7)

**Comment by AnirudhaGohokar** [comment]
Deployed this on vercel and we got no issues with SSR their so there is definitely something wrong with Amplify hosting.

**Comment by AnirudhaGohokar** [comment]
Issue got resolved after we downgraded nextjs v13.4.10 to v13.2.4. 
You guys really need to do proper comtability testing.

**Comment by AnirudhaGohokar** [comment]
update issue happening only with NextJS 13.4.10+ versions. Below 13.4.0 giving blank page. Working fine with 13.4.3 - 13.4.9
