### ISSUE TITLE
AWS Amplify recurring deploy fail

### ISSUE THREAD

**Issue by basfordrobert** [aws-amplify/amplify-hosting#3623]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

app-id d2ina7ghoi2un8

### AWS Region

ap-southeast-2

### Amplify Hosting feature

Deployments

### Frontend framework

Other

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

AWS Amplify deployment fails. Method of upload of static website file Archive.zip via local HDD and now S3 both fail.

### Expected behavior

Upload succeeds.

### Reproduction steps

AWS Amplify 
Select Deployment method HDD or S3
Deploy

### Build Settings

```yaml
Build to file Archive.zip (<50Mb)
```

### Log output

<details>
AWS Amplify Error message: Please reload this page to continue // on reload same error message
</details>

### Additional information

Tried to resolve this using support documentation during past few days without success.
I've used CLI to remove "Failed" and "Pending" jobs.

**Comment by basfordrobert** [comment]
Status Fri 28/07/2023: Deployment defect DAY 10.  
Last successful deployment: 18/07/2023.
My Action Fri 28/07/2023: Local cache again cleared. Re-Login again AWS account. Result: Same defect -> AWS Amplify deployment "pending" from S3 bucket.

**Comment by basfordrobert** [comment]
Status Mon 31/07/2023: Deployment defect DAY 13.
Last successful deployment: 18/07/2023.
My Action Mon 31/07/2023: Local cache again cleared. Re-Login again AWS account. Result: Same defect -> AWS Amplify deployment "pending" from S3 bucket / pending from Drag/Drop / pending from Select file methods.
Recommended alternative to AWS Amplify?

**Comment by basfordrobert** [comment]
Status Mon 31/07/2023: Deployment DAY 15.  Deployment DAY 14 had again failed.  
For some unexplained reason Deployment DAY 15 succeeded?????
Leaving this issue OPEN until AWS can provide a resolution path from manual Amplify Deploy defect to success.

**Comment by Jay2113** [comment]
Hi @basfordrobert 👋 , thanks for raising this with us and sorry to hear that you have been experiencing issues with manual deployments.

We are aware of issues with the `drag and drop` functionality when performing manual deployments and please refer to this FAQ: https://github.com/aws-amplify/amplify-hosting/blob/main/FAQ.md#deployments-or-jobs-are-stuck-with-a-pending-status-in-the-amplify-console which outlines some potential reasons why this behavior can occur.

That being said, can you please share some `deployment IDs` when this behavior was observed while using the Amazon S3 method of performing manual deployments? You can retrieve the `deployment IDs` as follows:
- Navigate to the app in the Amplify console
- Select the `prod` hosting environment 
- Click on `View deployment history` button
