### ISSUE TITLE
SDK for JS v3 asks for AWS_* env variables but amplify does not accept "AWS" word

### ISSUE THREAD

**Issue by andre-mr** [aws-amplify/amplify-hosting#3629]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3vc3r2jaskk9c

### AWS Region

sa-east-1

### Amplify Hosting feature

Backend builds, Environment variables, Frontend builds, SSR

### Question

Hi.

I migrated a project to AWS-SDK For Javascript v3, and now I have some issues with credentials.
This doc says credentials from environment variables (method i was using in v2) are auto detected but with specific name convention: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN:
https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/loading-node-credentials-environment.html

Not using token part for now.

With version 2, I had to rename my variables starting with "AWS_*", replacing with "AMAZON_*" because amplify doesn't accept variables starting with "AWS" word.

Now I honestly don't know how this is intended for v3. SDK expecting "AWS_ACCESS_KEY_ID" but amplify doesn't accept this naming convention.

I tried to deploy to Vercel, wich doesn't have "AWS" prefix restriction, and it worked as a charm.

This is the file where I setup DocumentClient, where I defined credentials with v2 and now it doesn't need for Vercel (as v3 docs stated by the way):
```
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient } from "@aws-sdk/lib-dynamodb";

const Table = process.env.AMAZON_DYNAMODB_TABLE;
const AMAZON_REGION = process.env.AMAZON_REGION;
const client = new DynamoDBClient({ region: AMAZON_REGION });
const docClient = DynamoDBDocumentClient.from(client);

const AWSDynamoDB = () => {
  return docClient;
};

export { AWSDynamoDB, Table };

```

Any ideas to deal with that, other than downgrading to v2?

**Comment by andre-mr** [comment]
Nevermind... found a solution, using "AMAZON_*" instead of "AWS_*" as I did with v2.

Just setup credentials parameter, this way:
```
const client = new DynamoDBClient({
  region: AMAZON_REGION,
  credentials: {
    accessKeyId: AMAZON_ACCESS_KEY_ID,
    secretAccessKey: AMAZON_SECRET_ACCESS_KEY,
  },
});
```

Really don't know why Amplify has "AWS*" as reserved prefix, since there's just a few default variables using that. 🤷‍♂️
You could revise this rule, to better match v3 convention about default env approach.

**Comment by Jay2113** [comment]
Hi @andre-mr 👋 , thanks for raising this with us! 

You've correctly mentioned that Amplify Hosting does not allow the use of environment variables with a prefix of `AWS*` as it is reserved for internal use only and the following error will be returned in the console:
```
Operation failed - Environment variables cannot start with the reserved prefix "AWS".
```

We will update our [documentation](https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html) to accurately reflect the same.

**Comment by Jay2113** [comment]
@andre-mr 👋 , our documentation has been updated to reflect this information: https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html.
