### ISSUE TITLE
IP Range(s) for AWS Amplify GitHub App

### ISSUE THREAD

**Issue by dstead2** [aws-amplify/amplify-hosting#3634]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3l4oxsvslgkht

### AWS Region

us-west-2

### Amplify Hosting feature

Git providers

### Question

Is there a list of IP addresses that the AWS Amplify GitHub app uses? My organization will be enforcing an IP Allowlist and I need to ensure that IP addresses used GitHub app are allowed.

**Comment by Jay2113** [comment]
Hi @dstead2 👋 , thanks for raising this!

We haven't added or implemented any IP address allow list on the AWS Amplify GitHub app which is used to authorize Amplify read-only access to GitHub repositories.
