### ISSUE TITLE
Images not showing after deployment

### ISSUE THREAD

**Issue by FilipaMerino** [aws-amplify/amplify-hosting#3639]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d38ivm2hflcl3i

### AWS Region

us-east-1

### Amplify Hosting feature

Build settings

### Frontend framework

Next.js

### Next.js version

13

### Next.js router

App Router

### Describe the bug

My images are working locally, and still work if i deploy on vercel. but when i deploy on aws amplify, they don't show.. 
My images are located in a directory named "images" under my public directory

### Expected behavior

I want the images to show

### Reproduction steps

i Deployed and then my images don't show

### Log output

image:1     GET https://master.d38ivm2hflcl3i.amplifyapp.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FbannerPic.24ef67af.png&w=2048&q=75 404
image:1     GET https://master.d38ivm2hflcl3i.amplifyapp.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FblogBackSquare.8e227e63.png&w=3840&q=75 404
image:1     GET https://master.d38ivm2hflcl3i.amplifyapp.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fsubscribe.dd96de83.jpeg&w=2048&q=75 404
image:1     GET https://master.d38ivm2hflcl3i.amplifyapp.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FblogBack.a0f8da1c.png&w=1920&q=75 404
image:1     GET https://master.d38ivm2hflcl3i.amplifyapp.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo.f3f60dc5.png&w=3840&q=75 404
favicon.ico:1     GET https://master.d38ivm2hflcl3i.amplifyapp.com/favicon.ico 404

**Comment by terrymun** [comment]
This is likely due to issues with reading the middleware, and is probably related to #3641. I've experienced the same problem too.

**Comment by Jay2113** [comment]
Hi @FilipaMerino 👋 , thanks for raising this!

Can you please share the following information:
- Next.js version used by the Amplify app `d38ivm2hflcl3i`
- Did the issue start occurring once you upgraded the Next.js version (to maybe latest)? If yes, can you try downgrading it to see if that mitigates the issue.
