### ISSUE TITLE
SSL Configuration

### ISSUE THREAD

**Issue by lukaszbodziony1** [aws-amplify/amplify-hosting#3643]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d21457y6tio4ez

### Region

eu-central-1

### Step

SSL configuration

### Status

Pending

### Issue or question

I bought my domain on seohost.pl, and deployed my react app on AWS Amplify. 
On seohost side added CNAME records for my domain that are pointing the url provided by amplify (without https://).
Then moved DNS also to Route 53 - on seohost side added NS records from R53.
In Amplify dashboard I've added custom domain with SSL, to seohost and R53 added CNAME with name and value I was asked by Amplify and done the same with www record.
Status is still pending, I'm not sure if should I do some additional steps.
Under my custom domain I want to attach I can see 403 error from CloudFront.

**Comment by lukaszbodziony1** [comment]
I've made a mistake in my app id, it's d21457y6tio4ez - sorry for that

**Comment by Jay2113** [comment]
Hi @lukaszbodziony1 👋 , thanks for raising this with us!

I observed that the domain activation process has failed to complete on your Amplify app `d21457y6tio4ez`. Are you observing any specific errors in the Amplify Console?

Please refer to this troubleshooting guide related to custom domains as it outlines common scenarios and resolution steps for them: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html

**Comment by Jay2113** [comment]
@lukaszbodziony1 I am glad to hear that you were able to successfully connect your custom domain to your Amplify app.

> how can I set subdomain for my domain as a wildcard on amplify side?

Currently, we do not support wildcard subdomains and are tracking it as a feature request here: https://github.com/aws-amplify/amplify-hosting/issues/44.

I'd highly recommend you to upvote it and comment on it with your use case.
