### ISSUE TITLE
Domain activation getting failed with Hostinger

### ISSUE THREAD

**Issue by Tejasviohlan** [aws-amplify/amplify-hosting#3644]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

ap-south-1

### Step

Domain activation

### Status

Failed

### Issue or question

Trying to add custom domain to AWS amplify

### Error message

Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below.
Error message: At least one of your domains has a CAA record that does not include Amazon as an approved Certificate Authority. Please add an entry to your CAA DNS record like the following: [0 issue "amazontrust.com"], so that we can provision an SSL certificate for your domain. To learn more, visit https://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-caa.html

**Comment by ggalmeida0** [comment]
+1 Also getting this error.
I can verify the CAA record is there by doing `dig +short CAA mydomain.com`
I see `0 issue "amazontrust.com"` being returned. But error still shows up
