### ISSUE TITLE
Next.js image optimization 404 when deployed to Amplify

### ISSUE THREAD

**Issue by Appacy** [aws-amplify/amplify-hosting#3645]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d32v9f6td84iz

### AWS Region

eu-west-2

### Amplify Hosting feature

Frontend builds, SSR

### Frontend framework

Next.js

### Next.js version

13.4.13

### Next.js router

App Router

### Describe the bug

When deploying a simple Next.js project to Amplify, any usage of the "Image" component that uses the image optimization API returns 404. This is using an image hosted in the "/public" dir.

Turning off image optimization, therefore serving the image as-is, is OK.

### Expected behavior

The optimized image to be served correctly.

### Reproduction steps

1. Create a Next.js app using `npx create-next-app@latest` with default settings.
2. Run `amplify init` with default settings. I have not added any backend resources.
3. Add a `*.png` image to the `/public` folder and display using the Next.js `Image` component.
4. Publish to Github and connect branch to Ampify.
5. Deploy.

All using default build settings.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

App: https://master.d32v9f6td84iz.amplifyapp.com/
Src: https://github.com/Appacy/test-nextjs
Image that is returning 404: https://master.d32v9f6td84iz.amplifyapp.com/_next/image?url=%2Fno-image.png&w=128&q=75

**Comment by terrymun** [comment]
Related to #3641

**Comment by Jay2113** [comment]
Hi @Appacy 👋 , thanks for raising this!

Can you try downgrading your Next.js version to v13.4.12 to see if that mitigates this issue? Please let us know how it goes.

**Comment by Appacy** [comment]
Hi @Jay2113 

Thanks for the reply.

I downgraded the test project referenced here to Next.js v13.4.12 and all is well.

However, I did run into issues with the project I noticed the issue with initially. Changing the Next.js version in `package.json`, removing `node_modules` and `package-lock.json`, and then running `npm install` didn't work. When I looked in the `package-lock.json`, the `node_modules/@next/env` etc. referenced version 13.4.15. Not sure why that is. Only when I ran `npm i next@13.4.12` before installing the other packages did the version change to 13.4.12 and resolved the issue.

Anyway it seems to be working OK on v13.4.12.

Thanks

Richard

**Comment by ArianHamdi** [comment]
Same here.
Still getting 404 on 13.4.16

**Comment by Jay2113** [comment]
@ArianHamdi Please try to downgrade your Next.js version to v13.4.12.

**Comment by Jay2113** [comment]
Hi everyone 👋 , thanks for your continued patience.

We have identified this as a bug on our end and are actively working on a fix to support newer Next.js versions.

I am going to close this thread in favor of https://github.com/aws-amplify/amplify-hosting/issues/3641 to keep all the communication in the same place.
