### ISSUE TITLE
AWS Amplify "Save and Deploy" keeps on loading.

### ISSUE THREAD

**Issue by jap-gln** [aws-amplify/amplify-hosting#3646]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

ap-south-1

### Step

App Deployment

### Status

Failed

### Issue or question

 I am trying to deploy my react-app via GitHub. But AWS Amplify "Save and Deploy" keeps on loading.

"Houston, there's a problem
We are unable to process your request. Please reach out to your support representative."

Get the following above error. What seems to be the issue for AWS Amplify.

### Error message

Houston, there's a problem
We are unable to process your request. Please reach out to your support representative.

**Comment by Jay2113** [comment]
Hi @jap-gln 👋 , thanks for raising this with us.

Can you please share your AWS Account ID (where you observing this exception) privately via a DM on our [community discord server](https://discord.gg/amplify)? My username is `Jay Raval`.

**Comment by Jay2113** [comment]
@jap-gln As discussed on Discord, in order to further troubleshoot your issue, please reach out to the AWS Support team: https://aws.amazon.com/support for additional assistance.

Thank you!
