### ISSUE TITLE
aws amplify start-deployment  [INFO]: Updating Edge config [ERROR]: Failed to deploy

### ISSUE THREAD

**Issue by dsws** [aws-amplify/amplify-hosting#3648]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2fgeigcv30gsb

### AWS Region

us-east-2

### Amplify Hosting feature

Deployments

### Frontend framework

Gatsby

### Next.js version

Gatsby CLI version: 5.3.1, Gatsby version: 5.8.1

### Next.js router

N/A

### Describe the bug

When I manually upload my zip file to the Choose files feature the deployment works.

But when I upload from the command, it fails for me...which makes no sense because the dist zip is the same

aws amplify start-deployment --app-id d2fgeigcv30gsb --branch-name dev --source-url https://[MASKED].s3.us-east-2.amazonaws.com/public/artifacts/dist.zip

 https://us-east-2.console.aws.amazon.com/amplify/home?region=us-east-2#/d2fgeigcv30gsb

### Expected behavior

For the deployment to work same as when using the AWS Amplify UI. Amplify logs to be better at telling me what failed? Why?

### Reproduction steps

Build:
  before_script:
    - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
    - apt-get install -y nodejs
    - node -v
    - echo "JOB_ID=$CI_JOB_ID" > build.env
    - npm i yarn gatsby -g
    - gatsby info
    - yarn config set cache-folder .yarn
    - yarn --frozen-lockfile
  script:
    - yarn run build
    - cd public
    - zip -r dist.zip .
    - aws s3 cp dist.zip s3://[MASKED]/public/artifacts/
  artifacts:
    paths:
      - dist.zip
    reports:
      dotenv: build.env

Deploy:
  variables:
    APP_ID: d2fgeigcv30gsb
    BRANCH_NAME: dev
    SOURCE_URL: https://[MASKED].s3.us-east-2.amazonaws.com/public/artifacts/dist.zip
  script:
    - echo $SOURCE_URL
    - aws amplify start-deployment --app-id $APP_ID --branch-name $BRANCH_NAME --source-url $SOURCE_URL
  needs:
    - Build

### Log output

<details>

```
....
2023-08-15T16:04:22 [INFO]: Deploying listing/Ex3ZO9x4pRtZUInJTIrjK/index.html
2023-08-15T16:04:22 [INFO]: Deploying listing/FPgL9SkeSPZV2GQ4YSXS5/index.html
2023-08-15T16:04:22 [INFO]: Deploying listing/CvWBSB8GVbQCWp0HM14DG/index.html
2023-08-15T16:04:23 [INFO]: Deploying listing/-92QVDQQfqYp2RhdFna83/index.html
2023-08-15T16:04:23 [INFO]: Skipping deploy of existing file component---src-pages-blog-js-35a75ee67d4b8122faea.js.map
2023-08-15T16:04:23 [INFO]: Skipping deploy of existing file boat-photo-2.png
2023-08-15T16:04:23 [INFO]: Updating Edge config
2023-08-15T16:04:23 [ERROR]: Failed to deploy


```

</details>

**Comment by johnenderson** [comment]
It is the same problem that I faced in the us-east-1 region, and below are the related issues:
https://github.com/aws-amplify/amplify-hosting/issues/3500
https://github.com/aws-amplify/amplify-hosting/issues/3638

**Comment by johnenderson** [comment]
In my case, I resolved the issue by migrating from us-east-1 to us-east-2, which allowed me to successfully deploy the package. However, this required a modification in my CI/CD configuration, and I still need to adjust the DNS settings. But I am concerned about making these changes and then encountering problems again.

**Comment by dsws** [comment]
So i'm actually in us-east-2, but after some more attempts I think the issue got resolved. I did notice that I tried to upload zips that had no changes in them, the amplify deploy log was saying skipping on all the files. Maybe this somehow tripped up the project deployment. Now it seems to work... hopefully it's consistent going forward. I was writing this blog about it incase someone needs help with deploying from GitLab

https://medium.com/@webcore1/deploying-amplify-front-end-project-form-private-gitlab-project-gatsbyjs-2257d514a632

**Comment by dsws** [comment]
Nevermind, pipeline just failed again :( Amplify can you guys fix this please it's really bad. Or give some better feedback to why it's failing? How can I fix something with error of:

2023-08-17T14:12:52 [INFO]: Updating Edge config
2023-08-17T14:12:52 [ERROR]: Failed to deploy

**Comment by dsws** [comment]
@johnenderson and others...  it works if you just pass the s3:// url as --source-url

So don't waste your time with public http urls.

- aws amplify start-deployment --app-id $APP_ID --branch-name $BRANCH_NAME --source-url $SOURCE_URL

You might need to get the right permissions for the CI image.

Currently my bucket policy has all the read Actions for s3 and ListBucket

**Comment by Jay2113** [comment]
Hi @dsws 👋 , thanks for raising this with us!

We are aware of this issue as stated here: https://github.com/aws-amplify/amplify-hosting/issues/3500#issuecomment-1574058486.

The source URL can be any HTTP GET URL that is publicly accessible and downloads a single .zip file: https://docs.aws.amazon.com/amplify/latest/APIReference/API_StartDeployment.html

I am going to close this thread in favor of https://github.com/aws-amplify/amplify-hosting/issues/3500 to keep all the communication in the same place and to make it easier for tracking purposes.
