### ISSUE TITLE
AWS amplify deployment issue

### ISSUE THREAD

**Issue by WebGuru1228** [aws-amplify/amplify-hosting#3654]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-1

### Amplify Hosting feature

Build settings, Deployments, Environment variables, Monorepo

### Frontend framework

React

### Next.js version

16.8

### Next.js router

Pages Router

### Describe the bug

![image](https://github.com/aws-amplify/amplify-hosting/assets/124536260/036b6ee1-2fb3-439e-b36b-d8303e9d5197)
I can't passed this step and our app was not built.

### Expected behavior

I want to deploy code changes to AWS amplify.

### Reproduction steps

![image](https://github.com/aws-amplify/amplify-hosting/assets/124536260/8fbf91f5-c3a8-4848-95f5-c36d347c5230)

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Jay2113** [comment]
Hi @WebGuru1228 👋 , thanks for raising this with us.

Can you please share your AWS Account ID (where you observing this exception) privately via a DM on our [community discord server](https://discord.gg/amplify)? My username is `Jay Raval`.

**Comment by suleman1220** [comment]
@Jay2113 I am having the same issue with my aws amplify deployment. Sometimes it gets stuck at provision and some other times at cloning repo step in build. I have tried reconnecting the repo but still having the same issue.

**Comment by Jay2113** [comment]
@suleman1220 Can you also share your AWS Account ID (where you observing this exception) privately via a DM on our [community discord server](https://discord.gg/amplify)? My username is `Jay Raval`.

**Comment by zuhaib10** [comment]
https://github.com/aws-amplify/amplify-hosting/issues/2581#issuecomment-1686864081

**Comment by Jay2113** [comment]
I am going to close this thread as we are tracking @zuhaib10 's issue separately [here](https://github.com/aws-amplify/amplify-hosting/issues/2581#issuecomment-1686864081).
