### ISSUE TITLE
NextJS 13.4.12 - Issue when including more than one handler in api route

### ISSUE THREAD

**Issue by baskeyx** [aws-amplify/amplify-hosting#3655]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d958wox4bf0gy

### AWS Region

eu-west-1

### Amplify Hosting feature

Deployments

### Frontend framework

Next.js

### Next.js version

13.4.12 

### Next.js router

App Router

### Describe the bug

I've been having issues when adding multiple handlers into an api route in Next JS 13.

Next JS 13 requires that you provide the name of the handler(s) as below:

```
export async function GET () {
  const { DYNAMODB_IMPACT_AREAS } = process.env
  const { Items } = await dynamoDb(DYNAMODB_IMPACT_AREAS).scan({})
  if (!Items) NextResponse.json({ test: false })
  return NextResponse.json({ impacts: Items })
}

// export async function POST () {
//   return NextResponse.json({ test: true })
// }

// export async function PATCH () {
//   return NextResponse.json({ test: true })
// }

// export async function DELETE () {
//   return NextResponse.json({ test: true })
// }
```

This version works, however if I uncomment out the rest of the handlers the route endpoint does not work, even the GET request does not work

### Expected behavior

You should be able to access the GET query when viewing this in the browser regardless of whether there are multiple handlers or not

https://main.d958wox4bf0gy.amplifyapp.com/api/impacts

### Reproduction steps

Go to https://main.d958wox4bf0gy.amplifyapp.com/api/impacts and see that route is broken

### Log output

<details>

```
# Put your logs below this line


2023-08-17 | 08:42:39 | LHR61-C1 | 194 | 51.186.92.104 | GET | d958wox4bf0gy.cloudfront.net | /api/impacts | 500 | - | Mozilla/5.0%20\(Macintosh;%20Intel%20Mac%20OS%20X%2010_15_7)%20AppleWebKit/537.36%20\(KHTML%20like%20Gecko)%20Chrome/115.0.0.0%20Safari/537.36 | - | - | Error | tPbnpsncRAED6oWnYTcIQIjVNvRKVQzwqRlZYRDvX_JdN_B7GsIj9A\=\= | main.d958wox4bf0gy.amplifyapp.com | https | 36 | 8.933 | - | TLSv1.3 | TLS_AES_128_GCM_SHA256 | Error | HTTP/2.0 | - | - | 57576 | 8.933 | OriginError | - | 0 | - | -
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --



2023-08-17	08:42:39	LHR61-C1	194	51.186.92.104	GET	[d958wox4bf0gy.cloudfront.net](http://d958wox4bf0gy.cloudfront.net/)	/api/impacts	500	-	Mozilla/5.0%20\(Macintosh;%20Intel%20Mac%20OS%20X%2010_15_7)%20AppleWebKit/537.36%20\(KHTML%20like%20Gecko)%20Chrome/115.0.0.0%20Safari/537.36	-	-	Error	tPbnpsncRAED6oWnYTcIQIjVNvRKVQzwqRlZYRDvX_JdN_B7GsIj9A\=\=	[main.d958wox4bf0gy.amplifyapp.com](http://main.d958wox4bf0gy.amplifyapp.com/)	https	36	8.933	-	TLSv1.3	TLS_AES_128_GCM_SHA256	Error	HTTP/2.0	-	-	57576	8.933	OriginError	-	0	-	-

``` 

</details>

**Comment by Jay2113** [comment]
Hi @baskeyx 👋 , thanks for raising this with us! 

I wasn't able to reproduce this behavior with Next.js version 13.4.12. Here is the `route.js` file that I used for testing purposes:
```
import { headers } from 'next/headers'
import { NextResponse } from 'next/server'
 
export async function GET(request) {
  const headersList = headers()
  const referer = headersList.get('referer')
 
  return new Response('Hello, Next.js!', {
    status: 200,
    headers: { referer: referer },
  })
}

export async function POST () {
    return NextResponse.json({ test: true })
}
  
export async function PATCH () {
    return NextResponse.json({ test: true })
}
  
export async function DELETE () {
    return NextResponse.json({ test: true })
}
```

Additionally, I tested it as follows:
```
curl https://main.d2kcqri7zze2uz.amplifyapp.com/api/test

curl -X POST https://main.d2kcqri7zze2uz.amplifyapp.com/api/test -d "key=value"

curl -X PATCH https://main.d2kcqri7zze2uz.amplifyapp.com/api/test -d "key=1"

curl -X DELETE https://main.d2kcqri7zze2uz.amplifyapp.com/api/test
```

You may want to review your Hosting Compute logs for this API route to check for any errors.
