### ISSUE TITLE
Custom domain in godaddy.  I setup the cname records, and independently verified that they return the correct values. value, using a couple of third party tools. I have tried 3 times, but stuck in the domain activation state.

### ISSUE THREAD

**Issue by bssitton** [aws-amplify/amplify-hosting#3659]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-1:630501542430:apps/d1r9jcqmrg0bok

### Region

us-east-1

### Step

Domain Activation

### Status

Never finishes

### Issue or question

It failed twice.  The first time I think I had one of the names wrong in the cname record (prod instead on main or something like that).  I corrected it.

I did a lookup from what's my dns.com
https://compete.highschoolbbqleague.com
returns
main.d1r9jcqmrg0bok.amplifyapp.com
I open main.d1r9jcqmrg0bok.amplifyapp.com  in a web browser and it opens the correct site.
compete.highschoolbbqleague.com also opens the correct site, but it will stop when Domain Activation times out.

I did a lookup from what's my dns.com
https://test.highschoolbbqleague.com
returns
dev.d1r9jcqmrg0bok.amplifyapp.com
I opened dev.d1r9jcqmrg0bok.amplifyapp.com in a web browser, and it opens the correct site.
https://test.highschoolbbqleague.com also opens the correct site, but it will stop when Domain Activation times out.

### Error message

Domain activation times out, when I'm only adding subdomains.

**Comment by Jay2113** [comment]
Hi @bssitton 👋 , thanks for raising this!

I observed that the domain activation process has failed to complete on your Amplify app `d1r9jcqmrg0bok`. Are you observing any specific errors in the Amplify Console?

Please refer to this troubleshooting guide related to custom domains as it outlines common scenarios and resolution steps for them: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
