### ISSUE TITLE
Unable to add Rewrites and redirects

### ISSUE THREAD

**Issue by parvusville** [aws-amplify/amplify-hosting#3660]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

depru07ul0a6v

### AWS Region

eu-west-1

### Amplify Hosting feature

Redirects

### Frontend framework

React

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

I am trying to add basic SPA redirect (https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa) into my app in the Amplify hosting console, but every time I try to "Save" nothing happens. The "Updating app:.." flashes by really quickly, and my new rule does not appear to the list on Rewrites and redirects. Based on what I see in my app when refreshing on a routed page, it really does not get added as I see an "AccessDenied" XML-thingy. 

I also tried a basic http -> https redirect, same result. 

### Expected behavior

Adding redirects should work. 

### Reproduction steps

1. Go to Rewrites and redirects page of Amplify console
2. Try to add the example rule: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa
3. Save
4. The new rule does not appear in the listing. 

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Jay2113** [comment]
Hi @parvusville 👋 , thanks for raising this!

I am unable to reproduce this behavior across different AWS regions. Can you confirm if you are actively able to reproduce it?

I observed that your Amplify app `depru07ul0a6v` has a single redirect rule setup as follows:
```
Source: http://urent.orhi.fi
Destination: https://urent.orhi.fi
Type: 302 (Temporary Redirect)
```

Can you try to delete it and then retry? Please let us know how it goes.

**Comment by parvusville** [comment]
Hello @Jay2113. I was able to remove the existing rule, but I am not able to add it back. Please help. :D

**Comment by parvusville** [comment]
Someone in the Discord figured it out, it was because of the existing redirect rule containing a "http" source. Pasting his comment from Discord:

> I figured it out: this should be more clear to a user but in the console I found an error that shows during an API call "{
  "message" : "HTTP URLs cannot be used as source in custom rules. Use HTTPS instead."
}"  This should show on the UI to let the user know.  I had source URLs that were HTTP that have been in there for months, so something must have changed. But it is working now after removing those URLs.

It seems that the http -> https redirect is default behavior on Amplify hosting, and that old rule is no longer needed.
