### ISSUE TITLE
Project is working fine on server but getting blank page in Amplify.

### ISSUE THREAD

**Issue by aniruddha-kulkarni24** [aws-amplify/amplify-hosting#3663]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2qm2bcxzwh970

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Question

i am building the application in ec2 and deploying in pm2 so its working and when hit an ip addres on 3000 port its working fine but same project if i am deploying on aws amplify so its building and deploying successfully but when i hit url blank page opens and when i inspect that and see in console i found below error. Even i tried everything with same node version, node version upgrade and downgrade but didnt worked. 
Uncaught TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at 59970 (index.js:99:17)
    at n (bootstrap:19:32)
    at Toaster.jsx:11:1
    at index.js:12:11
    at index.js:12:11

**Comment by Jay2113** [comment]
Hi @aniruddha-kulkarni24 👋 , thanks for raising this!

While reviewing the build logs for your latest build, I observed errors similar to this:
```
2023-08-22T12:30:06.624Z [INFO]: Failed to parse source map from '/codebuild/output/src2244306856/src/background-check-frontend/node_modules/@metamask/safe-event-emitter/index.ts' file: Error: ENOENT: no such file or directory, open '/codebuild/output/src2244306856/src/background-check-frontend/node_modules/@metamask/safe-event-emitter/index.ts'

Failed to parse source map from '/codebuild/output/src2244306856/src/background-check-frontend/node_modules/@solana/buffer-layout/src/Layout.ts' file: Error: ENOENT: no such file or directory, open '/codebuild/output/src2244306856/src/background-check-frontend/node_modules/@solana/buffer-layout/src/Layout.ts'
```

Have you tried doing a production build of your app locally via `npm run build`?

I also observed that you are doing a force install of the dependencies via `npm install --force` during the `preBuild` phase of the build. Our recommendation is to use `npm ci` which perform a clean install of the dependencies in a CI/CD environment.

**Comment by aniruddha-kulkarni24** [comment]
Hi @Jay2113 , thanks for reply
I have tried in locally its is building perfectly even in EC2 dedicated server its working fine. first i have tried with npm ci but same issue was so i have tried with npm install forcefully.

**Comment by Jay2113** [comment]
Can you try the steps stated here: https://github.com/paulmillr/noble-ed25519/issues/23#issuecomment-1109248320?
