### ISSUE TITLE
App stuck in provisioning state

### ISSUE THREAD

**Issue by Jeerjmin** [aws-amplify/amplify-hosting#3665]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dycnq68vjlzt9

### AWS Region

eu-north-1

### Amplify Hosting feature

Frontend builds

### Frontend framework

React

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

My application worked and deployed well for the last month, but today when I made changes in the repository, the deployment stuck at the provisioning stage.

Also, I did try create new app and deploy it, but no success, It was also stucked after click "Save and deploy"

### Expected behavior

I expected rebuild and redeploy app in 3-5 minuts as usual.

### Reproduction steps

Redeploy the last working build version = Build 21 on appId = dycnq68vjlzt9 with branch = master

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Jay2113** [comment]
Hi @Jeerjmin 👋 , thanks for raising this!

In order to further troubleshoot your issue, please reach out to the AWS Support team: https://aws.amazon.com/support for additional assistance.

Thank you.
