### ISSUE TITLE
Cold start taking 10-12 seconds to render static page

### ISSUE THREAD

**Issue by borisyordanov** [aws-amplify/amplify-hosting#3667]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1cj5rx5g2zj4w

### AWS Region

eu-central-1

### Amplify Hosting feature

Not Applicable

### Frontend framework

Next.js

### Next.js version

13.2

### Next.js router

Pages Router

### Describe the bug

Reopening https://github.com/aws-amplify/amplify-hosting/issues/3211 because there doesn't seem to have been any performance improvements since the issue was closed. I just measured a 16s load time on a cold app.

![image](https://github.com/aws-amplify/amplify-hosting/assets/12392666/1eb9b40f-2813-47c6-b638-b90115e2c4d4)

Customer support has responded with something along the lines of "the AWS Amplify service team is continuously working to improve the performance". I don't doubt that's the case, but this effort has not yet yielded meaningful results.

Considering that [slow load times have an effect on bounce rates](https://www.thinkwithgoogle.com/marketing-strategies/app-and-mobile/mobile-page-speed-new-industry-benchmarks-load-time-vs-bounce/) and therefore our profits, this issue should be treated with the highest possible priority.

The health check hack discussed in the previous issue is not a valid workaround, since [it only helps keep 1 instance alive](https://github.com/aws-amplify/amplify-hosting/issues/3211#issuecomment-1575558794).

Considering there are no solutions or workarounds, it's no surprise that several users have reported abandoning Amplify altogether:
- https://github.com/aws-amplify/amplify-hosting/issues/3211#issuecomment-1405621346
- https://github.com/aws-amplify/amplify-hosting/issues/3211#issuecomment-1406737862
- https://github.com/aws-amplify/amplify-hosting/issues/3211#issuecomment-1416772618

### Expected behavior

Pages should load under 400ms

> Research indicates that website users are likely to leave if it takes more than 400 milliseconds – the blink of an eye — to load.

https://www.browserstack.com/guide/how-fast-should-a-website-load

### Reproduction steps

Open an app after a deployment or after it's fallen asleep

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Jay2113** [comment]
Hi @borisyordanov 👋 , thanks for raising this with us and sorry to hear that you are running into this issue.

Please rest assured that we are investigating into it and will keep you posted with any updates.

**Comment by borisyordanov** [comment]
Some extra information - in my production env I have performance mode enabled. I set up an API test in Datadog that pings my /heath-check endpoint every 10 mins. Response time is consistently ~15s. Both the test and my app are hosted in Frankfurt.

![image](https://github.com/aws-amplify/amplify-hosting/assets/12392666/a01e7ead-3fc3-4f60-bd1c-7679df556b07)

This endpoint has no imports or logic, it just returns a response. So the issue definitely isn't related to dependencies etc.

```
export default function handler(_req, res) {
  res.status(200).json({ status: 'ok' });
}
```

**Comment by alanzdr** [comment]
I've been trying to improve amplify's performance for a few days now, and my biggest problem has been the cloudfront caching system. And apparently, it creates a cache based on the cookies saved in the browser, which means that systems that regularly save different cookies for each user create different caches, causing the site to have the same behavior as if it had never been cached.
https://github.com/aws-amplify/amplify-hosting/issues/2243

The best solution I found so far was to manually write the headers, to force the cloudfront cache:
![image](https://github.com/aws-amplify/amplify-hosting/assets/44515081/c78e11d5-ddf4-4e71-9270-8d464c70e8af)

And then, I developed a script, to set the page as a priority loading, which basically creates a middleware for saving cookies.
https://github.com/alanzdr/storage-cookies

This solved it for me, but in my case, I didn't need to deal with dynamic pages, which cannot store cache, nor deal with authentication or other things that need to use cookies.
![image](https://github.com/aws-amplify/amplify-hosting/assets/44515081/3e9055a7-74b1-402f-8548-3506818c337e)
Maybe in other cases this won't solve it.

**Comment by p1l3** [comment]
hey @Jay2113 any news? i'm having the same problem. i've configured healthcheck, but the response time is still high.

**Comment by Rihyx** [comment]
Having the same issue. Let's wait until they close this issue again without fixing it.

**Comment by mauerbac** [comment]
Hey everyone -- we've examined app performance across the board and don't see holistic issues that would contribute to slow starts/time to first byte. There are many factors at play and it is more effective to examine each app on a case by case basis to identify potential issues. If you are still experiencing this issue, please open a AWS Support case or ask in our [Community Discord server ](www.discord.gg/amplify)
