### ISSUE TITLE
Default AWS generated URL displays SSL error

### ISSUE THREAD

**Issue by tjforeman** [aws-amplify/amplify-hosting#3668]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dr9xhq8757761

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Frontend framework

React

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

When connecting to default aws generated url: https://main.dr9xhq8757761.amplifyapp.com/ the following error occurs: 

This site can’t provide a secure connectionmain.dr9xhq8757761.amplifyapp.com sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

This is only happening on the main branch, all other branches work as expected. 

### Expected behavior

The app to have SSL and no security errors

### Reproduction steps

1. Navigate to https://main.dr9xhq8757761.amplifyapp.com/
2. See error

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Jay2113** [comment]
Hi @tjforeman 👋 , thanks for raising this!

I wasn't able to observe the `ERR_SSL_PROTOCOL_ERROR` when resolving your website https://main.dr9xhq8757761.amplifyapp.com/.

It seems that it is returning a blank page since a 404 is returned from this endpoint: https://listingsmanager-staging.thryv.com/api/mc/user-check/undefined.

Are you still running into this issue?
