### ISSUE TITLE
There is a cache somewhere that prevent changes in existing js files to be displayed

### ISSUE THREAD

**Issue by tipgo** [aws-amplify/amplify-hosting#3672]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

tipgov2

### AWS Region

ca-central-1

### Amplify Hosting feature

Frontend builds

### Question

js file is

export const PROVINCES = {
  "ab":  "ab",
  "bc":  "bc",
  "on":  "on",
  "qc":  "qc"
};

running locally has no issue

After publish

export const PROVINCES = {
  "qc":  "qc",
  "on":  "on",
  "bc":  "bc"
};

published multiple times for 2 days, changes not reflected cloud front cache needs to be invalidated

**Comment by tipgo** [comment]
Forgot to mention

this happened after those commands

amplify publish
amplify publish -c
amplify publish --invalidateCloudFront

**Comment by tipgo** [comment]
this is a blocker for a production application. Any tips or recommendation ?

**Comment by Jay2113** [comment]
Closing this thread in favor of https://github.com/aws-amplify/amplify-hosting/issues/3673 to keep all the communication in the same place.
