### ISSUE TITLE
Cache / CF invalidation not working

### ISSUE THREAD

**Issue by tipgo** [aws-amplify/amplify-hosting#3673]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

tipgov2

### AWS Region

ca-central-1

### Amplify Hosting feature

Not Applicable

### Frontend framework

React

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

Amplify environment produces

Change my files (jsx)

npm I
nom start

See may pages connected to produce backend

amplify publish -c

Launch my application

Old content is displayed

### Expected behavior

Simply see my changes after a publish as if invalidation does not happen

### Reproduction steps

amplify publish -c

Open my app

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Jay2113** [comment]
Hi @tipgo 👋 , thanks for raising this!

I am unable to reproduce this behavior using the following workflow:

- npx create-react-app
- amplify init
- amplify add hosting
  - select manual deployments
- amplify publish

Are you still running into this behavior? If yes, can you share your Amplify App ID?
