### ISSUE TITLE
amplify to amplify app redirect 502 error

### ISSUE THREAD

**Issue by april21dev** [aws-amplify/amplify-hosting#3674]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dgshdm0aubfq3, d1vlzhjkb9uddb

### AWS Region

ap-northeast-2

### Amplify Hosting feature

Redirects

### Question

I have two amplify apps.
A: React web application
B: Next.js web application

A: domain: www.example.com
B: domain: www.blog.example.com

I don't want to use blog.exmaple.com subdomain for SEO.
I want to use subdirectory for my blog like www.example.com/blog
So, I configured A's redirect to B
Like below

[A's redirection rules]

/blog<*>   ==>   https://www.blog.example.com/<*>   200
/blog    =>   https://www.blog.example.com    200
https://example.com   =>   https://www.example.com
/<*>   =>   /index.html
</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>   =>   /index.html

top two rules are for redirection to B application

but, when I type https://www.example.com/blog in the web browser, It returns

```
502 ERROR
The request could not be satisfied.
The Lambda function returned an invalid origin configuration: One or more HeaderName or HeaderValue values are invalid. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: 08xGvfAymrXECVwvOGcC48uJw0UE2qQvvhrgQ4Y-iklX3rkaJ0H77w==
```

How to solve this?

**Comment by Jay2113** [comment]
Hi @april21dev 👋 , thanks for raising this!

I was unable to reproduce the behavior outlined with reverse proxy rewrites. I tested as follows:
- App A: React -> v1.example.com
- App B: Next.js -> blog.v1.example.com

The Reverse Proxy Rewrite was setup as follows:
```
  {
        "source": "/blog",
        "target": "https://blog.v1.example.com/blog",
        "status": "200",
        "condition": null
  },
  {
        "source": "/blog/<*>",
        "target": "https://blog.v1.example.com/blog/<*>",
        "status": "200",
        "condition": null
  }
```

Are you able to actively reproduce the 502 error?
