### ISSUE TITLE
Can not create new environment when adding New App (Host Web App)

### ISSUE THREAD

**Issue by bergmorten** [aws-amplify/amplify-hosting#3685]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d34x9npy2tqygn 

### AWS Region

ca-central-1

### Amplify Hosting feature

Backend environments

### Frontend framework

Vue

### Next.js version

Does not use Next

### Next.js router

N/A

### Describe the bug

I want to add a App and create a new backend environment which are not shared with other apps connected to the same branch. 

In build settings I select `create new environment` and fill in name `wcscanada` both for app name and environment. Do not know why the pull down of App name does not reflect the app-name given (possible another bug).
<img width="989" alt="buildSettings" src="https://github.com/aws-amplify/amplify-hosting/assets/86950981/872c3df2-067a-45b7-8a53-b75975b5832b">

Summary seems ok:
<img width="801" alt="summary" src="https://github.com/aws-amplify/amplify-hosting/assets/86950981/69ddf437-6b9c-457f-a42d-bea814e0da0c">

But the when I deploy it try to create an environment with the same name as the branch name (template). 
<img width="1002" alt="resulting-name" src="https://github.com/aws-amplify/amplify-hosting/assets/86950981/6fade0ba-a70b-4c76-9b87-dde833a2769d">

One of the errors:
<img width="907" alt="error" src="https://github.com/aws-amplify/amplify-hosting/assets/86950981/7eba7492-2872-412f-aa1b-2359f8e8d54d">

I my setup this does not work since I need to have separate environment per app.

## Need also help to clean this up.
I tried first to deploy this app in another region where I also another app with this backend environment. However if I try to delete this app it will also delete the environment of the existing app. How do I delete an app and keep the environment?
See app id `d38c3xshp5shlw`  and `d3h2imtpur0g0t`  in `region us-east-1`

### Expected behavior

Create app easy with separate environment so that database, Cognito and roles are unique.

### Reproduction steps

1. Create new app - web hosted
2. Connect to git hub and a branch
3. Under build setting set `Create new environment` with a name other than the branch name
4. Should create this environment, but is does not. It use the branch name

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Jay2113** [comment]
Hi @bergmorten 👋 , thanks for raising this and for providing detailed reproduction steps.

The behavior outlined in this issue seems related to #3745. Please refer to my comment here: https://github.com/aws-amplify/amplify-hosting/issues/3745#issuecomment-1754139394 which outlines a workaround to use the `USER_BRANCH` environment variable.

Closing this to keep all the communication in the same place. Please track #3745 for any further updates.
