### ISSUE TITLE
Getting Rate exceeded while calling CreateDomainAssociation, please slow down or try again later.

### ISSUE THREAD

**Issue by ysunil702** [aws-amplify/amplify-hosting#3688]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2sjwlavncc14i

### Region

N. verginia

### Step

create custom domain using api in amplify

### Status

bad request

### Issue or question

Kindly look into the following screenshot https://prnt.sc/4ftLFZr6VOWT. I am getting an exception Rate exceeded while calling CreateDomainAssociation, please slow down or try again later.

Code snippet
var responseCert = await amplifyClient.CreateDomainAssociationAsync(new Amazon.Amplify.Model.CreateDomainAssociationRequest
                    {
                        DomainName = customDomain,
                        AppId = amplif_app_id,
                        SubDomainSettings = new List<Amazon.Amplify.Model.SubDomainSetting>
                        {
                            new Amazon.Amplify.Model.SubDomainSetting
                            {
                                BranchName = branchName,
                                Prefix = ""
                            }
                        }
                    });

How many calls are allowed for this API endpoint?

### Error message

The rate exceeded while calling CreateDomainAssociation, please slow down or try again later.

### Additional information

error screenshot https://prnt.sc/4ftLFZr6VOWT

**Comment by Jay2113** [comment]
Hi @ysunil702 👋 , thanks for raising this!

We currently have a rate limit on the CreateDomainAssociation API of 10 per hour. This is a hard limit and you will have to wait until the hour mark before trying again.

**Comment by ysunil702** [comment]
Thank you for your prompt reply.
