### ISSUE TITLE
Next.js API routes are cached by cloudfront

### ISSUE THREAD

**Issue by markus-mw** [aws-amplify/amplify-hosting#3689]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3jneonuggifo0

### AWS Region

eu-central-1

### Amplify Hosting feature

Custom headers, Public APIs, SSR

### Question

Hi all!

I recognized that requests to an Next.js API route are cached for 2 seconds. In between I get an X-Cache Header "Hit from cloudfront". Is there a way to change this behaviour? 
In my local environment, I cannot reproduce this behavior. There I always get a freshly generated response.

Thank you
Markus

**Comment by arturkasperek** [comment]
I have the same problem - why it happens?

**Comment by calavera** [comment]
Hi,

This problem has been resolved. CloudFront doesn't cache for 2 seconds anymore, and it will respect the cache-control response header that your api returns.

I'm closing this issue as it's been resolved.
