### ISSUE TITLE
Github webhook is not triggering Amplify Preview builds

### ISSUE THREAD

**Issue by hinaaman** [aws-amplify/amplify-hosting#3690]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1h6e93qbxs4wx

### AWS Region

us-east-1

### Amplify Hosting feature

Web previews

### Frontend framework

React

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

New branches and commits are not triggering Amplify preview builds.

Notes:
- I have tried re-installing Github and reconnecting repo. Did not work.
- The webook payloads look good (status response is 202).
- On the app dashboard, app status section on the top of the page is stuck in loading state. Inspecting the payloads, I see `/AppState?appId=d1h6e93qbxs4wx` errors out with "Requested app was not found".

### Expected behavior

If a new branch is created or a new commit is added, amplify should trigger a preview build.

### Reproduction steps

The issue is specific to the app with id `d1h6e93qbxs4wx`
Creating a new branch or adding a new commit to an existing branch results in a valid webhook call to Amplify but Amplify does not trigger a preview build for that branch.

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Jay2113** [comment]
Hi @hinaaman 👋 , thanks for raising this!

The root cause of this behavior seems related to this GitHub outage where webhooks were impacted: https://www.githubstatus.com/incidents/n8wpsvv7wt6x

They seem to have recovered about 30 mins ago. Can you retry now?

**Comment by hinaaman** [comment]
Thanks for the update, @Jay2113. Preview builds seem to be back up.
