### ISSUE TITLE
hosting app returns with an error: huston we have a problem. 

### ISSUE THREAD

**Issue by thekubilay** [aws-amplify/amplify-hosting#3693]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

ap-northeast-1

### Amplify Hosting feature

Git providers

### Question

I am currently using the basic tier of Amplify, and I've successfully hosted one application using GitHub integration. However, when I attempted to add another application in the same manner, I encountered an issue. Specifically, when I clicked on the "Save and Deploy" button, I received an error message. I took a look at the console logs, which indicated a 401 authorization error. I initially suspected that the issue might be related to the user account I was using for authentication. I even tried using the root user account, but unfortunately, I encountered the same error.

I'm wondering if there might be a limitation associated with the basic tier that is causing this problem, or if there could be another underlying issue causing the 401 authorization error.

**Comment by Jay2113** [comment]
Hi @thekubilay 👋 , thanks for raising this with us.

Can you please share your AWS Account ID (where you observing this exception) privately via a DM on our [community discord server](https://discord.gg/amplify)? My username is `Jay Raval`.

**Comment by Rafaelceid** [comment]
Hello I have the same problem, by trying to add my react app to the amplify via aws gui

**Comment by thekubilay** [comment]
> Hi @thekubilay 👋 , thanks for raising this with us.
> 
> Can you please share your AWS Account ID (where you observing this exception) privately via a DM on our [community discord server](https://discord.gg/amplify)? My username is `Jay Raval`.

I contacted with you on the discord.

**Comment by Jay2113** [comment]
@thekubilay As discussed on discord, in order to further troubleshoot your issue, please reach out to the AWS Support team: https://aws.amazon.com/support for additional assistance.

@Rafaelceid, I'll recommend the same for you too.

Thank you.
