### ISSUE TITLE
Activation error

### ISSUE THREAD

**Issue by FrancescBagur** [aws-amplify/amplify-hosting#3695]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2stmh7s6efztg

### Region

eu-central-1

### Step

Domain activation

### Status

Failed

### Issue or question

**Issue:** CNAMEAlreadyExistsException Error on Domain Transfer

**Error Message:**

[CNAMEAlreadyExistsException] The following CloudFront distributions or Amplify Apps are already using one or more of your domains:

I make all steps that I found in documentation, but got the same error. I think that the problem could be that I transfered the domain to one AWS account to another. But I delete al amplify app I the old account and I saw in CloudFront as I read in the docs but I don't have nothing in the old account and also in the new. So I tried all and it still not work.

To address this, I:

Deleted all Amplify apps associated with the old account.
Checked CloudFront distributions as mentioned in the documentation.
Despite these steps, I found no remaining resources in either the old or new AWS account that could be using the domain. However, the error persists.

I'd appreciate any guidance on resolving this.

### Error message

[CNAMEAlreadyExistsException] The following CloudFront distributions or Amplify Apps are already using one or more of your domains

**Comment by swooner** [comment]
Having the same issue.

**Comment by FrancescBagur** [comment]
Hi @Jay2113 

Is this the correct site for my issue? There is no way I can solve it and I need to put this application into production. I think it is an Amazon problem because I have applications configured the same and they work perfectly, only in this case it does not work and I suppose it is because I transferred the domain from one account to another.

Thank you so much!

**Comment by Jay2113** [comment]
Hi @FrancescBagur 👋 , thanks for raising this and apologies for the delayed response here. It looks like you have successfully connected your domain to the Amplify app `d2stmh7s6efztg`. Are you still running into this issue while connecting any other domain?
