### ISSUE TITLE
Sub Subdomain Activation Error

### ISSUE THREAD

**Issue by mgowland** [aws-amplify/amplify-hosting#3696]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dxyo3wjxvzu9s

### Region

us-west-1

### Step

Domain Activation

### Status

Failed

### Issue or question

I am attempting to set up a subdomain for a domain that is hosted outside of AWS.  I followed the instructions for creating a subdomain found here: 

https://docs.aws.amazon.com/amplify/latest/userguide/to-manage-subdomains.html

When the sub-domain was created, I clicked to **Remove Root**.

Amplify provisioned a CNAME record that was added to the domain DNS.  After the DNS was updated, I clicked **Retry**.  

After the retry attempt, I received an error that the CNAME record in the domain was incorrect and a different CNAME record should be used.  The problem is the CNAME record that I was provided by Amplify is the record that is causing the error.  The "correct" CNAME record is a new CNAME that was seemingly generated at the time of the error.  

![Screenshot 2023-09-08 at 11 35 40 AM](https://github.com/aws-amplify/amplify-hosting/assets/1242957/948ce79f-64d1-4e1b-beab-e18d5bfac6f5)

I have tried updating the CNAME and clicking **Retry** four (4) separate times with the same result.  We do not have a record in Route53 for the root domain.  

### Error message

Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below.

Error message: [CNAMEDNSMisconfiguration] The following domain names include an incorrectly configured DNS record that points to the wrong target URL: [Domain creaturecards.deutschla.com has a CNAME record pointing to d1zffsgtv3088u.cloudfront.net]. The correct target URL was d2ezkbt1ob2gyy.cloudfront.net. Please cleanup any old CNAME records from your DNS entries before adding your domain.

**Comment by Jay2113** [comment]
Hi @mgowland 👋 , thanks for raising this!

It looks like you have successfully connected the custom domain https://creaturecards.deutschla.com to your Amplify app `dxyo3wjxvzu9s` and it also seems to be resolving as expected. Thus, I am going to close this issue but please feel free to create a new issue if you are experiencing any issues with Amplify Hosting.
