### ISSUE TITLE
How to Setup Congito Amplify to link to a Cognito account in another enviroment

### ISSUE THREAD

**Issue by jasontVitac** [aws-amplify/amplify-hosting#3700]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-1

### Amplify Hosting feature

Access control

### Question

Do need to setup a Federated Cognito user pool? So that my AWS Amplify backend project can authenticate against a central Cognito user pool? Or can I just some how connect directly to their user pool? 

https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-social-idp.html

So, I think the flow is...

1) Create a Cognito user pool in my environment.
   a) Can create from scratch
2) Link that user pool to the external environment.
3) Update the Amplify authentication to point to the my environment user pool.

Will this work? Or is there a better/easier solution?

**Comment by Jay2113** [comment]
Hi @jasontVitac 👋, thanks for raising this! 

Can you clarify where you are in the process of implementing Auth or creating your user pool?  Is there a certain section of the docs you’re following from the Amplify side?  Happy to help and get your Authentication up an running!

**Comment by jasontVitac** [comment]
> Hi @jasontVitac 👋, thanks for raising this!
> 
> Can you clarify where you are in the process of implementing Auth or creating your user pool? Is there a certain section of the docs you’re following from the Amplify side? Happy to help and get your Authentication up an running!

Well we have two different ideas...

1) Is to use the existing Amplify Cognito integration and the extend that logic through a Federated Cognito Pool.
   a) Idea is currently on the backburner. 
2) Is to use a S3 bucket and the policy settings to link through an existing ALB that contains the Cognito setup already.
   a) Our current approach. But we can't get it to work. We added the VPC End Point to our S3 bucket and it just gives us a 403 
    error. 
    
I opened up a support ticket through our company account for direction. But still waiting on details. Any help is appreciated!

**Comment by Jay2113** [comment]
@jasontVitac thanks for sharing that information. To better assist you, I would like to understand the following:
- How did you set up the auth resources?
  - Amplify CLI
  - Amplify Studio
  - Cognito console 
- What federated providers are you looking to use?
- Can you elaborate on the 403 errors that you are observing? Do the errors occur when trying to upload and/or download resources?
- Lastly, can you provide us your flow of events?
