### ISSUE TITLE
App creation limit

### ISSUE THREAD

**Issue by pradeepsankar** [aws-amplify/amplify-hosting#3706]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-1

### Amplify Hosting feature

Frontend builds

### Question

![WhatsApp Image 2023-09-15 at 12 49 31](https://github.com/aws-amplify/amplify-hosting/assets/50713763/3d278957-4d8d-43cb-889a-06bd5262e200)

unable to create more than one app

**Comment by Jay2113** [comment]
Hi @pradeepsankar 👋 , thanks for raising this!

You can request an increase in the `Apps` limit by raising an AWS Support case using this link: https://console.aws.amazon.com/servicequotas/home/services/amplify/quotas/L-1BED97F3

Amplify Service Quotas: https://docs.aws.amazon.com/general/latest/gr/amplify.html#service-quotas-amplify
