### ISSUE TITLE
accept-language header is overriden

### ISSUE THREAD

**Issue by SamKomesarook** [aws-amplify/amplify-hosting#3712]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d19oqxloeeub82

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments, Frontend builds

### Frontend framework

Next.js

### Next.js version

13.4.19

### Next.js router

App Router

### Describe the bug

When querying for the accept-language header in a Next.js middleware file, it appears as though AWS is setting the language header to a wildcard, instead of the more specific 

### Expected behavior

The accept-language header should remain as the more accurate selection that the browser makes.

### Reproduction steps

1. Create a NextJS App with a middleware file present.
2. In the middleware file, console log the `request.headers.get("accept-language")` value.
3. Note how when run locally, the header should be set to whatever the browser sets, whereas when run on Amplify, the header is set to a wildcard.

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Jay2113** [comment]
Hi @SamKomesarook 👋 , thanks for raising this! Unfortunately, this is a known limitation with the `accept-language` header and in association with this we are also tracking the support for i18n automatic locale detection feature here: https://github.com/aws-amplify/amplify-hosting/issues/3320.

I am going to close this thread in favor of #3320 .
