### ISSUE TITLE
Out of Service for Deployment

### ISSUE THREAD

**Issue by Coronafintech** [aws-amplify/amplify-hosting#3714]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3kvvzz6imlawd

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Question

I tried deploy simple HTML/JAVA website. Succeeded 1st time, hanged on 2nd try (within 10 minutes from the 1st deployment) since last 6 hours. Unable to deploy any new zip file to direct Amplify Hosting.
The Deployment ZIP file size is around 11 MB.

Any solution to this through CLI?

**Comment by Jay2113** [comment]
Hi @Coronafintech 👋 , thanks for raising this! It looks like your latest deployments on the app `d3kvvzz6imlawd` has succeeded. I'll recommend referring to this [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/main/FAQ.md#manual-deployments) which outlines some potential issues that can occur when performing manual deployments and solutions to mitigate them.
