### ISSUE TITLE
Integration of oswap or jfrog to amplify reactjs application with next.js framework

### ISSUE THREAD

**Issue by pichu1995** [aws-amplify/amplify-hosting#3718]
### Before opening, please confirm:

- [x] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [x] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2jroedicsrin4

### AWS Region

us-west-2

### Amplify Hosting feature

Build settings, Deployments, E2E Cypress tests, SSR

### Question

How can i integrate oswap or jfrog in my amplify application, which should test the vulnerabilities in the packages and dependencies. Which should provide a report of vulnerabilities and stop proceeding the build.

**Comment by Jay2113** [comment]
Hi @pichu1995 👋 , we do not provide an out of the box or native solution for applications such as owasp and jfrog to test package and dependency vulnerabilities. To get started, I'll recommend reviewing their official documentation and/or public GitHub repositories (if any). If you can install these security solutions using a package manager such as `npm`, you can then also install them via `npm install <package>` in the default build container by modifying the build specification `amplify.yml` file.

The default build container provided by Amplify Hosting uses Amazon Linux 2 as its operating system. If these security solutions are not compatible with Amazon Linux 2, you can consider creating your own custom build image and using it with Amplify Hosting: https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup
