### ISSUE TITLE
Connection Timeout even after re-adding custom domains multiple times

### ISSUE THREAD

**Issue by farshidtf** [aws-amplify/amplify-hosting#3720]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2lrt2izq1n5x1

### Region

us-east-1

### Step

N/A all steps have succeeded

### Status

Available

### Issue or question

I have deleted and re-added custom domains multiple times (as suggested in https://github.com/aws-amplify/amplify-hosting/issues/447) and have waited 24 hours in between but I am still getting ERR_CONNECTION_TIMED_OUT when visiting any of my subdomains. As stated above, status for my custom domain is `Available`.

I am using godaddy as my DNS provider and have followed the guide: https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-godaddy.html

**Comment by Jay2113** [comment]
Hi @farshidtf 👋 , thanks for raising this!

Have you verified that the required CNAME records (ACM server validation and CloudFront CNAME records) are still present in your DNS settings in GoDaddy?

Additionally, I observed that your app has 3 redirect rules pointing to `www.<redacted>.com`. Do you intend to use these redirect rules?
- If yes, you will also need to add 3 CNAME records which point to the same CloudFront distribution for the `www.<redacted>.com` URL.
- If no, you can delete these rules and then try to access your custom domain.

Hope this helps!

**Comment by farshidtf** [comment]
@Jay2113 redirect rule was the issue. Thank you for getting back to me
