### ISSUE TITLE
On-Demand ISR Revalidation 

### ISSUE THREAD

**Issue by matteocollina** [aws-amplify/amplify-hosting#3722]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d25o2wcah36k9r

### AWS Region

us-east-1

### Amplify Hosting feature

SSR

### Is your feature request related to a problem? Please describe:

I've created a route `/revalidate` that is accessible with a secret token but On-Demand ISR Revalidation doesn't work as described in the official documentation of Nextjs

### Describe how you'd like this feature to work

I'd like that Amplify hosting worked as described in the official documentation: 
https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration#on-demand-revalidation

**Comment by Jay2113** [comment]
Hi @matteocollina 👋 , thanks for raising this! We are already tracking this as an existing feature request here https://github.com/aws-amplify/amplify-hosting/issues/3116. I'll recommend up-voting and monitoring it for any further updates on the on-demand ISR feature support.

Thus, I am going to close this as a duplicate.
