### ISSUE TITLE
Backend Hosting

### ISSUE THREAD

**Issue by Techking5287** [aws-amplify/amplify-hosting#3728]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-1

### Amplify Hosting feature

Backend builds, Build settings

### Question

I have backend project(Node.js, Express.js, MongoDB)
I'm trying to deploy that but This is not simple for me
So I know everyone is busy but I'm writing now
How to deploy backend project using amplify of aws?

**Comment by Jay2113** [comment]
Hi @Techking5287 👋 , thanks for raising this!

Are you utilizing the Amplify CLI to build your backend? Or are you looking to host your existing backend stack with Amplify CLI and Hosting? Can you share your detailed use case?
