### ISSUE TITLE
Support Codecommit repositories for Amplify Console Previews

### ISSUE THREAD

**Issue by kziemski** [aws-amplify/amplify-hosting#373]
**Is your feature request related to a problem? Please describe.**
I get an error saying Previews are not yet available for AWS CodeCommit repositories.

**Describe the solution you'd like**
Is there an ETA or is there someway that CodeCommit Repo's are insufficient to support this functionality.

**Additional context**
It seems weird that this wasn't supported first.

**Comment by kziemski** [comment]
@Joycehao19  can codecommit get some love?  
i get github is amazing but whats the point of codecommit if AWS developers won't make it great or at least treat it like they would github.
i have all my developers revolting bc we are not using github

**Comment by ben-elsen** [comment]
Is there some update about this request? I would love it as well to have the web previews with our code being in Codecommit.

**Comment by kziemski** [comment]
Has there been any update on timing? i'm tempted to move my repo's out of codecommit

**Comment by kziemski** [comment]
Is there any update on this ?

**Comment by na018** [comment]
we would love to use previews with CodeCommit as well - any updates here?

**Comment by kziemski** [comment]
Guys is there any update for Amplify Previews support for CodeCommit?

**Comment by Kamilius** [comment]
Same question here. Awkward that Amazon is not supporting Previews for its own platform VCS in the first place :( Would be really handy

**Comment by JodiWarren** [comment]
I would like to add a strong +1 for this.

**Comment by slaat** [comment]
it's quite odd that they aren't supporting their own platform...

**Comment by kziemski** [comment]
CodeCommit the neglected child of AWS services

**Comment by yanislavtankov** [comment]
Really keen to see this option soon!!!!

**Comment by Ali-Parandeh** [comment]
Adding another +1 here. Quite surprised CodeCommit which is an AWS product is not supported by another AWS product Amplify

**Comment by kziemski** [comment]
@Ali-Parandeh  This will never happen. I've given up on waiting on this.

**Comment by vidhyasagarj** [comment]
I don't understand why it is too hard to implement for CodeCommit !!.. Now I need to migrate to GitHub just because of this.

**Comment by jatin-faze** [comment]
Guys any luck on this or ETA for the Previews support ?

**Comment by jatin1201** [comment]
Guys any ETA for this?

**Comment by sawravchy** [comment]
Any update on this feature?

**Comment by mauerbac** [comment]
unfortunately, this is not a feature that is currently prioritized or has a ETA

**Comment by mauerbac** [comment]
With code commit being de-emphasized I don't see us working on this. Will close this out

**Comment by kziemski** [comment]
Waiting it out good strategy.  Good Luck
