### ISSUE TITLE
Cloning Repo from Bitbucket failing -- team completely blocked

### ISSUE THREAD

**Issue by djorgji** [aws-amplify/amplify-hosting#3730]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1o1goat7xuf0t

### AWS Region

us-east-1

### Amplify Hosting feature

Backend builds, Deployments

### Frontend framework

React

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

All of sudden earlier today our builds stopped working at the clone repository step.

We did not modify `amplify.yml` or make any other major changes in git, it failed on a small UI update merge.

Even getting the error when clicking `redeploy this version` on a previous successful builds.

We utilize a repository in Bitbucket.

### Expected behavior

Repo clones and build as it did before.

### Reproduction steps

N/A -- Feel free to "redeploy" the latest version on main.

### Build Settings

```yaml
version: 1
backend:
  phases:
    preBuild:
      commands:
        - npm i -g yarn@1.22.10
        - yarn global add typescript
        - amazon-linux-extras enable golang1.11
        - yum clean metadata
        - yum -y install golang jq
        - export GOPROXY=https://proxy.golang.org
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install --frozen-lockfile
    build:
      commands:
        - yarn build --skip-nx-cache
  artifacts:
    baseDirectory: dist/apps/company
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  phases:
    preTest:
      commands:
        - yarn install --frozen-lockfile
        - npx cypress install
    test:
      commands:
        - export COMMIT_INFO_BRANCH="$(git rev-parse HEAD | xargs git name-rev | cut -d' ' -f2 | sed 's/remotes\/origin\///g')"
        - export COMMIT_INFO_MESSAGE="$(git log -1 --pretty=%B)"
        - export COMMIT_INFO_EMAIL="$(git log -1 --pretty=%ae)"
        - export COMMIT_INFO_AUTHOR="$(git log -1 --pretty=%an)"
        - export COMMIT_INFO_SHA="$(git log -1 --pretty=%H)"
        - export COMMIT_INFO_REMOTE="$(git config --get remote.origin.url)"
        - yarn e2e:ci --spec **/signUp.cy*
        - yarn e2e:ci --excludeSpecPattern **/signUp.cy*
    postTest:
      commands:
        - npx mochawesome-merge dist/cypress/apps/company-e2e/mochawesome-report/mochawesome_*.json > dist/cypress/apps/company-e2e/mochawesome-report/mochawesome.json
  artifacts:
    baseDirectory: dist/cypress/apps/company-e2e/
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
2023-09-25T20:13:52.913Z [INFO]: Git SSH Key acquired
2023-09-25T20:13:52.992Z [INFO]: # Cloning repository: git@bitbucket.org:company/company.git
2023-09-25T20:14:08.505Z [INFO]: Agent pid 157
2023-09-25T20:14:08.641Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
                                 Cloning into 'company'...
                                 Warning: Permanently added the ECDSA host key for IP address '18.205.93.1' to the list of known hosts.
2023-09-25T20:14:08.642Z [INFO]: # Switching to commit: d0aa6581da79f039cd1b27ae7f43d49b149cb373
2023-09-25T20:14:08.718Z [INFO]: Agent pid 170
2023-09-25T20:14:08.719Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
                                 Note: switching to 'd0aa6581da79f039cd1b27ae7f43d49b149cb373'.
                                 You are in 'detached HEAD' state. You can look around, make experimental
                                 changes and commit them, and you can discard any commits you make in this
                                 state without impacting any branches by switching back to a branch.
                                 If you want to create a new branch to retain commits you create, you may
                                 do so (now or later) by using -c with the switch command. Example:
                                 git switch -c <new-branch-name>
                                 Or undo this operation with:
                                 git switch -
                                 Turn off this advice by setting config variable advice.detachedHead to false
                                 HEAD is now at d0aa6581 amplify.yml edited online with Bitbucket
2023-09-25T20:14:08.767Z [INFO]: Successfully cleaned up Git credentials
2023-09-25T20:14:08.768Z [INFO]: # Checking for Git submodules at: /codebuild/output/src847317844/src/g2mint/.gitmodules
2023-09-25T20:14:08.795Z [ERROR]: !!! CustomerError: Invalid configuration file found in repository: Unexpected end of JSON input
2023-09-25T20:14:08.795Z [INFO]: # Starting environment caching...
2023-09-25T20:14:08.795Z [INFO]: # Environment caching completed
Terminating logging...


```

</details>

**Comment by Jay2113** [comment]
Hi @djorgji 👋 , it looks like you have a buildSpec `amplify.yml` file in your git repository and the build process is failing as the `amplify.yml` file seems to have some syntax errors. I'll recommend using a yaml linter to ensure the file does not have any syntax errors. Once you have ensured that, you can then redeploy the build.

**Comment by djorgji** [comment]
@Jay2113 I have double checked the `amplify.yml` a few dozen time. I have `reconnected repository`, and disconnected/reconnected the branch, still the same error. When I click `Redeploy this version` on an older fully successful build it still the same error.

I just checked again with a few different validators, and it is they all said the yml is valid.

**Comment by Jay2113** [comment]
@djorgji thanks for confirming that. Based on the `baseDirectory: dist/apps/company` attribute, it seems that you may have your app in a monorepo setup and if that's the case the `amplify.yml` file is missing the `appRoot` attribute: https://docs.aws.amazon.com/amplify/latest/userguide/monorepo-configuration.html#monorepo-yml-syntax

Can you verify the same?

**Comment by djorgji** [comment]
@Jay2113 I noticed there was a `package-lock.json` even though we use yarn, so I deleted it, that seems to have done the trick.

Unsure how it was corrupted, or how it showed up to begin with... neither of which is your problem, so I am closing this. Sorry for the trouble, and thanks for your time!

**Comment by djorgji** [comment]
Resolved closing.
