### ISSUE TITLE
Error: /lib64/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by ccks01** [aws-amplify/amplify-hosting#3735]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16

### Amplify CLI Version

10.6.2

### What operating system are you using?

Amazon Linux:2 default

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Describe the bug

Can not use Cypress anymore. Update to 13.3.0. Gives error in console:

2023-09-28T07:42:15.506Z [INFO]: Error: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /root/.cache/Cypress/13.3.0/Cypress/resources/app/packages/server/lib/modes/addon/addon-native.node)

### Expected behavior

Can use Cypress in build pipeline

### Reproduction steps

install Cypress 13.3.0
run Cypress in build pipeline

### Before submitting, please confirm:

- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by Jay2113** [comment]
Hi @ccks01 👋 , the Cypress team have released a fix for this issue as stated here: https://github.com/cypress-io/cypress/issues/27920#issuecomment-1741318824.

Thus, I am going to close this issue. Thanks!
