### ISSUE TITLE
Houston, there's a problem [error message]

### ISSUE THREAD

**Issue by GoldieClover** [aws-amplify/amplify-hosting#3738]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

manual_deploy

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Question

Hello,

Right now I'm having an issue : 

"Houston, there's a problem
We are unable to process your request. Please reach out to your support representative."

![image](https://github.com/aws-amplify/amplify-hosting/assets/96825231/bb51ca2b-5816-42f9-a2da-eefdd74556e7)

Please help
Thank you

Rgds,

GC

**Comment by Jay2113** [comment]
Hi @GoldieClover 👋 , in order to further troubleshoot your issue, please reach out to the AWS Support team: https://aws.amazon.com/support for additional assistance.

Thanks.
