### ISSUE TITLE
Restricting Direct Access to Amplify App to Ensure Traffic Only Through Cloudflare

### ISSUE THREAD

**Issue by afern247** [aws-amplify/amplify-hosting#3741]
### Amplify CLI Version

12.5.1

### Question

I have an AWS Amplify app which is set up with a custom domain via Cloudflare. However, the app can also be accessed through the default Amplify URL (e.g., `https://prod.123.amplifyapp.com`). I have observed some malicious attempts to access the app directly through this Amplify URL, bypassing Cloudflare's security measures.

I have already set up Cloudflare with the necessary proxy and full encryption settings. But, the issue of direct access through the default Amplify URL still persists.

Is there a way to restrict or disable direct access to the Amplify app through the default URL, ensuring that all traffic to the app only comes via the custom domain set up through Cloudflare?

Thank you

**Comment by Jay2113** [comment]
Hi @afern247 👋 , the Amplify generated URL `https://<branch-name>.<app-id>.amplifyapp.com` is publicly accessible and it cannot be disabled for any Amplify application.

If you have connected a custom domain to your app, our recommendation would be as follows:

- Share the custom domain URL with your customers
- You can consider adding a redirect rule which would redirect your customers from the Amplify generated URL to your custom domain:
```
{
        "source": "https://<branch-name>.<app-id>.amplifyapp.com",
        "target": "https://example.com",
        "status": "302",
        "condition": null
}
```
- Lastly, you can consider fronting your Amplify application with a custom CloudFront distribution and attaching a WAF on it to restrict access to certain IPs.

**Comment by afern247** [comment]
Hi Jay, this can be closed, the measures you suggested are for a development environment, not a production one. As I came to realize, Amplify is not prod ready. If anyone wanted to they can ddos attack any amplify resources, it takes more time, effort and money to try to secure each amplify resource (in case it was possible but it's not) than creating a CDK and doing it there.
