### ISSUE TITLE
 Starting phase: preBuild build failure

### ISSUE THREAD

**Issue by Sardor-M** [aws-amplify/amplify-hosting#3743]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

`d2yhdze04u5fsp`

### AWS Region

us-east-1

### Amplify Hosting feature

Frontend builds

### Question

 Before having this issue, i had a package version conflicts and i fixed them successfully. But after that point, the frontend build is throwing this error. 

**Question**:
- How can it get this `package_locjk.json` and `package.json` syncronization issue get resolved and be able to build my project successfully on `AWS Amplify` ?
 
 What i have tried to solve it?
i followed the [this solution](https://stackoverflow.com/questions/69984660/npm-ci-can-only-install-packages-with-an-existing-package-lock-json-or-npm-shrin) and [Issue-3289](https://github.com/aws-amplify/amplify-hosting/issues/3289)to  solve the issue. 

**First try - solution case**:
- i removed the `package-lock.json` file and the `node_modules`folder, and regenerated using `npm install`. This did not work though.

**Second try - solution case**:
- i did sync `package-lock.json` with `package.json` using a `npm ci`command as it was showing in the error message. However this try also did not work out.

Below this is the error message log: 
     Starting phase: preBuild
2023-10-04T16:13:32.693Z [INFO]: # Executing command: npm ci
2023-10-04T16:13:40.825Z [WARNING]: npm
2023-10-04T16:13:40.827Z [WARNING]: ERR! code EUSAGE
2023-10-04T16:13:40.872Z [WARNING]: npm ERR!
2023-10-04T16:13:40.873Z [WARNING]: 
                                    npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
                                    npm ERR!
                                    npm ERR! Missing: react-native@0.72.5 from lock file
                                    npm ERR! Missing: @jest/create-cache-key-function@29.7.0 from lock file
                                    npm ERR! Missing: @react-native-community/cli@11.3.7 from lock file
                                    npm ERR! Missing: @react-native-community/cli-platform-android@11.3.7 from lock file
                                    npm ERR! Missing: @react-native-community/cli-platform-ios@11.3.7 from lock file
                                    npm ERR! Missing: @react-native/assets-registry@0.72.0 from lock file
                                    npm ERR! Missing: @react-native/codegen@0.72.7 from lock file
                                    npm ERR! Missing: @react-native/gradle-plugin@0.72.11 from lock file
                                    npm ERR! Missing: @react-native/js-polyfills@0.72.1 from lock file
                                    npm ERR! Missing: @react-native/normalize-colors@0.72.0 from lock file
                                    npm ERR! Missing: @react-native/virtualized-lists@0.72.8 from lock file
                                    npm ERR! Missing: abort-controller@3.0.0 from lock file
                                    npm ERR! Missing: anser@1.4.10 from lock file
                                    npm ERR! Missing: deprecated-react-native-prop-types@4.1.0 from lock file
                                    npm ERR! Missing: event-target-shim@5.0.1 from lock file
                                    npm ERR! Missing: flow-enums-runtime@0.0.5 from lock file
                                    npm ERR! Missing: jest-environment-node@29.7.0 from lock file
                                    npm ERR! Missing: jsc-android@250231.0.0 from lock file
                                    npm ERR! Missing: memoize-one@5.2.1 from lock file
                                    npm ERR! Missing: metro-runtime@0.76.8 from lock file
                                    npm ERR! Missing: metro-source-map@0.76.8 from lock file
                                    npm ERR! Missing: mkdirp@0.5.6 from lock file
2023-10-04T16:13:40.873Z [WARNING]: npm ERR! Missing: nullthrows@1.1.1 from lock file
                                    npm ERR! Missing: pretty-format@26.6.2 from lock file
                                    npm ERR! Missing: promise@8.3.0 from lock file
                                    npm ERR! Missing: react-devtools-core@4.28.4 from lock file
                                    npm ERR! Missing: react-refresh@0.4.3 from lock file
                                    npm ERR! Missing: react-shallow-renderer@16.15.0 from lock file
                                    npm ERR! Missing: regenerator-runtime@0.13.11 from lock file
                                    npm ERR! Missing: scheduler@0.24.0-canary-efb381bbf-20230505 from lock file
                                    npm ERR! Missing: stacktrace-parser@0.1.10 from lock file
                                    npm ERR! Missing: whatwg-fetch@3.6.19 from lock file
                                    npm ERR! Missing: ws@6.2.2 from lock file
                                    npm ERR! Missing: yargs@17.7.2 from lock file
                                    npm ERR! Missing: @jest/types@29.6.3 from lock file
                                    npm ERR! Missing: @jest/schemas@29.6.3 from lock file
                                    npm ERR! Missing: @types/istanbul-lib-coverage@2.0.4 from lock file
                                    npm ERR! Missing: @types/istanbul-reports@3.0.2 from lock file
                                    npm ERR! Missing: @types/yargs@17.0.26 from lock file
                                    npm ERR! Missing: @sinclair/typebox@0.27.8 from lock file
                                    npm ERR! Missing: @react-native-community/cli-clean@11.3.7 from lock file
                                    npm ERR!
2023-10-04T16:13:40.873Z [WARNING]: Missing: @react-native-community/cli-config@11.3.7 from lock file
                                    npm ERR! Missing: @react-native-community/cli-debugger-ui@11.3.7 from lock file
                                    npm ERR! Missing: @react-native-community/cli-doctor@11.3.7 from lock file
                                    npm ERR! Missing: @react-native-community/cli-hermes@11.3.7 from lock file
                                    npm ERR! Missing: @react-native-community/cli-plugin-metro@11.3.7 from lock file
                                    npm ERR! Missing: @react-native-community/cli-server-api@11.3.7 from lock file
                                    npm ERR! Missing: @react-native-community/cli-tools@11.3.7 from lock file
                                    npm ERR! Missing: @react-native-community/cli-types@11.3.7 from lock file
                                    npm ERR! Missing: commander@9.5.0 from lock file
                                    npm ERR! Missing: execa@5.1.1 from lock file
                                    npm ERR! Missing: find-up@4.1.0 from lock file
                                    npm ERR! Missing: fs-extra@8.1.0 from lock file
                                    npm ERR! Missing: prompts@2.4.2 from lock file
                                    npm ERR! Missing: cosmiconfig@5.2.1 from lock file
                                    npm ERR! Missing: deepmerge@4.3.1 from lock file
                                    npm
2023-10-04T16:13:40.873Z [WARNING]: ERR! Missing: joi@17.11.0 from lock file
                                    npm ERR! Missing: serve-static@1.15.0 from lock file
                                    npm ERR! Missing: command-exists@1.2.9 from lock file
                                    npm ERR! Missing: envinfo@7.10.0 from lock file
                                    npm ERR! Missing: hermes-profile-transformer@0.0.6 from lock file
                                    npm ERR! Missing: ip@1.1.8 from lock file
                                    npm ERR! Missing: node-stream-zip@1.15.0 from lock file
                                    npm ERR! Missing: ora@5.4.1 from lock file
                                    npm ERR! Missing: strip-ansi@5.2.0 from lock file
                                    npm ERR! Missing: sudo-prompt@9.2.1 from lock file
                                    npm ERR! Missing: wcwidth@1.0.1 from lock file
                                    npm ERR! Missing: yaml@2.3.2 from lock file
                                    npm ERR! Missing: logkitty@0.7.1 from lock file
                                    npm ERR! Missing: metro@0.76.8 from lock file
                                    npm ERR! Missing: metro-config@0.76.8 from lock file
2023-10-04T16:13:40.873Z [WARNING]: npm ERR! Missing: metro-core@0.76.8 from lock file
                                    npm ERR! Missing: metro-react-native-babel-transformer@0.76.8 from lock file
                                    npm ERR! Missing: metro-resolver@0.76.8 from lock file
                                    npm ERR! Missing: readline@1.3.0 from lock file
                                    npm ERR! Missing: compression@1.7.4 from lock file
                                    npm ERR! Missing: connect@3.7.0 from lock file
                                    npm ERR! Missing: errorhandler@1.5.1 from lock file
                                    npm ERR! Missing: nocache@3.0.4 from lock file
                                    npm ERR! Missing: ws@7.5.9 from lock file
                                    npm ERR! Missing: appdirsjs@1.2.7 from lock file
                                    npm ERR! Missing: mime@2.6.0 from lock file
                                    npm ERR! Missing: open@6.4.0 from lock file
                                    npm ERR! Missing: shell-quote@1.8.1 from lock file
                                    npm ERR! Missing: flow-parser@0.206.0 from lock file
                                    npm ERR! Missing: jscodeshift@0.14.0 from lock file
2023-10-04T16:13:40.874Z [WARNING]: npm ERR! Missing: @types/istanbul-lib-report@3.0.1 from lock file
                                    npm ERR! Missing: @types/yargs-parser@21.0.1 from lock file
                                    npm ERR! Missing: accepts@1.3.8 from lock file
                                    npm ERR! Missing: bytes@3.0.0 from lock file
                                    npm ERR! Missing: compressible@2.0.18 from lock file
                                    npm ERR! Missing: debug@2.6.9 from lock file
                                    npm ERR! Missing: on-headers@1.0.2 from lock file
                                    npm ERR! Missing: safe-buffer@5.1.2 from lock file
                                    npm ERR! Missing: vary@1.1.2 from lock file
                                    npm ERR! Missing: negotiator@0.6.3 from lock file
                                    npm ERR! Missing: debug@2.6.9 from lock file
                                    npm ERR! Missing: finalhandler@1.1.2 from lock file
                                    npm ERR! Missing: parseurl@1.3.3 from lock file
                                    npm ERR!
2023-10-04T16:13:40.874Z [WARNING]: Missing: utils-merge@1.0.1 from lock file
                                    npm ERR! Missing: escape-html@1.0.3 from lock file
                                    npm ERR! Missing: get-stream@6.0.1 from lock file
                                    npm ERR! Missing: human-signals@2.1.0 from lock file
                                    npm ERR! Missing: is-stream@2.0.1 from lock file
                                    npm ERR! Missing: merge-stream@2.0.0 from lock file
                                    npm ERR! Missing: npm-run-path@4.0.1 from lock file
                                    npm ERR! Missing: onetime@5.1.2 from lock file
                                    npm ERR! Missing: signal-exit@3.0.7 from lock file
                                    npm ERR! Missing: strip-final-newline@2.0.0 from lock file
                                    npm ERR! Missing: debug@2.6.9 from lock file
                                    npm ERR! Missing: encodeurl@1.0.2 from lock file
                                    npm ERR! Missing: on-finished@2.3.0 from lock file
                                    npm ERR! Missing: statuses@1.5.0 from lock file
                                    npm
2023-10-04T16:13:40.874Z [WARNING]: ERR! Missing: unpipe@1.0.0 from lock file
                                    npm ERR! Missing: jsonfile@4.0.0 from lock file
                                    npm ERR! Missing: universalify@0.1.2 from lock file
                                    npm ERR! Missing: source-map@0.7.4 from lock file
                                    npm ERR! Missing: @jest/environment@29.7.0 from lock file
                                    npm ERR! Missing: @jest/fake-timers@29.7.0 from lock file
                                    npm ERR! Missing: jest-mock@29.7.0 from lock file
                                    npm ERR! Missing: jest-util@29.7.0 from lock file
                                    npm ERR! Missing: @sinonjs/fake-timers@10.3.0 from lock file
                                    npm ERR! Missing: jest-message-util@29.7.0 from lock file
                                    npm ERR! Missing: @sinonjs/commons@3.0.0 from lock file
                                    npm ERR! Missing: type-detect@4.0.8 from lock file
                                    npm ERR! Missing: @types/stack-utils@2.0.1 from lock file
                                    npm
2023-10-04T16:13:40.874Z [WARNING]: ERR! Missing: pretty-format@29.7.0 from lock file
                                    npm ERR! Missing: stack-utils@2.0.6 from lock file
                                    npm ERR! Missing: ci-info@3.9.0 from lock file
                                    npm ERR! Missing: @hapi/hoek@9.3.0 from lock file
                                    npm ERR! Missing: @hapi/topo@5.1.0 from lock file
                                    npm ERR! Missing: @sideway/address@4.1.4 from lock file
                                    npm ERR! Missing: @sideway/formula@3.0.1 from lock file
                                    npm ERR! Missing: @sideway/pinpoint@2.0.0 from lock file
                                    npm ERR! Missing: @babel/plugin-proposal-nullish-coalescing-operator@7.18.6 from lock file
                                    npm ERR! Missing: @babel/plugin-proposal-optional-chaining@7.21.0 from lock file
                                    npm ERR! Missing: @babel/preset-flow@7.22.15 from lock file
                                    npm ERR! Missing: @babel/register@7.22.15 from lock file
                                    npm ERR! Missing: babel-core@7.0.0-bridge.0 from lock file
                                    npm ERR!
2023-10-04T16:13:40.874Z [WARNING]: Missing: neo-async@2.6.2 from lock file
                                    npm ERR! Missing: node-dir@0.1.17 from lock file
                                    npm ERR! Missing: recast@0.21.5 from lock file
                                    npm ERR! Missing: temp@0.8.4 from lock file
                                    npm ERR! Missing: write-file-atomic@2.4.3 from lock file
                                    npm ERR! Missing: @babel/plugin-transform-flow-strip-types@7.22.5 from lock file
                                    npm ERR! Missing: @babel/plugin-syntax-flow@7.22.5 from lock file
                                    npm ERR! Missing: clone-deep@4.0.1 from lock file
                                    npm ERR! Missing: find-cache-dir@2.1.0 from lock file
                                    npm ERR! Missing: pirates@4.0.6 from lock file
                                    npm ERR! Missing: source-map-support@0.5.21 from lock file
                                    npm ERR! Missing: is-plain-object@2.0.4 from lock file
                                    npm ERR! Missing: kind-of@6.0.3 from lock file
                                    npm ERR! Missing: shallow-clone@3.0.1 from lock file
                                    npm
2023-10-04T16:13:40.874Z [WARNING]: ERR! Missing: commondir@1.0.1 from lock file
                                    npm ERR! Missing: pkg-dir@3.0.0 from lock file
                                    npm ERR! Missing: isobject@3.0.1 from lock file
                                    npm ERR! Missing: ansi-fragments@0.2.1 from lock file
                                    npm ERR! Missing: dayjs@1.11.10 from lock file
                                    npm ERR! Missing: colorette@1.4.0 from lock file
                                    npm ERR! Missing: slice-ansi@2.1.0 from lock file
                                    npm ERR! Missing: strip-ansi@5.2.0 from lock file
                                    npm ERR! Missing: async@3.2.4 from lock file
                                    npm ERR! Missing: ci-info@2.0.0 from lock file
                                    npm ERR! Missing: debug@2.6.9 from lock file
                                    npm ERR! Missing: denodeify@1.2.1 from lock file
                                    npm ERR! Missing: error-stack-parser@2.1.4 from lock file
                                    npm ERR! Missing: hermes-parser@0.12.0 from lock file
2023-10-04T16:13:40.875Z [WARNING]: npm ERR! Missing: image-size@1.0.2 from lock file
                                    npm ERR! Missing: jest-worker@27.5.1 from lock file
                                    npm ERR! Missing: jsc-safe-url@0.2.4 from lock file
                                    npm ERR! Missing: lodash.throttle@4.1.1 from lock file
                                    npm ERR! Missing: metro-babel-transformer@0.76.8 from lock file
                                    npm ERR! Missing: metro-cache@0.76.8 from lock file
                                    npm ERR! Missing: metro-cache-key@0.76.8 from lock file
                                    npm ERR! Missing: metro-file-map@0.76.8 from lock file
                                    npm ERR! Missing: metro-inspector-proxy@0.76.8 from lock file
                                    npm ERR! Missing: metro-minify-terser@0.76.8 from lock file
                                    npm ERR! Missing: metro-minify-uglify@0.76.8 from lock file
                                    npm ERR! Missing: metro-react-native-babel-preset@0.76.8 from lock file
                                    npm ERR! Missing: metro-symbolicate@0.76.8 from lock file
                                    npm
2023-10-04T16:13:40.875Z [WARNING]: ERR! Missing: metro-transform-plugins@0.76.8 from lock file
                                    npm ERR! Missing: metro-transform-worker@0.76.8 from lock file
                                    npm ERR! Missing: serialize-error@2.1.0 from lock file
                                    npm ERR! Missing: throat@5.0.0 from lock file
                                    npm ERR! Missing: ws@7.5.9 from lock file
                                    npm ERR! Missing: yargs@17.7.2 from lock file
                                    npm ERR! Missing: stackframe@1.3.4 from lock file
                                    npm ERR! Missing: hermes-estree@0.12.0 from lock file
                                    npm ERR! Missing: queue@6.0.2 from lock file
                                    npm ERR! Missing: supports-color@8.1.1 from lock file
                                    npm ERR! Missing: cosmiconfig@5.2.1 from lock file
                                    npm ERR! Missing: jest-validate@29.7.0 from lock file
                                    npm ERR! Missing: camelcase@6.3.0 from lock file
                                    npm ERR! Missing: jest-get-type@29.6.3 from lock file
                                    npm ERR! Missing: leven@3.1.0 from lock file
                                    npm ERR! Missing: pretty-format@29.7.0 from lock file
                                    npm ERR! Missing: debug@2.6.9 from lock file
                                    npm ERR! Missing: fb-watchman@2.0.2 from lock file
                                    npm ERR! Missing: jest-regex-util@27.5.1 from lock file
                                    npm ERR! Missing: jest-util@27.5.1 from lock file
                                    npm ERR! Missing: node-abort-controller@3.1.1 from lock file
                                    npm ERR! Missing: walker@1.0.8 from lock file
                                    npm ERR! Missing: bser@2.1.1 from lock file
                                    npm ERR! Missing: node-int64@0.4.0 from lock file
                                    npm ERR! Missing: debug@2.6.9 from lock file
                                    npm ERR! Missing: ws@7.5.9 from lock file
                                    npm ERR! Missing: yargs@17.7.2 from lock file
                                    npm ERR! Missing: terser@5.21.0 from lock file
                                    npm ERR! Missing: uglify-es@3.3.9 from lock file
                                    npm ERR! Missing: @babel/plugin-proposal-async-generator-functions@7.20.7 from lock file
                                    npm ERR! Missing: @babel/plugin-proposal-export-default-from@7.22.17 from lock file
                                    npm ERR! Missing: @babel/plugin-proposal-numeric-separator@7.18.6 from lock file
                                    npm ERR! Missing: @babel/plugin-proposal-optional-catch-binding@7.18.6 from lock file
                                    npm ERR! Missing: @babel/plugin-syntax-export-default-from@7.22.5 from lock file
                                    npm ERR! Missing: @babel/plugin-transform-react-jsx-self@7.22.5 from lock file
                                    npm ERR! Missing: @babel/plugin-transform-react-jsx-source@7.22.5 from lock file
                                    npm ERR! Missing: @babel/plugin-transform-runtime@7.22.15 from lock file
                                    npm ERR! Missing: babel-plugin-transform-flow-enums@0.0.2 from lock file
                                    npm ERR! Missing: semver@6.3.1 from lock file
                                    npm ERR! Missing: babel-preset-fbjs@3.4.0 from lock file
                                    npm ERR! Missing: babel-plugin-syntax-trailing-function-commas@7.0.0-beta.0 from lock file
                                    npm ERR! Missing: ob1@0.76.8 from lock file
                                    npm ERR! Missing: vlq@1.0.1 from lock file
                                    npm ERR! Missing: through2@2.0.5 from lock file
                                    npm
2023-10-04T16:13:40.876Z [WARNING]: ERR! Missing: ee-first@1.1.1 from lock file
                                    npm ERR! Missing: mimic-fn@2.1.0 from lock file
                                    npm ERR! Missing: is-wsl@1.1.0 from lock file
                                    npm ERR! Missing: bl@4.1.0 from lock file
                                    npm ERR! Missing: cli-cursor@3.1.0 from lock file
                                    npm ERR! Missing: cli-spinners@2.9.1 from lock file
                                    npm ERR! Missing: is-interactive@1.0.0 from lock file
                                    npm ERR! Missing: is-unicode-supported@0.1.0 from lock file
                                    npm ERR! Missing: log-symbols@4.1.0 from lock file
                                    npm ERR! Missing: buffer@5.7.1 from lock file
                                    npm ERR! Missing: readable-stream@3.6.2 from lock file
                                    npm ERR! Missing: restore-cursor@3.1.0 from lock file
                                    npm ERR! Missing: find-up@3.0.0 from lock file
                                    npm ERR! Missing: @jest/types@26.6.2 from lock file
2023-10-04T16:13:40.876Z [WARNING]: npm ERR! Missing: react-is@17.0.2 from lock file
                                    npm ERR! Missing: asap@2.0.6 from lock file
                                    npm ERR! Missing: kleur@3.0.3 from lock file
                                    npm ERR! Missing: sisteransi@1.0.5 from lock file
                                    npm ERR! Missing: ws@7.5.9 from lock file
                                    npm ERR! Missing: string_decoder@1.3.0 from lock file
                                    npm ERR! Missing: util-deprecate@1.0.2 from lock file
                                    npm ERR! Missing: ast-types@0.15.2 from lock file
                                    npm ERR!
2023-10-04T16:13:40.876Z [WARNING]: Missing: esprima@4.0.1 from lock file
                                    npm ERR! Missing: source-map@0.6.1 from lock file
                                    npm ERR! Missing: send@0.18.0 from lock file
                                    npm ERR! Missing: debug@2.6.9 from lock file
                                    npm ERR! Missing: depd@2.0.0 from lock file
                                    npm ERR! Missing: destroy@1.2.0 from lock file
                                    npm ERR! Missing: etag@1.8.1 from lock file
                                    npm ERR! Missing: fresh@0.5.2 from lock file
                                    npm ERR!
2023-10-04T16:13:40.876Z [WARNING]: Missing: http-errors@2.0.0 from lock file
                                    npm ERR! Missing: mime@1.6.0 from lock file
                                    npm ERR! Missing: ms@2.1.3 from lock file
                                    npm ERR! Missing: on-finished@2.4.1 from lock file
                                    npm ERR! Missing: range-parser@1.2.1 from lock file
                                    npm ERR! Missing: statuses@2.0.1 from lock file
                                    npm ERR! Missing: setprototypeof@1.2.0 from lock file
                                    npm ERR!
2023-10-04T16:13:40.876Z [WARNING]: Missing: statuses@2.0.1 from lock file
                                    npm ERR! Missing: toidentifier@1.0.1 from lock file
                                    npm ERR! Missing: ansi-styles@3.2.1 from lock file
                                    npm ERR! Missing: astral-regex@1.0.0 from lock file
                                    npm ERR! Missing: is-fullwidth-code-point@2.0.0 from lock file
                                    npm ERR! Missing: buffer-from@1.1.2 from lock file
                                    npm ERR! Missing: source-map@0.6.1 from lock file
                                    npm ERR! Missing: escape-string-regexp@2.0.0 from lock file
                                    npm ERR! Missing: type-fest@0.7.1 from lock file
                                    npm ERR! Missing: safe-buffer@5.2.1 from lock file
                                    npm ERR! Missing: rimraf@2.6.3 from lock file
2023-10-04T16:13:40.876Z [WARNING]: npm ERR! Missing: @jridgewell/source-map@0.3.5 from lock file
                                    npm ERR! Missing: commander@2.20.3 from lock file
                                    npm ERR! Missing: readable-stream@2.3.8 from lock file
                                    npm ERR! Missing: xtend@4.0.2 from lock file
                                    npm ERR! Missing: commander@2.13.0 from lock file
                                    npm ERR! Missing: source-map@0.6.1 from lock file
                                    npm ERR! Missing: makeerror@1.0.12 from lock file
                                    npm ERR! Missing: tmpl@1.0.5 from lock file
                                    npm ERR!
2023-10-04T16:13:40.877Z [WARNING]: Missing: defaults@1.0.4 from lock file
                                    npm ERR! Missing: clone@1.0.4 from lock file
                                    npm ERR! Missing: async-limiter@1.0.1 from lock file
                                    npm ERR! Missing: import-fresh@2.0.0 from lock file
                                    npm ERR! Missing: is-directory@0.3.1 from lock file
                                    npm ERR! Missing: js-yaml@3.14.1 from lock file
                                    npm ERR! Missing: parse-json@4.0.0 from lock file
                                    npm ERR! Missing: caller-path@2.0.0 from lock file
                                    npm ERR!
2023-10-04T16:13:40.877Z [WARNING]: Missing: resolve-from@3.0.0 from lock file
                                    npm ERR! Missing: caller-callsite@2.0.0 from lock file
                                    npm ERR! Missing: callsites@2.0.0 from lock file
                                    npm ERR! Missing: argparse@1.0.10 from lock file
                                    npm ERR! Missing: sprintf-js@1.0.3 from lock file
                                    npm ERR! Missing: json-parse-better-errors@1.0.2 from lock file
                                    npm ERR! Missing: ansi-regex@4.1.1 from lock file
                                    npm ERR! Missing: locate-path@5.0.0 from lock file
                                    npm ERR!
2023-10-04T16:13:40.877Z [WARNING]: Missing: p-locate@4.1.0 from lock file
                                    npm ERR! Missing: p-limit@2.3.0 from lock file
                                    npm ERR! Missing: ansi-regex@4.1.1 from lock file
                                    npm ERR! Missing: ms@2.0.0 from lock file
                                    npm ERR! Missing: ms@2.0.0 from lock file
                                    npm ERR! Missing: ms@2.0.0 from lock file
                                    npm ERR! Missing: ansi-styles@5.2.0 from lock file
                                    npm ERR! Missing: react-is@18.2.0 from lock file
2023-10-04T16:13:40.877Z [WARNING]: npm ERR! Missing: ansi-styles@5.2.0 from lock file
                                    npm ERR! Missing: react-is@18.2.0 from lock file
                                    npm ERR! Missing: import-fresh@2.0.0 from lock file
                                    npm ERR! Missing: js-yaml@3.14.1 from lock file
                                    npm ERR! Missing: parse-json@4.0.0 from lock file
                                    npm ERR! Missing: resolve-from@3.0.0 from lock file
                                    npm ERR! Missing: argparse@1.0.10 from lock file
                                    npm
2023-10-04T16:13:40.878Z [WARNING]: ERR! Missing: ms@2.0.0 from lock file
                                    npm ERR! Missing: @jest/types@27.5.1 from lock file
                                    npm ERR! Missing: @types/yargs@16.0.6 from lock file
                                    npm ERR! Missing: ms@2.0.0 from lock file
                                    npm ERR! Missing: cliui@8.0.1 from lock file
                                    npm ERR! Missing: y18n@5.0.8 from lock file
                                    npm ERR! Missing: yargs-parser@21.1.1 from lock file
                                    npm ERR! Missing: wrap-ansi@7.0.0 from lock file
                                    npm ERR! Missing: ms@2.0.0 from lock file
                                    npm ERR! Missing: cliui@8.0.1 from lock file
                                    npm ERR! Missing: y18n@5.0.8 from lock file
                                    npm ERR! Missing: yargs-parser@21.1.1 from lock file
                                    npm ERR! Missing: wrap-ansi@7.0.0 from lock file
                                    npm ERR! Missing: locate-path@3.0.0 from lock file
                                    npm ERR! Missing: p-locate@3.0.0 from lock file
                                    npm ERR! Missing: path-exists@3.0.0 from lock file
                                    npm ERR! Missing: p-limit@2.3.0 from lock file
                                    npm ERR! Missing: @types/yargs@15.0.16 from lock file
                                    npm ERR! Missing: cliui@8.0.1 from lock file
                                    npm ERR! Missing: y18n@5.0.8 from lock file
                                    npm ERR! Missing: yargs-parser@21.1.1 from lock file
                                    npm ERR! Missing: wrap-ansi@7.0.0 from lock file
                                    npm ERR! Missing: ms@2.0.0 from lock file
                                    npm ERR! Missing: color-convert@1.9.3 from lock file
                                    npm ERR! Missing: color-name@1.1.3 from lock file
                                    npm ERR! Missing: core-util-is@1.0.3 from lock file
                                    npm ERR! Missing: isarray@1.0.0 from lock file
                                    npm ERR! Missing: process-nextick-args@2.0.1 from lock file
                                    npm ERR! Missing: string_decoder@1.1.1 from lock file
                                    npm ERR!
                                    npm ERR! Clean install a project
                                    npm ERR!
                                    npm ERR! Usage:
                                    npm ERR! npm ci
                                    npm ERR!
                                    npm ERR! Options:
                                    npm ERR! [-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
                                    npm ERR! [-E|--save-exact] [-g|--global] [--global-style] [--legacy-bundling]
                                    npm ERR! [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
                                    npm ERR! [--strict-peer-deps] [--no-package-lock] [--foreground-scripts]
                                    npm ERR! [--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]
                                    npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
                                    npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]
                                    npm ERR!
                                    npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
                                    npm ERR!
                                    npm ERR! Run "npm help ci" for more info
2023-10-04T16:13:40.880Z [WARNING]: 
2023-10-04T16:13:40.882Z [WARNING]: npm ERR! A complete log of this run can be found in:
                                    npm ERR!     /root/.npm/_logs/2023-10-04T16_13_32_921Z-debug-0.log
2023-10-04T16:13:40.892Z [ERROR]: !!! Build failed
2023-10-04T16:13:40.892Z [INFO]: Please check the supported SSR features to find if your build failure is related to an unsupported feature: https://docs.aws.amazon.com/amplify/latest/userguide/ssr-Amplify-support.html#supported-unsupported-features. You may also find this troubleshooting guide useful: https://docs.aws.amazon.com/amplify/latest/userguide/troubleshooting-ssr-deployment.html
2023-10-04T16:13:40.892Z [ERROR]: !!! Non-Zero Exit Code detected
2023-10-04T16:13:40.892Z [INFO]: # Starting environment caching...
2023-10-04T16:13:40.893Z [INFO]: # Environment caching completed
Terminating logging...

**Comment by Jay2113** [comment]
Hi @Sardor-M 👋 , thanks for raising this!

Our recommendation for build failures such as these is to perform a clean install as follows:
- Delete the `package-lock.json` and `node_modules` folder locally
- Run `npm install`
- Remove the `cache` path from the build specification file `amplify.yml` in the Amplify Console as it is used to cache build-time dependencies such as the `node_modules` folder
- Commit and push the changes to the git repository and a new build will initiate with synced `package.json` and `package-lock.json` files.

You may also want to try the steps mentioned here: https://stackoverflow.com/a/76004061

**Comment by Sardor-M** [comment]
Hi @Jay2113, thanks for reaching out !

After following your instructions and the solution reference  you provided, I successfully build and deployed my project to the AWS Amplify. 

This link [stackoveflow issue](https://stackoverflow.com/a/76004061) helped me a lot to resolve the issue.

Once again, thanks for helping me out to solve this issue.
