### ISSUE TITLE
404 Not found for all my amplify apps

### ISSUE THREAD

**Issue by tigrandivanyan** [aws-amplify/amplify-hosting#3744]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dibhy1xsriigv

### AWS Region

eu-west-3

### Amplify Hosting feature

Access logs

### Question

Hello, I get 404 Not found while trying to get to my application which worked fine yesterday, I tried to redeploy it several times and to make redirect from 404 to ./index.html the app runs fine locally but I encounter this issue on aws amplify could you please help me understand what is the problem?

Thanks in advance.

**Comment by Jay2113** [comment]
Hi @tigrandivanyan 👋 , thanks for raising this!

After reviewing the configuration of your Amplify app `dibhy1xsriigv`, it seems that you are performing manual deployments. When using manual deployments you will need to ensure the following:
- When creating the zip folder, you will need to ensure that you zip the contents of your build output and not the top level folder. For example, if your build output generates a folder named `build` or `public`, first navigate into that folder, select all of the contents, and zip it from there. 
- If you are storing the zip file in Amazon S3, you will need to ensure that the S3 bucket has ACLs enabled on them.

Can you verify that you followed these steps?
