### ISSUE TITLE
Frontend deployed cannot make HTTP/HTTPS requests to API on external VM

### ISSUE THREAD

**Issue by faysalbadaoui** [aws-amplify/amplify-hosting#3746]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-1

### Amplify Hosting feature

Frontend builds

### Question

I would like to know why my frontend which is deployed in a AWS Amplify instance cannot access and get a font located into fonts.google.com or make API calls because I get error response, as the petition cannot be done.

**Comment by Jay2113** [comment]
Hi @faysalbadaoui 👋 , thanks for raising this!

Can you share some insights on the following:
- Have you verified if the issue occurs when building and running your application locally? 
- Can you share your Amplify app id?
- What type of errors are you observing when trying to retrieve the fonts? Can you share the error response?

**Comment by faysalbadaoui** [comment]
Issue solved by re-deploying instance.
