### ISSUE TITLE
"GitHub authorization failed" when trying to reconnect to a repository using github organization

### ISSUE THREAD

**Issue by phelix001** [aws-amplify/amplify-hosting#3747]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

new_app

### AWS Region

us-east-1

### Amplify Hosting feature

One click deploy

### Frontend framework

Next.js

### Next.js version

10.1.3

### Next.js router

Pages Router

### Describe the bug

Existing amplify deployment can't reconnect after turning on mandtory 2fa for github users.  Revoked tokens and stil lgetting "GitHub authorization failed" on aws when connecting github repo.

### Expected behavior

Should connect to github.

### Reproduction steps

existing amplify on github organization connected and working.
add mandatory 2fa for github users.
need to reconnect amplify to github but when I try just get errors GitHub authorization failed

### Build Settings

```yaml
just regulat stuff
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
I'm not reall a dev

### Additional information

I'm not super devy.

**Comment by phelix001** [comment]
I ended up revoking the AWS token, and then turning on ALL repo access instead of two of my repos, then reconnected and it all worked.  Users should still be able to share only select repos with aws.

**Comment by Jay2113** [comment]
Hi @phelix001 👋 , thanks for raising this!

Amplify uses the GitHub Apps feature to authorize Amplify read-only access to GitHub repositories. Can you try the following steps to provide read-only access to only select repositories:
- Within your GitHub profile, navigate to `Installed GitHub apps`: https://github.com/settings/installations/
- Select the `AWS Amplify (us-east-1)` GitHub app
- Select `Configure`
- Within the `Repository access` section, choose `only select repositories` option
- Click `Save`

Alternatively, you can also uninstall the `AWS Amplify (us-east-1)` GitHub app and can restart the GitHub authorization process from the Amplify Console. During this process, you will be prompted to:
- Select where you want to install the `GitHub` app
- Install and authorize `all repositories` or `only select repositories`

**Comment by phelix001** [comment]
Yes, I tried both those methods, and ended up not being able to select a single or few repos but had to disconnect completely and ONLY choose ALL repos.

**Comment by kensiej** [comment]
Having this same issue, on an IAM account, can access Amplify dashboard and have access to a private organization repository. Attempting to connect and every time receiving a Github authorization error with no further explanation

**Comment by Jay2113** [comment]
@phelix001 @kensiej 👋 , I was not able to reproduce this behavior. Here are the flows I tried:
- 2FA was already enabled on my GitHub profile
- Enabled the requirement of 2FA for users on an existing repository which is linked to a GitHub organization 
- On an existing app, I used the `Reconnect this repository` button in the Amplify console and was able to re-authenticate to the GitHub repository successfully
- I was able to modify the GitHub app to only allow access to a single repository and was able to successfully reconnect following the above step.
- Also, created a new app altogether connected to the same repository and was able to authenticate as expected.

Are you using the 1-click deploy feature? Can you share the detailed flow of steps/events using which you can reproduce this behavior?

**Comment by mauerbac** [comment]
Can you try again? if you are still experiencing an issue please open an aws support case
