### ISSUE TITLE
Can't Create New Amplify Apps via Terraform or Console - BadRequestException: Rate exceeded while calling CreateApp

### ISSUE THREAD

**Issue by ckchessmaster** [aws-amplify/amplify-hosting#3748]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-2

### Amplify Hosting feature

Console, Deployments

### Frontend framework

Angular

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

Since a few days ago I am no longer able to create new Amplify apps either via my CI/CD process (terraform) or via the AWS console. Every time I try to create it I get the following error: 

**Error: creating Amplify App (frontend): BadRequestException: Rate exceeded while calling CreateApp, please slow down or try again later.**

I even deleted and re-created an existing working app to make sure that it wasn't something weird with my repo.

### Expected behavior

I should be able to create new amplify apps.

### Reproduction steps

1. Go to the amplify app space in the AWS console and click create new app
2. Follow the app creation wizard using GitLab and an existing repo as the code source.
3. Leave all settings at their defaults.
4. Click Save and Deploy
5. Error: Rate exceeded while calling CreateApp, please slow down or try again later.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line
# This is the output from terraform

Plan: 1 to add, 0 to change, 0 to destroy.
aws_amplify_app.frontend: Creating...
╷
│ Error: creating Amplify App (frontend): BadRequestException: Rate exceeded while calling CreateApp, please slow down or try again later.
│ 
│   with aws_amplify_app.frontend,
│   on main.tf line 15, in resource "aws_amplify_app" "frontend":
│   15: resource "aws_amplify_app" "frontend" {
│ 
╵

# This is the output from the AWS console:
Houston, there's a problem
Rate exceeded while calling CreateApp, please slow down or try again later.

```

</details>

**Comment by ckchessmaster** [comment]
Does Amplify have a really aggressive rate limit that I missed somewhere? I just tried to deploy it again since it's been a couple of days and it worked both through the AWS Console & through Terraform to create one of my two apps. The 2nd app failed to be created due to the same error.

**Comment by Jay2113** [comment]
Hi @ckchessmaster 👋 , thanks for raising this!

We have a default rate limit on the apps creation of 25 per hour as stated here: https://docs.aws.amazon.com/general/latest/gr/amplify.html#service-quotas-amplify.

Based on the information provided, it looks like you are only trying to deploy 2 apps using Terraform? Can you share your AWS Account ID privately via a DM on our [community discord server](https://discord.gg/amplify)? My username is `Jay Raval`.

**Comment by ckchessmaster** [comment]
Okay yeah, so today I created an app via the AWS console, deleted it then created it again via Terraform, and then couldn't create my second app. So unless Terraform is doing something strange I am definitely under the 25/day limit. I DMed you on discord thanks!

**Comment by Jay2113** [comment]
@ckchessmaster As discussed on discord, in order to further troubleshoot your issue please reach out to the AWS Support team: https://aws.amazon.com/support for additional assistance. Thank you.
