### ISSUE TITLE
Error: You have reached the maximum number of apps in this account

### ISSUE THREAD

**Issue by NourTuffaha** [aws-amplify/amplify-hosting#3752]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APPNext.js v13.4.11

### AWS Region

eu-central-1

### Amplify Hosting feature

Manual deploys

### Next.js version

Next.js v13.4.11

### Next.js router

Pages Router

### Describe the bug

I deployed a nextjs website 6 days ago with no issues. I've been trying to deploy another one every since however I keep getting the error:  Error: You have reached the maximum number of apps in this account.  ![image](https://github.com/aws-amplify/amplify-hosting/assets/95666577/0943d6ac-db19-435b-88a1-a181d253395d) 
 However when I check my service quotas, the value for apps is 25 as shown in the image attached.

![image](https://github.com/aws-amplify/amplify-hosting/assets/95666577/d767cab3-21cc-40e3-bd56-e99984a0807b)

### Expected behavior

I need to deploy the other website as it is complementary to the first which both are one package for a client which has been waiting for far too long. Please help me deploy this website, and the rest of the websites for future instances.

### Reproduction steps

I was told this issue usually has to do with the account being relatively new, mine isn't.

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by cacharrin** [comment]
I'm having the same issue. I have 5 apps and I want to add a new one. Error appear. Service quotas for amplify shows 25 apps are allowed.

**Comment by Jay2113** [comment]
Hi @NourTuffaha 👋 , in order to further troubleshoot your issue please reach out to the AWS Support team: https://aws.amazon.com/support for additional assistance.

@cacharrin, I'll recommend the same for you too.

Thank you.
