### ISSUE TITLE
Astro build failing due to mismatched node version.

### ISSUE THREAD

**Issue by xkeshav** [aws-amplify/amplify-hosting#3754]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Other

### Which UI component?

Other

### How is your app built?

Astro

### What browsers are you seeing the problem on?

Chrome

### Which region are you seeing the problem in?

us-east-1

### Please describe your bug.

I have blog and it is hosted on a domain and AWS amplify trigger the build as soon as I commit and it was working fine till last commit

in last commit, I have updated Astro version and now build is getting failed and reason is. Although I have checked in GitHub workflow, it shows different error of CSS parsing issue in Jekyll build ;[ mentioned here. ](https://stackoverflow.com/questions/77246947/astro-build-getting-failed-in-github-workflow-build-step-with-error-jekyllconv)

but in AWS amplify build log, it says wrong node js version, this is the log details.

```log
                                 # Starting phase: preBuild
                                 # Executing command: npm ci
2023-10-06T19:20:02.795Z [WARNING]: npm
2023-10-06T19:20:02.797Z [WARNING]: WARN EBADENGINE Unsupported engine {
                                    npm WARN EBADENGINE   package: '@astrojs/prism@3.0.0',
                                    npm WARN EBADENGINE   required: { node: '>=18.14.1' },
                                    npm WARN EBADENGINE   current: { node: 'v16.19.0', npm: '8.19.3' }
                                    npm WARN EBADENGINE }
                                    npm WARN EBADENGINE Unsupported engine {
                                    npm WARN EBADENGINE   package: '@astrojs/telemetry@3.0.2',
                                    npm WARN EBADENGINE   required: { node: '>=18.14.1' },
                                    npm WARN EBADENGINE   current: { node: 'v16.19.0', npm: '8.19.3' }
                                    npm WARN EBADENGINE }
2023-10-06T19:20:02.798Z [WARNING]: npm
2023-10-06T19:20:02.798Z [WARNING]: WARN EBADENGINE Unsupported engine {
                                    npm WARN EBADENGINE   package: 'astro@3.2.0',
                                    npm WARN EBADENGINE   required: { node: '>=18.14.1', npm: '>=6.14.0' },
                                    npm WARN EBADENGINE   current: { node: 'v16.19.0', npm: '8.19.3' }
                                    npm WARN EBADENGINE }
2023-10-06T19:20:15.722Z [INFO]: added 576 packages, and audited 577 packages in 16s
2023-10-06T19:20:15.726Z [INFO]: 227 packages are looking for funding
                                 run `npm fund` for details
2023-10-06T19:20:15.742Z [INFO]: 4 vulnerabilities (3 low, 1 moderate)
                                 To address issues that do not require attention, run:
                                 npm audit fix
                                 To address all issues (including breaking changes), run:
                                 npm audit fix --force
                                 Run `npm audit` for details.
2023-10-06T19:20:15.756Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
2023-10-06T19:20:15.756Z [INFO]: # Executing command: npm run build
2023-10-06T19:20:16.116Z [INFO]: > grateful-galaxy@0.0.1 build
                                 > astro build
2023-10-06T19:20:16.234Z [WARNING]: Node.js v16.19.0 is not supported by Astro!
                                    Please upgrade Node.js to a supported version: ">=18.14.1"
2023-10-06T19:20:16.236Z [INFO]: AWS CodeBuild CI Environment Detected!
                                 Additional steps may be needed to set your Node.js version:
2023-10-06T19:20:16.237Z [INFO]: Documentation: https://docs.astro.build/guides/deploy
2023-10-06T19:20:16.244Z [ERROR]: !!! Build failed
2023-10-06T19:20:16.245Z [ERROR]: !!! Non-Zero Exit Code detected
2023-10-06T19:20:16.245Z [INFO]: # Starting environment caching...
2023-10-06T19:20:16.245Z [INFO]: # Uploading environment cache artifact...
2023-10-06T19:20:16.357Z [INFO]: # Uploaded environment cache artifact
2023-10-06T19:20:16.358Z [INFO]: # Environment caching completed
Terminating logging...
```

build link: https://us-east-1.console.aws.amazon.com/amplify/home?region=us-east-1#/d1c6hzkoiamnhy/develop/15

now kindly help me how to upgrade node js version to this AWS Amplify app? 

 thsi is my *package json*
 
```json
{
  "name": "grateful-galaxy",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/mdx": "^0.17.2",
    "@astrojs/rss": "^2.1.1",
    "@astrojs/sitemap": "^1.1.0",
    "astro": "^3.2.0"
  },
  "devDependencies": {
    "typescript": "^5.2.2"
  }
}
```

note: local build command run successfully.

Thanks

### What's the expected behaviour?

Build should run and complete successfully.

### Help us reproduce the bug!

created a separate branch so you can trigger the build again here is the latest build result for the same: https://us-east-1.console.aws.amazon.com/amplify/home?region=us-east-1#/d1c6hzkoiamnhy/update/1?step=BUILD

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

![image](https://github.com/aws-amplify/amplify-ui/assets/415219/054fa464-aaa4-4f43-bed3-5988213f8505)

_No response_

**Comment by reesscot** [comment]
@xkeshav Moving ticket over the to the Amplify Hosting repo, since this is a Amplify hosting build issue.

**Comment by xkeshav** [comment]
I have tried whatever mentioen in the comment #3571 but Astro doesnt support less than 18.4.0 . :(

**Comment by BraedenKilburn** [comment]
For those still having issues, in my "Build Settings", I set my "Build image" to be a custom image from Docker's public ECR. This is the image that I used `public.ecr.aws/docker/library/node:20`; however, you may choose to use your own image, a list of which may [be found here](https://gallery.ecr.aws/docker/library/node).

**Comment by JuanCa8313** [comment]
I was searching for a couple of hours, and I found a solution to that problem. All I did was change the image to Amazon Linux:2023.

![image](https://github.com/aws-amplify/amplify-hosting/assets/109004902/8d0ef449-925e-426d-9121-58b13cf2d317)

**Comment by xkeshav** [comment]
this worked

> I was searching for a couple of hours, and I found a solution to that problem. All I did was change the image to Amazon Linux:2023.
> 
> ![image](https://private-user-images.githubusercontent.com/109004902/289850023-8d0ef449-925e-426d-9121-58b13cf2d317.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MjQyNTksIm5iZiI6MTcwMjkyMzk1OSwicGF0aCI6Ii8xMDkwMDQ5MDIvMjg5ODUwMDIzLThkMGVmNDQ5LTkyNWUtNDI2ZC05MTIxLTU4YjEzY2YyZDMxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQxODI1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWNjY2Y5OTZkNmZmZGEwZDMxMDQzOWJkNGVjZDNjZGJiYThiN2QzOGRjMDBjNTU4Mjk1MGYzM2U3N2E3ZDUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aZcouERxmVR9Hw4AJHCbaYAahSWBSXl5qDP0ib6focs)

this worked
