### ISSUE TITLE
Error from cloudfront

### ISSUE THREAD

**Issue by ysoffner** [aws-amplify/amplify-hosting#3755]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d34je5hlq2q26a

### AWS Region

us-east-1

### Amplify Hosting feature

Custom domain, SSR

### Frontend framework

Next.js

### Next.js version

13.0.6

### Next.js router

Pages Router

### Describe the bug

I'm getting 404 | X-Cache: Error from cloudfront, from https://payb.ticto.app/O7951502B, is one of the pages in the production environment, I noticed that on some computers, cell phones, they can open it, others cannot. I use Cloudflare in front, I tested activating and removing proxy, the same error occurs. PS: The same problem happens with custom domains, or with amplify itself

```
Cf-Cache-Status:  DYNAMIC
Cf-Ray: 813fd425aef61aac-GRU

Content-Encoding: gzip
Content-Type: text/html; charset=utf-8
Date: Tue, 10 Oct 2023 15: 7: 0 GMT
Server: cloudflare
Vary: Accept-Encoding
Via:  1.1 fad3f173366d4dbb66574501c04f58ec.cloudfront.net (CloudFront)
X-Amz-Cf-Id:  pLxRCP161B-nTpljJff5Gr1AI4IPHcdHenfQ_GQzNSeD2a5HkJoARA==
X-Amz-Cf-Pop: GRU3-P5
X-Cache:  Error from cloudfront
X-Powered-By: Next.js
```

### Expected behavior

I hope to load the same on Vercel using cloudflare, link:https://payment.ticto.app/O7951502B

### Reproduction steps

build a NextJS project
test the specific url

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by gabstv** [comment]
Similar errors here aswell

**Comment by gustavo-ticto** [comment]
+1

**Comment by SoulAuctioneer** [comment]
Also having this problem.

**Comment by umansia** [comment]
I am also having the same problem.

**Comment by mauerbac** [comment]
This issue seems to be resolved. Please re-open if its still experiencing it https://github.com/aws-amplify/amplify-hosting/issues/3769#issuecomment-1776481346
