### ISSUE TITLE
500 errors with images on next.js

### ISSUE THREAD

**Issue by argaen** [aws-amplify/amplify-hosting#3756]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1w6jie2l5rnr4

### AWS Region

ap-southeast-1

### Amplify Hosting feature

Custom build image

### Frontend framework

Next.js

### Next.js version

13.5.3

### Next.js router

App Router

### Describe the bug

Hi! I'm getting the following error when trying to load an image in my Next.js app:

```
2023-10-11T18:43:07.264+08:00 | cause: [Error: 139932014778304:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:331:
-- | --
  | 2023-10-11T18:43:07.264+08:00 | ] {
  | 2023-10-11T18:43:07.264+08:00 | library: 'SSL routines',
  | 2023-10-11T18:43:07.264+08:00 | function: 'ssl3_get_record',
  | 2023-10-11T18:43:07.264+08:00 | reason: 'wrong version number',
  | 2023-10-11T18:43:07.264+08:00 | code: 'ERR_SSL_WRONG_VERSION_NUMBER'
  | 2023-10-11T18:43:07.264+08:00 | }
```

The error only happens in production build.

This is the asset giving issues: https://app.maffin.io/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fmaffin_logo_sm.094266a4.png&w=128&q=75

However, favicon is loading properly: https://app.maffin.io/favicon/favicon-32x32.png

After reading some similar issues I tried deleting `sharp` but same result.

### Expected behavior

Images should load properly

### Reproduction steps

The repo is public and can be seen in: https://github.com/maffin-io/maffin-app

I'm using the `Image` tag of next.js.

### Log output

<details>

```
2023-10-11T18:42:38.865+08:00 | START RequestId: f00ae0a9-7a42-4a4c-ba65-3af7df66796b Version: $LATEST
-- | --
  | 2023-10-11T18:42:39.176+08:00 | upstream image response failed for /_next/static/media/maffin_logo_sm.094266a4.png TypeError: fetch failed
  | 2023-10-11T18:42:39.176+08:00 | at Object.fetch (/var/task/node_modules/next/dist/compiled/undici/index.js:1:26672)
  | 2023-10-11T18:42:39.176+08:00 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
  | 2023-10-11T18:42:39.176+08:00 | at async globalThis.fetch (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:127:62909)
  | 2023-10-11T18:42:39.176+08:00 | at async invokeRequest (/var/task/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
  | 2023-10-11T18:42:39.176+08:00 | at async /var/task/node_modules/next/dist/server/next-server.js:362:39
  | 2023-10-11T18:42:39.176+08:00 | at async imageOptimizer (/var/task/node_modules/next/dist/server/image-optimizer.js:537:13)
  | 2023-10-11T18:42:39.176+08:00 | at async cacheEntry.imageResponseCache.get.incrementalCache (/var/task/node_modules/next/dist/server/next-server.js:519:61)
  | 2023-10-11T18:42:39.176+08:00 | at async /var/task/node_modules/next/dist/server/response-cache/index.js:102:36 {
  | 2023-10-11T18:42:39.176+08:00 | cause: [Error: 139932014778304:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:331:
  | 2023-10-11T18:42:39.176+08:00 | ] {
  | 2023-10-11T18:42:39.176+08:00 | library: 'SSL routines',
  | 2023-10-11T18:42:39.176+08:00 | function: 'ssl3_get_record',
  | 2023-10-11T18:42:39.176+08:00 | reason: 'wrong version number',
  | 2023-10-11T18:42:39.176+08:00 | code: 'ERR_SSL_WRONG_VERSION_NUMBER'
  | 2023-10-11T18:42:39.176+08:00 | }
  | 2023-10-11T18:42:39.176+08:00 | }
  | 2023-10-11T18:42:39.178+08:00 | REPORT RequestId: f00ae0a9-7a42-4a4c-ba65-3af7df66796b Duration: 312.58 ms Billed Duration: 313 ms Memory Size: 1024 MB Max Memory Used: 22
```

</details>

**Comment by ShahriarKh** [comment]
See https://github.com/vercel/next.js/issues/53715

**Comment by argaen** [comment]
Oh, version 13.5.4, sorry for opening duplicate :/
