### ISSUE TITLE
How to change runtime node.js version in next.js SSR 

### ISSUE THREAD

**Issue by ArianHamdi** [aws-amplify/amplify-hosting#3757]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3akk1nl18rszx

### AWS Region

us-east-1

### Amplify Hosting feature

Build settings, Custom build image

### Question

I changed the Node.js version in the build settings for both Amazon Linux 2 and a custom build image. In both cases, I successfully changed the build Node.js version. However, when I checked the logs in CloudWatch, it showed that the Lambda function was running with Node.js 16 instead of 18, which I had set in the build settings.

How can I change the runtime version to 18 for Lambda?

**Comment by gangeshwark** [comment]
I am facing the same issue with NextJS 14. Next JS 14 drops support for Node 16 and requires at least Node v18.17 - https://nextjs.org/blog/next-14
This means Amplify can not run Nextjs 14 until the lambda environment is upgraded.

Is there a timeline on when Node 18.17 will be supported? Thanks!

**Comment by CoDanny** [comment]
It's being worked on according to: https://github.com/aws-amplify/amplify-hosting/issues/3773

**Comment by siegerts** [comment]
Hi @ArianHamdi and @gangeshwark , please see my comment here https://github.com/aws-amplify/amplify-hosting/issues/3773#issuecomment-1792971715 . Closing this to track the ongoing conversation in one place.
