### ISSUE TITLE
Amplify Deploy Stuck on  Updating Edge config (ap-southest-2)

### ISSUE THREAD

**Issue by Andy-FRAMD** [aws-amplify/amplify-hosting#3760]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3jtxsyf2djalv

### AWS Region

ap-southeast-2

### Amplify Hosting feature

Deployments

### Frontend framework

Angular

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

Deployment stuck Updating Edge config for the last 10 minutes.
![image](https://github.com/aws-amplify/amplify-hosting/assets/53776307/eb62ba7c-5492-403c-a9d7-d464a1fa5b73)

### Expected behavior

Deployment should complete within a few minutes.be completed

### Reproduction steps

I have cancelled 3 prior deployments each with varying issues. 

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by mauerbac** [comment]
Hello -- please open an aws support case if you are still experiencing issues.
