### ISSUE TITLE
Frontend build fails: amplify.sh: line 22: node: command not found

### ISSUE THREAD

**Issue by tanyageorgieva** [aws-amplify/amplify-hosting#3762]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1nw87xs6xnvpy

### AWS Region

us-east-1

### Amplify Hosting feature

Frontend builds

### Frontend framework

Other

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

The AWS Amplify Console Web Preview step on PRs started to fail with Frontend build failure: `[WARNING]: /codebuild/output/src2100266492/src/flows-sdk/amplify.sh: line 22: node: command not found` without changing build configurations.

### Expected behavior

The AWS Amplify Console Web Preview step should build successfully on git push.

### Reproduction steps

Git Push on PRs 

### Build Settings

```yaml
version: 1
frontend:
  phases:
    build:
      commands: [
          'pip install -r requirements-dev.txt',
          './run_build_docs.sh',
      ]
  artifacts:
    baseDirectory: /docs/build
    files:
      - '**/*'
  cache:
    paths: []
```

### Log output

<details>

```
     The HTML pages are in docs/build.
2023-10-19T10:33:40.370Z [INFO]: 3. Validating well-known backlinks exist
2023-10-19T10:33:40.370Z [INFO]: /codebuild/output/src2100266492/src/flows-sdk/docs/build/pages/python_packages.html validated to exist
                                 # Completed phase: build
2023-10-19T10:33:40.372Z [WARNING]: /codebuild/output/src2100266492/src/flows-sdk/amplify.sh: line 22: node: command not found
2023-10-19T10:33:40.373Z [ERROR]: !!! Build failed
2023-10-19T10:33:40.373Z [ERROR]: !!! Non-Zero Exit Code detected
2023-10-19T10:33:40.373Z [INFO]: # Starting environment caching...
2023-10-19T10:33:40.373Z [INFO]: # Environment caching completed
Terminating logging...


```

</details>

**Comment by tanyageorgieva** [comment]
Tried to open a PR for a new/another branch in the same repository, but the issue persists.

**Comment by Xavientois** [comment]
We are experiencing this issue as well. The build was working before and with no functional changes to our code or config, it now fails with this error:

```
/codebuild/output/src1338011394/src/asdfqwerty/amplify.sh: line 61: node: command not found
```

**Comment by jsarafajr** [comment]
This happens when you use a custom image that doesn't have node installed.

**Comment by Xavientois** [comment]
We use `public.ecr.aws/sam/build-python3.9:1` as the build container, so that makes sense. What I am confused about is the fact that it used to work fine, and nothing was changed on our end. Did AWS post about this change somewhere?

**Comment by thogerb** [comment]
Experiencing the same issue here. Fails all builds on same code as before. 

## When did the same code work?

17/10/2023 was last that we deployed with success. 

## When did the same code start to fail? 

19/10/2023 it started failing. Same code base.

**Comment by Jay2113** [comment]
Hi everyone 👋 , thanks for raising this with us and sorry for the inconvenience caused due to it.

We are actively investigating into this and will keep you posted with any updates.

**Comment by ferdingler** [comment]
We rolled back the defective commit on all regions. For those affected, we have notified your AWS accounts via [Health Dashboard](https://aws.amazon.com/premiumsupport/phd).

**Comment by Jay2113** [comment]
We have root caused the issue and it has been mitigated. Please redeploy your apps.

As mentioned by @ferdingler, we have also notified the impacted AWS accounts via the [Health Dashboard](https://aws.amazon.com/premiumsupport/phd). 
```
Between Oct 12 12:18 PM PT and Oct 20 09:11 AM PT we experienced increased build error rates with custom images. This issue has been resolved and the service is operating normally.
```
We really appreciate your continued patience and cooperation. Thank you.
