### ISSUE TITLE
Deployment stuck at provision step 

### ISSUE THREAD

**Issue by sheshkumarp** [aws-amplify/amplify-hosting#3763]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3dm7uqva9w8or

### AWS Region

eu-west-2

### Amplify Hosting feature

Deployments, Frontend builds, SSR, Webhooks

### Frontend framework

Vue

### Next.js version

NA

### Next.js router

N/A

### Describe the bug

Deployment stuck at provision step 

### Expected behavior

it should complete the provision step and go for the build

### Reproduction steps

1.  App connected with GitHub
2. App update via webhook
3. when webhook is called the amplify stuck to the provision state

<img width="1346" alt="image" src="https://github.com/aws-amplify/amplify-hosting/assets/16536881/7369d5d0-8415-4bbd-a434-3ed523c4f603">

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Jay2113** [comment]
Hi @sheshkumarp 👋 , in order to further troubleshoot your issue please reach out to the [AWS Support team]( https://aws.amazon.com/support) for additional assistance.

Thank you.
