### ISSUE TITLE
All environments on custom domains suddenly 404'ing with “x-cache: Error from cloudfront”

### ISSUE THREAD

**Issue by SoulAuctioneer** [aws-amplify/amplify-hosting#3769]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-2:904806167043:apps/d6pm27nn9t0e8

### Region

us-east-2

### Step

Accessing app via custom domain, e.g. https://app.datasightusa.com

### Status

404 

### Issue or question

All of our Amplify environments, with custom domains, have suddenly started 404'ing with the header response "X-Cache: Error from cloudfront". No code updates or configuration changes for over a month. App can still be accessed via its naked Amplify URL https://production.d6pm27nn9t0e8.amplifyapp.com/

### Error message

When I request e.g. app.datasightusa.com, I get the response:
Request URL: https://app.datasightusa.com/
Request Method: GET
Status Code: 404 Not Found
Remote Address: 65.8.161.58:443
Referrer Policy: strict-origin-when-cross-origin
Alt-Svc: h3=":443"; ma=86400
Content-Length: 0
Date: Mon, 23 Oct 2023 23:27:36 GMT
Server: AmazonS3
Via: 1.1 dee6f6319b26c06091b49860450185bc.cloudfront.net (CloudFront)
X-Amz-Cf-Id: U_MWxEuX5aYqBDcAtEYAqTQuwj44a0qWUx_P6qPqJa776pWVKFYYsA==
X-Amz-Cf-Pop: SFO53-C1
X-Cache: Error from cloudfront

### Additional information

Issues reported by previous customers appear to have been caused by issues within AWS itself, and were only resolved by the AWS support team making changes: 
- https://github.com/aws-amplify/amplify-hosting/issues/1745
- https://github.com/aws-amplify/amplify-hosting/issues/1130
- https://github.com/aws-amplify/amplify-hosting/issues/3755

**Comment by Jay2113** [comment]
Hi @SoulAuctioneer 👋 , thanks for raising this with us and sorry for the inconvenience caused due to it.

We are actively investigating into this and will keep you posted with any updates.

**Comment by Jay2113** [comment]
@SoulAuctioneer thank you for your continued patience.

We identified an issue with how custom domains resolve for your application. The issue has been resolved and the service is operating normally.

**Comment by SoulAuctioneer** [comment]
@Jay2113 thank you. I would like to ensure that this does not reoccur, and to submit a credit claim for downtime beyond SLA. It would be very helpful if you can confirm specifically what the issue was. I see a bot comment that I should open a new issue and reference this one, so I'll do that too.
