### ISSUE TITLE
Houston, there's a problem We are unable to process your request. Please reach out to your support representative.

### ISSUE THREAD

**Issue by oksanat** [aws-amplify/amplify-hosting#3770]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

011195323160

### AWS Region

us-east-1

### Amplify Hosting feature

Not Applicable

### Frontend framework

Web

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

I am following AWS tutorial https://aws.amazon.com/getting-started/hands-on/build-serverless-web-app-lambda-apigateway-s3-dynamodb-cognito/ and wanted to create AWS Amplify. However, I am getting

> Houston, there's a problem
> We are unable to process your request. Please reach out to your support representative.

when I click "Save and Deploy". I tried different regions and repositories.

### Expected behavior

Deployment process to start

### Reproduction steps

<img width="1792" alt="Screenshot 2023-10-24 at 13 58 36" src="https://github.com/aws-amplify/amplify-hosting/assets/380610/a95506d5-f14a-403a-ae02-d80e24295f71">

<img width="1792" alt="![Screenshot 2023-10-24 at 15 42 53" src="https://github.com/aws-amplify/amplify-hosting/assets/380610/b61f20b0-93b8-49f8-85c0-1880baa8da69">

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by camden-kid** [comment]
I have the same issue.

**Comment by Jay2113** [comment]
Hi @oksanat @camden-kid 👋 , in order to further troubleshoot your issue please reach out to the [AWS Support team]( https://aws.amazon.com/support) for additional assistance.

Thank you.
