### ISSUE TITLE
Support for Nodejs 18.18.2 as Nextjs 14.0.0 requires more than 18.17

### ISSUE THREAD

**Issue by adarsh-drishya** [aws-amplify/amplify-hosting#3773]
Hi everyone, we now have Node 18 available in the default Docker image for all builds! The version is pinned to `18.13.0`, which you can leverage by simply adding the `nvm use 18` command to your build spec.

Unfortunately, you will not be able to use Live Updates with Node 18 - So you will not be able to use any other minor/patch version of Node 18. This is because of a limitation with Amazon Linux 2, where Node 18 needs to be built from source. We have however built `18.13.0` from source and baked that into the image.

If you need any other minor/patch version of Node 18, please install it from source like so:
```
nvm install -s 18.x.x
```

Please note though that this will increase your build time.

_Originally posted by @Narrator in https://github.com/aws-amplify/amplify-hosting/issues/3109#issuecomment-1509264093_

**Comment by adarsh-drishya** [comment]
https://github.com/vercel/next.js/issues/57214 refer to this @Narrator

**Comment by Jay2113** [comment]
Hi @adarsh-drishya 👋 , thanks for raising this!

We are actively working on supporting Next 14 based apps on Amplify Hosting. Today, our compute runtime for SSR apps uses Node 16 by default and we are tracking this [breaking change](https://nextjs.org/blog/next-14#other-changes) for Next 14 and are working on supporting Node 18 in the runtime.

We will keep you posted with any updates on this thread.

**Comment by adarsh-drishya** [comment]
> Hi @adarsh-drishya 👋 , thanks for raising this!
> 
> We are actively working on supporting Next 14 based apps on Amplify Hosting. Today, our compute runtime for SSR apps uses Node 16 by default and we are tracking this [breaking change](https://nextjs.org/blog/next-14#other-changes) for Next 14 and are working on supporting Node 18 in the runtime.
> 
> We will keep you posted with any updates on this thread.

Node 16 is no longer maintained anyways, node 18 better be default. Thanks

**Comment by theo-staizen** [comment]
As of last week, the v20 has entered LTS. Is that compatible with Amazon Linux 2023 and available through nvm?

**Comment by guidovalente** [comment]
@theo-staizen I believe not - I've been able to work around limitations on the default build image (AWS's Amazon Linux 2), but the runtime still runs on node 16, and there seems to be no way to customize that. So even if you're able to build Node 18+, you're still limited to a runtime environment with Node 16.

If anyone's been able to find a way around this please share!

**Comment by masterbater** [comment]
> Hi @adarsh-drishya 👋 , thanks for raising this!
> 
> We are actively working on supporting Next 14 based apps on Amplify Hosting. Today, our compute runtime for SSR apps uses Node 16 by default and we are tracking this [breaking change](https://nextjs.org/blog/next-14#other-changes) for Next 14 and are working on supporting Node 18 in the runtime.
> 
> We will keep you posted with any updates on this thread.

Why not just use node 20, its the LTS not node 18

**Comment by kearfy** [comment]
Hey @Jay2113, is it possible to get any indication as to when support for node 18/20 will be released? Just a general idea if we're talking about days, weeks or months.

If not, I'll need to start to hack around the problem to get my application deployed again, which for obvious I would rather not do 😛 

Thanks and have a great week! ✨

**Comment by icesupawan** [comment]
> Hi @adarsh-drishya 👋 , thanks for raising this!
> 
> We are actively working on supporting Next 14 based apps on Amplify Hosting. Today, our compute runtime for SSR apps uses Node 16 by default and we are tracking this [breaking change](https://nextjs.org/blog/next-14#other-changes) for Next 14 and are working on supporting Node 18 in the runtime.
> 
> We will keep you posted with any updates on this thread.

+1

**Comment by Jens-n11** [comment]
+1
We are also really waiting for node >18.17 support for NextJS 14. 😬

**Comment by tarasowski** [comment]
+1

**Comment by jr-duarte** [comment]
+1

**Comment by maloyuso** [comment]
+1

**Comment by danshev** [comment]
+1

**Comment by MinnieMinwoo** [comment]
+1

**Comment by tarasowski** [comment]
Hey folks! Here is the working solution: https://github.com/aws-amplify/amplify-hosting/issues/3779#issuecomment-1789305362

**Comment by tarasowski** [comment]
@CoDanny at least I was able to get the app running back again. Sure it has to be fixed, but as a prelimenary solutioin I think it is worth trying.

**Comment by CoDanny** [comment]
@tarasowski some apps might work. However, the runtime node is not 18 so you can expect runtime errors  for sure. You might not have hit them yet or you app happens to not use the features that touch them but I would advise people to wait until the amplify team moves the runtime before updating to next 14

**Comment by siegerts** [comment]
Hi All (@tarasowski, @CoDanny , @adarsh-drishya) - The runtime environment has been updated to support Node 18.

To deploy, use a custom build image with Node v18.17. The hosting compute runtime will use the corresponding version of Node used to build the application. An example image to test/use with is: `public.ecr.aws/docker/library/node:18.17.0`.

We are prioritizing an update to the build image that will remove this custom image dependency.

**Comment by stefanofa** [comment]
> Hi All (@tarasowski, @CoDanny , @adarsh-drishya and others) 👋🏻 - The runtime environment has been updated to support Node 18.
> 
> To deploy, use a custom build image with Node v18.17. The hosting compute runtime will use the corresponding version of Node used to build the application. An example image to test/use with is: `public.ecr.aws/docker/library/node:18.17.0`.

@siegerts it only works with node 18.17.0 doesn't it? I just tried with node 20.9.0 and got the following error in the deploy step:
![image](https://github.com/aws-amplify/amplify-hosting/assets/9802152/762a8242-f86b-4674-977f-c9330ed10f4f)

**Comment by siegerts** [comment]
@stefanofa Yes, correct. Currently, to Node 18.

**Comment by kearfy** [comment]
Can confirm too that I am able to deploy my application with NextJS 14 now, after sorting our some other build issues! Thanks @siegerts ❤️

**Comment by kachkaev** [comment]
Can anyone share their `amplify.yaml` please? I understand the part when it is necessary to use `public.ecr.aws/docker/library/node:18.17.0` as a base image. When should we `npm -i -g @aws-amplify/cli`? is it prebuild phase or / build / frontend / etc. Or all?

 Context of my issue: https://github.com/aws-amplify/amplify-hosting/issues/3779#issuecomment-1792985986

**Comment by kachkaev** [comment]
It'd be great to see 18.18.2 available, not just 18.17.0. There are few closed CVEs in 18.17.0, [according to release notes](https://nodejs.org/en/blog/release/v18.18.2).

**Comment by stefanofa** [comment]
> It'd be great to see 18.18.2 available, not just 18.17.0. There are few closed CVEs in 18.18.2, [according to release notes](https://nodejs.org/en/blog/release/v18.18.2).

@kachkaev I tried using version `18.18.2` and the build was successful. However, I am not sure whether the runtime used after deployment is actually `18.18.2` or `18.17.0`.

**Comment by kachkaev** [comment]
@stefanofa, good to know! How did you get `@aws-amplify/cli` when using `node@18.18.2`? That's the only combination of versions that work for me in build image settings:

<img width=350 src="https://github.com/aws-amplify/amplify-hosting/assets/608862/f30164db-2378-4822-ad15-9e222b6b99b5" />

Bumping any of these versions [leads to build failure](https://github.com/aws-amplify/amplify-hosting/issues/3779#issuecomment-1792985986).

**Comment by stefanofa** [comment]
@kachkaev I'm not sure it will work, but have you tried removing the Amplify CLI version override?
I'm just using the following config:
![image](https://github.com/aws-amplify/amplify-hosting/assets/9802152/738a881f-5fea-4ce6-9c75-e68b9f155806)

However, I do not have a backend environment associated with the app on amplify, so if you do, the problem may depend on that.
![image](https://github.com/aws-amplify/amplify-hosting/assets/9802152/d7ae7b47-70f2-4007-8c81-3c183e2a91c0)

**Comment by kachkaev** [comment]
Yeah I tried removing overrides, but then I get this warning when building backend:

```
[WARNING]: /codebuild/output/src123/src/my-project/amplify.sh: line 45: amplify: command not found
```

and then this error when building frontend (next.js app):

```
Module not found: Can't resolve '../../aws-exports'
```

(this refers to `./src/aws-exports.js`)

I guess that lack of `@amplify/cli` during build means that `amplify pull --appId ...` does not run and therefore the file with credentials is missing.

That is healed when I define Amplify CLI override with build settings but it only works for Node 18.13.0 as base image and Amplify CLI 12.5.2. Bumping any of these breaks the build 🤷

**Comment by casewalker** [comment]
I had a setup working just fine earlier this week running Node.js 20 for both the Build and Deploy using a custom build image (`node:20-bullseye`), but now it is broken. This is pretty frustrating.

**Comment by siegerts** [comment]
> I had a setup working just fine earlier this week running Node.js 20 for both the Build and Deploy using a custom build image (`node:20-bullseye`), but now it is broken. This is pretty frustrating.

@casewalker the compute may have been defaulting to Node 16 in that case since 20 is/was not available. So your build was running with 20, but the runtime compute was 16. Is it possible to bump down to 18 as mentioned above and try? Also is this with Next 14?

**Comment by casewalker** [comment]
> @casewalker the compute may have been defaulting to Node 16 in that case since 20 is/was not available. So your build was running with 20, but the runtime compute was 16. Is it possible to bump down to 18 as mentioned above and try? Also is this with Next 14?

I am almost certain it was **not** running on 16, that it was indeed running on Node 20. Firstly, I am using Node's builtin `fetch` (without having `node-fetch` installed or imported), and this was only introduced in Node 18. Secondly, I have defined my engine to be >=20 in my package.json and I have the line `engine-strict=true` in .npmrc.

I deployed this code without issue earlier this week, and now with identical code (only updating unrelated environment variables) it fails on the deploy stage stating that Node 20 is not supported. So it seems pretty conclusive to me that I was able to run Node 20 previously (and it is still running because the new deploy failed), and now I cannot.

I can probably downgrade to Node 18. But why shouldn't Amplify support the Node 20 runtime?

**Comment by siegerts** [comment]
@casewalker Thanks for following up. Do you mind opening a new issue with this information? That way we have all of the information regarding your app to investigate.

**Comment by em1l1000** [comment]
> > @casewalker the compute may have been defaulting to Node 16 in that case since 20 is/was not available. So your build was running with 20, but the runtime compute was 16. Is it possible to bump down to 18 as mentioned above and try? Also is this with Next 14?
> 
> I am almost certain it was **not** running on 16, that it was indeed running on Node 20. Firstly, I am using Node's builtin `fetch` (without having `node-fetch` installed or imported), and this was only introduced in Node 18. Secondly, I have defined my engine to be >=20 in my package.json and I have the line `engine-strict=true` in .npmrc.
> 
> I deployed this code without issue earlier this week, and now with identical code (only updating unrelated environment variables) it fails on the deploy stage stating that Node 20 is not supported. So it seems pretty conclusive to me that I was able to run Node 20 previously (and it is still running because the new deploy failed), and now I cannot.
> 
> I can probably downgrade to Node 18. But why shouldn't Amplify support the Node 20 runtime?


I have to agree with what was said here. I'm pretty sure I was running 20.8.0 previously last week. Here's my screenshot to prove it:

<img width="1479" alt="image" src="https://github.com/aws-amplify/amplify-hosting/assets/106544880/8b42b7cf-e775-484a-bd74-c99234e3cb66">

Now when I try to redeploy this exact same version I get this error:

<img width="1238" alt="image" src="https://github.com/aws-amplify/amplify-hosting/assets/106544880/34cfed4a-aa13-461f-bcd5-e5f709b05f6d">

There was somekind of validation added to the deploy phase of AWS Amplify. Why was that necessary? I'm slightly annoyed because our app was suppose to go live after this weekend.

**Comment by siegerts** [comment]
@casewalker & @em1l1000, are these Next 14 apps?

The update that I posted was above is in reference to the Node 18 compute runtime requirement from Next 14. If these were Next apps <14 than then may have been building with Node > 16 but the execution in the compute runtime was using Node 16. This stopped working with Next 14 since the the minimum required versions bumped as per this issue title. Previously, there was not building/runtime environment matching - it was Node 16 by default.

As per @Jay2113's comment initially -
>Today, our compute runtime for SSR apps uses Node 16 by default and we are tracking this [breaking change](https://nextjs.org/blog/next-14#other-changes) for Next 14 and are working on supporting Node 18 in the runtime.

@em1l1000, this new validation is trying to match the build and compute runtimes with a compatible/supported Node version. This is now throwing the Error with 20 since you are using Node 20 in your build but that is not supported yet as a version in the compute runtime.

In both scenarios, although the build may have been using a different version of Node, the compute runtime for SSR apps _was_ using Node 16 by default.

I hope that this helps. For Node 20 support I have opened a separate feature request to track -https://github.com/aws-amplify/amplify-hosting/issues/3785 .

**Comment by em1l1000** [comment]
> @casewalker & @em1l1000, are these Next 14 apps?
> 
> The update that I posted above is in reference to the Node 18 compute runtime requirement from Next 14. If these were Next apps <14 than they may have been building with Node > 16 but the execution in the compute runtime was using Node 16 - this could be checked by logging out the Node version during SSR compute to the CloudWatch log stream. This stopped working with Next 14 since the the minimum required versions bumped as per this issue title. Previously, there was not building/runtime environment matching - it was Node 16 by default for the runtime.
> 
> As per @Jay2113's comment initially -
> 
> > Today, our compute runtime for SSR apps uses Node 16 by default and we are tracking this [breaking change](https://nextjs.org/blog/next-14#other-changes) for Next 14 and are working on supporting Node 18 in the runtime.
> 
> @em1l1000, this new validation is trying to match the build and compute runtimes with a compatible/supported Node version. This is now throwing the Error with 20 since you are using Node 20 in your build but that is not supported yet as a version in the compute runtime.
> 
> In both scenarios, although the build CI/CD may have been using a different version of Node, the compute runtime for SSR apps _was_ using Node 16 by default.
> 
> I hope that this helps. For Node 20 support I have opened a separate feature request to track -#3785 .

I'm running version 13.5.6. I actually tried to upgrade to 14 last week but ran into this issue: 
![image](https://github.com/aws-amplify/amplify-hosting/assets/106544880/a1c6a33d-070d-4849-b9dd-6c697b5a8c17)
This error only occurred during runtime (the build and deploy didn't show any error). I was asking the guys in the next.js discord channel why this was happening and they said that it's because of my node version that's outdated. But I was confused because this node version I'm using (20.8.0) is fairly recent so I was showed them exactly what I'm showing you in my post right up here ==> my docker is running 20.8.0. I then reverted back to 13.5.6 because I couldn't figure out what was wrong. We're one week later and I now understand that this is the AWS Amplify compute runtime that's apparently using node v16 by default. 

Couple of comments:

1. It would be nice if there was some mechanism to drive the compute runtime version. 
2. Also, I couldn't find any documentation on this. It's through the posts here that I learned that there's a difference between build time and run time node version.

**Comment by shawnseaton** [comment]
I have used a custom image 18.17.0 but my build is still failing with Module not found: Can't resolve '../src/aws-exports' .  I guess I would love to see someone's amplify.yml with a backend.  Here is mine:

version: 1
backend:
  phases:
    build:
      commands:
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip awscliv2.zip
        - ./aws/install
        - '# Execute Amplify CLI with the helper script'
        - npm install -g @aws-amplify/cli
        - amplifyPush --simple
        - amplify version
        
frontend:
  phases:
    preBuild:
      commands:
        - aws codeartifact login --tool npm --repository academy --domain skillquest --domain-owner XXXXXXXXXX --region us-east-1
        - npm ci
        - echo "# Running frontend build" > .env 
        - echo "NEXT_PUBLIC_CLOUDFRONT_COOKIE_DOMAIN=$NEXT_PUBLIC_CLOUDFRONT_COOKIE_DOMAIN" >> .env
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      
      
      Everything runs fine on the backend but during the frontend build I get.

023-11-04T23:12:22.115Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
                                 # Executing command: npm run build
2023-11-04T23:12:22.330Z [INFO]: > build
                                 > next build
2023-11-04T23:12:22.905Z [INFO]: ⚠ No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
2023-11-04T23:12:22.911Z [INFO]: Attention: Next.js now collects completely anonymous telemetry regarding usage.
2023-11-04T23:12:22.911Z [INFO]: This information is used to shape Next.js' roadmap and prioritize features.
                                 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
                                 https://nextjs.org/telemetry
2023-11-04T23:12:23.004Z [INFO]: ▲ Next.js 14.0.1
2023-11-04T23:12:23.005Z [INFO]: - Environments: .env
2023-11-04T23:12:23.005Z [INFO]: Creating an optimized production build ...
2023-11-04T23:13:08.308Z [WARNING]: Failed to compile.
2023-11-04T23:13:08.313Z [WARNING]: ./api/apolloClient.js
                                    Module not found: Can't resolve 'src/aws-exports'
                                    https://nextjs.org/docs/messages/module-not-found

**Comment by siegerts** [comment]
@shawnseaton any success with these versions  - https://github.com/aws-amplify/amplify-hosting/issues/3773#issuecomment-1793149762

**Comment by shawnseaton** [comment]
> @shawnseaton any success with these versions - [#3773 (comment)](https://github.com/aws-amplify/amplify-hosting/issues/3773#issuecomment-1793149762)?

I tried limiting Amplify to 12.5.2 like in the referenced comment (I can't limit to node 18.13 as I need at least 18.17 for Next 14 support) and it still received the same error message.  It is like 
`- amplifyPush --simple`

is not generating the amplify aws-exports for the backend environment.

**Comment by AkihiroTakamura** [comment]
I created a custom build image and built&deployed it from Amplify and succeeded in running Next.js14 with Amplify Hosting.

Dockerfile of build image looks like this

```Dockerfile
FROM amazonlinux:2023

RUN dnf install -y tar gzip unzip git

# aws-cli
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install

# nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash

# node
RUN . ~/.nvm/nvm.sh && nvm install 18.17.0

RUN echo -e "\
export NVM_DIR=\"\$HOME/.nvm\"\n\
[ -s \"\$NVM_DIR/nvm.sh\" ] && \. \"\$NVM_DIR/nvm.sh\"\n\
" >> ~/.bashrc

ENTRYPOINT [ "/bin/bash" ]

```

After building the Dockerfile and pushing it to public ECR, I specified it in the build image of amplify and built & deployed it.

![image](https://github.com/aws-amplify/amplify-hosting/assets/9854080/0c9103a1-643c-4be2-a333-5cdc6d96a505)

The amplify.yml did not need to be changed in any particular way

```yml
version: '1.0'
applications:
  - appRoot: frontend
    frontend:
      phases:
        preBuild:
          commands:
            - npm ci
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
          - .next/cache/**/*
```

**Comment by ronalddas** [comment]
Am using Nextjs `14.0.1` , even though it requires  ` node: '>=18.17.0'` , it still deployed  for me using the node 18.13 public image `public.ecr.aws/docker/library/node:18.13.0` and haven't run into any errors yet
![Screenshot from 2023-11-06 11-47-38](https://github.com/aws-amplify/amplify-hosting/assets/12792689/2846d5a2-fbde-402d-9090-feeab61e55b3) 
![Screenshot from 2023-11-06 11-48-03](https://github.com/aws-amplify/amplify-hosting/assets/12792689/343d476e-fc61-479c-929f-9ef5bba627f0)

**Comment by Develliot** [comment]
In stead of using nvm or installing different versions, of node would a better fix be to have a newer default images available for amplify like Amazon Linux 2023/2024

**Comment by casewalker** [comment]
Thanks @siegerts for continuing to track this issue. I posted a related question on Discord [here](https://discord.com/channels/705853757799399426/1171111306108076064).

**Comment by shawnseaton** [comment]
I finally got it working with Next.js 14.0.1 and Node 18.18.2.  Thanks to @AkihiroTakamura for setting me in the right direction.  I needed to also install amplify to get the backend working (Auth/GraphQL APIs that I already had before) so I modified the dockerfile to this:

`FROM amazonlinux:2023

RUN dnf install -y tar gzip unzip git

# aws-cli
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install

# nvm and node
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash

# Install node, npm and the global package
RUN echo 'export NVM_DIR="$HOME/.nvm"' >> $HOME/.bashrc && \
    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $HOME/.bashrc && \
    echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' >> $HOME/.bashrc && \
    . $HOME/.nvm/nvm.sh && \
    nvm install 18.18.2 && \
    npm install -g @aws-amplify/cli

# Start bash with NVM loaded
ENTRYPOINT [ "/bin/bash", "--login" ]`

and then uploaded to ECR public as suggested.

Then I changed my build settings to point to this container image in ECR public.

`public.ecr.aws/<your_alias>/node:18.18.2`

All is now working! Thank you guys!

**Comment by kachkaev** [comment]
Glad that you have found a working solution @shawnseaton!

While a custom docker image technically works, it’s too tedious to set up in each team for such a trivial need as running Next.js. This is a very popular framework, so I wish that Amplify team prioritises its built-in support for all of us. Hope that we can all benefit from the solution you have shared, just via an official image of some sort.

Amplify team, please find resources to resolve this problem – it’s quite massive given the popularity of Next.js 🙏

**Comment by hani-q** [comment]
> I finally got it working with Next.js 14.0.1 and Node 18.18.2. Thanks to @AkihiroTakamura for setting me in the right direction. I needed to also install amplify to get the backend working (Auth/GraphQL APIs that I already had before) so I modified the dockerfile to this:
> 
> `FROM amazonlinux:2023
> 
> RUN dnf install -y tar gzip unzip git
> 
> RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && ./aws/install
> 
> RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
> 
> RUN echo 'export NVM_DIR="$HOME/.nvm"' >> $HOME/.bashrc && echo '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"' >> $HOME/.bashrc && echo '[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"' >> $HOME/.bashrc && . $HOME/.nvm/nvm.sh && nvm install 18.18.2 && npm install -g @aws-amplify/cli
> 
> ENTRYPOINT [ "/bin/bash", "--login" ]`
> 
> and then uploaded to ECR public as suggested.
> 
> Then I changed my build settings to point to this container image in ECR public.
> 
> `public.ecr.aws/<your_alias>/node:18.18.2`
> 
> All is now working! Thank you guys!

I tried the same and i get  the below error in provision phase

[SINGLE_BUILD_CONTAINER_DEAD: Build container found dead before completing the build. Build container died because it was out of memory, or the Docker image is not supported]

**Comment by lyleunderwood** [comment]
Just want to say thanks for the quick turnaround on supporting v18 and Next.js 14. After lots of tinkering, I've got everything working at our org.

That being said, it seems like there are many issues with AWS Amplify that are deeply concerning. The fact that the node LTS release was not supported for so long is a little ridiculous. Hopefully AWS can add support for node 20 in a more reasonable timeframe. Issues like this make Amplify feel like an afterthought, has AWS decided that it is not viable as a product and moved it into minimal maintenance?

We would like to invest further in Amplify as it's a pretty good fit for what we're doing, but it's dubious right now whether it's a smart place to put our money.

**Comment by fdansey-ostmodern** [comment]
Reading about the [problems](https://github.com/aws-amplify/amplify-hosting/issues/3109) installing nodejs [18.17.0](https://github.com/vercel/next.js/blob/canary/package.json#L252C8-L252C8) on Amazon Linux 2, I also decided to create a [custom image](https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup), like @AkihiroTakamura .
I took [this](https://github.com/aws-amplify/amplify-hosting/blob/8a84e03/images/latest/Dockerfile) as my base Dockerfile and adapted it as necessary.  One could also take the Dockerfile from the provision step of an Amplify build in the AWS Console.

**Comment by shawnseaton** [comment]
> > I finally got it working with Next.js 14.0.1 and Node 18.18.2. Thanks to @AkihiroTakamura for setting me in the right direction. I needed to also install amplify to get the backend working (Auth/GraphQL APIs that I already had before) so I modified the dockerfile to this:
> > `FROM amazonlinux:2023
> > RUN dnf install -y tar gzip unzip git
> > RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && ./aws/install
> > RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
> > RUN echo 'export NVM_DIR="$HOME/.nvm"' >> $HOME/.bashrc && echo '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"' >> $HOME/.bashrc && echo '[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"' >> $HOME/.bashrc && . $HOME/.nvm/nvm.sh && nvm install 18.18.2 && npm install -g @aws-amplify/cli
> > ENTRYPOINT [ "/bin/bash", "--login" ]`
> > and then uploaded to ECR public as suggested.
> > Then I changed my build settings to point to this container image in ECR public.
> > `public.ecr.aws/<your_alias>/node:18.18.2`
> > All is now working! Thank you guys!
> 
> I tried the same and i get the below error in provision phase
> 
> [SINGLE_BUILD_CONTAINER_DEAD: Build container found dead before completing the build. Build container died because it was out of memory, or the Docker image is not supported]

The reason that it is failing is that you built an ARM image on your Apple Silicon Mac.  You need to build an Intel image with this command.

`docker build . --platform linux/amd64  `

**Comment by hani-q** [comment]
@

> > > I finally got it working with Next.js 14.0.1 and Node 18.18.2. Thanks to @AkihiroTakamura for setting me in the right direction. I needed to also install amplify to get the backend working (Auth/GraphQL APIs that I already had before) so I modified the dockerfile to this:
> > > `FROM amazonlinux:2023 RUN dnf install -y tar gzip unzip git RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && ./aws/install RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash RUN echo 'export NVM_DIR="$HOME/.nvm"' >> $HOME/.bashrc && echo '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"' >> $HOME/.bashrc && echo '[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"' >> $HOME/.bashrc && . $HOME/.nvm/nvm.sh && nvm install 18.18.2 && npm install -g @aws-amplify/cli ENTRYPOINT [ "/bin/bash", "--login" ]`
> > > and then uploaded to ECR public as suggested.
> > > Then I changed my build settings to point to this container image in ECR public.
> > > `public.ecr.aws/<your_alias>/node:18.18.2`
> > > All is now working! Thank you guys!
> > 
> > 
> > I tried the same and i get the below error in provision phase
> > [SINGLE_BUILD_CONTAINER_DEAD: Build container found dead before completing the build. Build container died because it was out of memory, or the Docker image is not supported]
> 
> The reason that it is failing is that you built an ARM image on your Apple Silicon Mac. You need to build an Intel image with this command.
> 
> `docker build . --platform linux/amd64 `

Thanks man, that worked,

But what are your build settings 
```

version: '1.0'
applications:
  - appRoot: frontend
    frontend:
      phases:
        preBuild:
          commands:
            - npm ci
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
          - .next/cache/**/*

```
?? same as above

**Comment by siegerts** [comment]
Hi All 👋🏻 - Just to follow up again - 

The Amazon Linux 2023 (AL2023) build image is now available in the **Edit build image settings**. This will remove the need for the custom build image workaround from above. You can select this as the image for your Next 14 apps instead.

![image](https://github.com/aws-amplify/amplify-hosting/assets/634958/e52e33a2-ffaf-43c6-ad8f-29590938f584)
