### ISSUE TITLE
Next.js 13 not rendering page - No error shown 

### ISSUE THREAD

**Issue by solgarcia2002** [aws-amplify/amplify-hosting#3782]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2jqmwpeqr6zpq

### AWS Region

us-east-1

### Amplify Hosting feature

Frontend builds

### Question

I was able to run my build and it looks everything it's ok but the page is blank https://main.d2jqmwpeqr6zpq.amplifyapp.com/

**Comment by evcodes** [comment]
Hey @solgarcia2002 have you taken a look at your logs? I assume this is working for you locally but not when you deployed it on Hosting?

**Comment by lukasulbing** [comment]
Hey I'm having the same issue right now. Did you solve the problem?

This is my first time deploying to Amplify. I have built my NextJs (v14.0.2) App, compressed the .next (build) folder and drag & dropped it into Amplify. But it just shows a blank page and the console logs show that it returns a 404 error.

**Comment by mauerbac** [comment]
Going to assume this is fixed as this is a stale issue
