### ISSUE TITLE
Redirects broken

### ISSUE THREAD

**Issue by raffclar** [aws-amplify/amplify-hosting#3787]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dfgwx0v13a7s4

### AWS Region

eu-west-2

### Amplify Hosting feature

Redirects

### Frontend framework

React

### Next.js version

N/A

### Next.js router

App Router

### Describe the bug

On Thursday 2nd November roughly around 6PM UTC we suddenly experienced a redirect loop with our website.

We investigated and discovered the cause of the redirect looping: our redirect rules that we haven't changed in almost a year. When we removed the rules, the looping stopped. We would like to restore the rules.

In the logs we saw this:

1. User goes to https://subdomain.devdomain.co.uk
2. User is redirected to https://subdomain.domain.co.uk
3. User is redirected from https://subdomain.domain.co.uk to https://subdomain.domain.co.uk again.
4. Redirects repeat until the browser stops the loop.

We've changed the domains and subdomains but here's what our rules used to look like:
```
[
    {
        "source": "https://subdomain.devdomain.co.uk/<*>”,
        "target": "https://subdomain.domain.co.uk/<*>",
        "status": "302",
        "condition": null
    },
    {
        "source": "https://subdomain.devdomain.co.uk",
        "target": "https://subdomain.domain.co.uk",
        "status": "302",
        "condition": null
    },
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    }
]
```

We now only have the third rule with the status 200. If we restore all three rules, the redirect loop returns.

### Expected behavior

When navigating to https://subdomain.devdomain.co.uk we expect it to go to https://subdomain.domain.co.uk
When navigating to https://subdomain.devdomain.co.uk/abc we expect it to go to https://subdomain.domain.co.uk/abc

There should be no looping.

### Reproduction steps

1. Add these redirect rules to your app. Change the domains to ensure they work.
   ```    {
        "source": "https://subdomain.devdomain.co.uk/<*>”,
        "target": "https://subdomain.domain.co.uk/<*>",
        "status": "302",
        "condition": null
    },
    {
        "source": "https://subdomain.devdomain.co.uk",
        "target": "https://subdomain.domain.co.uk",
        "status": "302",
        "condition": null
    },
   ```
2. Go to "source", (in the above that's https://subdomain.devdomain.co.uk)
3. Experience redirect looping!

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ferdingler** [comment]
Hi @raffclar , thanks for bringing this to our attention. We will look into what happened to your rewrite rules on Nov 2nd. But in the meantime, try keeping just the 1 rule without the `/<*>` placeholder. Basically these rules: 

```json
[
    {
        "source": "https://subdomain.devdomain.co.uk",
        "target": "https://subdomain.domain.co.uk",
        "status": "302",
        "condition": null
    },
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    }
]
```

You shouldn't get a redirect loop with these and you should still get the same redirect behavior on nested paths.
