### ISSUE TITLE
Problems with limits in AWS Amplify

### ISSUE THREAD

**Issue by GatlinTheWolf** [aws-amplify/amplify-hosting#3790]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

eu-central-1

### Amplify Hosting feature

Build settings, Manual deploys

### Frontend framework

Angular

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

I want to host the app in AWS Amplify, but I get a limit error.
Houston, there’s a problem
Failed to create app. You have reached the maximum number of apps in this account.
But we have all the apps. Help solve this problem, please.

### Expected behavior

Host application.

### Reproduction steps

1. Go to AWS Amplify
2. Host your web app
3. Deploy without Git provider

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ferdingler** [comment]
Hi, you are welcome to request a limit increase under the Service Quotas > Amplify > Apps. Quota code: L-1BED97F3.

**Comment by GatlinTheWolf** [comment]
But we haven’t used up the quota. We have 1 app, we want to host another
one, but it gives an error. Limit 25.

În mie., 8 nov. 2023 la 01:52, github-actions[bot] ***@***.***>
a scris:
