### ISSUE TITLE
Suddenly seeing 500's after re-deploying known working revisions

### ISSUE THREAD

**Issue by iamcgn** [aws-amplify/amplify-hosting#3793]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3r3cld460f6i7

### AWS Region

us-east-2

### Amplify Hosting feature

SSR

### Frontend framework

Next.js

### Next.js version

13.5.5

### Next.js router

Pages Router

### Describe the bug

After deploying a seemingly innocuous change to my dev environment I started getting 500's. Redeploying old versions that we were previously working does _not_ resolve the issue. The error in the compute logs show a readonly filesystem error: 
```
ln: failed to create symbolic link ‘/tmp/app/amplify-compute-bundle-output/amplify-compute-bundle-output’: Read-only file system

```

### Expected behavior

I expect to be able to deploy updates and/or revert to previous versions.

### Reproduction steps

1. Deploy anything
2. Notice a 500 response with readonly filesystem errors in the log.

### Log output

<details>

```
# Put your logs below this line
ln: failed to create symbolic link ‘/tmp/app/amplify-compute-bundle-output/amplify-compute-bundle-output’: Read-only file system

```

</details>

**Comment by iamcgn** [comment]
Looks like this issue was opened while I was writing mine. This appears to be the same issue: https://github.com/aws-amplify/amplify-hosting/issues/3792

**Comment by Jay2113** [comment]
Hi @iamcgn 👋 , thanks for raising this and apologies for the inconvenience caused due to this issue.

I am going to close this thread in favor of #3792 . Please track and monitor it for any further updates on the issue.
