### ISSUE TITLE
Failed to load static images in Next.js

### ISSUE THREAD

**Issue by ArianHamdi** [aws-amplify/amplify-hosting#3795]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3akk1nl18rszx

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments, Frontend builds

### Frontend framework

Next.js

### Next.js version

13.5.6

### Next.js router

Pages Router

### Describe the bug

Static images failed to load.

We just redeployed a branch, and now no static images are being loaded. This is the same for other newly connected branches.

There have been no changes in our code.

We believe it was working fine until yesterday.

### Expected behavior

Static images should load.

### Reproduction steps

1. Use the next `<Image />` component to render some static images.
2. Deploy the app on Amplify.
3. Check for any static images that failed to load.

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Jay2113** [comment]
Hi @ArianHamdi 👋 , thanks for raising this with us.

We are actively investigating into it and will keep you posted with any updates.

**Comment by Jay2113** [comment]
@ArianHamdi thanks for your continued patience.

Between 01:02 PM PST on Nov 8 and 8:18 AM PST on Nov 9, we experienced problems loading static images for Next.js apps. The issue has been resolved and the service is operating normally.
