### ISSUE TITLE
The maximum number of apps that you can create with Amplify in this region has likely been reached

### ISSUE THREAD

**Issue by aranoop** [aws-amplify/amplify-hosting#3798]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3lxmz7ucit4kv

### AWS Region

ap-south-1

### Amplify Hosting feature

Deployments

### Question

On deploying application we are getting an error
**The maximum number of apps that you can create with Amplify in this region has likely been reached:**
we are using only one app in this region. Our app quota was 25 and we had increased the same to 30 now. But still we are getting this above same warning message and the app is not getting build it is showing 
**The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.**

**Comment by Jay2113** [comment]
Hi @aranoop 👋 , thanks for reaching out. I observed that your Amplify app `d3lxmz7ucit4kv` has been deleted and based on the error message that you have shared it does seem like your build failed with an out of memory (OOM) error. If the issue persists or resurfaces, I'll recommend trying the workaround mentioned in this related 🧵 : https://github.com/aws-amplify/amplify-hosting/issues/3664#issuecomment-1690743995.
