### ISSUE TITLE
NodeJS 18 or 20

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-hosting#3802]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

123

### AWS Region

eu-west-3

### Amplify Hosting feature

Build settings

### Frontend framework

Angular

### Next.js version

123

### Next.js router

App Router

### Describe the bug

Hi,

For Angular 17, I need NodeJS 18 or 20 with Amplify hosting.
How to do ?

### Expected behavior

NodeJS 18 or 20.

### Reproduction steps

Oui.

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by siegerts** [comment]
Hi @rudyhadoux , closing this as resolved - please see the update here - https://github.com/aws-amplify/amplify-hosting/issues/3773#issuecomment-1811288919

**Comment by rudyhadoux** [comment]
The unique solution is : 
nvm use 18.
