### ISSUE TITLE
The size of the build output exceeds the max allowed size after Nextjs 14 Update

### ISSUE THREAD

**Issue by gstrobl** [aws-amplify/amplify-hosting#3804]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

ca-central-1

### Amplify Hosting feature

Frontend builds

### Question

Hey,
we updated Next to 14.0.2, with Custom Image (`public.ecr.aws/docker/library/node:18.17.0`). 

Now we're facing this issue:

`The size of the build output (235208983) exceeds the max allowed size of230686720 bytes. Please reduce the size ofyour build output and try again.`

If I check the file size local, I got this one here:
```
du -h -d 1
152M	./cache
 44M	./server
 60M	./static
260M	.
```

I'm not sure if it's possible to get rid of the cache folder after the successful build, I think many other people facing this issue, but I didn't found any solution yet.

**Comment by danielkoller** [comment]
I updated my build setting to the latest "Linux 2023" build and have the same problem with Next 14.0.2.

**Comment by Jay2113** [comment]
Hi @gstrobl @danielkoller 👋 , we have updated our documentation with a troubleshooting guide for the build output size limitation: https://docs.aws.amazon.com/amplify/latest/userguide/troubleshooting-ssr-deployment.html#build-output-too-large. This should enable you to:
- Download and inspect your build artifacts
- Measure the size of your `compute` and `static` directories
- Review the dependencies within the `node_modules` folder
- Delete the binaries that aren't required at runtime
