### ISSUE TITLE
Add tag to the resources created for amplify to more easily indentify.

### ISSUE THREAD

**Issue by sanchojaf** [aws-amplify/amplify-hosting#3805]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-2

### Amplify Hosting feature

Not Applicable

### Is your feature request related to a problem? Please describe:

Having issue figure out what S3 Bucket correspond with an specific amplify app

### Describe how you'd like this feature to work

I want to go to a bucket on s3, or cloud form, and filter by tag to find the corresponding resource to an specific amplify app.

**Comment by swaminator** [comment]
This is now available: https://docs.amplify.aws/react/build-a-backend/add-aws-services/tagging-resources/
