### ISSUE TITLE
Domain disabled with no reason

### ISSUE THREAD

**Issue by itsMeBruno** [aws-amplify/amplify-hosting#3810]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

https://us-east-1.console.aws.amazon.com/amplify/home?region=us-east-1#/d643zn3exdmsl

### AWS Region

us-east-1

### Amplify Hosting feature

Custom domain

### Frontend framework

React

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug
![image](https://github.com/aws-amplify/amplify-hosting/assets/104770403/71269e1d-4325-4e2f-9e07-d3e8942691b8)

After setup de project envs and connection with github I set up the domain configs. I choose my domain, amplify show me DNS address. I add the DNS config on cloudflare and CNAME starts do work correctly as you can see [App Link](https://ripiotrade.velotax.com.br/p/cadastrar )

After some days, week or sometimes hours, the CNAME stops do work  and it doesn't redirect to de application. I open amplify page and I see "Error connecting with domain." But the fun fact is that we have a load of applications using the same domain and just this one happens it.

So I have to remove the domain and add it again.

### Expected behavior

I should not accours this error connecting to the domain.

### Reproduction steps

N/A

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by arundna** [comment]
@itsMeBruno Apologies for the delay! I see that your app and domain is rendering fine on the link. Are you still experiencing problems with the domain?
