### ISSUE TITLE
AWS amplify React Web App deploy completes successfully but error 404 on access to website

### ISSUE THREAD

**Issue by MoDaCoder** [aws-amplify/amplify-hosting#3827]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d34nndegsdx4fm

### Region

us-east-1

### Step

Deployment

### Status

Deployment successful 

### Issue or question

I deploy my react app and the build is successful but when I click on the domain link it sends me to a 404 error page.
Can someone help me fix this and explain how to prevent it from it happening in the future please.
<img width="994" alt="Screen Shot 2023-11-25 at 2 02 45 PM" src="https://github.com/aws-amplify/amplify-hosting/assets/53015834/970d1f1e-b9dd-40c0-9794-49f16683fdbd">
<img width="1280" alt="Screen Shot 2023-11-25 at 2 03 24 PM" src="https://github.com/aws-amplify/amplify-hosting/assets/53015834/0e2d18bf-321b-413b-bded-acd5fe031df5">

### Error message

This main.d34nndegsdx4fm.amplifyapp.com page can’t be found No webpage was found for the web address: https://main.d34nndegsdx4fm.amplifyapp.com/
HTTP ERROR 404
<img width="1280" alt="Screen Shot 2023-11-25 at 2 03 24 PM" src="https://github.com/aws-amplify/amplify-hosting/assets/53015834/116214d5-bb90-4c7f-829c-ff30754a7db7">

### Additional information

Here is my package.json file code

```
{
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/plugin-proposal-private-property-in-object": "^7.21.11"
  },
  "name": "martinez-autobody-react",
  "version": "0.1.0",
  "homepage": "https://main.d34nndegsdx4fm.amplifyapp.com/",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "^5.0.1",
    "web-vitals": "^2.1.4"
  }
}
```

**Comment by revupai** [comment]
Hi, Were you able to resolve this issue?

**Comment by saranya-sreedharan** [comment]
I am facing the same issue. Has anyone been able to resolve it?

**Comment by saranya-sreedharan** [comment]
That issue resolved. Just clear the catche and try again that's only required

**Comment by MoDaCoder** [comment]
I tried clearing the cache but it didn't do anything.
Do you know of any other things that might work?

**Comment by MoDaCoder** [comment]
> Hi, Were you able to resolve this issue?

No I haven't been able to resolve it yet.
