### ISSUE TITLE
Angular Build - Fails no errors

### ISSUE THREAD

**Issue by ct5845** [aws-amplify/amplify-hosting#3831]
### Before opening, please confirm:

- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dd3snbh7adm98

### Region

eu-west-2

### Step

Build

### Status

Failed

### Issue or question

The build is currently failing, but I've got no indication as to why and/or what to do to fix it.

### Error message

This error appears to occur consistently about 4 minutes after the `ng build` command runs.
Last 2 lines of the log are;

```
2023-11-28T09:21:56.869Z [INFO]: > ngx-alterian@3.0.0 build
                                 > ng build
2023-11-28T09:21:58.096Z [WARNING]: - Generating browser application bundles (phase: setup)...
2023-11-28T09:26:04.995Z [WARNING]: /codebuild/output/src4215038211/src/ngx-alterian/amplify.sh: line 18:  2807 Killed                  npm run build
2023-11-28T09:26:05.081Z [ERROR]: !!! Build failed
2023-11-28T09:26:05.082Z [ERROR]: !!! Non-Zero Exit Code detected
2023-11-28T09:26:05.083Z [INFO]: # Starting environment caching...
2023-11-28T09:26:05.083Z [INFO]: # Environment caching completed
Terminating logging...
```

### Additional information

Based on random googling, updated the build image to `Linux 2023` and forced the node version to `18.8.2`, and tried to increase the Max Old Space size for node. But this seems to have zero effect on the error.

Build works fine locally, in bitbucket pipelines, in our CI Jenkins environment and via Vercel.

**Comment by himanshu-mobstac** [comment]
I'm also facing similar issue on amplify.

**Comment by Jay2113** [comment]
Hi @ct5845 👋 , thanks for reaching out. I observed that the latest build (88) on your Amplify app `dd3snbh7adm98` failed with `2828 Killed npm run build` which looks similar to the error message that you have shared and it seems like your build failed with an out of memory (OOM) error. 

For OOM errors, I'll recommend trying the workaround mentioned in this related 🧵 : https://github.com/aws-amplify/amplify-hosting/issues/3664#issuecomment-1690743995.
