### ISSUE TITLE
AMAZON makes additional request to my getAddress.io API

### ISSUE THREAD

**Issue by imceZZ** [aws-amplify/amplify-hosting#3835]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2l5ihtxfyb9ra

### AWS Region

eu-west-2

### Amplify Hosting feature

Backend builds, Frontend builds, SSR, Not Applicable

### Frontend framework

Next.js

### Next.js version

13.5.4

### Next.js router

App Router

### Describe the bug

I have builded my web-app in Next.JS 13.5.4 and I have hosted in AWS Amplify and also I have used ROUTE 53 for my domain from godaddy the problem is that when user lands to checkout page I have a section that it requires you to enter postcode when user enter's postcode I am firing API call to [getaddress.io](https://getaddress.io/) to get address details everything looks ok here but what it does in background AMAZON it makes additional request to my [getaddress.io](https://getaddress.io/) which this leads to charge me more for my usage in getaddress, I discovered this when I saw logs in [getaddress.io](https://getaddress.io/) that these ip addresses (3.235.103.192, 54.87.128.108) belongs to AMAZON because I checked from [here](https://iplocation.com/)

these are logs from [getaddress.io](https://getaddress.io/)

![Screenshot 2023-11-30 at 10 27 43](https://github.com/aws-amplify/amplify-hosting/assets/49072837/00a5f692-e38e-40fb-8639-42160c58ba86)

![Screenshot 2023-11-30 at 10 26 12](https://github.com/aws-amplify/amplify-hosting/assets/49072837/9126e198-e27e-4632-b795-28990586781d)

### Expected behavior

when user lands to my checkout page and when user makes search for postcode it should send only one request to my API [getaddress.io](https://getaddress.io/) not AMAZON to make additional request because like this I reach daily limit to quickly.

### Reproduction steps

there is not way to reproduce this issue because it happens on my web-app when user lands to checkout page and makes request for postcode to [getaddress.io](https://getaddress.io/) and in the background AMAZON makes another additional request to my API I saw these ip addresses (3.235.103.192, 54.87.128.108) from the logs of [getaddress.io](https://getaddress.io/)

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I need help for this problem because like this It reaches daily limit to fast and users can't order from my web-app.

**Comment by mauerbac** [comment]
Sorry for getting to this so late. Can you re-open if its still an issue?
