### ISSUE TITLE
DNS address could not be found. Diagnosing the problem. DNS_PROBE_POSSIBLE

### ISSUE THREAD

**Issue by Codebloater** [aws-amplify/amplify-hosting#3836]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1xit2ufxagk72

### Region

eu-north-1

### Step

Domain management

### Status

Available

### Issue or question

Custom Domain Management

### Error message

DNS address could not be found. Diagnosing the problem.
DNS_PROBE_POSSIBLE

### Additional information

i have purchased the Domain name from Hostinger and Hosted it on Route 53 and copied all 4 DNS configurations  and changed with Hostinger provided default DNS's. the Status is showing available but when directed to website URL then shows upper Error

**Comment by Jay2113** [comment]
Hi @Codebloater 👋 , thanks for reaching out. I observed that your Amplify app `d1xit2ufxagk72` has been deleted. 

That being said, if the issue resurfaces I would highly recommend reviewing this [article](https://repost.aws/knowledge-center/route-53-troubleshoot-nxdomain-responses) which outlines some potential root causes of the `DNS_PROBE_FINISHED_NXDOMAIN` error.
