### ISSUE TITLE
AWS Amplify not accepting backend env name

### ISSUE THREAD

**Issue by vikaskgahlawat** [aws-amplify/amplify-hosting#3842]
While creating a new aws amplify app, amplify does not use the name provided for backend environment. It always creates the backend with the name of the code commit branch.

**To Reproduce**
1. Go to AWS Amplify console.
2. Click on New App -> Host Web App.
3. Choose repository and branch and click Next. For example, branch name is "master".
4. In the "Select a backend environment to use with this branch" section, choose "Create New Environment".
5. For the backend environment, give any name other than the branch itself. For example: "prod"
6. Click on Next and create the app.

**Expected behavior**
A backend environment should be created with the name "prod"

**Actual behavior**
A backend environment namely "master" is created.

**Screenshots**
<img width="1004" alt="image" src="https://github.com/aws-amplify/docs/assets/64056565/da1dd087-b125-4cd9-8cdf-bef52f5f8ce0">

**Comment by kvramyasri7** [comment]
Facing the same issue from my side. Is there any update? @Milan-Shah @ArseniyKotov  from you guys @reesscot ?

**Comment by Jay2113** [comment]
We have identified this as a bug and are tracking it here: https://github.com/aws-amplify/amplify-hosting/issues/3745.

The workaround for now is to manually set the `USER_BRANCH` environment variable to the backend environment name that is being used during the app creation workflow. https://github.com/aws-amplify/amplify-hosting/issues/3745#issuecomment-1754139394
