### ISSUE TITLE
Error: The "target" property is no longer supported in next.config.js.

### ISSUE THREAD

**Issue by skylar-media** [aws-amplify/amplify-hosting#3844]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

arn:aws:amplify:us-east-2:030507554032:apps/d3k8hajyc65ts4

### AWS Region

us-east-2

### Amplify Hosting feature

Deployments, Frontend builds

### Frontend framework

Next.js

### Next.js version

14.0.2

### Next.js router

App Router

### Describe the bug

After modules update on our Test which includes Next.js from 12.3.4 to 14.0.2 and React 17.0.2 to 18.2.0 we began to face front-end build error "The "target" property is no longer supported in next.config.js." and the next.config.js does not contain any "target" properties within it at all. If we are trying to merge branches, the Live will not even try to build it.

We have our build image set to "Amazon Linux:2023" Next.js version to "latest" and Node.js version to "20 under Build Image settings on Amplify dashboards

https://nextjs.org/docs/messages/deprecated-target-config recommends as a **possible** way to solve this, switching to Vercel, but is there any alternatives that we can do?

### Expected behavior

We expected to see successful deployment.

### Reproduction steps

Just trying to build an app in a regular way.

### Log output

<details>

```
# Put your logs below this line
2023-12-06T19:10:06.112Z [ERROR]: [G[?25h[G[J
                                  22s › d3k8hajyc65ts4 › Error: Command failed with exit code 1: node_modules/.bin/next build
                                  > Build error occurred
                                  Error: The "target" property is no longer supported in next.config.js.
                                  See more info here https://nextjs.org/docs/messages/deprecated-target-config
                                  at loadConfig (/codebuild/output/src4040508740/src/skylar-media-website/node_modules/next/dist/server/config.js:744:19)
                                  at async Span.traceAsyncFn (/codebuild/output/src4040508740/src/skylar-media-website/node_modules/next/dist/trace/trace.js:140:20)
                                  at async /codebuild/output/src4040508740/src/skylar-media-website/node_modules/next/dist/build/index.js:192:28
                                  at async Span.traceAsyncFn (/codebuild/output/src4040508740/src/skylar-media-website/node_modules/next/dist/trace/trace.js:140:20)
                                  at async build (/codebuild/output/src4040508740/src/skylar-media-website/node_modules/next/dist/build/index.js:187:29)
                                  at async main (/codebuild/output/src4040508740/src/skylar-media-website/node_modules/next/dist/bin/next:150:5)
                                  [G[?25h
Terminating logging...

```

</details>

### Additional information

**Comment by viniciuslagedo** [comment]
Hello, maybe you can try to use the custom build image `amplify:al2023` instead of linux2023
Reference: https://aws.amazon.com/blogs/mobile/6-new-aws-amplify-launches-to-make-frontend-development-easier/

**Comment by skylar-media** [comment]
> Hello, maybe you can try to use the custom build image `amplify:al2023` instead of linux2023 Reference: https://aws.amazon.com/blogs/mobile/6-new-aws-amplify-launches-to-make-frontend-development-easier/

Hello, thanks for your reply. We already are using al:2023.
<img width="785" alt="image" src="https://github.com/aws-amplify/amplify-hosting/assets/102713917/a36ec026-f900-4c34-b5c4-7c8f0d78bc63">

**Comment by matamatanot** [comment]
#3840
