### ISSUE TITLE
2023-12-09T04:48:24.806Z [ERROR]: !!! CustomerError: Artifact directory doesn't exist: build

### ISSUE THREAD

**Issue by Zyculous** [aws-amplify/amplify-hosting#3848]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1qt02vx5mp6zb

### AWS Region

us-east-2

### Amplify Hosting feature

Build settings, Deployments, Redirects

### Question

![image](https://github.com/aws-amplify/amplify-hosting/assets/69947837/0ddd7115-44ee-49b4-a500-4989a0961beb)
This is the structure of the project file, including a build 

![image](https://github.com/aws-amplify/amplify-hosting/assets/69947837/b3305172-1d58-42e4-a8d7-19369d710b0f)
this is the amplify.yml file

**Framework:** React

I'm not sure what exactly is happening, the project structure is slightly off from regular 

I've tried multiple other paths 
- /
- \build
- \client\build

'/' worked but it had the problem of constantly rerouting me which I couldn't find a way to fix and assumed my build file was still the issue 

I assume the issue is the baseDirectory from what I have found but I don't know what it should be

**Comment by asteriskpro** [comment]
hello  @Zyculous I hope you doing well, so about your issue, can you add  buildPath  ?

**Comment by mauerbac** [comment]
Are you still needing help? can you open a support case so we can get your exact details
