### ISSUE TITLE
Build_Folder_Non_Zero_Exit_Code

### ISSUE THREAD

**Issue by mcdeagles** [aws-amplify/amplify-hosting#3849]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-1

### Amplify Hosting feature

Build settings

### Frontend framework

JavaScript

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

Front End BUILD FAILED, NON ZERO EXIT CODE DETECTED. Tried to update build settings to choose proper artifact folder. Decided to create folder during prebuild and move files in. 

### Expected behavior

Build was supposed to succeed.

### Reproduction steps

1. Modify build settings artifact field to build root directory.
2. Run Build
3. Non Zero Exit code

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
        - mkdir -p build
        - cp * build -r
        
    # IMPORTANT - Please verify your build commands
    build:
      commands: []
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line
                                 # Starting phase: preBuild
                                 # Executing command: npm ci
2023-12-10T01:59:46.403Z [INFO]: added 9 packages, and audited 10 packages in 2s
2023-12-10T01:59:46.405Z [INFO]: 1 package is looking for funding
                                 run `npm fund` for details
                                 found 0 vulnerabilities
2023-12-10T01:59:46.409Z [INFO]: # Executing command: mkdir -p build
2023-12-10T01:59:46.413Z [INFO]: # Executing command: cp * build -r
2023-12-10T01:59:46.417Z [WARNING]: cp: cannot copy a directory, ‘build’, into itself, ‘build/build’
2023-12-10T01:59:46.482Z [ERROR]: !!! Build failed
2023-12-10T01:59:46.482Z [ERROR]: !!! Non-Zero Exit Code detected
2023-12-10T01:59:46.482Z [INFO]: # Starting environment caching...
2023-12-10T01:59:46.482Z [INFO]: # Environment caching completed
Terminating logging...

```

</details>

### Additional information

Question: How do you find the root build directory to use in the artifact build setting. I created my own build folder instead.

**Comment by Jay2113** [comment]
Hi @mcdeagles 👋 , thanks for reaching out. The default build directory for your app will vary based on your app framework. For example, if you are building a react app via CRA it will generate a `build` directory for your artifacts when you do a production build via `npm run build`. If you want to use a custom folder instead of `build` for the output, you can achieve this via either of the methods:
- Modify the build script in the `package.json` file: https://create-react-app.dev/docs/advanced-configuration 
- Move the `build` folder post the build process:
```
build:
  commands:
     - npm run build
     - mkdir -p custom_folder
     - mv build custom_folder
  artifacts:
    baseDirectory: custom_folder
```
