### ISSUE TITLE
Custom headers issue on two different hosting environments

### ISSUE THREAD

**Issue by CCGRegaltest** [aws-amplify/amplify-hosting#3850]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

arn:aws:amplify:ap-northeast-1:476944795571:apps/d33dvg9x53pe0j

### AWS Region

ap-northeast-1

### Amplify Hosting feature

Custom domain

### Frontend framework

Other

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

My app has 2 environments. One is "main" (for production) and the other one is "staging".
After I created a new custom header by edit the customHttp.yml on AWS portal UI, main will auto take effect immediately about the new headers while staging will take effect until the app be redeployed.
Why there are difference between two environments?

### Expected behavior

Both should need redeploy to let them taking effect the new headers.

### Reproduction steps

1. Create new custom headers in AWS Amplify console and Save.
2. Staging environment takes effect while main will not.

### Log output

N/A

### Additional information

N/A

**Comment by mauerbac** [comment]
Are you able to open a support case so we can look at the exact details of your app? Thank you
