### ISSUE TITLE
In Next.js, when using the fetchAuthSession method from the aws-amplify library, the token information obtained is decoded by default. However, you wish to obtain the undecoded JSON web token (JWT), specifically to access the raw JWT returned by the OAuth 2.0 token endpoint at /oauth2/token.

### ISSUE THREAD

**Issue by itlhq-first** [aws-amplify/amplify-hosting#3852]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

eu-west-3

### Amplify Hosting feature

Public APIs

### Question

To use the fetchAuthSession method in a Next.js project with AWS Amplify and obtain the accessToken without JWT decoding, I want to receive the raw JWT returned by the OAuth 2.0 token endpoint without any transformation or decoding.

**Comment by chinthaka-dinadasa** [comment]
Try accessToken.toString()

**Comment by mauerbac** [comment]
Is this still an issue? Going to close and feel free to re-open
