### ISSUE TITLE
I made an amplify app in the Stockholm region and I want to move I to the London region.

### ISSUE THREAD

**Issue by UyiAguebor** [aws-amplify/amplify-hosting#3856]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2n0da8zljxad

### AWS Region

eu-north-1

### Amplify Hosting feature

Not Applicable

### Question

I want to move this app to the London region as its closest to me how do I do this as the AWS amplify app is currently on the Stockholm region

**Comment by mauerbac** [comment]
To move regions you will need to delete it from one region and re-create in the other. You can re-link the repo and add the proper settings by pattern matching from the old region. There is no feature to move it
