### ISSUE TITLE
SSR Image Optimization Feature - unable to deploy

### ISSUE THREAD

**Issue by alexnguyennz** [aws-amplify/amplify-hosting#3873]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1palg3fcdvx2w

### AWS Region

us-east-1

### Amplify Hosting feature

SSR

### Question

Hi I'm having issues deploying a project using a deploy manifest with Image Optimization routes and settings. 

For example, using the default examples from [this page](https://docs.aws.amazon.com/amplify/latest/userguide/image-optimization.html#integrate-image-optimization-framework) and [this one](https://docs.aws.amazon.com/amplify/latest/userguide/ssr-deployment-specification.html) (under "The following example demonstrates the imageSettings attribute"):

```ts
// have omitted other routes and the required settings e.g. `computeResources`, `framework`
{
          version: 1,
          routes: [
            {
              path: "/images/*",
              target: {
                kind: "ImageOptimization",
                cacheControl: "public, max-age=31536000, immutable",
              },
            },
          ],
          imageSettings: {
            sizes: [100, 200],
            domains: ["example.com"],
            remotePatterns: [
              {
                protocol: "https",
                hostname: "example.com",
                port: "",
                pathname: "/**",
              },
            ],
            formats: ["image/webp"],
            minumumCacheTTL: 60,
            dangerouslyAllowSVG: false,
          }
        }
```

leads to an error of `We failed to validate the deploy-manifest.json file found in your build output directory - An invalid 'deploy-manifest.json' file was provided.`. I've tried a few different variations but am not able to get past this error. Any idea what needs to be changed?

Thanks for any assistance.

**Comment by gentksb** [comment]
Did you define compute route?

> If you specify an ImageOptimization route, you must also specify a Compute route. This is required because image optimization is not yet supported for purely static applications.
https://docs.aws.amazon.com/amplify/latest/userguide/ssr-deployment-specification.html

**Comment by alexnguyennz** [comment]
Hi I found out a few months ago that this was actually due to a typo in the AWS documentation example for the spec so that was throwing off the build. Forgot about this issue. Thanks.
