### ISSUE TITLE
CNAME Already Exists

### ISSUE THREAD

**Issue by ctostech** [aws-amplify/amplify-hosting#3874]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dnw2a5ofhsf5a

### Region

me-south-1

### Step

Domain Activation

### Status

Failed

### Issue or question

I'm trying to connect my custom domain but I got the below message, I don't have any other AWS accounts and the DNS provider is CloudFlare.
Please advise

### Error message

Error message: [CNAMEAlreadyExistsException] The following CloudFront distributions or Amplify Apps are already using one or more of your domains: [Distribution: *******5PKHKGQ in AWS Account: ******076848]. For distributions you own, please remove the domains from them first and then retry adding your domain. For Amplify apps you own, you may already have associated this domain to another Amplify App in another account or region. You can also check our troubleshooting guide for more help: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html

**Comment by arundna** [comment]
@ctostech Apologies for the delayed response! Upon investigating, I'm unable to locate the app ID - dnw2a5ofhsf5a. Can you please confirm if you're still running into the issue and the right app ID? Thanks!

**Comment by starttechdev** [comment]
@arundna Thanks for your response but I removed the app and did a workaround. But anyways the issue still exists

**Comment by mauerbac** [comment]
@starttechdev - are you able to open up a support ticket so we can work with you directly?
