### ISSUE TITLE
Custom subdomains stopped being created for new branches (re-opened)

### ISSUE THREAD

**Issue by tonycassara** [aws-amplify/amplify-hosting#3875]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1h6e93qbxs4wx

### Region

us-east-1

### Step

Preview url with custom domain

### Status

Fails to create

### Issue or question

We use custom subdomains for our preview builds. E.g.; https://pr-1111.customdomain.dev. These are auto-generated for each new branch. As of yesterday evening, the preview builds are defaulting to amplify urls. E.g; https://pr-1111.cccc.amplifyapp.com. Nothing has changed on our side. Settings seem fine and if we manually add a subdomain from Domain Management page, it works.

### Additional information

See existing issue that was closed before. This is the exact same problem: https://github.com/aws-amplify/amplify-hosting/issues/3774

**Comment by mcd-janan** [comment]
Hi @Jay2113 

It looks like you were able to support us with this issue when it was reported in #3774. 

Would you be able to assist with looping in someone to investigate this further? It's been two weeks since this issue has been opened, so we're hoping to get this resolved ASAP!

Thanks in advance,
Janan

**Comment by rickbergfalk** [comment]
More info that might help troubleshooting for folks at AWS - we're seeing a lot of old `amplifyapp.com` preview URLs sticking around after PRs have been merged and branch deleted. Clean up of old preview builds is not consistently happening.

**Comment by rickbergfalk** [comment]
More updates - It seems our environment is inconsistently broken. A PR that is missing its custom domain does not allow for one to be manually created.

Opening a new branch and new PR results in a proper custom domain preview build.

Some branches/PRs are working. Some are not.

Would very much appreciate if someone could look into what is going on.

**Comment by tonycassara** [comment]
I just opened a new branch and the domain did not successfully create, and adding it manually does not apply to subsequent amplify builds trying to kick off our CI as a follow up task.

**Comment by arundna** [comment]
@tonycassara - Apologies for the delay! We're investigating this issue under priority and will keep you posted with updates.

**Comment by tonycassara** [comment]
@arundna Unfortunately minutes before your reply I accidentally deleted the Amplify App we were trying to fix and now we're unable to reconnect the subdomain.

**Comment by arundna** [comment]
@tonycassara - Could you try again after an hour? https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error

In the meantime, we have identified a fix for the subdomain issue and will update once it's complete. Thanks!

**Comment by tonycassara** [comment]
@arundna it's been nearly 2 hours, still not connecting. I see the CNAME added to Route 53, but I think the old Amplify app is not letting go of the domain.

**Comment by tonycassara** [comment]
Okay we're back up and operational, hopefully the auto branch deletion can be fixed.

**Comment by victorccccc** [comment]
Hi @tonycassara, sorry for the inconvenience. This issue has now been resolved.

**Comment by arundna** [comment]
@tonycassara We have fixed the issue and verified your app is working as expected. Can you please check and let us know if everything works? Thanks!
