### ISSUE TITLE
Getting this error "!!! CustomerError: It looks like you are attempting to deploy a Next.js SSR app, but your app's framework looks wrong. Please update your app's framework to 'Next.js - SSR' to ensure that your app is deployed correctly." any support appreciated. thanks

### ISSUE THREAD

**Issue by azhar-rayn** [aws-amplify/amplify-hosting#3877]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

ap-southeast-1

### Amplify Hosting feature

Monorepo

### Question

My main branch is configured and app is running fine, but the sub domain that I am trying to serve from dev branch is failing with error "!!! CustomerError: It looks like you are attempting to deploy a Next.js SSR app, but your app's framework looks wrong. Please update your app's framework to 'Next.js - SSR' to ensure that your app is deployed correctly."
Any feedback/support is really appreciated

**Comment by yangtopia** [comment]
I resolved it with the following command.

`aws amplify update-branch --app-id {APP_ID} --branch-name {BRANCH_NAME} --framework 'Next.js - SSR'`

I hope this helps.

**Comment by tigercat1124** [comment]
It worked for me too!!

> I resolved it with the following command.
> 
> `aws amplify update-branch --app-id {APP_ID} --branch-name {BRANCH_NAME} --framework 'Next.js - SSR'`

**Comment by panachainy** [comment]
> I resolved it with the following command.
> 
> `aws amplify update-branch --app-id {APP_ID} --branch-name {BRANCH_NAME} --framework 'Next.js - SSR'`
> 
> I hope this helps.

+1

**Comment by PhilipWee** [comment]
I am facing this same issue but I am deploying a react app. Is there any way to resolve it?

**Comment by alexff91** [comment]
> It worked for me too!!
> 
> > I resolved it with the following command.
> > `aws amplify update-branch --app-id {APP_ID} --branch-name {BRANCH_NAME} --framework 'Next.js - SSR'`
> 
> In my case, the issue was caused when the framework changed to `Web` due to the content of the code when I switched from the develop branch to the main branch.
> 
> ![image](https://private-user-images.githubusercontent.com/51685193/317266886-8c131b81-2428-46bf-a81d-88d294738377.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MjMxMjUsIm5iZiI6MTcxNTcyMjgyNSwicGF0aCI6Ii81MTY4NTE5My8zMTcyNjY4ODYtOGMxMzFiODEtMjQyOC00NmJmLWE4MWQtODhkMjk0NzM4Mzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDIxNDAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZGJlYWEzY2Q0NjIyYmU0OThkZjRiM2Y0YzE0YzI3YTU1OTI1ODk2NzJjODRlZmQwYmVmNDY3ODBmNTVmZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gMvDnNOMVWdxtb_-cS44tJV5IYT-9iYFsoJ2Tzp9VNA)

for me worked only when I added the region like 
`aws amplify update-branch  --app-id d1rudbio41kj5x --branch-name main --framework 'Next.js - SSR' --region ap-southeast-1`

**Comment by pvhuwung** [comment]
### You can use the AWS CLI to solve this, remember to create an IAM account with the correct provision rules to work with Amplifier

1. Run the following AWS CLI commands
```
aws amplify update-app --app-id <APP_ID> --platform WEB --region <REGION>
aws amplify update-branch --app-id <APP_ID> --branch-name <BRANCH_NAME> --framework 'Next.js - SSR' --region <REGION>
```

2. Update your build spec to point the `baseDirectory` to `out`. e.g.

```
version: 1
frontend:
  ...
  artifacts:
    baseDirectory: out
  ...
```

3. Trigger rebuild through commit, or manually

4. You ready to go
