### ISSUE TITLE
Unable to add/update/remove subdomain from domain management

### ISSUE THREAD

**Issue by MikeMozol** [aws-amplify/amplify-hosting#3878]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2yedo25udegu5

### Region

us-east-2

### Step

Remove subdpmain

### Status

Failed

### Issue or question

Our app is hosted on amplify and we utilize domain management to create and remove subdomains programmatically using AmazonAmplifyClient (c# .net) with `GetDomainAssociationAsync` and `UpdateDomainAssociationAsync`.  Recently we are receiving the following error "Cannot update domain while the domain is in UPDATING status." when adding/removing subdomains. This  same error can also be seen in the AWS Amplify Web console > Domain Management > Manage Subscriptions when trying to remove a subdomain.

What is causing this error to occur or how can we troubleshoot it to further mitigate this problem?

<img width="1147" alt="Screen Shot 2023-12-22 at 9 22 46 PM" src="https://github.com/aws-amplify/amplify-hosting/assets/117678051/89390eb8-b46e-4780-8885-6d872623fe96">

### Error message

Cannot update domain while the domain is in UPDATING status.

**Comment by bmccann36** [comment]
I think we may be experiencing something similar. We have preview environments set up to auto-create based on branch names. They used to automatically disconnect but now they do not. Also when I try to remove them manually I get the message described in this bug report. 

![Screenshot 2024-01-04 at 10 22 52 AM](https://github.com/aws-amplify/amplify-hosting/assets/28324264/ec022de0-af16-456d-982f-da03e144acce)

![Screenshot 2024-01-04 at 10 22 40 AM](https://github.com/aws-amplify/amplify-hosting/assets/28324264/694a2891-7ff9-402f-bac7-cd28b5856f60)

**Comment by arundna** [comment]
@MikeMozol @bmccann36 - We're actively investigating this issue and will keep you posted with updates.
