### ISSUE TITLE
My website showing a 404 error

### ISSUE THREAD

**Issue by AkshitDiesel** [aws-amplify/amplify-hosting#3883]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d32tizva3n1m9j

### Region

ap-south-1

### Step

Domain Activation

### Status

Available

### Issue or question

My domain is live and so is my website I believe, but I'm getting a 404 error when I'm trying to access my website.

### Error message

This www.carrelinarctic.com page can’t be foundNo webpage was found for the web address: https://www.carrelinarctic.com/
HTTP ERROR 404

**Comment by xkeshav** [comment]
check the rewrite and redirect settings
it should set 

https://domain.com https://www.domain.com  to 302 redirect

**Comment by AkshitDiesel** [comment]
Hi Keshav... Thanks for your reply. However, the actual problem as I figured out from StackOverflow was that the name of the HTML file must be "index.html" while I was using another name and therefore the error.
