### ISSUE TITLE
Support for Nodejs 18.18.2 as Nextjs 14.0.0 requires more than 18.17 - document properly workaround

### ISSUE THREAD

**Issue by OperationalFallacy** [aws-amplify/amplify-hosting#3884]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Backend builds

### Is your feature request related to a problem? Please describe:

https://github.com/aws-amplify/amplify-hosting/issues/3773#issuecomment-1811288919

There was a comment with workaround, but the image is broken. Also these kind of problems should be documented officially, no?  

![image](https://github.com/aws-amplify/amplify-hosting/assets/62673610/c428e88f-4784-486a-b4d6-9a8636fdb241)

@siegerts could you explain it again?

### Describe how you'd like this feature to work

Have workarounds in one place, rather then spread in github issues.

**Comment by arundna** [comment]
@OperationalFallacy - Thanks for reporting this issue. This GitHub repository only accepts new feature requests as described in the [README](https://github.com/aws-amplify/amplify-hosting/blob/main/README.md). 

For the workaround, the image in the comment is rendering properly - I've attached it here for reference. You are spot on with the documentation updates in a single place and we have documented it in our launch blog post for [Next.js 14 support](https://aws.amazon.com/blogs/mobile/6-new-aws-amplify-launches-to-make-frontend-development-easier/). We also have an open PR to update this in our documentation site - https://github.com/aws-amplify/docs/pull/6714. Once this is merged, we will have the required information in Amplify documentation site.

<img width="265" alt="al2023-1" src="https://github.com/aws-amplify/amplify-hosting/assets/84913786/6697d164-2abd-4af1-917a-4a9eade4ad32">
![al2023-2](https://github.com/aws-amplify/amplify-hosting/assets/84913786/fe086a50-317f-4742-ac42-0e1cda133303)

**Comment by OperationalFallacy** [comment]
Thank you!
