### ISSUE TITLE
Next auth error in nextjs app 

### ISSUE THREAD

**Issue by ALFAMODO** [aws-amplify/amplify-hosting#3887]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Access control, Deployments, Environment variables

### Is your feature request related to a problem? Please describe:

I hosted my next js application on AWS Amplify. However, when I am trying to sign in to my application which significantly uses next-auth functionality, it throws an error and does not call it accordingly. When I do the same execution in other cloud hosting services like Digital Ocean, it works perfectly fine.

Kindly help me to solve this issue if it is about redirecting or any environmental variable problems. 

### Describe how you'd like this feature to work

<img width="1470" alt="Screenshot 2023-12-31 at 2 52 47 PM" src="https://github.com/aws-amplify/amplify-hosting/assets/126672243/338e7ee5-f662-4a07-9e9f-10b959d79dac">

**Comment by Jay2113** [comment]
@ALFAMODO 👋 , This repository only accepts new feature requests for AWS Amplify Hosting. For technical support, we encourage you to open a case with [AWS technical support](https://docs.aws.amazon.com/awssupport/latest/user/case-management.html#creating-a-support-case) if you have AWS support plan. If you do not have an active AWS support plan, we encourage you to leverage our Amplify community [Discord server](https://discord.gg/amplify) where community members and staff try to help each other with Amplify.
