### ISSUE TITLE
Custom domain stuck on SSL config / Err 403 / All DNS records look good

### ISSUE THREAD

**Issue by badvik83** [aws-amplify/amplify-hosting#3888]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Frontend builds

### Is your feature request related to a problem? Please describe:

I have a domain with namecheap.com and I don't use Route53. I successfully deployed my custom domain (nadiahope.com) with Amplify and it's opening at:
https://dev8901.djaiq6dooqujo.amplifyapp.com/
However, it's stuck at SSL Configuration (although SSL certificate is shown as issued when I go to https://nadiahope.com) and the site itself won't open, pointing at cloudfront. A DNS CNAME check returns all green checks.
![Untitled](https://github.com/aws-amplify/amplify-hosting/assets/152312982/43b2bb09-36ef-4dae-bf81-61f03703a4cc)

p.s. I also have WorkMail and the MX record set up and this works properly.
![Untitled2](https://github.com/aws-amplify/amplify-hosting/assets/152312982/64cb6b0d-a418-4e47-9d16-2404ba523a49)

### Describe how you'd like this feature to work

Site should open

**Comment by arundna** [comment]
@badvik83 - 👋 I'm unable to locate your app ID - djaiq6dooqujo in our service. I did see that https://nadiahope.com/ is rendering correctly. Do you have the right app ID for your app that can help to investigate further?

**Comment by badvik83** [comment]
> @badvik83 - 👋 I'm unable to locate your app ID - djaiq6dooqujo in our service. I did see that https://nadiahope.com/ is rendering correctly. Do you have the right app ID for your app that can help to investigate further?

Thank you for checking and getting back to me. But I moved the site to my trusted hosting service with a quick and free support (this not to you but AWS in general).
