### ISSUE TITLE
[ERROR]: !!! Non-Zero Exit Code detected

### ISSUE THREAD

**Issue by rajat-forgeahead** [aws-amplify/amplify-hosting#3889]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Environment variables, Frontend builds

### Is your feature request related to a problem? Please describe:

while deploying my next js app I am getting this error [ERROR]: !!! Non-Zero Exit Code detected

### Describe how you'd like this feature to work

I want the build to be successful

**Comment by arundna** [comment]
@rajat-forgeahead 👋 This repository only accepts new feature requests for AWS Amplify Hosting. For technical support, we encourage you to open a case with [AWS technical support](https://docs.aws.amazon.com/awssupport/latest/user/case-management.html#creating-a-support-case) if you have AWS support plan. If you do not have an active AWS support plan, we encourage you to leverage our Amplify community [Discord server](https://discord.gg/amplify) where community members and staff try to help each other with Amplify.
