### ISSUE TITLE
HTTP3 support for existing apps

### ISSUE THREAD

**Issue by KholdStare** [aws-amplify/amplify-hosting#3891]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Not Applicable

### Is your feature request related to a problem? Please describe:

I have asked about HTTP3 support here: https://github.com/aws-amplify/amplify-hosting/issues/3767 . However, the issue is now closed and locked without anyone able to comment on it or ask questions. Please don't lock issues after posting an extremely unhelpful comment.

The comment says "All new apps have HTTP/3 enabled by default." Great. I have so many questions:
- What counts as "new" - when was the feature enabled?
- Do existing apps get it automatically?
- Is there a way to enable this for existing apps if not?
- Is there any documentation for the migration?
- Any links to documentation/articles/announcements that mentions HTTP3 for amplify hosting?

Right now as a customer, I have no idea how to take advantage of this feature.

### Describe how you'd like this feature to work

I would like to see some documentation on how to enable HTTP3 support in existing apps. Ideally issues should not be immediately locked in case customers wish to respond or ask questions.

**Comment by mauerbac** [comment]
HTTP3 is supported. If you aren't seeing this please open a premium support case

**Comment by KholdStare** [comment]
What counts as "new" - when was the feature enabled?
Do existing apps get it automatically?
Is there a way to enable this for existing apps if not?
Is there any documentation for the migration?
Any links to documentation/articles/announcements that mentions HTTP3 for amplify hosting?
Right now as a customer, I have no idea how to take advantage of this feature.

**Comment by mauerbac** [comment]
Hi @KholdStare - sorry for missing those. Yes, we leverage CloudFront and it enables it for all apps new and existing. It should be enabled by default for all, so there isn't a setting. In terms of documentation, we should make clear this is enabled - I will work on that. 

I can triple check your app - can you share the App ID? (this is ok to share on GitHub)

**Comment by KholdStare** [comment]
Hi, thank you. The app ID is d3ejuvhpmcoxdy

**Comment by mauerbac** [comment]
Yep, HTTP3 is enabled. You can check in the network tab of an HTTP3 enabled client. but yes I can confirm for you!
