### ISSUE TITLE
FR: Would like to see console to be translated to HINDI.

### ISSUE THREAD

**Issue by sowmyadev-kota** [aws-amplify/amplify-hosting#3894]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Not Applicable

### Is your feature request related to a problem? Please describe:

Would love to see the console to get translated `HINDI`,
I would like to the console website to be available to people who speak hindi,
https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers_in_India,
https://en.wikipedia.org/wiki/Hindi#Geographical_distribution

### Describe how you'd like this feature to work

This features will help people who have hard time learning english and would still want to use the website. This can make millions of people happy, thank you.

**Comment by kvramyasri7** [comment]
No longer interested in this feature request. Do we have a down vote reaction option if I strongly discourage 👎
