### ISSUE TITLE
PR preview error 

### ISSUE THREAD

**Issue by felixpro** [aws-amplify/amplify-hosting#3896]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Web previews

### Is your feature request related to a problem? Please describe:

I have 2 amplify apps. The App 1 has a backend and a hosting which is the landing page. The app 2 is just for hosting the main web app. 

Here is the problem:

I connected both hosting apps to the backend and they are working great. But, the PR preview is not working for app 2 because it's outside the app that has the backend. 

![image](https://github.com/aws-amplify/amplify-hosting/assets/42367473/2681c817-9012-4098-b85e-04d2c6704cd1)

When I go to the preview settings for the app 2 no backend shows there. And I'm not able to set the PR previews for the APP 2. 

### Describe how you'd like this feature to work

How can I connect 2 fron-end or repo to the same backend so they all have PR previews from the same backend and also can be connected to 2 different repositories?

**Comment by mauerbac** [comment]
Sorry for the delay. Going to close this as its quite old and we updated our UI for Gen2
