### ISSUE TITLE
In manual drag and drop deploy, main.js and style.js looks text/html content-type

### ISSUE THREAD

**Issue by sathishcst10** [aws-amplify/amplify-hosting#3902]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Manual deploys

### Is your feature request related to a problem? Please describe:

I'm tried to deploy my angular application on amplify manually with build artifacts, but after deployment main.js and style.js not working returns 404 error, 
amplify server read this files as text/html content-type, why this happend?

![Capture](https://github.com/aws-amplify/amplify-hosting/assets/6767773/16a83762-6c7f-4b02-9b0e-9d4c1542dc23)
![Capture2](https://github.com/aws-amplify/amplify-hosting/assets/6767773/99b58140-9445-40d0-a29c-e68ae63c5530)

### Describe how you'd like this feature to work

need solution for this issue

**Comment by Jay2113** [comment]
Hi @sathishcst10 👋 , this repository only accepts new feature requests for AWS Amplify Hosting. For technical support, we encourage you to open a case with [AWS technical support](https://docs.aws.amazon.com/awssupport/latest/user/case-management.html#creating-a-support-case) if you have AWS support plan. If you do not have an active AWS support plan, we encourage you to leverage our Amplify community [Discord server](https://discord.gg/amplify) where community members and staff try to help each other with Amplify.
