### ISSUE TITLE
Is it possible to use 2 different platforms in one amplify app? 

### ISSUE THREAD

**Issue by yafimvo** [aws-amplify/amplify-hosting#3907]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Monorepo, SSR

### Is your feature request related to a problem? Please describe:

I have a monorepo with two applications: one in React and another in Next.js. Each project has its own amplify.yml in its root folder. While I was able to build both applications in my Amplify, the CI/CD doesn't work properly because the app's platform should be 'Web' for React and 'Web compute' for Next.js. As a result, I need to manually change it every time I want to deploy one of them.

Also, a follow up question - is it possible to set the AMPLIFY_MONOREPO_APP_ROOT from one of the configuration files?

### Describe how you'd like this feature to work

Generally, my goal is to connect both monorepo folders (react and nextjs) into 1 URL, i.e. `https://example.com` which is hosted on Amplify. Then, for every `example.com/app2`, this should show the Next.js app; otherwise, it should show the React app. I was able to achieve this with a rewrite, however, I wonder if there is a simpler way to do it that will also support CI/CD.

**Comment by kvramyasri7** [comment]
Any update trying to do the same and few folks are reaching out to ME!

**Comment by kvramyasri7** [comment]
cc: @Milan-Shah @chrisbonifacio

**Comment by yafimvo** [comment]
> Ummmm, oops have not realized have opened a duplicate copy/paste issue sorry u guys !!!!

@kvramyasri7 

Thanks for bumping it up! I'm still waiting for a better solution since the CI/CD is quite a mess.

Maybe a quick solution would be allowing to update specific env params.

this way I can write a small github action script that runs whenever I want to deploy NextJS to Amplify (I can do it now but I need to share all of my Amplify secrets). 

Something like this:

1. Change the platform

```sh
aws amplify update-app --app-id <my-app-id> \
    --platform WEB_COMPUTE 
    --region <my-region>
    --update-environment-variables AMPLIFY_MONOREPO_APP_ROOT=nextjs
```

2. push to my main nextjs branch branch, i.e., `main_nextjs_branch`, to invoke the build on Amplify 

3. After a successful build - return the platform to WEB
```sh
aws amplify update-app --app-id <my-app-id> \
    --platform WEB 
    --region <my-region>
    --update-environment-variables AMPLIFY_MONOREPO_APP_ROOT=react
```


**Note** I tried to create a conditional variable but it doesn't work for `AMPLIFY_MONOREPO_APP_ROOT` so fixing this might be also useful.

**Comment by mauerbac** [comment]
Going to close this issue as it seems to be resolved. Please re-open if you still need help or check out our Amplify Discord!
