### ISSUE TITLE
test branch deploy succesfull it gives 404 on domain which is hosted on amplifyapp.com

### ISSUE THREAD

**Issue by xkeshav** [aws-amplify/amplify-hosting#3913]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Build settings

### Is your feature request related to a problem? Please describe:

I have my domain which runs succesfully with master branch and I have  connected *develop* branch and its build getting successfull but when I open the application link it gives 404 error

> https://develop.d1v0nmn943cmur.amplifyapp.com
This develop.d1v0nmn943cmur.amplifyapp.com page can’t be foundNo webpage was found for the web address: https://develop.d1v0nmn943cmur.amplifyapp.com/
HTTP ERROR 404

### Describe how you'd like this feature to work

it whould load the page which build from develop branch

**Comment by Jay2113** [comment]
@xkeshav 👋 , this repository only accepts new feature requests for AWS Amplify Hosting. For technical support, we encourage you to open a case with [AWS technical support](https://docs.aws.amazon.com/awssupport/latest/user/case-management.html#creating-a-support-case) if you have AWS support plan. If you do not have an active AWS support plan, we encourage you to leverage our Amplify community [Discord server](https://discord.gg/amplify) where community members and staff try to help each other with Amplify.
