### ISSUE TITLE
Nextjs 14 Backend Build faild with AWS Appsync and Cognito

### ISSUE THREAD

**Issue by ibrarmunircoder** [aws-amplify/amplify-hosting#3916]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Backend builds, Build settings

### Is your feature request related to a problem? Please describe:

I am using Nextjs 14 with AWS Congnito, AWS Appsync to build full stack web application. I am not facing any issue on the development environment. I am facing an issue while hosting next14 app (Src directory with app directory) on amplify hosting compute.

Source Code Link: https://github.com/ibrarmunircoder/verkada-valet
![AWS-Amplify-us-east-2 (1)](https://github.com/aws-amplify/amplify-hosting/assets/34518290/2d38e2e0-98dd-44ef-9647-47c8aefc7136)
![AWS-Amplify-us-east-2](https://github.com/aws-amplify/amplify-hosting/assets/34518290/e6643b2b-208a-45c3-bbe8-6ae5e26e27e6)

### Describe how you'd like this feature to work

Please let me know how to resolve this issue

**Comment by mauerbac** [comment]
If you are still experiencing this can you open an AWS support case?
