### ISSUE TITLE
Houston, there's a problem We are unable to process your request. Please reach out to your support representative.

### ISSUE THREAD

**Issue by srinivaskv1** [aws-amplify/amplify-hosting#3919]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Not Applicable

### Is your feature request related to a problem? Please describe:

I am getting below error while trying to create an app to hose a simple index.html page with JavaScript function that calls AWS Rest API.
 "Houston, there's a problem We are unable to process your request. Please reach out to your support representative."

I am using my personal AWS account for this activity.

### Describe how you'd like this feature to work

Ideally the application should be created by adding the zip file containing the html file.

**Comment by mauerbac** [comment]
For this, can you open a support ticket. There might be a hold on your account. Thank you
