### ISSUE TITLE
My apps have disappeared from Amplify

### ISSUE THREAD

**Issue by giacomo-predexyo** [aws-amplify/amplify-hosting#3923]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Deployments

### Is your feature request related to a problem? Please describe:

it's the same issue as https://github.com/aws-amplify/amplify-hosting/issues/2546

### Describe how you'd like this feature to work

 I've managed to successfully run amplify push on one of my apps, after deleting the stack and associated resources and re-running amplify init, but the app is still not showing in my dashboard. I'm now absolutely stumped, it feels like the dashboard and my actual account state are not in sync.

**Comment by giacomo-predexyo** [comment]
Suddenly I'm not able to see my apps in amplify console

**Comment by swaminator** [comment]
@giacomo-predexyo can you check your region please?

**Comment by mauerbac** [comment]
Closing this as we haven't heard back from the customer. @giacomo-predexyo - if you still need help , please cut a ticket to AWS Support. Thank you
