### ISSUE TITLE
Amplify stuck in "Provisioning" step in a monorepo.

### ISSUE THREAD

**Issue by harrysrevis** [aws-amplify/amplify-hosting#3924]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Deployments, Monorepo

### Is your feature request related to a problem? Please describe:

I've created a monorepo using Turborepo for two React & NextJS apps. When I pushed some UI changes to the GH repo, the provisioning phase begun and stuck there for like an hour.

After waiting for some time, I cancelled and clicked "Redeploy this version" several times. This triggered an account restriction for my account and couldn't use many of the services. I opened a ticket with AWS and I'm still waiting for them to resolve it.

After checking ECS, I've seen multiple instances having been created, in every region that I manually had to delete.

What caused the issue on this? 

Does anyone have any similar cases?

Thanks

### Describe how you'd like this feature to work

Can anyone give me any insight?

**Comment by mauerbac** [comment]
Can you open a support case if you are still experiencing this?
