### ISSUE TITLE
Unable to connect a repo in AWS Amplify

### ISSUE THREAD

**Issue by ahmadqayyum9** [aws-amplify/amplify-hosting#3926]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Deployments

### Is your feature request related to a problem? Please describe:

I have a React app deployed to AWS Amplify. It is getting the code from a repo of a GitHub account. What I want to do is that I want this app to get any updates from a repo of a different GitHub account. When I try to do this by going to the General tab and the Reconnect Repo and follow the steps, I get the following error:

![image](https://github.com/aws-amplify/amplify-hosting/assets/167066340/bb5dcf2c-2acc-40b7-9028-c692a4d0d3f2)

### Describe how you'd like this feature to work

How can I resolve this issue? What further permissions do I need to give, if any?

**Comment by mauerbac** [comment]
Hello - this is a support issue. Please open up a ticket with premium support or ask us on Discord. Thank you!
