### ISSUE TITLE
SSL Certificate expired and did NOT auto renew

### ISSUE THREAD

**Issue by AhmadMraish** [aws-amplify/amplify-hosting#3931]
### Environment information

```plain text
.
```

### Description

I have a static website on AWS Amplify, with the SSL Amplify issued and managed. It expired today, I do not see an option to renew it or issue a renewal, I also do not see the certificate in the ACM dashboard.

I also do not know what to do in my case since there are already generated records in the Amplify panel for the website so if I even think about using ACM to issue a new certificate, how can I add the new records to the app..., don't see an option to edit them.

**Comment by mauerbac** [comment]
Hi -- I understand your issue. It looks like a setting was changed in your DNS that stopped our system from properly renewing the cert. We mention [in the documentation](https://docs.aws.amazon.com/amplify/latest/userguide/using-certificates.html)that altering DNS records with your domain provider can lead to issues with renewal. 

To solve this, you can 1) Dissociate and reassociate the domain to create a new certificate with Amplify Hosting 2) You could manage the cert yourself with ACM using our CustomSSL feature. https://aws-blogs-prod.amazon.com/mobile/custom-ssl-amplify-hosting/
