### ISSUE TITLE
Issue with Access Control in Amplify Console

### ISSUE THREAD

**Issue by subhankar-trisetra** [aws-amplify/amplify-hosting#3933]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Access control

### Is your feature request related to a problem? Please describe:

I had a global password set for all my branch deployments (only have 1), as soon as I changed it to something else, I was not able to login to my app with the new or old passwords, even after clearing cached in chrome and hard refreshing the tab. Now when I remove the password altogether and make it Publicly Viewable, I'm able to access it. Its happening for all 3 of my apps:
APP ID 1: d2175qax4he4k2
APP ID 2: dtq2fhfaa88nf
APP ID 3: d9237tfenzizp

I could find related closed issues:
https://github.com/aws-amplify/amplify-hosting/issues/171
https://github.com/aws-amplify/amplify-hosting/issues/896

### Describe how you'd like this feature to work

A seamless experience is what I look for even if I need to rotate the passwords.

**Comment by subhankar-trisetra** [comment]
Its resolved, turns out that there are some special characters which you wouldn't be able to include in the password. When I changed my password to all texts and numbers, it worked! Not all symbols are supported in the password due to "I think" web requirements.

**Comment by mauerbac** [comment]
oh i see! Awesome!
