### ISSUE TITLE
Amplify's "monitoring-with-cloudwatch" documentation page uses wrong metric names

### ISSUE THREAD

**Issue by taraspos** [aws-amplify/amplify-hosting#3961]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

CloudWatch metrics, CloudWatch alarms

### Is your feature request related to a problem? Please describe:

[Amplify -> Monitoring an application with Amazon CloudWatch](https://docs.aws.amazon.com/amplify/latest/userguide/monitoring-with-cloudwatch.html) mentions metric names `4XXErrors` and `5XXErrors`, however in reality they are `5xxErrors` and `4xxErrors`

![image](https://github.com/user-attachments/assets/5aba5440-434f-4781-92d5-8645cb70df59)

### Describe how you'd like this feature to work

Metric names in documentation should be fixed

**Comment by KristinaPeterson** [comment]
@taraspos Thank you for reporting the issue with the format of the metric names. The metric names have been corrected on the public documentation site.
https://docs.aws.amazon.com/amplify/latest/userguide/monitoring-with-cloudwatch.html#metrics
