### ISSUE TITLE
How enable SSR logs for existing Amplify App

### ISSUE THREAD

**Issue by ashokvaddevalli** [aws-amplify/amplify-hosting#3964]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Other

### Which UI component?

Other

### How is your app built?

Svelte

### Please describe your bug.

Enable SSR logs for existing Amplify App?
We are missed to enable SSR logs during create app but we want enable now for existing App. But we didn't see any options in settings for enable SSR logs for existing App.

### What's the expected behaviour?

Enable SSR logs for existing Amplify App?
We are missed to enable SSR logs during create app but we want enable now for existing App. But we didn't see any options in settings for enable SSR logs for existing App.

### Help us reproduce the bug!

Enable SSR logs for exiting Amplify App?
We are missed to enable SSR logs during create app but we want enable now for existing App. But we didn't see any options in settings for enable SSR logs for existing App.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by ferdingler** [comment]
Hi, yes, Amplify will deliver logs automatically so long as your app has an IAM role attached to it with the right permissions. 

1. Attach an IAM role to your app: 

```bash
aws amplify update-app --app-id YOUR_APP_ID --iam-service-role-arn arn:aws:iam::YOUR_ACCOUNT_ID:role/YOUR_ROLE_NAME
```

Ensure that the role has the following trust policy that allows Amplify to assume it: 

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "amplify.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```

and the role needs at least the following permissions: 

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogStream",
                "logs:CreateLogGroup",
                "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:*:*:*"
        }
    ]
}
```

2. Kickoff a deployment of your App, this is necessary whenever you update the role. 

```
aws amplify start-job --app-id YOUR_APP_ID --branch-name YOUR_BRANCH_NAME --job-type RELEASE
```
