### ISSUE TITLE
Wildcard subdomains in AWS Amplify

### ISSUE THREAD

**Issue by cjimenezber** [aws-amplify/amplify-hosting#44]
So we recently decided to remove server side rendering from our react app to use Amplify, since it provides us all that we need (serverless, high availabilty, speed and no need to test in two environments). 

However now I have a question regarding how to configure AWS Amplify to have a wildcard CNAME record. I want that any subdomain can reach my app, not just the ones I manually select in the Amplify Console. 

I have a wildcard CNAME in Route 53 pointing to the cloudfront, and the subdomains I added manually in the console are working, but the ones that are not (due to the nature of the wildcard CNAME), just get a 403  from cloudfront.

Is there support for wildcard subdomains in Amplify? 

How does one configure it? Assuming there is no support for this. 

Is there an API I can use to create the Amplify subdomains for me rather than doing it manually everytime a client purchases access?

**Comment by swaminator** [comment]
@cjimenezber you should be able to create domain associations via the AWS CLI: https://docs.aws.amazon.com/cli/latest/reference/amplify/create-domain-association.html

We have a feature request for domain patterns in our backlog. Thanks hope this helps.

**Comment by cjimenezber** [comment]
I have another question, to finalize this. We will be either adding them manually or using a cron job that invokes a CLI method with the new customers. When doing manual changes to the subdomains I noticed that all subdomains slow down greatly while the domain gets reverified and everything gets added to cloudfront.

Will this happen for all domains/sub-domains every time I update the list of subdomains?

**Comment by VividKnife** [comment]
First of all, we have a limit on total number of subdomains you can add to each customer domain (50). 
Secondly, any update to the subdomains(including add and remove) it will require us to update the cloudfront behind, which takes about 10-15mins.

**Comment by cjimenezber** [comment]
Alright, will there be any notification of when the wildcard subdomain feature is finished?

**Comment by favour121** [comment]
Any update on wildcard subdomains?

**Comment by MR-Neto** [comment]
Any updates? I am in need of this feature.

**Comment by leewenjie** [comment]
+1 to this feature request, or the next best solution for wildcard subdomains

**Comment by Cyborganic** [comment]
The feature is most definitely required

**Comment by eduardotamaki** [comment]
+1

**Comment by divsbhalala** [comment]
+1

**Comment by dtelaroli** [comment]
+1

**Comment by danielfolley** [comment]
+1

**Comment by Kaustubh26** [comment]
+1

**Comment by YorbenVerhoest** [comment]
+1

**Comment by anuj-bluebash** [comment]
+1
Please update on this, We are getting delay in our production launch. 
Please answer yes/No

**Comment by dtelaroli** [comment]
I have created this js function as workaround:

https://gist.github.com/dtelaroli/ffbebd858f5089bfb7532ff3d96fb7ea

**Comment by abhi7cr** [comment]
@anuj-bluebash, 
We currently don't support wildcards as a subdomain prefix. We have a feature request in our backlog to address this, and will let you know once it's rolled out. Thanks for your patience.

**Comment by Kaustubh26** [comment]
Would anyone be aware whether this would be possible to achieve through the Cloudfront and S3 hosting option? I see that the docs support it, but not aware of the limitations or if there are any issues with using this solution. 

https://aws.amazon.com/about-aws/whats-new/2013/09/18/amazon-cloudfront-announces-wildcard-cname-support/#:~:text=We're%20excited%20to%20let,distribution%20to%20include%20each%20subdomain.

**Comment by skolodyazhnyy** [comment]
@swaminator @abhi7cr is there any workaround for wildcards to work? I don't see CloudFront in my AWS Console, so I assume it's internal. Maybe there is way for me to create own CloudFront and setup DNS manually? It would be wonderful if I could keep CI pipeline and setup CloudFront on my own.

**Comment by cjimenezber** [comment]
> Would anyone be aware whether this would be possible to achieve through the Cloudfront and S3 hosting option? I see that the docs support it, but not aware of the limitations or if there are any issues with using this solution.
> 
> https://aws.amazon.com/about-aws/whats-new/2013/09/18/amazon-cloudfront-announces-wildcard-cname-support/#:~:text=We're%20excited%20to%20let,distribution%20to%20include%20each%20subdomain.

I ended up going for this option, we have a production app using S3 + Cloudfront with Wildcard CNAME record.

**Comment by cdac901** [comment]
+1

**Comment by niknokseyer** [comment]
> First of all, we have a limit on total number of subdomains you can add to each customer domain (50).
> Secondly, any update to the subdomains(including add and remove) it will require us to update the cloudfront behind, which takes about 10-15mins.

Can the limit be increased? We are using it so that each account have their own subdomain.

**Comment by dtelaroli** [comment]
I have tried and received no as answer

**Comment by swaminator** [comment]
This issue was closed so we missed this. Reopened it and tracking it as an active feature request.

**Comment by niknokseyer** [comment]
> This issue was closed so we missed this. Reopened it to let you know that we launched a feature for automatic subdomains that match a pattern. Please let us know if this will work for you: https://aws.amazon.com/blogs/mobile/automatically-create-and-delete-custom-sub-domains-for-your-branch-deployments-with-amplify-console/

Can the subdomain limit be increased? We are using it so that each account have their own subdomain.

**Comment by dtelaroli** [comment]
The short answer is NO

**Comment by niknokseyer** [comment]
> The short answer is NO

What’s gonna be the workaround for that? Are wildcards possible?

**Comment by dtelaroli** [comment]
No, you can use wildcards configuring it directly at route53, cloudfront and acm, but amplify does not support yet. We are waiting for aws team to solve this issue.
I also need this feature, but following the time that AWS takes to solve some issues (near to 3 years), I will move my project from amplify to an own configuration at cloudfront ou cloudflare when I would have 50 customers.

**Comment by swaminator** [comment]
> The short answer is NO

@dtelaroli that isn't really going to help us prioritize the issue. Can I understand a bit more in detail why the subdomain autodetection will not work for you? Again, apologies that this issue slipped under the rug as it was closed. But given I reopened it, I'd like to understand the usecase a bit more.

**Comment by swaminator** [comment]
@niknokseyer not currently but we will enable limit increases soon.

**Comment by dtelaroli** [comment]
> > The short answer is NO
> 
> @dtelaroli that isn't really going to help us prioritize the issue. Can I understand a bit more in detail why the subdomain autodetection will not work for you? Again, apologies that this issue slipped under the rug as it was closed. But given I reopened it, I'd like to understand the usecase a bit more.

@swaminator because I don't want to create one subdomain per branch, but one subdomain per customer. I'm creating via sdk a new subdomain to each my customer, but the limit of 50 subdomain limits my app to get maximum of 50 customers. If you increase the limit, it's good, but imagine my r53 zone with a huge number of entries for acm validation and cnames.

The better solution still being wild card subdomain.

**Comment by niknokseyer** [comment]
> @niknokseyer not currently but we will enable limit increases soon.

Looking forward to that. Our use case is for url branding purposes. When a new client / company signs up on our application they get their vanity url (e.g. <company>.webapp.com) to login to their dashboard. We've reached more than 50 account sign ups so we were surprised reaching the 50 subdomain limit. @swaminator

**Comment by eschreiner** [comment]
@swaminator Same here. I need to use subdomains for customer's dashboards as well. Support for wildcards would solve this for me.

**Comment by zgr024** [comment]
Correct me if I'm wrong, doesn't this just involve allowing us to place an asterisk as the host? and then just update the DNS to * CNAME target ?

**Comment by niknokseyer** [comment]
> Correct me if I'm wrong, doesn't this just involve allowing us to place an asterisk as the host? and then just update the DNS to * CNAME target ?

This is currently not an option on AWS Amplify.

**Comment by dtelaroli** [comment]
> Correct me if I'm wrong, doesn't this just involve allowing us to place an asterisk as the host? and then just update the DNS to * CNAME target ?

With clouldfront you can get it, but you can't use another subdomain together in amplify, because cloudfront doesn't allows between different accounts. I have tested too much workaround, but there is no way.
I think that amplify use another account and it is this the limitation.

By the history, in 2 years the aws will solve it.

**Comment by cjimenezber** [comment]
> et it, but you can't use another subdomain together in amplify, because cloudfront doesn't allows between different accounts. I have tested too much workaround, but there is no way.
> I think that amplify use another account and it is this the limitation.

I have come to the same conclusion, we ended up buying a different domain to use in dev for this reason.

**Comment by dtelaroli** [comment]
I'm using different domain as a new hosted zone as subdomain of mine root domain (eg. dev.mydomain.com). But I don't like using different environment configuration. Now, I'm migrating the all 4 apps to CloudFront/S3 (one uses wildcard). If I would have some new surprise, I'll migrate to the CloudFlare.

**Comment by cjimenezber** [comment]
> I'm using different domain as a new hosted zone as subdomain of mine root domain (eg. dev.mydomain.com). But I don't like using different environment configuration. Now, I'm migrating the all 4 apps to CloudFront/S3 (one uses wildcard). If I would have some new surprise, I'll migrate to the CloudFlare.

I fully agree with not wanting to use different environment configuration, we plan to eventually get out of amplify once we finish some critical functionality since we really really need the wildcard subdomains, but that means setting up our own pipeline rather than using a premade one, which is a shame, but the only option we got in order to not have multiple environment configurations.

**Comment by dtelaroli** [comment]
@cjimenezber today I understand why you have used another domain to development env. It's impossible use another subdomain wildcard because cloudfront does not allow also. Eg.: *.rootdomain.com and *.dev.rootdomain.com.
Now, it is a blocker missing feature for me. I also will need to buy another domain or migrate to another service.

**Comment by vemundeldegard** [comment]
This is a blocker for me too. It is very useful to have wildcards for multi-tenant systems.

**Comment by magedjisr** [comment]
any updates on this, I need this feature

**Comment by colecanning** [comment]
bump

**Comment by lemaju** [comment]
> This issue was closed so we missed this. Reopened it to let you know that we launched a feature for automatic subdomains that match a pattern. Please let us know if this will work for you: https://aws.amazon.com/blogs/mobile/automatically-create-and-delete-custom-sub-domains-for-your-branch-deployments-with-amplify-console/



> > The short answer is NO
> 
> @dtelaroli that isn't really going to help us prioritize the issue. Can I understand a bit more in detail why the subdomain autodetection will not work for you? Again, apologies that this issue slipped under the rug as it was closed. But given I reopened it, I'd like to understand the usecase a bit more.

Wildcard means, that literally ANY subdomain can be entered (e.g. costumer1.example.com or costumer9999.example.com or even 989addad.example.com) to start the same application. 

Within the application itself we then render depending on the subdomain, but that's not AWS concern. What matters is, that my App starts, when some random subdomain is entered.

The feature you deployed is nice-to-have, but this is a dealbreaker for many of us.

**Comment by zgr024** [comment]
As I understand it, wildcards (*) will cause an issue for SSL certs and probably why AWS has not allowed a * in the subdomain entry. Wildcard certs are becoming obsolete as they open up security issues. Increasing, or better yet, removing the limit of 50 subdomains would be the real solution here. As a programmer, I'm pretty sure there's a single config variable in the code that is set to 50. Just append a few more zeros and make it 5000 or 50000... Problem solved. 

I can create new subdomains programmatically but the limit here is the true killer. Such a nice system that is ruined by this unrealistic limit.

**Comment by Drnoodle** [comment]
I'm dealing with the same issue...

I have a first quick fix for it (proxy using api gateway): 
1.- Create an Api Gateway, create an any method, then integration HTTP to url : youramplifyurl.com
2.- Add a custom domain name (still in api gateway) "*.yourdomain.ext" (create your ACM certificat *.yourdomaine.ext)
3.- Add a A record (active with alias button) and select "from api gateway"

It works fine and does not seems to have any speed performance issues (SEO), I just need to verify it's scalable (it should be).

I'm gonna look for something cleaner on tomorrow but amplify enforce https and manage all certificates. 
It looks complicated to find an easy way to fix it elsewhere than in cloudformation.

Maybe the simple solution is to find another service...

Keep me in touch

**Comment by WillVill** [comment]
bump, this is a real issue. Might need to move over to service/supplier.

**Comment by swaminator** [comment]
Hey guys we are actively looking at designing a solution for this. We will update this thread soon with a plan.

**Comment by rohan-jisr** [comment]
+1, big issue for us as we have over 400 clients and we let them choose their subdomain programatically when they onboard

**Comment by WillVill** [comment]
We have gotten this problem solved by reaching out to AWS support and asking to increase the 50 limit to 500. It took a little under a day for them to change it!

**Comment by mits87** [comment]
+1, guys we really need that functionality! 
We have above 5000 customers with custom subdomain, so because of that problem we can't use Amplify at all.

Right now we moved back to the Vercel solution because of that. 
I'm looking forward to have a proper solution in Amplify.

**Comment by DiegoArrieta** [comment]
+1 please support multi tenancy apps!!

**Comment by fangzhouli** [comment]
+1

**Comment by brayann** [comment]
👍 for this

**Comment by Ilya93** [comment]
+1

**Comment by boricic** [comment]
👍  for this

**Comment by rababahmed** [comment]
+1

**Comment by zgr024** [comment]
The solution I found was to ask AWS for a limit increase for subdomains in the region you want for all apps in the region and use Route 53 to automatically add the CNAMEs when a new subdomain is added via the SDK (will not work in console past 50). 

Wildcard certificates are dangerous and not recommended anyway. If you want to handle 404s at the subdomain level, you can just add a * CNAME in Route 53 and point it to a separate web server with a wildcard cert. Then either redirect back to your application or display your 404 page.

**Comment by kyashrathore** [comment]
> +1, guys we really need that functionality! 
> We have above 5000 customers with custom subdomain, so because of that problem we can't use Amplify at all.
> 
> Right now we moved back to the Vercel solution because of that. 
> I'm looking forward to have a proper solution in Amplify. 

How are you using vercel for it?

They provide wild card support.

But how yo are asking them to point their custom domain to your wildcard domain?

**Comment by dgl9** [comment]
+1 for wildcard support

Let's get this rolling.. where is the classic Amazon Customer Obsession?

**Comment by DanielOverdevest** [comment]
+1 for wildcard subdomain support to have a subdomain for all of our clients. Now I have to do it manually.

**Comment by terryds** [comment]
+1 for wildcard domain support

**Comment by r-moore** [comment]
+1

**Comment by dgl9** [comment]
> Hey guys we are actively looking at designing a solution for this. We will update this thread soon with a plan.

Any update on this?

**Comment by Shaunwild97** [comment]
+1

**Comment by lisbuenas** [comment]
+1

**Comment by Matheusgfgl** [comment]
+1

**Comment by olivierpichon** [comment]
@abhi7cr, @VividKnife, @swaminator,

Could you guys let us know if there is an underlying issue as to why this can't be implemented easily? From an external point of view (which must not have a clear picture), it feels like the underlying Cloudfront distribution(1) and Certificate Manager(2) should support wildcard.

This feature would come a long way to achieve sophisticated multi-tenancy (one user can belong to many accounts / orgs) and would further help Amplify to gain an enterprise-ready reputation.

Thanks!

(1) https://aws.amazon.com/about-aws/whats-new/2013/09/18/amazon-cloudfront-announces-wildcard-cname-support/ 
(2) https://docs.aws.amazon.com/acm/latest/userguide/acm-certificate.html

**Comment by marceloch2** [comment]
+1

**Comment by johnstan** [comment]
+1

**Comment by fezzy2020** [comment]
+1

**Comment by hassanabbasi** [comment]
+1

**Comment by marco-debortoli** [comment]
+1

**Comment by Drnoodle** [comment]
Hello,

I encountered the same problem while developing a project. I solved it by implementing a reverse ssl proxy with the following features :

- Clients can choose a subdomain
- Clients can link their own domain name
- HTTPS and automatic renewal of the clients certificates
- Possibility to manage domains : remove entry, check if the domain already exists...

Would you be interested in a service that would handle this issue for you for a price between 100 and 400 dollars per month? 

Let me know by putting a 👍 beside this comment. 

Hugo

**Comment by drashtibpatel** [comment]
+1 for wildcard domain/subdomain support

**Comment by lisbuenas** [comment]
At moment solved without Amplify, combining Codepipeline with S3 bucket and configuring the wildcard subdomain to a root application, to map subdomain and configure the application on runtime.

**Comment by zgr024** [comment]
I solved this issue by using the AWS SDK to create/update the subdomains as needed. I did this after asking them to increase my limits which was a feat in and of itself. No need for wildcards anymore.

**Comment by tasarsu** [comment]
+1 Amplify is great we already use it but it would be much more great to have wildcard subdomain support for multi tenant applications

**Comment by osnodegeoffrey** [comment]
+1

**Comment by LuckyBeardDev** [comment]
+1

**Comment by simo97** [comment]
+1

**Comment by hsynakgul** [comment]
+1

**Comment by SaqibZafar** [comment]
+1

**Comment by neilferreira** [comment]
+1

**Comment by nuriakman** [comment]
+1

**Comment by bronzemoon81** [comment]
+1

**Comment by 3rkan0zturk** [comment]
+1

**Comment by DominikScholz** [comment]
+1

**Comment by manikpokhetra79** [comment]
+1

**Comment by MattTimmons** [comment]
+1

**Comment by digitalhurricane-io** [comment]
+1

**Comment by nikitastryuk** [comment]
+1

**Comment by sanchojaf** [comment]
+1

**Comment by othman-albakri** [comment]
@aws-amplify-ops  , Is there any plan to support wildcard or not , so we can search for other options

**Comment by chudinovskikh** [comment]
+1

**Comment by nick-bir** [comment]
+1

**Comment by alex-karo** [comment]
+1

**Comment by ambakiev** [comment]
+1

**Comment by codethazine** [comment]
+1

**Comment by NamTHP** [comment]
+1

**Comment by biller-aivy** [comment]
+1

**Comment by mike-atlas** [comment]
+1 - This is keeping a bunch of our stack on Heroku where we can use SSL FastTrack to match a wildcard subdomain. Our application is multi-tenant and mints a subdomain for each new tenant's storefront, so manually managing subdomains is tedious, and a limit of 50 is a hard "no" for our business case. I'd love to be able to move things over to AWS and get off of Heroku entirely.

**Comment by edstromserculate** [comment]
+1

**Comment by vigneshwaran-vtpl** [comment]
+1

**Comment by claytonrogers** [comment]
+100

**Comment by nyousefzai** [comment]
+1

**Comment by MotivationalSqueaker** [comment]
+1

**Comment by vizardkill** [comment]
+100

**Comment by maikonb** [comment]
+1

**Comment by MFaqihRidho** [comment]
+100

**Comment by thecodelifter** [comment]
+101

**Comment by thecodelifter** [comment]
Any update on this?

+1

**Comment by supermarcos** [comment]
For what is worth, I want to share the way I'm doing it (even though it's not using wildcard that could fit any subdomain):

- Go to your Amplify app in AWS console (I'm sure there's a way to do this using cloudformation and a proper yaml / json manifest, but I only onboard new customers every now and then so... for now I don't mind doing it manually)
- Go to Domain Management option on the side-panel
- Manage Subdomains button at the top-right
- Add a new one, but when you find your domain, remember you can write subdomains there, so you can select the one you want from the drop-down picker and then add a subdomain at the front simply typing what you want.

Disclaimer:
I have the domain dns management in Cloudflare so first thing I do is figure out the cloud internal url that AWS gives me for the applicaion and create a CNAME with the subdomain I will add in the Amplify domain management area.

There may be other and better ways of doing this using Route53, but I don't know those.
Hope this is helpful for anybody in the meanwhile until we get wildcard support (if ever).
:)

**Comment by thecodelifter** [comment]
@supermarcos thanks for sharing but we have over 55 clients that we give custom sub domains and themes/branding depending on which sub domain they use. And we are growing so we need to add more each time. I don't want to do it manually unfortunately just would like the wild card (*) to work :(

**Comment by supermarcos** [comment]
Yeah, I understand. I just wanted to share a workaround that works for me, because of the nature of my project, but obviously, it's way to tedious to do manually in your case.
However, I would go and have a look at this:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amplify-domain.html

If you defined your Amplify application using a yaml or json file for cloudformation, in theory (I haven't tried myself) you should be able to deploy changes as simply as adding the subdomains on the domain section of the config file and re-deploying. You could automate that by listening to a trigger or webhook when a new customer onboards and registers so, in some way, you know at that stage what's going to be the subdomain and you may need to be able to accept or not the subdomain (they, obviously, need to be unique), at that point you can make a call to write the new subdomain on the yaml file and fire a cloudformation build / deploy command to make a new deployment of the applicaion. I know it's ideal, a new customer shouldn't need to trigger a new deployment, but you're not really triggering a new deployment, only re-deploying the existing one with new config which takes way less time.
These kind of solutions sound like hacks at first, but when you look into the nity-gritty of how a proper CI/CD strategy is built, you will notice there are a lot of these commands flying around, triggering changes, running commands, etc... it's not that crazy and it's not necessarily a bad approach if it fits your needs and scales.

Alternatively, you can do kind of similar thing, but making calls to your DNS provider and registering the new subdomains with CNAME redirections. Cloudflare has an API for that in their documentation and I'm pretty sure AWS Route53 should have one too. In this case you may want to trigger the new change from within your server, using a lambda function that calls either the AWS SDK or an external API endpoint.

I don't know... just thinking out loud here trying to give some ideas.
:)

**Comment by thecodelifter** [comment]
@supermarcos thanks for the suggestion I was actually already looking at this route to go down. The other option was using something like manually adding in the Route53 wildcard with ACM and pointing at directly at the Amplify resource ID or something like that :P

**Comment by luizcarlosrodrigues** [comment]
+1 for the wildcard

**Comment by davizoop** [comment]
+1 for the wildcard

**Comment by daniel-veiga** [comment]
+1 for the wildcard

**Comment by Storxy** [comment]
+1 for the wild card

**Comment by sbasheersc** [comment]
+1 for wildcard

**Comment by bsormagec** [comment]
any way to do this with another way ?

**Comment by myatmin8** [comment]
+1 for wildcard

**Comment by yassinecc** [comment]
Wildcard domains are possible in the previous platform version (`WEB_DYNAMIC`) where you can set up wildcard routing between your DNS provider and Cloudfront

You might try to migrate to the previous platform version with `aws amplify update-app --region $REGION --app-id $APP_ID --platform  WEB_DYNAMIC`, redeploy and work on the Cloudfront distributions from there. Be aware that builds will be significantly longer on the previous platform and you might lose on some extra features

**Comment by byanes** [comment]
Are there plans to add support for this? Is there a way to achieve wildcard subdomains at the moment?

**Comment by neondeex** [comment]
Please notify when added wildcards!
+1 wildcard
and please replay if you guys will add this soon

**Comment by tnsengimana** [comment]
+1 This feature would help a lot.

**Comment by MohamedMohsenX2** [comment]
+1 for wildcard

**Comment by medimnos** [comment]
+1 for wildcard

**Comment by MilestoneTech** [comment]
+1 for wildcard

**Comment by akizora** [comment]
+1
I'd be so happy if I could use this!

**Comment by decades404** [comment]
+1 for wildcard

**Comment by narita-takeru** [comment]
I'm unable to use amplify because I want to host a multi-tenant application.
I look forward to this request 👍

**Comment by JRafael91** [comment]
I need this feature

**Comment by scottmanny** [comment]
+1 for wildcard, absolutely need this.

**Comment by keerl** [comment]
+1 I was able to solve the problem by switching to Vercel deployments. Just took a few minutes to transfer to Vercel from Amplify and now wildcard subdomains work perfectly. Maybe someday Amplify will catch up.

**Comment by shazadmaved** [comment]
+1

**Comment by tasarsu** [comment]
Hi @Jay2113 and @aws-amplify team,

It's been over four years since issue #44 was raised. While your continuous encouragement to upvote and comment on this issue is appreciated, it's becoming evident that a resolution might not be on the horizon.

Many community members have started suggesting alternative solutions here to meet wildcard subdomain needs due to the prolonged uncertainty. In the interest of transparency, could you kindly provide a clear stance on whether AWS Amplify plans to implement this feature or not?

This would greatly assist users in making informed decisions and help manage expectations. If the decision is not to proceed with wildcard subdomains, explicitly communicating this and closing the issue might be the best course of action.

Thank you for your attention to this matter.

**Comment by Talhafaz** [comment]
+1 for wildcard

**Comment by siegerts** [comment]
Hi All & @tasarsu :wave:, 

I'm on the Amplify Hosting PM team. Just want to update everyone that we're actively working on this functionality in Amplify Hosting and planning on making it available within the next few months. I appreciate all of the engagement here (and Discord) and all of the feedback provided over the course of the issue.

I'll maintain communication here in the case of any updates. Thanks again!

**Comment by jaga810** [comment]
Given the importance of this feature for our multi-tenant SaaS product, which allows each tenant to have custom sub-domains, we urgently request implementation of this feature. Service team has informed us that it's currently impossible to increase the custom domain limit to 50+. We believe this is crucial for our product's success.

**Comment by mubasshir** [comment]
@siegerts any update for us?

**Comment by siegerts** [comment]
Hi All 👋🏻 - I’m happy to update that **wildcard subdomains are now available** in AWS Amplify Hosting when using a custom domain. The updated documentation is here - https://docs.aws.amazon.com/amplify/latest/userguide/wildcard-subdomain-support.html.

Thank you for the feedback and tracking along!

**Comment by SaqibZafar** [comment]
Finally, Congrats everyone.

**Comment by scottmanny** [comment]
Literally one of the top 10 days of my life.  Thank you so much!!

**Comment by siegerts** [comment]
Hi All - Closing this now that the functionality is live and officially launched!

- The documentation is @ [AWS Amplify Hosting wildcard subdomains](https://docs.aws.amazon.com/amplify/latest/userguide/wildcard-subdomain-support.html)

- Also, there blog post using wildcards with a Next 14 app + middleware @ [Wildcard Subdomains for Multi-tenant Apps on AWS Amplify Hosting](https://aws.amazon.com/blogs/mobile/wildcard-subdomains-for-multi-tenant-apps-on-aws-amplify-hosting/)
