### ISSUE TITLE
Amplify Build configuration, Lambda environment variables being overwritten

### ISSUE THREAD

**Issue by timeconsumer** [aws-amplify/amplify-hosting#459]
** Please describe which feature you have a question about? **
Amplify Build Preview

** Provide additional details**
I have previews enabled for my git repo and when I build using the build settings file configured, the build wipes out the existing environment variables for the Lambdas configured for hooks such as PreSignup, CustomMessage...etc. Am I missing something as to how this is supposed to be used?

**Comment by Joycehao19** [comment]
Hi @timeconsumer , did you follow the instruction here: https://egghead.io/lessons/react-how-to-enable-pull-request-previews-with-amplify-console-hosting

**Comment by timeconsumer** [comment]
The Previews work, it's an issue with the amplify backend build step. When the build happens, it's like it is unaware of the configuration I've set up for each env. When the amplifyPush command happens, the variables set wind up getting reset i.e.:
![image](https://user-images.githubusercontent.com/2559699/75254543-84133a00-57ae-11ea-94c6-b680da9f7030.png)
Those variables were all set when creating and updating the environment on my local machine. Once the PR happened, they all get reset.

**Comment by Joycehao19** [comment]
Hi @timeconsumer , we cut a ticket in our team backlog, now it is pending to investigate.

**Comment by Joycehao19** [comment]
@timeconsumer Hi, I can't reproduce your issue. Would you mind provide your steps that we could replicate? Thanks

**Comment by timeconsumer** [comment]
Working locally I created 3 environments, dev, staging, prod. They look as follows (This is pulled from the team-provider-info.json file and scrubbed for info):
`
"dev": {
        "awscloudformation": {
            "AuthRoleName": "XXXXXXXXXXXX-authRole",
            "UnauthRoleArn": "arn:aws:iam::XXXXXXXXXXX:role/XXXXXXXXX-unauthRole",
            "AuthRoleArn": "arn:aws:iam::XXXXXXXXXXX:role/XXXXXXXXX-authRole",
            "Region": "us-east-1",
            "DeploymentBucketName": "XXXXXXXXX-deployment",
            "UnauthRoleName": "XXXXXXXXX-unauthRole",
            "StackName": "XXXXXXXXX",
            "StackId": "arn:aws:cloudformation:us-east-1:XXXXXXXXX:stack/XXXXXXXXX",
            "AmplifyAppId": "XXXXXXXXX"
        },
        "categories": {
            "auth": {
                "XXXXXXXXX": {
                    "hostedUIProviderCreds": "[{\"ProviderName\":\"Google\",\"client_id\":\"XXXXXXXXX-XXXXXXXXX.apps.googleusercontent.com\",\"client_secret\":\"XXXXXXXXX-\"}]"
                }
            },
            "function": {
                "XXXXXXXXXCustomMessage": {
                    "REDIRECTURL": "http://localhost:8080/",
                    "EMAILSUBJECT": "Click this",
                    "EMAILMESSAGE": "Click it",
                    "resourceName": "XXXXXXXXX"
                },
                "XXXXXXXXXPostConfirmation": {
                    "GROUP": "precert"
                },
                "XXXXXXXXXPreSignup": {
                    "DOMAINBLACKLIST": ""
                },
                "visionauth": {}
            }
        }
    },
`

There are 2 other envs that are identical to this (with the exception of names).
I set up gitlab to trigger builds on branches and have tried triggering builds against all 3 environments.
On the `dev` env, things behave as expected, the values of the params in the functions are the same as if I did an `amplify push` from my local. If I do the same thing with the staging or production environments, the parameters are overwritten to their default values (empty string). If I were to do an amplify push from my local when on that environment the values go back to their respective environments' configurations. The backend build command that I've used was `amplifyPush --simple` but I've also tried just about every other configuration that I could possibly think of.

**Comment by no-creative-name** [comment]
I have the same problem. Is there an update on this issue?

**Comment by vidhyasagarj** [comment]
Any update on this! stuck with the same issue

**Comment by akinwol** [comment]
Any updates here? I am still having this issue. It's a bit annoying to have to update all environment variables every time there's a new build

**Comment by hloriana** [comment]
This issue has been resolved.
