### ISSUE TITLE
Post Deployment Phase or Trigger

### ISSUE THREAD

**Issue by jhoffmcd** [aws-amplify/amplify-hosting#478]
**Is your feature request related to a problem? Please describe.**

For some projects, we use a centralized multi-platform back end not under the umbrella of Amplify. We have 3 persistent environments (dev, staging, prod) and we use GitFlow. Amplify helps us automate dev and prod pretty easily, but we have to script the staging environment updates based on new release candidates. We do this by leveraging the AWS CLI.

Ideally, after a new release branch is created and a new staging environment has been created, I need to swap out a few things, namely **domain association** and **webhook branch association**. I can do it now but the latest stage in the process that I can do that is **post-build** which is before the actual deployment, so there may be some small downtime for that environment as the swap is taking place.

**Describe the solution you'd like**

I would love some sort of post deploy/validate hook or phase to run some commands.

**Additional context**

None

**Comment by nimacks** [comment]
@jhoffmcd , thanks for the feedback, we'll add this to our feature request list.

**Comment by sceptyk** [comment]
Hey, @nimacks, is there any update on that?

**Comment by jerelmiller** [comment]
We could also really use this feature. We have a script that runs to sync some data to a remote service. We would ideally like to trigger that script after a deployment of the site so that we can guarantee that the new data is in place.

**Comment by Jay2113** [comment]
Hi everyone 👋 , I am going to close this feature request in favor of https://github.com/aws-amplify/amplify-hosting/issues/588 since it has higher engagement and I'll recommend upvoting it as it will help us prioritize the feature.
