### ISSUE TITLE
PR Previews show 'Stuck in Queued' for certain PRs

### ISSUE THREAD

**Issue by netochaves** [aws-amplify/amplify-hosting#550]
**Is your feature request related to a problem? Please describe.**
When I send a commit, a new build preview is created at Amplify console, starting the Github check. If I send another commit while the old builds are running, the check is queued and will remain so until we send another commit. That's because a new build is created and the old one is not cancelled.

**Describe the solution you'd like**
I think we should cancel the current build if a new one is created.This will solve or problem with github amplify check. 

**Additional context**
When I send a new push with the build still running.
![image](https://user-images.githubusercontent.com/19830660/77932915-8f152a80-7284-11ea-84b4-494393feeedb.png)

**Comment by ganipcanot** [comment]
@netochaves For clarification how are you triggering this behavior?

(1) Create a pull request --> Commit some changes (before pull request build finishes)
OR
(2) Commit some changes (build triggered) --> commit some more changes

**Comment by ganipcanot** [comment]
@netochaves I tried:

(1) creating a PR with PR preview enabled --> then I made a commit to my master branch and I wasn't able to reproduce this issue.

**Comment by netochaves** [comment]
Option one, but you've to commit on PR.

**Comment by netochaves** [comment]
@ganipcanot Create a pull request (build triggered) => Commit some changes on the same PR (before pull request build finishes)

**Comment by ganipcanot** [comment]
@netochaves So you created a pull request (build triggered) => commit some changes to the PR branch => at this point you do a git push (to update the remote repository/branch)?

**Comment by ganipcanot** [comment]
I was able to reproduce this and I am adding it to our backlog for further investigation - thanks for letting us know!

**Comment by jonvanausdeln** [comment]
We are also seeing this issue with about 20% of our Pull Requests.

**Comment by woodsae** [comment]
This is a problem for us as well.  Do you have an ETA on a fix?

**Comment by daroczig** [comment]
I'm also experiencing this issue.

**Comment by stevenphaedonos** [comment]
I'm able to reproduce this consistently via the following two scenarios (let's assume master branch triggers the preview to be built):
1. Open a PR against a **non-master** branch, then switch the base branch of the PR to master branch.
2. Have a PR that was opened against master branch, with previews working. While a build is in progress, push a new commit to the PR branch. 
In both of the above cases, preview builds become stuck without resolution.

**Comment by daroczig** [comment]
This is still a huge problem for us, and becoming so annoying that I am considering to disable PR previews after all and trigger the Amplify builds from GitHub Actions instead -- despite the complexity of this design compared to the really promising Amplify PR previews :disappointed: 

The main issue is that our tests take 30+ minutes, and every single push to the repo at the time of a previous PR preview build still running will end up in the queued state (forever), not only missing the related PR preview, but the build status badge as well blocking PR merges.

Would love to see an ETA on this :zipper_mouth_face:

**Comment by zstix** [comment]
We are also experiencing this issue. As a workaround, we plan to utilize GitHub actions, but it's not exactly ideal.

Any word on when the issue will get addressed?

**Comment by michaelbrewer** [comment]
Happens a lot for me too, especially if there are multiple commits close to each other

**Comment by sugi-s** [comment]
We are seeing this issue frequently and disabling PR previews are not ideal.... Is there any ETA on this???

**Comment by reddypramod85** [comment]
We are also facing the same issue. We deploy it to both Netlify and Amplify but Amplify preview is being queued most of the time.

![image](https://user-images.githubusercontent.com/12749370/119658569-e95f3c00-bdf2-11eb-9076-235a09c3e1cc.png)

**Comment by noahgorstein** [comment]
Has there been any progress with respect to this issue?

**Comment by croossin** [comment]
@ganipcanot Do you mind providing some sort of status on this issue? It is becoming a problem for us as well.

**Comment by Sherdycoder** [comment]
Also seeing the same issue. Any updates would be greatly appreciated!

**Comment by olefirenko** [comment]
+1 We also are having the same issue with the PR previews in Amplify.

**Comment by Maker-Mark** [comment]
I'm also seeing this issue consistently. Any updates?

**Comment by Mhm0ud** [comment]
Did anyone find a workaround for this issue?

**Comment by Mhm0ud** [comment]
I am seeing this same behavior if a commit is pushed to the repository, triggering another build while the last build hasn't finished yet. The check never finishes despite the build actually completing in amplify.

**Comment by Djelnar** [comment]
Same

**Comment by giioohbernini** [comment]
Same here!

**Comment by mmakarin** [comment]
Same thing!

**Comment by fidlow** [comment]
+1 same issue!

**Comment by chudinovskikh** [comment]
This is constantly happening for my project. Very annoying and slowing down the development.
Do you have any plans for fixing the issue ?

**Comment by edelpolly** [comment]
+1

**Comment by alex-karo** [comment]
+1

**Comment by AKP-13** [comment]
+1

**Comment by darkc0der** [comment]
+1

**Comment by zavedyaev** [comment]
+1

**Comment by newsiberian** [comment]
Please, fix this asap

**Comment by servy** [comment]
+1

**Comment by meerimm1** [comment]
+1

**Comment by dementev** [comment]
+1

**Comment by noahgorstein** [comment]
+1

**Comment by turboDi** [comment]
+1

**Comment by nickberens360** [comment]
Same here
![image](https://user-images.githubusercontent.com/1283934/147362550-636dc78d-c1a6-4067-b519-11ab762a6d1c.png)

**Comment by ViniciusVaz** [comment]
+1

**Comment by victufell** [comment]
+1

**Comment by palloi** [comment]
+1

**Comment by utilscottquested** [comment]
+1

**Comment by victorccccc** [comment]
Sorry for the inconvenience, we've fixed this issue. Feel free to reopen if issue persists
