### ISSUE TITLE
Mount host machine's docker.sock to build container

### ISSUE THREAD

**Issue by MaralKay** [aws-amplify/amplify-hosting#665]
** Please describe which feature you have a question about? **
Custom Build Image

** Provide additional details**
We would like to mount the host machine's `/var/run/docker.sock` to the build container (from our custom build image), because we need the Docker daemon running in it. Is this somehow configurable in the Amplify console? Or we have absolutely no control over the container run's parameters? If not, I'd like to add this as a feature request as it can be an important point in a deployment pipeline..
Thank you!

**Comment by calavera** [comment]
We're never going to do this. It's a very serious security risk.
