### ISSUE TITLE
Incoming webhook fails to trigger for Wordpress.com webhooks

### ISSUE THREAD

**Issue by artchen** [aws-amplify/amplify-hosting#758]
** Please describe which feature you have a question about? **
Incoming webhooks

** Provide additional details**
Amplify's incoming webhooks did not trigger for Wordpress post/page updates (http://en.support.wordpress.com/webhooks/). However, the Netlify webhooks can be triggered correctly.

**Comment by artchen** [comment]
I noticed the CURL command has an extra query parameter "&operation=startbuild" than the URL. But adding the query parameter did not get it to work.

**Comment by artchen** [comment]
Hi is there update for this issue?

**Comment by abhi7cr** [comment]
Hi @artchen,

I will take a look and get back to you. Thanks for your patience.

**Comment by abhi7cr** [comment]
Hi @artchen,

Did the CURL command work directly from within a terminal ? Also, what is your appId and region?

**Comment by artchen** [comment]
Hi @abhi7cr,

Yes the CURL command works from terminal. Region is us-west-2, appId is dh5dx8bwj1njg (I got this from url, not sure if this is what you meant by appId).

**Comment by abhi7cr** [comment]
Yup that’s the appId. Thanks. I will take a look. Are there any logs from within WordPress for the failed invocations?

**Comment by artchen** [comment]
I don't have access to logs because wordpress.com is a managed service. You can probably try it out by creating a free account at wordpress.com and register an amplify web hook with publish_post or publish_page event. Then create/edit any post/page to verify if the web hook actually triggered.

I tried set up my wordpress site with both Netlify and Amplify web hook urls, the Netlify one can trigger build, that's why I think the issue wasn't on Wordpress' end. Perhaps there are some filtering happening at Amplify.

**Comment by artchen** [comment]
Hello, any update?

**Comment by abhi7cr** [comment]
Hey @artchen, 

Sorry for the delayed response. I was able to reproduce the above behavior. We will do some more investigation on our side to see why that's happening, and update you.

**Comment by artchen** [comment]
Sorry to be annoying, any update to this issue?

**Comment by abhi7cr** [comment]
Hello @artchen,

Since I was able to reproduce consistently, I went ahead and added a bug in our backlog to fix this issue. We will let you know once it's resolved. Thanks for your patience.

**Comment by jketcham** [comment]
Hi, is there any ETA on when this would be fixed or when there would be more information about the root cause? I'm running into this problem as well in considering whether or not to use AWS Amplify.

**Comment by artchen** [comment]
> Hi, is there any ETA on when this would be fixed or when there would be more information about the root cause? I'm running into this problem as well in considering whether or not to use AWS Amplify.
> 
> Edit: As a workaround, I created a lambda function that acts as my webhook.

Thanks for the tip 👍

**Comment by idkidm** [comment]
Why was this closed?
