### ISSUE TITLE
retry button doesn't work

### ISSUE THREAD

**Issue by juanitomint** [aws-amplify/amplify-hosting#836]
**App Id**: d2fvk319y3wfc7
**Region**: us-east-1
**Step**: Domain Activation
**Status**: Domain activation

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.
Button retry doesn't work

**Error message**
`globalnav-d717b3c6990cbb495eb90755479156d01ffb4e5b.gz.js:31 Refused to load the script 'https://phd.aws.amazon.com/phd/auth?state=hashArgs' because it violates the following Content Security Policy directive: "script-src https://d2ehysm26eepwv.cloudfront.net/ https://media.amazonwebservices.com/urchin.js https://d2q66yyjeovezo.cloudfront.net/ https://d1ge0kk1l5kms0.cloudfront.net/ https://d36w9x9zqjsko8.cloudfront.net/". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

d @ globalnav-d717b3c6990cbb495eb90755479156d01ffb4e5b.gz.js:31
main.js:41 Uncaught TypeError: Cannot read property '0' of null
    at r.getColor (main.js:81)
    at onLoad (main.js:81)
    at Object.r (main.js:41)
    at a (main.js:41)
    at Object.s [as executeDispatchesInOrder] (main.js:41)
    at h (main.js:41)
    at g (main.js:41)
    at Array.forEach (<anonymous>)
    at r (main.js:81)
    at Object.processEventQueue (main.js:41)
main.js:55 Refused to load the script 'https://console.aws.amazon.com/amplify/mode-mode.js' because it violates the following Content Security Policy directive: "script-src https://d2ehysm26eepwv.cloudfront.net/ https://media.amazonwebservices.com/urchin.js https://d2q66yyjeovezo.cloudfront.net/ https://d1ge0kk1l5kms0.cloudfront.net/ https://d36w9x9zqjsko8.cloudfront.net/". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.
got a session with technical support and couldn't resolve this issue either

**Comment by Athena96** [comment]
Hi @juanitomint where is the above error message being displayed on your end, are you inspecting the page and viewing the console logs?

**Comment by LeoLapworthKT** [comment]
I'm seeing similar - in the browser console  - when I view the build steps, I see the overview - when I click into a step I get the page nav (left and top) but then blank screen and this is the message in the console

**Comment by citrusoft** [comment]
I see similar issue in the AWS Organizations console of the Master account.
This causes the internal frame of the AWS Organizations console to render blank.
I detect this using the Firefox Web Developer Tools > Network Tab.
It's the only failed https request in the Organizations Console page view.

**Comment by juanitomint** [comment]
> Hi @juanitomint where is the above error message being displayed on your end, are you inspecting the page and viewing the console logs?

Yes in the amplify console

**Comment by ganipcanot** [comment]
Resolving due to age - if you are still experiencing this issue please re-open.
