### ISSUE TITLE
How to purge all files before deployment

### ISSUE THREAD

**Issue by ptrobert** [aws-amplify/amplify-hosting#93]
** Please describe which feature you have a question about? **

Hi we have implemented two new Custom headers we want to apply these headers to all the files,
However files which are changed are only being deployed and files which are untouched are being skipped while deploying
we need to purge all the previous files and re deploy every thing
Please let us know the workaround
** Provide additional details**

**Comment by calavera** [comment]
Custom headers are automatically added to all files that you have deployed, you don't have to purge all files anymore. I'm closing this issue as fixed.
